### ISSUE TITLE
Multiple gatling runs in single jenkins job?

### ISSUE THREAD

**Issue by cprice404** [gatling/gatling#1162]
I'd previously asked about this an in issue filed against the gatling jenkins plugin project.

It would be awesome if the Gatling jenkins plugin could find and archive multiple gatling reports from an individual jenkins build run, and graph them against one another in the trend graphs.  It appears that the trend graph widget already supports this, so it seems doable.

I started poking at the source code to see about submitting a pull request for this.  I found a pretty easy path forward as far as locating multiple reports after a build, making sure they are relevant to the current run, and archiving them.  However, it looks the next necessary step might be to change the definition of `GatlingBuildAction` such that it supports an array of simulations rather than an individual one.  Before I go too much farther down that path I was hoping to get a general sanity check to make sure that:
1. that sounds correct, and
2. you guys are interested in this idea and would be willing to consider merging something along these lines once all of the kinks are worked out.

Thoughts?

**Comment by ShettyA** [comment]
Hello, 
I am interested in using this feature of running multiple gatling runs and fetching separate reports via jenkins in a single test run. I am currently using the 1.0.3 plugin version of gatling-plugin with gatling-charts-highlights-2.0.0-M3a code base. 

On running test twice in single run, I do see two reports on clicking 'Gatling' via the specific jenkins build but both reports contains the latest run test report and I totally miss the first test report. Is there any specific configuration required that I am missing here?
