### ISSUE TITLE
Bundled samples no longer work [cloudfoundry classic has been shutdown]

### ISSUE THREAD

**Issue by berinle** [gatling/gatling#1251]
The bundled samples with the gatling distribution no longer work. This is because the old cloudfoundry has been shutdown as of today.

[Sample Banking Application](http://excilys-bank-web.cloudfoundry.com)

now returns a 404.

**Comment by wilsonmar** [comment]
http://excilysbank.gatling.cloudbees.net/
now shows this:
<img width="171" alt="http 404 apache tomcat" src="https://cloud.githubusercontent.com/assets/300046/14762067/df74ba54-092e-11e6-9ba4-9e1cd5aab4b2.png">
