### ISSUE TITLE
Core: Allow simulations to be run as tests

### ISSUE THREAD

**Issue by srirachapills** [gatling/gatling#1474]
As a user of Gatling libraries, I want to be able to run one or many simulations in an IDE and/or build system through the use of a testing framework. For example, support of a JUnit runner that is able to bootstrap Gatling engine and run tests would definitely boost productivity. Current state of the art (for me) is creating an Engine class in each of my test projects which contains plumbing to start Gatling. We then run this class, answer a few questions and have to look through the console for test status. A test runner of some sort who would handle a keep a single Gatling engine, reset it between simulations and use assertions properly for test status would be the general idea.

**Comment by slandelle** [comment]
Closing for now. I don't think there's any chance we investigate this any time soon.
