### ISSUE TITLE
Xpath doesn't handle HTML 5

### ISSUE THREAD

**Issue by japgolly** [gatling/gatling#1529]
xpath checks don't work with HTML5 because it isn't strict XML.

Specifically having an unclosed tag such as this on a page:

``` html
<link href="/css/application.css" rel="stylesheet" type="text/css">
```

causes the xpath check to die saying

```
[Fatal Error] :14:3: The element type "link" must be terminated by the matching end-tag "</link>".
16:15:13.085 [WARN ] i.g.h.a.AsyncHandlerActor - Request 'Login' failed : xpath.exists failed, could not prepare: Could not parse response into a DOM Document: The element type "link" must be terminated by the matching end-tag "</link>".
```

**Comment by Glamdring** [comment]
Please reconsider that recommendation: http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454

**Comment by slandelle** [comment]
Excerpts from our [official documentation](http://gatling.io/docs/2.1.7/http/http_check.html):

> XPath only works on well formed XML documents, which regular HTML is not (while XHTML is). If you’re looking for path expression for matching HTML documents, please have a look at our CSS selectors support.

Regarding regex for parsing HTML, yes, everybody knows this very funny SOF answer. But then, CSS selectors are no magic bullet. For example, how can you grab a given query parameter in the url of a link? You can't, CSS selectors only deal with DOM nodes, not text. Even the `contains` instruction was dropped in HTML5. You can fetch the url with a CSS selector, then use a regex. Some people will then prefer directly going with the dirty and brittle yet quick solution of using a regex.
