### ISSUE TITLE
Core: Support closed workload model

### ISSUE THREAD

**Issue by robzienert** [gatling/gatling#1647]
Support needs to be added for an injector similar to `scn.inject(constantUsersPerSec(5) to (100 users))` where a constant 5 users per second is injected, until there are 100 users with active sessions, at which point it will maintain 100 active sessions until the feeder is empty (or another criteria is met: `cUPS(5) to (100 users) until (10 minutes)`?).

Google discussion: https://mail.google.com/mail/u/0/?ui=2&shva=1#inbox/1442cdccaa64a114

// edit @slandelle: here's what the DSL will look like

```scala
scn.inject(
  constantConcurrentUsers(10) during(10 seconds),
  rampConcurrentUsers(10) to(20) during(10 seconds)
)
```

**Comment by theredcat** [comment]
@slandelle Actually, in real-world a customer often come to you with this question : "My marketing department say that we'll have to face X hits per seconds maximum because <web maketing obscure reason>. Can you ensure me we will handle that with our current infrastructure?"

**Comment by slandelle** [comment]
> My marketing department say that we'll have to face X hits per seconds maximum because [web maketing obscure reason]

Yeah, in real world, marketing department sometimes tries to play engineers, and then usually gets it wrong...

What you're looking for is a closed workload model. You can implement this by having your virtual users loop and reset their state: http://gatling.io/docs/2.1.7/http/http_helpers.html

**Comment by LuboVarga** [comment]
I see another use case. I have test scenario, where I need to prepare some data. It can be done in some maximal rate (exceeding this rate will drop some data). I would like to use something like `scn.inject(constantUsersPerSec(5) to (100 users))` to achieve given rate. Now I am simulating this behaviour by `splitUsers(100) into(constantUsersPerSec(5) during(1 seconds)) separatedBy(nothingFor(1 millisecond))`. The only issue is that splitUsers will not insert more than given number of users, so my number of users need to be exactly divisible by constant rate factor.

I think that similar behaviour can be achieved also by throttling, but my scenario cannot be throttled because of strict timeouts on server side.

**Comment by manish-panwar** [comment]
We have a use-case for this.

Our app serve traffic to mobile device. There are 2 types of requests, one is returned back right away, another is long pooled(basically sleeping on the request) at server for X amount of seconds.


So, we want a constant load for the requests that are long pooled at server for X amount of seconds. If I use constantUsersPerSec then it will keep adding the users/new-request irrespective of if server has returned the response. We want constant requests/users but with a ceiling, and test our app if it can handle it.

cUPS(5) to (100 users) until (10 minutes) fulfill our requirement completely. Right now I can't use Gatling with constantUsersPerSec. JMeter sucks, but seems like I have no choice.

**Comment by manish-panwar** [comment]
Actually I would call it as follows :

constantUsers(100 users) until (10 minutes)

Means keep 100 users(or request or connections) at any given moment until 10 minutes.

**Comment by mikpan** [comment]
+1

In our company we do like Gatling, its expressive DSL and numerous features! But one important feature is missing to ensure quality of service (QoS) for the API with Gatling. 

Typically, to ensure that QoS does not decrease we assume that there are N parallel open sessions and N users (a user per session) perform various or same operations according to the scenario. The only invariant in is the number of open sessions.

The number of open sessions (or simultaneously active users) is not just "marketing department" stuff. In case of API agreement it is often written in the contract and, for instance, if the service goes down the company will not be penalised for excessive user behaviour. The feature of fixing the number of "open sessions" (active users) would be very helpful to ensure quality of service for RESTfull API.

Now, considering solution to API testing with Gatling, the closest I can get is with throttling. Throttling allows to limit the number of simultaneous HTTP user requests. On the other hand it does not work for complex scenarios. Are there any plans to go  forward with this feature?

**Comment by slandelle** [comment]
Anyway, that's something we might consider for Gatling 3, as it would require to isolate open and closed workload models.

**Comment by slandelle** [comment]
Until now, wrap you scenario content with a loop and recycle virtual users and possibly [reset HTTP caches](http://gatling.io/docs/2.2.2/http/http_helpers.html#dealing-with-caching) in the loop.

**Comment by LGH** [comment]
@slandelle any functional examples on how this code would look?
