### ISSUE TITLE
HTTP: Add WebSocket server messages check

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#1650]
WebSockets server messages are received asynchronously, in a path different from the main HTTP one.

We need to provide checks on those, so that users can assert on those, but also capture data out of it.

Here's the design I propose:
- let one add checks on a WebSocket:
  - when opening it
  - when sending messages to the server
  - or even with a dedicated action
- let one clear checks on a WebSocket
- have a `reconciliate` action that would apply the checks on the accumulated messages and reconciliate with the main flow Session.

**Comment by ori-cohen** [comment]
@slandelle according to the latest documentation: http://gatling.io/docs/2.1.7/http/websocket.html it looks to me like reconciliation for a multi web-socket scenario is still not supported.
There is still no way to tell the reconciliate method on which open web-socket to work.
Am I missing something?

**Comment by slandelle** [comment]
@ori-cohen Your question doesn't seem related to this issue. Please use our Google Group for questions.
