### ISSUE TITLE
HTTP: Better embedded resources fetching strategy.

### ISSUE THREAD

**Issue by blemale** [gatling/gatling#1690]
Currently in the recorder the embedded resources fetching work as follow:
- We enable the `fetchHtmlResources()` on HTTP protocol definition with corresponding white/black list.
- We parse HTML body and retrieve embedded resources.
- We remove requests corresponding to retrieved embedded resources from the simulation.

However there are embedded resources we can't retrieve as image embedded in css, Ajax calls at page loading, and so on.

These resources are currently loaded sequentially in the generated `Simulation`.

We should find a better strategy in order to put these resources in a `resources` block and load them in parallel. However we have to deal with Ajax calls, long polling requests, and so on.

**Comment by slandelle** [comment]
Getting back to this after such a long delay, thanks for your patience :)

Actually, we have a very hard time delimiting "page" request and "resource" requests.
For example, `X-Requested-With` is completely optional, so one can hardly tell Ajax request appart. And even if we were to find a way, an Ajax request can be triggered by a user action and not on page load.
We currently use an empirical algorithm that tries to isolate fast chains of requests separated by longer pauses, and I fail to see a better one.
What I do want though is to isolate this transformation from an internal AST (similar to HAR) to the Simulation one and have it properly tested.

**Comment by slandelle** [comment]
Closing, there's not much we can do here.
