### ISSUE TITLE
Recorder: Reimplement HAR parsing on an AST instead of Dynamic

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#1722]
Would be much more simple for debugging + don't maintain own parser.

**Comment by slandelle** [comment]
I happened to stumble on a thing of beauty...

In [HarMapping](https://github.com/gatling/gatling/blob/2.2/gatling-recorder/src/main/scala/io/gatling/recorder/har/HarMapping.scala#L60):

```scala
val time = Try(entry.time.toLong).getOrElse(entry.time.toDouble.toLong)
```

Guess what? `toLong` is [not defined](https://github.com/gatling/gatling/blob/2.2/gatling-recorder/src/main/scala/io/gatling/recorder/har/Json.scala#L31-L33). Yet, the code compiles just fine, because the Dynamic synthetic method is called instead, crashes (as obviously the JSON object doesn't have to `toLong` field) and is recovered in `getOrElse`.

Lesson learnt: `Dynamic` is a dangerous crap that violates every type safely principles at the core of Scala and we must get rid of it and map to an AST.

**Comment by pdalpra** [comment]
Yup, dynamic typing at its best :/

**Comment by slandelle** [comment]
@pdalpra Hey man, IIRC, aren't you the culprit here ;-)

**Comment by pdalpra** [comment]
I am indeed... youthful mistake ? :)

**Comment by slandelle** [comment]
Lol is strong with this one.
[This on](https://github.com/gatling/gatling/commit/213a8782c16cd5d1dbe1698a744588a618db2c11#diff-efec041e5cc259eee9e2ba61a5c76208R35)e's on me.
