### ISSUE TITLE
HTTP: Support SOCKS proxies

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#1744]
Inspiration:
* https://github.com/shenfeng/async-http-client/blob/master/src/java/me/shenfeng/http/SocksHandler.java
* https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/socksproxy/SocksServerHandler.java

**Comment by slandelle** [comment]
No community demand.

**Comment by bcatarinoneoworks** [comment]
What's the status on socks proxy support? Supported now? Still unsupported? This would be very useful to me, as I can't access any non-local environment without it. Gatling is my tool of election but lack of socks support means I'd have to choose something else. Cheers

**Comment by slandelle** [comment]
Still unsupported. Lots of work yet very low community demand, hence very low priority. Only something we would do with a contract. Contributions welcome, then :)

**Comment by bcatarinoneoworks** [comment]
That's too bad :( but I understand the prioritization. Thanks for the quick reply anyway and thanks for building this fantastic tool. Really simple and works like a charm

**Comment by chin2here** [comment]
What's the status on socks proxy support? I wanted to hit amazon EC2 nodes with gatling which requires socks proxy.

**Comment by slandelle** [comment]
As demand for SOCKS proxy support is very scarce (~once a year), my feeling is the only way for this feature to land some day would be either to have it contributed by someone from the community, or have some company sponsor us from GatlingCorp to have it developed.

**Comment by gtycherry** [comment]
does gatling supports socks5 now? seems has been implemented , still not open-sourced?
