### ISSUE TITLE
Core: custom action with individual reporting 

### ISSUE THREAD

**Issue by pwielgolaski** [gatling/gatling#1898]
I have situation where I want to hide HTTP call (using .silent) and report time consumed by i.e. loop like asLongAs.

asLongAs(condition)(exec(action.silent).pause(x))

I made some custom wraper to make it possible to report time (just keep start time in session and latter report it)
I wonder if you see it convient for wider audience and we could add it to framework.
I think I could contribute it, probably doing it with actions rather what using simple sessionFunction.
Any idea about DSL?

report("actionname")(chain)

**Comment by slandelle** [comment]
The solution for this is to wrap the loop with a group.

**Comment by pwielgolaski** [comment]
I tried this and I dont see group when I have silent action in group.
When I make not silent, it is fine.
Is there a option to show all groups also "empty" if there is case that all requests are silent?

**Comment by slandelle** [comment]
@pwielgolaski Are you sure it's not that you're seing cumulated response time, and not group duration? If you think you've found an issue, could please open one and provide a reproducer.
This issue seems unrelated to me.
