### ISSUE TITLE
Illegal character exception with the Pipe character in Urls

### ISSUE THREAD

**Issue by florentbr** [gatling/gatling#1981]
Version: Gatling 2.0.0-M3a, JRE8

Description:
The Pipe character in Urls is throwing an exception whereas it's a valid character:
[ERROR] [06/25/2014 15:32:08.500] [GatlingSystem-akka.actor.default-dispatcher-2] [akka://GatlingSystem/user/$g]
Illegal character in dex 72: https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic|Roboto+Slab:400,700|Inconsolata:400,700
java.lang.IllegalArgumentException: Illegal character in query at index 72: https://fonts.googleapis.com/css?family=Lato:400,700,400itlic|Roboto+Slab:400,700|Inconsolata:400,700

Example of a valid Url throwing an exception:
https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic|Roboto+Slab:400,700|Inconsolata:400,700

**Comment by yoavm** [comment]
Hey,

Looks like there is no way to send decoded "|" in url using Java. 
Please let us know if encoded url agreed by the client.
Using curl or other technologies from the current DTS requires deep coding investment.

Yoav

**Comment by slandelle** [comment]
@yoavm AHC tries to conform to [RFC3986](http://tools.ietf.org/html/rfc3986). No idea what a DTS is.
