### ISSUE TITLE
Core: allow assertions to check group cumulated time 

### ISSUE THREAD

**Issue by ceeaspb** [gatling/gatling#2120]
following on from #2091, this is the feature request to allow the tester to check the cumulated time of a group. This is a typical use case for checking the response time of a web page.

not needed for 2.0

**Comment by slandelle** [comment]
I lost track on this.
Actually, 2.1 and 2.2 already check group cumulated time, not duration:
* 2.1: https://github.com/gatling/gatling/blob/2.1.X/gatling-core/src/main/scala/io/gatling/core/assertion/AssertionValidator.scala#L65
* 2.2: https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/assertion/AssertionValidator.scala#L59

**Comment by slandelle** [comment]
The default group metric is cumulated response time.
Since #2929, it's possible to switch to group duration, but that's a global switch.

**Comment by anyone-can-test** [comment]
Is it possible to assert group cumulated response time, in Gatling 2.2?
