### ISSUE TITLE
HTTP: add onSuccess and onFailure WebSocket check hooks

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2241]
For now, the idea is to be able to trigger sending messages to the server.
Being able to trigger whatever action would be way to complex, maybe not feasible with current implementation.
We have to cope with the fact that WebSocket state lives in a different path from main HTTP state and that state synchronization can only come from main branch.

example:

``` scala
exec(ws("Message")
  .check(wsListen.within(30 seconds).expect(1).message
    .onSuccess(ws("SendOnSuccess").sendText("Foo"))
    .onFailure(ws("SendOnFailure").sendText("Bar"))
  )
)
```

Of course, one can set checks and onSuccess/Failure messages on subsequent messages.
Just beware of callback hell.

**Comment by untra** [comment]
Is this feature still planned? Or will it eventually be rolled into #3071 ?
This is feature that I could use right about now 👍

**Comment by slandelle** [comment]
Nothing planned atm.

Then, we'd need some real world examples to consider this, and limit the scope.
Current architecture in not very suited for streams and state machines.

**Comment by rsareth** [comment]
Right now, I need to benchmark the scenario where 2 "virtual users" are in a chat session. One is sending messages and the other is just receiving. But with gatling, it seems that it is not possible to do that.

I really hope that it would be possible in the future.

Just by having this:
```
ws("Just received a message.")
            .check(wsListen.within(5 minutes).expect(1).message.saveAs("message"))
```
I have this error **Check didn't succeed by the time a new one was set up**

**Comment by slandelle** [comment]
@rsareth Cross virtual user transactions is in the FrontLine roadmap.

**Comment by slandelle** [comment]
Won't do for now
