### ISSUE TITLE
HTTP: improve per user keystore support.

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2293]
Currently, one has to create as many keystore files as virtual users, and the way of doing things is a bit hacky (magic name session attributes).

We should:
- [ ] have a way for also passing 1 single keystore containing multiple keys
- [ ] configure this through the HttpProtocol

**Comment by shreyas-agnihotri** [comment]
This issue hasn't been updated for a while now.

Is the functionality to just pass 1 keystore containing multiple keys targeted for any future release?

We are moving from JMeter to Gatling and this is holding us back.

**Comment by slandelle** [comment]
@shreyas-agnihotri 

No, there hasn't been any progress.
Feel free to contribute, or contract with us for implementing it.

**Comment by slandelle** [comment]
This feature request has been idle for a very long time. Closing for now.
