### ISSUE TITLE
Core: Parallel chains

### ISSUE THREAD

**Issue by BrandenPellucid** [gatling/gatling#2336]
Currently you can only do a set of parallel requests using `.resources`, but it would be nice if there was a way to do parallel chains.

Example:

``` scala
execParallel(
  exec(req1, req2),
  exec(req3, req4)
)
```

This can be useful in accurately performance testing more complex web-based libraries.

https://groups.google.com/forum/#!topic/gatling/khCqhYit0rw

**Comment by aleksz** [comment]
This gets more important when you test apps with JS front end.
In my case, back end is a set of REST APIs. APIs are called by JS in quite random ways. Sometimes button click triggers multiple parallel requests. Testing those requests in series means that we will not notice concurrency issues in those requests. Also load profile becomes different.

**Comment by lvic** [comment]
Hi, one big vote for the top level async request.

It would be great, if Gatling could provide such a feature. With it Gatling would clearly stand out from the rest of load testing tools, as testing multiple parallel requests per user isn't really possible in other tools.

More and more applications provide APIs to use different clients (like desktop version, mobile client, web access, etc) for accessing apps content. These clients may send parallel (async) requests to provide different information in one view. If someone has to test these views, he has to create his own tool for that.

Could you provide information on what is needed to get this feature accepted? What may be needed for top level async requests? How can we help?

**Comment by slandelle** [comment]
@lvic You can help for 2 things:

* API/DSL design: we need more feedback to properly design one that suits most users
* implementation: here, my answer might surprise you, but the best way to help is to convince your company to purchase some support from us.

**Comment by francoisledroff** [comment]
This would also be helpful to get this to simulate a mix of http REST and websocket calls.
But I guess I'll give `.resources` a try too.
http://gatling.io/docs/2.0.0-RC2/http/http_request.html#resources

**Comment by zmoshansky** [comment]
A few use cases that this would really help enable:
- Simulating simultaneous uploads (1 user uploading multiple files)
- Allow fetching resources that need to use a feeder

Perhaps using a DSL like the following:
```
private def singleUpload(userIDs : IndexedSeq[Record[String]]) : ChainBuilder = {
        feed(userIDs)
            .exec(http("Check Session Data Range")
                .post("/images")
                .body(ElFileBody("${userID}")
            )
 }

...

val userIDs = csv("usersFixture.csv").records
scenario("Parallel Uploads")
  .execParallel(
    exec(singleUpload(userIDs)),
    exec(singleUpload(userIDs)),
    exec(singleUpload(userIDs))
)
```

In my use cases, this entire scenario would then be run concurrently with 10's, or 1000's, of different users.

**Comment by henning77** [comment]
This feature would enable me to test websocket / http interaction.
My use case is that I have a websocket server which interacts with both http/rest and websocket clients.

What I would like to do:
```
execParallel(
  // http flow sends requests which get routed by the server to websocket clients
  exec(http("send request")
                .get("/request")
                .check(jsonPath("$[0].answer").is("hello"))

  // websocket flow answers requests. The server sends them back to the http clients
  exec(ws("wait for request")
             .check(wsAwait.within(10).until(1).regex("...").saveAs("request")))
    .exec(ws("send answer")
            .sendText("""{"answer": "hello"}"""))         
)
```

I would not mind if each parallel flow would have its own separate session if that makes things easier.

**Comment by ralfe** [comment]
Hi,
any news on this feature?
The usecase described by @zmoshansky is exactly my current problem I'm struggling with:
```
scenario("Parallel Uploads")
  .execParallel(
    exec(singleUpload(userIDs)),
    exec(singleUpload(userIDs)),
    exec(singleUpload(userIDs))
)
```
This would be awesome!

**Comment by slandelle** [comment]
> any news on this feature?

No. Maybe something we'll work on for Gatling 3.

Parallel HTTP single requests would be pretty doable. Parallel flows would be much more complicated, not sure if they will ever be a thing.

**Comment by mmiglier** [comment]
Any update on this feature? We would really need a way to execute a number of parallel requests according to a previous json response

**Comment by slandelle** [comment]
@mmiglier There hasn't been any external contribution on this, and we're really swamped atm. Contributions/sponsoring welcome.
