### ISSUE TITLE
Metrics: OpenTSDB DataWriter

### ISSUE THREAD

**Issue by EricKWLee** [gatling/gatling#2395]
Would love to have a DataWriter that is capable of doing asynchronous metrics emissions to OpenTSDB similar to how Graphite is supported. I love Graphite, but as a company, ended up setting up and storing a lot of historical metrics inside of OpenTSDB already and cannot move.

Features:
* TCP would be great since it has less overhead per payload.
* Configurable Metric Root and Tags
* Per second timestamp resolution

**Comment by slandelle** [comment]
Not a priority and no community demand (user no longer replies).
