### ISSUE TITLE
Doc: Include some example for custom protocol

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2466]
Ex: https://github.com/softmentor/gatling-examples

**Comment by mnogu** [comment]
:+1:

**Comment by holub** [comment]
@slandelle Do you have any solutions for: https://github.com/softmentor/gatling-examples/issues/1

**Comment by slandelle** [comment]
We don't have a public API for building custom protocol supports atm, as things are not stable there atm. And we don't plan to any time soon:
* there's tons of things we want to experiment, for example for improving performance
* we don't want to be stucked for implementing new official protocol supports, typically HTTP/2, because of bad design choices that we can't reconsider because we've released an API

Atm, not being able to implement a protocol support by yourself (like some people did with AMQP, Kafka, CQL, etc) is probably a good sign that you shouldn't. Either don't, or consider contracting with us so we can help you building and maintain it when internals change.

**Comment by holub** [comment]
That's really sad. But thank you for the clear and detailed answer!
