### ISSUE TITLE
Maven Plugin: GatlingMojo.simulations() returns all scala files when simulationClass isn't defined

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2481]
The problem is that it scans the source directories.

It should be scanning the compiled binaries directory, convert file names to class names, load the directory into a ClassLoader, and look for classes that extend from Simulation.

**Comment by pdalpra** [comment]
Note : We could simply reuse SimulationClassloader that does exactly what is suggested.

**Comment by slandelle** [comment]
Absolutely :)

**Comment by pdalpra** [comment]
There is, however, a small issue with that : This would conflict with the `includes` and `excludes` options…

**Comment by slandelle** [comment]
Why? Just that they should be applied AFTER compiling and target only Simulation classes and be class names instead of file names.

**Comment by pdalpra** [comment]
Should we allow to filter Simulation class names using regexes ?
For excluding whole packages, for example.

**Comment by slandelle** [comment]
Baby steps. Let's have full names for a starter.
