### ISSUE TITLE
bodyString.is RawFileBody

### ISSUE THREAD

**Issue by johnyUA** [gatling/gatling#2486]
I tried to compare json response using gatling,
https://gist.github.com/johnyUA/ff74be49780781017721

but I am receiving such error

10:24:08.563 [GatlingSystem-akka.actor.default-dispatcher-4][WARN ][AsyncHandlerActor.scala:127] i.g.h.a.AsyncHandlerActor - Request 'Address Types Get Paged Result' failed: bodyString.find.is({
    "offset": 0,
    "limit": 20,
    "count": 2,
    "resources": [
        {
            "id": 1,
            "name": "Реєстрації",
            "abbrName": "реєстр.",
            "uri": "/addresstypes/1"
        },
        {
            "id": 2,
            "name": "Поштова",
            "abbrName": "пошт.",
            "uri": "/addresstypes/2"
        }
    ],
    "uri": "/addresstypes"
}), but actually found {
  "offset" : 0,
  "limit" : 20,
  "count" : 2,
  "resources" : [ {
    "id" : 1,
    "name" : "Реєстрації",
    "abbrName" : "реєстр.",
    "uri" : "/addresstypes/1"
  }, {
    "id" : 2,
    "name" : "Поштова",
    "abbrName" : "пошт.",
    "uri" : "/addresstypes/2"
  } ],
  "uri" : "/addresstypes"
}

**Comment by johnyUA** [comment]
I think it's issue, because I don't found a way to compare my string json

**Comment by slandelle** [comment]
You're comparing Strings, ie each character matter. But one one side, you have:

```
"uri": "/addresstypes/2"
}
]
```

while on the other you have:

```
"uri": "/addresstypes/2"
}]
```

So there's an extra CR in your "expected.json" file.
