### ISSUE TITLE
Metrics: deploy our own Docker containers

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2491]
* Graphite + Graphana
* InfluxDB + Graphana

This way, people could start playing with our Graphite integration in no time.

**Comment by slandelle** [comment]
@pdalpra WDYT?

**Comment by pdalpra** [comment]
Good idea :)
I'll work on it !

**Comment by slandelle** [comment]
Mr non-core topics ;)

**Comment by adrianlewis** [comment]
Also, would it be a good idea to provide Grafana JSON in order to provide a sample dashboard?

**Comment by slandelle** [comment]
@adrianlewis Yes, good idea, we could do that for standard metrics. Per request metrics have the name of the request.

**Comment by adrianlewis** [comment]
@slandelle The dashboards can be scripted (to avoid hardcoding) but not looked into that yet.
http://grafana.org/docs/features/scripted_dashboards/

**Comment by pdalpra** [comment]
@slandelle I'd prefer Mr not only core topics :)
@adrianlewis Will have a look.

**Comment by slandelle** [comment]
> I'd prefer Mr not only core topics :)

I'd prefer too ;)

**Comment by DaveBlooman** [comment]
#2494 Here is a variation of what we are using in BBC-News

**Comment by pdalpra** [comment]
@slandelle Still relevant ?

**Comment by slandelle** [comment]
I don't think so.

**Comment by pdalpra** [comment]
Closing the issue.

**Comment by aidylewis** [comment]
I think it would add to the attraction of Gatling if sample out-of-the-box persistence and real-time graphing was provided.

**Comment by pdalpra** [comment]
Well, there are already good Docker images for Grafana and Graphite/InfluxDB, we could link to those to provide an easy setup of a monitoring stack. 
Having our own Docker images  is one more thing that we'd need to actively maintain, and we already have more than enough work to keep use busy :)

**Comment by aidylewis** [comment]
This is what I am using:
```sh
docker run -d -p 8081:8081 --name grafana aidylewis/grafana
docker run -d \
           -p 8083:8083 -p 8084:8084 -p 8086:8086 -p 2003:2003 \
           -e PRE_CREATE_DB="gatling;grafana" --name influxdb davey/influxdb:latest
```

Most of the work here was done by @DaveBlooman

**Comment by pdalpra** [comment]
Just to check : are those images forks of tutumcloud [InfluxDB image](https://github.com/tutumcloud/tutum-docker-influxdb) and [Grafana Image](https://github.com/tutumcloud/tutum-docker-grafana) ?

**Comment by aidylewis** [comment]
The base image for InfluxDB derives from a tutum image: https://github.com/DaveBlooman/gatling-docker/blob/master/influxdb/Dockerfile#L1

And the grafana image is an install on a base Debian distro: https://github.com/DaveBlooman/gatling-docker/blob/master/grafana/Dockerfile#L1

My grafana docker, only overrides the default.json: https://github.com/aidylewis/grafana-docker

It may be an alternative to link to those images you suggest but provide a gatling default.json.
