### ISSUE TITLE
Doc: non-existing method disableUrlEncoding

### ISSUE THREAD

**Issue by mnogu** [gatling/gatling#2497]
The document says that we can use ``.disableUrlEncoding``,
> If you know that your urls are already properly encoded, you can disable this feature with ``.disableUrlEncoding``.
http://gatling.io/docs/2.1.2/http/http_protocol.html

but we can't compile the following file:
```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class BasicSimulation extends Simulation {
  val httpConf = http.baseURL("http://example.com").disableUrlEncoding
  val scn = scenario("Scenario Name").exec(http("request_1").get("/"))
  setUp(scn.inject(atOnceUsers(1)).protocols(httpConf))
}
```

Here is the error message:
> value disableUrlEncoding is not a member of io.gatling.http.config.HttpProtocolBuilder

**Comment by Stringsy** [comment]
Might want to update the docs to reflect this btw.

**Comment by slandelle** [comment]
It is documented: http://gatling.io/docs/2.1.3/http/http_protocol.html#urlencoding

**Comment by slandelle** [comment]
Actually, I realize the proper name should indeed be `disableUrlEncoding`.
Will revert back.
Sorry for that.
