### ISSUE TITLE
Unknow option -df / --data-folder

### ISSUE THREAD

**Issue by gh0zt** [gatling/gatling#2500]
Calling gatling.sh with the option -df yields following error. Tried 2.1.2 and 2.2.0-SNAPSHOT.

```
gatling.sh -sf /project/gatling/simulations --data-folder /project/gatling/data

GATLING_HOME is set to /Tools/gatling
Warning: Unknown option --data-folder
Warning: Unknown argument '/project/gatling/data'
```

**Comment by pdalpra** [comment]
This is only a warning emitted by the compiler, which can safely be ignored.
Will fix so these warnings do not show up anymore.
