### ISSUE TITLE
runtime parameter --simulations-folder doesn't work

### ISSUE THREAD

**Issue by fkowal** [gatling/gatling#2511]
tl;dr
-sf and --simulations-folder do not work

i am using gatling-charts-highcharts-bundle-2.1.0-SNAPSHOT
i have gatling/bin in my PATH
i do:

cd project
gatling.sh -s TestName -m -rd RunName -sf $PWD/src/test/scala/gatling

TestName.scala is a Simulation file that exists in the above directory
but it's not found

**Comment by slandelle** [comment]
What's the full class name of TestName.scala's content? It is TestName, or `gatling.TestName`. Are you sure that `TestName` isn't actually in the `gatling` package?

**Comment by pdalpra** [comment]
This has been fixed by #2455.
Please upgrade to Gatling 2.1.2 at least.
