### ISSUE TITLE
nested try blocks with the same name

### ISSUE THREAD

**Issue by jmdcal** [gatling/gatling#2517]
I made the mistake to create two try blocks with the same name, this crashed the gatling.

**Comment by slandelle** [comment]
What do you mean by `try` blocks? There's a `tryMax`, but it doesn't take a name. And how did Gatling crash? Did you get an exception?

**Comment by jmdcal** [comment]
Something like this , I can provide a real test case next week.

    tryMax(1, "try") {
        repeat(1, "repeat") {
           tryMax(1, "try") {
             repeat(1, "repeat") {
               exec(blah)
            }
         }
      }
    }

**Comment by slandelle** [comment]
Ah, OK, you forced the loop index name.
Then, I don't think there's anything we can do about it, sorry. When you don't let Gatling define them, you're on your own. For example, you could as well override it with a feeder content, or a check, etc.
