### ISSUE TITLE
Jenkins plugin does'nt visualize old simulations after upgrading to Jenkins 1.597

### ISSUE THREAD

**Issue by henriwi** [gatling/gatling#2527]
After upgrading to the latest Jenkins (1.597) I have som issues with the Jenkins gatling plugin, and that is that it does'nt seem to find old simulations. If I go in to a specific gatling simulation build, there is no gatling-button there (in the left menu), and it seems like the plugin is not able to find and visualize the simulation. If I run a new build everything works as expected.

My first thought is that this has something to do with the new JENKINS_HOME layout that Jenkins has implemented in the latest version (see https://wiki.jenkins-ci.org/display/JENKINS/JENKINS-24380+Migration and https://issues.jenkins-ci.org/browse/JENKINS-24380 for more information).

On the server, all the simulations seems to lie there, and the new folder structure has been implemented by Jenkins.

**Comment by pdalpra** [comment]
Closed by https://github.com/jenkinsci/gatling-plugin/pull/9
