### ISSUE TITLE
Jenkins plugin causes CSS layout problem when chart is rendered.

### ISSUE THREAD

**Issue by meteorfox** [gatling/gatling#2543]
Since upgrading to Jenkins 1.597 the plugin doesn't render properly. 

Here's a screenshot:
![projectscreenshot](https://cloud.githubusercontent.com/assets/232300/5984222/d5dfdaf6-a899-11e4-87a9-a729dad5ddfc.png)

**Comment by slandelle** [comment]
Looks like a duplicate of #2527.
Great move, Jenkins!

**Comment by pwielgolaski** [comment]
it seems that I was able to fix it check pull request https://github.com/jenkinsci/gatling-plugin/pull/9

**Comment by pdalpra** [comment]
Fixed by jenkinsci/gatling-plugin/pull/9
