### ISSUE TITLE
Core: Remove static singletons

### ISSUE THREAD

**Issue by mauaht** [gatling/gatling#2558]
Gatling currently makes extensive use of static singletons. The most significant consequence of this is that it limits test execution to a single simulation per JVM instance through singletons in Scala objects such as GatlingSystem, GatlingConfig (see issue 2327), Controller, Throttler, CssExtractor, DataWriter, AsyncHandler, HttpEngine, etc. This limits opportunities for embedding Gatling in other applications, such as distributed load testing built on Gatling, and also makes automated testing of Gatling components and different Gatling configurations difficult.     

Removal of static singletons will overcome these issues. 

A possible solution is as follows:
- Move all Gatling code within the context of a root AKKA ActorSystem and implement Gatling wide singletons within an AKKA Extension. Akka Extensions are singletons managed by the AkkaSystem and are created either on demand, when first accessed from code, or on startup via a config file entry. Extensions have access to the entire AkkaSystem and the config used to create it.
- Move all test run specific singletons into a test run specific actor that is the root for all actors associated with that test run. Any descendent actor can recover a reference to this run specific actor by following the chain of parent entries in the ActorContext provided to each actor when it is created. Alternatively, the Gatling extension could maintain a list of active test runs. This way data for each test run is issollated from all other test runs. The Gatling extension above should support management of multiple test runs, each with its own directory tree. 

A Scala application can have any number of ActorSystem instances, each with its own Gatling extension, based on different com.typesafe.config instances. For testing and demo purposes this approach can be used to set up a cluster of ActorSystem instances on a single JVM with each instance using a different port for the AKKA remoting endpoint.  

The above solution would address issue 2327 and remove obstacles to resolution of issue 415.

**Comment by slandelle** [comment]
I've removed GatlingConfiguration mutable singleton (actually, there's now one in core.Predef as it was the only place to pass it to the Simulation and dependencies without breaking everything, but it's only used there, not internally).

The next step is to remove the ActorSystem singleton: create it in the app layer, and pass it to the whole build chain. I have to admit I don't currently see a point in using the Extension API.

Then, all this work is for improving testability. I only see problems with JVM recycling.
