### ISSUE TITLE
App: stop commenting gatling.conf entries

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2559]
Quite often, people don't realize they have to remove the leading `#` when editing this file.
Actually, we could leave the entries as is and don't comment them when generating this file.

**Comment by adrianlewis** [comment]
I think in JMeter config (e.g. system.properties), commented out lines indicate default values.

**Comment by slandelle** [comment]
After more thinking, I realize this is a bad idea.

If we were to make people always overriding the properties, people who upgrade Gatling by just upgrading the jars without upgrading the conf file wouldn't be notified of default values changes.
