### ISSUE TITLE
Facing issue with Feeders

### ISSUE THREAD

**Issue by munagoti** [gatling/gatling#2560]
i am facing an issue with the response body.

the request is like this : {"referenceText1":"free","referenceText2":"","referenceText3":""}

i have changed to : .body("""{"referenceText1":"${text}","referenceText2":"","referenceText3":""}""")

in place of test i am just pumping texts.  : .feed(csv("EditText.csv").circular)

unfortunately this request is getting failing .please help me.

**Comment by slandelle** [comment]
Please use the Google Group for asking questions. And please follow the rules there.
