### ISSUE TITLE
java.lang.IllegalArgumentException when response headers contain multiple set-cookie statements

### ISSUE THREAD

**Issue by martinkovacik** [gatling/gatling#2565]
Response with these headers

HTTP/1.1 302 Found
Date: Mon, 16 Feb 2015 22:54:17 GMT
Server: Jetty(9.0.7.v20131107)
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Cache-Control: no-cache, no-store
Location: http://localhost/xxxx
Content-Length: 0
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 15-Feb-2015 22:54:17 GMT
JSESSIONID=1qh36eruk199b1byit8zz1igxe;Path=/;HttpOnly
rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 15-Feb-2015 22:54:17 GMT
Set-Cookie: NSC_TMAA=xyz;Path=/;expires=Wednesday, 09-Nov-1999 23:12:40 GMT
X-XSS-Protection: 1; mode=block
x-content-type-options: nosniff
X-Frame-Options: deny
Vary: User-Agent
Keep-Alive: timeout=5, max=82
Connection: Keep-Alive

cause java.lang.IllegalArgumentException: invalid version format: SET-COOKIE

Note the multiple Set-Cookie headers (it is perfectly valid according to RFC spec)

**Comment by slandelle** [comment]
Could you provide the version of Gatling you're using please?

**Comment by martinkovacik** [comment]
Of course sorry for that: 2.1.4

**Comment by slandelle** [comment]
And the full stacktrace?

**Comment by martinkovacik** [comment]
I'll replicate my scenario and send the stack trace.

**Comment by slandelle** [comment]
Could you provide a pointer to where in RFC6265 is having multiple cookies inside a same Set-Cookie is valid, please? It seems to me [it's not](http://tools.ietf.org/html/rfc6265#section-4.1.1):
>   set-cookie-header = "Set-Cookie:" SP set-cookie-string
 set-cookie-string = cookie-pair *( ";" SP cookie-av )

I think you're referring to RFC2965 that's obsolete.

**Comment by slandelle** [comment]
AsyncHttpClient will silently ignore the second cookie is the first Set-Cookie header (I think modern browsers will do the same).

I suspect the issue is something else and probably has to do with broken HTTP messages.

**Comment by martinkovacik** [comment]
I'm referring to RFC2109 which is obsoleted by newer RFC2965. You are right RFC2965 doesn't allow multiple cookies in one set-cookie header. This is not a Gatling bug.
