### ISSUE TITLE
generate summarized html report

### ISSUE THREAD

**Issue by matankatz** [gatling/gatling#2573]
Hi,

I am trying to run a simulation using 50,000 request with 100 users concurrent.
It means that there are total of 50,000 * 100 = 5,000,000 requests.
The html report generated is extremely heavy, weighting over 20GB.

is there a way to make more summarized html report, without generating html file for each request?

Thanks,
Matan

**Comment by slandelle** [comment]
Could you please use our [Google Group](https://groups.google.com/forum/#!forum/gatling) for questions?

Also please take care of providing all the required information.
