### ISSUE TITLE
HTTP: Group Cumulated Response Time doesn't account for WebSockets

### ISSUE THREAD

**Issue by JamieTabone** [gatling/gatling#2574]
Hi, 

I am running a small load test using websockets. I have a group with separate requests inside. In the results generated, the response time for each separate request in the group is visible while the accumulated response time is being set to 0.

Following is part of the code:

``` scala
.group("UserConnecting"){
         exec(ws("OpenConnection").open("/uname=${currentUser}")wsAwait.within(30)).exitHereIfFailed
         .exec(ws("GetInitialPresenceCount")
            .sendText("""{"messageType": "getInitialPresenceCount", "username": "${currentUser}"}""")
            .check(wsAwait.within(30).until(1).regex("""\{.*"messageType":"connectionStarted".*\}""")
            ))
          .exec(ws("TellOthersImOnline")
            .sendText("""{"messageType": "tellOthersImOnline", "username": "${currentUser}"}""")
            .check(wsAwait.within(30).until(1).regex("""\{.*"messageType":"presenceCountIncrement","username":"${currentUser}".*\}""")
            ))
        }.pause(360)
    .exec(ws("BeforeClosing")
```

The graphs generated for the cumulated response time is as follows:

![capture](https://cloud.githubusercontent.com/assets/6746603/6252506/38ce1938-b79b-11e4-913e-8f8f635624b0.PNG)

Then if I go to one of the requests which are part of the group response time is not 0 (For example the following shows the result for the open connection request).

![capture1](https://cloud.githubusercontent.com/assets/6746603/6252523/4f194988-b79b-11e4-86b2-ad393348601e.PNG)

**Comment by JamieTabone** [comment]
Do you think that this issue will take long to solve because I am very tight with my dissertation and I really depend on this?

Thanks

**Comment by slandelle** [comment]
No plan yet.
If you're really in a rush, consider [purchasing support](http://gatling.io/#/services).

**Comment by slandelle** [comment]
This is no longer an issue with Gatling 3 WebSocket support.
