### ISSUE TITLE
Recorder: export to HAR

### ISSUE THREAD

**Issue by cprice404** [gatling/gatling#2580]
Hi,

Would it be possible to provide an option that would allow the recorder to export the recorded simulations to a more parseable format, e.g. JSON?

We're looking into automating some recordings as part of a certain CI job, and would really like to do a little post-processing on the recording before saving it out to Scala.  So, for example, give the individual requests a meaningful name based on matching a regex against their URL, etc.

So, what I was thinking is: if the object model for a recording in memory is pretty well-known, perhaps it would be possible to:
- Have the recorder export the objects as JSON rather than Scala
- Run our own code to do some transformations on the JSON
- Read the JSON back in to the original object model
- Finally, save it back out as Scala that we can use to run actual simulations

Without having looked at the code that exports the recordings to Scala, it seems like this might not be all that difficult to implement?

If this doesn't sound like a completely crazy idea or an insane amount of work, I might hack on it at some point in the future.  Curious to hear what you think.

**Comment by slandelle** [comment]
This looks like super user specific to me.
We plan on refactoring the recorder so we properly isolate the AST generation and rendering phase, so users can plug their own renderer, but there's quite a lot of work and no ETA.

**Comment by cprice404** [comment]
That's totally fair about it potentially being user-specific.  No worries.

It sounds like your goals w/rt separating the AST and rendering would line up with what I'm interested in doing, though.  Do you have any notes on your planned implementation for that?  It's something I might be interested in hacking on and submitting PRs if you thought that that would be tractable.  I'd obviously want to do that in a way that lined up with your plans, was testable, etc., but it is something I'd be interested in helping with if it was possible for me to do so.

**Comment by slandelle** [comment]
Hi Chris,

So you're done with your config ruby port and are looking for a new challenge? ;)

I'm very very very busy at the moment, so I could find the time to dig into this myself, and won't probably any time soon. So yes, contribution would be very welcome.

Here's what I had in mind:
* Define a proper raw model for the proxy mode.
* Define a common final AST model for the proxy and HAR modes
* Define clear rules to transform the raw proxy model into the HAR mode:
  * request/response pair (current way is ugly)
  * rules for telling appart top level requests and resources (hard, mostly empiric, so we should isolate them so we can properly test)
* Define an AST to Simulation rendering model
* Make this rendering model pluggable

Once we have that, we could go even further, and have algorithms to suggest response checks / request parameterization / correlation.

As you can see, quite a bit of work...

**Comment by cprice404** [comment]
Not quite done with the config port, but, you know... close enough to where I need to have the next thing mapped out :)

Thanks for the bullet points.  It'd probably be a month or so before I would end up with some hack time but those bullet points sound like things that could be worked on as a series of incremental PRs.  So, I'll probably bug you with some more specific questions if I get a chance to hack on it.

Thanks!

**Comment by slandelle** [comment]
Sure, any time!

**Comment by cprice404** [comment]
@slandelle this is still on my wish list and I'm hoping to get some time to start digging into it, maybe in the next month or so.  Anything on your list above that has changed significantly since my original inquiry?

**Comment by slandelle** [comment]
@cprice404 No, nothing changed since then. Just that IMO, we should aim for an AST based on HAR. But then, I wonder what HAR looks like for HTTP/2 (haven't investigated myself yet).

**Comment by slandelle** [comment]
Closing for now.
I don't see this feature to ever become a requirement for us (from GatlingCorp), so this feature could only be contributed. And I suspect dedicated proxy tools, such as CharlesProxy, would do a better job.

**Comment by AntonioSun** [comment]
Came here for the same reason, since the ticket was open almost ten years ago, let me double-check, so 
 is Recorder never be able to export to HAR, or it is available later on? thanks.
