### ISSUE TITLE
Doc: wrong writers format in conf sample in realtime monitoring page

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2590]

**Comment by gempesaw** [comment]
Oh, huh, I was actually trying to say that the quoted format worked for me, _not_ the list format. Maybe it's because I'm using an older version of gatling ? Should I expect the behavior to change at some point? 

```
# plugins.sbt
addSbtPlugin("io.gatling" % "gatling-sbt" % "2.1.0")
```

also thanks gatling is awesome :D

**Comment by pdalpra** [comment]
This will change in Gatling 2.2, we'll move to the list format.

We used that quoted format  to circumvent a limitation in one of the third party libraries we're using, and that limitation has been dropped since then.

**Comment by gempesaw** [comment]
Ah, excellent! Thanks for the explanation.
