### ISSUE TITLE
HTTP: SSE blocking check does not stop after timeout

### ISSUE THREAD

**Issue by ctranxuan** [gatling/gatling#2591]
Hello,
With the following example:

```scala
package org.tests.gatling.sse

import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._

class NewProxySimulation extends Simulation {
  val httpConf = http
  .baseURL("http://my-sse-server.com")

  val scn = scenario(this.getClass.getSimpleName)
  .exec(sse("sse").open("/app/stockmarket/prices")
                .check(wsAwait.within(10).until(1).regex("""event(.*)"""))
    )
           .exec(sse("close").close())
  setUp(scn.inject(rampUsers(1) over 1)).protocols(httpConf)
```
the simulation does not timeout as long as the SSE server does not send at least one SSE event.

**Comment by slandelle** [comment]
Hi @ctranxuan 

What's your SSE implementation? It seems to me that the server should reply ASAP with the HTTP status code instead of waiting for the first message.

Do you have a reproducer?

**Comment by slandelle** [comment]
Some information for the world renown expert @jfarcand, such a behavior might crash some Firefox. Atmosphere sends a white space payload in such a situation.

@ctranxuan Could you share a reproducer, please?

**Comment by jfarcand** [comment]
@ctranxuan Which server is acting like that BTW?

**Comment by ctranxuan** [comment]
Apologizes, it might be an issue in our side: the SSE message sent was messy. I need to confirm with our QA that the message is the origin of our issue or not.
But at first sight, we thought it came from the Gatling SSEHandler. In the meantime, I had some issue in using a patched version of Gatling (some maven resolution stuff, I assume), so I come back to you once I get the QA feedback (it might take a week: I am not in our office for this period of time).

**Comment by ctranxuan** [comment]
Hello,
We check with our QA: it was indeed an issue with the SSE streams that was not well formatted.
The issue can be closed and the PR rejected.

Apologize for this mess.

**Comment by slandelle** [comment]
No pro, thanks for your feedback!
