### ISSUE TITLE
rampUsers(X) over(Y) is constant and not ramping

### ISSUE THREAD

**Issue by philippsander** [gatling/gatling#2599]
While developing, i noticed that when I use `rampUsers(500) over(2 minutes)` my active rises pretty fast in the beginning, stays at a certain rate and then dropps fast at the end

I would expect it to rise (linear) over time, but thats not the case.

tested with the BasicSimulation

**Comment by slandelle** [comment]
You're confusing injection, i.e new users creation rate, and active users that accounts for users that died.

**Comment by philippsander** [comment]
ok. thanks for clarifying

**Comment by slandelle** [comment]
See http://gatling.io/docs/2.1.4/general/timings.html#active-users
