### ISSUE TITLE
Core: Provide a "streaming" CSV reader

### ISSUE THREAD

**Issue by pdalpra** [gatling/gatling#2602]
There are cases where users are loading massive CSV files as feeders for their simulations.
Currently, as CSV feeders are loaded eagerly to avoid file IO during the simulation, users may require huge heaps so that the data can fit in memory.

An alternative could be to read CSV files in small batches, which would trade memory usage for some file IO when a new batch is read.

**Comment by slandelle** [comment]
linked to #3174
