### ISSUE TITLE
HTTP: Query parameters passed to request in reversed order.

### ISSUE THREAD

**Issue by BlazingPhoenix** [gatling/gatling#2607]
I have some performance tests on old gatling 2.0.0-M4-NAP, after I had updated it to newest version 2.1.4 I observed that some tests failed. During investigation I found that HTTP query parameters on new gatling passed in reverse order.
Minimal code example that illustrates the issue presented below:
```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class TestParametersSimulation extends Simulation {
  val httpConf = http.baseURL("http://computer-database.herokuapp.com")

  val scn = scenario("Test parameters order")
    .exec(http("request")
      .get("/")
      .queryParam("param1", "1")
      .queryParam("param2", "2"))

  setUp(scn.inject(atOnceUsers(1)).protocols(httpConf))
}
```

Request built by Gatling looks like:
```
GET /?param2=2&param1=1 HTTP/1.1
Connection: keep-alive
Host: computer-database.herokuapp.com
Accept: */*
```

In code param1 precedes param2 but in the request we observe opposite case.

**Comment by slandelle** [comment]
Fixed.

But then, this is not really a bug. You really shouldn't depend on the query params order, there's nothing in the HTTP specs that guarantees it.

**Comment by slandelle** [comment]
Also note that 2.0.0-M4-NAP wasn't deployed by us, but by the Net-a-Porter people, so we have no idea what's in there.

**Comment by BlazingPhoenix** [comment]
Thanks a lot, great work! :)
