### ISSUE TITLE
Gatling plugin - Multiple Simulation trigger Reports not added to view due to difference in timestamp

### ISSUE THREAD

**Issue by hanumanthan** [gatling/gatling#2608]
Hi,

We are triggering **multiple** simulations from a job and using gatling plugin to track those simulations. (Enable simulation tracking is checked in the config). Few simulations are not being tracked by the plugin. Dug into the code and found that the simulation results are added if the *last modified time is greater than the build start time*.

Attached a typical case where the last modified time is lesser than the build time though not sure why is it happening.
Jenkins version - 1.570
Gatling plugin version - 1.1.0
Would like to know the reason for the check of modified time and build start time and is it possible to get away with that.

![build_starttime](https://cloud.githubusercontent.com/assets/5584802/6634243/1ea82a5c-c97b-11e4-956b-8aed44ce918e.png)
![build_success_report](https://cloud.githubusercontent.com/assets/5584802/6634249/3da77f2a-c97b-11e4-8790-52421b995e20.png)
![report_stats](https://cloud.githubusercontent.com/assets/5584802/6634251/524ceea6-c97b-11e4-8fe6-3ffe51e128a3.png)

**Comment by pdalpra** [comment]
Are you running your simulations on a slave ? 
If so, it looks that your master and slaves clocks syncs are not synced : if I read correctly, you have a 13 seconds (!!!!) gap between your master clock and slave clock.

**Comment by hanumanthan** [comment]
Thanks mate. I adjusted the clock and verified it for few days. Simulations are getting tracked.

**Comment by pdalpra** [comment]
Glad that it could solve your issue :)
