### ISSUE TITLE
Order of JSON paramters appears to matter for JSONPath

### ISSUE THREAD

**Issue by Vinnl** [gatling/gatling#2625]
Let's say we have the following JSON:

    { "store": {
        "book": "In store"
      },
      "street": {
        "book": "On the street"
      }
    }

Using JSONPath, the expression `$.store` should return the store object (`{book: "In store"}`). This works fine in Gatling.

Likewise, `$.street` should return the street object (`{book: "On the street"}`) - at least, that's what happens [in this online tester](http://jsonpath.curiousconcept.com/). In Gatling, however, this only appears to work when `street` is the first value in the root object.

Unless I'm misunderstanding, that's not how it should work, right?

**Comment by slandelle** [comment]
I just added a test with your sample and Gatling works fine as expected: 6917d596906a16cdc85b4e1ac1abe6762c2da76c

It looks like a problem on your side.

**Comment by slandelle** [comment]
If you can provide a reproducer, feel free to ping so I can reopen.

**Comment by Vinnl** [comment]
Hmm, then I'm probably doing something wrong somewhere else. Sorry to have wasted your time...

**Comment by slandelle** [comment]
What does your check look like exactly? Are you trying to extract a String, or an object(ie a Map)? If the former, beware that white spaces are stripped. If the latter, beware that you have to use `ofType` (see test).

**Comment by Vinnl** [comment]
It should extract a string:

      .check(jsonPath("$.productType")
        .saveAs("productType"))

It says:

    jsonPath($.productType).find(0).exists, found nothing

Considering my current grasp of Gatling and Scala, I'm probably doing something stupid somewhere, so thanks for the pointer - I'll do some more reading :)

**Comment by slandelle** [comment]
That's probably more a usage issue. Lower logging level in logback.xml and Check that your response is indeed the JSON payload you expect.
