### ISSUE TITLE
JMS: add support for receive timeout

### ISSUE THREAD

**Issue by soudmaijer** [gatling/gatling#2626]
Would it be possible to add support for setting a receive timeout for JMS reqreply actions.

Possibly somewhere here:

https://github.com/gatling/gatling/blob/master/gatling-jms/src/main/scala/io/gatling/jms/JmsReqReplyAction.scala#L68

Maybe I will contribute when I have some spare time.

**Comment by slandelle** [comment]
Yes, contribution would be very welcome! :)

**Comment by slandelle** [comment]
Backported on 2.1.

**Comment by soudmaijer** [comment]
Awesome! Thanks!
