### ISSUE TITLE
Upgrade SBT 0.13.8

### ISSUE THREAD

**Issue by pdalpra** [gatling/gatling#2631]
Drop usage of aether-deploy plugin, in favor of the new built-in Maven Resolver

**Comment by slandelle** [comment]
To be properly tested before breaking everything...
I think I also read a discussion with Twitter/Pants people saying that namehashing wasn't working properly.

**Comment by pdalpra** [comment]
Tested by releasing a snapshot (cleaned up right after the tests), worked without issues.
Will wait to see if those issues are confirmed.
