### ISSUE TITLE
Core: Better support for writing functional specs

### ISSUE THREAD

**Issue by constantijn** [gatling/gatling#2638]
Copy from https://groups.google.com/forum/#!topic/gatling/_BqDQFxXKz8

---------

On my project we're building a REST API and when it comes to testing we use ScalaTest for most of the unit tests, however at the end of the day we also want to know our API works properly and we decided to use Gatling to write some functional specs against our API.

It works quite well for this purpose but i had to deal with a couple of gotchas (by default failed tests don't fail the build, SBT plugin had a bug that i already submitted a fix for etc.) 
In the end after abstracting away all the boilerplate into the GatlingFunSpec class my tests ended up looking something like this:

```scala
class StuffHandlerTest extends GatlingHttpFunSpec {

  override val baseURL = "http://localhost:7654/api"
  override val httpConf = super.httpConf.header("MyHeader", "MyValue")

  spec {
    http("GetAll")
      .get("/stuff")
      .check(stuff exists)
  }

  spec {
    http("GetStuffFromCountryToCountry")
      .get("/stuff/NL/NL")
      .check(stuff.count is 1)
      .check(fromCountry is "NL")
      .check(toCountry is "NL")
  }

}

object StuffHandlerTest {

  def stuff = jsonPath("$.stuff")
  def fromCountry = jsonPath("$.stuff[0].fromCountryCode")
  def toCountry = jsonPath("$.stuff[0].toCountryCode")

}
```

Would you guys be interested in a pull request for my GatlingFunSpec implementation? I realize it's nothing new per se, but it would make it quite a bit easier for people to get started writing functional tests using Gatling.

It would require some cleaning up from it's current implementation but I'd be happy to do it (write tests, a manual page,blog post, etc.) and submit a pull request if this seems interesting to you.

Constantijn Visinescu

**Comment by constantijn** [comment]
I have a first implementation ready. I'd like to nail down the implementation first before I start writing docs and submitting pull requests ;)

https://github.com/constantijn/gatling/compare/master...constantijn:gatling-funspec

I have two questions to the devs:

What would be the correct module to implement this functionality in?

gatling-main would make the most sense because that's where the simulation class this is based on lives, but it doesn't have access to gatling-http. gatling-http would sorta make sense, but I'm not sure it belongs there. I have it in gatling-testframework now which makes most sense namewise, but rightnow it only contains classes realted to the sbt testframework implentation

How would you like me to write a test for this?

I tried looking at the test for the Simulation class it's based on, but I noticed it doesn't have a test ;) I could add the GatlingPlugin to the sbt file so it actually runs the really basic test I provided (probably coupled with using your http mocking framework instead of using example.com) but I figured I'd ask before I start messing with your build ;)

**Comment by slandelle** [comment]
> What would be the correct module to implement this functionality in?

I think we should have some base class in core, then some extensions in each module.

Either `GatlingFunSpec  with HttpSpec` or `GatlingHttpFunSpec`.

> How would you like me to write a test for this?

At least some class that checks that it compiles fine, like `HttpCompileTest`. For historical reason, the Simulation design makes it hard to test.

**Comment by constantijn** [comment]
Made a pull request with the first implementation that includes the suggestions Stéphane made above.

Any comments on the implementation? I made a snapshot build of gatling and it works great for my own project :)

**Comment by slandelle** [comment]
I added a few comments.

Then, could you please add a new documentation page in the [General](https://github.com/gatling/gatling/tree/master/src/sphinx/general) section?

**Comment by constantijn** [comment]
Addressed your comments with fixes and made an example project here:
https://github.com/constantijn/gatling-funtest-example
(HEADS UP: It depends on a 2.2.0-SNAPSHOT version built off off this pull request)

I'll go take a look at the documentation pages now

**Comment by constantijn** [comment]
Documentation page added, anything else? :)

**Comment by slandelle** [comment]
squash and rebase :)

**Comment by constantijn** [comment]
Done

**Comment by slandelle** [comment]
Merged, thanks!
