### ISSUE TITLE
Not able to resolve ELFileBody using Gatling 2.2.0

### ISSUE THREAD

**Issue by felixgao** [gatling/gatling#2648]
I am new to gatling  and I have a simple simulation but not able to resolve ELFileBody when using 2.2.0 version of gatling.
/gatling/gatling-charts-highcharts-bundle-2.1.4/user-files/simulations/PostThenPatch.scala:26: not found: value ELFileBody
11:58:13.088 [ERROR] i.g.c.ZincCompiler$ -           .body(ELFileBody("post.json")).asJSON

```
import io.gatling.core.feeder._
import scala.concurrent.duration._
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

 val createProfile =
        http("Create")
          .post("/entities")
          .header("Content-Type", "application/json")
          .body(ELFileBody("post.json")).asJSON
          .check(bodyString.transform(rawId => rawId.substring(1, rawId.length - 1)).saveAs("id"))
```

The simulation is executed as gatling.sh -sf user-files -s PostThenPatch and my GATLING_HOME is set as  /Users/felix/Programs/gatling and it is a simlink to 
/Users/felix/Programs/gatling -> gatling-charts-highcharts-bundle-2.2.0-SNAPSHOT

Thanks for all the help.

**Comment by pdalpra** [comment]
1. Please read the [Guidelines](https://github.com/gatling/gatling/blob/master/CONTRIBUTING.md) : the issue tracker is for bugs/features, not questions. Ask first on the mailing list, then open an issue here if it' indeed a bug.
2. Typo : It's ElFileBody, not ELFileBody.

**Comment by slandelle** [comment]
@pdalpra ELFileBody was renamed into ElFileBody in 2.2.0.
@felixgao If you're new to Gatling, you'd better no go with undocumented upcoming versions and stick to the released stable ones.

**Comment by baritom** [comment]
Typical of the documentation. I had the exact same problem and spent HOURS trying to fix it. If ELFilebody was renamed to ElFilebody, why hasn't the doc been updated. Lame.

**Comment by slandelle** [comment]
Well, well, well... Let's see:
* [Documentation updated](http://gatling.io/docs/2.2.3/http/http_request.html?highlight=elfilebody#request-body)? checked
* [Renaming mentioned in the migration guide](http://gatling.io/docs/2.2.3/migration_guides/2.1-to-2.2.html?highlight=elfilebody#elfilebody)? checked

Conclusion: you could have saved HOURS if you had read the doc. Guess who's lame?

**Comment by baritom** [comment]
Yeah, thanks for changing it after it was pointed out that it wasn't updated. I looked through the documentation for hours, trying to figure it out, it was always the previous.

**Comment by slandelle** [comment]
Right... https://github.com/gatling/gatling.github.io
