### ISSUE TITLE
Update the documentation to reflect the changes made in the latest test refactoring

### ISSUE THREAD

**Issue by pdalpra** [gatling/gatling#2652]
https://github.com/gatling/gatling/pull/2649

**Comment by slandelle** [comment]
What do you have in mind here?

**Comment by pdalpra** [comment]
There is a documentation page which lists our test helper classes and
objects.
Since tests have been refactored, this page needs to be updated to reflect
those changes.

**Comment by slandelle** [comment]
> There is a documentation page which lists our test helper classes and
objects.

Really?
