### ISSUE TITLE
HTTP: status code stats

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2663]
Myself, @DaveBlooman and @PoornimaGunisetti would be interested in the stats engine pushing extra data to the graphite protocol, specifically HTTP error codes which currently appear in stdout.

**Comment by slandelle** [comment]
@aidylewis I just pushed status codes Graphite support on a branch. Will implement in standard reports too before merging.

**Comment by aidylewis** [comment]
This looks really good. We all very much appreciate it.

**Comment by DaveBlooman** [comment]
Great work, looking forward to this.

**Comment by slandelle** [comment]
Done in commercial product
