### ISSUE TITLE
Graphite: Add mean and std dev metrics

### ISSUE THREAD

**Issue by mhettema** [gatling/gatling#2670]
Hi,

Currently, not all available timing metrics are sent to graphite.
The HTML report contains details regarding min, max, mean, std dev, and four configurable percentiles. 
The details sent to graphite contains the min, max, and the percentiles. 
Would it be possible to also include the mean and std dev in the information sent to graphite?

Thanks!
Marius Hettema

**Comment by slandelle** [comment]
Willing to contribute? ;)

**Comment by aidylewis** [comment]
I'll need to add additional metrics, I'll look into it and submit a PR.

**Comment by aidylewis** [comment]
It looks like I can retrieve the max and stdDev as attributes from the GeneralStats case class, but not sure how this ties into the GraphiteDataWriter object?

**Comment by pdalpra** [comment]
They are not related at all: GeneralStats is only used by the FileDataReader, which's in charge of reading the simulation.log to produce the HTML reports.
The GraphiteDataWriter computes its metrics in realtime, as soon as the Actions log info to it : https://github.com/gatling/gatling/tree/master/gatling-metrics/src/main/scala/io/gatling/metrics/types

**Comment by aidylewis** [comment]
I am trying to work back from the various send methods in GraphiteDataWriter (not sure which one I should be looking at (sendRequestMetrics, sendMetricsToGraphite, sendMetrics), and I am unsure where the metrics are actually coming from (Metrics, GraphiteData).

**Comment by slandelle** [comment]
Actually, I really wonder if that's a good idea to promote mean and standard dev usage. I mean those are pretty useless with real world distributions.

**Comment by aidylewis** [comment]
Aren't percentiles enough? A mean could be meaningless with a high standard deviation and if you give someone a mean with a standard deviation is that any better? However, they are in the HTML reports - and maybe they shouldn't be.

**Comment by slandelle** [comment]
Yep, I think that's the only pro... :)

**Comment by slandelle** [comment]
@aidylewis I was doing some changes there, so I just shipped this too.
