### ISSUE TITLE
push mean, std deviation and error codes to graphite. 

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2671]
linked to this:
https://github.com/gatling/gatling/issues/2670
https://github.com/gatling/gatling/issues/2663

**Comment by aidylewis** [comment]
treat them as two separate issues. apologies.

**Comment by slandelle** [comment]
Mean and std dev are pretty straightforward. Status codes aren't.

**Comment by aidylewis** [comment]
OK, I'll take Mean and std dev.
