### ISSUE TITLE
Metrics: Support Graphite pickle protocol

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2678]
Inspiration: https://github.com/irmen/Pyrolite/blob/master/java/src/net/razorvine/pickle/Pickler.java

**Comment by slandelle** [comment]
@pdalpra To be tested ;)

**Comment by slandelle** [comment]
Reverting, #2681 is way more simple and still very efficient.

**Comment by cgallinaro** [comment]
Can you recall why this feature was reverted?  Was simplicity the only reason?  My load testing infrastructure would benefit from pickle support.  I can fork and re-implement, but I wanted to ensure there weren't additional problems with the pickle implementation.
