### ISSUE TITLE
Metrics: support proper path format for InfluxDb 0.9

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2679]
http://influxdb.com/docs/v0.8/advanced_topics/schema_design.html#schema-design

**Comment by DaveBlooman** [comment]
What is the current state of native influxdb support?

**Comment by slandelle** [comment]
No plan atm. We'll provide a Grafana datasource for our upcoming commercial product.

**Comment by aidylewis** [comment]
What were you planning to do @DaveBlooman?

**Comment by slandelle** [comment]
Discarding, as we have FrontLine now
