### ISSUE TITLE
Doc: Improve documentation for cached pages usage

### ISSUE THREAD

**Issue by colinux** [gatling/gatling#2683]
Hi,

I think an important information is missing in the documentation: when a page is cached, the request is not performed, but any check is **silently ignored**. So not only an user would think the checks are okay, but also any extraction / saveAs does not work with cached pages.

I spent 3 hours to understand this behavior, so maybe it could help someone else in the future.

**Comment by slandelle** [comment]
It's all open source, feel free to contribute: https://github.com/gatling/gatling/tree/master/src/sphinx/http
