### ISSUE TITLE
App: bring back "--binaries-folder" CLI option

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2689]
It seems that the `--binaries-folder` was lost. But it covers a perfectly valid use case (have a share read-only Gatling install and override directories), and it's documented and possible with the maven archetype.

**Comment by aleksz** [comment]
I think there is a mistake in that commit,     
```
opt[String](BinariesFolder)
      .foreach(props.sourcesDirectory)
```

it setting sources directory

**Comment by slandelle** [comment]
Argh!
Thanks!

**Comment by slandelle** [comment]
Fixed, thanks!
