### ISSUE TITLE
Add HttpActionInterceptor to be able to debug HTTP requests

### ISSUE THREAD

**Issue by siman** [gatling/gatling#2691]
I would like to be able to intercept HTTP request in order to debug what I am going to send via HTTP. So I implemented ActionInterceptor. Let me know what do you think about this idea.

https://github.com/siman/gatling/commit/e503ab5a4fc1606ede53d2c187ac81e846d34640

P.S. I haven't written any tests yet.

**Comment by slandelle** [comment]
@siman Sorry for the late answer (vacation).

I'm not very fond of this, that looks more like a hack than a feature.
Do you know that you can have HTTP requests and responses in the logs, when you lower the logging level?
