### ISSUE TITLE
Core: Let one pass authentication header to JsonFeeder

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2692]
Main class to modify: https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/feeder/JsonFeederFileParser.scala

**Comment by blemale** [comment]
I'm in to take this issue !

**Comment by blemale** [comment]
Which kind of API would you expose ?

Something like: ```def jsonUrl(url: String, authenticationHeader: String)(implicit jsonParsers: JsonParsers)``` ?

**Comment by slandelle** [comment]
@blemale Is this something you need, or an issue you picked in order to contribute? I mean that somebody asked for this once, and I never heard about it again, so I'd rather not bring a feature that nobody would need/use.

If we were to have this, I'd rather go with the same design as request auth: http://gatling.io/docs/2.1.7/http/http_request.html#authentication

**Comment by blemale** [comment]
@slandelle, I just pick an issue with "Please contribute" tag.

**Comment by slandelle** [comment]
Someone's feeling his Scala rusty before quitting for a new Scala dev position? :stuck_out_tongue_winking_eye:

If you want to implement this one, I think this feeder json w/ url should move to the http module so it can reuse some AHC utils for the header computation.

**Comment by blemale** [comment]
Do you have another more useful issue to unjam my scala skills ?

**Comment by slandelle** [comment]
Actually, could you please first tackle this one? I have some ideas, but I have to first finish some other tasks so you can build upon.

**Comment by williamassoni** [comment]
Hello guys, I came from the future just to ask one question, I couldn't found in the documentation anything about this feature, it's that possible to call json feed using some sort of authentication like oauth2?

did you get this feature?

Thanks

**Comment by slandelle** [comment]
The idea was dropped because of lack of interest. Feel free to contribute.
