### ISSUE TITLE
Maven archetype: resources are missing

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2698]
They are here in 2.1.2 and 2.2.0-M2, but not in 2.1.5.
@pdalpra Any idea?

**Comment by pdalpra** [comment]
I'll check what could have happened ASAP.

**Comment by slandelle** [comment]
@pdalpra The only commit on the maven archetype between 2.1.2 and 2.1.5 is bumping the Scala version.

I suspect a release process change that caused the conf files extract and copy (from the bundle) to have failed.

**Comment by pdalpra** [comment]
Quite possibly.
But that would also means that the resources are missing from the bundle
too...

**Comment by slandelle** [comment]
I see that maven archetype 2.1.5 was released against gatling 2.1.2: https://github.com/gatling/gatling-maven/blob/2.1.X/pom.xml#L53

I think this prop should be removed and the archetype version aligned against the gatling one.

**Comment by pdalpra** [comment]
Oh crap...

**Comment by slandelle** [comment]
Ah ah ah.
Found it, that's indeed the versions: https://github.com/gatling/gatling-maven/blob/master/gatling-highcharts-maven-archetype/pom.xml#L180

**Comment by slandelle** [comment]
I say we drop the `gatling.version` prop and use `project.version` everywhere.
I don't expect to ever release the maven modules without release main gatling first.

WDYT?

**Comment by pdalpra** [comment]
And that's why automated releases are good :)

**Comment by pdalpra** [comment]
We can't: when executing the release:prepare goal, the version is still a
SNAPSHOT one and Maven the release is aborted.
But this won't really be a concern for releases done with gatling-build ,
since this step is automated and can't be forgotten.
