### ISSUE TITLE
2.1.5 Cheat Sheet Page has invalid links

### ISSUE THREAD

**Issue by rwwarren** [gatling/gatling#2699]
Cheat sheet page has invalid navigation links:
http://gatling.io/docs/2.1.5/cheat-sheet.html

Download, Documentation and Professional Services links don't work

**Comment by slandelle** [comment]
@notdryft This one's for you ;-)

**Comment by slandelle** [comment]
@notdryft I fixed the links on the generated pages, but I'll let you fix upstream.

@rwwarren Thanks for reporting!

**Comment by pdalpra** [comment]
Closed by d7ac5d6
