### ISSUE TITLE
HTTP: check for saving HTML form inputs

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2703]
Would ease passing back forms with already populated values. cc @Skeebl 

Could be based on Jodd/Css selectors.
Would fail if form can't be found.
Would save a `Map[String, Any]` where value could be `String` or `Seq[String]` (multivalues).

**Comment by Skeebl** [comment]
We can either save a Map[String, Any] or a Map[String, Option[Any]]. I depends on whether we want to save every field or only fields with values (excluding unchecked checkbox / radio).

<select> are a little tricky when it comes to default values as, if there is no "selected" value, a monovalued select takes its first option as default value.

We might also want to handle HTML5 input types. 
<input type="date"/> return a Date ... 
<input type="number" -> Double
That would induce greater complexity, but would allow direct manipulation on the extracted data.

**Comment by slandelle** [comment]
> We can either save a Map[String, Any] or a Map[String, Option[Any]].

No. What we want is what will be sent over the wire, ie `foo=`, hence an empty String.

> We might also want to handle HTML5 input types. return a Date ... 
Double

No, we want to focus on Strings, as that's what will be sent over the wire. If one wants more complex types, he'll have to manually convert.

**Comment by Skeebl** [comment]
Can users easily get a Map (field name) -> (complete html) ? They will need context to convert.

**Comment by slandelle** [comment]
> They will need context to convert.

Why?

**Comment by Skeebl** [comment]
Well, if they need a single conversion, that's fine without any context. They know the name of the field to convert, and they should know how to convert it.

I thought that, if they needed a mass conversion, they might need the type of the field or the min/max attributes. I'm actually struggling to find a use-case for such a thing.

**Comment by slandelle** [comment]
over engineering ;-)

**Comment by slandelle** [comment]
If you want "context", grab the full text body with a `responseBody` check and parse yourself in a `transform` step.
