### ISSUE TITLE
Core: Rewrite Injection model

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2706]
It would be great if:
* the number of users was not static, so we could have ways for changing the injection in real time
* ~~the number of users was just an estimate, so we could use ThreadLocalRandom instead of Random~~

**Comment by aidylewis** [comment]
> the number of users was not static, so we could have ways for changing the injection in real time

This is something traditional load-testers ask for quite a lot. Is this something that could be changed from the REPL? JMeter reads a changed integer from a file, but this seems a bit clunky.

**Comment by slandelle** [comment]
The first step I have in mind is to support mutable InjectionSteps. This would also help implementing closed model first class support. But my mind isn't set yet.

> JMeter reads a changed integer from a file, but this seems a bit clunky.

Well, you need some sort of IPC, so that's the easiest way and it doesn't rely on any external dependency. You don't want to set up redis just for this ;-)

**Comment by slandelle** [comment]
Will be controlled from the product interface/API.
