### ISSUE TITLE
Doc: Document how to set up an IDE for Gatling

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2708]

**Comment by aidylewis** [comment]
This will give you a basic Scala development environment that includes Vim, Tmux and SBT.
https://github.com/aidylewis/basic-scala-env.

If you also clone the gatling-sbt-demo project you should be ready to run.

**Comment by pdalpra** [comment]
Well, vim is not exactly an IDE... :)

**Comment by slandelle** [comment]
What I have in mind in a central page mentioning:
* IDE set up: Eclipse, IntelliJ
* Text editors such as SublimeText
* SBT set up
* Bootstrappers such as the maven archetype and the demo projects

**Comment by aidylewis** [comment]
In my opinion it would be worthwhile to document all the major editors. Derek Wyatt who wrote 'Akka Concurrency" uses Vim and Scala. I could add documentation on Vim and Emacs.

**Comment by slandelle** [comment]
Cool

**Comment by aidylewis** [comment]
What OS' are we thinking about? GNU/Linux and OSX?

**Comment by aidylewis** [comment]
I have started the documentation with Vim. 
https://gist.github.com/aidylewis/80fd794edc5cc2072249

**Comment by slandelle** [comment]
Done as of 81332b371aa962ff7036141aab4fa98cf495aa7b
