### ISSUE TITLE
Core: Target JDK8

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2709]
We have to decide when to drop JDK7 support that has reached EOL.
As Gatling is a load test tool where performance is a must, and modern JVM always bring performance improvements (such as G1), we already recommend using JDK8 anyway.

Some of our dependencies have already switched or plan to:
* Typesafe config (as of 1.3.0, already released): https://github.com/typesafehub/config/tree/v1.3.0#binary-releases
* Scala 2.12: http://scala-lang.org/news/2.12-roadmap

**Comment by pdalpra** [comment]
Note: Scala 2.11.7 will introduce the ability to use JDK8's `LambdaMetaFactory` to generate lambdas : https://github.com/scala/scala/pull/4463
This could bring (possibly huge) performance and memory usage improvements.

**Comment by slandelle** [comment]
Dependencies available in Scala 2.12 (current is 2.12.0-M2):
* []   scala-swing
* []   scala-xml
* []   scala-parser-combinators
* []   akka-actor
* []   fastring
* []   scopt
* []   scala-logging
* []   jsonpath
* []   boopickle
* []   redisclient
* []   scalatest
* []   scalacheck
