### ISSUE TITLE
Core: Have a ofType for css selector checks too

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2716]
So we could return a Node instead of a String.

**Comment by kleini** [comment]
I solved it by parsing the full body with the parser used internally in Gatling:
    .check(bodyString.transform(content =>
        ( for {
            node <- new NodeSelector(new LagartoDOMBuilder().parse(content)).select("your css selector")
          } yield {
            // Do whatever you need with your node
          }
        )
      )
    )

**Comment by slandelle** [comment]
Yep, this is the current workaround, thanks for documenting.

The new construct has the advantage of building the DOM tree for you and directly hand the selected nodes, so you only have to deal with the "Do whatever you need with your node" part in a transform step.
