### ISSUE TITLE
HTTP: Make HttpProtocol.localAddress take an Expression

### ISSUE THREAD

**Issue by abhigogna** [gatling/gatling#2725]
Need ability to submit requests with different IP address.
Load balancer can then route traffic to different servers instead of one. 
Needed in situations where server configuration is sticky IP.

Google group https://groups.google.com/forum/#!topic/gatling/-pSV27DMvE0

**Comment by slandelle** [comment]
Setting this as "Low Hanging Fruit" can could easily be contributed.

Then, as said on the Google Group, this is not really a blocker as it's possible to pass to setUp the same scenario injected with different protocols.
