### ISSUE TITLE
Doc: Move sample url

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2727]
http://computer-database.gatling.io

**Comment by aidylewis** [comment]
I am doing a demo of Gatling with this site, this afternoon, and I wondered if you could not deploy this afternoon?

**Comment by slandelle** [comment]
We'll be taking the app deployed on Heroku beginning of June, when their new pricing model will be enabled. Until then, http://computer-database.herokuapp.com will keep on working.

http://computer-database.gatling.io is restarted once a night to flush the database updates.
