### ISSUE TITLE
JMS: Don't wait forever for listener threads to join

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2745]
No idea why, but it was reported on the Google Group that threads are stalled there with Oracle AQ.

**Comment by soudmaijer** [comment]
I will test this on monday! Thanks for now!

**Comment by Nonius** [comment]
I've tested [this](https://github.com/gatling/gatling/tree/5a7a921fe4889bae61ed1bef65485ad304f009fa) commit. It works.

**Comment by slandelle** [comment]
@Nonius Thanks for your feedback!
