### ISSUE TITLE
Doc: Warn when browsing an old version

### ISSUE THREAD

**Issue by Vinnl** [gatling/gatling#2751]
I often reach Gatling's documentation through search results. However, since the current version is included in the URL, references on the internet to the documentation refer to the documentation of a specific version. When I come across that reference at a later time, the documentation could be outdated.

Therefore, it would be useful to add a banner to the top of the page of documentation on previous Gatling versions, with a link to the latest documentation (preferably taking you straight to the up-to-date version of the documentation you're currently watching).

**Comment by slandelle** [comment]
@notdryft IMO, the only way to do that is to load such a link dynamically in javascript. We shouldn't republish a version that's been already published.

Thoughts?

**Comment by slandelle** [comment]
@notdryft We really have to tackle this one. We have ppl referencing old versions on the mailing list several times a week :(

**Comment by notdryft** [comment]
Sure, need to time to spend on the site !

On Thu, May 19, 2016 at 8:40 PM, Stephane Landelle <notifications@github.com

**Comment by GabrielPlassard** [comment]
Hi, I think I could have a look if you wish
