### ISSUE TITLE
Recorder: Request Body saved as Response Body

### ISSUE THREAD

**Issue by TheCopycat** [gatling/gatling#2757]
Hi,

After some testing with the recorder, when checking "Save & check response bodies", it seems that the content of the *_response.txt file is the request body (the same as the *_request.txt file) instead of the response body.

I'm running gatling 2.1.5 highcharts bundled on Windows 7.

Thank you for your help.

**Comment by slandelle** [comment]
@TheCopycat Thanks for reporting!
