### ISSUE TITLE
Requests get dropped silently when logging to file

### ISSUE THREAD

**Issue by macarenomarco** [gatling/gatling#2773]
# Environment
Ubuntu 14.04
Gatling 2.1.6
Connected through ssh
## Plugins
SBT Gatling Plugin 
SBT version 0.13

# Steps
Ran simulation with ~200,00 reqs in under 10 minutes 

# Problem
When outputting to stdout a *significant* (about half) amount of requests get dropped and there's no mention of them in the report.

## Workaround
If the output is redirected to a file or to /dev/null requests get sent as (I think) they should.

Other than that, great tool, and it's been loads of fun getting to use it.

**Comment by slandelle** [comment]
Hi @macarenomarco 

Sorry, but this doesn't make sense and I'm having a hard time believing it.
Are you sure you're not just experiencing [caching](http://gatling.io/docs/2.1.7/http/http_protocol.html#caching)?

**Comment by macarenomarco** [comment]
Hello, sorry for the delay.

Allthough I'm not using the disableCaching method, I don't think this is the case. However, here is a gist which can reproduce the issue.

https://gist.github.com/macarenomarco/3c204bb005b7d18746bb

And a link to the reports (with logs included) of the same simulation ran with the following commands (I'm using the Gatling SBT Plugin):

```sh
sbt "testOnly TestSimulation"  # For the stdout example
sbt "testOnly TestSimulation" > /dev/null # For the redirected example
```

https://drive.google.com/file/d/0B4Qz01H8lFpfQjJFUTZOTHZ2NGc/view?usp=sharing

And if it helps I ran it from an
EC2 c4.4xlarge (16vCPUs / 30GB RAM / enhanced networking ) Amazon Instance

**Comment by slandelle** [comment]
OK, so by "Requests get dropped silently", you mean that throughput is way lower when console output is enabled on your EC2 instance. What goes in there? Stdout sure is slow, by default, Gatling only logs a few lines every 5 seconds, so that shouldn't be an issue. Are you sure you're not logging in DEBUG level?

**Comment by macarenomarco** [comment]
Yes, the expected amount of requests are pretty far from the actual requests, and there's no message (or I couldn't find one) inside the logs that indicate that a request wasn't made for external reasons, and that gave us misleading info. Also, the Gist is a minimal working example, the actual simulations with which we found this behavior are slightly more elaborate.

About the DEBUG level, I'm running Gatling mostly on vanilla settings, the only different setting is:
```sbt
javaOptions in Gatling += "-Dsun.net.inetaddr.ttl=0"
```
So unless the logging is in that level by default, I'm not.

**Comment by slandelle** [comment]
Honestly, the only sane explanation is that stdout is dead slow on your EC2 instance. You should ask AWS support.
Then, feel free to disable the console DataWriter in gatling.conf. That's quite a common set up for production anyway.

**Comment by slandelle** [comment]
Oh wait, do you mean the logged count is different from what you actually experienced and measured with this set up???

**Comment by macarenomarco** [comment]
Actually the server experiences the same load that Gatling reports. However, when logging to stdout the load on the server is significantly lower, which means that the requests are never made.

**Comment by slandelle** [comment]
Ok, so that really means stdout is foobar on your platform. The reason is for you to figure out. Like I suggested, you could maybe talk to the AWS support.

That's good to know that such a thing can happen, but there's nothing we can do about.
Go with disabling the console DataWriter like I said.

Thanks for the info.

**Comment by slandelle** [comment]
Oh wait, you're connected on ssh on your machine. Do you pipe Gatling's stdout all the way through the ssh tunnel???

**Comment by macarenomarco** [comment]
Although the tests were being run remotely the issue still occurs when running Gatling locally. Sorry for the delay, hadn't seen the notification.
