### ISSUE TITLE
HTTP: Send cache hit ratio to graphite

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2778]
A couple of teams have asked for it. I wondered what you thought?

**Comment by slandelle** [comment]
Interesting idea.
For now, we don't plan on adding new metrics in the OSS. But we do in the commercial version we're working on (we've already added a few).

**Comment by slandelle** [comment]
Note that getting the status codes will give you a part of the cache hits (304).
Still, you would be missing the other cache hits (Expires or Cache-Control max-age).

Then, there's also the permanent redirects.

**Comment by aidylewis** [comment]
I currently do a headerRegex on X-Cache HIT|MISS and write to a file: https://github.com/bbc/gatling-load-tests/blob/master/src/test/scala/bbc/mediaselector/MediaSelectorOpen.scala#L32-L38

**Comment by slandelle** [comment]
`X-Cache` is not a standard HTTP cache and even it's behavior is very implementation specific.
Is it set on resources that are served from a CDN?

**Comment by aidylewis** [comment]
Yes, I think that is the case.

**Comment by slandelle** [comment]
Note that your `PrintWriter` based impl probably lessen performance (synchronized).

**Comment by aidylewis** [comment]
Thanks for the info. What library would you suggest?

**Comment by slandelle** [comment]
Akka :) But that's probably overkill for you.

Also note that you don't close your writer, so you're leaking a fd.

**Comment by aidylewis** [comment]
I close the writer in an after block. Should I close it on each write?

**Comment by slandelle** [comment]
My bad.

**Comment by aidylewis** [comment]
I am now updating a mutable map during the simulation
https://github.com/bbc/gatling-load-tests/blob/master/src/test/scala/bbc/mediaselector/MediaSelectorOpen.scala#L41

and using synchronous file I/O in the after block 
https://github.com/bbc/gatling-load-tests/blob/master/src/test/scala/bbc/mediaselector/MediaSelectorOpen.scala#L45

**Comment by slandelle** [comment]
A mutable Map isn't threadsafe. Use a ConcurrentHashMap instead (or a ConcurrentLinkedQueue).

You also have to make sure all your data fits in memory.

**Comment by slandelle** [comment]
Something to be considered in the commercial product, but not in the OSS version.
