### ISSUE TITLE
Update Assertions documentation

### ISSUE THREAD

**Issue by ori-cohen** [gatling/gatling#2783]
The "Assertions" documentation is out of date, providing details of the "HttpRequestBuilder.assertThat" API that no longer exists.
The documentation should discuss the "Simulation.SetUp.assertions" API instead.

**Comment by slandelle** [comment]
Where did you find such reference? The only place I could find is the Gatling 1.5 to 2.0 migration, saying it was removed.

**Comment by ori-cohen** [comment]
http://gatling.io/docs/2.0.0-RC2/general/assertions.html

**Comment by slandelle** [comment]
Our documentation is versioned, and you're referring to a milestone (hence unstable) that was released 1 year ago. You have to use the version of the documentation that matches the version of Gatling you're using!
