### ISSUE TITLE
HTTP: body parts are added in reverse order

### ISSUE THREAD

**Issue by kostya-sh** [gatling/gatling#2790]
The following code:

    exec(http("post")
      .post("/url")
      .bodyPart(ByteArrayBodyPart("name1", body1))
      .bodyPart(ByteArrayBodyPart("name2", body2)))

will create HTTP request that contains `body2` followed by `body1`. This makes constructing HTTP requests with the predefined body parts order confusing.

This should be fixed here: https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/request/builder/HttpRequestBuilder.scala#L92

**Comment by slandelle** [comment]
@kostya-sh Thanks for reporting!
