### ISSUE TITLE
Maven: Don't recompile when scalac has already run

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2799]
When running a full lifecycle on a maven project where both scala-maven-plugin and gatling-maven-plugin are configured, simulations get compiled twice.

We can surely detect that scala-maven-plugin has already run and then skip launching our own compiler.

**Comment by slandelle** [comment]
@pdalpra ping :)

**Comment by pdalpra** [comment]
yes, sorry for the delay :)

**Comment by slandelle** [comment]
No pro, that was just a kind reminder, as IIRC, you were really close.

**Comment by pdalpra** [comment]
Indeed, it mostly need thorough testing, implementation should be OK.

**Comment by slandelle** [comment]
@pdalpra ping ;-)

**Comment by slandelle** [comment]
@pdalpra has a prototype, but it's very brittle. We now realize that the best solution is to document and have users explicitly disable the gatling compiler.

**Comment by slandelle** [comment]
Closing and opening a dedicated issue.
