### ISSUE TITLE
Expose API for logging of response bodies with condition only on errors and/or successes

### ISSUE THREAD

**Issue by ori-cohen** [gatling/gatling#2800]
JMeter has a feature called Listeners->"View Results Tree" that is disable-able and allows logging of response bodies either always / when error occur / when successes occur.
This is missing now in Gatling.

Currently to log response bodies I need to within a request to use check to save the bodyString to session and then afterward log it and then remove the value from session.

This is a very expensive operation to perform and cannot be easily automatically switched on or off according to the log level in the logback.xml file.

**Comment by ori-cohen** [comment]
My suggestion is to on the request level add a ".log" API in addition to the ".http" and ".check" APIs of the HttpRequestBuilder
A more general API on the scenario and/or the simulation level in addition to the request level could also be very useful.

**Comment by slandelle** [comment]
No. You have to tune the logging level on the http module, see logback.xml.

* if debug logging (see logback.xml) is enabled and the request fails, the full (session, request, response) is logged
* if trace logging is enabled, all of them are logged, not only the failed ones.

**Comment by ori-cohen** [comment]
Please slandelle read the first comment of this issue.
This is not something I am able to set up from the logback.xml and JMeter has this feature out of the box.
I have a task of converting highly used JMeter scripts to Gatling.
Some of the most important scripts we have have this feature widely used...

**Comment by slandelle** [comment]
Why doesn't the logback logging suite your needs?

**Comment by ori-cohen** [comment]
because that would force me to run all future load tests in trace log level which is not really useful, due to the amount of redundant logging that would be done just to get some specific successful requests logged.

**Comment by slandelle** [comment]
This feature is intended for debugging, not to run on production.
I suspect you use it for something else, in which case you really should elaborate.
