### ISSUE TITLE
Jenkins: Improve test performance trend chart with icon to hide legend

### ISSUE THREAD

**Issue by bonyeck** [gatling/gatling#2803]
I have project with many tests in Gatling. It's very embarassing when the legend is over the chart and is looking like that:
![zrzut ekranu 2015-09-03 o 16 33 14](https://cloud.githubusercontent.com/assets/11856140/9661115/8c9228a8-5259-11e5-98b9-e8cc8696d970.png)

I want to hide legend and see only trend. If anything is drastically changing then I could click on the pick and I'm in the gatling report. Legend is not needed in such case so I suggest to add button/small icon to hide legend and remember decision.

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by slandelle** [comment]
Then, honestly, the Jenkins plugin architecture is simply a crazy PITA and trying to create a nice interface in there is just a lost cause.
This is typically something we'll provide in our commercial product, where the Jenkins integration will just delegate to our own system.

**Comment by slandelle** [comment]
Been around for quite long and nobody picked it up.
