### ISSUE TITLE
Doc: Mismatch in Cheat sheet and implementation of `doIfEqualsOrElse`

### ISSUE THREAD

**Issue by PawelReszka** [gatling/gatling#2807]
As in Cheat sheet doIfEqualsOrElse should be used like: "(Session => Boolean){chain}{otherChain}", however it works only for "(actual, expected){chain}{otherChain}".
There is also method `doIfOrElse`, which works with "(Session => Boolean){chain}{otherChain}", but it isn't documented in Cheat sheet at all

**Comment by slandelle** [comment]
Fixed, thanks!
