### ISSUE TITLE
Report graphs break on escaped URL

### ISSUE THREAD

**Issue by DBezemer** [gatling/gatling#2808]
When there is a redirect or request with the name 3\" (or similar format) the report display is broken with a javascript error "Uncaught SyntaxError: Unexpected token ILLEGAL" in stats.js:5932

To resolve this the report generator should escape the string before generating the report.

Detected on 2.1.7 and I can provide a log that reproduces this issue if required.

**Comment by slandelle** [comment]
Fixed, thanks for reporting
