### ISSUE TITLE
HTTP: Websocket double reporting

### ISSUE THREAD

**Issue by p14n** [gatling/gatling#2813]
I am seeing the websocket request and check treated as two different reportable items, whereas only the check should be included for timings (the request is always 0ms).

I wondered if the silent option could be used to handle this, but it is not available on websockets.

**Comment by slandelle** [comment]
The timing of sending a WebSocket message is always 0, sure. But you don't want to silence it, as you still want the count of sent messages.

**Comment by p14n** [comment]
The issue is that both the send and the check are counted as requests in the req/s count - I suppose that's correct if you interpret it as msgs/s, but it's not intuitive.  Does it seem correct?

**Comment by slandelle** [comment]
Reopening to keep this in our radar if we want to reboot the WebSocket API some day.

**Comment by slandelle** [comment]
Closing, this is probably no longer an issue with the Gatling 3 WebSocket support as it hasn't been reported.
