### ISSUE TITLE
JMS: Support fire-and-forget queueing

### ISSUE THREAD

**Issue by neilshannon** [gatling/gatling#2815]
Currently Gatling only supports a request/response model for JMS queues.  My use case is a fire-and-forget (given there are no exceptions) situation where a message is enqueued and then dequeued at some later point by another application.  For this reason, our Gatling load tests for the queues never terminate.

Snippet of example code: https://gist.github.com/neilshannon/47b2adc64e08551cf463

I suggest implementing a "request only" situation (which JMeter currently supports for point-to-point queues).

I'd be happy to take a shot at contributing one.

**Comment by slandelle** [comment]
@neilshannon Sure, contributions welcome :)

**Comment by mgurov** [comment]
What would be the measure of the responsiveness in this case? Polling via other protocol? Or simply forget and check metrics outside of gatling?

**Comment by teo96** [comment]
In my case, check metrics outside of Gatling.
