### ISSUE TITLE
Docs: setUp example now misaligned

### ISSUE THREAD

**Issue by ChrisBAshton** [gatling/gatling#2825]
Looking at the `setUp` block of example code at http://gatling.io/docs/2.0.0-RC2/general/simulation_setup.html#injection.

The code is not in line with the explainers underneath. For example:

`splitUsers(1000) into(rampUsers(10) over(10 seconds)) separatedBy(10 seconds), // 8`

...no longer maps to this, which is below it:

`8. heavisideUsers(nbUsers) over(duration): Injects a given number of users following a smooth approximation of the heaviside step function stretched to a given duration.`

Whereas:

` nothingFor(4 seconds), // 1`

...maps to this line perfectly:

`1. nothingFor(duration): Pause for a given duration.`

It looks like explainer number 8 should be moved to the end of the list, becoming explainer number 10.

**Comment by slandelle** [comment]
@ChrisBAshton Thanks!

**Comment by aidylewis** [comment]
If your the Chris I have just done a demo to, its good also to keep up with the latest documentation - which is currently at 2.1.7. Sorry to jump in.

**Comment by ChrisBAshton** [comment]
Ha, yes that's me! Ok, I should have checked. This just happened to be the first result on Google.
