### ISSUE TITLE
Gatling recorder not capturing "Content-Type: application/json"

### ISSUE THREAD

**Issue by tpanningnextcen** [gatling/gatling#2826]
I tried the Gatling recorder program, which is very handy, to record some interactions with my web application, but the playback generated a bunch of errors. I was able to determine that the recorder was not noticing the Content-Type on the POST requests.

To reproduce:

1. Launch the Gatling 2.1.7 recorder.
2. Under the Blacklist, click "No static resources", and then also add .*\.html
3. Click "Start!"
4. In your web browser (I used Firefox) navigate to http://demo.neonframework.org/neon-examples/app/
5. In the recorder, click on one of the POST requests, and in the "Request Information" box, you will see "Content-Type: application/json; charset=UTF-8"
6. After the page has loaded, click "Stop & Save" in the recorder.
7. Use gatling to run the resulting script, and it will report a bunch of errors.
8. Open the resulting script, and there should be only one header Map that is used by the post commands. To that Map, add the entry "Content-Type" -> "application/json".
9. Save the script, and rerun it.
10. There should now be no errors reported by gatling.

Expected behavior: The Content-Type should have been included in the script when the recorder created it.

Environment: I ran this with the Gatling 2.1.7 download from Gatling's site, with OpenJDK 24.79-b02 on Fedora 20.

**Comment by slandelle** [comment]
@tpanningnextcen http://demo.neonframework.org/neon-examples/app/ works fine with Chrome, but completely crashes with FireFox (tried with 40.3.0, then upgraded to latest 41.0 with same result) and I have to force kill! 

<img width="475" alt="neon-crash" src="https://cloud.githubusercontent.com/assets/849197/10148796/e7012560-6635-11e5-8421-eff4c843b482.png">

**Comment by tpanningnextcen** [comment]
We haven't been able to reproduce the Neon hang in Firefox on Linux, but while we investigate that, I have a separate way to reproduce this gatling issue.

If it's not too much trouble for you to run the below node.js script (you will have to `npm install express` in the directory that contains the script, once you download it), you can test the gatling behavior that way. Here are the steps to reproduce:

    var express = require('express');
    var app = express();

    app.get('/', function (req, res) {
      res.send('<html><head><script>' +
               'function doPost(){var xhr = new XMLHttpRequest(); xhr.open("post", "/post", true); xhr.setRequestHeader("Content-Type", "application/json; charset=UTF-8"); xhr.send("{}");}' +
               '</script></head><body onload="doPost()"></body></html>');
    });

    app.post('/post', function(req, res) {
      console.log('POST to /post with ' + req.get('Content-Type'));
      res.send('<html><head></heead><body>Content-Type: ' + req.get('Content-Type'));
    });

    var server = app.listen(3000, function () {
      var host = server.address().address;
      var port = server.address().port;

      console.log('Example app listening at http://%s:%s', host, port);
    });



1. Run `node index.js`
2. Start the gatling recorder
3. Configure your browser to use the gatling recorder proxy and go to http://localhost:3000/
4. In the gatling recorder should see the initial GET for localhost:3000/, immediately followed by a POST for localhost:3000/post
5. If you click on the POST request in gatling recorder, you will see the Content-Type is set to "application/json; charset=UTF-8".
6. Also, if you check the node script output, it will say "POST to /post with application/json; charset=UTF-8"
7. Stop and save the gatling recorder
8. Run the resulting gatling script
9. The node script output will now say "POST to /post with application/json; charset=UTF-8".

**Comment by slandelle** [comment]
@tpanningnextcen Thanks, I'll give it a try (travelling atm, so probably next week).

Regarding the OSX FF issue, I think it actually has to do with the plot drawing method being too slow.
