### ISSUE TITLE
Doc: How to debug scripts page in the documentation

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2830]
I suggest creating a debugging page in the documentation. Extract the stuff about printing session  values and add logback stuff.

**Comment by slandelle** [comment]
Good idea. Contributions welcome :)

Doc is [here](https://github.com/gatling/gatling/tree/master/src/sphinx) and is built with [Sphinx](http://sphinx-doc.org/).

**Comment by aidylewis** [comment]
I'll submit a PR sometime this week.

**Comment by slandelle** [comment]
Great, thanks!

**Comment by aidylewis** [comment]
I've made a pull request.

**Comment by slandelle** [comment]
Thanks Aidy! I'll review asap.

**Comment by slandelle** [comment]
Doen in https://github.com/gatling/gatling/blob/master/src/sphinx/general/debugging.rst
