### ISSUE TITLE
Exception thrown when running the sbt plugin and Gatling 2.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2836]
Reproducer
--------------
$ git clone https://github.com/bbc/gatling-load-tests && cd gatling-load-tests
$ sbt
`>` testOnly *ComputerWorld

```
Select simulation id (default is 'computerworld'). Accepted characters are a-z, A-Z, 0-9, - and _
[error] java.lang.NullPointerException
[error] 	at io.gatling.app.Selection$Selector.loop$1(Selection.scala:127)
[error] 	at io.gatling.app.Selection$Selector.askSimulationId(Selection.scala:135)
[error] 	at io.gatling.app.Selection$Selector.selection(Selection.scala:50)
[error] 	at io.gatling.app.Selection$.apply(Selection.scala:33)
[error] 	at io.gatling.app.Gatling.runIfNecessary(Gatling.scala:73)
[error] 	at io.gatling.app.Gatling.start(Gatling.scala:63)
[error] 	at io.gatling.app.Gatling$.start(Gatling.scala:51)
[error] 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:43)
[error] 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
[error] 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Simulation ComputerWorld failed.
[info] Simulation(s) execution ended.
[error] Failed tests:
[error] 	ComputerWorld
[error] (gatling:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 58 s, completed 16-Oct-2015 10:37:02
```

**Comment by aidylewis** [comment]
Reproducer
--------------
$ git clone https://github.com/bbc/gatling-load-tests && cd gatling-load-tests
$ sbt
$ testOnly *ComputerWorld

elect simulation id (default is 'computerworld'). Accepted characters are a-z, A-Z, 0-9, - and _
[error] java.lang.NullPointerException
[error] 	at io.gatling.app.Selection$Selector.loop$1(Selection.scala:127)
[error] 	at io.gatling.app.Selection$Selector.askSimulationId(Selection.scala:135)
[error] 	at io.gatling.app.Selection$Selector.selection(Selection.scala:50)
[error] 	at io.gatling.app.Selection$.apply(Selection.scala:33)
[error] 	at io.gatling.app.Gatling.runIfNecessary(Gatling.scala:73)
[error] 	at io.gatling.app.Gatling.start(Gatling.scala:63)
[error] 	at io.gatling.app.Gatling$.start(Gatling.scala:51)
[error] 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:43)
[error] 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
[error] 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Simulation ComputerWorld failed.
[info] Simulation(s) execution ended.
[error] Failed tests:
[error] 	ComputerWorld
[error] (gatling:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 58 s, completed 16-Oct-2015 10:37:02

**Comment by slandelle** [comment]
Regression only affecting current master

**Comment by slandelle** [comment]
@aidylewis Fixed, sorry for the delay

**Comment by aidylewis** [comment]
@slandelle Will you be deploying the fix to the snapshot repo?

**Comment by slandelle** [comment]
CI automatically triggers on commit and deploy new snapshots on Sonatype.
But sbt doesn't update automatically. You have to run `sbt update`.

**Comment by slandelle** [comment]
@aidylewis Please also note that you shouldn't be using `testOnly` but `gatling:testOnly`. See https://github.com/gatling/gatling/issues/2763#issuecomment-148681035 for more details.

Supporting `test` and `testOnly` was a mistake on our side in the first place, and breaks unit tests in the same project.

**Comment by aidylewis** [comment]
@slandelle Thanks for the heads up. The fix has been tested and passes.
