### ISSUE TITLE
Doc: Advanced tutorial sources link is dead

### ISSUE THREAD

**Issue by kristapsmelderis** [gatling/gatling#2845]
Page: http://gatling.io/docs/2.1.6/advanced_tutorial.html#step-05-check-and-failure-management

**Clicking the link:** "The files for this tutorial can be found in the distribution in the user-files/simulations directory, and on Github **here.**"
Ends with 404

**Comment by slandelle** [comment]
broken by c50bf4657a4d058206d627955bec4dcf1585dd15

**Comment by slandelle** [comment]
Fixed. Proper link is https://github.com/gatling/gatling/tree/master/gatling-bundle/src/main/scala/computerdatabase

Thanks for reporting
