### ISSUE TITLE
HTTP: HttpRequestBuilder formParam overwrites content-type header

### ISSUE THREAD

**Issue by jestinbrooks-ck** [gatling/gatling#2850]
Calling the HttpRequestBuilder formParam method will set the content type to application/x-www-form-urlencoded even if it has already been set to something else.  

The example code below would create a request with a content-type of application/x-www-form-urlencoded

```
http("test").post("http://localhost:9000")
.header(HttpHeaderNames.ContentType, HttpHeaderValues.ApplicationJson)
.formParam("key", "value")
```

I couldn't find anything in the documentation that mentions the side effect of calling the method.

**Comment by slandelle** [comment]
Documentation lacking.

`formParam` will set `Content-Type` to `application/x-www-form-urlencoded` except if there's also some parts, in which case it will set `multipart/form-data`.

**Comment by slandelle** [comment]
Re-qualifying: let user force a different Content-Type (even if it's probably wrong).
