### ISSUE TITLE
Active Sessions graph is incorrect in Gatling report

### ISSUE THREAD

**Issue by ybo** [gatling/gatling#2861]
I'm working on Windows, running Gatling 2.1.7 from Eclipse. I have found that the active session graph in Gatling report does not match with the data in console output, graphite, or simulation.log

For details and steps to reproduce, please see https://groups.google.com/forum/#!topic/gatling/T8jHFCWHvp4

Thanks,
Brian

**Comment by slandelle** [comment]
Please provide `simulation.log`. Couldn't reproduce with current master.

**Comment by ybo** [comment]
I have attached the simulation logs in a reply in the Google group topic. 
https://groups.google.com/group/gatling/attach/90d8041f0a910/simulation_logs.zip?part=0.1&authuser=0&view=1

Thanks

**Comment by slandelle** [comment]
Fixed, thanks for reporting!
