### ISSUE TITLE
HTTP: Upgrade AHC 2.0

### ISSUE THREAD

**Issue by kevarh** [gatling/gatling#2867]
Please update to AHC 2.0. I have a blocker testing websockets at high concurrency that is fixed in AHC 2.0

https://github.com/AsyncHttpClient/async-http-client/issues/988

**Comment by slandelle** [comment]
lol
Do you realize who develops AHC exactly? Gatling 2.2 will use AHC 2.0 (or 2.1 that will target Netty 4.1). You can already give the snapshots a try.
