### ISSUE TITLE
Scalariform auto-format problem.

### ISSUE THREAD

**Issue by xiongjia** [gatling/gatling#2868]
It's not a bug/defect. It's just a small problem. 

**The problem:**
All the Gatling source files are modified after I build it from source. 
I think the Scalariform plugin auto-formatted all the *.scala* files when I run `sbt compile`. 
In every file, it inserted a empty blank line at the tail of license comments. 

For instance, after I built the Gatling from srouce: **632 files** are modified and just added a new blank line to every *.scala* file. 
```
gatling [dev +0 ~632 -0]> git diff 
diff --git a/src/sphinx/session/code/Feeders.scala b/src/sphinx/session/code/Fee
index a14331e..42c1fd8 100644
--- a/src/sphinx/session/code/Feeders.scala
+++ b/src/sphinx/session/code/Feeders.scala
@@ -13,6 +13,7 @@
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */
+
 import io.gatling.core.Predef._
```
This problem is reproduced on the master branch. 

**Expected:**
Add one SBT or Scalariform  setting/flag to skip the Scalariform  "auto-format".

**Comment by slandelle** [comment]
Sorry, can't reproduce.

Are you sure you don't override/force the scalariform set up, like in your .sbt dir.

**Comment by xiongjia** [comment]
@slandelle Thanks for your quick response. 

I checked this issue on my local. 

* It only reproduced on my Windows OS. 
* I did not add any Scalariform setting on this Windows OS. 

I am guessing, the problem is related the line end style. 

* On my Windows, my git client is "autocrlf = input". It keeps the Unix line end style. 
* The Scalariform on windows will convert all it to Windows Line end style. 

----

I will close this issue since it's a local env problem.

**Comment by slandelle** [comment]
@xiongjia Thanks for your feedback. I was suspecting something like this. I'm afraid this issue will be hard to get fixed. Scalariform is more or less orphan atm, and latest releases have introduced countless regressions so we had to revert upgrade :(

**Comment by slandelle** [comment]
ping @pdalpra This might be of interest to you
