### ISSUE TITLE
Jenkins plugin to show different stat on project dashboard

### ISSUE THREAD

**Issue by nutthaka** [gatling/gatling#2872]
Is there a way to change the plugin to show other stat e.g. 95th percentiles response time trend on the project dashboard (instead of Mean Value)?

**Comment by slandelle** [comment]
From [doc](https://wiki.jenkins-ci.org/display/JENKINS/Gatling+Plugin):

> If you are on the project dashboard, clicking on Gatling will get you to a more detailed performance trend, displaying for your last 30 builds :
* Mean response time trend
* 95th percentiles response time trend
* Percentage of KO requests

Then, no, trends can't be customized. However, we'll have a dedicated Jenkins plugin for our upcoming commercial product that will give you way more trends.
