### ISSUE TITLE
Jenkins Gatling plugin fails : Could not find a Gatling report in results folder

### ISSUE THREAD

**Issue by YannMoisan** [gatling/gatling#2881]
It has worked for some builds and it fails now for unknown reason (maybe due to a jenkins upgade). 

Here is the stack trace of the error :

11:49:58 Archiving Gatling reports...
11:49:58 ERROR: Build step failed with exception
11:49:58 java.lang.IllegalArgumentException: Could not find a Gatling report in results folder.
11:49:58 	at io.gatling.jenkins.GatlingPublisher.saveFullReports(GatlingPublisher.java:99)
11:49:58 	at io.gatling.jenkins.GatlingPublisher.perform(GatlingPublisher.java:68)
11:49:58 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
11:49:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:786)
11:49:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:733)
11:49:58 	at hudson.model.Build$BuildExecution.post2(Build.java:183)
11:49:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:680)
11:49:58 	at hudson.model.Run.execute(Run.java:1763)
11:49:58 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:49:58 	at hudson.model.ResourceController.execute(ResourceController.java:98)
11:49:58 	at hudson.model.Executor.run(Executor.java:381)
11:49:58 Build step 'Track a Gatling load simulation' marked build as failure 

Versions are : 
- gatling-plugin : 1.1.1
- jenkins : 1.609.4.6

**Comment by YannMoisan** [comment]
my bad

**Comment by slandelle** [comment]
@YannMoisan No space left on device? ;-)

**Comment by M3lkior** [comment]
@YannMoisan ;What was the reason?

**Comment by YannMoisan** [comment]
There was a failure, before Gatling step, in my build !
So, if you don't call Gatling, Gatling doesn't generate the report …
