### ISSUE TITLE
Doc: OSX tuning is out of date / doesn't cover all releases

### ISSUE THREAD

**Issue by ceeaspb** [gatling/gatling#2884]
http://gatling.io/docs/2.0.0-RC2/general/operations.html
for mac
update is needed eg. per 
https://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks

**Comment by slandelle** [comment]
Some more from the Basho people:
http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/
http://docs.basho.com/riak/latest/ops/tuning/linux/

**Comment by slandelle** [comment]
Happy New Year BTW :)
Glad to see you there, and only on the jClarity ML ;-)

**Comment by ceeaspb** [comment]
Bonne année to you too!

**Comment by slandelle** [comment]
We'll extract some parts of the Riak doc, give credit to them, and add a link to their doc. The stackexchange link is also an extract from them.
