### ISSUE TITLE
Multiple version of scala detected when building gatling 2.1.7 with maven

### ISSUE THREAD

**Issue by Willymontaz** [gatling/gatling#2888]
I am building a project with gatling as the only dependency

Here is the snippet of the log produced by 'mvn clean install' during the compile phase

[WARNING]  Expected all dependencies to require Scala version: 2.11.7
[WARNING]  io.gatling:gatling-app:2.1.7 requires scala version: 2.11.7
[WARNING]  io.gatling:gatling-core:2.1.7 requires scala version: 2.11.7
[WARNING]  org.scala-lang:scala-reflect:2.11.7 requires scala version: 2.11.7
[WARNING]  com.typesafe.akka:akka-actor_2.11:2.3.12 requires scala version: 2.11.5
[WARNING] Multiple versions of scala libraries detected!

**Comment by slandelle** [comment]
Stupid warnings, minor versions of Scala are now compatible. It should only complain if for example we were mixing librairies compiled against Scala 2.10 and Scala 2.11.
Just forget about them.
