### ISSUE TITLE
HTTP: mitigate Java's eternal DNS cache lack of round robin

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2890]
When using Java's eternal DNS cache, records come always in the same order, so DNS round robin is ignored and all the virtual users hit the same host.
We can have a per virtual user cache that stores a shuffled list.

**Comment by aidylewis** [comment]
Will this fix also use additional IPs that are included in DNS records when ELB autoscales?

**Comment by slandelle** [comment]
[This](https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/protocol/HttpProtocolBuilder.scala#L61) will.
But beware of the extra IO on the Gatling hosts :)

**Comment by aidylewis** [comment]
Ah. Good point. And is that why we should set nativeTransport to true?

**Comment by slandelle** [comment]
No, completely unrelated. Enabling `nativeTransport` triggers a [Linux epoll based transport](http://netty.io/wiki/native-transports.html) instead if Java NIO implementation.
