### ISSUE TITLE
Website: Redesign download page

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2891]
### Zip bundle

Download here (link)

### maven artifacts

Deployed on maven central

### Zip bundle

Download here (link). Make sure to grab the latest timestamp at the bottom of the page.

### maven artifacts

Deployed on Sonatype Nexus: url

**Comment by slandelle** [comment]
@notdryft WDYT?

**Comment by notdryft** [comment]
@slandelle Had this in mind, WDYT?

![screen shot 2016-05-04 at 10 00 49](https://cloud.githubusercontent.com/assets/2608594/15008234/2472d088-11df-11e6-8536-b5434c75bf2a.png)

**Comment by slandelle** [comment]
Actual flaw is that some people fail to realize "Gatling bundle (.zip)" is a link.

**Comment by notdryft** [comment]
Live on http://gatling.io/#/download
