### ISSUE TITLE
Demo site is down.

### ISSUE THREAD

**Issue by ChrisKaelinJr** [gatling/gatling#2892]
Hi,
We would like to try this tool out, however it seems that the demo site in the documentation: http://excilysbank.gatling.cloudbees.net is offline/not responding.

It would be fantastic if this could be brought back online for us.

Respectfully,
Christopher Kaelin

**Comment by slandelle** [comment]
It's been several months that Cloudbees shut his free for OS project hosting down, and that we're hosting elsewhere. Check the tutorials for the updated link.

**Comment by slandelle** [comment]
Also, this site was used for the Gatling 1 tutorials that is no longer supported for several years.

**Comment by ChrisKaelinJr** [comment]
Fantastic! Thank you.
