### ISSUE TITLE
Recorder: compile errors in generated scala: `not found: value uri1`

### ISSUE THREAD

**Issue by hedefalk** [gatling/gatling#2897]
I got something looking like this:

```
val scn = scenario("RecordedSimulation")
		.exec(http("request_0")
			.get("/")
			.headers(headers_0)
			.resources(http("request_1")
			.get(uri1 + "/img/glyphicons-halflings.png")
			.headers(headers_1)))

…
```

which doesn't compile. `uri1` is not in scope…

**Comment by slandelle** [comment]
Could you provide a procedure to reproduce, please?

**Comment by slandelle** [comment]
And mention the version you're using.

**Comment by hedefalk** [comment]
Ran from bundle 2.2.0-SNAPSHOT:

"gatling-charts-highcharts-bundle-2.2.0-SNAPSHOT"

I'll be back with repro.

**Comment by slandelle** [comment]
@hedefalk ping :)

**Comment by hedefalk** [comment]
Sorry, I haven't had the opportunity to dig any further in this. I just went ahead and wrote manual code (which was my plan anyways). Please feel free to close, otherwise I might come back with repro at a later time. Thanks for a great tool, helped me nail a serious memory leak :)

**Comment by slandelle** [comment]
Thanks!
