### ISSUE TITLE
Maven: Cannot parse gatling.jvmArgs properly

### ISSUE THREAD

**Issue by rvansa** [gatling/gatling#2898]
I am trying to debug my custom code integration in gatling, executing the scenario through
```
mvn gatling:execute -Dgatling.jvmArgs="-agentlib:jdwp=address=5005,transport=dt_socket,server=y,suspend=y"
````
However this is not parsed properly; it seems that only the first argument (address=5005) goes in and the rest is lost, therefore I get
```
ERROR: JDWP address specified without transport: -agentlib:jdwp=address=5005
```
It would be even more convenient if there was option to run gatling from within Maven's JVM, since that would allow one-click IDE (Intellij IDEA in my case) debugging.

**Comment by rvansa** [comment]
I should probably add this rather directly to the gatling-maven project.

**Comment by smiklosovic** [comment]
Hi, how did your resolve this exactly, please?

**Comment by rvansa** [comment]
You'd find this issue (with comments) in gatling-maven project. In the end, it's not possible due to the way how Maven parses the command-line args; Nevertheless, for debugging purposes I rather use the Engine class generated from the artifact generator.
