### ISSUE TITLE
Response body string is null for KO sessions in ExtraInfoExtractor

### ISSUE THREAD

**Issue by fakraemer** [gatling/gatling#2902]
I'm currently writing support to generate an `HTTPArchive` from the `ExtraInfoExtractor`.  In order to extract the response body, I do:

    val responseBody = Content(info.response.bodyLength.toLong, -1, "", Option(info.response.body.string).getOrElse(""))

where info is the `ExtraInfo` passed into the function. On the scenarios, we employ checks like `status.is(201)`. What I can observe so far is that the response body is null for all interactions that were declared KO as a result of these checks, but it is set for all OK interactions.

Is this a know restriction or am I doing something wrong? I'm using Gatling 2.1.7.

**Comment by slandelle** [comment]
http://gatling.io/docs/2.1.7/http/http_protocol.html#response-chunks-discarding
Please use our Google Group for questions.
