### ISSUE TITLE
Finalization for 2.2.0-M3

### ISSUE THREAD

**Issue by aoboturov** [gatling/gatling#2903]
Hi

It's been almost a year since the 2.2.0-M3 was released. The project does not seem to be dead - commits are coming rather regularly. Would there be something finalized for 2.2.0? We have to use master otherwise. Old akka version is the bottleneck for our use case.

Regards

**Comment by slandelle** [comment]
> The project does not seem to be dead - commits are coming rather regularly.

It sure is not: we've created a company, GatlingCorp, to make our living with it!

> Would there be something finalized for 2.2.0?

We'll ship 2.2.0 along with our upcoming commercial product, planned end of March. If you need support, consider subscribing to our support offer.
