### ISSUE TITLE
Unable to resolve data from the feeder file

### ISSUE THREAD

**Issue by Ajithshetty127** [gatling/gatling#2907]
Hi Team,
Our application uses encoded  values( base64 bit encoding) ,  so we have used a method as  below

def encodeData(data: String): String = {
	java.util.Base64.getMimeEncoder().encodeToString(data.getBytes(StandardCharsets.UTF_8))
  }

When we use same to method  in scripts

.feed(loginUserFeeder)
		.exec(
		...
            .formParam("data",encodeData("""{"tbl0":{"csrfToken":"${"UserName"}"}}"""))
		...
		)

User name is not getting resolved with feeder value.

feeder has value "ABC".

After encoding  we are getting value as "eyJ0YmwwIjp7ImNzcmZUb2tlbiI6IiR7IlVzZXJOYW1lIn0ifX0=" which is nothing but {"tbl0":{"csrfToken":"${"UserName"}"}}, we are expecting {"tbl0":{"csrfToken":"ABC"}}

Can any one please help us on this

**Comment by slandelle** [comment]
This is a question, and a user issue, not a Gatling bug.

**Comment by Ajithshetty127** [comment]
Hi slandelle,

 I tried doing all possible ways, but  was not successful. Can you please help us in resolving this? 

I have posted same question on goggle groups, didn't get any reply. If goggle group is not right place to post question, please let us know the right forum.

**Comment by slandelle** [comment]
If the documentation and the public mail list is not enough for you and you need fast answers from the Gatling experts, you can consider subscribing to our support offer: http://gatling.io/#/services
