### ISSUE TITLE
JMS: Responses not properly handled when multiple actions use the same replay queue

### ISSUE THREAD

**Issue by kiggundu** [gatling/gatling#2913]
It looks like the JMS plugin when used with activeMQ behaves unpredictably, randomnly dropping requests and responses. I've attached a sample test script that will reproduce the issue. What happens is that though the messages are successfully submitted and the responses are successfully dequed the JMS client fails to consistently pass this on to the gatling reporting framework and the tracker simply ticks on waiting to be notified
If all the tasks are commented out of the scenario appart from one then all works fine because only one thread is created. I believe this has something to do with JMS session thread affinity but not certain.

Simulation attached below:
[JMSConcurrencyIssue.txt](https://github.com/gatling/gatling/files/128347/JMSConcurrencyIssue.txt)

**Comment by slandelle** [comment]
```scala
  private def initExecution(title: String): JmsRequestBuilder = {
    jms(title)
      .reqreply
      .queue("abraham.simulation.in")
      .replyQueue("abraham.simulation.out")
      .textMessage(stringToExpression("Client asking server to: " + title))
      .property("transactionId", java.util.UUID.randomUUID.toString.toUpperCase())
  }
```

Is it intended that transactionId is static for a given exec type? Are you sure you don't want to pass an Expression instead (one transactionId per message sent)?

**Comment by slandelle** [comment]
Your problem is that all your actions read and write from the same queues.

Trackers keep track of sent ids and are in charge of performing correlation. The thing is there's one tracker per action. But as you have several of them, and they all read from the same queue, there's a very good chance that a given response gets picked up by a different tracker than the one that kept track of the request, hence correlation never happens.

**Comment by slandelle** [comment]
IMO, this is a design issue. There should be only one tracker per replyDestination, or a single one that would use the replyDestination in the tracking key.

**Comment by kiggundu** [comment]
Hi Stephane,

Thanks for looking into this. Sounds like a change needs to be made
within the JMS client to ensure that there is one tracker per queue. If
that's so are you able to advise on when a patch might be available?
We'll stand down if that's pretty soon, if not we can take a stab at
fixing it.

rgds
Abraham

Stephane Landelle:

**Comment by slandelle** [comment]
Fixed

**Comment by kiggundu** [comment]
Brilliant,
Many thanks for the quick turnaround on this one Stephan.

**Comment by kiggundu** [comment]
We're keen to integrate with your fix as soon as possible. When will you be in a position to push the changes?

**Comment by slandelle** [comment]
2.2.0 is planned for end of March

**Comment by kiggundu** [comment]
Were happy to pull and build a snapshot in the meanwhile if that's ok... just couldn't see the fix in master.

**Comment by slandelle** [comment]
http://gatling.io/#/services

**Comment by kiggundu** [comment]
Be glad to start with the "Basic" option and upgrade as necessary if that's sufficient for us to start using this fix today. please advise?

**Comment by slandelle** [comment]
Yes, with Basic would grant you access to the private fixes. Please get in touch at contact@gatling.io and we'll gladly send you an invoice.
