### ISSUE TITLE
Change results folder location in gatling.conf

### ISSUE THREAD

**Issue by pierrefevrier** [gatling/gatling#2920]
Hi,

Is there a way to change results output location in file `gatling.conf` ?

```
gatling {
    [...]
    directory {
      [...]
      results = "$HOME/DATA/GATLING/results"                    # Name of the folder where all reports folder are located
    }
  }
```

Results are store in `$GATLING_HOME/$HOME/DATA/GATLING/results` instead of `$HOME/DATA/GATLING/results`.

**Comment by slandelle** [comment]
Not an issue but a question

**Comment by rufreakde** [comment]
> Not an issue but a question

But is there?
