### ISSUE TITLE
Gatling JMS plugin seems to loose responses under high loads

### ISSUE THREAD

**Issue by kiggundu** [gatling/gatling#2921]
This was initially reported under issue #2913 and fix build 2.2.0-E20160217 was provided which passed the [provided testcase](https://github.com/gatling/gatling/files/128347/JMSConcurrencyIssue.txt). I have attached a [new testcase](https://github.com/gatling/gatling/files/142552/JMSConcurrencyIssue.scala.txt). In this case the issue manifests its self through a large number of messages showing in the output graphs as timed-out yet according to the JMS brokers the reply messages were picked up well within the timeout. The pull-request provided under issue #2918 seems to pass this new testcase though so we have decided to use that for now until a proper fix is provided.

**Comment by slandelle** [comment]
Thanks. Having a look at your test case asap.

**Comment by slandelle** [comment]
I had a quick look at your test case, it seems you didn't take an comment I did on your previous one into account (or I didn't have an answer on this point from your side).

You have this `transactionId` is about. Is it supposed to be unique by task (ie task definition), or be unique by task execution? The way you wrote it, you have the former, not the latter:

```scala
.property("transactionId", java.util.UUID.randomUUID.toString.toUpperCase())
```

Is it intended? If you wanted the latter, you'd need to pass a function so the randomUUID is computed on every execution:

```scala
.property("transactionId", _ => java.util.UUID.randomUUID.toString.toUpperCase())
```

**Comment by kiggundu** [comment]
Yes... good point. I shall change that at our end. I believe that does
not invalidate the testcase though considering I ran it using a server
that does not care about the provided transactionId. Do you agree?

Stephane Landelle:

**Comment by slandelle** [comment]
Agree.
The issue is that there's one actor instanciated by scenario, which is not expected. Investigating.

**Comment by slandelle** [comment]
Fixed
