### ISSUE TITLE
Show group duration in main report table instead of cummulated response time

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2924]
For some of my simulations, group duration is more important than cumulated response time. I propose to add a switch in configuration to choose between two timings.

For the records, it is close to #2091 .

**Comment by slandelle** [comment]
Already available in FrontLine :)

**Comment by mxbossard** [comment]
OK thanks @slandelle !

**Comment by slandelle** [comment]
We might have this in the standard reports some day, but that's not really a priority. So much to do... If you want to give it a stab, contributions are welcome.

**Comment by mxbossard** [comment]
Ah ok, I understood it was already implemented.
I'll propose a solution.

**Comment by slandelle** [comment]
@mxbossard Thanks!
