### ISSUE TITLE
Core : Conditionnal check

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2927]
For my use case testing a Vaadin app, I need a mean to perform a check only if one condition against the response or the session is True.

I ended up by developping a check wrapper which take a function : (session, response) => boolean and a nested check in parameter and perform the nested check if the function return true.
I am not sure it has no impact on performance, but I need it cause my scenarios are highly coupled with the server responses.

Here is a simple use case for this feature : I check all responses with a jsonpath check, but some responses payload are not formated in json. So I supplied a jsonSecured check wich is a ConditionnalCheck with a condition on the reponse content-type header, to perform the jsonpath nested check only if the response contains a JSON payload.

Are you interested in this feature ?

**Comment by slandelle** [comment]
Hey @mxbossard 

Yes, such feature would be interesting. What's nice is that, as you said, that's something you could implement on your own without forking Gatling.

Then, let's discuss both the API and the implementation.

Requirements:
* it must be both simple enough for basic users and powerful enough for advanced ones. Typically, basic users tend to not use functions but EL, while advanced ones want the full control from Scala functions.
* implementation must be extensible. You suggest a kind of `if`, but as soon as we have that, other people will also want "if else" and "switch" too.

The other/intermediate solution would be to document how to write a custom check like you did. We have a cookbook section in the documentation that would be suited for this.

Looking forward to your suggestions.

**Comment by mxbossard** [comment]
For now it's pretty basic, and maybe not easy to use. 
Here is the signature : 

def doCheckIf(condition: (Session, Response) => Validation[Boolean])(nestedCheck: HttpCheck): HttpCheck

Like you said, it don't need to be integrate in the DSL. Expression[Session] seem not to be sufficient cause I need to check the response. I am not sufficently scala fluent to find a "simpler way" to pass a condition depending on the response or the condition. 

Or maybe like this : 
def doCheckIf(condition1: Response => Validation[Boolean] = response => Success(true), condition2: Expression[Boolean] = session => Success(true))(nestedCheck: HttpCheck): HttpCheck

Which permit to pass an expression[Boolean] or a Response => Validation[Boolean] or both, an and operation being applied between all supplied functions.

**Comment by mxbossard** [comment]
Or something more extensible like this : 
```scala
def if(condition: Expression[Boolean]) : ConditionnalCheckBuilder

class ConditionnalCheckBuilder {
  def then(nestedCheck: Check): Check
  def thenOrElse(nestedThenCheck: Check)(nestedElseCheck: Check): Check
}
```
I think it's ok for general checking. But I need a "ConditionnalHttpCheck", so I need to extend it, moreover, with a (Session, Response) => Validation[Boolean] as condition.

So I will probably need this : 
```scala
def if(condition: (Response) => Validation[Boolean]) : ConditionnalHttpCheckBuilder
def if(condition: (Session, Response) => Validation[Boolean]) : ConditionnalHttpCheckBuilder

class ConditionnalHttpCheckBuilder {
  def then(nestedCheck: Check): Check
  def thenOrElse(nestedThenCheck: Check)(nestedElseCheck: Check): Check
}
```
I don't know yet how to deal with mixed signatures. How to call mixed conditions supplied in if functions ?
For instance, I think 
```scala
def if(condition1: Response => Validation[Boolean] = response => Success(true),
                       condition2: (Response, Session) => Validation[Boolean] = (response, session) => Success(true)) : ConditionnalHttpCheckBuilder
```
may be a way

**Comment by slandelle** [comment]
You can't use `if` for a method name. Just like in Java, it's of course a reserved word. Hence our `doIf`.

Regularity is important in a DSL, so I think we should stick with the same form as for `doIf`: currying with the first parameter list being the condition and the second one the actual check.

**Comment by slandelle** [comment]
`checkIf` ?

**Comment by mxbossard** [comment]
Ok, if we imitate the doIf signature we get this : 
```scala
checkIf(condition: Expression[Boolean])(thenCheck: Check): Check
checkIfEqualsOrElse(condition: Expression[Boolean])(thenCheck: Check)(elseCheck: Check): Check
```
I'm a little disturbed by "ifEquals" because it's not an equals operation but this is the current DSL.

Then for HttpCheck, it's more tricky. I want to express a condition against the HttpResponse, we can achive this with a precedent check by storing some information in the session, then using a condition against this session parameter. But I think it's not as elegent as a Response => Boolean condition.
Maybe using a check as a condition ? doCheck could perfrom the thenCheck if condition check succeed, and the elseCheck if the condition check fail : 
```scala
checkIfDontFail(condition: Check)(thenCheck: Check): Check
checkIfDontFailOrElse(condition: Check)(thenCheck: Check)(elseCheck: Check): Check
```
The double negation maybe counter intuitive...
But the idea is powerful because it could work quickly for all modules with various checks. I think it's impelemntable, but I didn't verified it.

**Comment by mxbossard** [comment]
I checked the Check trait, and I came whith a simpler idea using the parametric Response type of the Check trait : 

```scala
def checkIf[R, C <% Check[R]](condition: Expression[Boolean])(thenCheck: C): Check[R]
def checkIfTrueOrElse[R, C <% Check[R]](condition: Expression[Boolean])(thenCheck: C)(elseCheck: C): Check[R]

def checkIfResponse[R, C <% Check[R]](condition: (R, Session) => Validation[Boolean])(thenCheck: C): Check[R]
def checkIfResponseOrElse[R, C <% Check[R]](condition: (R, Session) => Validation[Boolean])(thenCheck: C)(elseCheck: C): Check[R]
```

What do you think of it ?
I'll test my implementation on this.

**Comment by slandelle** [comment]
Yes, that's what I had in mind: a generic DSL that would go to core, not http.

I'd rather have `checkIfOrElse` than `checkIfTrueOrElse`, it would be more consistent with `doIfOrElse`.

Regarding `checkIfResponse`, I wonder if it would be possible to just name it `checkIf` and let type inference do the job of picking the proper overload. I suspect it wouldn't work, but it's worth giving it a try.

**Comment by mxbossard** [comment]
Yeah, I had this in mind too, but it's not simple.
For now I return a Check[R] but I need to return a subclass of it like HttpCheck infered from the nested check. I am working on how to wrap the Check[R] to the final type like HttpCheck.

I'll commit my current implementation.

**Comment by slandelle** [comment]
Sounds like a type class.

**Comment by slandelle** [comment]
I realize having such all-purpose branching DSL won't work. The issue is that we have a user could pass checks of different scopes and/or different body usage strategy in each branch. We really need to be able to determine them before sending the request. But the checkIf condition could depend on data only present when processing the response, for example saved by a prior check.

I think we'd better come up with an API for easily building all purpose checks, plus making it easier to use JsonPath programatically.

WDYT?

**Comment by mxbossard** [comment]
I don't know,

I failed to take time to look at the check scope usage. For now I use it tied to one unique scope and it works for me. Maybe we could tie all nested check scope and throw an error if they are differents.
Plus, the problem appear only for ifCheckOrElse, since ifCheck nest one check only so the scope should be unique.

**Comment by slandelle** [comment]
> Plus, the problem appear only for ifCheckOrElse, since ifCheck nest one check only so the scope should be unique.

Yeah, I think you're right, and we should give up on the `orElse` part. With simple `ifCheck`, we can directly inherit from the wrapped check.
