### ISSUE TITLE
New feature: Results from scenario x are preserved and transformed into a feeder for subsequent scenario

### ISSUE THREAD

**Issue by u6f6o** [gatling/gatling#2928]
Some days ago I created a [question](http://stackoverflow.com/questions/35461350/how-to-execute-a-scenario-using-data-from-the-previous-scenario) on stackoverflow to find out if it's possible to preserve the results from a scenario and reuse the data on a separate scenario. 

It is currently possible to save data from a given request like this: 

`.check(
          jsonPath("userId").saveAs("anId")
        )`

and reuse it right away for the next request. The problem is though, that I cannot create all entities and store the resulting ids somewhere and run a different scenario on this set of ids. My idea would be to have something like this: 

```
val feederForScn2

val scn1 = scenario("scn1).during(5 minutes) {
    ....
    ....
    check(
          jsonPath("userId").addToFeeder("feederForScn2").as("scn1Id")
    )
}
```

**Comment by slandelle** [comment]
I don't think we'll implement such feature in Gatling. Possibly in FrontLine (hence, not open source).

That's something you can implement on your own: in memory queue, such as ConcurrenthashMap, persisted queue, Redis, file, etc...
