### ISSUE TITLE
JMS: Request TransactionIds seem to be reused with multiple submissions of the same execution

### ISSUE THREAD

**Issue by kiggundu** [gatling/gatling#2930]
It appears as if each Execution can be given a unique Transaction ID however It looks like there is no way to get the JMS API to change the transactionID submitted with the message on a per request basis.

**Comment by slandelle** [comment]
`transactionId` is something specific to your application, not JMS. Please provide an example f what your doing.

**Comment by slandelle** [comment]
@kiggundu Could you please provide more information? Otherwise I'll have to close this.

**Comment by kiggundu** [comment]
Apologies,
When we set up a simulation as follows say:
````
setUp(
    scenario("Some test scenario")
       .exitBlockOnFail(
          exec(
              jms("title")
                 .reqreply
                .queue("out-queue")
                .replyQueue("in-queue")
                .textMessage("<... XML containing a transaction id element whose content is  ...>")
                .property("transactionId", generateGuid())
          )
     )
     .inject(constantUsersPerSec(5) during (5))
)
.protocols(<.....the JMS configuration ...>)

)
````

Where each call to generateGuid() will produce a new GUID we find that a single transactionID will be used for all requests submitted to JMS (i.e. the method is only called once and the request reused). This may well be by design though. The consequence was that tracing the load messages through our system was a bit more difficult. Not a show stopper, however would be useful if the API was to provide a means of providing unique values for properties on a per-request basis. Or maybe we are using it wrong. Open to suggestions.

**Comment by slandelle** [comment]
Please read and take into account my previous explanations, both [here](https://github.com/gatling/gatling/issues/2921#issuecomment-187694866) and from our private emails.

`generateGuid()` is only called once when the scenario is built, so it has to return a function that will be evaluated later, not a value.
