### ISSUE TITLE
Core: Debug Request & Response logs are truncated

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2932]
On current master, the trace log of request & response are truncated. For the first requests it's fully logged, but quickly, only the end of the request payload and the full response is logged in my environnement.

It should be kinda like this : 
```
\>>>>>>
Request:
\======
Session:
\======
HTTP request:
\======
HTTP response:
\<<<<<<
```

But in my environment it's  more like this : 
```
(part of request payload)
\======
HTTP response:
\<<<<<<
```

I thought it could be a buffer max size, but apparently, the log for each requests are of inequal sizes.
I saw a new ThreadLocal StringBuilder is used to log this, maybe it could be the cause ?
cf gatling-http/src/main/scala/io/gatling/http/ahc/AsyncHandlerActor.scala

**Comment by slandelle** [comment]
Could you try downgrading slf4j and logback, please?

**Comment by slandelle** [comment]
Found it.

**Comment by slandelle** [comment]
Until the fix gets pushed in the public master, you can the following line at the beginning of the dump method: `tx.request.ahcRequest.getUrl`.

Thanks for reporting!

**Comment by mxbossard** [comment]
Didn't understand how to fix it :D

**Comment by slandelle** [comment]
Insert before this line: https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/ahc/AsyncHandlerActor.scala#L96

**Comment by mxbossard** [comment]
Thank you.
