### ISSUE TITLE
Potential bug : Response body is not valid UTF-8 bytes

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2935]
Hi,
I use the master code.
Sometimes, I got this error among hundreds of similar response which are valid.
I don't know if it's a problem in my application or in gatling, but with the current gatling log output, I can't decide.

```

10:16:27.905 [ERROR] i.g.h.r.StringResponseBody$ - Response body is not valid UTF-8 bytes
10:16:27.907 [TRACE] i.g.h.a.AsyncHandlerActor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
LaunchRandomRapprochement_pollingRequest_3_to_102: OK 
=========================
Session:
Session(devSetup-test,1,... )
=========================
HTTP request:
POST http://xxx.xx/homol-alpha-ihm/UIDL/?v-uiId=1
headers=
Pragma: no-cache
Accept: */*
Referer: http://xxx.xx/homol-alpha-ihm/Individu
Cookie: JSESSIONID=42gL+d7y+jEfb-xe3-NME9pZ.yyy.xxx.xx-hom1-tp02-02
Content-Length: 127
Host: xxx.xx
compositeByteData={"csrfToken":"2affefc0-afd2-4391-80a5-ffca7ff78872","rpc":[["12","com.vaadin.shared.ui.ui.UIServerRpc","poll",[]]],"syncId":48}
=========================
HTTP response:
status=
200 OK
headers= 
Date: Thu, 10 Mar 2016 09:16:28 GMT
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Content-Length: 12389

body=

<<<<<<<<<<<<<<<<<<<<<<<<<

================================================================================
```

How can I find where is the problem ?

**Comment by mxbossard** [comment]
It is somehow a random problem, so it's not simple to reproduce.
Nevertheless, I got multiple of this error quickly on all my simulations.
I found that adding the check bodyBytes.exists seems to resolve the problem, because I cannot reproduce it with this check added.
Since this new check never fail, I think it is a bug in gatling.

**Comment by slandelle** [comment]
What does your original check look like?

**Comment by mxbossard** [comment]
It has a lot of check, I cannot list them all.

Here are the firsts checks : 

```
CheckHelper.securedJsonCheck(jsonPath("$..pollInterval").ofType[Int].optional.saveAs(pollIntervalKey))
, CheckHelper.securedJsonCheck(jsonPath("$..changes..pid").findAll.optional.saveAs(changesPidKey))
, CheckHelper.securedJsonCheck(jsonPath("$..[?(@.pollInterval > " + driver.POLL_INTERVAL_DISABLER + ")]." + driver.KEY_IN_ENTRY_NAME).ofType[String].optional.saveAs(pollingIdKey)).asInstanceOf[HttpCheck]
, regex(""""v-uiId"\s*:\s*([0-9]+)""").ofType[String].optional.saveAs(vuiidTokenKey)
, regex("""\\?"Vaadin-Security-Key\\?"\s*:\s*\\?"(""" + driver.CSRF_TOKEN_MATCHER + """)\\?"""").ofType[String].optional.saveAs(csrfTokenKey)
, regex(""""([0-9]+)"\s*,\s*"com.vaadin.shared.ui.ui.PageClientRpc"""").ofType[String].optional.saveAs(pcRpcKey)
, regex(""""([0-9]+)","com.vaadin.shared.extension.javascriptmanager.ExecuteJavaScriptRpc"""").ofType[String].optional.saveAs(jsRpcKey)
, CheckHelper.securedJsonCheck(jsonPath("$[0].syncId").ofType[Int].find(0).optional.saveAs(syncIdKey))
, CheckHelper.securedJsonCheck(jsonPath("$.uidl.syncId").ofType[Int].find(0).optional.saveAs(syncIdKey))
, CheckHelper.securedJsonCheck(jsonPath("$.uidl.Vaadin-Security-Key").ofType[String].find(0).optional.saveAs(csrfTokenKey))
, status.in(200,304,201,202,203,204,205,206,207,208,209)

, bodyBytes.exists

```
Before adding bodyBytes.exists at the end, the first check was failing like this : 
```
11:51:22.920 [ERROR] i.g.h.r.StringResponseBody$ - Response body is not valid UTF-8 bytes
11:51:22.933 [WARN ] i.g.h.a.AsyncHandlerActor - Request 'request_22_pollingRequest_0' failed: jsonPath($..pollInterval).find(0).noop failed, could not prepare: Boon failed to parse into a valid AST: -1
11:51:22.936 [TRACE] i.g.h.a.AsyncHandlerActor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
request_22_pollingRequest_0: KO jsonPath($..pollInterval).find(0).noop failed, could not prepare: Boon failed to parse into a valid AST: -1
```

**Comment by slandelle** [comment]
Could you please provide a string sample?

**Comment by mxbossard** [comment]
I can, provide a random response. When the problem occurs, I have no response logged, so I need to add a log somewhere to retrieve the problematic response.

**Comment by mxbossard** [comment]
Hi @slandelle ,

I think I found the problem.
I define some "general checks" which I apply on all requests. like ones to get CSRF token for example.
When I use the val keyword to define this check I get the problem. I need to define the check with a def keyword to fix this.

**Comment by slandelle** [comment]
mmm, very weird.

Either creating new check instances (def instead of val) slightly changed some concurrency issue, or your custom checks are statefull but shouldn't.

I re-implemented the UTF-8 decoder but haven't pushed yet.

**Comment by slandelle** [comment]
@mxbossard Could you give the latest snapshot a try, please? It ships a new decoder implementation.

**Comment by mxbossard** [comment]
Ok I'll find some time tommorow to build the last snapshot.

**Comment by slandelle** [comment]
You can just grab the binaries from Sonatype's repo

**Comment by mxbossard** [comment]
ok

**Comment by mxbossard** [comment]
Where is your snapshot repo ? :D

**Comment by slandelle** [comment]
Sonatype, like most Java well-mannered open source libs.
Check the download page.

**Comment by mxbossard** [comment]
For now, I cannot reproduce the problem like I did 2, days ago with my current version.

**Comment by slandelle** [comment]
That's great news, thanks for your feedback!

**Comment by mxbossard** [comment]
Nop, I mean I cannot reproduce by using my current gatling version.
