### ISSUE TITLE
Core: Excessive Actors usage

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2936]
Most actions are stateless and compute very simple Session computations, such as Loop that increment a counter stored in the session.  It's a total waste to use an Actor for this and pay the extra cost of message passing and handling thought an executor. We should only use Actors where needed: extensive computing, scheduling, mutable state (such as correlating requests and responses). Other Actions can be performed sequentially in the calling thread.

**Comment by psilos** [comment]
Have you measured / seen any performance improvements after the refactoring to not use Actors ?

**Comment by slandelle** [comment]
+40% throughput on some use cases
