### ISSUE TITLE
Core: non exitASAP exitBlockOnFail/ tryMax

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2939]
Hi,

When I put an exitBlockOnFail inside another one, the failure is "trapped" by the global one.

Here is a schema of my usage : 

```
Loop 1 {
  exitBlockOnFail 1 {
    code A
    Loop 2 {
      exitBlockOnFail 2 {
        code B => Failure
      }
    }
  code C
  }
}
code D
```

If code B throw a failure, then Loop 2 is exited. Code C is never executed. Only code D is executed.

I think this behaviour is pretty not specified, so do you think it's sound like a bug ? 
Do you think it's implementable on top of existing DSL ?

I think we should decide if exitBlockOnFail 1 absorb failure or not / If exitBlockOnFail 2 propagate failure or not. Or we should have the possibility to add a session => session.markAsSucceeded before the propagation of the failure to the englobant block.

I may need a tryMax(tryChain)(catchChain).

**Comment by slandelle** [comment]
You would need an exitASAP parameter, like loops have. Defalut should be false to no break current behavior.
Not supported atm. Contribution welcome (this one is not risky/complex like the check one).

**Comment by mxbossard** [comment]
So you suggest that with an exitASAP = true we should simply mark the session as succeeded after exiting the enclosing blok. That's it ?

**Comment by slandelle** [comment]
No. I was thinking about a behavior where exit is only evaluated and triggered at the end of the block, instead of for every enclosed component. This way, you get a chance to recover and switch Session status. WDYT?

**Comment by mxbossard** [comment]
I'll make a look on this soon.

**Comment by slandelle** [comment]
cool!

**Comment by mxbossard** [comment]
I am looking at actions implementation. If I understand well, In Loop or TryMax, when chaining, an inner link is added which is the first chain link of the resulting inner chain. The action logic is performed by this first inner link.

So, if I can put a link at the end of the inner chain, I can resume the chain at the end of the inner chain.

Am I wrong ?

**Comment by slandelle** [comment]
No, that's not how it works. Inner action can be forcefully exited, see `ExitableAction`.

**Comment by slandelle** [comment]
Feature request has been idle for too long, closing for now.

Will reopen if someone chimes in with a contribution.
