### ISSUE TITLE
Core: Ramp user / sec not expected when less than 1 user per sec

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2940]
Hi again in here,

I don't get the ramp i expect with rampUsers or constantUsersPerSec. I don't tested yet others injectors.

For example : 
with RampInjection(10,5 minutes) => in 15 secs, all 10 users are running.
with RampInjection(10,30 seconds) => again 15 secs needed to run all 10 users.

Same problem with constantUsersPerSec
The ramp seems to be constant whatever duration we set.

**Comment by slandelle** [comment]
Indeed a bug. We didn't properly distribute values, and this caused this bug when you inject less than 1 user per second.

Thanks for reporting!
