### ISSUE TITLE
Jenkins Plugin: Fail build conditionally.

### ISSUE THREAD

**Issue by phillip-peach** [gatling/gatling#2943]
I have a feature request for the Jenkins Plugin.

My team has been using Gatling and the Jenkins integration for a while and in general we find it great. However sometimes someone will make a change that inadvertently affects performance and it can take a while to notice because of the number of performance and CI tests we have running. We would like to be able to have the Jenkins build fail under certain conditions (eg. exceeding a specified number of Global KO's or Mean or Max time). This would trigger all the alert emails and red lights on the dashboard so we can see our problems.

**Comment by pdalpra** [comment]
This is already possible using [Gatling's assertions](http://gatling.io/docs/2.1.7/general/assertions.html): all official integrations (bundle, Maven & sbt) returns a non zero status code/fail the build if assertions were not validated.

**Comment by phillip-peach** [comment]
Ok my bad, I thought I'd been all through the documents but I guess I missed that. We'll try that. I guess I can close this.
