### ISSUE TITLE
JMS: Extend gatling-jms module with the option to send JMS messages to inbound queue

### ISSUE THREAD

**Issue by pmihalcin** [gatling/gatling#2944]
allowing for creation of background noise in case of message driven systems

**Comment by slandelle** [comment]
@pmihalcin Is this something you plan on contributing?

**Comment by pmihalcin** [comment]
My scala fluency is not huge :) I just opened this to see whether people would be interested

**Comment by pmihalcin** [comment]
I have ActiveMQ running inside Tomcat and would like to send messages to ActiveMQ broker, but with current JNDI only setup, it is not possible because JNDI tree is not exposed by Tomcat
Would it be possible to connect to ActiveMQ broker directly? as it is done in Spring e.g.

**Comment by slandelle** [comment]
Could you elaborate, please?

**Comment by pmihalcin** [comment]
I am referring to the use case where you have ActiveMQ inside Tomcat: http://activemq.apache.org/tomcat.html

If you want to use gatling jms protocol, you are asked to provide JNDI JMS details such as contextFactory, connectionFactoryName
but Tomcat doesn't support remote access to its JNDI tree
hence I can't use gatling jms protocol in actual form

see:
https://stackoverflow.com/questions/744389/tomcat-what-is-the-init-context-params-to-use-for-making-an-external-client-con

As far as I know it is possible to publish a message into ActiveMQ broker without creating InitialContext as it is done in SimpleJmsClient

Not sure if you know what I mean :)

**Comment by slandelle** [comment]
If your queues can't be reached from outside the Tomcat JVM, that the end of the story. Your architecture is not suited for making those queues "testable".
