### ISSUE TITLE
Gatling fails to start with Improperly specified VM option 'ThreadPriorityPolicy=42'

### ISSUE THREAD

**Issue by thomasdarimont** [gatling/gatling#2950]
It seems that the JVM Option `-XX:ThreadPriorityPolicy=42` that is used in `bin/gatling.sh` to work around [Java / Linux Thread Priority oddities](http://tech.stolsvik.com/2010/01/linux-java-thread-priorities-workaround.html) is not supported by the latest Java Version 1.8.0_u74.

Running `bin/gatling.sh` with the JVM property set yields:
```
$ bin/gatling.sh 
GATLING_HOME is set to /home/tom/dev/playground/gattling/gatling-charts-highcharts-bundle-2.1.7
intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
Improperly specified VM option 'ThreadPriorityPolicy=42'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Removing the JVM option resolves the problem.

```
$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
``` 

```
$ uname -a
Linux euler 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by slandelle** [comment]
Fun :)

Thanks for reporting.
Actually, we've already dropped this option in master/upcoming Gatling 2.2 (commit is not public yet).

**Comment by iamzken** [comment]
the same as cassandra
