### ISSUE TITLE
[Report] global information table sorting rules

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2952]
Hi there,

I have some complex simulations with tenth of groups and requests. I named my groups to match an alphanumeric sorting rule : xxx-100 xxx-200 xxx-300 ...

I think it would be cool to be able to sort groups / queries either by name, or by order of emission.
It seems that the current sorting is perform via JS and should be by name, but in my case, groups are not sorted by name. Nether by emission time.

Can someone point me to the sorting rule which I d'ont understand ?

**Comment by slandelle** [comment]
IIRC, it sorts the requests inside the groups. Groups should be sorted by emission.

**Comment by mxbossard** [comment]
I have, sometimes some groups which are not sorted in the same way. I'm sure this groups are executed sequentialy. Maybe there are so close in time, the sorting does not make a difference.

Since we can have multiple scenarios in a report, I would appreciate to have a per scenario separation, or an alphanumeric sorting of groups.

Furthermore, reporting could produce a csv of the table which likely could be manipulated and archived by users.

WDYT ?

**Comment by slandelle** [comment]
I'm thinking: FrontLine!

**Comment by slandelle** [comment]
I'm fine with fixing the sort if it's broken. But new reporting features go into FrontLine.

**Comment by mxbossard** [comment]
In my simulation.log I have this : 
`REQUEST devSetup-test   1       SICOR_30_01-200-Valider_donnes_persos-group     /validerDonneesPersos   1458756509290   1458756531128   OK
REQUEST devSetup-test   1       SICOR_30_01-200-Valider_donnes_persos-group     request_102     1458756531129   1458756531146   OK
GROUP   devSetup-test   1       SICOR_30_01-200-Valider_donnes_persos-group     1458756509059   1458756531146   21855   OK
REQUEST devSetup-test   1       SICOR_30_01-300-Ouvrir_modification_carriere-group      request_104     1458756531147   1458756531163   OK
REQUEST devSetup-test   1       SICOR_30_01-300-Ouvrir_modification_carriere-group      request_105     1458756531164   1458756531172   OK
REQUEST devSetup-test   1       SICOR_30_01-300-Ouvrir_modification_carriere-group      request_107     1458756531165   1458756531179   OK
REQUEST devSetup-test   1       SICOR_30_01-300-Ouvrir_modification_carriere-group      request_106     1458756531164   1458756531179   OK
REQUEST devSetup-test   1       SICOR_30_01-300-Ouvrir_modification_carriere-group      /getRegimesPourCatSocioPro/NC   1458756531180   1458756531202   OK
GROUP   devSetup-test   1       SICOR_30_01-300-Ouvrir_modification_carriere-group      1458756531146   1458756531202   54      OK
REQUEST devSetup-test   1       SICOR_30_01-320-Ajouter_nouvelle_ligne-group    /ajouterModifierCarriere        1458756531205   1458756531357   OK
GROUP   devSetup-test   1       SICOR_30_01-320-Ajouter_nouvelle_ligne-group    1458756531202   1458756531376   152     OK
`
But groups are appearing like this in report table:

# SICOR_30_01-200
# SICOR_30_01-320
# SICOR_30_01-300

**Comment by slandelle** [comment]
Could you send me a private email with your simulation.log please?

**Comment by slandelle** [comment]
Fixed! Thanks for reporting!

**Comment by mxbossard** [comment]
Cool thx !
