### ISSUE TITLE
doSwitchorElse

### ISSUE THREAD

**Issue by JMVM** [gatling/gatling#2959]
Hi all,

I've just tried to raise an Exception from else() in doSwitchOrElse(), if given parameter is not matching any option.

However, it looks like that exception is always thrown, independently of given parameter value.

So it looks like it's an obligatory code to execute a subchain there.

Am I right? For me it would be more useful to raise an exception "on the fly" to notice about a wrong given parameter by command line.

Thanks

**Comment by slandelle** [comment]
Please use the community mailing list for questions, not the bugtracker.
