### ISSUE TITLE
Generate load test scripts from REST API specs

### ISSUE THREAD

**Issue by wilsonmar** [gatling/gatling#2960]
We have an effort going on to generate JMeter and LoadRunner code from specs in Swagger, RAML, WADL, etc. It would be useful to have DSL generated for Gatling too? As I describe in 
See http://github.com/wilsonmar/oss-perf  it is doable now that REST API specs are designed to be complete.  This would be a major revolution because devs won't have to wait for test scripts to be hacked together.

**Comment by slandelle** [comment]
Seems someone asked for the same thing on the Swagger side and answer was "contributions welcome".
Flagging the same way here.

**Comment by slandelle** [comment]
It seems Gatling simulations has just landed in Swagger Codegen and will be shipped in 2.4.0, see https://twitter.com/wing328/status/949949716871069697
