### ISSUE TITLE
The Gatling JMS DSL does not provide for supplying unique property values on a per request basis

### ISSUE THREAD

**Issue by kiggundu** [gatling/gatling#2962]
This is a re-stating of issue #2930 using a test case:

The attached [TransactionIdIssue.scala.txt](https://github.com/gatling/gatling/files/214603/TransactionIdIssue.scala.txt) test case script will generate the following error

> Only objectified primitive objects, String, Map and List types are allowed but was: <function0> type: class uk.co.inps.TaskExecutions$$anonfun$uk$co$inps$TaskExecutions$$initExecution$1
> 	at org.apache.activemq.command.ActiveMQMessage.checkValidObject(ActiveMQMessage.java:538)
> 	at org.apache.activemq.command.ActiveMQMessage.setObjectProperty(ActiveMQMessage.java:504)
> 	at org.apache.activemq.command.ActiveMQMessage.setObjectProperty(ActiveMQMessage.java:488)
> 	at io.gatling.jms.client.SimpleJmsClient$$anonfun$writePropsToMessage$1.apply(SimpleJmsClient.scala:102)
...

The only way to get it to work is to not provide a function for the property set however this results in all the requests having the same transactionID.

**Comment by slandelle** [comment]
Thanks for reporting. Will investigate this afternoon

**Comment by slandelle** [comment]
This is a mistake on your side. I don't know why you went with such design. You're not passing message but functions that build messages. But Gatling doesn't know anything about those functions, so you end up sending them as the messages themselves. And of course ActiveMQ fails to serialize them.

**Comment by slandelle** [comment]
The signature for passing functions to Gatling is to take a Session as input parameter, not nothing. Check how you compute your transaction ids.

**Comment by kiggundu** [comment]
Thanks for the advise. Will make the recommended changes our side.
