### ISSUE TITLE
JMS: support JMSType customization

### ISSUE THREAD

**Issue by mgurov** [gatling/gatling#2967]
It would be nice to be able to be able to invoke/specify value for [setJMSType](https://docs.oracle.com/javaee/7/api/javax/jms/Message.html#setJMSType-java.lang.String-) for the jms message sent by gatling. 
This would allow to test jms listeners that depend on the JMSType.

**Comment by mgurov** [comment]
A quick'n'dirty [patch](https://github.com/gatling/gatling/compare/2.1.X...mgurov:JMSType?expand=1) for internal use has been made based on 2.1.X branch. 

In order to prepare a proper pull request I would like to get a feedback from the gatling community on the question of DSL desired. I abused `.property` for the quick fix. Would we prefer to have explicit holder for JMSType only? Or `.header` next to `.property`? Or maybe a generic callback to modify message before sending?

**Comment by slandelle** [comment]
> Or .header next to .property? 

AFAIK, the JMS API doesn't have generic headers, but specific fields, such as type. I'd rather stick to the JMS API. WDYT?

**Comment by mgurov** [comment]
>  JMS API doesn't have generic headers

Correct. We would have to map header keys to the JMS API calls. Do you have a good idea of exposing the JMS API via the JmsRequestBuilder ? Maybe a generic callback to keep it simple?

**Comment by slandelle** [comment]
We definitively need specific methods directly mapped on the JMS API, eg a `jmsType(Expression[String])`. Many users are familiar with JMS, but not with Scala and functions.

Then, we can have a lower level method that takes a JMS session to message function.
