### ISSUE TITLE
Recorder: SslServerContext assumes the keyStore and KeyManager have the same password

### ISSUE THREAD

**Issue by ttzvika** [gatling/gatling#2971]
In SslServerContext the keyStrore is initialized like so:

``` scala
lazy val keyStore = {
      val ks = KeyStore.getInstance(keyStoreType.toString)
      withCloseable(keyStoreInitStream) { ks.load(_, password) }
      ks
    }
```

and the KeyManager is initialized like so

``` scala
 // Set up key manager factory to use our key store
      val kmf = KeyManagerFactory.getInstance(Algorithm)
      kmf.init(keyStore, password)
```

The code assumes they both use the same password. In reality, if there are two different passwords needed the you will get the an exception:

```
java.security.UnrecoverableKeyException: Cannot recover key
```

**Comment by ggsjyoon** [comment]
Hello. I created a pull-request for the issue #2971. Could you review it when you have free time?

**Comment by slandelle** [comment]
@ttzvika Is having different passwords for the keystore and the key something you actually do? Or is it something you stumbled upon when reading the code?

**Comment by ttzvika** [comment]
@slandelle it is something we actually did. To work around this we changed the keymanager password to be the same as the keystore password which solved the problem

**Comment by slandelle** [comment]
Good to know. As this usage is not very common, and there's an easy workaround, that's not really a priority for us. Contribs welcome.

**Comment by ggsjyoon** [comment]
Should I re-open my PR?

**Comment by ttzvika** [comment]
Only if others find interest in it as well

**Comment by slandelle** [comment]
@ggsjyoon And your PR was missing the UI part.

**Comment by ggsjyoon** [comment]
My bad. You're right.

**Comment by slandelle** [comment]
@ggsjyoon Please ping me if you can come up with a more complete version :)

**Comment by slandelle** [comment]
This feature request has been idle for a very long time. Closing for now.
