### ISSUE TITLE
HTTP: test hanging

### ISSUE THREAD

**Issue by rebrowning** [gatling/gatling#2973]
Currently when I run the following test (both the machine running the test, and the machine I'm testing against are in GCE, at the same location) the "active" count will hang indefinitely, causing the test to never complete.

```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class SingleInstance extends Simulation {
  val instance = "sandbox-search.vadio.com/v1.0"
  val httpConf = http
    .baseURL("https://"+instance)
    .acceptHeader("*/*")
    .doNotTrackHeader("1")
    .acceptLanguageHeader("en-US,en;q=0.8")
    .acceptEncodingHeader("gzip, deflate")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36")

  val sos = scenario(s"Full Chain")
    .feed(csv("onlygoodsongs.csv").random.circular) // This is a csv of around 10k artist/title combinations
    .exec(http("full chain").get("/video?artist=${artist}&title=${title}&country=US&api_key=ltkeyfordoingthingssometimes")
      .transformResponse {
        case resp if resp.statusCode.get == 200 =>
          resp
        case resp =>
          println("Response Code: " + resp.statusCode.get.toString + "\n" +
            "Response Request URL: " + resp.request.getUrl + "\n" +
            "Response Body: " + resp.body.string + "\n" +
            "Response Headers: " + resp.headers.toString + "\n")
          resp
      }
      .check(status.is(200))
      .check(regex("videoId").find(0).exists)
    )

  setUp(
    sos.inject(constantUsersPerSec(400) during(60 seconds) randomized)
  ).protocols(httpConf)
}
```

Sample set from onlygoodsongs.csv
```
artist,title
Slipknot,Duality
Slipknot,Wait and Bleed
Slipknot,Vermillion
Chimaira,Empire
Chimaira,Resurrection
Chimaira,Pure Hatred
Heaven Shall Burn,Enziet
Heaven Shall Burn,Hunters Will Be Hunted
Amon Amarth,Twilight of the Thunder God
White Zombie,Thunder Kiss '65
Alice In Chains,Rooster
White Zombie,More Human Than Human
Bring Me The Horizon,Sleepwalking
Bring Me The Horizon,Drown
Bring Me The Horizon,Go To Hell For Heaven's Sake
Pierce The Veil,King for a Day
Sleeping With Sirens,If You Can't Hang
Bring Me The Horizon,Shadow Moses
Bring Me The Horizon,Can You Feel My Heart
Parkway Drive,Vice Grip
Parkway Drive,Crushed
Five Finger Death Punch,Wrong Side Of Heaven
Pierce The Veil,Bulls In The Bronx
A Day To Remember,All I Want
Taylor Swift,I Knew You Were Trouble
Post Malone,White Iverson
Amon Amarth,First Kill
Robin Schulz,Sugar
Slipknot,Snuff
Slipknot,The Devil In I
Slipknot,Dead Memories
Slipknot,Killpop
Fall Out Boy,Irresistible
Fall Out Boy,Uma Thurman
Fall Out Boy,Centuries
Fall Out Boy,Immortals
Caliban,We Are The Many
Insomnium,While We Sleep
Caliban,Devil's Night
Arch Enemy,You Will Know My Name
Drake,Hotline Bling
Sia,Alive
Adele,Hello
Owl City,Fireflies
Bring Me The Horizon,Throne
Born of Osiris,Bow Down
Bullet For My Valentine,Worthless
Mudvayne,Dig
Mudvayne,Death Blooms
Mudvayne,Forget to Remember
```

For the above test I may end up with the following test message 
```
================================================================================
2016-04-13 08:08:25                                         200s elapsed
---- Full Chain test -----------------------------------------------------------
[##############################################################------------] 84%
      waiting: 0      / active: 3728   / done:20362 
---- Requests ------------------------------------------------------------------
 Global                                                   (OK=20362  KO=0     )
================================================================================
```

As you can see the expected 60 second test has gone on for 200 seconds at this point, the "active" number is the same at 200 seconds as it was at 60 seconds.

my reference.conf is 
```
gatling {
  http {
    ahc {
      requestTimeout=7000
      maxRetry=0
      sslSessionTimeout=7000
    }
  }
  data {
    noActivityTimeout=5
  }
}
```

I have tried adding `-Djava.net.preferIPv4Stack=true`, but it doesn't remedy the situation.

Original stackoverflow post: https://stackoverflow.com/questions/36602870/force-gatling-io-test-to-fail-connections-after-a-certain-duration

If there's anything I can do to help, let me know.

**Comment by slandelle** [comment]
Answer is still the same, please provide a complete reproducer **with the app**. You can send private information by email if you want.

**Comment by rebrowning** [comment]
I sent an email asking for clarification on what you mean by a complete reproducer with the app, will update when I get a response.

**Comment by slandelle** [comment]
Thanks

**Comment by rebrowning** [comment]
I haven't received an email back for clarification on what was meant by a "complete reproducer with the app". However I have updated the original question with the full script (hitting the correct endpoint) as well as a temp API key. I have also selected a small amount of items from the csv file that is being drawn from for the feed.

If there is something else you need, please explain.

**Comment by slandelle** [comment]
Thanks, that should suffice!
I'm on vacation atm, I'll investigate next week.

**Comment by slandelle** [comment]
I could reproduce. Investigating atm.

**Comment by slandelle** [comment]
The root cause is a user issue. There's a very good reason for `resp.statusCode` to be an `Option`: it can indeed be missing, eg if we couldn't connect the socket under heavy load.

Lesson learnt: NEVER use `.get` on an `Option`. Use `map` or pattern matching.

Then, we'll handle such crashes more gracefully, see #3005

**Comment by rebrowning** [comment]
Excellent... It didn't even occur to me that statusCode may not be set.

Thanks for looking into this and figuring it out!

**Comment by rakeshnambiar** [comment]
HI @slandelle .. I am not using any get method, but still facing this issue.

val feeder = csv("epmcData.csv").circular

  val header = Map(
    "Content-Type" -> "text/xml;charset=UTF-8",
    "SOAPAction" -> "",
    "Operation" -> "searchPublications",
    "Style" -> "Document",
    "Type" -> "Request-Response",
    "Host" -> "ves-hx-30:8090"
    )

  val scn = scenario("SOAP API Without Snippets")
      .feed(feeder)
      .exec(http("Search_Publications")
      .post("")
        .headers(header)
          .body(StringBody("<?xml version=\"1.0\" encoding=\"UTF-8\"?> <soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:web=\"http://webservice.cdb.ebi.ac.uk/\">   <soapenv:Header />   <soapenv:Body>      <web:searchPublications>         <queryString>"
            + "${SearchKey}" +"</queryString>         <resultType>core</resultType>         <cursorMark>*</cursorMark>         <pageSize>1000</pageSize>      </web:searchPublications>   </soapenv:Body> </soapenv:Envelope>"))
             .check(status.is(200).saveAs("status_code"))
              .check(bodyString.transform(_.contains("resultList")).is(true))
               .check(bodyString.transform(_.contains("authorList")).exists)
                  .check(bodyString.transform(_.contains("${SearchKey}")).exists)
                    .extraInfoExtractor(extraInfo => List(extraInfo.request.toString, extraInfo.response.body.string,extraInfo.session))
    )

  setUp(scn.inject(atOnceUsers(50)).protocols(httpConf))
    .assertions(
        global.responseTime.max.lte(3500),
        global.successfulRequests.percent.gte(100)
      )

Could you please check and advice? With random data, it's working fine.

**Comment by slandelle** [comment]
@rakeshnambiar Impossible to investigate without you providing an actionable reproducer.

**Comment by atoolchain** [comment]
Hi @slandelle 
I ´am trying to run a test against a page, where I redirect (302) images to a google bucket, instead of local serving the files to reduce the throughput.
But I run in a Problem where my scenario gets hanging and never finish the test.

The thing I don’t understand when I run the test without the redirect and serving the files direct, the scenario is slow but gets finished. I’m using gatling-charts-highcharts-bundle-2.3.0, but I get the same behaviour with 2.2.5 and 2.3.1

I can’t show the simulation class public

What I have to change to get test finished again, with redirect?
Please any suggestions it looks like a bug

Best regards
alex

**Comment by slandelle** [comment]
> I can’t show the simulation class public

Please implement a reproducer that you can share, even privately (slandelle at gatling dot io).

**Comment by atoolchain** [comment]
hi i have send you a reproducer
