### ISSUE TITLE
Why no STATISTICS data in the gatling results???

### ISSUE THREAD

**Issue by kangwen6663** [gatling/gatling#2974]
![2016-04-19_13-42-33](https://cloud.githubusercontent.com/assets/7346217/14628958/4a48ce3a-0635-11e6-8351-a6f082207126.jpg)

**Comment by kangwen6663** [comment]
It ran at our jenkins server, could you give some advice to this problem?

**Comment by slandelle** [comment]
Because Jenkins is #@*$.
See [changelog](https://wiki.jenkins-ci.org/display/JENKINS/Gatling+Plugin) and #2889
