### ISSUE TITLE
HTTP logging regression

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2975]
I've cloned the gatling-sbt-plugin-demo project and enabled logging for ALL HTTP request and responses:

However, the HTTP requests and responses are not logged to the console. 

I've reverted to the previous commit (i.e. 2.1.7):
$ git reset --hard 77f9c67d25b6bcc9

And again enabled trace logging. The request and responses are now logged to the console.

**Comment by slandelle** [comment]
Just the logback.xml that wasn't up to date. Thanks for reporting.

**Comment by aidylewis** [comment]
Probably need also to update the README:

1. SBT 0.13.8 => 0.13.11
2. testOnly computerdatabase.BasicSimulation => gatling:testOnly computerdatabase.BasicSimulation
3. test => gatling:test ?

**Comment by slandelle** [comment]
Indeed. Thanks!
