### ISSUE TITLE
App: conf directory is missing from bundle

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2977]
@notdryft Alert!

cc @pdalpra

**Comment by pdalpra** [comment]
fixing it in the evening

**Comment by slandelle** [comment]
would be awesome, I could then republish

**Comment by slandelle** [comment]
I just verified it's not a regression caused by upgrading gatling-highcharts module's sbt-native-packager from 0.6.4 to 0.8.0

**Comment by slandelle** [comment]
The `conf` directory is present in `gatling-bundle` but seems to not be copied when repackaging `gatling-highcharts-bundle`

**Comment by slandelle** [comment]
So, actually, for some reason, the `gatling-bundle`'s `conf` directory is present in my maven local repository, but is missing from the one on maven central.

**Comment by slandelle** [comment]
Republishing `gatling-bundle`. Once the fixed version will be up in maven-central, will republish `gatling-highcharts-bundle` too. No idea what happened o_0

**Comment by pdalpra** [comment]
I noticed that sometimes file generation acts funny when not running from a clean project. Did you release with `gatling-build` ?

**Comment by slandelle** [comment]
No, I released manually from my existing projects.

**Comment by slandelle** [comment]
I could be a conflict with IntelliJ trying to refresh resources at the same time...

**Comment by slandelle** [comment]
Republished
