### ISSUE TITLE
Core: Constant pause not impacted by force.

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2989]
Hi there,

I actively use a fixed pause which cannot be disabled or modified by force (see PauseBuilder).
My need is a technical pause fixed by the server for the client. I don't want this pause disabled, uniformely modified or anything else.

My feature is not compatible with the 2.2.0 release, so I will test an update and submit a pull request if you are interested.

For now I propose an alternate "ConstantNotForcablePauseBuilder". Do you see another way to do this ?

**Comment by slandelle** [comment]
Wouldn't adding an `overridable` boolean parameter with a default value of `false` suffice?

**Comment by mxbossard** [comment]
Yeah, ok I'll work on this. I originally wanted to not modify the PauseBuilder.

**Comment by slandelle** [comment]
Great!

**Comment by mxbossard** [comment]
I wonder if I need this, because I just saw that ctx.pauseType seems only to be a fallback.
So if I enforce the PauseType in a pause exec chain, It should not be override if I disabled all pauses with .disablePauses on the PopulationBuilder, right ?

**Comment by slandelle** [comment]
Right.
I think this can be closed.
