### ISSUE TITLE
Core: strict vs not strict inequalities in Assertions

### ISSUE THREAD

**Issue by anna-zzz** [gatling/gatling#2993]
Part of my simulation definition is `assertions(global.failedRequests.percent.lessThan(100))`
Gatling output:
```
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                            0 (  0%)
> 800 ms < t < 1200 ms                                  0 (  0%)
> t > 1200 ms                                           0 (  0%)
> failed                                               60 (100%)
    <some output skipped>
Global: percentage of failed requests is less than 100 : true
```
This seems a bit misleading (especially the last line), I wonder if `lessThan` and `greaterThan` should be strict inequalities and API should also provide `lessThanOrEqual` and `greaterThanOrEqual` or something like that?
[Documentation](http://gatling.io/docs/2.1.7/general/assertions.html#condition) does not say anything about strictness either.

**Comment by slandelle** [comment]
I agree.

This can only go in 2.3, as it would be an API breakage (even if it's for the better).
Would you be interested in contributing?

**Comment by anna-zzz** [comment]
Sorry for getting back so late — yes, I'd absolutely love to contribute.

**Comment by slandelle** [comment]
* Let's drop `greaterThan` and `lowerThan`
* Introduce `gt`, `gte`, `lt`, `lte`
* Add optional parameters on `between` with default value to exclude bounds
