### ISSUE TITLE
HTTP: Improve JsonPath null values checks

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2997]
It's currently only possible to fetch a null value when explicitly setting the type to `Any` (using `ofType`).
It would be nice to also support it for the other types.

**Comment by Srisaibersys** [comment]
Hi @slandelle 

We have used Gatling version 2.2.3

   ```
 compile ('io.gatling:gatling-core:2.2.3')
    compile ('io.gatling:gatling-app:2.2.3')
    compile ('io.gatling.highcharts:gatling-charts-highcharts:2.2.3')
```
We are checking error as below,

`.check(jsonPath("$.workOrderInfo").ofType[String].is("null"))`

But, get error as 

`failed: jsonPath($.workOrderInfo).find.is(null), but actually found null`

Is this still an issue in Gatling or am I missing something?

Thanks,
Navya

**Comment by jmflaherty-dsc** [comment]
@Srisaibersys , try like this:

`.check(jsonPath("$.workOrderInfo").ofType[Any].is(null))`

As null is a type, not a String.

It works for me with 2.2.3, which is the same one that you have.

**Comment by jmflaherty** [comment]
@Srisaibersys , try like this:

`.check(jsonPath("$.workOrderInfo").ofType[Any].is(null))`

As null is a type, not a String.

It works for me with 2.2.3, which is the same one that you have.

**Comment by swapnil-kotwal-sp** [comment]
Here is appropriate solution i got finally https://stackoverflow.com/a/45557250/1665592

Gatling should implement it.

**Comment by slandelle** [comment]
Here's the plan for Gatling 3: #3341
