### ISSUE TITLE
[feature request] httpRequest with method as expression

### ISSUE THREAD

**Issue by manonthemat** [gatling/gatling#3000]
I'd be great, if there was the ability to make a httpRequest with signature (method: Expression[String], url: Expression[String]).

I've explained my use case in this [StackOverflow question](
http://stackoverflow.com/questions/37013490/gatling-httprequest-with-dynamic-method-from-collection).

**Comment by slandelle** [comment]
You didn't actually describe your use case, but an implementation.

Why do you need to pass a dynamic method exactly?

**Comment by manonthemat** [comment]
Sure, let me shed a little light on my situation, so you can decide if that's a useful scenario and a good idea to support HTTP methods in a more dynamic matter.

As you can see in the code sample, I use a collection of a custom data structure. There are several reasons for choosing this over a CSV or Json Feeder. We might get our raw data from several external sources with varying formats (csv, text files, json, etc). The data needs to be processed and enriched (applying different access tokens for example), before we can use it. In the end we'll have a sanitized list with several objects with title (descriptor for results page), method (to use in http request), endpoint (url), requiredParameters (a query map), code (for response code check).

Does this make sense to you?

**Comment by slandelle** [comment]
There's still something that bugs me: usually, requests don't have the same look depending on the method used, eg `GET`s tend to not have a body while `POST`s do. So you can't just use a dynamic method, you need to route on different branches with a `doSwitch`.

**Comment by manonthemat** [comment]
That's a good argument, and I have actually incorporated doSwitch in the meantime. There's some unnecessary code duplication, but this might be the better solution for many cases anyway. Therefore closing this issue and thanking for the open ear and suggestion.
