### ISSUE TITLE
Doc: Mention maiha's AMQP plugin instead of fhalim's

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3008]
The later is now longer active

**Comment by LuboVarga** [comment]
There is also obsolete link on this documentation subpage: http://gatling.io/docs/2.2.0/extensions/index.html

**Comment by LuboVarga** [comment]
List of extensions here: http://gatling.io/docs/2.2.0/extensions/index.html is not in sync with list here: http://gatling.io/docs/2.2.0/extensions/index.html Minimally rabbitmq (amqp) protocol plugin is on about page obsolete.

**Comment by slandelle** [comment]
The documentation sources have been updated in our private repository, but haven't been pushed in the public repo yet. Will do next week probably, when we'll release 2.2.1.
