### ISSUE TITLE
HTTP inferred resources requests

### ISSUE THREAD

**Issue by JMVM** [gatling/gatling#3010]
Hi there,

If we configure with **inferHtmlResources** in order to get inferred resources requests, only a few ones of them are done, but not all of them. For example, images are not downloaded.

That's the expected behaviour? We were expecting requests for **all static resources** at least, how browser would do.

Thanks

**Comment by slandelle** [comment]
The documentation explains which resources can be inferred: http://gatling.io/docs/2.2.0/http/http_protocol.html#resource-inferring

Gatling is not a browser, so it won't trigger your javascript and won't apply your CSS rules on a DOM which would trigger css images download.

Then, please use the community mailing for questions, not the bug tracker.

**Comment by JMVM** [comment]
Raised in Gatling mailing list.

Thanks
