### ISSUE TITLE
doSwitchOrElse with Exception

### ISSUE THREAD

**Issue by JMVM** [gatling/gatling#3011]
Hi there,

As part of performance script, the idea is to have a **doSwitchOrElse()** with each possible page under test as parameter, throwing an exception otherwise.

For example, something like this:

```
var page = "google"
    val load = doSwitchOrElse(page) ( "yahoo" -> exec(),
                         "google" -> exec()
                         ) (
                      throw new Exception("Hello World!")
                  )
```

The point is **Exception seems to be thrown always**, even if parameter is matching one of possible ones in **doSwitchOrElse()**. For code above, the console output is the next one:

**Caused by: java.lang.Exception: Hello World!
        at com.example.TestHandler$.<init>(TestHandler.scala:83)
        at com.example.TestHandler$.<clinit>(TestHandler.scala)
        ... 26 more**

Possible bug or not well controlled behavior? If so, please could you include in next releases?

Thanks

**Comment by slandelle** [comment]
This is a user issue. Please use the community mailing list for questions.

**Comment by JMVM** [comment]
Raised in Gatling mailing list.

Thanks
