### ISSUE TITLE
Support real templating engine

### ISSUE THREAD

**Issue by mtheus** [gatling/gatling#3028]
Mustache has more powerful features than EL, like: if, foreach, context, etc. 
With mustache support I could work with more complex objects without support this thing by hand in scala giving me more productivity. 

Ex.: [scalate](http://scalate.github.io/scalate/documentation/mustache.html#features)

```
/* user-files/request-bodies/myFileData.json */
[
    {
        "name": "John",
        "tags": ["java", "scala", "es6"]
    },
    {
        "name": "Kelvin",
        "tags": ["vb", "ruby", "python"]
    }   
]
```

```
/* user-files/request-bodies/myFileBody.json */
{ 
    "myContent": "{{myValue.name}}" 
    "myValues": [
        {{#myValue.tags}}
          {{^first}},{{/first}}
          "{{value}}"
        {{/myValue.tags}}
    ]
}
```

```
/* Scenario */
val jsonFileFeeder = jsonFile("myFileData.json")
http("Template Body")
   .exec { session =>
      session.set("myValue", jsonFileFeeder) // Figure out if this works, 
   }
  .post("my.post.uri")
  .body(MustacheFileBodies("myFileBody.json")).asJSON

```

**Comment by slandelle** [comment]
I don't think we'll investigate this direction any time soon.

IMO, Scala has powerful tools such as multiline Strings and macros that make template engines pretty useless, see http://gatling.io/docs/2.2.1/http/http_request.html#request-body

But if you're willing to give it a shot, we'll gladly review a pull request and merge if it makes sense.

**Comment by slandelle** [comment]
FWIW, Scalate is a kind of dead project. We used it in Gatling 1 and ditched it because it was very painful to use and lacking maintenance (Scala 2.10 support came late, so 2.11 did, what will happen for 2.12?).

There seems to more active implementation that don't rely on code generation, such as [scala-mustache](https://github.com/vspy/scala-mustache) and [handlebars.scala](https://github.com/mwunsch/handlebars.scala).

**Comment by slandelle** [comment]
Mustache is logicless so it doesn't add much value compared to Gatling EL.
We're going to support Peeble.
