### ISSUE TITLE
Core: More users injected than defined

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#3029]
Hi everyone,

When I define an injection profile like this : 
```scala
Seq(rampUsers(50) over(9 minutes),
  nothingFor(1 minute),
  rampUsers(50) over(1 minute),
  nothingFor(9 minutes),
  rampUsers(50) over(1 minute),
  nothingFor(9 minutes),
  rampUsers(50) over(1 minute),
  nothingFor(9 minutes),
  rampUsers(50) over(1 minute),
  nothingFor(9 minutes)
)
```

I end up with more than 250 users, like 1 or 2 users which were not invited to the party.
Maybe a problem inherent to less than 1 user / sec rate ?

As usual, thanks for your great work.

**Comment by slandelle** [comment]
A bug indeed thanks for reporting!
