### ISSUE TITLE
Part custom header name value separator is not generated in actual payload

### ISSUE THREAD

**Issue by ivanursul** [gatling/gatling#3030]
I was playing around with gatling tool, and found one thing, which looks completely unintuitive for me:
If I want to setup a header for BodyPart,I need to do it in quite unintuitive way:

```scala
.header("Content-Length:", "35260")
```

By adding colon after Content-Length. Guys, it's completely unintuitive, and It took me a while to understand what's going on.
Please, refer to following stackoverflow question
http://stackoverflow.com/questions/37411987/unable-to-set-correct-bodypart-header-in-gatling/37412021#37412021

**Comment by slandelle** [comment]
See https://github.com/AsyncHttpClient/async-http-client/issues/1168

**Comment by ivanursul** [comment]
Cool, thanks
