### ISSUE TITLE
How to get mean requests/sec?

### ISSUE THREAD

**Issue by hzq376768908** [gatling/gatling#3031]
I have done a test,but I found my req/s is very large. For example, the total requests is 15136 then req/s is 125090.909. So I don't understantd the way of req/s

---- Global Information --------------------------------------------------------
> request count                                       6000 (OK=6000   KO=0     )
> min response time                                    122 (OK=122    KO=-     )
> max response time                                   5316 (OK=5316   KO=-     )
> mean response time                                  1264 (OK=1264   KO=-     )
> std deviation                                        361 (OK=361    KO=-     )
> response time 50th percentile                       1315 (OK=1315   KO=-     )
> response time 75th percentile                       1531 (OK=1531   KO=-     )
> mean requests/sec                                222222.222 (OK=222222.222 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                           605 ( 10%)
> 800 ms < t < 1200 ms                                1688 ( 28%)
> t > 1200 ms                                         3707 ( 62%)
> failed                                                 0 (  0%)

**Comment by slandelle** [comment]
Which version do you use?
If you use an old version, can you reproduce with the latest one?
If you can still reproduce with the latest version, can you please provide a reproducer?

**Comment by slandelle** [comment]
Closing for now.
Feel free to reopen if you can provide more information.
