### ISSUE TITLE
Action.recover spams log for expected errors

### ISSUE THREAD

**Issue by jrudolph** [gatling/gatling#3035]
Action.recover logs errors unconditionally even if the action was executed inside `tryMax` where errors are expected. It seems the behavior was introduced here: https://github.com/gatling/gatling/blob/ff7a3307df2f207619f101aa887963499c8416f7/gatling-core/src/main/scala/io/gatling/core/action/Action.scala

It would be nice if only final errors would be logged and not errors from which tryMax will eventually recover.

**Comment by slandelle** [comment]
Hey @jrudolph 

Awesome to see you there!

Are you saying that Gatling 2.1 didn't log those? I would expect [it would](https://github.com/gatling/gatling/blob/2.1.X/gatling-core/src/main/scala/io/gatling/core/action/Actions.scala#L72).

Then, I agree with your point. Will check this a bit later, spent the day at a conference, I'm dead tired...

**Comment by jrudolph** [comment]
Yes, we updated from gatling 2.1.5 where those weren't logged. I guess we may be using gatling wrong. What we have is basically something like this where we want to execute `someRequest` in a loop until `someCondition` holds. This was implemented like this:

```scala
.tryMax(...)(exec(someRequest).doIf(!someCondition)(exec(session => Failure(...))
```

AFAICS the new logging comes from the `exec(session => Failure())` part which is implemented by `SessionHook` which was wrapped in `recover` since the above commit: https://github.com/gatling/gatling/commit/ff7a3307df2f207619f101aa887963499c8416f7#diff-64502ac21fb2f3bf612afd2bc496b6d7L47

**Comment by jrudolph** [comment]
Ah, no, this was exactly what `Failable` should have done before as you pointed out. So, I don't know why this changed.

**Comment by slandelle** [comment]
I suspect we've raised the logging level in 2.1.6 or 2.1.7 and missed your use case.

**Comment by slandelle** [comment]
I just tried the following sample with 2.1.5:

```scala
val scn = scenario("scenario")
  .exec(http("Home").get("http://gatling.io/"))
  .tryMax(2, "i") {
    doIfOrElse(_("i").validate[Int].map(_ < 1)) {
      exec { session =>
        session("i").validate[Int].flatMap { i => Failure("Try" + i) }
      }
    } {
      exec { session =>
        session("i").validate[Int].map { i =>
          println(s"Try $i is fine")
          session
        }
      }
    }
  }

setUp(scn.inject(atOnceUsers(1)))
```

And I got the following logs:
```
11:42:13.411 [ERROR] i.g.c.a.b.SessionHookBuilder$$anonfun$build$1$$anon$1 - 72 - 'sessionHook-2' failed to execute: Try0
Try 1 is fine
```

It looks to me recover was already logging such failures in 2.1.5. Are you sure you didn't filtered those logs explicitly in `logback.xml`?

**Comment by slandelle** [comment]
Then, back to your use case, if what you really do is `exec(session => Failure(...)` in order to trigger the retry, you should just be using `session.markAsFailed` instead.

**Comment by jrudolph** [comment]
Thanks, @slandelle for looking into it.

> Are you sure you didn't filtered those logs explicitly in logback.xml?

No, not explicitly at least. It seems, we didn't have any explicit logging configuration before so we may have inherit some configuration from one of the dependencies. I'll look into that and report back.

> Then, back to your use case, if what you're really doing is exec(session => Failure(...) in order to trigger the retry, you should just be using session.markAsFailed instead.

Ok, but `session.markAsFailed` wouldn't allow us to actually report an error with this message if the tryMax finally fails, right?

**Comment by slandelle** [comment]
> Ok, but session.markAsFailed wouldn't allow us to actually report an error with this message if the tryMax finally fails, right?

Correct. But you would not see the Failure in the reports either, only in the logs.

We're considering some major reporting changes atm but those will only land in the next major version (and private milestones for our customers).
Our current reporting model is very bound to the HTTP1 request-response transactions logic.
Errors can only be logged when attached to a request, but detached in a `exec(function)` like you do.

BTW, why don't you trigger the retry from a request check? Is it because you want to see the intermediate requests as successes and not failures?

**Comment by jrudolph** [comment]
>> Are you sure you didn't filtered those logs explicitly in logback.xml?

> No, not explicitly at least.

I stand corrected. Turns out we did exactly this but buried deep down in the classpath. So, the issue for us was that only the name of the logger changed from

```
io.gatling.core.action.builder.SessionHookBuilder$$anonfun$build$1$$anon$1
```

to

```
io.gatling.core.action.builder.SessionHookBuilder$$anon$1
```

So, you were right, the behavior never changed. It's just a bit annoying that these things are logged in the first place :) Sorry for the fuss.

**Comment by slandelle** [comment]
> I stand corrected. Turns out we did exactly this but buried deep down in the classpath.

Crystal ball win!

> It's just a bit annoying that these things are logged in the first place :) Sorry for the fuss.

No pro. What's actually a pity is that we didn't get this feedback early (before releasing 2.2). This make perfect sense to have such issues reported somewhere, not just logged.

May I ask what you guys use Gatling for (I can perfectly understand if it's not public)? Is it to load test akka-http from a different stack?

**Comment by jrudolph** [comment]
> BTW, why don't you trigger the retry from a request check? Is it because you want to see the intermediate requests as successes and not failures?

That's a good point, at other places we recently did exactly this and replaced the `doIf` construction with a `check` because otherwise (using `doIf`) the global assertions wouldn't fail because no requests had failed but only the `exec(_ => Failure)` which would abort the scenario but wouldn't fail the assertion.

> May I ask what you guys use Gatling for (I can perfectly understand if it's not public)? Is it to load test akka-http from a different stack?

Not related to akka-http this time. I guess it's a standard use case for gatling in a client project.

**Comment by slandelle** [comment]
More thinking about your use case and your implementation of it, IMO:

* If you want the request to be retried to be reported as a failure when the condition is not met: use `tryMax`. Typical usage is "under load, my login process sometimes fail, and users will retry a given number of times before giving up".
* If you want the request to still be reported as a success: use an `asLongAs` loop instead
* If you only want the last tentative to be a failure, you can work it around with an `asLongAs` loop, and switch from a `dontValidate` to a `exist` check depending on the loop index. Pita but doable.

**Comment by slandelle** [comment]
If you're ok with that, can I close this?

The recommended way to trigger a `tryMax` retry is either to have a failing request, or manually make the Session as failed. An `Action` returning a `Failure` is considered an unexpected error and is logged as such.

**Comment by jrudolph** [comment]
Ok, so this issues is basically a user error here, right?

`Action` is supposed to be only executed for the side-effects, so it makes no sense to propagate the error, thus it is needs to be reported immediately? Otherwise, I could use `check` or one of the alternatives you are proposing above.

Thanks for clearing that up for me.

**Comment by slandelle** [comment]
Thanks a lot for all your awesome work!
We're currently playing with perf-map-agent and your old json-lenses are on our plate (we'd like to have lenses for editing JSON in Gatling). 😄
