### ISSUE TITLE
sbt previewSite fails with compilation error

### ISSUE THREAD

**Issue by henri-tremblay** [gatling/gatling#3036]
The error seems real from my code reading (even though I'm not a scala expert). Just type `sbt previewSite` on the current master HEAD (93c0b14583eae5eb28109a1c534edda99fe9d70c)

```
[error] /Users/me/dev/github/gatling/gatling-benchmarks/src/main/scala/io/gatling/http/request/builder/HttpRequestExpressionBuilderBenchmark.scala:47: not enough arguments for method apply: (httpProtocol: io.gatling.http.protocol.HttpProtocol, httpEngine: io.gatling.http.ahc.HttpEngine, httpCaches: io.gatling.http.cache.HttpCaches, responseProcessor: io.gatling.http.ahc.ResponseProcessor)io.gatling.http.protocol.HttpComponents in object HttpComponents.
[error] Unspecified value parameter responseProcessor.
[error]   private val httpComponents = HttpComponents(
[error]                                              ^
[error] /Users/me/dev/github/gatling/gatling-charts/src/main/scala/io/gatling/charts/stats/LogFileReader.scala:108: The referenced trait AssertionPath does not have any sub-classes. This may happen due to a limitation of scalac (SI-7046) given that the trait is not in the same package. If this is the case, the pickler may be defined using boopickle.CompositePickler directly.
[error]             Unpickle[Assertion].fromBytes(ByteBuffer.wrap(bytes))
[error]                     ^
[info] No documentation generated with unsuccessful compiler run
[error] two errors found
[error] (gatling-parent/scalaunidoc:doc) Scaladoc generation failed
[error] Total time: 16 s, completed Jun 2, 2016 5:09:22 PM
```
sbt version is 0.13.11. Scala version is 2.11.8

**Comment by slandelle** [comment]
* first error shouldn't happen, `gatling-benchmarks` is supposed to be excluded
* second error (Boopickle) is WTF. Seems scalac can't properly trigger the macro. Let's see if upgrading sbt-site fixes things.

**Comment by henri-tremblay** [comment]
For the first error, do you mean I should exclude it in some way or it is
an error in the script?

I'm launching the command from the root of the project.

**Comment by slandelle** [comment]
The first error is a compile one in a module that shouldn't be in the scope of this task. The compile error itself is easy to fix (it already is in our private branch). But I'd like to have the sbt set up fixed.
The second one seems to be fixed by upgrading the sbt-site plugin, which is not backward compatible. @notdryft seems to have it working but we'll do some proper tests tomorrow.

All in all, we'll get this fixed soon.

**Comment by henri-tremblay** [comment]
Great. Thanks
Le 2 juin 2016 8:50 PM, "Stephane Landelle" <notifications@github.com> a
écrit :
