### ISSUE TITLE
HTTP: Support for HTTP/2

### ISSUE THREAD

**Issue by wilsonmar** [gatling/gatling#3042]
Question: Does Gatling support HTTP/2?

**Comment by aha-oretama** [comment]
[aync-http-client](https://github.com/AsyncHttpClient/async-http-client) which is used in Gatling, does not support HTTP/2.

Here is the detail.
https://github.com/AsyncHttpClient/async-http-client/issues/1096

So that, I think that Gating does not support HTTP/2.

**Comment by vijaycse** [comment]
Great. Thank you.  Any dates to release?
