### ISSUE TITLE
HTTPprotocol - feeders and domain case sensitivity 

### ISSUE THREAD

**Issue by welker90** [gatling/gatling#3046]
with Http protocol -  can you add the ability to have a feeder so that you can put parameters in the the protocol.  For instance, parameterize different users with authentication in the HTTP protocol.

Also, it appears that the domain for ntlmauth (haven't tried it with others) is case sensitive - only works with upper case (lower case causes unauthorized).  Is it possible to make this ignore case?

**Comment by slandelle** [comment]
Please use the community google group for questions, not the bug tracker.

**Comment by welker90** [comment]
This isn't a question, they are a recommendation for fixes. HTTP protocol doesn't have the ability to have feeders (at least from anything I've seen). And the case sensitivity is a bug.  There's no reason for the domain to have to be upper case.

**Comment by slandelle** [comment]
> HTTP protocol doesn't have the ability to have feeders (at least from anything I've seen).

HTTP protocol does take Expressions.

> And the case sensitivity is a bug. There's no reason for the domain to have to be upper case.

OK, now I get it, sorry. Indeed, it seems domain and workstation must be uppercase.
Thanks for reporting!

https://github.com/AsyncHttpClient/async-http-client/issues/1185
