### ISSUE TITLE
Core: foreach on empty collection creates a busy loop

### ISSUE THREAD

**Issue by evredinka** [gatling/gatling#3048]
i have such simulation, the case is that during first http get i receive a list of elements (it could be empty or not), then save it to session, then during some time iterate this list in foreach loop with calling another http get

when list contains some elements simulation ends in 10 seconds as expected, but if the list is empty, simulation continues to run (i use ctrl + c to stop it)

gatling version: 2.2.0, also reproduced in 2.2.1

```scala
class MyTestSimulation extends Simulation {

  val baseHttpConf = http.baseURL("").userAgentHeader("Gatling API Load Test").disableCaching

  val chained = scenario("my scenario")
    .exec(http("get google outside during")
      .get("http://google.com")
      .check(status.is(200)))

    .exec(_.set("myList", 0 until 0))

    .during(10) {

      foreach("${myList}", "element") {

        exec(http("get google inside during")
          .get("http://google.com")
          .check(status.is(200)))
      }

    }

  setUp(chained.inject(atOnceUsers(50))).protocols(baseHttpConf)

}
```

**Comment by slandelle** [comment]
Thanks for reporting!
