### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by gasparltd** [gatling/gatling#3049]
When I test a service which returns large (~200MB) responses (in chunks) I get OutOfMemoryError.
The way to replicate:

val httpConf = http.baseURL("your url")
val scn = scenario("BasicSimulation").exec(http("large_file").get("file/1").check(status.is(200)))

setUp(scn.inject(atOnceUsers(10)))
   .assertions(global.responseTime.max.lessThan(180000))
   .protocols(httpConf)

(Also I had to set requestTimeout to 3 minutes in the config file.)

Obviously when I increase the heap to several GB (in particular 8GB) the test succeeds. But that's not the point ... the point is when I set the number of users to 100 I get OutOfMemoryError again and increasing memory doesn't make sense as I have only 8GB on my box.

It looks like gatling is keeping the whole responses in memory despite I'm not interested in the body ... I just need to check the final status and make sure the responses are handled within a specified timeout.

**Comment by slandelle** [comment]
* which version do you use?
* do you run in debug?
* can you provide a heap dump?

> It looks like gatling is keeping the whole responses in memory despite I'm not interested in the body ...

It shouldn't, except if you're running in debug mode, or if you've explicitly change the behavior, see http://gatling.io/docs/2.2.1/http/http_protocol.html#response-chunks-discarding

**Comment by gasparltd** [comment]
Version 2.2.0

I don't think I run in debug. I didn't know there's such a mode. I just use default settings except requestTimeout. And I run the test from SBT. Also as you can see from the example I didn't disable the chunks discarding.

Due to a security policy of my client I cannot upload anything anywhere but the heap dump points somewhere to netty. Anyway I believe it is easy to replicate ... just test a server which returns big files.

**Comment by slandelle** [comment]
> Due to a security policy of my client I cannot upload anything anywhere

Too bad. Your client should understand how things work in open source.

**Comment by gasparltd** [comment]
Here is sample project where I tried to replicate the issue:
https://github.com/gasparltd/gatling_memory_leak

The interesting bit is that I cannot replicate it now. I will investigate further.

**Comment by slandelle** [comment]
Good luck. The problem is probably non trivial, I'm 100% sure we're supposed to not store the chunks and Netty's supposed to release them.
If you want to share a heap dump and the OOM stacktrace from your real app, please send a private email.

**Comment by gasparltd** [comment]
I ran the sample project against the real server and it worked without any problems ... no growing memory. It looks like the issue was caused by the fact that the gatling test ran as a part of integration tests which had some extra library dependencies ... and these libraries were causing the problem (maybe  mixing incompatible versions?) ... I didn't have time to investigate further. But at the end of the day I can confirm that there was no memory leak when running gatling load test as a separate SBT project. Closing the bug.

**Comment by slandelle** [comment]
Thanks for your feedback

> It looks like the issue was caused by the fact that the gatling test ran as a part of integration tests which had some extra library dependencies ... and these libraries were causing the problem (maybe mixing incompatible versions?)

Any clue what those libs are? Old Netty or AsyncHttpClient versions? Pulled from Play?

**Comment by wmorrison365fr** [comment]
Hi, was there any follow up on which versions seem to produce a memory leak. Also, what is meant by “running in debug mode”. I don’t believe I’m running in debug and have removed checks on the réponse. However, I’m not seeing message chunks discarded.

I’m testing GETs of 1Gb but can see that the full 1Gb is stored in memory. Worse, I can see it’s also stored in two independent ‘char[]’, meaning an additional 2x 2Gb. So, my 1Gb response consumes 5Gb memory in Gatling/ Netty. I can’t see why chunking is not taking place. This is limiting the amount of concurrent users I can test with and I have to have a large heap.

Any thoughts on why appreciated. I have an .hprof if helpful. I can open an issue but it relates closely to this issue, which was closed.

I’m using Gatling 2.2.1 and Scala 11.10 (I think - I can confirm tomorrow if need be).

Thanks, Wayne

**Comment by slandelle** [comment]
@wmorrison365fr Please first upgrade to Gatling 2.3.0, the version you're using is to old and we won't investigate there.

**Comment by wmorrison365fr** [comment]
Ok, thanks @slandelle. There’s a reason we’re on 2.2.1, but I’ll check. 

Can you brief me on how to confirm “debug mode” is disabled please. Presume it’s not just the logback config?
