### ISSUE TITLE
Misc: Add LDAP support

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#305]
Investigate JLDAP by Novell :

http://www.openldap.org/jldap/
http://www.novell.com/developer/ndk/ldap_classes_for_java.html

**Comment by slandelle** [comment]
No community demand

**Comment by automatictester** [comment]
There is a community demand fot LDAP support. Due to lack of LDAP support, I couldn't use Gatling in my previous project. JMeter was the only option for me.

**Comment by slandelle** [comment]
No, there isn't much demand for it, only once every year or so.

Then, as Java doesn't have a proper standard LDAP API, only JNDI lookups (whose performance is crap), and you really want to test with the same client that you use in your app, we'd actually have to implement support of every possible Java client, whose performance can be very different.

All in all, I don't think we'll ever implement something for LDAP ourselves, except if some customer was to sponsor this feature.
Then, of course, contributions are welcome.
