### ISSUE TITLE
exception while executing timer task

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#3052]
2.2.1

If the sim runs for < 1 second (atOnceUsers), a timer exception is thrown.

```
[##########################################################################]100%                                                                                                                                                                                        [19/341]
          waiting: 0      / active: 0      / done:10
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=9      KO=1     )
> Front Page                                               (OK=3      KO=1     )
> Deportes                                                 (OK=5      KO=0     )
> International                                            (OK=1      KO=0     )
---- Errors --------------------------------------------------------------------
> status.find.is(200), but actually found 404                         1 (100.0%)
================================================================================

Simulation bbc.phiippa.CpsRequestsProducer completed in 0 seconds
[ERROR] [06/14/2016 15:49:01.953] [GatlingSystem-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(GatlingSystem)] exception while executing timer task
java.lang.NullPointerException
        at io.gatling.core.akka.BaseActor.system(BaseActor.scala:25)
```

**Comment by slandelle** [comment]
I've run a very basic simulation (1 request on localhost, `atOnceUsers(1)`) and haven't been able to reproduce so far.

**Comment by aidylewis** [comment]
I'll create a reproducer.

**Comment by aidylewis** [comment]
Can you run ComputerWorld from this: https://github.com/bbc/gatling-load-tests ?

**Comment by aidylewis** [comment]
Clean clone is fine. Can you hold on this till tomorrow, to see if I can reproduce.

**Comment by aidylewis** [comment]
Apologies. Cannot now reproduce after a fresh install.

**Comment by slandelle** [comment]
Mmmm, I fail to see how a clean install could fix anything in a JVM based app.
There might be a race condition somewhere, but I fail to find out how we could possibly get a NPE there. Please ping if you can reproduce.

**Comment by KrauseStefan** [comment]
I'm now experiencing this issue as well.

Setup:
- Win 8.1
- Gatling 2.2.5
- Async websockets checks are used, together with http
- Test target is on the same machine

As you can see in the screenshot below this happens after the simulation is completed.
The last thing the test does is

`exec(`
  `    exec(ws("End Async Check", socketName).reconciliate),`
  `    exec(ws("Close WebSocket", socketName).close)`
`)`

It does not reproduce every time though, but pretty often.

![image](https://user-images.githubusercontent.com/1446336/29452099-5f85a972-8405-11e7-8900-22b95520b687.png)
