### ISSUE TITLE
Doc: Update and simplify realtime monitoring page 

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#3058]
Even though the real-time monitoring page contains some useful information, I also think it is confusing.  http://gatling.io/docs/2.2.2/realtime_monitoring/index.html

I currently have my own documentation which could be merged into the official documentation: 
https://github.com/bbc/notes-on-perf-testing/blob/master/ch/gatling/real_time_graphs.md

I was thinking of offering two solutions: Gatling -> InfluxDB -> Grafana and keeping the lo-fi (but immensely useful awk script). 

I'd be inclined to rip-out anything to do with Windows (from my experience those with Windows machine are developing Gatling simulations on GNU/Linux VMs). And do we really need the Graphite tool conf and the collectd stuff? 

Didn't @ceeaspb originally write this (he may have some opinions)?

**Comment by slandelle** [comment]
Yes, more simplicity is probably better.

Then, I wouldn't advertise InfluxDB as the ultimate and perfect time series database. It's actually suited for counts, but inadequate for distributions. FrontLine is a way stronger player on the latter (but specific to Gatling metrics atm).

**Comment by slandelle** [comment]
My previous comment is about the language, not the overall content of your doc, which is great :)

**Comment by aidylewis** [comment]
I'll link to FrontLine at the bottom of the page. We can also add a paragraph outlining the drawbacks of the InfluxDB/Grafana offering.

**Comment by slandelle** [comment]
Looks great to me!

**Comment by aidylewis** [comment]
How are your running Sphinx to create HTML documentation from rst files?

**Comment by aidylewis** [comment]
https://github.com/gatling/gatling/blob/50f09863bf152202398dc65daa653a48fef2e3d5/src/sphinx/realtime_monitoring/index.rst

**Comment by aidylewis** [comment]
https://github.com/gatling/gatling/pull/3063
