### ISSUE TITLE
Core: Loop exit ASAP doesn't properly remove itself from block stack

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#3060]
Hi there,

I got a problem with 2.2.2. It is fine with 2.2.1 : 

16:57:22.799 [ERROR] i.g.c.a.GroupEnd - GroupEnd called but head of stack List(ExitAsapLoopBlock(POLL_ITERATION_COUNT-PollingScope,<function1>,io.gatling.core.action.GroupEnd@44b1490d), GroupBlock(List(RNE_200_03-accueilRne-group, request_7-group),1466521042504,106,OK), GroupBlock(List(RNE_200_03-accueilRne-group),1466521041959,428,OK), ExitOnCompleteLoopBlock(feeb3cda-28a4-4899-883f-00bb59518788)) isn't a GroupBlock, please report.

Thanks for your great work as usual.

**Comment by slandelle** [comment]
Could you please provide a reproducer?

**Comment by slandelle** [comment]
@mxbossard Gentle ping :)

**Comment by mxbossard** [comment]
Sorry, for now cannot give you a reproducer, nor investigate on it. I am stuck with 2.2.1.

**Comment by slandelle** [comment]
I could reproduce. It seems `ExitAsapLoopBlock` is not being removed when it triggers.

**Comment by slandelle** [comment]
Fixed! Thanks for reporting!

**Comment by mxbossard** [comment]
Thanks for your work. I Hope it's my bug :D
