### ISSUE TITLE
Doc: Kernel and network tuning explanations 

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#3064]
Regarding the Operations page: 
http://gatling.io/docs/2.2.2/general/operations.html

Some may be a little reticent in copying and pasting config in /etc. I don't mind explaining the Linux and network tuning in detail (if anyone thinks it is worthwhile?)

*Sidenote*
Is it worth separating the documentation from the code mainline as is done in the Rust OS: 
https://github.com/redox-os/book?

**Comment by slandelle** [comment]
> Some may be a little reticent in copying and pasting config in /etc. I don't mind explaining the Linux and network tuning in detail (if anyone thinks it is worthwhile?)

Why not, but please keep it light. We're not supposed to be a source for Linux tuning tutorials.

> Is it worth separating the documentation from the code mainline

Not atm. At some point, we'll move our site from a static github pages to a full blown website, and I don't know yet how we'll deal with the doc. Let's see then.

**Comment by slandelle** [comment]
Closing. I think we provide enough resources for OS tuning. For more advanced information, users might look for specialized sources.
