### ISSUE TITLE
Jenkins plugin: NullPointerException in isVisible

### ISSUE THREAD

**Issue by wimsymons** [gatling/gatling#3069]
I have a NullPointerException in isVisible(). Result is that all reporting is not available.

In the Jenkins logs:
```
Jun 30, 2016 3:43:39 PM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: action.isVisible() in /jenkins/view/XXX/view/5.%20Gatling/job/XXX-gatling-XXX-perf/. Reason: java.lang.NullPointerException
java.lang.NullPointerException
```

(I replaced some parts of the real URL with XXX for security reasons)

I can't actually pinpoint what makes it fail.

This is an overview of all builds in the job:
![image](https://cloud.githubusercontent.com/assets/1419117/16490744/407d8dd0-3edb-11e6-93b0-e8cb8d3506b3.png)

Jenkins version 1.651.3
Plugin version 1.2.0

**Comment by wimsymons** [comment]
Maybe related to this: https://groups.google.com/forum/#!searchin/gatling/NullPointerException$20jenkins/gatling/QYp3ArAR2vM/REJRke8ABAAJ

**Comment by wimsymons** [comment]
Did a debug session of the plugin. Not able to reproduce. But has something to do with latest build status. When the last build fails, there is no "Mean Response Time Trend" graph on the right side panel of the project page and even the Gatling icon in the left bar disappears.

This is not wanted behaviour when the build exits with failure because you used a Gatling assertion which failed. You want the graphic and the link to Gatling to appear at all times.

**Comment by slandelle** [comment]
This is not a maven plugin issue but a Jenkins plugin one.
It was introduced in 1.2.0 with the support for pipeline API. cc @cprice404 

@ccedric has a fix under way.

**Comment by wimsymons** [comment]
Any release date for 2.2.3?

**Comment by slandelle** [comment]
End of August or September

**Comment by cprice404** [comment]
somehow I missed the ping on this, sorry about that bug @slandelle !

**Comment by slandelle** [comment]
@cprice404 No pro, this way, we could grow skills on Jenkins 2 too :)
