### ISSUE TITLE
HTTP: New WebSocket API

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3071]
This will be a long run feature for new Gatling generation, planned for next year.
- [x] Checks should target one single incoming message
- [x] It should be possible to perform multiple validations and captures on a given incoming message (e.g. capturing data from multiple JSON branches)
- [x] It should be possible to set up sequences of checks
- [x] It should be possible to set up multiple sequences of checks
- [x] It should be possible to define optional matching criteria so that check would ignore un-correlated incoming messages
- [x] It should be possible to auto-reconnect on next user action when the WebSocket gets closed by the server
- [x] It should be possible to define a post-connect sequence (eg auth) that would be triggered on auto-reconnect
- [x] Support binary frames

ex:

``` scala
exec(ws("Connect")
  .connect("wss://host:port/path")
  // blocks the flow
  // it can wait for a sequence of messages, it will then block until all succeed or one fails
  // order is meaningful
  .wait(1 second)(
    wsTextMessage.check(someCheck1, someCheck2),
    wsTextMessage.check(someCheck1, someCheck2)
  )
 // sequence to be performed on (re-)connect (optional)
 .onConnected {
    exec(ws("sentAuthData").sentTextMessage("someText")
      .wait(1 second)(
        wsTextMessage
          // optional, used to filter incoming messages and tell push messages appart
          // always match by default
          .matching(someCheckWithoutSaveAs)
          .check(someCheck)
      ))
 }
).exec(ws("SendMessage1")
  .sendTextMessage("someText")
  .wait(1 second)(
    wsTextMessage.check(someCheck))
)
```

**Comment by slandelle** [comment]
* wip happens here: https://github.com/gatling/gatling/tree/master/gatling-http/src/main/scala/io/gatling/http/action/ws2
* sample here: https://github.com/gatling/gatling/blob/master/gatling-http/src/test/scala/io/gatling/http/Ws2CompileTest.scala

feedback welcome

**Comment by Sejten** [comment]
Hi, what happened to the non blocking checks? From what I see in new WebSocket API, all checks are blocking main HTTP flow.

**Comment by slandelle** [comment]
@Sejten Not sure if we'll continue supporting async checks for this one support. So far, the only users who gave us feedback on WebSocket support (both old and new one) is that they don't use non-blocking checks. The ones who are interested in async checks actually want to use WebSockets, not for web apps, but for message broking, similar to what we have for JMS.

Feedback welcome.

**Comment by Sejten** [comment]
I have a problem similar to the one [described in this ticket](https://github.com/gatling/gatling/issues/2336): I want to simulate  a mix of http REST and websocket calls to communicate with an app. With async checks I would be able to create simulation that alternately sends REST calls and receives websocket responses.

**Comment by slandelle** [comment]
Supporting async checks introduces a lot of complexity. I don't think we from GatlingCorp will work on this outside a contract any time soon. Then, contributions would be very welcome!

**Comment by johnsonexosite** [comment]
I am wondering, what's the differences between auto-reconnect in the new API and `wsReconnect` in current 2.2.5 version?

**Comment by reidconnor** [comment]
Any plans to support byte message checks? Or even merely to save the raw byte array from a WebSockets response in the scenario session?

**Comment by slandelle** [comment]
@johnsonexosite It works the same way, except new API can replay an applicative connection sequence (ex: auth).

@reidconnor Yes, we'd like to have binary frames check for final version in Gatling 3. But working on that is not a priority atm, unless we get a customer who needs it. Contribs welcome!

**Comment by irishmark** [comment]
I'm new to Gatling, I'm just starting to investigate it as jmeter is using too much CPU to handle websocket messages, but async message handling would be essential. Is it really being removed? How are we to handle sites which send messages unpredictably? Maybe I'm missing the point cos I'm new to Scala and Gatling, but the reason I'm considering it is so I don't have to have a polling "sleep" loop for these unexpected messages (as doing so is using too much CPU on my jmeter engines, I need an async message handling mechanism instead. I'm used to webload which has a great async handling mechanism for websockets)

**Comment by slandelle** [comment]
> Is it really being removed? 

It's not being "removed". The WebSocket support is being re-written for Gatling 3 as the version in Gatling 2 has some issues that couldn't be fixed. Support for async checks hasn't been re-implemented yet. See comments above on how to make it happen faster.

> I'm used to webload which has a great async handling mechanism for websockets

Suggestions on design of such API welcome then

**Comment by htambekar** [comment]
I have service which doesn't send any response on connect method and after sending pingMessage.
In that case, I would like to avoid adding following line.

ws2 protocol should support sendTextMesssage without adding any checks. Checks should not be mandatory. 

.wait(1 second) (
           ws2.checkTextMessage("PingMessageResponse").check(regex(""" """))
         )

**Comment by mz0** [comment]
regarding "Checks should target one single incoming message" - I have a check on ws().open like this one: https://gist.github.com/mz0/65a8b24769f05577449e9636b6cdfc35
SUT on the first connection fires 43 messages (which draw UI) of which I'm interested in 17 listed in the transform check. When I tried to split this check in two I missed many messages - websocket debug log indicated that subsequent check was set 15ms after the previous one.
