### ISSUE TITLE
Typo in Migrating document 

### ISSUE THREAD

**Issue by xiongjia** [gatling/gatling#3074]
I am reading the Migrating document ( http://gatling.io/docs/2.2.2/migration_guides/2.1-to-2.2.html ) and I think the "JKD8" is a Typo.
Please check below screenshot:
![jdk](https://cloud.githubusercontent.com/assets/1784521/16604805/9525652c-435b-11e6-9ac5-9322a22fb8be.png)

**Comment by slandelle** [comment]
thanks!
