### ISSUE TITLE
Maven Plugin: doesn't work if there's whitespace in the maven path

### ISSUE THREAD

**Issue by distinctdan** [gatling/gatling#3078]
I'm trying to get gatling to work with maven to avoid having gatling's core files under source control, so I downloaded the demo project found here: https://github.com/gatling/gatling-maven-plugin-demo

However, when I run it, I get the error: 
```
[INFO] --- gatling-maven-plugin:2.2.0:execute (default-cli) @ gatling-maven-plugin-demo ---
Error: Could not find or load main class Files\\apache-maven-3.3.9\\bin\\..\\bin\\m2.conf
```

It looks like it doesn't like the space in `c:\Program Files`, and has cut it to `Files`

**Comment by untra** [comment]
This looks to be the last issue labeled for 2.2.3. Is there an expected 2.2.3 release, or is gatling going to continue work until a 3.0 release?

**Comment by slandelle** [comment]
2.2.3 is planned for September. Then, all GatlingCorp fixes until 3.0 will only be available for our customers. Still, community contributed fixes will keep on being released until then.

PS: contributions welcome

**Comment by slandelle** [comment]
It was also [reported](https://groups.google.com/d/msg/gatling/iSSI5YHuPsE/R8ACac_0CAAJ) that system props with white spaces could be a problem, which is weird because we escape them. o_O

**Comment by benwck** [comment]
I also facing the same problem. I tried to change my PATH variable and set M2_HOME to the new path (C:/Maven). Still trying to get the C:/Program Files.... Any idea ?

**Comment by slandelle** [comment]
From JSE [doc](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html):

> -Dproperty=value
Sets a system property value. The property variable is a string with no spaces that represents the name of the property. The value variable is a string that represents the value of the property. If value is a string with spaces, then enclose it in quotation marks (for example -Dfoo="foo bar").

Guess what? It doesn't work on Windows...

**Comment by ctapobep** [comment]
Could you please release the new version of the maven plugin?

**Comment by slandelle** [comment]
We'll release along with Gatling 2.2.3, as soon as we can.

**Comment by sskorol** [comment]
I've pulled plugin's source code, built it locally and deployed snapshot into Nexus. Works fine. Still see some warnings about whitespaces, but it's not failing at least.
