### ISSUE TITLE
Recorder: Add support for managing multiple preference profiles in the recorder app

### ISSUE THREAD

**Issue by thomasdarimont** [gatling/gatling#3090]
Currently gattling recorder only supports to save one set of preferences.
However when using gatling in multiple projects at the same time one needs to adjust preferences for a  particular project.

It would be helpful if the gatling recorder app would support creating project specific profiles to store preferences. A user should then be able to select a profile from a set of previously stored preferences.

**Comment by slandelle** [comment]
Why not. Care to contribute? ;)

**Comment by thomasdarimont** [comment]
Sure, can you give me a pointer where the preferences are stored?

**Comment by thomasdarimont** [comment]
Found it: https://github.com/gatling/gatling/search?utf8=%E2%9C%93&q=preferences

**Comment by slandelle** [comment]
Idle thread for several months. Closing for now. Will reopen if needed.
