### ISSUE TITLE
[Jenkins] Could not find a Gatling report in results folder.

### ISSUE THREAD

**Issue by shuyuei** [gatling/gatling#3091]
Jenkins is unable to find the report located in ..\target\gatling\results\testlogin-1469548742923\index.html

Tried editing pom.xml and gatling.conf but not successful. [Document](http://gatling.io/docs/2.0.3/extensions/jenkins_plugin.html) says it needs to be in this particular timestamp format: runname-rundate (ex: mysimulation-201305132230) but I can't find where to set that.

**Comment by ccedric** [comment]
Hello,

Which versions do you use? (Jenkins, gatling-jenkins-plugin, gatling-maven-plugin)
Can you give me the stack trace of the error from the Jenkins log?

**Comment by shuyuei** [comment]
Hi,

Jenkins version 2.7

Gatling version 2.1.7

Plugin version 1.1.2

Stack trace:
17:20:38 Reports generated in 0s.
17:20:38 Please open the following file: D:\work\testautomation\workspace\webperformanceautomation\target\gatling\results\testlogin-1469568037702\index.html
17:20:38 For all requests: percentage of failed requests is less than 5 : true
17:20:38 Global: max of response time is less than 65000 : true
17:20:38 Global: 99th percentile of response time is less than 10000 : true
17:20:38 Global: 95th percentile of response time is less than 5000 : true
17:20:38 [INFO] ------------------------------------------------------------------------
17:20:38 [INFO] BUILD SUCCESS
17:20:38 [INFO] ------------------------------------------------------------------------
17:20:38 [INFO] Total time: 10.536 s
17:20:38 [INFO] Finished at: 2016-07-26T17:20:38-04:00
17:20:38 [INFO] Final Memory: 25M/1963M
17:20:38 [INFO] ------------------------------------------------------------------------
17:20:39 Archiving Gatling reports...
17:20:39 ERROR: Build step failed with exception
17:20:39 java.lang.IllegalArgumentException: Could not find a Gatling report in results folder.
17:20:39 	at io.gatling.jenkins.GatlingPublisher.saveFullReports(GatlingPublisher.java:99)
17:20:39 	at io.gatling.jenkins.GatlingPublisher.perform(GatlingPublisher.java:68)
17:20:39 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
17:20:39 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
17:20:39 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
17:20:39 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
17:20:39 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
17:20:39 	at hudson.model.Run.execute(Run.java:1766)
17:20:39 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:20:39 	at hudson.model.ResourceController.execute(ResourceController.java:98)
17:20:39 	at hudson.model.Executor.run(Executor.java:410)
17:20:39 Build step 'Track a Gatling load simulation' marked build as failure
17:20:39 Finished: FAILURE

**Comment by ccedric** [comment]
Hello,

I can't reproduce your issue.

Can you send me your gatling.conf and pom.xml?
Which Java version do you use for your Jenkins?

Can you try a Jenkins build with our test simulation? (https://github.com/gatling/gatling-maven-plugin-demo)

**Comment by shuyuei** [comment]
Hi, 

The demo build also runs successfully but plugin cannot find the file. 
Java: jdk1.8.0_40
Attached are the requested files
[New folder.zip](https://github.com/gatling/gatling/files/388822/New.folder.zip)

**Comment by shuyuei** [comment]
Figured out why it was failing.

I was building with Windows batch command instead of invoking top-level maven targets. Thanks.

**Comment by kalyangogineni** [comment]
How did you fix this issue . I am also facing this issue while trying to use HTML publish in jenkins . It complains about report does not found . Because Gatling suffixes a folder with timestamp.

**Comment by alectronic0** [comment]
in a similar issuie
```groovy
                publishHTML([
                        allowMissing         : false,
                        alwaysLinkToLastBuild: false,
                        keepAll              : true,
                        reportDir            : "./target/gatling/results/",
                        reportFiles          : 'index.html',
                        reportName           : 'Performance Test Report'
                ])
                gatlingArchive()
```
