### ISSUE TITLE
How to find length of JSON array in gatling using jsonpath or any other?

### ISSUE THREAD

**Issue by gopimr2** [gatling/gatling#3095]
How can I find the length of an jsonArray which arrives through REST API?

My case:

```
object RESTAPI { 
   def getItemsArray(desc: String, i1: String, i2: String) = {
        http(desc)
          .get(RESTURL.test + i1)
          .queryParam("key", i2)
      }
}

 scenario("Check items")
 .exec(RESTAPI.getItemsArray("Getting Item list ", "phones",    STORE.android)
      .check(status is 200)
      .check(jsonPath("$").count.greaterThanOrEqual("2")))
```
**jsonPath("$")** will return [{"item1":"X pro"},{"item2":"Y pro"},.....]

The **jsonPath("$").count** always returns 1. I can't find its length. Please help me resolve this. ([my stackoverflow link](http://stackoverflow.com/questions/38660251/how-to-find-length-of-json-array-in-gatling-using-jsonpath-or-any-other))

**Comment by slandelle** [comment]
Please use our mailing list for questions, not the bug tracker.

**Comment by aroramayank2002** [comment]
Was there an answer, I am stuck too. Or can we have the link to the mailing list ?

**Comment by Amerousful** [comment]
Try jsonPath("$.blablabla").count.saveAs("someCount")

**Comment by grib0** [comment]
Solution : `.check(jsonPath("$.yourProperty[*]").count.gt(2))`
From : https://groups.google.com/forum/#!searchin/gatling/check$20jsonPath$20length|sort:date/gatling/gmvNEO5jCP0/cNUDlXksCgAJ

**Comment by square-bracket** [comment]
> Solution : `.check(jsonPath("$.yourProperty[*]").count.gt(2))` From : [https://groups.google.com/forum/#!searchin/gatling/check$20jsonPath$20length|sort:date/gatling/gmvNEO5jCP0/cNUDlXksCgAJ](https://groups.google.com/forum/#!searchin/gatling/check$20jsonPath$20length%7Csort:date/gatling/gmvNEO5jCP0/cNUDlXksCgAJ)





https://jessemil737.github.io/magician/
