### ISSUE TITLE
Gatling log seems to be incomplete

### ISSUE THREAD

**Issue by schmitzhermes** [gatling/gatling#3096]
Hey folks,

I am using the a Gradle Gatling Plugin (com.github.lkishalmi.gatling). After executing my load tests successfully, I try to visualize my results in my ELK stack. In order to accomplish this, I try to analyze the `simulation.log` file...

However, that does not work, because I only have two timestamps in my log (and not four - as google and your source code) in my log.
My logs look like this:
```
RUN     mypackage           mysimulation    1470167474654           2.0
USER    Einfache Simulation: einfacher Request  1       START   1470167475432   1470167475432
REQUEST Einfache Simulation: einfacher Request  1               request_1       1470167475465   1470167475900   OK
USER    Einfache Simulation: einfacher Request  2       START   1470167475989   1470167475989
REQUEST Einfache Simulation: einfacher Request  2               request_1       1470167475989   1470167476354   OK
USER    Einfache Simulation: einfacher Request  1       END     1470167475432   1470167476922
USER    Einfache Simulation: einfacher Request  2       END     1470167475989   1470167477369
```

Do you guys have any idea where that comes from? 

Thank you for any help.

Cheers,
Jan

**Comment by slandelle** [comment]
In 2.2, we switched to only 2 timestamps. Note that the log format is internal and subject to changes.

**Comment by slandelle** [comment]
Also, please use our mailing list for questions, not the bug tracker.

**Comment by schmitzhermes** [comment]
OK thank you and sorry for the inconvenience ;-)
