### ISSUE TITLE
Allow graphite configuration to also use environment variables and not only gatling.conf

### ISSUE THREAD

**Issue by camiloribeiro** [gatling/gatling#3097]
I am using gatling as engine for running performance testing and monitoring in a fatjar that we spread around several datacenters, so it is hard (and unnecessary) to build different fatjars because I need two different configurations, one for each data center for instance. 

The feature would be to keep the current behaviour and allow users to use env variables to set values. If the environment variable is not there, it fallback to its current behaviour and uses gatling.config as usual.

the configuration I am asking to be changed is, with its respective environment variable suggested names:

```
 graphite {
      light = false                         # GRAPHITE_LIGHT
      host = "metrics.tvoli.com"            # GRAPHITE_HOST
      port = 2003                           # GRAPHITE_PORT
      protocol = "tcp"                      # GRAPHITE_PROTOCOL
      rootPathPrefix = "production"         # GRAPHITE_ROOTPATHPREFIX
      bufferSize = 8192                     # GRAPHITE_BUFFERSIZE
      writeInterval = 5                     # GRAPHITE_WRITEINTERVAL
    }
```

I know it sounds very specific, but this would not affect the current api and would not change the behaviour we have today.

Let me know if you need any extra data. A PR is coming with this issue soon.

**Comment by slandelle** [comment]
PR reviewed, but I had to reject it.
Please use Lightbend config's built-in features.

**Comment by slandelle** [comment]
So, all good with plain config lib?
