### ISSUE TITLE
Doc: Gatling 3 migration

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3099]
- New WebSocket API, see #3071 (first version shipped in 3.0.0-M1)
- Dropping `PerMillion`, see #2873
- strict vs not strict inequalities in Assertions, see #2993
- `baseUrls` are now sticky, see #3043 
- `Validation#get` was removed, see #3189
- new Pebble based templating engine, see #3028
- Now using Scala 2.12, see #3179

**Comment by mikla** [comment]
Hi there!
When do you plan to release Scala 2.12 support?
As far as I see everything is closed except #3071.

**Comment by slandelle** [comment]
Gatling 3 should be out late 2017/early 2018

**Comment by aakavalevich** [comment]
Will Gatling 3 be the first release with Scala 2.12 support?

**Comment by slandelle** [comment]
Yep

**Comment by slandelle** [comment]
Then FrontLine has Gatling 3 previews, indeed with Scala 2.12.

**Comment by aakavalevich** [comment]
Is there any workaround? I would like to migrate our project to Scala 2.12 and gatling is currently the only one dependency, which is still using 2.11.

**Comment by slandelle** [comment]
Don't have a single monolithic project. Either have modules with different Scala versions or move Gatling to it's own. Or subscribe to FrontLine.

**Comment by slandelle** [comment]
Don't have a single monolithic project. Either have modules with different Scala versions or move Gatling to it's own. Or subscribe to FrontLine.

**Comment by mb720** [comment]
@slandelle Can you maybe point us to a `build.sbt` that uses Gatling as a module, circumventing the problem with incompatible Scala versions?
Thanks!

**Comment by slandelle** [comment]
Have a look at Gatling build itself, compiler module is compiled against Scala 2.10 (old Zinc version).

**Comment by magro** [comment]
What about releasing an RC? This way there would at least be a stable version available for early adopters...

**Comment by slandelle** [comment]
We'll release Release Candidates once Gatling 3 will be feature complete.
But we won't be releasing milestones before that. We don't really have time for that, and we had a bad experience with doing that for 2.0.0-M3a where people wouldn't upgrade to stable versions and kept bugging us with it for years.
We do provide private milestones for our FrontLine customers.
If you're not willing to contract with us, you can deploy on your own, typically on a private repo.

**Comment by magro** [comment]
Ok, thanks!

**Comment by thinkerou** [comment]
any progress? thanks!

**Comment by thinkerou** [comment]
like done, thanks!
