### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by kailuowang** [gatling/gatling#3100]
I am using gatlin sbt 2.2.0

>  i.n.u.c.DefaultPromise - An exception was thrown by org.asynchttpclient.netty.request.NettyRequestSender$1.operationComplete()
> java.lang.NullPointerException: timeoutsHolder
> 	at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
> 	at org.asynchttpclient.netty.request.NettyChannelConnector.<init>(NettyChannelConnector.java:54)
> 	at org.asynchttpclient.netty.request.NettyRequestSender$1.onSuccess(NettyRequestSender.java:281)
> 	at org.asynchttpclient.netty.request.NettyRequestSender$1.onSuccess(NettyRequestSender.java:276)
> 	at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:24)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
> 	at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:624)
> 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:139)
> 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:33)
> 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:276)
> 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:136)
> 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:107)
> 	at org.asynchttpclient.netty.request.NettyRequestSender.sendNextRequest(NettyRequestSender.java:464)
> 	at org.asynchttpclient.netty.request.NettyRequestSender.retry(NettyRequestSender.java:422)
> 	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:129)
> 	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:106)
> 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
> 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:604)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:564)
> 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:222)
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by slandelle** [comment]
Can you reproduce with 2.2.2? If so, can you please provide a reproducer?

**Comment by kailuowang** [comment]
I don't have a reproducer, I saw it from the log, but I think that the stack trace of a `NullPointerException` should provide enough useful information for code improvement. So it's more a FYI

**Comment by kailuowang** [comment]
Update actually it was on 2.2.1.  I updated to 2.2.2 and haven't seen it so far. So maybe it's fixed on 2.2.2. I will reopen if I see it again. Thanks for the great project!

**Comment by slandelle** [comment]
Thanks.

**Comment by NilsKrause** [comment]
Hey,
I am using Gatling 2.2.3 SNAPSHOT and getting the same NullPointerException.

> `Exception in thread "main" java.lang.NullPointerException: host
>         at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
>         at org.asynchttpclient.uri.Uri.<init>(Uri.java:65)
>         at org.asynchttpclient.uri.Uri.create(Uri.java:38)
>         at org.asynchttpclient.uri.Uri.create(Uri.java:31)
>         at io.gatling.http.protocol.HttpProtocol.io$gatling$http$protocol$HttpProtocol$$$anonfun$3(HttpProtocol.scala:145)
>         at io.gatling.http.protocol.HttpProtocol$lambda$2.apply(HttpProtocol.scala:145)
>         at io.gatling.http.protocol.HttpProtocol$lambda$2.apply(HttpProtocol.scala:145)
>         at io.gatling.http.protocol.HttpProtocol.makeAbsoluteHttpUri(HttpProtocol.scala:155)
>         at io.gatling.http.request.builder.RequestExpressionBuilder.makeAbsolute(RequestExpressionBuilder.scala:60)
>         at io.gatling.http.request.builder.RequestExpressionBuilder.<init>(RequestExpressionBuilder.scala:65)
>         at io.gatling.http.request.builder.HttpRequestExpressionBuilder.<init>(HttpRequestExpressionBuilder.scala:37)
>         at io.gatling.http.request.builder.HttpRequestBuilder.build(HttpRequestBuilder.scala:154)
>         at io.gatling.http.action.sync.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:34)
>         at io.gatling.core.structure.StructureBuilder$class.io$gatling$core$structure$StructureBuilder$class$$$anonfun$1(StructureBuilder.scala:34)
>         at io.gatling.core.structure.StructureBuilder$class$lambda$$build$1.apply(StructureBuilder.scala:33)
>         at io.gatling.core.structure.StructureBuilder$class$lambda$$build$1.apply(StructureBuilder.scala:33)
>         at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
>         at scala.collection.immutable.List.foldLeft(List.scala:84)
>         at io.gatling.core.structure.StructureBuilder$class.build(StructureBuilder.scala:33)
>         at io.gatling.core.structure.ChainBuilder.build(ChainBuilder.scala:30)
>         at io.gatling.core.action.builder.LoopBuilder.build(LoopBuilder.scala:44)
>         at io.gatling.core.structure.StructureBuilder$class.io$gatling$core$structure$StructureBuilder$class$$$anonfun$1(StructureBuilder.scala:34)
>         at io.gatling.core.structure.StructureBuilder$class$lambda$$build$1.apply(StructureBuilder.scala:33)
>         at io.gatling.core.structure.StructureBuilder$class$lambda$$build$1.apply(StructureBuilder.scala:33)
>         at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
>         at scala.collection.immutable.List.foldLeft(List.scala:84)
>         at io.gatling.core.structure.StructureBuilder$class.build(StructureBuilder.scala:33)
>         at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
>         at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:101)
>         at io.gatling.core.scenario.SimulationParams.io$gatling$core$scenario$SimulationParams$$$anonfun$13(Simulation.scala:169)
>         at io.gatling.core.scenario.SimulationParams$lambda$$scenarios$1.apply(Simulation.scala:169)
>         at io.gatling.core.scenario.SimulationParams$lambda$$scenarios$1.apply(Simulation.scala:169)
>         at scala.collection.immutable.List.map(List.scala:273)
>         at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:169)
>         at io.gatling.app.Gatling.run(Gatling.scala:102)
>         at io.gatling.app.Gatling.runIfNecessary(Gatling.scala:75)
>         at io.gatling.app.Gatling.start(Gatling.scala:65)
>         at io.gatling.app.Gatling$.start(Gatling.scala:57)
>         at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
>         at io.gatling.app.Gatling$.main(Gatling.scala:43)
>         at io.gatling.app.Gatling.main(Gatling.scala)`

I was getting the error on 2.2.2 and updated to the snapshot version in hope that it would be resolved. At first it worked but in my current scenario it keeps crashing on executing the scenario.

**Comment by slandelle** [comment]
@NilsKrause Please don't hijack an old issue that's been fixed and that's obviously not related. Check your stacktrace, it's completely different. Your problem is that you're trying to create an URI with a host name.
