### ISSUE TITLE
ArrayIndexOutofBoundsException

### ISSUE THREAD

**Issue by kailuowang** [gatling/gatling#3101]
gatling sbt 2.2.0
Met the following error 

> 
> Simulation MYSimulation completed in 480 seconds
> Parsing log file(s)...
> [error] java.lang.ArrayIndexOutOfBoundsException: -1470255393
> [error] 	at io.gatling.charts.stats.buffers.CountsBuffer.update(CountBuffer.scala:35)
> [error] 	at io.gatling.charts.stats.buffers.ResponsesPerSecBuffers$class.updateResponsesPerSecBuffers(ResponsesPerSecBuffers.scala:32)
> [error] 	at io.gatling.charts.stats.ResultsHolder.updateResponsesPerSecBuffers(ResultsHolder.scala:21)
> [error] 	at io.gatling.charts.stats.ResultsHolder.addRequestRecord(ResultsHolder.scala:48)
> [error] 	at io.gatling.charts.stats.LogFileReader.io$gatling$charts$stats$LogFileReader$$$anonfun$10(LogFileReader.scala:150)
> [error] 	at io.gatling.charts.stats.LogFileReader.io$gatling$charts$stats$LogFileReader$$$anonfun$10$adapted(LogFileReader.scala:145)
> [error] 	at io.gatling.charts.stats.LogFileReader$$Lambda$264/167139802.apply(Unknown Source)
> [error] 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
> [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
> [error] 	at io.gatling.charts.stats.LogFileReader.secondPass(LogFileReader.scala:145)
> [error] 	at io.gatling.charts.stats.LogFileReader.io$gatling$charts$stats$LogFileReader$$$anonfun$11(LogFileReader.scala:165)
> [error] 	at io.gatling.charts.stats.LogFileReader$$Lambda$263/1683387756.apply(Unknown Source)
> [error] 	at io.gatling.charts.stats.LogFileReader.parseInputFiles(LogFileReader.scala:63)
> [error] 	at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:165)
> [error] 	at io.gatling.app.LogFileProcessor.initLogFileReader(RunResultProcessor.scala:55)
> [error] 	at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:37)
> [error] 	at io.gatling.app.Gatling.start(Gatling.scala:66)
> [error] 	at io.gatling.app.Gatling$.start(Gatling.scala:57)
> [error] 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
> [error] 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
> [error] 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
> [error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
> [error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [error] 	at java.lang.Thread.run(Thread.java:745)

**Comment by slandelle** [comment]
Duplicate fo #3084
