### ISSUE TITLE
JMS: Support passing a ConnectionFactory factory

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3103]
We currently only support the JEE way: pass an `InitialContextFactory` class, create an `InitialContext` and fetch the `ConnectionFactory` with a JNDI lookup.

Some JMS client, such as AWS SQS don't have such `InitialContextFactory` and only support creating a `ConnectionFactory` manually.

**Comment by aidylewis** [comment]
I don't mind looking into this. But if possible I'll need some up front guidance if OK?

**Comment by slandelle** [comment]
We need to be able to support both strategies:
* the [existing JNDI based one](https://github.com/gatling/gatling/blob/master/gatling-jms/src/main/scala/io/gatling/jms/client/SimpleJmsClient.scala#L47-L62)
* a new one where one would pass a `() => ConnectionFactory` function

Then, we need to be able to pass this from the DSL, ie [`JmsProtocolBuilder`](https://github.com/gatling/gatling/blob/master/gatling-jms/src/main/scala/io/gatling/jms/protocol/JmsProtocolBuilder.scala).
It looks like the current DSL is not very right, as the ContextFactory and the ConnectionFactory JNDI name are passed in different places while they are actually completely related.

If one can manage to implement this without breaking the current DSL (probably in an ugly, but temporary way), we could ship it in Gatling 2.2. Otherwise, we'll have to wait for Gatling 3.

**Comment by Mishail** [comment]
What about moving `ConnectionFactory` initialization out of the `JmsClient`? Let's keep a reference to a factory in `JmsProtocol`, and let user create that factory instance.

```scala
  // create a factory explicitly
  val cf = new ActiveMQConnectionFactory()
  
  // or use DSL
  val cf = jmsConnectionFactory
    .name("FFMQConstants.JNDI_CONNECTION_FACTORY_NAME")
    .url("tcp://localhost:10002")
    .credentials("user", "secret")
    .contextFactory("FFMQConstants.JNDI_CONTEXT_FACTORY")
  
  // and the protocol builder just uses a reference to our factory
  val jmsConfig = jms
      .connectionFactory(cf)
      .listenerCount(1)
      .usePersistentDeliveryMode
      .receiveTimeout(1000)
      .messageMatcher(IdentificationMatcher)
```

**Comment by slandelle** [comment]
@Mishail Yes, I suspect that's the way to go. Then, I'd like to know if we can completely drop the JNDI lookup way (meaning that we can indeed create a ConnectionFactory for all well know JMS implementations).
