### ISSUE TITLE
[Question]How to Launch simulation from code?

### ISSUE THREAD

**Issue by tianchengbaihe** [gatling/gatling#3108]
Hi :

I am considering constructing a simple performance test service, but it seems I can't construct a new simulation and start it in code. It seems the only option is to generate the file and start it with a shell command.

I read the doc, it only taught me how to use it, but no information on this topic.

Is there simple way to do so?

Thanks

**Comment by slandelle** [comment]
Hi,

Please don't use the bug tracker for questions, use the mailing list.

**Comment by tianchengbaihe** [comment]
OK, Got it.
I didn't know it is forbidden here.

Thanks
