### ISSUE TITLE
gatling for asynchrnous requests..

### ISSUE THREAD

**Issue by ArihantRk** [gatling/gatling#3110]
i want to achieve the asynchrnous requests to webservice without wait for response. the same request repetedly should be send to webservice irrespective of response from server. we would like to test how many cps a webservice can handle?

but could see that internally gatling uses response status and then next request request which is making sychrnous calls and we are not able to achieve the cps what we wanted.

using resources we can have parallel requests sent to webservice but we nedd same request send in asynchronous manner. can this be achievable in gatling?

**Comment by slandelle** [comment]
Hi,

Please use our community mailing list for questions. This is a bugtracker, hence for issues and feature requests only.
