### ISSUE TITLE
Can i execute a scenario every 5min once,through out the day.

### ISSUE THREAD

**Issue by RekhaDasari** [gatling/gatling#3114]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [ ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [ ] Check that you can reproduce your issue with latest Gatling version
  * [ ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [ ] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [ ] Explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment]
You are incredible!!! Did you really even took 5 seconds to read the instructions?
