### ISSUE TITLE
JMS: Make queue names dynamic

### ISSUE THREAD

**Issue by kiggundu** [gatling/gatling#3123]
We would like to run a test suit where different JMS requests have a 'feeder' driven response queue name. However, when calling replyQueue("${queueName}") even though the queueName has been set to say 'replyQueue' in the session the JMS client seems to be listening on a queue named '${queueName}'

The attached [test-case](https://github.com/gatling/gatling/files/449235/ELIssueTestCase.scala.txt) when run produces 10 messages which appear as per the attached [screenshot](https://cloud.githubusercontent.com/assets/690186/18162232/54858386-702d-11e6-8b96-d7e857d816bf.png) in activemq. Note that though the EL correctly evaluates the message text and transactionId it does not evaluate the response queue correctly. It appears that this is because method accepts a String as opposed to a Gatling EL experession

[ELIssueTestCase.scala.txt](https://github.com/gatling/gatling/files/449235/ELIssueTestCase.scala.txt)
![screenshot from 2016-09-01 10-17-03](https://cloud.githubusercontent.com/assets/690186/18162232/54858386-702d-11e6-8b96-d7e857d816bf.png)

**Comment by slandelle** [comment]
And what would the behavior be?
Create one consumer per queue per virtual user? One per queue and shared amongst virtual users?

**Comment by kiggundu** [comment]
"One per queue and shared amongst virtual users" is representative of our real world scenario.

**Comment by slandelle** [comment]
Could make sense to support this in Gatling 3.

**Comment by caoimhindenais** [comment]
Hi, 
Is there a workaround for such a case in Gatling 2.0?

Something like the following :

`feed(queueFeeder)
....
queue(EL.compile("${inQueueName}")`

Thanks

**Comment by slandelle** [comment]
no
