### ISSUE TITLE
Specify multiple simulations (maven plugin)

### ISSUE THREAD

**Issue by ronanquillevere** [gatling/gatling#3125]
I am using gatling maven plugin and I would like to be able to specify multiple simulations

today I can choose either 
```xml
<simulationClass>Foo</simulationClass>
```

either 
```xml
<simulationsFolder>src/test/scala</simulationsFolder>
```
maybe you could do the same kind of things as the mvn resource plugin
https://maven.apache.org/plugins/maven-resources-plugin/examples/include-exclude.html

Note that I need this because when I specify the simulationsFolder, if I use some scala code outside this folder then I get compilation errors as if the classpath were only using that folder. I do not know how to change that

**Comment by slandelle** [comment]
You can configure `includes` and `excludes` and enable `runMultipleSimulations`

**Comment by ronanquillevere** [comment]
Thanks for the answer, I was already using `runMultipleSimulations` that I found inside the the maven plugin mojo source code

https://github.com/gatling/gatling-maven/blob/master/gatling-maven-plugin/src/main/java/io/gatling/mojo/GatlingMojo.java

A quick example inside the maven plugin doc page withou includes and excludes would be great imo !

**Comment by slandelle** [comment]
Agree. This would be a perfect opportunity to contribute :)
https://github.com/gatling/gatling/blob/master/src/sphinx/extensions/maven_plugin.rst

**Comment by ronanquillevere** [comment]
#3128

**Comment by ronanquillevere** [comment]
Build is failing but does not seem related to my change (only a doc page ...)

**Comment by ronanquillevere** [comment]
@slandelle do not know how to rebase and squash just created another pull request (faster for me)
#3130

**Comment by slandelle** [comment]
* `git rebase -i HEAD~n` where `n` is the number of commits you want to squash
* replace `pick` with `f` (for fixup) for squashing
* `git push --f origin nameOfYourBranch` to update your repository

**Comment by ronanquillevere** [comment]
Sorry I am a git noob + used github to create branch and pull request

#3130 should be fine @slandelle
