### ISSUE TITLE
Type mismatch on http methods

### ISSUE THREAD

**Issue by AlginMaduro** [gatling/gatling#3127]
The 2 code snippets provided below is the bug.
The get evaluates correctly, but the put gives a type mismatch, namely expected Session.Expression[String], actual Validation[String].
Using Gattling 2.2.2

only way to get it working is through a workaround which is the 3rd scenario

```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._

  val get = scenario("scenario")
    .exec(http("")
    .get("/some-url-path/" + userId))

  val putFail = scenario("scenario")
    .exec(http("")
    .put("/some-url-path/" + userId))

  val putFail2 = scenario("scenario")
    .exec(http("")
    .put(s"/some-url-path/$userId"))


  val putUrl = "/some-url-path/" + userId
  val putWorks = scenario("scenario")
    .exec(http("")
      .put(putUrl))
```

**Comment by slandelle** [comment]
Pretty certain the error is on your side.
Could you please provide a full sample that's supposed to compile? Here, `userId` is undefined.

**Comment by slandelle** [comment]
Tested with userId declared in scope as an Int or a String and compiles perfectly fine.
Closing for now.
