### ISSUE TITLE
Accessing session from feeder

### ISSUE THREAD

**Issue by thmd** [gatling/gatling#3148]
I have some testing that I want to do where the data for the scenarios are very user dependent and while I can use parsers and add some scala code in the gatling script to simulate that it breaks down the abstraction heavily and makes us copy paste a fragile bit of code.

I wanted to write a feeder that would encapsulate this but to do that I need access to the gatling session object. So my idea is to pass some userAttributeName during the construction and the feeder will parse the file using built-in parser, group it by user and when the feed() is called it will get the userId from the session with the given attributeName and will use that to provide appropriate value.

Also if I understand correctly gatling random feeding is global whereas for this scenario I might want to do random access on the user level dat (sometimes) and for that I can actually store the Random object instance in the session and use that.

I have no idea how the feeders is implemented and if its even possible to provide such access. But I think you can encapsulate almost any complex feed logic if you can manage state and track user through the session.

**Comment by slandelle** [comment]
When you created this issue, there were some pretty clear instructions on what an issue or a feature request is, and to use the community mailing list otherwise.

**Comment by thmd** [comment]
I read the instruction and posted here since it was a feature request. As far as I understand you cannot access gatling session object from a feeder. And I also tried to explain how I use such a feature to implement my requirements not how that feature itself needs implementation.

This might be something not possible and ok to be rejected but I'm unfortunately at a loss where I misunderstood the instruction.

**Comment by slandelle** [comment]
As explained in the doc, `Feeder[T]` is a mere alias for `Iterator[Map[String, T]]`, so there's no way it could access the session.
What you want is a custom action, and that's something you can do in an `exec(function)` action.
