### ISSUE TITLE
Jenkins: SyntaxError on JSON parsing in trends

### ISSUE THREAD

**Issue by kimiffx** [gatling/gatling#3154]
Hi

performance trends are empty in Jenkins 2.23 and Gatling plugin 1.2.0.

Console show following error: 
(index):39 Uncaught SyntaxError: Unexpected token ,
(index):73 Uncaught SyntaxError: Unexpected token ,
(index):107 Uncaught SyntaxError: Unexpected token ,
(index):139 Uncaught SyntaxError: Unexpected token ;

All independent reports shows ok.

It's looks like https://github.com/gatling/gatling/issues/3069 is same kinfd of issue

**Comment by slandelle** [comment]
Not sure if it's related to #3069. As this on is fixed, you can build a snapshot from sources and give it a try.
Otherwise, we can only investigate this if you can provide a way to reproduce.
If you can't I'm afraid you'll have to investigate yourself.

**Comment by kimiffx** [comment]
Hi

I compile 1.2.1-plugin snapshot, but didn't get it to work. Following error occurs when I try to open Gatling reports.

**Comment by ccedric** [comment]
I've fixed the issue. It will be available on the next release.
