### ISSUE TITLE
Gatling bat file prints doesn't give a pause to choose simulation number

### ISSUE THREAD

**Issue by Ahmed-A-Syed** [gatling/gatling#3158]
Gatling as a zip file works well. We were trying to integrate gatling in to our application, as we don't find ant plugins for gatling integration , we were trying to run the gatling.bat file from our app using ant. Running gatling. bat file from ant build gives an below issue. It infinitely prints Simulation number options and doesn't give a pause to choose a simulation number. 

    **build file console:**

     [exec] GATLING_HOME is set to "C:\ECPR\workspace\gatling-plugin"
     [exec] JAVA = ""C:\ECPR\java\jdk1.8.0_51\bin\java.exe""
     [exec] "C:\ECPR\workspace\gatling-plugin"\lib\*;"C:\ECPR\workspace\gatling-plugin"\user-files;"C:\ECPR\workspace\gatling-plugin"\conf;    

     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
     [exec] Choose a simulation number:
     [exec]      [0] ebs.ecpr.EcprSimulation
     [exec]      [1] ebs.mcie.McieSimulation
     [exec] Invalid characters, please provide a correct simulation number:
      ............
      ............ 
      ............
help me to resolve the issue

**Comment by slandelle** [comment]
We don't support embedding Gatling.

**Comment by Ahmed-A-Syed** [comment]
Is there any way or approach to integrate the gatling with the java ee application. We were not using maven or gradle. its an ant based application
