### ISSUE TITLE
"extraInfo.request.getStringData" always returns "null" if HTTP Request JSON body is short.

### ISSUE THREAD

**Issue by lfazari** [gatling/gatling#3161]
Hello, I'm using Gatling 2.2.2.

I'm using "extraInfoExtractor" to get some nice printouts from my http requests and responses and I've noticed that "extraInfo.request" (and of course the more specific "extraInfo.request.getStringData") returns a null http request body every time the json body in the request is kinda short.
I get always the same behavior, and "extraInfo.response.body.string" works really fine all the time.
No problem when the request is kind of long (I can't say from when it starts to work).
This is an example of a JSON HTTP  request body that "extraInfo.request.getStringData" returns as "null" (The request succeeds):

{  
   "params":{
        "name": "foo",
        "product": "1234",
        "data": "XCRTGSJJUUSJ",
        "otherData": "None"
   },
   "jsonrpc":"2.0",
   "method":"myMethod.execute",
   "id":101
}

**Comment by slandelle** [comment]
`Request`'s javadoc is incorrect. `getXXXData` returns the body in the form it was originally passed. Gatling optimizes body bytes computation, so the body might not be a String.

**Comment by MichaelCowanPdx** [comment]
So I am having this same issue. How do I get the body?   extraInfo.response.body.string does not compile. Can't resolve body.  Help?
