### ISSUE TITLE
Incorrect percentile 99 in graphite report.

### ISSUE THREAD

**Issue by bhattchaitanya** [gatling/gatling#3164]
I see that the percentiles99 have the same value as percentile95. Looks like inadvertently the incorrect values are published to the percentile99 column. 

I can reproduce this for every test. I cross verified that the HTML report shows totally different TP99 and it seems correct.  Only graphite seems to report same values for Percentile 99 and Percentile 95.

Please note that I have tested this scenario with over 10000 transactions with varying response times.

**Comment by slandelle** [comment]
Sorry, can't reproduce.
Are you sure your data is not such that the 95th and the 99th percentiles are equal (could happen if you only have a few artifacts), or that you didn't mess up with the percentiles ranks in gatling.conf?

**Comment by bhattchaitanya** [comment]
`  charting {
    #noReports = false       # When set to true, don't generate HTML reports
    #maxPlotPerSeries = 1000 # Number of points per graph in Gatling reports
    #useGroupDurationMetric = false  # Switch group timings from cumulated response time to group duration.
    indicators {
      #lowerBound = 800      # Lower bound for the requests' response time to track in the reports and the console summary
      #higherBound = 1200    # Higher bound for the requests' response time to track in the reports and the console summary
      percentile1 = 50      # Value for the 1st percentile to track in the reports, the console summary and Graphite
      percentile2 = 90      # Value for the 2nd percentile to track in the reports, the console summary and Graphite
      percentile3 = 95      # Value for the 3rd percentile to track in the reports, the console summary and Graphite
      percentile4 = 99      # Value for the 4th percentile to track in the reports, the console summary and Graphite
    }
  }`

 ```
graphite {
      #light = false              # only send the all* stats
      host = "localhost"         # The host where the Carbon server is located
      port = 2003                # The port to which the Carbon server listens to (2003 is default for plaintext, 2004 is default for pickle)
      protocol = "tcp"           # The protocol used to send data to Carbon (currently supported : "tcp", "udp")
     # rootPathPrefix = "jmeter" # The common prefix of all metrics sent to Graphite
      bufferSize = 15192          # GraphiteDataWriter's internal data buffer size, in bytes
      writeInterval = 5          # GraphiteDataWriter's write interval, in seconds
      bucketWidth = 100
    }
  }
```

**Comment by slandelle** [comment]
> I see that the Gatling version 2.2.2 does not have the property bucketWidth.

I think `bucketWidth` is something that existed in Gatling 1 version and disappeared years ago.

> Does it matter if I include/exclude?

I don't get you.

> I think that the percentile aggregation function in Gatling is taking a very small set of values before streaming it out to Graphite. Could that be a possibility?

No. We take all values into account and compute percentiles every second.

Your problem is simply that you don't have enough values (from ok.count series) to get different percentile values.
