### ISSUE TITLE
Add the ability to check for an exception type error condition as the expected response to an HTTP request

### ISSUE THREAD

**Issue by andycognitoiq** [gatling/gatling#3165]
Currently in Gatling it is possible to check for error responses to an HTTP request if the error manifests as an HTTP status code (e.g. 4xx or 5xx). However it is not possible to check for an error response that manifests as an exception, for example a timeout.

We've taken a copy of the Gatling snapshot and added in a two types of check for the HTTP request. These checks are:

error - This check matches an exact error string - e.g. error("ConnectionException: Connection timed out")
errorRegex - This check uses a regular expression match - e.g. errorRegex("(?i)._\QConnectException\E._")

We'd like to submit a pull request with our changes so these can be included in future Gatling releases.

**Comment by slandelle** [comment]
Could you please explain your use case? Why do you need to check exceptions?

**Comment by slandelle** [comment]
@andycognitoiq gentle ping

**Comment by green-creeper** [comment]
@slandelle I have the same requirement.
My case is that I need to stress-test my service to check what happens if we have lots of requests with incorrect SSL certificate, or wrong subdomain.  In this case I expect j.n.ConnectException: Received fatal alert: handshake_failure, but there is no way to consume it as expected behavior

**Comment by enriquezrene** [comment]
+1

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by slandelle** [comment]
Feature request has been idle for too long, closing for now.

Will reopen if someone chimes in with a contribution.
