### ISSUE TITLE
SBT: provide a giter8 template

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3168]
Once sbt 0.13.13 is out.

https://github.com/sbt/sbt/pull/2705

**Comment by slandelle** [comment]
example: https://github.com/polymorphic/gatling-simulation-template.g8

**Comment by slandelle** [comment]
Feature request has been idle for too long, closing for now.

Will reopen if someone chimes in with a contribution.

**Comment by asarturas** [comment]
Hi @slandelle, I have put up template, which uses sbt plugin and sample basic simulation from docs. Is that kind of minimal example what you needed? https://github.com/spikerlabs/gatling.g8

**Comment by slandelle** [comment]
Hi @asarturas 

Exactly! Would you be interested in contributing it so it's hosted in the gatling Github organization?

**Comment by asarturas** [comment]
Would like to keep attribution to it, but otherwise - sure, would be great. More people may find it when in gatling org. I've also added travis to ease the discoverability of issues later.

How do we do that @slandelle?

**Comment by slandelle** [comment]
> Would like to keep attribution to it somehow

We require to get copyright (as a software editor startup, shared copyright would be a legal mess for us) and generally use Apache 2 license.

Then, we would mention you in the README and in the [contributors](https://gatling.io/docs/current/project/contributors/) page.

**Comment by asarturas** [comment]
I will transfer project via github to gatling org? and I am okay to transfer copyright to your org if that's what you need to keep it open there. Is there address I can email you? Feels like any further discussion on this is quite offtopic. We can post result here for the history.

**Comment by slandelle** [comment]
slandelle at gatling dot io

**Comment by slandelle** [comment]
Living now in https://github.com/gatling/gatling.g8

Kudos to @asarturas !
