### ISSUE TITLE
[Gatling Maven plugin] "mvn install -DskipTests" executes Gatling tests

### ISSUE THREAD

**Issue by EugeneAbramchuk** [gatling/gatling#3169]
Hi guys, thanks for the framework!

I found out that Maven always tries to run Gatling tests as a part of install phase. While debatable on it's own, even the -DskipTests parameter does not control this. This is rather opposed to other plugins behaviour and it would be nice to align it.

**Comment by slandelle** [comment]
> I found out that Maven always tries to run Gatling tests as a part of install phase. While debatable on it's own.

No, it's pretty normal that the Gatling plugin is bound by default to the `test` phase, which is of course triggered when running `mvn install`. You can bind to to other phases if you want, or move the plugin in a profile.

> even the -DskipTests parameter does not control this. This is rather opposed to other plugins behaviour and it would be nice to align it.

AFAIK, `skipTests` is a surefire plugin prop and not a maven standard. I don't think it's honored by other plugins.
We have our [own property](https://github.com/gatling/gatling-maven/blob/master/gatling-maven-plugin/src/main/java/io/gatling/mojo/GatlingMojo.java#L129) for skipping. Having our own different one is intended to one can easily disable surefire without disabling gatling.

I'll reject the issue for now. Feel free to keep on discussing here if you want.

**Comment by EugeneAbramchuk** [comment]
Sounds reasonable, thanks.
