### ISSUE TITLE
Upgrade sbt 0.13.13

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3172]
https://groups.google.com/forum/#!topic/sbt-dev/Q4ROTNVH5gY

**Comment by slandelle** [comment]
```
trait Build in package sbt is deprecated: Use .sbt format instead
```

cc @pdalpra

**Comment by pdalpra** [comment]
Yep, we had it coming for a long time :/
I can help with migration if you want :)

**Comment by slandelle** [comment]
I don't really get the reasons behind this move.

Anyway, if you have some spare time to help with this, it would be awesome!

**Comment by pdalpra** [comment]
I happen to have a full week of spare time :) 
The simplest migration path would be to simply move module definitions in `GatlingBuild` to a `build.sbt` as this is the only deprecation here, `.scala` files contributing to the build are still supported AFAIK.
A possible next step would be to move the common settings to a local AutoPlugin, but it's only a nice to have.
WDYT ?

**Comment by slandelle** [comment]
> The simplest migration path would be to simply move module definitions in GatlingBuild to a build.sbt as this is the only deprecation here, .scala files contributing to the build are still supported AFAIK.

> A possible next step would be to move the common settings to a local AutoPlugin, but it's only a nice to have.

I'd rather keep it simple :)

**Comment by slandelle** [comment]
Thanks a lot!
