### ISSUE TITLE
Core: Evaluate sfm-csv

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3174]
Compare with Jackson CSV, both in terms of features and performance.

http://simpleflatmapper.org/0101-getting-started-csv.html
https://github.com/arnaudroger/SimpleFlatMapper/tree/master/sfm-csv

**Comment by arnaudroger** [comment]
just saw that, I've got a benchmark here http://simpleflatmapper.org/12-csv-performance.html
source
might not be representative but at least it's there https://github.com/arnaudroger/mapping-benchmark/tree/master/sfm-csv

**Comment by arnaudroger** [comment]
though looking at gatling code it's using a Map which I tested currently does not work. But if you really care about perf that's far form optimal. but Map should work on sfm investigating why it does not

**Comment by slandelle** [comment]
Hi @arnaudroger 

Thanks for reaching out!

First, we have to kind of usage:
* pre-test parsing. We're in the cold path here. Speed improvement can be interesting, even though not critical. Garbage allocation is not a concern, as we trigger GC after the parsing, before launching test. JIT wouldn't help here.
* on-the-fly parsing. This is something we'll introduce in Gatling 3 to overcome a limitation of the above strategy: huge files can burn a lot of memory if we pre-load all the data in heap. Here, we would be on the hot path, so speed and intermediate allocation could be critical.

Note that I would expect a significant part of the performance to be related to the charset decoding and that results with JDK8 could be very different from JDK9 because of the new String implementation.

I agree that the current implementation that binds to Map (note: those are Scala Maps, not Java ones) is not great. We'll work on this in the next major version. We have to find a good balance between in-memory cold storage and hot adding into Scala Maps (our Session type that's basically a virtual user's memory space).

I'll let you know how things turn out.

Cheers

**Comment by arnaudroger** [comment]
interesting, if you need any help with sfm-csv give me a shout.

There is a low level callback where it points to the underlying  buffer avoiding String creation but only valid in the callback scope. 
```java
CsvParser.reader(source).parserAll( new CellConsumer() {
   void newCell(char[] chars, int offset, int length) {
   }
   boolean endOfRow() {
      return true;
   }
)).
```
Also the Map issue occurs only when passing a non generified type, put that's a small fix. will try and double check if it works with Scala map.

From my benchmark the decoding is quite optimised, takes no more than 20% of the parsing, I have ParallelReader that can do it on another Thread gives a bit of perf boost on very big file.
I wonder what the impact would be of the String byte[] would be coming from a Reader as it's already been transformed in a char[]...

**Comment by slandelle** [comment]
I just gave "sfm-csv" a try. Perf looks great, eg, parsing a 400MB (500,000 records) file into `Iterator[Map[String, String]]`:
* Jackson: 1519 ms
* SimpleFlatMapper: 1145 ms

Sadly, SimpleFlatMapper doesn't properly handle escaping, see https://github.com/arnaudroger/SimpleFlatMapper/issues/459

**Comment by slandelle** [comment]
Correcting myself: it seems the reason for Jackson being slower than SimpleFlatMapper is enabling the escaping feature. When disabling escaping (which is the default), we get:

* Jackson: 833 ms
* SimpleFlatMapper: 1271 ms

**Comment by arnaudroger** [comment]
did you try disabling the escaping in sfm? CsvParse.disableUnescaping() ?

**Comment by slandelle** [comment]
@arnaudroger Yes, I did. I didn't notice any improvement on my test case (which is not super great, one single column, no escaping, but that was an extreme use case that was causing issues for one of our customer. will try next week with more columns).

**Comment by arnaudroger** [comment]
@slandelle has the file your parsing any quoted field? Is there a way I could have a look at the benchmark code? and the data file - if that's not possible an idea of the file format?
Thanks

**Comment by slandelle** [comment]
@arnaudroger Just sent you a private email
