### ISSUE TITLE
Upgrade Scala 2.12

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3179]
* [x] akka
* [x] scala-swing
* [x] scala-xml
* [x] scala-java8-compat
* [x] fastring
* [x] scopt
* [x] scala-logging
* [x] jsonpath
* [x] boopickle
* [x] redisclient
* [x] quicklens
* [x] scalatest
* [x] scalacheck

**Comment by Tvaroh** [comment]
Is there a build using 2.12?

**Comment by AlexPerfMechnix** [comment]
Hi @slandelle , 
I was using gatling 3.0.0 and all was working fine until socket issues with ALB. I couldnt get proper document in migrating from 3.0.0 to Latest. Could you help me on this.

--Alex

**Comment by slandelle** [comment]
@AlexPerfMechnix See the "Upgrading" section in our doc: https://gatling.io/docs/gatling/
Then, questions are better asked on our [community](https://gatling.io/community/).
