### ISSUE TITLE
Custom config file overrided from javaOption '-Dgatling.config=gatling-perf2.conf'

### ISSUE THREAD

**Issue by Telhar** [gatling/gatling#3181]
I need to override a Gatling config file name for several environments. Now in other tests I use a construction like

```scala
val configName = Option(System.getProperty("some.custom.config")).getOrElse(defaultCustomConfigName)
```

And now I need to use it with `gatling.conf`. Can we do that?

```scala
private val GatlingConfigFile = Option(System.getProperty("gatling.config")).getOrElse("gatling.conf")
val customConfig = ConfigFactory.parseResources(classLoader, GatlingConfigFile)
```

**Comment by martin-g** [comment]
I'm not answering your question, just wanted to say that you can simplify it to:
```java
val configName = System.getProperty("some.custom.config", defaultCustomConfigName)
```

**Comment by slandelle** [comment]
No, that's not possible.
Please use the community mailing list for such questions.

**Comment by Telhar** [comment]
OK, sorry about that.
Please, let's talk about this.
https://groups.google.com/forum/#!topic/gatling/901_GLwQ6_Y
