### ISSUE TITLE
findRandom not available until 3.0.0 but is documented in 2.2.3

### ISSUE THREAD

**Issue by barryperez** [gatling/gatling#3182]
findRandom is documented for 2.2.3, yet it doesn't look like this function will be available until 3.0.0.

http://gatling.io/docs/2.2.3/http/http_check.html
http://gatling.io/#/cheat-sheet/2.2.3

**Comment by slandelle** [comment]
@notdryft It seems doc was generated from the wrong branch. `findRandom` doesn't exist in 2.2 and shouldn't be mentioned in cheat sheet (and indeed isn't in [sources](https://github.com/gatling/gatling/blob/master/src/sphinx/cheat-sheet.html)).

**Comment by slandelle** [comment]
@barryperez Thanks for reporting

**Comment by slandelle** [comment]
@notdryft So fast! Thanks man!

**Comment by barryperez** [comment]
Thanks guys!

**Comment by dannyfreak** [comment]
Issue still occurs in 2.2.5 docs
http://gatling.io/docs/current/http/http_check/
http://gatling.io/docs/current/cheat-sheet/

**Comment by slandelle** [comment]
@dannyfreak Thanks for reporting!
