### ISSUE TITLE
Failed requests are logged twice when DEBUG level is enabled

### ISSUE THREAD

**Issue by lguerrin** [gatling/gatling#3183]
I think there is a bug on ResponseProcessor in Gatling 2.2.
In previous version (2.1.7), in AsyncHandlerActor, the implementation is:
`      if (status == KO) {
          logger.warn(s"Request '$fullRequestName' failed: ${errorMessage.getOrElse("")}")
        if (!logger.underlying.isTraceEnabled) logger.debug(dump)
      }
      logger.trace(dump)`

It's ok: log error when DEBUG is enabled and all requests when TRACE is enabled.

But in ResponseProcessor, used in 2.2.3, the implementation is:
`if (status == KO) {
        logger.warn(s"Request '$fullRequestName' failed: ${errorMessage.getOrElse("")}")
        if (!logger.underlying.isTraceEnabled) logger.debug(dump)
      }
      logger.debug(dump)`

So, when DEBUG is enabled, all requests are logged...

**Comment by slandelle** [comment]
> So, when DEBUG is enabled, all requests are logged...

That's the intended behavior. We intendedly raised logging level from TRACE to DEBUG.
The only issue here is that failed requests are logged twice.

**Comment by slandelle** [comment]
Thanks for reporting!

**Comment by lguerrin** [comment]
When you say "We intendedly raised logging level from TRACE to DEBUG.", it's about the second logger?
In this case, we can no longer get only failed requests?

**Comment by bcolmard-ebz** [comment]
Hi guys, I upgraded my project to gatling 2.2.3 and also noticed this behavior : I can't find a way to control independently the logging of failed request body. I relied on the [logback.dummy](https://github.com/gatling/gatling/blob/fac325b8a243edf4a50c238e7a23a009f7903f83/gatling-core/src/main/resources/logback.dummy) sample file, which also reflects the current doc

**Comment by davoustp** [comment]
Hi,
Seen the fix on master, any chance to have a 2.2.x fix soon?
Currently stuck with this issue to investigate failures under high volume traffic, since there is no way to log failed requests only...

**Comment by slandelle** [comment]
@davoustp There's no plan for new public releases for 2.2.x atm, only if some critical bug fixes get contributed by the community. We'll have private ones for our FrontLine customers though.
