### ISSUE TITLE
Gatling stops sending data to InfluxDB, when CPU runs very high

### ISSUE THREAD

**Issue by carlomas** [gatling/gatling#3186]
I have a gatling machine driving a load and sending data to InfluxDB.
What I have noticed is that, when CPU runs high, in short time, it stops sending data to InfluxDB, but everything else works properly.

The arrow is pretty much the moment since we don't have more data on the DB. 
![selection_289](https://cloud.githubusercontent.com/assets/18550707/20316241/00cb8ee0-ab59-11e6-80ed-c56330d1b40d.png)

As you can see from Gatling report at that time there was a problem, with a drop of requests, but then it recovered correctly

![selection_290](https://cloud.githubusercontent.com/assets/18550707/20316385/7fed6482-ab59-11e6-89c2-0f11b1d39c3c.png)

It did not happened with the data sent to the DB.

I am attaching gatling.conf and influx.conf
[gatling.conf.txt](https://github.com/gatling/gatling/files/592729/gatling.conf.txt)
[influxdb.conf.txt](https://github.com/gatling/gatling/files/592730/influxdb.conf.txt)

**Comment by slandelle** [comment]
Well, not much we can do here.

The first thing you have to do is to figure out why you had such CPU spike. Is it Gatling itself? Is it another process on the same host? In any case, it looks like you CPU was eaten by something else than performing IO, computing requests and parsing responses.

Then, InfluxDB sure is convenient, but it's definitively not suited for performance testing as it can't store distributions, so you end up computing averages on percentiles, which is very wrong maths and make your number meaningless. We have FrontLine for such usage.

**Comment by carlomas** [comment]
@slandelle I appreciate your concerns about InfluxDB, but is not the issue here, since I have other 2 load drivers which were still sending data at that time.
The processes eating CPU were all java processes (4 of them including Jenkins), unfortunately I don't have more details, I will instrument the driver with nmon to get more info in case it would reappear.
