### ISSUE TITLE
Core: Remove Validation#get

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3189]
Error prone, unsafe and unused (at least in Gatling).

**Comment by yikkin** [comment]
hello , 

I just upgraded my galting version to 3.0.1.1 and scala version to 2.12 but suddenly I got an issue with this part of my code  ,
![2018-12-20_10h37_30](https://user-images.githubusercontent.com/24577131/50276886-55c7fb00-0443-11e9-951c-27b600d710b1.png)

I was wondering is there any change that has been brought to validation function?
