### ISSUE TITLE
Automatically add users until system breaks

### ISSUE THREAD

**Issue by RichoDemus** [gatling/gatling#3190]
So I'm interested in knowing how many concurrent users my system can take, and I'd like to measure that by setting something like:
The system is ok as long as 95% of all requests take less than 1s, and then gatling would just slowly increase the number of concurrent users until that condition is broken and then end. and that number could be used as a benchmark

**Comment by slandelle** [comment]
We don't support this out of the box atm.
And I don't think we'll ever will in the OSS version, as the injection system isn't coupled to the metrics one.
Maybe something we can consider for FrontLine though.

Note: if this was just a general question and not a feature you were interested in contributing, please use the community mailing list.
