### ISSUE TITLE
Core: Group is considered as OK even if no transaction was built

### ISSUE THREAD

**Issue by StephenSorriaux** [gatling/gatling#3197]
Hello Gatling team,

We encountered the following issue with both 2.1.7 version and latest version (2.2.3) : in a group ,that is successfully done at least one time during the simulation, if, for some reason, no transactions are built, the group will be considered as OK with a very small duration time (0-5ms).
This duration time will be used in the statistics calculation and lead to biased results.

To reproduce the problem, just use the following simulation : 

```scala
class ScenarioTest extends Simulation {
  val scn = scenario("Give me a group with 0 transaction built")
    //GROUP 1 will be ok
    .group("GROUP 1") {
      exec(http("home")
        .get("http://gatling.io/"))
    }
    .pause(5)	
    //add some good requests in group 2
    .group("GROUP 2") {
      exec(http("a request")
        .get("http://gatling.io/"))
    }
    .pause(5)	
    //add some not-built requests in GROUP 2
    .group("GROUP 2") {
      exec(http("a request")
        .get("${url}"))
    }	

    setUp(scn.inject(rampUsers(2) over (20 seconds))).protocols(http.disableCaching)
}
```

In simulation.log, 2 groups "GROUP 2" are OK with a duration time of 0 ms (should be KO)
In the report, 4 "GROUP 2" are "OK" with a minimum time of 0 ms (should be 2 OK and 2 KO)

Have you got a fix for this, please ?

Thank you.

**Comment by slandelle** [comment]
Hi @StephenSorriaux 

Thanks for reporting!
Fix is not straightforward as there are some potential interaction with recovery groups such as tryMax.
Will investigate.
If you want to investigate on your side, you can have a look at gatling private methods in `Session`, typically `markAsFailed`.
