### ISSUE TITLE
getExtraInfo is not providing access to the request body

### ISSUE THREAD

**Issue by MichaelCowanPdx** [gatling/gatling#3202]
Note: I have tried ALL the methods under extraInfo.request and they all return null or show no body. The request is valid, succeeds etc, but I can't print out the body.

Here is some basic code that generates the request

  def addComment(comment : String) = group("Streams.addComment") {
      exec(
        http("AddComment")
          .post("/collaboration/comments")
          .headers(headers_JsonPost)
          .body(StringBody(comment + " - " + new Date().toString))
          .check(currentLocationRegex("^.*login.req.*$").count.is(0))
          .check())
  }

here is the extrainfo code

  private def getExtraInfo(extraInfo: ExtraInfo): String = {
    '\t' + extraInfo.session("currentUserName").as[String] +
      '\t' + extraInfo.session("projectName").as[String] +
      '\t' + extraInfo.request.getUrl +
      '\t' + extraInfo.request.getBodyParts().size()
  }

I have printed out the entire request  extraInfo.request.toString()  and it does not contain the body.  In the addComment method above I am clearly adding the comment text into the body, I see it in the website so I know its working, but the log never shows it.

----
* [x ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [ x] Check that you can reproduce your issue with latest Gatling version
  * [x ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [x ] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x ] Explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment]
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/Request.java#L96-L99

Just that Gatling didn't pass the body as a String.

**Comment by MichaelCowanPdx** [comment]
I don't understand why this is closed? There is no body returned.      List<Part> getBodyParts(); returns 0 body parts.

The issue is not the string, the issue is the body is not accessible from extraInfo

**Comment by slandelle** [comment]
`getBodyParts` is for multipart upload, which you didn't use. You set a whole body.

**Comment by MichaelCowanPdx** [comment]
Thanks for the response. That makes sense.

I am sorry to be so dense, I have really looked for this information. Is it possible to do something to get the body in the extraInfo?  Maybe something I need to add to the request to force it to be saved? Any help would be appreciated. I have tried everything I could find in the Gatling usergroups. Its simply not working the way I am doing it.

**Comment by slandelle** [comment]
I'm sorry that you couldn't find an answer to your question on the community mailing list, and if you've raised a question here, that nobody could help.
As for getting help from the core committers, please understand that Gatling is our means of making a living, and that we provide such help as a [services](http://gatling.io/#/services) offer.
