### ISSUE TITLE
Core: Between assertion fails on valid data

### ISSUE THREAD

**Issue by vas78** [gatling/gatling#3203]
With Gatling 2.2.3 the "between" assertion fails although the underlying data is correct, here`s a screenshot:
![between_assertion](https://cloud.githubusercontent.com/assets/17594673/20882706/8201b758-bae2-11e6-9591-c7b2510d202c.PNG)

**Comment by vas78** [comment]
Looks like this has something to do with this "inclusive feature": when it is explicitly to false assertions work as expected. Here`s the same scenario with inclusive set to:
1. true (default?)
![between_inclusive_true](https://cloud.githubusercontent.com/assets/17594673/20883367/0bfdebae-bae6-11e6-89e6-91c92b834d6d.PNG)

2. false
![between_inclusive_false](https://cloud.githubusercontent.com/assets/17594673/20883373/11b5cfbc-bae6-11e6-81a8-c00a2c5ed82e.PNG)

**Comment by slandelle** [comment]
Indeed a bug, thanks for reporting!
