### ISSUE TITLE
Load Gap and Aliasing with usersPerSecond rate below 1

### ISSUE THREAD

**Issue by gmuecke** [gatling/gatling#3205]
We're using the latest version of the gatling-maven-plugin (2.2.1) and we define our scenarios with user-per-minute rate (because that's whats specified) doing the conversion to user/sec rate with:

```
def perMinute(rate : Double): Double ={
  rate / 60
}
```
and we run scenarios, like this

```
setUp(
  Scenarios.longRun.inject(
     constantUsersPerSec(perMinute(12)) during(6 hours)
    , constantUsersPerSec(perMinute(18)) during(2 hours)
    , constantUsersPerSec(perMinute(24)) during(2 hours)
    , constantUsersPerSec(perMinute(30)) during(2 hours)
    , constantUsersPerSec(perMinute(36)) during(2 hours)
    , constantUsersPerSec(perMinute(30)) during(2 hours)
    , constantUsersPerSec(perMinute(24)) during(4 hours)
    , constantUsersPerSec(perMinute(18)) during(4 hours)
  )
).protocols(httpProtocol)
```

With these setting we experience the following active-user curve
![load-graph](https://cloud.githubusercontent.com/assets/8408106/20886854/53b774f8-baf8-11e6-97f7-d22d82126a0a.png)

- load level is aliased, i.e. {24,30,36} users / min = 30 users/min, we should see 5 steps, but only have 3
- at the end of period with an aliased rate (i.e. 18 or 24) there is a gap where the load drops to 0

My guess is, the period between two users is rounded to seconds.

- with 12 users/min, we have 5 seconds between users -> no rounding.
- with 18 users/min, we have 3.3 seconds between users -> rounded down to 3, gap = 10% of duration (0.3 of 3.3), i.e. 12 min for 2 hour duration
- with 24 users/min, we have 2.5 seconds between users -> rounded down to 2, gap = 20% of duration (0.5 of 2.5), i.e. 24 min for 2 hour duration
- with 30 users/min, we have 2 seconds between users, no gap, same load as with 24 users/min
- with 36 users/min, we have 1.66 seconds between users, rounded up to 2, no gap, same load as with 30 or 24 users/min 

while the total number of users within period - calculated with numTotal = rate * numberOfSeconds - is reasonably precise, given a duration >= 1/rate, 
the waittime between each user in seconds seems to be to coarse for rates between 0 and 1 (because waittime is calculated by 1 / rate).

see also [this forum entry](https://groups.google.com/forum/#!topic/gatling/GOrFOCUpNGo)

**Comment by slandelle** [comment]
>  We're using the latest version of the gatling-maven-plugin (2.2.1)

As I explained on the mailing list, the `gatling-maven-plugin` version doesn't help much.
Depending on what you've configured, you could as well be using Gatling 2.2.0, 2.2.1, 2.2.2 or 2.2.3.

Could you please make sure that you're using 2.2.3?

**Comment by gmuecke** [comment]
Sorry for the confusion, we're using Gatling 2.2.2, 
I tested now with 2.2.3 with same result. 

The gap seems to be largest with the 24 users/min setting (20%). I made a short run with 2 x (24users/min for 2 minutes)

```
setUp(
  Scenarios.longRun.inject(
      constantUsersPerSec(perMinute(24)) during(2 minutes)
      , constantUsersPerSec(perMinute(24)) during(2 minutes)
  )
).protocols(httpProtocol)
```
with this distribution
![responsetimes2](https://cloud.githubusercontent.com/assets/8408106/20887391/a0ba4aa8-bafa-11e6-888e-72a10adc5806.png)

**Comment by slandelle** [comment]
Get it, that's an evenly distribution issue.

**Comment by slandelle** [comment]
Thanks for reporting!
