### ISSUE TITLE
I am getting this error while running my gattling code [at io.gatling.http.protocol.HttpProtocol$.apply(HttpProtocol.scala:71)]

### ISSUE THREAD

**Issue by Amrit998** [gatling/gatling#3209]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [ ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [ ] Check that you can reproduce your issue with latest Gatling version
  * [ ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [ ] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [ ] Explain your use case, not the implementation you have in mind.

**Comment by Amrit998** [comment]
This is my code.Please look to it
import io.gatling.core.Predef._ 

import io.gatling.http.Predef._

import scala.concurrent.duration._



class Simulations extends Simulation {

  



  

def test(){

  val httpConf = http 

    .baseURL("http://computer-database.gatling.io")

    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")

    .doNotTrackHeader("1")

    .acceptLanguageHeader("en-US,en;q=0.5")

    .acceptEncodingHeader("gzip, deflate")

    .userAgentHeader("Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0")



  val scn = scenario("BasicSimulation") 

    .exec(http("request_1")

    .get("/"))

    .pause(5) 



  setUp( 

    scn.inject(atOnceUsers(1)).protocols(httpConf)) 

 

}}

object Demo {





def main(args: Array[String]) {

val pt = new Simulations

pt.test()

}

}

**Comment by slandelle** [comment]
You didn't follow the instructions that were displayed when you created this issue that's not one.
Please use the community mailing list.
