### ISSUE TITLE
gatling.bat tells me that GATLING_HOME is not set, refuses to proceed

### ISSUE THREAD

**Issue by paolo-tanium** [gatling/gatling#3211]
![image](https://cloud.githubusercontent.com/assets/21039701/21203594/27a48dee-c221-11e6-9377-63e6b84d1f80.png)

Steps to reproduce: 

1. Get the latest version 2.2.3: https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/2.2.3/gatling-charts-highcharts-bundle-2.2.3-bundle.zip
2. Add GATLING_HOME to your environment variables.
3. Ensure that JAVA_HOME is correctly set.
4. cd %GATLING_HOME%
5. run bin\gatling.bat

**Comment by slandelle** [comment]
Your problem has nothing to do with GATLING_HOME not being set, but with the first error: "The input line is too long".
Move your gatling directory closer to your root so the path gets shorter.
