### ISSUE TITLE
request body with json type, it's not work correctly

### ISSUE THREAD

**Issue by SilenceWang** [gatling/gatling#3212]
I write a parameter file with contents like:
`[
  {"key": "this is a key",
   "value": {
        "k_1" : "1",
       "k_2" : 2
 }
}
]`

and I used it in my script by 

`
val scn = scenario("multiple_online") // A scenario is a chain of requests and pauses
   .feed(feeder)
   .exec(http("multiple_online")
     .post("${key}")
     .headers(headers_1)
     .body(StringBody("""${value}""")).asJSON
`
after running it，I got request body like: {k_1=1, k_2=2} , which is not a json I expected.
while I try it by
body(StringBody("""{"k_1":"1", "k_2":2}""")).asJSON. it works!

so, what's wrong with my script

**Comment by slandelle** [comment]
My2cents: you're using a CSV feeder, but you don't escape the commas in your JSON payloads.

Closing for now. Please feel free to provide a working reproducer if it really seems to be a Gatling issue and not a problem on your side.
