### ISSUE TITLE
redirect gatling.io/download to http://gatling.io/#/resources/download

### ISSUE THREAD

**Issue by jasongoodwin** [gatling/gatling#3219]
This works: http://gatling.io/#/resources/download

But most of the download links out there point to a broken page.
This points to the wrong download site:
https://github.com/gatling/gatling/wiki/Downloads
It points to:
http://gatling.io/download/
Which is a 404.

You should fix the link on https://github.com/gatling/gatling/wiki/Downloads and redirect gatling.io/download to http://gatling.io/#/resources/download as I'm sure some links out there reference it. 

Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [x] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [x] Check that you can reproduce your issue with latest Gatling version
  * [x] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [x] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x] Explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment]
Actually, it's time to pull the trigger on the wiki, which has been replaced by the online documentation on our website for about 5 years. Disabling it.

Thanks for reporting!
