### ISSUE TITLE
Reports: Active users graph not complete

### ISSUE THREAD

**Issue by Thilak-T** [gatling/gatling#3220]
Active users graph doesn't correspond with simulation.log or gatling console log. Whenever I run the simulation for more than 20 minutes,  the active users graph shows activity only upto ~16 minutes. After that as per graph there were 0 users but the simulation ran until end say 30 minutes. But as per logs and simulation.log, users were injected until the end i.e 30 mins.

Attached the report screenshot 
![screen shot 2017-01-17 at 1 48 25 pm](https://cloud.githubusercontent.com/assets/6108057/22009065/8f22a1f4-dcbb-11e6-9e2d-11e17ac8c5f0.png)
[simulation.log.zip](https://github.com/gatling/gatling/files/710097/simulation.log.zip)

and simulation.log

I run gatling 2.2.3 in linux.

**Comment by slandelle** [comment]
Thanks for reporting.

**Comment by nei** [comment]
I had a similar issue when I was running gatling with one version and generating the graphs with a newest version. Not sure if that is your case.

**Comment by maximerouillard** [comment]
I encountered a similar issue. I notice you add the fixed label. Is it possible to have more information about the correction?
I would like to fork the correction and test it locally.

**Comment by slandelle** [comment]
The fix hasn't been released publicly and is available for our customers. We only push in the public repository from time to time.

**Comment by Thilak-T** [comment]
Oh..until then is there any workaround
