### ISSUE TITLE
JMS: deal with connection crashes

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3227]
We should register `ExceptionListener` on the `Connection`, and try to reconnect.

**Comment by pwielgolaski** [comment]
What could be the case? 
If we use connection and it will be dropped, when we reconnect we can lost also temporary queues that we use for response.
What is scenario that it could be valid to reestablish connection instead of failing testing?

**Comment by slandelle** [comment]
Maybe people not using temporary queues have some auto-reconnect strategies.
Not sure about that.
