### ISSUE TITLE
Maven artifacts lagging slightly behind?

### ISSUE THREAD

**Issue by erikkemperman** [gatling/gatling#3228]
Just a quick question -- maven central has 2.2.3 for most components, but not gatling-maven-plugin nor gatling-maven-parent, which are still on 2.2.1. Is this deliberate, or am I just being impatient?

Thanks!

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.gatling%22

**Comment by slandelle** [comment]
Hi,

Please don't use our bug tracker for asking questions.
Versions are not aligned as lifecycles are different.

**Comment by erikkemperman** [comment]
Ok, thanks for quick response, sorry for abusing issue tracker.
