### ISSUE TITLE
 [ERROR] i.g.a.ZincCompiler$ -  not found: value exec

### ISSUE THREAD

**Issue by ThakkarGit** [gatling/gatling#3236]
Hi,

I am receiving following error during compilation. able to run same project last year...

12:40:45.861 [ERROR] i.g.a.ZincCompiler$ - C:\share\jenkins\jobs\EBPI_PERF_TestAs_Service\workspace\gatling\user-files\simulations\ITO\ITO_SignUpByRealm_V2.scala:62: not found: value exec

**Comment by slandelle** [comment]
Really, there's nothing anyone could do with such a description.
When you created this issue, you were asked to provide informations, but you decided not to.
Closing.

**Comment by ThakkarGit** [comment]
Who ask for more information and what kind of information required?
