### ISSUE TITLE
App: Don't loop for input infinitely

### ISSUE THREAD

**Issue by nafg** [gatling/gatling#3240]
I'm on Ubuntu 16.04. I downloaded gatling and double-clicked `bin/gatling.sh`. A while later I noticed my disk was full. `/var/log/syslog` has grown to over 13GB with lines like this:

```
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]: Choose a simulation number:
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [0] computerdatabase.BasicSimulation
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [1] computerdatabase.advanced.AdvancedSimulationStep01
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [2] computerdatabase.advanced.AdvancedSimulationStep02
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [3] computerdatabase.advanced.AdvancedSimulationStep03
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [4] computerdatabase.advanced.AdvancedSimulationStep04
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [5] computerdatabase.advanced.AdvancedSimulationStep05
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]: Invalid characters, please provide a correct simulation number:
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]: Choose a simulation number:
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [0] computerdatabase.BasicSimulation
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [1] computerdatabase.advanced.AdvancedSimulationStep01
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [2] computerdatabase.advanced.AdvancedSimulationStep02
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [3] computerdatabase.advanced.AdvancedSimulationStep03
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [4] computerdatabase.advanced.AdvancedSimulationStep04
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [5] computerdatabase.advanced.AdvancedSimulationStep05
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]: Invalid characters, please provide a correct simulation number:
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]: Choose a simulation number:
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [0] computerdatabase.BasicSimulation
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [1] computerdatabase.advanced.AdvancedSimulationStep01
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [2] computerdatabase.advanced.AdvancedSimulationStep02
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [3] computerdatabase.advanced.AdvancedSimulationStep03
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [4] computerdatabase.advanced.AdvancedSimulationStep04
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [5] computerdatabase.advanced.AdvancedSimulationStep05
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]: Invalid characters, please provide a correct simulation number:
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]: Choose a simulation number:
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [0] computerdatabase.BasicSimulation
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [1] computerdatabase.advanced.AdvancedSimulationStep01
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [2] computerdatabase.advanced.AdvancedSimulationStep02
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [3] computerdatabase.advanced.AdvancedSimulationStep03
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [4] computerdatabase.advanced.AdvancedSimulationStep04
Feb 15 21:34:32 naftoli-ThinkPad-W540 nautilus-autostart.desktop[6150]:      [5] computerdatabase.advanced.AdvancedSimulationStep05
```

Indeed, the process was still running, so I killed it. Now I have to figure if it's possible to delete the garbage from syslog without losing all my log history.

Please don't loop forever!

**Comment by nafg** [comment]
(realized logs are rotated so it's only one day's logs)

**Comment by slandelle** [comment]
Any idea what was causing invalid characters and enter signals to be sent to SYSIN?
Seriously [reminds me of something](http://coub.com/view/6qyy2)...

**Comment by nafg** [comment]
@slandelle sorry I wasn't clear (I guess I thought it was obvious) -- there was no terminal. I double-clicked it via the gui (nautilus) and didn't select Run in terminal (I didn't know what double-clicking would do).

So yeah, you might want to check whether stdin is a terminal or whether the "input" is EOF. But you should probably avoid infinite loops altogether, regardless.

Is there any real point in looping in the first place? Is it a big deal to just quit if the input is invalid?

**Comment by nafg** [comment]
(of course, part of the blame might go to whatever is sending that to syslog, I'm guessing systemd)

**Comment by slandelle** [comment]
IMO, the root cause is something is utterly broken on Nautilus (launching a process in the background, then piping sysin to it). Xfce doesn't do that, for example. As such, adding a protection like the one you suggest is not a priority for us. Then, fell free to contribute and provide a PR.

Cheers

**Comment by nafg** [comment]
Why, are all your users on xfce?

**Comment by slandelle** [comment]
All our developers who run on Linux run on Xfce so we could verify that it doesn't behave the way you describe. Then, you're first one to ever report such issue while Gatling has been running this way for 6 years, hence the low priority.

**Comment by nafg** [comment]
With that attitude (and for something so easy to fix), I have no interest
in contributing.

**Comment by slandelle** [comment]
I didn't mean to be rude, pity you got it this way.
Indeed, such protection is something that would be easy to add, hence it would be easy for a newcomer to jump in and contribute. That's why I flagged it as "Low Hanging Fruit" and "Contributions Welcome".
Please understand that our time is as precious as yours and that we have to set priorities.

**Comment by nafg** [comment]
The emails don't mention the labels. Also maybe English isn't your first language but the connotation of "X is not a priority for me" is usually "I have zero interest in X," although I see now you meant it literally.
Anyway I ended up not using Gatling because I didn't actually need it, so I don't have any plans to contribute.

**Comment by nafg** [comment]
Anyway I think that something this catastrophic, that can happen so easily
on the most widely used Linux desktops, should not be low priority.

**Comment by slandelle** [comment]
> Also maybe English isn't your first language

Indeed

> "that can happen so easily on the most widely used Linux desktops"

That's still has to be proven. As I said, you're the first one to ever report such behavior. In the meantime, we've tested with Nautilus and couldn't reproduce your behavior.

Generally speaking, I'm not in the favor of rushing into implementing countermeasures for issues whose root cause has been properly identified, all the more when it seems to be another system. This cause root causes to never get fixed.

Here, the fishy thing is that it seems the background process kept on being notified in its sysin our your keyboard input. This is very unexpected.

**Comment by nafg** [comment]
On Fri, Feb 17, 2017, 12:36 PM Stephane Landelle <notifications@github.com>
wrote:

> Also maybe English isn't your first language
>
> Indeed
>
> "that can happen so easily on the most widely used Linux desktops"
>
> That's still has to be proven. As I said, you're the first one to ever
> report such behavior. In the meantime, we've tested with Nautilus and
> couldn't reproduce your behavior.
>
Interesting! Was it on a systemd OS? (I'm on the latest Ubuntu.)

> Generally speaking, I'm not in the favor of rushing into implementing
> countermeasures for issues whose root cause has been properly identified,
> all the more when it seems to be another system. This cause root causes to
> never get fixed.
>
I totally agree. But I do think one can question the wisdom of looping
infinitely.

> Here, the fishy thing is that it seems the background process kept on
> being notified in its sysin our your keyboard input. This is very
> unexpected.
>
So to be clear, you're saying that if you redirect /dev/null into stdin, it
does not loop?

**Comment by nafg** [comment]
Thanks!
