### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by amitguptagwl** [gatling/gatling#3241]
I found that links under this [tutorial](http://gatling.io/docs/1.5.6/user_documentation/tutorial/first_steps_with_gatling.html#the-application-under-test) page are broken.

**Comment by slandelle** [comment]
If you have a look at the top of the page, you'll see this warning.

<img width="855" alt="capture d ecran 2017-02-17 a 06 53 33" src="https://cloud.githubusercontent.com/assets/849197/23055472/ee63cdd4-f4dd-11e6-81ce-f0eba8c8d649.png">

Indeed, you're checking the documentation for Gatling 1, which has been dead for years.

Anyway, we're about to launch a new version of our website and this page will go away.

**Comment by amitguptagwl** [comment]
Thanks. I seen that warning but I thought external links would not be dead with the documentation. So I found better to inform :)

**Comment by slandelle** [comment]
Yes, we killed this app a long time ago. One more reason to pull the trigger on everything related to Gatling 1.
Thanks for reporting :)
