### ISSUE TITLE
Gatling throwing "No attribute name 'CSVFieldName-X' is defined" , though fieldName is correct .  

### ISSUE THREAD

**Issue by Ritesh-Sharma** [gatling/gatling#3248]
Hi Team , 

I am trying to read some fields from CSV and use them in my scenario but facing **No attribute name 'CSVFieldName' is defined** issue Kindly, confirm whether its bug or not ? 

mentioning some details below , 

Gatling Version : bundle-2.2.3 

CSV Name : memId.csv

CSV contents : 
memid
CKABC123

Scala FIle contents : 

//Class Declaration 
{

     //some http configuration 

val memId_feeder = csv("memId.csv").circular                  

val scn = scenario("Scn name").during( 10 seconds ) {
     feed(memId_feeder)
     exec(http("Req_01_Auth")
           .post("/auth")
           .check(status.is(200))
           .headers(header_1)
           .formParam("memberId","${memid}"))
}

setup(scn.inject(atOnceUsers(1)).protocols(httpConf))
}   

Any help or clue to resolve this issue is really appreciable . 

P.S. : There is no whitespaces in inp csv file . 
Erroneous String : "No attribute named 'memid' is defined "

**Comment by slandelle** [comment]
Not a Gatling issue but a user one.
Please use the Gatling community mailing list for such questions.

**Comment by Ritesh-Sharma** [comment]
@slandelle : Hi , I would love to post their but Gatling Google community seems inactive ; somewhat similar question has been asked their earlier but none movement has been seen there for same since more than 6 months...if you know if its user issue then kindly Help !!

**Comment by slandelle** [comment]
> Gatling Google community seems inactive

No, it's not, some great folks like Aidy and Barry do help there. But you can't expect from a community mailing list the kind of fast and accurate answer you'd get from a professional support.

We from GatlingCorp don't answer a lot on the Community Mailing, but we have a [Helpdesk offer](http://gatling.io/#/services) if you want us to help you.
