### ISSUE TITLE
Use EL in URI/path

### ISSUE THREAD

**Issue by kag0** [gatling/gatling#3249]
The ability to dynamically set query parameters is [well documented](http://gatling.io/docs/2.2.3/http/http_request.html#query-parameters), however there doesn't seem to be any way to do the same with path parameters. 

An example use case would be 
```scala
http("Getting issue")
  .get("https://github.com/gatling/gatling/issues/${issueNumber}")
``` 
If there is a way to do this that I'm missing, could it be added to the docs? If not, adding it as a feature would be greatly appreciated.

**Comment by slandelle** [comment]
Hi,

Please don't use the bug tracker for question. Use the community mailing list instead.

Then, regarding your question, the answer is in the doc, you could/should read it all, even the advanced stuff. A shortcut would be to give it a try first :)

**Comment by kag0** [comment]
@slandelle thanks for the quick response. 

I've been whipping through the documentation of lots of tools looking for something that fits my needs, and unfortunately don't have time to try everything out or read as deep into documentation as I'd like. 
Quickly adding an example to the [request url docs](http://gatling.io/docs/2.2.3/http/http_request.html#method-and-url) would be a great way to show at a glance that the functionality is there. What would be the best place to request/suggest that change? Mailing list still?
