### ISSUE TITLE
App: Some error message is dropped at tail of logback log file

### ISSUE THREAD

**Issue by t-takatsuru** [gatling/gatling#3255]
Logback buffer is not flshed on finising simulation.
Some error message is dropped at tail of ``target/logs/test.log``.
(I tested using SBT.)

I think ``loggerContext.stop()`` should be called at the end of run.

**Comment by slandelle** [comment]
Hi @t-takatsuru ,

Thanks for reporting!
Would you have some time to provide a PR? We plan on releasing 2.2.4 this week.

Cheers
