### ISSUE TITLE
Recorder: Content-Type header value is empty in simulation generated from HAR.

### ISSUE THREAD

**Issue by t-takatsuru** [gatling/gatling#3256]
Content-Type header is empty in simulation generated from HAR.

protocol part of ``RecordedSimulation.scala`` is following:
```scala
val httpProtocol = http
    .baseURL("https://xxx.xxx.xxx.xxx")
    .contentTypeHeader("")
```

This simulation produces HTTP request with empty value Content-Type header in every interaction without overriding with ``.header(...)`` method.
It is problem on interpreting request in target web server.

Attachment HAR file to reproduce that.
[sample.har.txt](https://github.com/gatling/gatling/files/823599/sample.har.txt)

**Comment by slandelle** [comment]
Hi again, and thanks again :)

Same question as [here](https://github.com/gatling/gatling/issues/3255#issuecomment-284657628).
