### ISSUE TITLE
Error in Gatling scripts in 'New Alert' requests.

### ISSUE THREAD

**Issue by vvprabakaran** [gatling/gatling#3261]
Error is displayed in Gatling scripts with 'New Alert' requests.

The following error is displayed 

Hi Team,,

We are working with a .NET application performance testing and using Gatling 2.2.4 version to create the scripts. The AUT is a RIA application with AJAX calls getting loaded for each tab movement to save and retrieve the validation rules from server. Each call use to create a POST request which will have response as just "TRUE" or "FALSE" status.

The requests are captured in GATLING recorder script as a POST request. But each time the request is executed it fails abruptly and the proceeding requests produce issues as well. We've verified the preceding workflow for pageload and that is fine. These particular requests alone fails.

The same workflow is scripted and executed successfully in LoadRunner and verified with network sniffer tools which are good.

Can anyone who faced similar issues please help us with some expertise to solve the issue and proceed with scripting?

**Comment by slandelle** [comment]
Hi,

This is a bug tracker, hence for reporting issues and requesting features.
For questions regarding Gatling usage, please use the Community mailing list (you'll find the list on our home page).

**Comment by vvprabakaran** [comment]
Thanks Slandelle.
Since I am new to this community, I have created here.
I am not able to find the community mailing list in the home page. Are you able to help on this?

**Comment by slandelle** [comment]
<img width="927" alt="ml" src="https://cloud.githubusercontent.com/assets/849197/23755508/e29822c6-04e0-11e7-99b6-70bd1b69d6ac.png">
