### ISSUE TITLE
Load scenario aborts immediately on throttling scenario end

### ISSUE THREAD

**Issue by EugeneAbramchuk** [gatling/gatling#3266]
1. Create a test with forever loop (so it does not finish naturally)
2. Limit the scenario max duration at N seconds (so it must end at this time)
3. Set throttling to reachRps/holdFor together at <N seconds.
4. Run the scenario
=> Scenario ends after throttling's reachRps+holdFor expired.

Expected: Scenario runs for max duration (N seconds), throttling works for the set time, then proceeds unthrottled.

See the attached snippet

```
class OnboardingDebug extends BaseScenario {

  override def scenarioBuilder = scenario(getClass.getSimpleName)
    .exitBlockOnFail(exec(prepareAccount))
    .forever(Account.get)

  def prepareAccount =
    Account.create
      .exec(Account.login)
      .exec(Account.activate)

  // 30 seconds together throttled
  override def getThrottling = Seq(reachRps(3) in (10 seconds), holdFor(20 seconds)) 

  override def getRampUpScenario = List(atOnceUsers(2))

  override def getMaxDuration = 40 seconds
}
```

```
---- OnboardingDebug -----------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 2      / done:0     
================================================================================

Simulation ***.OnboardingDebug completed in 30 seconds
Parsing log file(s)...
```

Gatling **2.2.4**

**Comment by slandelle** [comment]
No, that's the expected behavior.
From [documentation](http://gatling.io/docs/2.2/general/simulation_setup/#throttling):

> If your injection lasts less than the throttle, your simulation will simply stop when all the users are done. If your injection lasts longer than the throttle, the simulation will stop at the end of the throttle.
