### ISSUE TITLE
Can we add class name tag in test cases in assertions.xml?

### ISSUE THREAD

**Issue by kamal951** [gatling/gatling#3269]
I want to use the gatling junit report to upload it automatically in Testlink using Hudson but there is no classname tag in the file so I can't link it to a test case. Is there any way to add it?
I want the file looks like this: 
`<testsuite name="Name of test suite" tests="3" errors="0" failures="0" skip="0">
	<testcase classname="MyTestClassName" name="Some name" time="1.691">
		<system-out>
			Some text 
		</system-out>
	</testcase>
	<testcase classname="MyTestClassName2" name="Other name" time="0.080">
		<system-out>
			Some text
		</system-out>
	</testcase>
</testsuite>`

**Comment by slandelle** [comment]
Hi,

This is a bug tracker. For questions, please use the community mailing list.
