### ISSUE TITLE
Doc: Update JSF cookbook to fix CSS selectors

### ISSUE THREAD

**Issue by frol2103** [gatling/gatling#3273]
I try to use gatling with jsf.

I use gatling 2.2.2.
I did what was explained in http://gatling.io/docs/2.2/cookbook/handling_jsf/ but i got an exception : 

> jodd.csselly.CSSellyException: Illegal character <.>. (state: 4)
> 	at jodd.csselly.CSSellyLexer.yylex(CSSellyLexer.java:781)
> 	at jodd.csselly.CSSelly.parse(CSSelly.java:61)
> 	at jodd.csselly.CSSelly.parse(CSSelly.java:96)
> 	at io.gatling.core.check.extractor.css.CssSelectors.io$gatling$core$check$extractor$css$CssSelectors$$$anonfun$1(CssSelectors.scala:35)
> 	at io.gatling.core.check.extractor.css.CssSelectors$lambda$1.apply(CssSelectors.scala:35)
> 	at io.gatling.core.check.extractor.css.CssSelectors$lambda$1.apply(CssSelectors.scala:35)
> 	at io.gatling.core.util.cache.SelfLoadingThreadSafeCache.io$gatling$core$util$cache$SelfLoadingThreadSafeCache$$$anonfun$1(SelfLoadingThreadSafeCache.scala:29)
> 	at io.gatling.core.util.cache.SelfLoadingThreadSafeCache$lambda$$get$1.apply(SelfLoadingThreadSafeCache.scala:29)
> 	at io.gatling.core.util.cache.ThreadSafeCache.getOrElsePutIfAbsent(ThreadSafeCache.scala:44)
> 	at io.gatling.core.util.cache.SelfLoadingThreadSafeCache.get(SelfLoadingThreadSafeCache.scala:29)
> 	at io.gatling.core.check.extractor.css.CssSelectors.extractAll(CssSelectors.scala:44)
> 	at io.gatling.core.check.extractor.css.CssExtractorFactory$$anon$2.extract(CssExtractorFactory.scala:27)
> 	at io.gatling.core.check.extractor.css.CssExtractorFactory$$anon$2.extract(CssExtractorFactory.scala:24)
> 	at io.gatling.core.check.extractor.CriterionExtractorFactory$$anon$1.extract(CriterionExtractorFactory.scala:43)
> 	at io.gatling.core.check.extractor.CriterionExtractor.apply(Extractor.scala:33)
> 	at io.gatling.core.check.CheckBase.io$gatling$core$check$CheckBase$$$anonfun$7(Check.scala:86)
> 	at io.gatling.core.check.CheckBase$lambda$$$nestedInAnonfun$5$2.apply(Check.scala:85)
> 	at io.gatling.core.check.CheckBase$lambda$$$nestedInAnonfun$5$2.apply(Check.scala:85)
> 	at io.gatling.commons.validation.Success.flatMap(Validation.scala:33)
> 	at io.gatling.core.check.CheckBase.io$gatling$core$check$CheckBase$$$anonfun$5(Check.scala:85)
> 	at io.gatling.core.check.CheckBase$lambda$$io$gatling$core$check$CheckBase$$$nestedInAnonfun$3$2.apply(Check.scala:84)
> 	at io.gatling.core.check.CheckBase$lambda$$io$gatling$core$check$CheckBase$$$nestedInAnonfun$3$2.apply(Check.scala:84)
> 	at io.gatling.commons.validation.Success.flatMap(Validation.scala:33)
> 	at io.gatling.core.check.CheckBase.io$gatling$core$check$CheckBase$$$anonfun$3(Check.scala:84)
> 	at io.gatling.core.check.CheckBase$lambda$$check$2.apply(Check.scala:83)
> 	at io.gatling.core.check.CheckBase$lambda$$check$2.apply(Check.scala:83)
> 	at io.gatling.commons.validation.Success.flatMap(Validation.scala:33)
> 	at io.gatling.core.check.CheckBase.check(Check.scala:83)
> 	at io.gatling.http.check.HttpCheck.check(HttpCheck.scala:35)
> 	at io.gatling.http.check.HttpCheck.check(HttpCheck.scala:32)
> 	at io.gatling.core.check.Check$.checkRec$1(Check.scala:37)
> 	at io.gatling.core.check.Check$.check(Check.scala:60)
> 	at io.gatling.http.ahc.ResponseProcessor.checkAndProceed$1(ResponseProcessor.scala:281)
> 	at io.gatling.http.ahc.ResponseProcessor.processResponse(ResponseProcessor.scala:322)
> 	at io.gatling.http.ahc.ResponseProcessor.onCompleted(ResponseProcessor.scala:61)
> 	at io.gatling.http.ahc.AsyncHandler.io$gatling$http$ahc$AsyncHandler$$$anonfun$1(AsyncHandler.scala:133)
> 	at io.gatling.http.ahc.AsyncHandler$lambda$$onCompleted$1.apply(AsyncHandler.scala:131)
> 	at io.gatling.http.ahc.AsyncHandler$lambda$$onCompleted$1.apply(AsyncHandler.scala:131)
> 	at io.gatling.http.ahc.AsyncHandler.withResponse(AsyncHandler.scala:124)
> 	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:131)
> 	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:47)
> 	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
> 	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
> 	at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
> 	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
> 	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
> 	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
> 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
> 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
> 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
> 	at java.lang.Thread.run(Thread.java:745)
> 

I fixed this by replacing the css selector from : `css("input[name=javax.faces.ViewState]", "value")`  
 to `css("input[name=javax\\.faces\\.ViewState]", "value")`

I will shortly post a pull request to fix the documentation

**Comment by slandelle** [comment]
Thanks!
