### ISSUE TITLE
Remove scroll takeover on gatling.io

### ISSUE THREAD

**Issue by robzienert** [gatling/gatling#3276]
There were no issues on the gatling.io repo, so I'm posting this here - sorry.

Trying to navigate the documentation with scroll-hijacking is super frustrating. It'd be dramatically better if the native scroll behavior was used instead.

**Comment by slandelle** [comment]
Hi @robzienert 

> There were no issues on the gatling.io repo, so I'm posting this here - sorry.

Yep, we no longer use it, I'll drop it.

> Trying to navigate the documentation with scroll-hijacking is super frustrating.

Could you please give us an example/more information? Maybe it's browser dependent. On our side, the scroll-hijacking is very light.

**Comment by slandelle** [comment]
We have never been able to figure out why the scroll takeover caused issues for some users. Maybe browser plugins... Anyway, we've removed it.
