### ISSUE TITLE
Generate report in preconfigured location

### ISSUE THREAD

**Issue by pwielgolaski** [gatling/gatling#3280]
I use gatling with Teamcity and would like to give consider path where simulation report should be.
Like using feature https://confluence.jetbrains.com/display/TCD10/Including+Third-Party+Reports+in+the+Build+Results
Gatling generate new folder every run with Scenario name and timestamp.
Could we make it configurable?

It seems that change could be relatively easy achieved here https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/config/GatlingFiles.scala#L41

I could contribute the change .

**Comment by slandelle** [comment]
Hi @pwielgolaski 

Sorry, but I'm not fond of this one. This might risk breaking or not being compatible with the current behavior, maybe break the Jenkins plugin. There's maybe a way to resolve the location programmatically, just like we do in the Jenkins plugin.

Then, integration with other tools fall into the FrontLine scope. And FrontLine already have a Teamcity plugin (easier, as FrontLine provides REST APIs, not files on the filesystem).

**Comment by pwielgolaski** [comment]
I still would like to ask you for giving possibility to change it by user.
I.e. we could add some configuration property that could define runId.
https://github.com/gatling/gatling/blob/b182da6648e57d05c7c3900cf42fc5ee10631f6d/gatling-app/src/main/scala/io/gatling/app/Runner.scala#L87
To implement it on my own, I would need to hack with Gatling runner.
