### ISSUE TITLE
Not using Scala version convention and not documenting it properly

### ISSUE THREAD

**Issue by MateuszKubuszok** [gatling/gatling#3282]
Gatling is not indicating directly it's dependencies nor the fact that it is build using Scala 2.11.

This appeared to be a problem when I added Gatling as a dependency to Scala 2.12 project using Akka HTTP, and added to SBT:

```
val gatlingVersion  = "2.2.4"
libraryDependencies += "io.gatling.highcharts" %  "gatling-charts-highcharts" % gatlingVersion  % "test"
libraryDependencies += "io.gatling"            %  "gatling-test-framework"    % gatlingVersion  % "test"
```
build failed with `Modules were resolved with conflicting cross-version suffixes in` and several libraries listed (e.g. akka-actor).

It appears that error was that gatling is actually a Scala library, that  do not follow Scala conventions (having `_2.11` in module name) and as a result when I used it with Scala 2.12 project there was a conflict that made build fail.

Since it is at least reproducible for anyone that use e.g. SBT with Scala version 2.12 and newest Akka HTTP and adds Gatling as its test dependency, it should be properly documented. I wasted 2h for figuring out, that a library, which signature suggests, that is Java-like (do not require `%%` instead of `%`, since there is no `_2.11` in its name), while it fails with newest version of Scala.

**Comment by slandelle** [comment]
Hi.

First, regarding the artifact naming scheme, AFAIK, the Scala community is a minority amongst our users, and the Scala standard naming scheme is a lost cause on most non-Scala users. As we have no plans on cross publishing atm, we plan on sticking to the current scheme for now.

Then, regarding documenting the versions in order to notifying of conflicts, build tools do a way more better job than any documentation, all the more as tons of libraries could be conflicting (Scala, Akka, AsyncHttpClient for Play! users, etc). In the sbt world, use the [sbt-dependency-graph plugin](https://github.com/jrudolph/sbt-dependency-graph).

Gatling 3 (wip in master) targets Scala 2.12. Anyway, instead of trying to have a monolithic project, you'd probably better isolate your Gatling test in a separated project/module with a different classpath.

**Comment by MateuszKubuszok** [comment]
I am not sure if we are talking about the same thing, so I will only describe the exact problem I encountered.

Build tools did not help much. Once I upgraded from 2.11 to 2.12, I started having conflicting versions - in such case SBT gives up before `sbt dependencyGraph` shows any output and so the plugin is useless. In fact I used the `sbt-dependency-graph plugin` plugin for listing dpendencies when I removed half the dependencies and message dissapeard. `sbt dependencyGraph` didn't show Gatling at all and `sbt dependencyGraph --force` worked so long, that I terminated the task. The only way of figuring out, which library caused conflict was commenting out libraries one by one and running `reload` and `update`.

In such case one would first look at `%%` libraries, as they are clearly Scala libraries and Scala libraries are the only one that could produce `cross version conflict` error. Except they shouldn't, as libraries using `%%` convention use the same version of Scala as the project, which guarantees, that they will never be the source of conflict.

f libraries I use follow `module_2.11` and `module_2.12`, then by using `%%` I will never have such conflict. So Scala, Akka, AsyncHttpClient for Play! users, etc will never be the source of such conflict. From all other libraries (single `%`) one can expect, that they will not be dependent on Scala version. Since it was nowhere documented I wasted 2 hours for figuring out the reason, and I expect that other people, when they migrate from Scala 2.11 to 2.12, might be surprised to see such error, especially coming from library that looks like a pure Java library. I just wanted to spare them the trouble.

**Comment by slandelle** [comment]
> sbt dependencyGraph didn't show Gatling at all

`sbt dependencyGraph` shows the `compile` deps graph. As you probably have Gatling with `test` scope, you want the `test` deps graph, hence `sbt test:dependencyGraph`.

> especially coming from library that looks like a pure Java library

Gatling has Scala all over the place. Even the simulations can only be written in Scala.
