### ISSUE TITLE
Push tags to github

### ISSUE THREAD

**Issue by cbornet** [gatling/gatling#3288]
Hi,

The latest version available for download seems to be 2.2.5 but the latest tag on github is 2.2.0.
Could you push the missing tags to github ? It's very useful to know what is inside a given version.

**Comment by slandelle** [comment]
Sorry, but no, we don't plan to, for many reasons:
* Github turns git tags into something they call "releases", that are actually only a source download. This might makes sense for scripting languages, but definitively not for a compiled one such as Scala. Because of Github abuse of the "release" word, people used to download this crap and then complain and open issues because they didn't get what they expected...
* We used to use the `sbt-release` plugin, which would automatically create tags, but this plugin made our life a misery and broke several releases so we dropped it.
* You can get the release content from the milestone
* Tags would mostly be useful for unfriendly forks

**Comment by slandelle** [comment]
Then, of course, if you have some valid pros that would balance all those cons, please state them.

**Comment by cbornet** [comment]
Thanks for your reply. That's the first time I hear complaints about gh tags so it's interesting to hear some. I have some remark to your points (taking my chance to make you change your mind 😄 )

> Github turns git tags into something they call "releases", that are actually only a source download. This might makes sense for scripting languages, but definitively not for a compiled one such as Scala. Because of Github abuse of the "release" word, people used to download this crap and then complain and open issues because they didn't get what they expected...

I believe people get into the confusion because your delivery is a zip archive just as github sources. You wouldn't have the problem if you delivered a mere jar lib I guess. That said you could pull a true gh release (not just a tag) when you make one and you can attach some resources to that release (eg. the built zip). Example of release on a gh project : https://github.com/springfox/springfox/releases/tag/2.6.1 Downloads here are clearly marked as source code and you could also easily add built artifacts

>    We used to use the sbt-release plugin, which would automatically create tags, but this plugin made our life a misery and broke several releases so we dropped it.

Not saying you should do it automated. I have always prefered manual tagging

>    You can get the release content from the milestone

For PR and issues but not for individual commits.
Eg.: I want a version that embeds https://github.com/gatling/gatling/commit/1307add32901d92a50313ee161d2c06c45cc5123 but I can't know which one has it

>    Tags would mostly be useful for unfriendly forks

Can you truely fight against unfriendly forks...

**Comment by slandelle** [comment]
> That said you could pull a true gh release (not just a tag) when you make one and you can attach some resources to that release (eg. the built zip)

Something we'll never do. We don't want things to be scattered all over the place: downloads are from Sonatype, where we have download anaytics, and release descriptions are currently on our mailing list but will move on our website.

> Eg.: I want a version that embeds 1307add but I can't know which one has it

Wouldn't help you, as this one isn't shipped in a public release yet.

> Can you truly fight against unfriendly forks...

No, but we can still refuse to add more work for us that would only help those.

**Comment by cbornet** [comment]
> > Eg.: I want a version that embeds 1307add but I can't know which one has it

> Wouldn't help you, as this one isn't shipped in a public release yet.

Yes, but I had to download v2.2.5 to figure that out. Not very nice...

**Comment by cbornet** [comment]
>> That said you could pull a true gh release (not just a tag) when you make one and you can attach some resources to that release (eg. the built zip)

> Something we'll never do. We don't want things to be scattered all over the place: downloads are from Sonatype, where we have download anaytics, and release descriptions are currently on our mailing list but will move on our website.

Don't want to argue to long. You probably have your reasons to do so. I proposed to pull true gh releases because you were concerned about the source zip link attached to simple tags which is confused with the deliverable. If you just make a release of the tag, it will become a `Source code` link which is no more ambivalent. Then you could just add a link to your website release note (or not).
