### ISSUE TITLE
Core: slf4j bindings target slf4j-api version prior to 1.8

### ISSUE THREAD

**Issue by johnsonexosite** [gatling/gatling#3290]
Environment: Ubuntu Server 14.04 & macOS Sierra
Run the BasicSimulation from command and you would get these slf4j warnings and exception log.

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/home/johnsonchuang/gatling/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

And you would always get exception output when simulation ends:

```
Exception in thread "main" java.lang.ClassCastException: org.slf4j.helpers.NOPLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
	at io.gatling.app.Gatling$.start(Gatling.scala:66)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:43)
	at io.gatling.app.Gatling$.main(Gatling.scala:35)
	at io.gatling.app.Gatling.main(Gatling.scala)
```

But if change slf4j-api jar's version from 1.8.0-alpha1 to 1.7.25 in $GATLING_HOME/lib, then these warnings and exception are gone.

**Comment by slandelle** [comment]
Yes, we've noticed this.

Full story:

- Boon declares a floating version for its slf4j-api dependency (KMN)
- We explicitly say we depend on a fixed version (would be 1.7.22 for Gatling 2.2.5), hence closer from the root in the dependency graph
- sbt and sbt-dependency-graph properly resolve the dependency graph and use slf4j-api 1.7
- sbt-native-packager, used to generate the bundle, messes up and resolves 1.8.0-alpha1
- slf4j-api 1.8.0-alpha1 is broken

We've republished the bundle, please download a fresh copy.
