### ISSUE TITLE
Send "Requests per Second" to Graphite (in addition to Responses per Second)?

### ISSUE THREAD

**Issue by geekdave** [gatling/gatling#3292]
Currently it appears that the Graphite writer outputs only **Responses** per-second, which I can query as:

```
SELECT "count" FROM "gatling" WHERE "request" = 'allRequests' AND "status" = 'all' AND $timeFilter
```

However there appears to be no metric for **Requests** per-second in Graphite results.  

I'm trying to model an Open Simulation where the users arrive at a constant rate, and the Requests-per-second remain constant, regardless of the system under test's ability to respond.  So I'm intentionally trying to show how Requests & Responses per-second will diverge over time.

Using the html report outputted by Gatling I can see this difference.  Just looking to be able to do the same in my Graphite/Grafana visualization.  

![gatling_stats_-_global_information](https://cloud.githubusercontent.com/assets/1438478/25539901/64ac045c-2c06-11e7-933f-abe63ab3f765.png)

Thanks for all you do on this project!

**Comment by slandelle** [comment]
Hi @geekdave 

Thanks for your kind words.

Then, I'm sorry, but we don't plan to add more feature/metrics to the Graphite integration.
Generally speaking, all new features related to metrics, reporting and third party integration go into FrontLine, which is our way of making a living. And indeed, you get the real time requests sent per second metrics in there.

<img width="684" alt="rps" src="https://cloud.githubusercontent.com/assets/849197/25543468/f210b888-2c56-11e7-87a5-1cefbc8bf897.png">

Cheers

**Comment by geekdave** [comment]
@slandelle I totally understand.  Would you accept a PR to add this integration?  I understand this is a tricky area where open source and business needs can conflict.

**Comment by slandelle** [comment]
I'm sorry again. We really love contributions, but I'll have to turn this one down
We'll run into dramas if we sometimes make exceptions to our scope rules ("why did you accept this contrib and reject mine?!") so we've decided to stick to the line we've drawn between OSS and FrontLine:

* improvements on engine, HTTP and JMS protocol support (and maybe other ones that could be contributed in the future) will go in OSS
* improvements in third party integrations and metric and reporting will go in FrontLine
