### ISSUE TITLE
Conflicting dependencies in gatling

### ISSUE THREAD

**Issue by kuipercm** [gatling/gatling#3293]
Hi,

I'm setting up a new project using Gatling in a maven context. When I look at the dependency graph in Intellij IDEA, I see a number of dependency conflicts. Obviously I can suppress those by forcing a single version, but I was wondering if this can be fixed within Gatling itself? That would avoid a lot of work when I want to upgrade to a new version. (Because in that case I would have to run through all the dependencies again and see where the conflicts are.)

Any thoughts?
I've attached the diagram I see. The red lines indicate conflicts. 

To reproduce: simple create a new project in Intellij, add Gatling as a dependency and open the dependency graph.

![2017-05-03_gatling_dependency_diagram](https://cloud.githubusercontent.com/assets/10634482/25661699/e93b0b64-3011-11e7-9856-b825b5634948.png)

**Comment by slandelle** [comment]
Hi.
Could you elaborate on your real issue, please?
Do you get non-compatible dependencies versions (such as Netty modules in different versions) in the resolved dependency tree?

**Comment by kuipercm** [comment]
Well, during a build I get flagged on the fact that there are different dependency versions in my configuration. This breaks the build for the reason that having multiple versions can lead to undefined execution results (first on the classpath wins).

So I have to enforce a single version. This is done at runtime anyway as described above, but I would rather not do so and therefore my question is whether this can be solved within Gatling.

**Comment by slandelle** [comment]
> This breaks the build

Maven builds don't break for such reason by default.

> for the reason that having multiple versions can lead to undefined execution results (first on the classpath wins)

No, that's not how maven works. Maven has (sometimes arguable) rules for resolving conflicts in the dependency tree, such as the closest to the root wins. But in the end, maven generates a classpath with unique versions of each dependency, there are absolutely no duplicated libs.

I suspect the actual story is that you're enforcing [very drastic rules with maven-enforcer-plugin](http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html).
If that's the case, trying to comply with such rules while there is actually no runtime issue is not something we'll work on ourselves.
Then, feel free to provide a pull request. But note that we'll only accept one that wouldn't turn our build files into a huge ugly pile of exclusions.

Closing for now. Feel free to ping if you've found a version conflict that breaks Gatling at runtime.

Regards
