### ISSUE TITLE
Core: Json.Stringify does not escape double quotes

### ISSUE THREAD

**Issue by jozemlakar** [gatling/gatling#3296]
io.gatling.core.json.Json.stringify method stringifies objects as JSON strings. This generally works fine, but not when a string value has double quotes. This would seem safe generally, but not when a whole JSON is stringified. Imagine this case:

```
val mapOriginalValue = Map[String,Any]("key1" -> "Regular foo", "key2" -> "Quoted \"foo\"");
val stringifiedMap = stringify(mapOriginalValue);
println("Stringified JSON: " + stringifiedMap);
```

expected output would be 
`Stringified JSON: {"key1":"Regular foo","key2":"Quoted \"foo\""}`
instead the result is
`Stringified JSON: {"key1":"Regular foo","key2":"Quoted "foo""}`

This is not valid JSON. 
I have tried to find where the problem is. In file [Json.scala](https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/json/Json.scala) line 48, escaping is implemented for line feeds but not double quotes. 

Adding escaping for double quotes is easy and I can prepare a PR, but this might break existing code, depending on this "feature". You can recommend the proper solution and I can implement it. 

```
val originalValue = "Quoted \"foo\"";
val expectedValue = "Quoted \\\"foo\\\"";
val stringified = stringify(originalValue);
if (stringified == expectedValue) {
	println("Stringified works properly")
} else {
	println("Stringify is not working properly")					
}
```

results in `Stringify is not working properly`

**Comment by slandelle** [comment]
Thanks for reporting!
Are you interested in contributing a fix?

**Comment by jozemlakar** [comment]
yes. I am testing a fix right now, but I am not sure if maybe someone somewhere is using this code in a wrong way and the fix will break their code

**Comment by jozemlakar** [comment]
Added PR https://github.com/gatling/gatling/pull/3297 to fix this

**Comment by jozemlakar** [comment]
Replaced with PR #3298
