### ISSUE TITLE
Commas in group hierarchy names are not escaped

### ISSUE THREAD

**Issue by jpcooper** [gatling/gatling#3305]
Consider a scenario named `"A,B"` where at some point an http request happens named `"C,D"`. `LogFileDataWriter.serializeGroups` will intersperse commas without escaping or handling otherwise the group hierarchy names. This leads to an error on parsing of the log and using it to generate the report, as `charts.stats.GroupRecordParser.parseGroup` simply splits by comma.

I would be happy to submit a pull request which fixes this if you think it would be useful.

**Comment by jpcooper** [comment]
On that note, `\t` would also break things.

**Comment by slandelle** [comment]
We explicitly state in the documentation that [group names mustn't contains commas](http://gatling.io/docs/current/general/scenario/#groups-definition). I agree this would deserve a WARNING layout though :)

Parsing group names to escape commas would bring a non neglectable overhead at high throughput as they can be dynamically generated, so that's an option we've rejected.

**Comment by slandelle** [comment]
Then, thanks for offering your help! Hopefully next time :)

**Comment by jpcooper** [comment]
@slandelle I'm not convinced that this would add an overhead at all. Have you made any tests to verify this? You are already using a regex replacement to replace `[\n\r\t]` with ` `, which allocates a whole new extra string for every message, even if those characters are not present. This is completely avoidable. You are then including this string in another `Fastring`.

All you would need to do this efficiently is have a growable character buffer to build up your line, regardless of whether you decide to escape commas or not.

There should definitely be a warning, if not an exception thrown, if you do decide not to escape commas.

**Comment by slandelle** [comment]
done as of https://github.com/gatling/gatling/commit/5449a5381c3d4d65ddbe4df59c73381c0c92621c#diff-615b549cde8a529dc4ba6026d46e9a09R125
