### ISSUE TITLE
Recorder : Custom SSL Certificate cause Timeout

### ISSUE THREAD

**Issue by izakiel** [gatling/gatling#3306]
Hi, 
I think there is a problem with SSL certificates generated by the recorder when we try to access a host.

Since Firefox 48 and Chrome 58 all certificate without alternative name are considered as invalid.
To bypass the problem i've generated my own CA and key and set it in Gatling Recorder.

My certificate is completely valid and contain all DNS I need.

When i set the recorder as proxy and try to access a website i'm kicked out because the object certificate generated from my CA does not contain the altrnative name.
I think this is not a normal behaviour, the extensions should be copied in all sub certificate.

![2017-05-25 04_37_35-erreur liee a la confidentialite](https://cloud.githubusercontent.com/assets/17925064/26433742/ce094596-4104-11e7-8903-b48966d9d98a.png)

My rootCA provide good extensions with my DNS
![2017-05-25 04_43_24-erreur liee a la confidentialite](https://cloud.githubusercontent.com/assets/17925064/26433774/e8d630a0-4104-11e7-95fa-7a4822b0ead9.png)

The object certificate (google.fr in the screenshot) does not contain extension and is considered as invalid.
![2017-05-25 04_44_18-erreur liee a la confidentialite](https://cloud.githubusercontent.com/assets/17925064/26433803/0dcc60c8-4105-11e7-805b-9577211123d1.png)

Maybe a team member could confirm if it's a bug or an attended behaviour ?

Today it's a blocking issue for me, as i need to tests some SSL only websites and if there is no Alt names in certificate browsers just eject us today.

Regards.

**Comment by slandelle** [comment]
I have no problem recording https://google.fr on my side with FireFox 53.

<img width="1361" alt="https-recording" src="https://cloud.githubusercontent.com/assets/849197/26443276/f1a3d6fa-4137-11e7-9349-062b55eeb13c.png">

**Comment by slandelle** [comment]
@izakiel Do you have an exact procedure that would let us reproduce your problem, please?

**Comment by izakiel** [comment]
@slandelle I'm on it, i am trying to make it work on firefox before just to be sure i am not boring you with a mistake from my part. Today I will post a detailed plan of what i do from the creation of the certificate to the gatling recorder config.

**Comment by slandelle** [comment]
Great.

> what i do from the creation of the certificate

Can't you use the Recorder CA generation feature?

**Comment by izakiel** [comment]
I've tried to generate the certificate directly from the Recorder.
And i can't hit google.fr.

Generate certificate with Recorder
![2017-05-26 15_44_45-](https://cloud.githubusercontent.com/assets/17925064/26497400/aa55a392-422b-11e7-96c3-99eb78584920.png)

Set the proxy in Firefox 53.0.3
![2017-05-26 15_50_36-options](https://cloud.githubusercontent.com/assets/17925064/26497425/c2dad720-422b-11e7-879e-c6adcbd05015.png)

Unsecure connexion on google.fr
![2017-05-26 15_51_11-connexion non securisee](https://cloud.githubusercontent.com/assets/17925064/26497432/c8d2e8b6-422b-11e7-8545-b88bfa0eb0aa.png)

Set the proxy on chrome 58.0.3029.110
And same thing because the Alternative Names are missing in the certificate.
![2017-05-26 15_52_01-erreur liee a la confidentialite](https://cloud.githubusercontent.com/assets/17925064/26497484/024cab36-422c-11e7-91c3-d4b67b41a069.png)

By digging on the Internet i've found that it's a new feature for Chrome v58 but that was already implemented in Firefox since v48. 
Missing Alternative Name is why the browsers are thinking Gatling Recorder Proxy is not a trusted source.
After that i tried to generate my own CA including Alternative Names like "localhost" using Openssl.

**Comment by slandelle** [comment]
Actually, it seems things work as expected with Gatling master, but not with Gatling 2.2.
Recorder has gone under some major refactoring, so it's possible we've improved things in there without noticing.
I really don't have time to investigate which commit might have fixed it, and if it's possible to backport. Help welcome :)

**Comment by izakiel** [comment]
Ok, i will use HAR convertion feature while the next release is under development.
But i will try to cloning master, build it and check how this feature works :)

**Comment by slandelle** [comment]
Actually, I had no problem recording https://www.google.fr/ with 2.2.5.

Closing for now.
