### ISSUE TITLE
HTTP: web-drivers (include remotewebdriver) support

### ISSUE THREAD

**Issue by nex0ma** [gatling/gatling#3307]

**Comment by nex0ma** [comment]
we  need worked, well documented template for any protocol.
all old articles about Gatling new protocol creation not worked.

**Comment by slandelle** [comment]
We're not ready to provide a stable API for everyone to implement his own protocol support.
If you're in a need of a custom protocol and don't feel like digging yourself in the code, you can contract with us so we develop it for you.

**Comment by slandelle** [comment]
Idle for too long. Will reopen if there's some activity.
