### ISSUE TITLE
"\" in request names are not escaped

### ISSUE THREAD

**Issue by sunbeltdn** [gatling/gatling#3314]
**Problem Desc**
![img_3702](https://cloud.githubusercontent.com/assets/19320354/26771933/e1590b88-49f4-11e7-8652-12c93928bd7d.jpg)

Above is the scripts which makes the report can't display correctly. Which is to get resource that the path including "/u" that highlight with red box.

but after the testing is done, will show a blank page for report as below and err msg as below:
![img_3703](https://cloud.githubusercontent.com/assets/19320354/26772114/263e8768-49f6-11e7-979e-642afcbe0be9.jpg)
![img_3704](https://cloud.githubusercontent.com/assets/19320354/26772121/2f9b1448-49f6-11e7-94ec-8891cf0167cd.jpg)

When check the details, found below that shows different place replace "/" differently, so it makes the report problem:
![img_3705](https://cloud.githubusercontent.com/assets/19320354/26772126/377c682e-49f6-11e7-882f-5a0a0bca6501.jpg)

**Comment by slandelle** [comment]
I haven't been able to reproduce so far.
Which version do you use?
Can you please provide an actionable reproducer?

**Comment by slandelle** [comment]
@sunbeltdn gentle ping

**Comment by sunbeltdn** [comment]
@slandelle I'm afraid that I missed the msg, let me try it on the latest version again, and I will response in the thread, thanks!

**Comment by sunbeltdn** [comment]
[gatling script](https://www.jianguoyun.com/p/DQmIpWcQnOsDGLbYLg)
[error report](https://www.jianguoyun.com/p/DehMVq8QnOsDGLjYLg)

In error report, it seems to be the stats.js line 2738 makes the problem.

Please help to take a look on it? Thanks!

**Comment by slandelle** [comment]
The issue is actually different from what you described.
You use "inferHtmlResources" and some of those urls contain backslashes (`\`) and Gatling report module wasn't properly escaping them.

**Comment by slandelle** [comment]
Thanks for reporting!

**Comment by sunbeltdn** [comment]
Thanks!
