### ISSUE TITLE
Feature Request: Add support for extending the graphite schema with extra tags or metics

### ISSUE THREAD

**Issue by KrauseStefan** [gatling/gatling#3315]
The current graphite `GraphiteDataWriter` does not support adding custom metrics to the schema.
In our setup we use both rest services and a websocket.
Websockets are used to push updates to clients, the updates that we push is a json structure with the updates bulked together.

I can get the number of bulk updates sent through the websocket, but I have no way pushing the actual number of updates contained within the updates.

Also for filtering purposes it would be great if it was possible to add a custom tag to every run made with gatling, this tag could be the git hash of both the build and the test configuration that was used to run the test.

It seems there is some support for `extraInfo` but this is only ever used by the `LogFileDataWriter`...

Adding support for custom metrics and custom tags will of course require a bit of configuration, but would also bring a lot of power to the `GraphiteDataWriter`, that already seems to be present in the `LogFileDataWriter`.

An other approach would be to open up for implementing a custom DataWriter, but as far as I can tell there is no way to load this into the system, since the datawriter must be defined in the configuration file and be defined in `DataWriterType.AllTypes` array.

Is any of this something you would be interested in?

**Comment by slandelle** [comment]
Hi,

I'm sorry, but new metrics, reporting features and integrations fall outside of our open core. So I don't think what you're asking for will happen in Gatling OSS.
FrontLine already has some features that would match what you're looking for. Feel free to reach out if you're interested.

Regards

**Comment by KrauseStefan** [comment]
Okay just to be clear, you're not looking for making gatling extensible with custom data writers (from a separate jar) either?

I might have misunderstood the Frontline Product from what I can read you provide an online platform for data collection and analysis, as well an easy way to run the tests from the cloud.

Having anything in the cloud is unfortunately not an option, must work on a local setup.

Is there a feature list for Frontline other than http://gatling.io/gatling-frontline/

**Comment by slandelle** [comment]
> Okay just to be clear, you're not looking for making gatling extensible with custom data writers (from a separate jar) either?

No, sorry. I hope you'll understand that we need to be able to make a living too :)

> Having anything in the cloud is unfortunately not an option, must work on a local setup.

No. FrontLine is currently only available on premises. Deploying injectors on the cloud is only an option, you can deploy them on your own on-premises hosts too.

> Is there a feature list for Frontline other than http://gatling.io/gatling-frontline/

Not atm. We love doing demos and chatting with our users so we get a better understanding of their needs. Note you can [book one online](http://gatling.io/gatling-frontline/demo/).

**Comment by KrauseStefan** [comment]
Okay, that was the information I needed
