### ISSUE TITLE
HTTP: Infinite waiting loop when sending text by new Websocket API without check assigned 

### ISSUE THREAD

**Issue by Sejten** [gatling/gatling#3316]
Im using newest gatling version  3.0.0-SNAPSHOT from repository. When I use sendText method of new Websocket API without check assigned, simulation gets into infinite waiting loop. 
E.g.
```
.exec(ws2("Connect WS").connect("/?encoding=text")        
.exec(ws2("Foo")
          .sendText("bar")
//          .wait(30 seconds)(
//            ws2.checkTextMessage("checkName").check(regex(".*").is("bar")))
       )
```
this step works fine with check attached, but with commented out check test falls into infinite wait loop.
[Full simulation file](https://gist.github.com/Sejten/e85ae6c8a796a72eadbd728002103bc1)

**Comment by slandelle** [comment]
Thanks for reporting!
