### ISSUE TITLE
Feature request: bodys of failed requests in Gatling Report 

### ISSUE THREAD

**Issue by yeryomenkom** [gatling/gatling#3317]
I think it would be nice to have detailed information about requests with failed assetions in report.
Generaly, first what I do, when see failed assertions, I go and watch failed requests body, parameters and so on.

**Comment by slandelle** [comment]
Hi,

This feature is planned for Gatling FrontLine, not for Gatling OSS.

Regards,

**Comment by yeryomenkom** [comment]
Thank you for quick reply.
Is this feature already done? Or when your planned to do this?

**Comment by slandelle** [comment]
No, it's not there yet. I expect we'll have it within a few months as it's been requested by several customers.
