### ISSUE TITLE
JDBC: jdbcFeeder doesn't follow others feeder guidelines imports

### ISSUE THREAD

**Issue by matheusmessora** [gatling/gatling#3322]
I was unable to follow the Feeder tutorial for the **jdbcFeeder**. I need to import it from `jdbc.Predef.` and this is not in the documentation. All other feeders are imported as expected, because all of them are importers from the FeederSupport trait from the core module.

I think this feeder should be inside _trait FeederSupport_ so it could be used as all others feeders.

```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._


object ClientsScenarios {
val clientsFeeder = io.gatling.jdbc.Predef.jdbcFeeder("xxx", "a", "a", "sql").circular // This compile as expected
  val clientsFeederJdbc = jdbcFeeder("xxx", "a", "a", "sql").circular // This doesn't compile
  val clientsFeedCSVr = csv("").circular // This compile as expected

  val get = feed(clientsFeederJdbc)
    .exec(http("get")
      .get("""/clients/${ID}/plans""")
    )
}
```

**Comment by slandelle** [comment]
> I need to import it from jdbc.Predef. and this is not in the documentation.

Agree, this is worth mentioning, even though the recorder generates this import for you.

> I think this feeder should be inside trait FeederSupport

No. `FeederSupport` is in core module, while the JDBC feeder sit in the JDBC module. With Jigsaw, it's possible that we could be running some day without JDBC installed, so I'd rather keep this isolated.
