### ISSUE TITLE
simulation.log does not contain status codes and status message

### ISSUE THREAD

**Issue by bhattchaitanya** [gatling/gatling#3327]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [ ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [ ] Check that you can reproduce your issue with latest Gatling version
  * [ ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [ ] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [ ] Explain your use case, not the implementation you have in mind.

**Comment by bhattchaitanya** [comment]
While looking at the report I don't easily get a summary of status codes and status messages grouped by transaction keys. 
This is a very crucial data which helps us understand why a particular transaction failed and what was the reason for the failure.

The alternative is to use logback trace/debug option which is not feasible when we run large amount of load and when there are large number of failures as the disc quickly fills up or we have to set a logback file limit which again limits us from capturing errors that happen throughout the test.

**Comment by slandelle** [comment]
This is planned for FrontLine, not for Gatling OSS.
