### ISSUE TITLE
gatling-maven-plugin logs a config ERROR when using Gatling 2.2.5 that pulls logback 1.1

### ISSUE THREAD

**Issue by peter-janssen** [gatling/gatling#3334]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [x] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [x] Check that you can reproduce your issue with latest Gatling version
  * [x] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [x] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [ ] Explain your use case, not the implementation you have in mind.

A change in the logback.xml of the gatling-maven-plugin concerning the immediateFlush property introduces an incompatibility with the latest version of gatling. This change is needed to make the logback configuration compliant with version 1.2.0 and higher. Unfortunately the latest stable release of gatling (2.2.5) still uses 1.1.7. The consequence is that an error is thrown by logback during execution. This is also present in the plugin demo. The issue is not present in 3.0.0-SNAPSHOT. This is validate by changing the version in the demo.

Either the logback.xml of the 2.2.x releases of the maven plugin should adhere to the pre 1.2.0 configuration of logback. Or the upgrade of logback that has already been been done for version 3.0.0 of gatling should be backported to 2.2.x.

**Comment by slandelle** [comment]
Thanks for reporting.

However, the actually issue is way less critical than what your original title states.
Once the `logback-test.xml` file made compatible with pre 1.2.0 logback (fixed), the only lingering issue is an ERROR log triggered during the compilation phase. That's more of a cosmetic issue than a blocking one.

> Or the upgrade of logback that has already been been done for version 3.0.0 of gatling should be backported to 2.2.x.

I guess we'll go with this solution if we someday release a 2.2.6.

**Comment by peter-janssen** [comment]
Your welcome, for the record I never stated it was blocking there is just an incompatibility.
