### ISSUE TITLE
recorder can't browse the website

### ISSUE THREAD

**Issue by debu99** [gatling/gatling#3335]
i found the problem is the js/css can't show on the website,  these static files are on the s3 bucket and use cloudfront cdn to speed up, like this
https://static-cloudfront.pigeonhole.at/app/3dd2684/_bundles/vendor.js

all browsers are ok, problem is only recorder

**Comment by slandelle** [comment]
Which [HTTPS](http://gatling.io/docs/current/http/recorder/#https-mode) mode do you use?
My first guess is you're using the self signed cert mode, which won't work for your domain as you use a cert that's validated by a cert authority.

**Comment by slandelle** [comment]
Works just fine now the user has fixed his cert.
