### ISSUE TITLE
Additional rules for proxy exceptions

### ISSUE THREAD

**Issue by mbronk** [gatling/gatling#3337]
\<background\>It is currently possible to explicitly bypass proxy configuration using the: `.noProxyFor("www.github.com", "www.akka.io")` syntax (introduced in [#1454](https://github.com/gatling/gatling/issues/1454)). For the `proxyExceptions` logic to kick-in though, the noProxy exception list needs to contain an exact name of the server to call.\</background\>

Would it be possible to implement **browser-like rules for no-proxy** (example: https://developer.mozilla.org/en-US/docs/No_Proxy_For_configuration)?

----

_Rationale:_
I'm running in an environment where entire outbound 'remote' traffic needs to traverse proxy server. The tests I run though span both local and remote server set, so I'd like to:
   * Set the proxy server as a default 'catch-all'
   * Bypass the proxy for all local addresses

I actually have this exact config in place for other tools (those using: `http_proxy` and `no_proxy ` environment variables) as well as in the browsers. Would like to have the same configuration gatling-side for uniformity.
As a current workaround, I do provide all IPs from my 'local' range to the `.noProxyFor()` method which does not scale for large subnets, nor does it allow for excluding based on DNS names, i.e. `.mycompany.com`.

If implementing a full Firefox-like support is considered too heavy, an ability to include wildcards in the `noProxyFor` entries (like what's done for [http.nonProxyHosts ](https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html)) would be a huge step forward

Thanks!

**Comment by slandelle** [comment]
Looks like both a good idea and a perfect opportunity to contribute :)

**Comment by mbronk** [comment]
While I likely won't be able to create a PR for it (at least not in a couple of weeks time), perhaps the following links will inspire someone  :)
 * https://github.com/dmlloyd/openjdk/blob/2a7331fa285e9e9e250058056fa54e2b584af2b2/jdk/src/java.base/share/classes/sun/net/spi/DefaultProxySelector.java#L131
 * https://github.com/dmlloyd/openjdk/blob/2a7331fa285e9e9e250058056fa54e2b584af2b2/jdk/src/java.base/share/classes/sun/net/spi/DefaultProxySelector.java#L367
(`http.nonProxyHosts` impl. in OpenJDK)

**Comment by slandelle** [comment]
Feature request has been idle for too long, closing for now.

Will reopen if someone chimes in with a contribution.
