### ISSUE TITLE
Core: Parameterized JsonFilter instances

### ISSUE THREAD

**Issue by lukemaurer** [gatling/gatling#3342]
The provided `JsonFilter` instances could be made more general. For collections, we're limited to `Seq[Any]` and `Map[String, Any]`, but, for instance, it's common to receive a `Seq[Map[String, Any]]` as a JSON response. Since implicits can be parameterized by implicits, it should be possible to allow `Seq[T]` and such for any `T` which itself has a `JsonFilter`. (I've got some utility code already written for this.)

Also, `Option[T]` would be handy even though not strictly necessary, seeing as idiomatic Scala code prefers `None` to `null` (though #3341 being fixed is helpful here).

**Comment by slandelle** [comment]
Are you sure that the Scala compiler would be able to tell appart an implicit for `Seq[Map[String, Any]]` and one for `Seq[Any]` in the same scope? Did you give it a try?

How would `Option` fit in our API and implementation? I don't see how.

**Comment by lukemaurer** [comment]
You don't need the separate one for `Any`. You can make `jListJsonFilter` a generic function with a context bound:

   implicit def jMapJsonFilter[T : JsonFilter] = new JsonFilter[Map[String, T]] { ... }

Then apply the filter to each element.

The `Option` filter could just be this:

    implicit def jOptionJsonFilter[T : JsonFilter] = new JsonFilter[Option[T]] {
      val filter: PartialFunction[Any, Option[T]] = {
        case null => None
        case e    => Some(implicitly[JsonFilter[T]].filter(e))
      }
    }

**Comment by swapnil-kotwal-sp** [comment]
👍

**Comment by slandelle** [comment]
> You can make jListJsonFilter a generic function with a context bound:

Indeed, will do

> The Option filter could just be this:

You didn't get me. None of the existing extractors return Option.

**Comment by slandelle** [comment]
@lukemaurer Wiling to provide a PR?

**Comment by slandelle** [comment]
@lukemaurer Gentle ping

**Comment by slandelle** [comment]
Actually, problem is more complex that proposed solution, eg:

```scala
implicit def jOptionJsonFilter[T : JsonFilter] = new JsonFilter[Option[T]] {
  val filter: PartialFunction[Any, Option[T]] = {
    case null => None
    case e    => Some(implicitly[JsonFilter[T]].filter(e))
  }
}
```

could crash with a match error because inner JsonFilter#filter is directly applied without checking if it's defined.

Closing for now as it's been open for a long time without a contribution.
Will reopen if someone chimes in with a contribution.
