### ISSUE TITLE
SBT plugin: support sbt 1.0

### ISSUE THREAD

**Issue by Elufimov** [gatling/gatling#3344]
I post this here because https://github.com/gatling/gatling-sbt do not have issues tab. Do you have plans to move gatling-sbt to sbt 1.0?

**Comment by slandelle** [comment]
> I post this here because https://github.com/gatling/gatling-sbt do not have issues tab.

Yeah, here is the right place. We prefer centralizing everything in one single bug tracker.

> Do you have plans to move gatling-sbt to sbt 1.0?

Of course we will. At some point :)
We're considering having a 2.3.0 that would be just a Scala 2.12, sbt 1.0 upgrade from latest 2.2.
The tricky thing here is [our Zinc based compiler](https://github.com/gatling/gatling/blob/master/gatling-compiler/src/main/scala/io/gatling/compiler/ZincCompiler.scala).

Contributions welcome :)

**Comment by Elufimov** [comment]
You use zinc for incremental compilation? Because I use simple `(compile in config).value` and then aggregate *.class files inside my plugin to mimic official bundle. [link](https://github.com/Pravoru/gatling-remote-sbt/blob/master/src/main/scala/ru/pravo/qa/gatling/remote/GatlingRemoteTasks.scala#L105)

**Comment by slandelle** [comment]
Because you use the sbt plugin.
We use Zinc for our standalone bundle and our maven-plugin (when you don't use the scala-maven-plugin).

**Comment by slandelle** [comment]
Renamed issue to focus on gatling-sbt.
Will open new issues for gatling-compiler and Gatling build itself.

Closed as of gatling-sbt 2.2.2
