### ISSUE TITLE
Core: Have an inject built-in for incremental injection

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3345]
A bit similar to `splitUsers`.

```scala
scn.inject(
    constantUsersPerSec(50) during(3 minutes),
    constantUsersPerSec(100) during(3 minutes),
    constantUsersPerSec(150) during(3 minutes),
    constantUsersPerSec(200) during(3 minutes),
    constantUsersPerSec(250) during(3 minutes),
    constantUsersPerSec(300) during(3 minutes),
    constantUsersPerSec(350) during(3 minutes),
    constantUsersPerSec(400) during(3 minutes),
    constantUsersPerSec(450) during(3 minutes),
    constantUsersPerSec(500) during(3 minutes),
    constantUsersPerSec(550) during(3 minutes),
    constantUsersPerSec(600) during(3 minutes),
    constantUsersPerSec(650) during(3 minutes),
    constantUsersPerSec(700) during(3 minutes),
    constantUsersPerSec(750) during(3 minutes),
    constantUsersPerSec(800) during(3 minutes),
    constantUsersPerSec(850) during(3 minutes),
    constantUsersPerSec(900) during(3 minutes),
    constantUsersPerSec(950) during(3 minutes),
    constantUsersPerSec(1000) during(3 minutes)
  )
```

can be shorten as
```scala
scn.inject((1 to 20).map(i => constantUsersPerSec(i * 50) during(3 minutes)))
```

but it would be nice to have a built-in for non-Scala developers.

**Comment by jiminhsieh** [comment]
> it would be nice to have a built-in for non-Scala developers

Hi @slandelle Could you elaborate more about this? You meant same API for Scala and Java developer. Or separated API for each other? Thanks!

**Comment by slandelle** [comment]
@jiminhsieh You got it wrong. The intent is to have a high level Gatling DSL component, similar to `splitUsers`.

**Comment by jiminhsieh** [comment]
Based on the example:
```scala
scn.inject((1 to 20).map(i => constantUsersPerSec(i * 50) during(3 minutes)))
```
This was what I could come up with:
```scala
def inject(iss: IndexedSeq[InjectionStep]): PopulationBuilder = inject(iss.toIterable)
```

**Comment by jiminhsieh** [comment]
@slandelle I think I totally misunderstood in the beginning. If I don't misunderstand what you said now, you want a DSL could return `SplitInjection` which will do the same behavior as `(1 to 10).map(i => constantUsersPerSec(i * 50) during(10 seconds))`. In the end, this DSL could be used in `inject` with other `InjectionSupport`.

There is my thought of new DSL:

* newAPI(20) **with** (constantUsersPerSec(50) during(3 minutes))
	* Do `constantUsersPerSec(50) during(3 minutes)` **20 times** and increase 50 users each time with 3 minutes duration. 
* newAPI(1000) into (constantUsersPerSec(50) during(3 minutes))
	* Do `constantUsersPerSec(1000) during(3 minutes)` from 50 users to **1000 users**.

If there is any suggestion, I would be glad to hear. Since this the first time I try to design a new DSL. Many thanks! :)

**Comment by slandelle** [comment]
* open workload model version:

```
incrementUsersPerSec(numberOfUsersPerSec: Double)
.times(nbOfStep: Int)
.eachLevelLasting(duration: Duration)
.startingFrom(usersPerSec: Double)
.separatedByRampsLasting(duration: Duration)
```

* closed workload model version:

```
incrementConcurrentUsers(users: Int)
.times(nbOfStep: Int)
.eachLevelLasting(duration: Duration)
.startingFrom(users: Int)
.separatedByRampsLasting(duration: Duration)
```
