### ISSUE TITLE
support for maxConnections and maxConnectionsPerHost

### ISSUE THREAD

**Issue by fommil** [gatling/gatling#3348]
* [x] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [x] Check that you can reproduce your issue with latest Gatling version
  * [x] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [x] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x] Explain your use case, not the implementation you have in mind.

We require a maximum limit on virtual user open connections.

This can be achieved by adding the two relevant lines to https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/ahc/AhcFactory.scala#L83

A workaround is to monkey patch `org/asynchttpclient/DefaultAsyncHttpClientConfig` with the values we want.

**Comment by fommil** [comment]
oh, no need. This can be done with https://raw.githubusercontent.com/AsyncHttpClient/async-http-client/async-http-client-project-2.0.35/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigDefaults.java

**Comment by slandelle** [comment]
For reference, my answer on Gatling's community mailing list:

>Nope. maxConnections and maxConnectionsPerHost are only safety limits that throws exceptions when the limit is reached.
Typically thread regarding this feature in AHC:
user: "I would expect AHC to buffer requests when there's no connection available"
me: "ok, so which kind of queue?"
user: "unbounded"
me: "so OOME when your peer can't handle your load?"
user: "bounded then?"
me: "so what when queue is full?"
user: "block calling thread?"
me: "no way, what you want is back pressure, so implement backpressure, or use AHC reactive streams"

**Comment by fommil** [comment]
yeah, but that's exactly what I need. Gatling took down my desktop several times last week, this protects against it. I would recommend setting something like 20k by default and then making it easy to raise it if needed.

**Comment by slandelle** [comment]
> I would recommend setting something like 20k by default

Overhead hasn't been measured, and it has suffered from leaks until very recently.
Maybe someday.

**Comment by slandelle** [comment]
FYI, you can set it with System props too.

**Comment by fommil** [comment]
I had suspected it might work with them, but I couldn't confirm it. resource files are preferred.
