### ISSUE TITLE
forever loop ends after (Int.MaxValue.milliseconds - 10.seconds)

### ISSUE THREAD

**Issue by mariomann** [gatling/gatling#3353]
Hi,

currently I use the gatling version **2.2.4**.
I use gatling for a real user monitoring and that's why I want to execute my test "forever". I use the forever loop to execute my scenario:

For example:

```
val scenarioHome = scenario("Home")
    .forever() {
      exec(_.set("stage", stage))
        .exec(_.set("languageCode", languageCode))
        .group(stage) {
          group(process) {
            exec(Login.home())
              .pause(1 minute)
          }
        }
    }

setUp(scenarioHome.inject(atOnceUsers(1)).protocols(httpProtocol))
```

But the forever loop ends after 2147473647 milliseconds and the test terminates with an exception:

```
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [2147473647 milliseconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
at scala.concurrent.Await$.result(package.scala:190)
at io.gatling.app.Runner.start(Runner.scala:114)
at io.gatling.app.Runner.run0(Runner.scala:99)
at io.gatling.app.Runner.run(Runner.scala:64)
at io.gatling.app.APGatling$.start(APGatling.scala:96)
at io.gatling.app.APGatling$.fromArgs(APGatling.scala:46)
at io.gatling.app.APGatling$.main(APGatling.scala:27)
at io.gatling.app.APGatling.main(APGatling.scala)
12:15:16.566 [ERROR] i.g.c.a.InnerLoop - 'forever-1-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
```

After an investigation I found out that in the _io.gatling.app.Runner.scala_ class (start - Method) a timeout is set to Int.MaxValue.milliseconds - 10.seconds (2147473647 milliseconds)

```
protected def start(simulationParams: SimulationParams, scenarios: List[Scenario], coreComponents: CoreComponents): Try[_] = {
    val timeout = Int.MaxValue.milliseconds - 10.seconds
    val start = nowMillis
    println(s"Simulation ${simulationParams.name} started...")
    logger.trace("Asking Controller to start")
    val whenRunDone: Future[Try[String]] = coreComponents.controller.ask(ControllerCommand.Start(scenarios))(timeout).mapTo[Try[String]]
    val runDone = Await.result(whenRunDone, timeout)
    println(s"Simulation ${simulationParams.name} completed in ${(nowMillis - start) / 1000} seconds")
    runDone
  }
```

Why is this timeout set? and why to Int.MaxValue?

The error is reproducible.
Can you solve this? That a forever loop really "run/execute" a scenario forever?

What about a workaround, instead of a forever loop to use the asLongAs(true) loop? But the forever loop execute an asLongAs loop, isn't it?

Thanks for your help.

**Comment by slandelle** [comment]
Hi

> After an investigation I found out that in the io.gatling.app.Runner.scala class (start - Method) a timeout is set to Int.MaxValue.milliseconds - 10.seconds (2147473647 milliseconds)

Yes, theres' a limit on timeouts Akka accept

> Why is this timeout set?

It's a security. We might actually consider lowering it someday (it's ~24 days atm, 5 days should cover most use cases).
We want to make sure process always terminates at some points even if it hangs because of a bug or is forgotten and runs in the background.
And we need this termination to trigger reports generation.

> Can you solve this?

My first thought is "no". It's not an issue but intended behavior.
Your use case is interresting but not standard Gatling usage, and I'd rather not push any workaround for something that uncommon while you can easily implement the workaround on your side and reboot your Gatling process every week.
