### ISSUE TITLE
Recorder: websocket proxy and record

### ISSUE THREAD

**Issue by mz0** [gatling/gatling#3356]
Current Recorder's proxy (2.3.0) seem not proxying websockets and definitely not recording those requests/messages.

E.g. my webapp under test has this logic: authenticate user with POST request, than open a single websocket,  mark him logged-on, and not let him logon again until that websocket is closed. When recording this simulation browsing is timing out after logon success on websocket connection (which is not recorded) and the app does not let me logon again until the respective flag in it is reset by that app's start/stop procedure.

HAR recording is of no use here since HAR does not deal with websockets either.

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by mz0** [comment]
I'd like to contribute but this far could find only [meta guide](CONTRIBUTING.md) Do you have some pointers for hacking? E.g. I know how to run Recorder form gatling-maven-plugin-demo, but could not find a similar entry point in this project.

**Comment by slandelle** [comment]
@mz0 Does this help? https://gatling.io/docs/current/developing_gatling/

**Comment by slandelle** [comment]
I don't think that's something we'll ever do (and a contribution is probably even less likely).
Instead I guess we'll implement a browser based recorder instead.
Closing for now.
