### ISSUE TITLE
App: Support Java 9

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3359]
Note: [Scala doesn't fully support Java 9 yet](https://github.com/scala/scala-dev/issues/139).

* Fix ZincCompiler to not cast current `ClassLoader` into `URLClassLoader`
* Disable Gatling's `StringHelper`'s String char array stealing when running with Java 9 as `value` is a byte array then
* Disable Boon's `FastStringUtils` when running with Java 9
* Make sure to never call Jodd's `DOMBuilder#parse` with a String, as it relies on Java 8 String implementation and there's currently no way to disable
* Fix multiple `Class`, `Classloader` and `ByteBuffer` deprecations and API breaking changes

**Comment by Glamdring** [comment]
Hello,

Its says "fixed", but I'm using the latest snapshots and it still fails with the ClassLoader cast.

**Comment by slandelle** [comment]
"Fixed" means pushed in private master (used for FrontLine). It advertises the work has been done (so no need to try and contribute).

Issue will get closed once the commit has been pushed to public master, which we only do from time to time.

**Comment by michaelbraun** [comment]
Any chance of this being included in a 2.3.2 release? Load testing with gatling will break on Java 9/10 JVMs now due to the String internals change.

**Comment by aandeers** [comment]
Any news on when gatling 3 will be released?
