### ISSUE TITLE
testOnly runs all test

### ISSUE THREAD

**Issue by bartkummel** [gatling/gatling#3360]
I have two test classes in the `src/it/scala/com/mycompany/myapp/` directory. Let's say the classes are `TestA` and `TestB`. When I run `sbt gatling-it:testOnly com.mycompany.myapp.TestB`, both tests are run. I'd expect only `TestB` to be run in this example.

**Comment by slandelle** [comment]
Which version of sbt do you use? Works fine with sbt 0.13.16 for me.
If you can only reproduce with sbt 1.0, I suggest opening an issue against sbt.

**Comment by bartkummel** [comment]
I'm using SBT 0.13.15

**Comment by slandelle** [comment]
Then please upgrade to 0.13.16 and provide a reproducer.

**Comment by bartkummel** [comment]
I have installed SBT 0.13.16 and the problem still exists. I have created a minimal project to reproduce the problem, please see https://github.com/bartkummel/reproduceGatlingProblem for details.

**Comment by slandelle** [comment]
I'd say you're not using sbt properly.

If you want to directly launch sbt and pass a full command as a parameter, you have to wrap it with double quotes: `sbt "gatling-it:testOnly com.mycompany.myapp.TestB"`.

Or go in interactive mode:
```
sbt
> gatling-it:testOnly com.mycompany.myapp.TestB
```

**Comment by bartkummel** [comment]
I guess you're right. That's a nasty problem in SBT then. I'd say `testOnly` should throw an error when it doesn't get an argument. But that's not of your concern of course. ;) Thanks for helping me out!

**Comment by slandelle** [comment]
> That's a nasty problem in SBT then.

Frankly, I'm not versed enough in the sbt arcanes to have an opinion on this :)
There's probably a good reason for this.
Could be an interesting question for the sbt mailing list or SoF then.

**Comment by MaksSieve** [comment]
have this problem with jenkins sbr-plugin now. sbt version 1.2.8
