### ISSUE TITLE
Bad option for testCompile for project generated with Maven archetype

### ISSUE THREAD

**Issue by t-kl** [gatling/gatling#3361]
Create a new Gatling project with:
`mvn archetype:generate`

Make sure to use the most recent version 2.3.0.

Compile the tests with:
`mvn test-compile`

This leads to the following error:
`[ERROR] scalac error: bad option: '-Ybackend:GenBCode'`

It appears that the `-Y` Option isn't supported in Scala 2.12 anymore.
However the generated `pom.xml` still uses it:
```
                    <execution>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-Ybackend:GenBCode</arg>
                                <arg>-Ydelambdafy:method</arg>
                                <arg>-target:jvm-1.8</arg>
                                <arg>-deprecation</arg>
                                <arg>-feature</arg>
                                <arg>-unchecked</arg>
                                <arg>-language:implicitConversions</arg>
                                <arg>-language:postfixOps</arg>
                            </args>
                        </configuration>
                    </execution>
```
I've tried and changed them to `-J` instead since that appears to be supported:
```
Usage: scalac <options> <source files>
where possible standard options include:
  -Dproperty=value                     Pass -Dproperty=value directly to the runtime system.
  -J<flag>                             Pass <flag> directly to the runtime system.
```
And now the goal `test-compile` runs without an error. But I don't know if that makes sense at all.

Interestingly the direct call `mvn scala:testCompile` doesn't lead to the error.
The reason is that the arguments aren't passed to the _Scala_ compiler in this case.
Thus I assume that's the bigger issue here.

**Comment by slandelle** [comment]
Thanks for reporting!

> Interestingly the direct call mvn scala:testCompile doesn't lead to the error.
The reason is that the arguments aren't passed to the Scala compiler in this case.
Thus I assume that's the bigger issue here.

No, this is how maven works. `execution` blocks are only honored when triggering plugin from the lifecycle, not when directly invoking plugin task.
