### ISSUE TITLE
Extend stats in *stats.json

### ISSUE THREAD

**Issue by LGH** [gatling/gatling#3370]
Current Gatling versions produce stats.json and global_stats.json files that are quite useful, but they still lack some information that would be very useful to have:

- Execution start time (and end time or duration)
- Definition of what the four different percentiles actually represent (i.e. percentile4 == 99th percentile) since that can vary between tests depending on the configuration (much like groupN values that have "name" fields that describe the group)

**Comment by slandelle** [comment]
Sorry, but we won't make any improvements to reporting and integrations with other systems in Gatling OSS.
Those fall into the scope of FrontLine, our Entreprise product.
