### ISSUE TITLE
HTTP: Gatling doesn't update to new Etag when it changes

### ISSUE THREAD

**Issue by mmneuro** [gatling/gatling#3371]
I wanted to make a stress test on our staging system and make sure our cache works correct, so i made a test scenario where i repeat a request and make assertion on the HTTP status code, whether it is 200 or 304.

So it looks like this:

```scala
var apiCall = 
  exec(
    http("apiCallName")
    .get("path/of/the/API/endpoint")
    .header("Accept-Encoding","gzip, deflate"))
   .pause(minPause milliseconds, maxPause milliseconds)
  .repeat(repeatsNo) {
    exec(
        http("apiCallName")
        .get("path/of/the/API/endpoint")
        .header("Accept-Encoding","gzip, deflate").check(status.is(200)))
    .pause(minPause milliseconds, maxPause milliseconds)
  }
```

The execution begins, with one successful request (no assertion on that anyway), and then all the other requests (these inside the repeat block) are reported as failed because gatling correctly uses the etag and receives an HTTP status code of 304.

Then, as the stress tests continues, I change the data on the database, so the response changes, and also the Etag changes.

Then, all subsequent responses that gatling receives are with HTTP status code 200, where the correct should be to receive one request with HTTP status code 200, and then use the new Etag and get reponses with HTTP status code 304.

I doubled checked by undoing the changes on the data on the database, so the Etag issued by the server changes back to the previous value (I suppose that Etag is created by a hash function on the response, so because subsequent responses are the same with the first response, they get issued with the same Etag value on the response header). Then, gatling gets responses with HTTP status 304, which means that gatling has stored the first Etag it received, and then uses it an all subsequent requests, no matter if the Etag changes.

Also tried disableClientSharing, perUserNameResolution on the HTTP configuration but no luck.

Thanks in advance

**Comment by slandelle** [comment]
Hi,

This case is supposed to be covered. We're updating the cache unless the entry is already cached with the same value:

* https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/ahc/ResponseProcessor.scala#L297
* https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/cache/HttpContentCacheSupport.scala#L59
* https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/util/cache/SessionCacheHandler.scala#L58-L59

Could you please provide a sample app to test against?

**Comment by slandelle** [comment]
Also, you didn't mention the version of Gatling you're using, as you're required to when submitting an issue.

Could you please check that you're indeed using the latest version, and otherwise check if upgrading fixes your issue.

**Comment by mmneuro** [comment]
Hi,

I am using Gatling version 2.3.

I can't provide a sample app but i am getting the desired functionality by manually storing and reusing the Etag by changing the aforementioned code to:

`var apiCall = exec(http("apiCallName").get("path/of/the/API/endpoint").header("Accept-Encoding","gzip, deflate").check(header("Etag").saveAs("lastEtag"))).pause(minPause milliseconds, maxPause milliseconds).repeat(repeatsNo) {
exec(http("apiCallName").get("path/of/the/API/endpoint").header("Accept-Encoding","gzip, deflate").
header("If-None-Match", if("${lastEtag}".charAt(0) == 'W') "${lastEtag}".substring(2) else "${lastEtag}").check(status.is(200)).check(header("Etag").saveAs("lastEtag"))).pause(minPause milliseconds, maxPause milliseconds);
}`

and also disabling caching on the http configuration using disableCaching.

**Comment by slandelle** [comment]
` .header("If-None-Match", if("${lastEtag}".charAt(0) == 'W') "${lastEtag}".substring(2) else "${lastEtag}")`

This code is completely broken and the condition will always evaluate to false.
Please read the doc: https://gatling.io/docs/current/session/expression_el/#expression-language

**Comment by mmneuro** [comment]
Yes, but unexpectedly the code works because, where the http client i use returns the Etag on the response header with W/ when the Etag is weak, the response header gets logged by gatling without it, so unexpectedly it works as:

.header("If-None-Match", "${lastEtag}")

always
