### ISSUE TITLE
Gatling dependencies should properly declare scala version in artifacts name 

### ISSUE THREAD

**Issue by kstokoz** [gatling/gatling#3373]
Gatling is scala library and has a lot of scala dependencies, but unfortunately artifacts does not declare scala version as part of theirs name.

Gatling 2.2.5 was compiled with scala 2.11 and has dependencies on for example akka of 2.11 as well.
Gatling 2.3.0 compiled now with 2.12 and it is no longer possible to use 2.3.0 version in the project build with scala 2.11.

Attempt to import Gatling to project build with 2.11 will result in following error:
```
Modules were resolved with conflicting cross-version suffixes in 
[error]    com.typesafe.akka:akka-actor _2.11, _2.12
[error]    org.scala-lang.modules:scala-xml _2.11, _2.12
[error]    org.scala-lang.modules:scala-java8-compat _2.11, _2.12
[error]    org.scala-lang.modules:scala-parser-combinators _2.11, _2.12
[error]    com.typesafe.akka:akka-slf4j _2.11, _2.12
```

All gatling artifacts should properly specify scala version and ideally cross compiled for scala 2.11 and 2.12.

**Comment by slandelle** [comment]
Actually, we don’t think of Gatling as a library but as a software. And we don’t target only the Scala devs, and sadly the Scala versioning scheme is unclear for non Scala people, hence the Java style versioning.
Maybe we’ll change it someday, maybe not.
We don’t have plans for cross compiling atm.
