### ISSUE TITLE
HTTP: Websocket incoming message is matched only with first check in sequence

### ISSUE THREAD

**Issue by Sejten** [gatling/gatling#3375]
When we have more than one check assigned to websocket the incoming message is matched only with match criteria from the first check, e.g.

```scala
    .exec(ws2("Ws").sendText("")
      .wait(30 seconds)(
        ws2.checkTextMessage("Check1")
          .matching(regex(".*expectedMessage1.*"))
          .check(regex(""".*expectedMessage1.*""")
          ),
        ws2.checkTextMessage("Check2")
          .matching(regex(".*expectedMessage2.*"))
          .check(regex(""".*expectedMessage2.*"""))
      )
    )
```
Incoming message will be either  match with ".*expectedMessage1.*" match condition or discarded, second check will not be processed.
Version:3.0.0-SNAPSHOT

**Comment by slandelle** [comment]
If I get it right, you're saying that you expect 2 messages, one for the first check, one for the second one, and that the second check is being discarded?

Could you provide a reproducer please?

**Comment by Sejten** [comment]
I think that pasted code is a good example. I'm sending message to websocket and I'm expecting to receive message "expectedMessage1" OR "expectedMessage2". Currently if I receive "expectedMessage2" msg, it will fail to match to the first expected match in sequence and msg be discarded. Eventually check will fail on timeout.

**Comment by slandelle** [comment]
That's not what this code does: receive message "expectedMessage1" AND THEN "expectedMessage2". Use matching and check conditions that would handle the OR you're trying to achieve.
