### ISSUE TITLE
Maven plugin: support failsafe mode so post-integration-test is executed

### ISSUE THREAD

**Issue by tbrouhier** [gatling/gatling#3379]
Hello Gatling community, 

First of all, our setup: we are using maven 3.3+, Gatling plugin 2.2.4 on Jenkins 2.x running on openjdk 8 and RHEL7. 

Now, the issue we have. We are starting a docker environment at the maven pre-integration-test, run the tests, and expect a post-integration-test execution to tear down the environment. Unfortunately, and unlike the Failsafe plugin, a failure in the tests would stop the maven execution and let the environment hanging. 

Finally, the expected behavior : we would expect that the post-integration-test goal to be run leaving the runner (Jenkins, in our case) clean and the build failure to arise at the verify phase. 

Cheers,
Thomas

**Comment by slandelle** [comment]
Looks like an interesting feature to support.
It would be awesome to have such contribution!

**Comment by slandelle** [comment]
Idle for a long time. Will reopen if there's some activity.

If someone is interested in contributing someday, the trick is to have 2 mojos:
* one bound to `integration-test` phase that buffers results in a file
* one bound to `verify` phase that reads the file and throws Exceptions

See https://github.com/apache/maven-surefire/tree/master/maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe

**Comment by albers** [comment]
I created https://github.com/gatling/gatling-maven-plugin/pull/17 to address this issue.

It detects failed assertions by analyzing the created _assertions.xml_ files.
