### ISSUE TITLE
checkTextMessage should not be mandatory.

### ISSUE THREAD

**Issue by htambekar** [gatling/gatling#3396]
I have service which doesn't send any response on connect method and after sending pingMessage.
In that case, I would like to avoid adding following line.

ws2 protocol should support sendTextMesssage without adding any checks. Checks should not be mandatory.

.wait(1 second) (
ws2.checkTextMessage("PingMessageResponse").check(regex(""" """))
)

**Comment by slandelle** [comment]
I suspect you're getting it wrong.
Where do you see a check [here](https://github.com/gatling/gatling/blob/master/gatling-http/src/test/scala/io/gatling/http/Ws2CompileTest.scala#L57)?
