### ISSUE TITLE
Core: Request build failures are not accounted by assertions

### ISSUE THREAD

**Issue by mpmiszczyk** [gatling/gatling#3403]
When running Gatling from `sbt` tests will be reported as sucess, even if some of requests failed to build:
```
Failed to build request Customer trays to end conversation: ur      1 (100,0%)
l io.gatling.core.session.el.ElCompiler$$$Lambda$289/212248733...
.....
[info] Simulation(s) execution ended.
[success] Total time: 7 s, completed 2017-12-21 16:05:22
```

```
...
   http("Customer trays to end conversation")
      .delete("conversation/${CID}")
```
```
  ).assertions(forAll.failedRequests.count.is(0))
```
Requests failed to build should mark whole scenario as failed.

**Comment by slandelle** [comment]
This has nothing to do with abt.
In assertions, we only account for real traffic. As Gatling couldn’t build this request, it can’t be counted here. I guess we would need a different kind of assertions.
Contributions welcome!

**Comment by mpmiszczyk** [comment]
Regarding contribution, maybe, I would like that. If I will be able to find enough time, and my company will continiue to use Gatling.

Since I have your "ear" I would like to nagg you for little bit more. I am aware that Gatling is stress testing tool, but in our case, since we are developing new product, we are still using it for Integration Testing (for now)(we settled on you mainly becouse of sse support, which also can be flaky, but that's another case), and we can see that Gatling was not build for it. I'm not complaining, but if I were to contriubute it would be (mainly) to bring it little bit close to testing framework. Things like:
 * improve shell output for failing scenarions
 * being able to run all tests from IntelliJ (not as sbt task)(I've failed to incorporate [maven artifact](https://gatling.io/docs/2.3/extensions/maven_archetype/) into our project
 * failing to build will couse failure of all tests (new assertion like you suggestet)
 * ...

So now I would like to know if you will be willing to *add* such functionality (accept PR) to Gatling, or does it conflict with your vision of this tool.

**Comment by slandelle** [comment]
Indeed, improving support for functional testing is something we'd like to do.

**Comment by slandelle** [comment]
Idle for a long time. Closing for now.

**Comment by agaal** [comment]
Hi,

for this a workaround is used by asserting the expected number of tests.

```
  setUp(scn.inject(ssers))
    .protocols(httpProtocol)
    .assertions(assertForFailedRequest, global.allRequests.count.is(8))
}
```

It would be great to have an in-built solution to assert items where the test could not be built due to missing parameters.

**Comment by ejayaraman** [comment]
@agaal . I am interested in hearing more that work around. When you do `global.allRequests.count.is(8)`, wouldn't the count vary depending on how long you run, load percentage etc? Or have I understood this incorrectly? 

Stephane, is there a case for reopening this issue? Thanks.

**Comment by Hennns** [comment]
Chiming in my support for this as well, it would be really nice to have a way of asserting that every request was built successfully. 
Furthermore, I definitively think there is a use-case for catching any other errors as well.

For example, the following will not fail the test, which I personally found pretty surprising

.exec{ session => assert(false); session }

**Comment by johnmartel** [comment]
@ejayaraman @agaal's workaround works well in a _functional_ testing scenario, since all HTTP requests are known in advance, at least it did fix the issue at hand here in my specific case.
