### ISSUE TITLE
Build: CI no longer properly publishes snapshots and metadata on Sonatype

### ISSUE THREAD

**Issue by mirosval** [gatling/gatling#3406]
Looking here: https://travis-ci.org/gatling/gatling

You can see: `java.lang.RuntimeException: Repository for publishing is not specified.`
The snapshots here: https://oss.sonatype.org/content/repositories/snapshots/io/gatling/highcharts/gatling-charts-highcharts/ 
are from September 2017, so it seems to be broken for some time.

I came across this when I was trying to use the latest snapshot to see if it fixes a (seemingly) Java 9 related issue:
`io.gatling.core.session.el.ElParserException: Failed to parse graphql with error '[B cannot be cast to [C`

**Comment by slandelle** [comment]
@mirosval Thanks for pinging. Sadly, since we've upgraded to sbt 1, we're currently no longer able to properly publish snapshots on Sonatype: https://github.com/sbt/sbt/issues/3486#issuecomment-354786612

**Comment by krisgeus** [comment]
Any progress on this? 
I'm using the snapshot version for a while now and am stuck on the november 17th release since that's the one that is referenced in the metadata. I'm afraid I will run into large issues when suddenly in the future I get a new version which has a lot of changes in it ;-)

**Comment by slandelle** [comment]
No, we depend on sbt to fix this. I've pinged in issues and on Twitter, no news so far.
On our side, we don't have expert skills on sbt and this issue has low priority as it affects neither stable releases nor FrontLine customers.
So best way to fix this is to contribute on sbt.

**Comment by slandelle** [comment]
It seems https://github.com/arktekk/sbt-aether-deploy do the job but I'm not very inclined to risk breaking release process and publishing snapshots is not really a priority, all the more now Gatling 3 is out.
I think we're going to drop publishing snapshots for now, and see if https://github.com/sbt/sbt/issues/3486 gets fixed some day.
