### ISSUE TITLE
Jenkins plugin: Configurable reports path

### ISSUE THREAD

**Issue by jmflaherty** [gatling/gatling#3407]
Hi.

I'm needing a new feature to configure the gatling-plugin for Jenkins with custom paths to find the reports.

Currently in my team we are using containers to deploy pretty much everything. Even our load tests. These tasks are executed via Jenkins and we are trying to use the gatling-plugin to visualize our reports. The problem is that as our tests reside in a container, so we fetch our reports from the containers and save them into a custom location due to our devops practices, and as the plugin doesn't allows us to configure it with custom locations from which to read the reports we can't of course visualize them.

Would it be possible to add an optional path field to override the default one that's being used to find the reports?

Thanks.

**Comment by slandelle** [comment]
This is not something we'll implement ourselves, as our official solution for deploying Gatling injectors is FrontLine, which comes with its own dashboard instead of the HTML reports.

Then, contributions welcome :)

**Comment by jmflaherty** [comment]
Read the source code with my devops partner and found the correct path on which the reports have to be left so the plugin can read them. It is: `/var/lib/jenkins/workspace/<jobName>/results`

I tried to edit the [Wiki page](https://wiki.jenkins.io/display/JENKINS/Gatling+Plugin) but it seems only the owners of the plugin can :sweat_smile:  

Could you, @slandelle , or someone else add this to it? :point_down: 

```
Configure your job :
- For a maven job: add "Track a Gatling load simulation" as a new post-build action. Beware that neither your Jenkin's path nor your job's name should contain any space.
- For a pipeline job: add a line to your pipeline script: gatlingArchive()
- For a containerized job: copy your simulations' results to `/var/lib/jenkins/workspace/<jobName>/results` in Jenkins.
```

Thanks again :smile:

**Comment by slandelle** [comment]
cc @ccedric

**Comment by ccedric** [comment]
Thanks @jmflaherty for pointing this out, I've added this information to the Wiki page :)

**Comment by ccedric** [comment]
Closing, as there is a Jenkins workaround.
