### ISSUE TITLE
Deploying and running gatling in Cloud foundry

### ISSUE THREAD

**Issue by pradeepkusingh** [gatling/gatling#3409]
This is a question, not a feature request and I posted in few forums and didn't get answer.

- How can I deploy Gatling in cloud foundry and run perf testing ?

**Comment by slandelle** [comment]
FrontLine already supports deploying on AWS, Azure, Google Cloud Platform, Digital Ocean and Azure. If we have demand from our customers, we'll implement Cloud Foundry support too. Nothing planned on the open source side.

Please use the community mailing list for questions, not the bug tracker.

**Comment by jhatcher9999** [comment]
Any update on this?  I would be interested in launching Gatling on PCF.

**Comment by slandelle** [comment]
Since previous message, we've added Kubernetes & OpenShift support in FrontLine.
But still no customer request for having FrontLine support Cloud Foundry. Feel free to reach out if you're interested: https://gatling.io/company/contact/.
