### ISSUE TITLE
HTTP: Drop extraInfoExtractor

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3417]
This feature isn't used in any official nor open source community reporting component.
And it's not a proper solution for debugging.
Let's drop dead code.

**Comment by kuzkdmy** [comment]
Hi @slandelle
May be we really don't find some standard way to do this and misused gatling somehow, 
but in our company we use this as a hook for our custom reporting solution
We have all data under control, we: 
- fulfill simulation.log with extra data what was send and what was got
- after hook we read this simulation.log with extra data and generate csv files with required for us
- after hook we push csv as Parquet on S3
I really don't see how this can be implemented now, so this block for now with library upgrade
Thanks.
