### ISSUE TITLE
System properties for http.ssl seem to be ignored

### ISSUE THREAD

**Issue by maurizio-lattuada** [gatling/gatling#3419]
Hi,

I'm using Gatling 2.3.0 to do some load and stress tests on a webservice endpoint.
This endpoint can be reached only by providing a valid client certificate.
According to [https://gatling.io/docs/2.3/http/http_ssl/](https://gatling.io/docs/2.3/http/http_ssl/) , I have to provide the truststore filename and password either in gatling.conf or in the system properties.
Well, when setting that using the system properties as
```
  System.setProperty("gatling.http.ssl.keyStore.file", "cert/user.p12");
  System.setProperty("gatling.http.ssl.keyStore.password", "password");
```

(`cert` is a subfolder in `src/test/resources`), that certificate is not provided to the endpoint and I have thus an HTTP 403. This call to `setProperty` is done before setting the http protocol object, an HttpRequestBuilder object and launching the simulation:
```
class WsPamCertificate extends Simulation {

  // See https://gatling.io/docs/2.3/http/http_ssl/
  System.setProperty("gatling.http.ssl.keyStore.file", "cert/user.p12");
  System.setProperty("gatling.http.ssl.keyStore.password", "password");

  println(System.getProperties)

  val httpProtocol = http
    .baseURL("https://myserver.ch:4443")
        .wsBaseURL("https://myserver.ch:4443")
    .inferHtmlResources()
    .acceptHeader("*/*")
    .contentTypeHeader("application/soap+xml; charset=UTF-8")
    .userAgentHeader("Apache-CXF/3.2.0")

  val wsPam:HttpRequestBuilder = http("request_0")
    .post("/endpoint")
    .headers(headers_0)
    .body(StringBody(preBody + lastName + postBody)) // here the SOAP message is composed
    .check(status.is(200))
    .check(xpath("...CUT CUT CUT...",
      List("S" -> "http://www.w3.org/2003/05/soap-envelope",
        "ns2" -> "http://namespace.ch/abc"))
      .count
      .greaterThan(0)
    )
  // ...
}
```

On the other hand, if I set filename and password in gatling.conf the same way as in the system properties:

```
      keyStore {
        #type = ""      # Type of SSLContext's KeyManagers store
        file = "cert/user.p12"      # Location of SSLContext's KeyManagers store
        password = "password"  # Password for SSLContext's KeyManagers store
        #algorithm = "" # Algorithm used SSLContext's KeyManagers store
      }
```

then that certificate is now provided to the endpoint, so I got correctly an HTTP 200.
Note: 

- by setting an absolute path in the system properties, unfortunately no success, still an HTTP 403
- doing a `println(System.getProperties)`, these SSL related properties are correctly stated (here below a truncated version for ease of reading:
```
{java.runtime.name=Java(TM) SE Runtime Environment, gatling.http.ssl.keyStore.password=password, sun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib, java.vm.version=25.152-b16, gopherProxySet=false, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=CH, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, gatling.http.ssl.keyStore.file=cert/user.p12, ...}
```

As said above, I'm using Gatling 2.3.0 in a maven project in IntelliJ.

Any idea about that?
Please feel free to ask for further logs if needed.

Thank you in advance

**Comment by slandelle** [comment]
>System.setProperty("gatling.http.ssl.keyStore.file", "cert/user.p12");
  System.setProperty("gatling.http.ssl.keyStore.password", "password");

I guess you're setting those in your Simulation. Then, it's too late, the configuration has already been resolved. You need to set those upstream.

**Comment by maurizio-lattuada** [comment]
Well, if with "you're setting those in your Simulation" you mean inside the subclass extending `Simulation`, then yes, you are right.
I suppose I have to set them either as command line (`-Dgatling.http.ssl.keyStore.file=...`) or in `gatling.conf`.
Thanks for the hint.
