### ISSUE TITLE
unable to stop the recording in CLI

### ISSUE THREAD

**Issue by MuthuVignesh91** [gatling/gatling#3422]
I am trying to record scripts in cli mode. I am able to achieve the recording, but the recording is not getting simulated unless i have to press CTRL-C manually. I am unable to understand the reason though, because i am using the pid from .gatling-recorder-pid to get the pid and killing it. Even that isn't helping. 

Normally when i stop the recorder.bat with CTRL-C, i get the following message which gives a message saying New simulation generated, followed by terminate batch job. I see the recorded file generated successfully in this case.

whereas, when i terminate by using the pid file, i just see the message as press any key to continue.

Command>> recorder.bat -cli true -m Proxy -of D:\Gatling\cli -cn TestcliRecording

Please help guys

**Comment by slandelle** [comment]
Works just fine for me (on OSX, don't have Windows).
Just make sure you're sending a SIGTERM and not a SIGKILL.

**Comment by MuthuVignesh91** [comment]
Hi,
I am trying to do the below action
1. Start the recorder from a batch file called in java.
2. Do something.
3. kill the pid retrieved from the .gatling-recorder-pid file. This process is also from java. This is where i am facing a problem. please help

**Comment by ikocev** [comment]
Hi,

Do you happen to run your job with Process? This is a known bug and won't be fixed as pointed here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4770092

You should use ProcessBuilder instead.
