### ISSUE TITLE
SSE: Very long events are not decoded

### ISSUE THREAD

**Issue by rafal0p** [gatling/gatling#3426]
If the event data is very long - `SseStreamDecoder` does not decode it at all.

[Here](https://gist.github.com/anonymous/de46ec477387bd6e9ec8f479315d1101) [are](https://gist.github.com/anonymous/39a58bcecfb37e6e069661ae3f02be0a) examples of slightly modified, failing tests from master branch. If variable `veryLongStr` is one char shorter tests are successful. Mind that magic limit for chunk length is close to 1024, but not exactly equal.

If I am correct bug is somewhere [there](https://github.com/gatling/gatling/blob/62340816e95d212a4cee07b296a5c8dee73eaf59/gatling-http/src/main/scala/io/gatling/http/action/async/sse/SseHandler.scala#L80). One `bodyPart` can have multiple events, but many `bodyParts` can as well contain the same, big event.

**Comment by slandelle** [comment]
Thanks for reporting!
