### ISSUE TITLE
Gatling http client with MutualTLS

### ISSUE THREAD

**Issue by politrons** [gatling/gatling#3429]
Hi, we are using Gatling API running with Gatling plugin in our Maven life cycle. Everything fine so far using Gatling http client

object GatlingHttpClient {

  val properties = new Properties() {
    put("contentType", "application/json; charset=UTF-8")
  }

  implicit val getHeaders: Map[String, String] = HttpClient.headers

  val conf = http
    .maxConnectionsPerHost(100000)
    .baseURL(Config.host)
    .headers(HttpClient.getHeaders(properties))
    .acceptHeader("application/json")

}

And the Scenes 

class RestScene(name: String) {

  val msgId = Iterator.continually(Map("msgId" -> Random.alphanumeric.take(30).mkString))

  def create(): ScenarioBuilder = {
    scenario(name)
      .exec(session => session.set("f2e_mock_service", host))
      .feed(msgId)
      .exec(http("rest connector")
        .post("${f2e_mock_service}/mus/rest/v1")
        .body(StringBody(F2EMessages.message(path = "/rest/v1", key = "${msgId}", id = "${msgId}")))
        .check(status.is(200)))
      .pause(Duration(1, SECONDS))
  }

}

But now we had the need to test against our endpoints using MutualTLS. And checking the documentation I cannot see any way to configure the httpClient to pass the SSLContext or something like that. Only configure by gatling.conf, but in our case not sure how can we do it.

Any suggestion or guide line about this?

**Comment by slandelle** [comment]
Please use the community mailing list for questions, not the bug tracker.

**Comment by politrons** [comment]
Sorry may I know where it is please?
