### ISSUE TITLE
Make command line parameters take precedence over gatling.conf 

### ISSUE THREAD

**Issue by rolandtritsch** [gatling/gatling#3430]
Just tried to make sbt-assembly work and run a simulation from the jar file with ...

java -jar load-test.jar -s my.Simulation

... and found out that the command line gets overridden by gatling.conf (and if simulationClass is "", then the error message will be "There is no script", which is misleading).

A/the test case is here - https://github.com/rolandtritsch/gatling-load-testing

Proposal 1: Make the command line override gatling.conf
Proposal 2: If this is not possible add an INFO/DEBUG/TRACE message, when gatling.conf overrides a/the command line parameter(s)

**Comment by slandelle** [comment]
Gatling OSS doesn't have support for fatjars. FrontLine has.
Then the proper way to override gatling.conf is to use System props
