### ISSUE TITLE
No suitable driver found for jdbc:mysql://localhost   

### ISSUE THREAD

**Issue by masen931005** [gatling/gatling#3431]
when i use jdbc to connection mysql.。such as jdbcFeeder("jdbc:mysql://localhost:3306/test","root","root","SELECT id FROM users where id =1"),it appers Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/test.。when I saw the source.I find 
gatling/gatling-jdbc/src/main/scala/io/gatling/jdbc/feeder/JdbcFeederSource.scala     lack   “Class.forName(driver);” to registered  the driver。

**Comment by slandelle** [comment]
Since JDBC 4 and JDK 6, drivers are automatically discovered, as long as they are in the classpath: https://docs.oracle.com/javadb/10.8.3.0/ref/rrefjdbc4_0summary.html.

You’re either using a very very old driver, or failed to add it in the classpath.
