### ISSUE TITLE
App: Nicer CLI experience

### ISSUE THREAD

**Issue by Mahoney** [gatling/gatling#3442]
Hi,

I'd like Gatling to be more pleasant to use from the command line on OS/X.

* At present installation involves going to the gatling website, downloading a zip and expanding it somewhere of your choice.

  I'd like it to be available on Homebrew.

* At present the `gatling.sh` script needs to be run from the bin directory in which Gatling was installed; if you symlink it as e.g. `/usr/local/bin/gatling` and try to use it it will complain it cannot find the Main class.

  I'd like it to be usable from my `PATH` so I don't have to remember where I installed it.

* At present the arguments passed to `gatling.sh -ro` are resolved relative to the directory in which Gatling was installed, rather than the current working directory.

  I'd like it to resolve relative to the current working directory.

In an ideal world I could generate a Gatling report from a `simulation.log` as follows:
```bash
brew install gatling && \
cd ~/simulation-project-dir/reports/mysim-1521468228891 &&  \
gatling -ro .
```
(It's a brilliant tool, btw - just think this would make it even better.)

**Comment by slandelle** [comment]
Supporting Homebrew is not a priority for us. Contributions welcome!

**Comment by slandelle** [comment]
Idle. Closing for now. Will reopen if there's some activity there.

**Comment by matthewjumpsoffbuildings** [comment]
the CLI install/usage is still kinda clunky on OSX

**Comment by slandelle** [comment]
@matthewjumpsoffbuildings Could you please elaborate?

**Comment by matthewjumpsoffbuildings** [comment]
sorta like the stuff mentioned by @Mahoney - for example i was expecting to be able to run `gatling` from anywhere for starters. i didnt try symlinking it to bin since i saw this issue... unless symlinking works now?
