### ISSUE TITLE
App: Make timestamp in test-result directory name more user friendly

### ISSUE THREAD

**Issue by Calieston** [gatling/gatling#3443]
A property to configure timestamp format for report result folders would increase readability.
Currently unix timestamp is added as suffix to folder name.
**Example**:
* "testserviceA"-1521641080618
* "testserviceA"-1521641143837
...

**Better**:
* "testserviceA"-20180320
* "testserviceA"-20180319

Didn't find such a configuration property in gatling.conf

**Comment by slandelle** [comment]
It would be more safe to go with millis resolution. Then, we need to make it configurable, I don't think we use the actual value anywhere.

Contributions welcome.

**Comment by MadeInChina** [comment]
I have static web server and want using test-result directory directly form localhost:8080/testserviceA/index

So It's would be configurable for timestamp and  test-result directory

for example 
"testserviceA"-1521641080618 could be  to testserviceA
