### ISSUE TITLE
Execs is not extensible. Could it be?

### ISSUE THREAD

**Issue by rs3vans** [gatling/gatling#3447]
_Feature request:_

The trait `Execs` is sadly not extensible because of the locked-down visibility on the `newInstance` def (it is `private[core]`). It would be great to open that up so that custom extensions could be added to the Gatling DSL by extending `StructureBuilder`.

My use case is such that I would like to add domain-specific extensions without having to be so wordy (e.g. having to wrap everything in `.exec(...)`).

Thanks for considering!

**Comment by slandelle** [comment]
Generally speaking, Gatling is a software, not a library or a framework.
Everything but the DSL is internal and subject to change, hence we prefer keeping those private.

You could achieve what you're trying to do with some [implicit conversions](https://danielasfregola.com/2015/06/08/pimp-my-library/).
