### ISSUE TITLE
Throttle disables pauses

### ISSUE THREAD

**Issue by dtertman** [gatling/gatling#3453]
If you specify a throttle condition, all pauses are disabled / skipped.
Simple reproduction steps:
1) Download the latest Gatling bundle
2) Modify the BasicSimulation.scala in the directory `$GATLING_HOME/user-files/simulations/computerdatabase/BasicSimulation.scala` by adding:
```
.throttle(jumpToRps(10), holdFor(10 seconds))
```
to the `setUp`.
3) Run using `gatling.sh`.

All pauses will be skipped, the simulation will complete in under 4 seconds. The situation is not improved by adding `.constantPauses` or any other workaround we've found.

For tests where we try to set something up, wait for it to process, and then validate it, this makes throttle unusable.

**Comment by slandelle** [comment]
Yes, that the current intended behavior.
`throttle` is intended for throughput shaping injection profile, so your scenario is supposed to be able to generate at least the throughput you've defined.
That being said, that's definitively a feature I don't like, both from the feature side (I still have to find someone capable of explaining properly how such injection profile makes sense compared to open and closed workload models) and from the implementation side (exceeding requests are enqueued).

**Comment by dtertman** [comment]
Our use-case : many of our calls go (from our services) to third parties, and some of these third parties have rate limits.  Rather than tweaking the number of users and the way those users are injected per-scenario, it would be nice to simply specify the third party limit as a `jumpToRps` and let Gatling guard the rate and extend the test.

**Comment by slandelle** [comment]
> let Gatling guard the rate

How does it make sense? How is it realistic, compared to what happens in your live system? I would expect your system to either start returning errors or apply back-pressure when third party limit is reached. It looks to me you want to introduce an artificial bias.
