### ISSUE TITLE
Graphite: cope with Graphite/InfluxDB being definitively down while reporting module is enabled

### ISSUE THREAD

**Issue by kudoueiji** [gatling/gatling#3456]
There are times when I use the real-time monitoring function and I do not use it.

Although I did not use real-time monitoring, I ran a long time simulation with the following settings.(Influx DB is not running.)

gatling.conf
  gatling.data.writers = [console, file, graphite]

After several hours, OutOfMemmoryError occurred and Gatling stopped.

After checking the heap dump, there were a lot of Metrics data in theStash field of TCPsender(To be exact, akka.actor.StashSupport#theStash field), accounting for over 90% of the heap.

After running the simulation, I also tried activating Influx DB before OutOfMemory occurred.
I expected that the Metrics data remaining in the heap will be registered with Influx DB, but it did not.

It is very painful to redo a long simulation with a setting mistake not directly related to load generation.
I have not fully understood the specification of TCPSender,
I think that it is better to set the upper limit of the Metrix data size to hold by default.

The procedure I tried is as follows.
1.  Download gatling-charts-highcharts-bundle-2.3.1-bundle.zip
2.  Change writers setting in gatling.conf.
  data {
    writers = [console, file, graphite]
3. Change the JVM option of gatling.bat
  -Xmx256m(to make OOM generation faster)
4. Perform the following load setting for arbitrary simulation
  setUp(scn.inject(rampUsers(345600) over (172800 seconds)))
5. Run simulation using gatling.bat

**Comment by slandelle** [comment]
TCPSender tries to cope with connectivity loss.

> I think that it is better to set the upper limit of the Metrix data size to hold by default.

Why not. Then, forcefully kill run?

Now that FrontLine provides way more powerful reporting capabilities than the Graphite integration, we don't plan on investing time on it, except for critical issues.
Contributions mostly welcome!

**Comment by slandelle** [comment]
Idle for a long time. Will reopen if there's some activity
