### ISSUE TITLE
Awkward assertion message in certain cases

### ISSUE THREAD

**Issue by ZoeThivet** [gatling/gatling#3458]
In a scenario, we have this kind of assertion:

global.successfulRequests.**percent.gte**(x)

In this kind of assertion, the message may be:

> Global: percentage of successful requests is **greater than or** equal to 100.0 : true (if x = 100) --> which is awkward

Or :

> Global: percentage of successful requests is greater than or equal to 1000.0 : false (obviously!)

I suggest to limit percent.gte possible arguments to numbers < 100.

Yay, it's a mini tiny issue.

Gatling version: 2.2.1

**Comment by slandelle** [comment]
Sorry, I don't follow. `gte` stands for `>=` and `gt` stands for `>`.

**Comment by ZoeThivet** [comment]
Yup, and combination of "percent", "gte" and an unaccurate argument (eg: 100 or bigger) is possible.

**Comment by slandelle** [comment]
The DSL is currently generic and doesn't tell appart percentages, counts and percentiles, those are just values.

Sorry, but I'm closing this as "won't fix" as the assertion result is correct (`global.successfulRequests.percent.gte(1000)` return `false`).
