### ISSUE TITLE
Jenkins Plugin: StringIndexOutOfBoundsException on gatling project name

### ISSUE THREAD

**Issue by hannes-angst** [gatling/gatling#3459]
The following code will fetch any `global_stats.json` file in the workspace, and not only the reports.

     private List<BuildSimulation> saveFullReports(FilePath workspace, File rootDir) throws IOException, InterruptedException {
         FilePath[] files = workspace.list("**/global_stats.json");

Reproduce:
Run an manual gatling test and save it in a git repository under `reports/...`. 
Build project in Jenkins and enable track Gatling load simulation. 

     Adding report 'gatling'
     Adding report '....simulation-1525332446442'
     Adding report '....simulation-1525332451704' 
     Adding report '....simulation-1525332461824'
     Adding report '....simulation-1525332559747'
     Adding report '....simulation-1525332596495'

The first entry is from the `report/` folder. The other files are from `target/gatling/...`.

    for (FilePath reportToArchive : reportsToArchive) {
      String name = reportToArchive.getName();
      int dashIndex = name.lastIndexOf('-');
      String simulation = name.substring(0, dashIndex);

The first entry will in a `StringIndexOutOfBoundsException` exception, bevause the name does not contain a `-`:

     ERROR: Build step failed with exception
     java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at io.gatling.jenkins.GatlingPublisher.saveFullReports(GatlingPublisher.java:157)
        at io.gatling.jenkins.GatlingPublisher.perform(GatlingPublisher.java:70)
        at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
        at hudson.model.Build$BuildExecution.post2(Build.java:186)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
        at hudson.model.Run.execute(Run.java:1752)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)
     Build step 'Track a Gatling load simulation' marked build as failure
     Finished: FAILURE

**Comment by slandelle** [comment]
Sorry, but I don't follow. Why would you store a Gatling `global_stats.json` file in your repository? o_0

**Comment by hannes-angst** [comment]
@sandello I would not. It seems to be the same magic making zips and large files appear in SCMs. In this particular case, same gatling reports were stored along side the groovy file. As I raised the same question as you did (good question btw ;)) I got a quite good/creative answer: 

> I cannot send the report as zip, because the Antivirus software on the other side prevents the mail delivery, if the zip file contains js.

Yeah...

Anyways. it would be very cool if there was a way to configure the report path to prevent CI failure.

**Comment by slandelle** [comment]
The JSON files are internals (they aren't documented) and are only used by the Jenkins plugin.
If your users really want to store test reports in the same git repo as the test sources (which we agree is wrong, Git is not Dropbox nor Confluence):

* if they just need the HTML reports, you can just remove the JSON files
* otherwise (meaning you use them for something else that isn't supported), you can rename them so they don't clash with supported intended usage.

From my point of view, this is not an issue but a misusage, so closing as "won't fix".
