### ISSUE TITLE
Not possible to pass  credentials (username,pwd) with file based MQ-JNDI

### ISSUE THREAD

**Issue by brandshaide** [gatling/gatling#3464]
Version of Gatling being used: 2.3.0 

I do have a JMS scenario against a IBM MQ using a file based MQ-JNDI in conjunction with a `bindingsfile` containing all required infomation about my MQ objects (e. g. Hostname, Channel etc.) 
From a security perspective, of course IBM does not allow to have values for username/password in the `bindingsfile` which is just a plain text file. 

So when starting the scenario, the connection attempt is being desclined. 
I'd expect the JNDI lookup to pass values for username/pwd while establishng the ConnectionFactory like so: 

```
QueueConnectionFactory qcf = (QueueConnectionFactory) ctx.lookup("myQCF");
QueueConnection qc = qcf.createQueueConnection(userID, password);
```

This is my scenario: 

```
import io.gatling.core.Predef._
import io.gatling.core.structure.ScenarioBuilder
import io.gatling.jms.Predef._
import io.gatling.jms.protocol.JmsProtocolBuilderBase.connectionFactoryName

import scala.concurrent.duration._

class GPRSForwarderTest extends Simulation {

  val JNDI_CONTEXT = "com.sun.jndi.fscontext.RefFSContextFactory"

  val DEFAULT_QCF_NAME = "GPRSF"

  val message254 = "00001100E033102C20EBB51CC1C036EFFFF00010002323802000200FE05001400000000FFFFFFFF01FFFFFFFFFFFFFFFFFFFFF10F37298C"



  val jmsConfig = connectionFactoryName(DEFAULT_QCF_NAME)
    .url("file:///Users/brandsheide/Documents")
    .credentials("mqm", "mqm")
    .contextFactory(JNDI_CONTEXT)
    .listenerCount(1)
    .usePersistentDeliveryMode

    println("filepath = " + jmsConfig)


  val scn = scenario("Load testing GPRS InboundQueue").repeat(1) {
    exec(jms("F&F testing").send
      .queue("COMPANY.GPRS_MESSAGES.QUEUE")
      .textMessage(message254)
    )
  }
```
Apparently the values being passed with `.credentials("mqm","mqm")`are being ingored. 
As of now the only way to run load tests against IBM MQ is to deactivate authentication (?)

**Comment by slandelle** [comment]
In Gatling 2.3, connecting to queues is [anonymous by default](https://github.com/gatling/gatling/blob/2.3/gatling-jms/src/main/scala/io/gatling/jms/protocol/JmsProtocolBuilder.scala#L44). This feature is being dropped in Gatling 3 and connecting will always use provided credentials if present.

**Comment by brandshaide** [comment]
@slandelle thanks, when is Gatling 3.0 goint to be released? And If I'd like to fix this on my instance of v. 2.3 I'll just have to 

`anonymousConnect: Boolean = true` to `false` instead? 

Or, another way, set `def disableAnonymousConnect = copy(anonymousConnect = false)` to `true` - compilele - and invoke the scenario again? Thanks for  your support.

**Comment by slandelle** [comment]
> when is Gatling 3.0 going to be released?
Hopefully first RC in July.

disableAnonymousConnect

**Comment by slandelle** [comment]
Connect is never anonymous in Gatling 3, and AFAIK, there's no reason to make this behavior configurable.
