### ISSUE TITLE
RawFileBody Only Works With Absolute Paths

### ISSUE THREAD

**Issue by JimTheMan** [gatling/gatling#3469]
I'm using Gatling 2.3.1, and whenever I use **_RawFileBody_** it cannot find the path I have entered even though it is a valid path. It works when I use absolute paths, but this is terribly fragile and a total nightmare for sharing code across computers / developers / teams. Is it really that difficult to support relative paths??

**Comment by slandelle** [comment]
Yes, it really is. And it's completely worthless too as we also resolve from classpath.

**Comment by JimTheMan** [comment]
Thanks, but what do you mean by "resolve from classpath"? Do relative paths work or not?
