### ISSUE TITLE
Add the ability to note "check" failures in assertions.xml

### ISSUE THREAD

**Issue by Will-Sommers** [gatling/gatling#3471]
Ask: 
Would the project maintainers be open to contributions which allow failures from both assertions as well as checks to report in jUnit. We are looking at using Gatling for both our load tests as well as functional tests, however, it appears that the only way to report a test as succeeding or failing would be to log the console output to a file and then parse it for the "failed 3 tests" output.

I'm not very familiar with Scala but would be open to digging into the project to add hooks to allow for the option to log both "checks" as well as "assertions" in jUnit output. Is this something that y'all would be open to? 

Thanks!

**Comment by slandelle** [comment]
That's something we might consider in the Entreprise version.
Right off the top of my head, I suspect this is not feasible in the OSS version without breaking tons of things.
Then, feel free to give it a try and ping we you have something you'd like to show.

Cheers

**Comment by Will-Sommers** [comment]
I'm relatively new to this project — are there two repos, one for enterprise and one for OSS?

**Comment by slandelle** [comment]
Yes. And the Entreprise version is both special versions of the Gatling binaries, plus a back-end named FrontLine.

**Comment by slandelle** [comment]
Someday, we might want to have a full blown support for functional testing. Then, the effort won't be to just hack the assertions.xml file.
