### ISSUE TITLE
Increasing concurrent users every minutes until errors

### ISSUE THREAD

**Issue by kewubenduben** [gatling/gatling#3475]
Is it possible to have a test run where I can have increasing concurrent users every minutes until I get a certain amount of errors?

I'm trying to stress test my servers but I can't seem to find a way from the samples which can do this.

The goal is to identify how many concurrent users my server can handle until it crashes by having an increasing amount of  active users every minute. It will then stop until I get to receive about 50 or more  5xx, 4xx, errors.

**Comment by slandelle** [comment]
No
