### ISSUE TITLE
Gatling Jenkins Plugin - Multiple gatling runs with the same name in the same build are not supported

### ISSUE THREAD

**Issue by pscosta** [gatling/gatling#3479]
As reported by ShettyA here: https://github.com/gatling/gatling/issues/1162#issuecomment-73151131
Multiple gatling runs with the same name in the same build are not supported.

"On running test twice in single run, I do see two reports on clicking 'Gatling' via the specific jenkins build but both reports contains the latest run test report and I totally miss the first test report."

Proposed PR: https://github.com/jenkinsci/gatling-plugin/pull/17

**Comment by slandelle** [comment]
I suspect your PR is wrong, see comment there.

**Comment by pscosta** [comment]
I've updated my PR. I think this time it won't cause any side effects.

**Comment by slandelle** [comment]
@pscosta Thanks!

**Comment by slandelle** [comment]
I've just release 1.2.4
