### ISSUE TITLE
Graphite: different results in InfluxDb and html reports

### ISSUE THREAD

**Issue by TrickyDoodle** [gatling/gatling#3483]
I use gatling 2.3.1 and influxdb 1.5.4 for real-time results monitoring.

I've faced the problem that not all results apeares in influxdb, even if the test consist of only one VU and several api calls. Moreover, time metrics also differes.

I launch gatling / Influxdb from my localhost, so this should not be a network problem. By the way, I tryed to use both tcp and udp, but the result was the same.

![4f543cda75c9e5fdcafe9c69623ef8ba](https://user-images.githubusercontent.com/849197/42951298-2a9cfa0c-8b76-11e8-9a4c-d3f55da29a40.png)

I have:

1) Gatling html report. 
2) Gatling console output after test ended.
3) Data that a exported from Influxdb to excel file and filtered by request name and status = 'ok' and count != '0'. As you can see, in influxdb one request is missed. If I start a longer test, I will have more missed requests.

I've tryed a dozens times even with previous version of gatling (2.3.0) and influx (1.4.1), but nothing changes. 

Does anyone encountered the same behaviour? 

Thanks.

**Comment by slandelle** [comment]
We from GatlingCorp no longer use the Graphite integration, now that we offer FrontLine which is far superior. So I'm afraid you'll have to investigate yourself.

You could try compile 2.3 branch and add some logs to check [if the stats get properly serialized](https://github.com/gatling/gatling/blob/2.3/gatling-metrics/src/main/scala/io/gatling/metrics/GraphiteDataWriter.scala#L109).
You could also use Wireshark to check what happens on the wire.

Note that you should probably stick to TCP as UDP doesn't guarantee delivery.

**Comment by TrickyDoodle** [comment]
I'm sad to hear that. InfluxDb is a nice solution for this. 

I noticed that data is always lost if I use  .pauses(disablePauses) in setUp section. If switch it to .pauses(exponentialPauses) in most cases this helps. Looks like gatling stop sending data if a test is already ended. 

And one more [picture](https://i.gyazo.com/a073922ca6c2737e1c3700eaefe546f9.png) - times are different in html and in influx (I sorted all request of the same type by max desc). What could be a reason of this overhead?

**Comment by slandelle** [comment]
> I noticed that data is always lost if I use .pauses(disablePauses) in setUp section. If switch it to .pauses(exponentialPauses) in most cases this helps.

Are you sure you're not saturating your box because you're sending too many requests for your hardware, so the requests to InfluxDB can't get through?

> Looks like gatling stop sending data if a test is already ended.

Absolutely, Gatling shuts down after trying to send last batch of stats.

> times are different in html and in influx

Reports uses t-digest and component that send to Graphite uses HdrHistogram. Maybe t-digest rounds max to closest bucket. We're talking a difference of 0.14% here, which is acceptable IMO.

**Comment by TrickyDoodle** [comment]
> Are you sure you're not saturating your box because you're sending too many requests for your hardware, so the requests to InfluxDB can't get through?

Yes, I'm sure. Even if test consists of 10 requests and the pauses are disabled, some requests are lost. 

> We're talking a difference of 0.14% here, which is acceptable IMO.

Maybe you right, but sometimes the difference a little bit more. I'll keep an eye on that. 

Then tell me please - are html reports reliable? I mean, if for some reason test fails - e.g. as your mentioned due to saturation of machine from which I will produce load -  will be a report generated?

**Comment by slandelle** [comment]
> Yes, I'm sure. Even if test consists of 10 requests and the pauses are disabled, some requests are lost.

That's the opposite: if you disable pauses, you'll increase throughput and generate a higher load that could saturate your OS/hardware.

> Then tell me please - are html reports reliable?

Reports are more reliable than InfluxDB when it comes to percentiles. InfluxDB can only store numbers, hence percentile values, and will compute average percentiles as soon as you need to aggregate (overall value for a given time window, reducing db records into a smaller number of chart plots, etc) which is completely wrong.

Injector host saturation will cause stats to be wrong, whatever the reporting engine. But then reports won't suffer from network saturation as it write on local disk and not on network sockets.

**Comment by slandelle** [comment]
Regarding HTML reports data correctness, you can compare reports with data in simulation.log, should be pretty straightfoward for max.

**Comment by slandelle** [comment]
Closing for now. Feel free to ping if you can provide more information.

**Comment by asbaghel** [comment]
How to save stats.js in influxdb
