### ISSUE TITLE
How to run multiple scenarios each with own set of users sequentially

### ISSUE THREAD

**Issue by hmble2** [gatling/gatling#3488]
Sorry, but couldn't see proper response anywhere so adding it here: I have two scenarios scn1 and scn2 that needs to run sequentially, however, scn1 should ramp up to x1 users in t1 time, while scn2 should ramp up to x2 users in t2 time. How to achieve that in single simulation. Following solutions run chains sequentially but with common users:
var scn = scenario("combined scenario").
           .exec(chain1)
           .exec(chain2)

def chain1 = exec(...)...
def chain2 = exec(...)...

Could you please let me know how to run two scenarios sequentially but with each having own user set:
scn1.inject(rampUsers(x1) over (t1 millisecond) then 
scn2.inject(rampUsers(x2) over (t2 millisecond)

**Comment by slandelle** [comment]
That's not possible atm within one single Simulation. You'd have to run 2 Simulations sequentially.

Now, please use the community mailing list for questions, not the bugtracker.
