### ISSUE TITLE
Reports: Misleading/erroneous statistics with small amount of requests in a bucket (< 0.01%)

### ISSUE THREAD

**Issue by EugeneAbramchuk** [gatling/gatling#3497]
Hi guys, I just found out the reports can be a bit misleading when I have small amount of slower requests.

My gatling.conf buckets are:
- t < 1000ms
- 1000ms < t < 4000ms
- t > 4000ms

Most of the requests (99.99%) are the fast ones and fall into the first bucket, however global response time chart misreports that there are no slow requests, when there are some.
![](https://i.imgur.com/G9QxIOx.png)

The right pie chart also shows 100% requests < 1000ms, which does not seem right too. I appreciate there is a likely issue of rounding in this case, however it does not explain why the bar chart shows 0 requests > 4000 ms.

Attaching the simulation.log.

Gatling 2.3.1 (same results on both Ubuntu or Windows)
JDK 1.8u161
Scala 2.12.4
[simulation.log.zip](https://github.com/gatling/gatling/files/2197638/simulation.log.zip)

**Comment by slandelle** [comment]
Thanks for reporting.

I was able to get the proper count displayed, but it's sill completely dominated so the column height is still 0.

<img width="630" alt="dominated series" src="https://user-images.githubusercontent.com/849197/42781324-1a34cd02-8946-11e8-9e7f-32fcd8476e5f.png">
