### ISSUE TITLE
Reports: Reports don't display Groups that don't contain any request

### ISSUE THREAD

**Issue by jgaalen** [gatling/gatling#3499]
We have a group with a custom request (so not using the .http method). Also enabled useGroupDurationMetric = true in the gatling.conf so the total duration of the group is measured.
We can see the group is measured just fine in the simulation log with a good start and end timestamp. But after the report is generated there are no metrics of that specific group.

So also groups without native http requests should be generated and visible in the report. This makes it easier to use custom requests or anything else that takes time and you want to capture and measure that in a group.

**Comment by jgaalen** [comment]
[customgroup.tar.gz](https://github.com/gatling/gatling/files/2205123/customgroup.tar.gz)

I've added a tar.gz with the simulation.log and the generated report. I've renamed the names to bogus data but it shouldn't matter. The 'Custom Group' is not used in the report, but it's in the simulation log with start/end timestamps, but without sub requests.

**Comment by slandelle** [comment]
Your use case if very specific (and quite hacky) so it's not a high priority on our side and I don't think we'll have time to work on this any time soon. A contribution would be very welcome.

The problem is most likely with the way we compute the hierarchy in `StatsReportGenerator`.

**Comment by slandelle** [comment]
FWIW, next FrontLine 1.9.0 will support such empty groups.

**Comment by slandelle** [comment]
Closing for now due to lack of activity.
