### ISSUE TITLE
Gatling throttle not working for injecting two scenarios for user

### ISSUE THREAD

**Issue by thivyae** [gatling/gatling#3503]
```scala
setUp(
    scn1
     .inject(constantUsersPerSec(800) during (60 seconds))
    .throttle(
        reachRps(500) in (10 seconds),
        holdFor(2 minutes)).protocols(httpConf),
scn2
      .inject(constantUsersPerSec(4000) during(60 seconds))
      .throttle(
        reachRps(1000) in (10 seconds),
        holdFor(2 minutes)).protocols(httpConf)
    )
```

I want this code to run both the scenarios and generate 500 rps for 2minutes for scn1 and 1000rps for scn2.But it generates only 9000 requests in total.

Any idea how to make it run for (500 * 60 * 2) +(1000 * 2 * 60) i.e. 180000 rps in total for total two minutes?

**Comment by slandelle** [comment]
Please use the community mailing list for questions, not the bug tracker.

`throttle` only applies a limit on the load that would be generated otherwise. You have to make sure that your virtual users generate enough load for long enough.
