### ISSUE TITLE
Rate and duration is buggy

### ISSUE THREAD

**Issue by jgaalen** [gatling/gatling#3504]
This is my inject schedule:

      .inject(rampUsersPerSec(0) to (0.4) during (300),
        constantUsersPerSec(0.4) during(1800)
      )

So you expect it's ramping up users linear to a rate of 0.4 and then hold that for 1800 seconds with a total execution time of 300 + 1800 = 2100 seconds.

What is actually happening:

After the rampup it's running at a constant rate of 0.5 users per second instead of 0.4
The total duration was 1700 seconds instead of 2100
The total started users was correct (780)   (rampup users =~ 0.2 * 300 = 60 + constant of 0.4*1800 = 720 makes a total of 780.

Rampup time was 260
Constant period was 1440 

It seems that 0.4 is a value it cannot handle and will round it to 0.5

**Comment by slandelle** [comment]
I've run a test with master and got the proper injection duration, so I suspect this is a dup of #3485.

<img width="920" alt="inject" src="https://user-images.githubusercontent.com/849197/43348010-35038f5a-91f8-11e8-8ce5-5086da074003.png">
