### ISSUE TITLE
Content-Type with a semicolon truncates the remaining value

### ISSUE THREAD

**Issue by karthikraman22** [gatling/gatling#3506]
Hi,
I am trying to execute a simulation with "Content-Type" having the value as "application/json; charset=utf-8". However it looks like gatling is dropping the charset=utf-8 and sending only the "application/json" part. Is this an issue or does it work as designed?

package avs;
  
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class AVSSimulation extends Simulation {

  val httpConf = http
    .baseURL("http://localhost:12345") // Here is the root for all relative URLs
    .doNotTrackHeader("1")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")

  val headers_10 = Map("Content-Type" -> "application/json; charset=utf-8", "Accept" -> "application/json; charset=utf-8", "Keep-Alive" -> "150") // Note the headers specific to a given request

  val scn = scenario("avs-fetch") // A scenario is a chain of requests and pauses
    .pause(5)
    .exec(http("request_10") // Here's an example of a POST request
      .post("/AVInqService/Fetch")
      .headers(headers_10)
      .body(RawFileBody("/tmp/avs.txt")).asJSON)

  setUp(scn.inject(atOnceUsers(1)).protocols(httpConf))
}

**Comment by slandelle** [comment]
asJson is a shortcut for setting Content-Type as application/json so you’re overiding.
