### ISSUE TITLE
We are not able to automate multiple Simulation run process through gradle build

### ISSUE THREAD

**Issue by SrikanthKarkala** [gatling/gatling#3509]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [ ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [x] Check that you can reproduce your issue with latest Gatling version
  * [x] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [x] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x] Explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment]
The grade plugin is not an official component developed by us. Please ask directly there: https://github.com/lkishalmi/gradle-gatling-plugin
