### ISSUE TITLE
GATLING: I am getting error message "Unknown channel option 'TCP_NODELAY'" in command prompt during recording and not able to record i.e. no script files are generated. Could anyone help me ASAP?

### ISSUE THREAD

**Issue by TanyaMt** [gatling/gatling#3520]
I tried to start recording and after that I got the following warning message. ![image](https://user-images.githubusercontent.com/43061270/45206167-017e7e00-b28d-11e8-8f61-ccbfff71012d.png)
![image](https://user-images.githubusercontent.com/43061270/45206176-0b07e600-b28d-11e8-8921-dd8e047e3c46.png)
What is a reason of such problem?
Please, help me with solution.

**Comment by slandelle** [comment]
> Unknown channel option 'TCP_NODELAY'"

This is a warn, not a blocking error.

Please use the community mailing list for questions, not the bugtracker.
