### ISSUE TITLE
HTTP: implement NTML/Kerberos/Spnego support

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3525]
Gatling 2 tried to support NTLM/Kerberos/Spnego and exposed what was available in AsyncHttpClient.

Making things clear: this part of AHC has never tested against a real NTLM platform as none of the successive committers could get their hands on such Windows enterprise environment.

Discussions on the community mailing list show that some people were able to get something running with considerable amount of hacks.

In Gatling 3, NTML support is removed.

It will be re-introduced if us from GatlingCorp can get our hands on such environment. If you're a company with such environment and in dire need of NTLM support, consider sponsoring.

**Comment by turgayh** [comment]
somebody can you help us please!

**Comment by slandelle** [comment]
@turgayh If you're interested in contracting with us and sponsoring the implementation of this feature, please reach out at contact@gatling.io.

**Comment by slandelle** [comment]
Unlikely to be ever implemented, given those authentication schemes are now legacy in favor of SAML and OIDC.
