### ISSUE TITLE
HTTP: Usage of InputStreamBody forces Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by alisiikh** [gatling/gatling#3526]
Hello,

I have a problem with uploading a reasonably big sequence of bytes (10GB) via Gatling as the receiving server doesn't support `Transfer-Encoding: chunked` and I don't want to physically have those 10GB on my disc.

I have a randomly generated `InputStream` that is backed by Scala's `Stream` which produces bytes until the size limit is reached, so I know the contentLength in advance, and so I need to somehow pass the contentLength along.

`InputStreamBody` should be used in this case which doesn't allow to specify the contentLength for the body, and Netty not knowingly adds a header `Transfer-Encoding: chunked`.

We can tell Netty what's the content length is. These are the places I spotted that should improve it:
```scala
// file: Body.scala, line: 75
// add optional contentLength to InputStreamBody
case class InputStreamBody(is: Expression[InputStream], contentLength: Option[Long] = None) extends Body

// file: HttpRequestExpressionBuilder.scala, line: 62
def setBody(body: Body): Validation[AhcRequestBuilder] = 
  body match {
    ...
    case InputStreamBody(is, maybeContentLength) => 
      is(session).map(is => 
        requestBuilder.setBody(
          // use other constructor from InputStreamBodyGenerator 
          // that propagates contentLength to the exact HTTP request
          // if None, Netty will use Transfer-Encoding: chunked as before
          new InputStreamBodyGenerator(is, maybeContentLength.getOrElse(-1L))
      )
  }
```

Can we extend the InputStreamBody to accept additional parameter: `contentLength: Option[Long]`?

Using the latest available version: 2.3.1.
I can potentially do a pull request for that.

Thanks for your time guys! 
Gatling is awesome, love it!

**Comment by slandelle** [comment]
> Can we extend the InputStreamBody to accept additional parameter: contentLength: Option[Long]?

Sounds reasonable

> Using the latest available version: 2.3.1.

We're not sure we'll have a 2.3.2, and if we do, it will only ship bug fixes.
Please send PR against master.
We'll be releasing first release candidate of Gatling 3 next Tuesday.

> Gatling is awesome, love it!

Thanks :)

**Comment by slandelle** [comment]
Closing then.
Thanks for your feedback

**Comment by alisiikh** [comment]
Yep it works! 
Tested my 'big file upload' scenario with the latest 3.0.0-SNAPSHOT master version, adding Content-Length header does the trick.

So waiting for the RC, thanks! :)
