### ISSUE TITLE
HTTP: resources computation doesn't account for data captured in main request with 3.0.0-RC1

### ISSUE THREAD

**Issue by black-snow** [gatling/gatling#3529]
My use case is this:  
When I hit `/` I need to extract a `jsessionid` from somewhere in the response body. I then have to use this `jsessionid` within some of the `resources` to that request.

The following worked fine in 2.3.x:

```scala
http("Home")
    .get("/")
    .headers(...)
    .check(regex(""".*;jsessionid=([A-Za-z0-9]+).*""").saveAs("jsessionid"))
    .resources(
        http("request_1")
        .get("/use/jsessionid/here;jsessionid=${jsessionid}")
    )
```

In _3.0.0.-RC1_ the second request fails with `...: Failed to build request: No attribute named    
 'jsessionid' is defined`.

But even if I add
```scala
exec{session => println("XOXOXOXOXO"); session.set("jsessionid", "whatevs"); session}
```
I end up with the same error and the second request not being executed while the XO's are being printed.

**Comment by Neoware** [comment]
Hi,
Thank you for your feedback ! I'm investigating on this issue. The first example should work but it is sure that 
```scala
exec{session => println("XOXOXOXOXO"); session.set("jsessionid", "whatevs"); session}
```
shouldn't be working since you are not returning session with the jsessionid attribute inside (don't forget that session is immutable and "set" returns a new session)

**Comment by black-snow** [comment]
Damn, should be

```scala
exec{session => println("XOXOXOXOXO"); session.set("jsessionid", "whatevs")}
```

right?

**Comment by Neoware** [comment]
yeah that should work when the bug is fixed :)

**Comment by black-snow** [comment]
Aight, let me know if you need anything.

**Comment by slandelle** [comment]
Thanks for your feedback!
