### ISSUE TITLE
Core: JsonPath parser regression with != filter operator not wrapped with spaces

### ISSUE THREAD

**Issue by TrickyDoodle** [gatling/gatling#3539]
I am using gatling 2.3.1 atm, but take an eye to 3.0RC2.

Encountered the following issue: 

I have a request:

```
  val request1 = exec(http("request1")
    .post("/request1")
    .body(StringBody("""{
                    // here is body
                    } """)).asJson
    .check(jsonPath("$.Response.filters[?(@.name!=\"name1\" && @.name!=\"name2\" && @.name!=\"name name3\")].name").findAll.saveAs("myVar")))
```

Response body of this request:

```
{
	"Response": {
		"filters": [{
				"name": "name1",
				"values": [{
						"value": "value1"
					}, {
						"value": "value2"
					}
				]
			}, {
				"name": "name2",
				"values": [{
						"value": "value1"
					}, {
						"value": "value2"
					}
				]
			}, {
				"name": "name name3",
				"values": [{
						"value": "value1"
					}
				]
			}, {
				"name": "name name4",
				"values": [{
						"value": "value1"
					}, {
						"value": "value2"
					}
				]
			}
				
		]
	}
}
```

The problem is that in v2.3.1 everything is going smoothly - it saves the value "name name4" in myVar variable, and in 3.0.0RC2 the following error appeares: 

`14:13:46.442 [ERROR] i.g.h.e.r.DefaultStatsProcessor - Request: /request1: KO jsonPath($.Response.filters[?(@.name!="name1" && @.name!="name2" && @.name!="name name3")].name.findAll.exists extraction crashed: ')]' expected but '=' found
`

**Comment by slandelle** [comment]
Indeed, there's a small regression. Until 3.0.0-RC3, you can add whitespaces around the operator: `foo != "bar"` instead of `foo!="bar"`.

**Comment by TrickyDoodle** [comment]
Thank you Stephane, I confirm - adding white spaces is a working workaround.
