### ISSUE TITLE
Core: Jodd crash on `\"`

### ISSUE THREAD

**Issue by TrickyDoodle** [gatling/gatling#3541]
Hi, I faced the following issue in 3.0.0RC2.

I have a check in my request:

`.check(jsonPath("$.ResponseHeader.responseCode").find.is("200"))`

Sometimes, I get the following error:

Request:
/request123: KO jsonPath($.Response.responseCode).find.is(200) preparation crashed: Jodd failed to parse into a valid AST: j.l.ArrayIndexOutOfBoundsException: 12996

As I have this check in every request my assumption is that error depends on the size of response body. Can't remembered anything similar in 2.3.1.

I uploaded full response on which an error occures to [google disk](https://drive.google.com/file/d/1QF_Xg6-Ot0QVqKYQNgoiqp1phrgXr35f/view?usp=sharing).

**Comment by slandelle** [comment]
Thanks, your sample helped a lot!
This is indeed a Jodd issue: https://github.com/oblac/jodd/issues/637
