### ISSUE TITLE
[3.0.0 RC-2] Incorrect work of incrementConcurrentUsers

### ISSUE THREAD

**Issue by Elufimov** [gatling/gatling#3542]
```scala
class SearchSimulation {
  val rate = incrementConcurrentUsers(100)
    .times(100)
    .eachLevelLasting(5 minutes)
    .startingFrom(1)
  setUp(
    scenario.inject(rate)
  ).protocols(httpConf)
    .maxDuration(1 hour)
}
```
In this simulation I expect following behaviour:
1) Simulation starts with 1 user
2) Every 5 minutes another user will be added to the simulation
But this is not how it works:
1) Simulation starts with 1 user  
2) After 5 minute all 100 users was added
![](http://img.parcsis.net/i/543eb56e281f698dd11701fa3fc67303.png)

**Comment by slandelle** [comment]
No, it works as expected: incrementXXX takes the value of the increment so here you are adding 100 more concurrent users every 5 min.
We'll improve the doc, and we also also a blog post coming.

**Comment by Elufimov** [comment]
Oh, I see it now. Thx!
