### ISSUE TITLE
[2.3.1] Instant timeouts

### ISSUE THREAD

**Issue by black-snow** [gatling/gatling#3545]
I'm switching back and forth between 2.3.1 and 3 in order to get gatling to follow my orders.

Back in 2.3.1 I experience instant timeouts. When I take a look at the `gatling.conf` there's no timeout below 10 seconds. Yet gatling is throwing timeouts at me just 2-3 seconds after start.

Also, when I take a look at the report the mean and max reponse times are way below the 20 seconds I set in the config. How can that be?

![timeout](https://user-images.githubusercontent.com/579733/46213210-464f7f00-c338-11e8-9fa4-0a227e536c23.png)

The error message is lying. I see traffic hitting my server and it's not overwhelmed in terms of load (CPU/MEM/IO).

*gatling.conf* - rest of the file is unmodified
```
requestTimeout = 20000                          # Timeout of the requests
```

The number of users I inject seems to matter - no errors for one or a handful of users.

```scala
    final val httpProtocol = http
        .baseURL("http://xyz")
        .inferHtmlResources(WhiteList("""XXX"""), BlackList(""".*\.google\.de.*""", """.*\.google\.com.*""", """.*maps\.googleapis\.com.*"""))
        .acceptHeader("*/*")
        .acceptEncodingHeader("gzip, deflate")
        .acceptLanguageHeader("de,en-US;q=0.7,en;q=0.3")
        .userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 - Gatling")
        .disableCaching

    // feeders
    final val userFeeder = csv("users_tokens.csv").circular

    val scenarioLogin = scenario("Login Only")
        .during(1 minute) {
            exec(flushHttpCache)
            .exec(Home.home)
            .feed(userFeeder)
            .exec(Home.doLogin)
    }


    setUp(
        scenarioLogin.inject(
            atOnceUsers(50),
        )
    )
    .protocols(httpProtocol)
```

`Home.home` etc. just look like this:
```scala
val home = http("Home")
    .get("/")
    .headers(Headers.html)
    .check(regex(""".*;jsessionid=([A-Za-z0-9]+).*""").saveAs("jsessionid"))
    .resources(
        http("request_1")
        .get("/xyz"),
        ...
```

My client machine has a recent i5, enough memory and a gigabit ethernet connection to the system under test.

**Comment by slandelle** [comment]
Please try again with 3.0.0-RC3 next week. I don't think we'll investigate on Gatling 2.

**Comment by zeburek** [comment]
This code is perfectly working on 2.3.1:
```scala
package test

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class TestSimulation extends Simulation {
  val httpConf = http.baseURL("https://httpbin.org")

  val httpMethods = exec(
    http("Request GET")
      .get("/get")
  ).exec(
    http("Request POST")
      .post("/post")
      .body(StringBody("""{"test":1}""")).asJSON
  ).exec(
    http("Request PUT")
      .put("/put")
      .body(StringBody("""{"test":1}""")).asJSON
  ).exec(
    http("Request PATCH")
      .patch("/patch")
      .body(StringBody("""{"test":1}""")).asJSON
  ).exec(
    http("Request DELETE")
      .delete("/delete")
  )

  val scn = scenario("BasicSimulation")
    .exec(
      httpMethods
    )

  setUp(
    scn.inject(atOnceUsers(1))
  ).protocols(httpConf)
}
```

And on 3.0.0-RC2, with changes in `asJson` and `baseUrl` almost fails on requsting not first request - every next request produces a timeout exception. Every child request performs a parent request - so if I run this code - it makes not 5 requests, it made 15 requests, where 10 of them will be failed

**Comment by black-snow** [comment]
Could be correlated.

@slandelle So 2.x has reached its EoL?

**Comment by slandelle** [comment]
@black-snow We might release a 2.3.2 for our of our customers with the fix he needs (waiting for his feedback), but aside for this special case, 2.x is indeed reaching EOL.

**Comment by slandelle** [comment]
> Back in 2.3.1 I experience instant timeouts.

Impossible to investigate without a reproducer. Also, as explained above, we won't be spending time investigating on 2.X as it's reaching EOL.
Could you please upgrade to RC3 (to be released tomorrow) and report again if you can still reproduce there (and provide a way for us to reproduce)?

> And on 3.0.0-RC2, with changes in asJson and baseUrl almost fails on requsting not first request - every next request produces a timeout exception.

@zeburek I suspect you have an Exception somewhere and you hit #3546. Anyway, your problem is not related to @black-snow 's original issue. Please also upgrade to RC3 and then open a dedicated issue if you can still reproduce and provide a reproducer.
