### ISSUE TITLE
Download page says 3.0.0-RC3 (2nd October 2018)

### ISSUE THREAD

**Issue by alex7071** [gatling/gatling#3549]
Expected: RC3 version
Actual: The file downloaded is gatling-charts-highcharts-bundle-3.0.0-RC2-bundle.zip

This RC2 throws an Request timeout exeption for everything even the BasicSimulation that comes packed in the bundle.
It looks like the latest build is not in the download page at https://gatling.io/download/
Edit: spelling

**Comment by slandelle** [comment]
> Expected: RC3 version

Release in progress, please wait a few minutes, we haven't even made the announcement yet :)

> This RC2 throws an Request timeout

Please try RC3

**Comment by alex7071** [comment]
Oh, my bad.

**Comment by slandelle** [comment]
No pro, thanks for your feedback. Everything should be online now.
