### ISSUE TITLE
For some `baseURL`s virtual users are stalling

### ISSUE THREAD

**Issue by dmand** [gatling/gatling#3550]
Consider the following simulation:

```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class MySimulation extends Simulation {
  val httpConf = http
    .baseURL("http://computer-database.gatling.io")

  val scn = scenario("BasicSimulation").forever{exec(http("request_1").get("/"))}

  setUp(
    scn.inject(atOnceUsers(10))
  ).protocols(httpConf).maxDuration(30 seconds);
}
```
This simulation gives me ~200rps and everything's good.

But if i change `baseURL` to, let's say, `"http://example.com"`,  i can see much weirder picture. 10 requests are made in the first few seconds, after that all virtual users are doing nothing (though they are marked as `active`) until they are killed by the duration limit.

I'm using Gatling 2.3.1 CLI with the latest Ubuntu.

**Comment by slandelle** [comment]
Your request gets most likely cached because the response headers so no actual HTTP request is sent.

PS: you should stick to genuine Gatling components.
PPS: Gatling 2 is about to reach EOL as we’re releasing Gatling 3 candidates.

**Comment by dmand** [comment]
Ok, can you suggest a way to verify that the issue is indeed with ? And how can i tell a load testing tool to not cache HTTP requests?

Also, i'm sorry, but what do you mean on "genuine" Gatling components? This simulation is pretty much copied from Gatling's quickstart docs with a few tweaks.

Also, releasing Gatling 3 will make Gatling 2 completely unsupported? That doesn't sound really nice. Do you have a writeup on transitioning from 2 to 3 somewhere?
