### ISSUE TITLE
NoClassDefFoundError while launching gatling.bat

### ISSUE THREAD

**Issue by sujin-sam** [gatling/gatling#3563]
Hello
I'm new to Gatling, just downloaded the gatling-high-charts-bundle 3.0.0 RC3. I have set up the JAVA_HOME and GATLING_HOME. When I launch gatling.bat, I'm getting the below error,

GATLING_HOME is set to "C:\Users\Sujin Sam\Downloads\gatling-charts-highcharts-bundle-3.0.0-RC3"
JAVA = ""C:\Program Files\Java\jdk1.8.0_131\bin\java.exe""
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

**Comment by slandelle** [comment]
Your Java installation is broken, and his is not related to Gatling. Please search on StackOverFlow for your error message.
