### ISSUE TITLE
Core: Scala 2.13 build

### ISSUE THREAD

**Issue by dsilvasc** [gatling/gatling#3566]
Scala 2.13 is now [feature-frozen](https://www.scala-lang.org/news/2.13.0-M5) and the ecosystem has [started porting to 2.13](https://github.com/scala/scala-dev/issues/563).

It would be great if Gatling 3 were able to run on Scala 2.13 as well.

**Comment by slandelle** [comment]
This won't happen for Gatling 3.0, as we're getting close to stable release. Plus we don't plan to ever cross-build.
We'll more likely aim at Scala 2.13 for Gatling 3.1 in a few months.

Note that some of our deps haven't started migrating yet:

* [ ] fastring
* [ ] spire
* [ ] boopickle
* [ ] zinc
* [ ] quicklens

**Comment by thinkerou** [comment]
any updates? thanks!

**Comment by slandelle** [comment]
@thinkerou As you can see above, not all of our dependencies are available for Scala 2.13 yet. And then, it will take use some time to migrate our own products. All in all, I expect Gatling w/ Scala 2.13 to be available near September.

**Comment by thinkerou** [comment]
@slandelle thanks 👍

**Comment by tOverney** [comment]
Where did the dependency on Fastring go?
It disappeared from your bullet list!

**Comment by thinkerou** [comment]
gatling not upgrade to scala2.13, so I don't suggest to use scala2.13

**Comment by slandelle** [comment]
@tOverney Because we're removing dep to Fastring.

**Comment by slandelle** [comment]
Answering question [here](https://github.com/sbt/zinc/issues/697#issuecomment-547332042):

We use zinc for:
* gatling-maven-plugin that can handle compilation in the absence of scala-maven-plugin, but that's something we could ditch
* gatling zip bundle that needs to be able to compile Scala code. This is not something we can ditch and I don't want to go back to the pre zinc 1.0 situation when we had to ship multiple scala libraries and deal with multiple classpaths.

**Comment by henricook** [comment]
Interesting, thanks. From my side i'm looking to somehow decouple gatling from our code base so we can keep it compiling on its own with 2.12 whilst we move everything else to the more efficient (at least in terms of compile time) 2.13

**Comment by dwijnand** [comment]
> * gatling zip bundle that needs to be able to compile Scala code. This is not something we can ditch and I don't want to go back to the pre zinc 1.0 situation when we had to ship multiple scala libraries and deal with multiple classpaths.

Is that just `ZincCompiler`?  Looks like it's an app that is run by scripts, so isn't this already fairly isolated in its current setup?  I would consider just keeping gatling-compiler supporting 2.12 only, and the rest of the Gatling can upgrade.

**Comment by slandelle** [comment]
Actually, that is how things used to work prior to zinc 1.0 when it started being cross compiled for Scala 2.11 and 2.12.

But we had to deal with multiple classpaths, both for our maven plugin (it can work with scala-maven-plugin) and our zip bundle distribution. Shipping a zinc version compiled against the same version of Gatling was a huge win for us and let us reduce a lot of complexity and reduce bundle distribution size.

I'd rather wait for Zinc to be compiled against 2.13 than revert to the previous complexity.
[Eugene said this could be possible as a sbt 1.4 or 2.0 milestone](https://github.com/sbt/zinc/issues/697#issuecomment-568535568).

**Comment by dwijnand** [comment]
As far as I can see it's only those scripts: https://github.com/gatling/gatling/search?q=ZincCompiler so I'm just confused on that part.

**Comment by slandelle** [comment]
This jar is pulled by other ones:
* https://search.maven.org/artifact/io.gatling.highcharts/gatling-charts-highcharts-bundle/3.3.1/zip
* https://github.com/gatling/gatling-maven-plugin/blob/da89a8e79620208b968352c07efdc5493c679b00/src/main/java/io/gatling/mojo/MojoConstants.java#L31

**Comment by SethTisue** [comment]
a zinc build is now available for 2.13: https://github.com/sbt/zinc/issues/697#issuecomment-613231841

**Comment by slandelle** [comment]
@SethTisue Yep, I know, I'm the one who opened this issue :)

**Comment by jozic** [comment]
maybe gatling 2.13 milestone? :)

**Comment by mikla** [comment]
Hi there! Any hope we can get 2.13 support soon?

**Comment by slandelle** [comment]
September/October probably.
Gatling 3.4.0 and FrontLine 1.12 will be the last minor versions targeting Scala 2.12.

**Comment by aphoristicartist** [comment]
Hi @slandelle. Is there any news on this track? Thank you.

**Comment by slandelle** [comment]
> Gatling 3.4.0 and FrontLine 1.12 will be the last minor versions targeting Scala 2.12.

Will be released tomorrow.

Expect Gatling 3.5.0 w/ Scala 2.13 support to be out next December/January.

**Comment by slandelle** [comment]
Just landed in master.
