### ISSUE TITLE
HTTP: Gatling modifies user defined request Content-Type

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3576]
Gatling patches Content-Type with charset attribute if it's undefined.
Even though such header is perfectly valid, some poorly implemented servers misunderstand Content-Type and mime-type and crash when Content-Type is not exactly what they expect, eg `application/json; charset=utf-8` instead of `application/json`.

Let's drop this behavior and stick to user defined value.

**Comment by patelh** [comment]
+1, this also is phantom addition since the user defined value could be used for generating signature and on server side, signature would not match since content type was modified after user defined it.

**Comment by slandelle** [comment]
dup of #3577, caused by Github being broken yesterday
