### ISSUE TITLE
Expose report generator as public interface

### ISSUE THREAD

**Issue by patelh** [gatling/gatling#3580]
I need to be able to push generated results to a DB, by exposing the report generator as public interface, I can provide a custom report generator which can push results to DB.

**Comment by slandelle** [comment]
Additional stats export fall into the scope of FrontLine.

**Comment by phpillet** [comment]
We are really sorry to hear this. We sincerely hope you will continue to use Gatling. As we explained to you earlier, our team spends time on both projects: our open-source solution and our Enterprise solution, Gatling FrontLine.
The way we decided to split our R&D is as follows: Everything related to Gatling itself, like new support protocols, will be open-sourced (eg. HTTP/2, closed workload model and new feeders features in our latest release); On the other hand, everything related to reporting and automation features is in the scope of Gatling FrontLine. Please note that our Enterprise version helps develop both projects and have a team of 7 full-time employees. We hope you understand.
Anyway, we would gladly continue this talk with you, feel free to contact us directly. We will now close this thread.
Best regards
