### ISSUE TITLE
Gatling 3.0.0 does not honor dns ttl 

### ISSUE THREAD

**Issue by Elufimov** [gatling/gatling#3581]
Right now we test new approach for load balancing with consul dns. One of consul protocols is dns, and it return service's shuffled ip addresses. I applied `-Dsun.net.inetaddr.ttl=0` and `.perUserNameResolution` from this https://gatling.io/docs/current/http/http_protocol/#hostname-resolution. Also I changed `networkaddress.cache.ttl` to 0 in `lib/security/java.security`. But nothing helped. 

I use Gatling 3.0.0-RC4 and java 8.

**Comment by slandelle** [comment]
With the set up you describe, you use a `ShuffleJdkNameResolver`.

As you can see from the [code](https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/resolver/ShuffleJdkNameResolver.scala#L33), we just use plain old `InetAddress#getAllByName` and don't cache anything, so there's no way we wouldn't honor Java props.

Please keep on investigating on your side. If you can come up with a reproducer we could use on our side, please provide it.

**Comment by Elufimov** [comment]
I found the problem. Use `forever {}` block for close workload. Combined with `atOnceUsers(1)` it leads to a situation when it looks like simulation calls only firstly resolved ip. But if I use new close model dsl `constantConcurrentUsers(1) during (30 minutes)` it leads to some weird metrics 
```
October 23rd 2018, 16:57:16.000	gatling..searchsimulation.users.allUsers.active 1 1540299436
October 23rd 2018, 16:57:15.000	gatling..searchsimulation.users.allUsers.active 5 1540299435
October 23rd 2018, 16:57:14.000	gatling..searchsimulation.users.allUsers.active 27 1540299434
October 23rd 2018, 16:57:13.000	gatling..searchsimulation.users.allUsers.active 3 1540299433
October 23rd 2018, 16:57:12.000	gatling..searchsimulation.users.allUsers.active 4 1540299432
October 23rd 2018, 16:57:11.000	gatling..searchsimulation.users.allUsers.active 19 1540299431
October 23rd 2018, 16:57:10.000	gatling..searchsimulation.users.allUsers.active 7 1540299430
October 23rd 2018, 16:57:09.000	gatling..searchsimulation.users.allUsers.active 6 1540299429
October 23rd 2018, 16:57:08.000	gatling..searchsimulation.users.allUsers.active 20 1540299428
October 23rd 2018, 16:57:07.000	gatling..searchsimulation.users.allUsers.active 20 1540299427
October 23rd 2018, 16:57:06.000	gatling..searchsimulation.users.allUsers.active 5 1540299426
October 23rd 2018, 16:57:05.000	gatling..searchsimulation.users.allUsers.active 5 1540299425
October 23rd 2018, 16:57:04.000	gatling..searchsimulation.users.allUsers.active 16 1540299424
October 23rd 2018, 16:57:03.000	gatling..searchsimulation.users.allUsers.active 1 1540299423
October 23rd 2018, 16:57:02.000	gatling..searchsimulation.users.allUsers.active 23 1540299422
October 23rd 2018, 16:57:01.000	gatling..searchsimulation.users.allUsers.active 11 1540299421
October 23rd 2018, 16:57:00.000	gatling..searchsimulation.users.allUsers.active 5 1540299420
October 23rd 2018, 16:56:59.000	gatling..searchsimulation.users.allUsers.active 14 1540299419
October 23rd 2018, 16:56:58.000	gatling..searchsimulation.users.allUsers.active 2 1540299418
October 23rd 2018, 16:56:57.000	gatling..searchsimulation.users.allUsers.active 10 1540299417
October 23rd 2018, 16:56:56.000	gatling..searchsimulation.users.allUsers.active 7 1540299416
October 23rd 2018, 16:56:55.000	gatling..searchsimulation.users.allUsers.active 1 1540299415
October 23rd 2018, 16:56:54.000	gatling..searchsimulation.users.allUsers.active 24 1540299414
October 23rd 2018, 16:56:53.000	gatling..searchsimulation.users.allUsers.active 22 1540299413
October 23rd 2018, 16:56:52.000	gatling..searchsimulation.users.allUsers.active 16 1540299412
October 23rd 2018, 16:56:51.000	gatling..searchsimulation.users.allUsers.active 10 1540299411
```

**Comment by slandelle** [comment]
> I found the problem. We use forever {} block for close workload. Combined with atOnceUsers(1) it leads to a situation when it looks like simulation calls only firstly resolved ip.

Then, behavior is expected: you have one single virtual user with HTTP pooling enabled. So there's no new DNS resolution until it needs to open an new socket, which is likely never.

> But if I use new close model dsl constantConcurrentUsers(1) during (30 minutes) it leads to some weird metrics

active != concurrent, please read doc: https://gatling.io/docs/current/general/timings/#active-users

**Comment by Elufimov** [comment]
Thx for clarification. I hope this issue will help others who could have same question.

**Comment by SBR99** [comment]
@Elufimov 
changing to constantConcurrentUsers(1) during (30 minutes) resolved your dns caching issue?

**Comment by Elufimov** [comment]
@SBR99 It was many years ago, I do not remember why we wanted to use consul dns. And besides that I do not actively use gatling for more than a two years.
