### ISSUE TITLE
Json parsers couldn't parse long values.

### ISSUE THREAD

**Issue by nazarenkAV** [gatling/gatling#3586]
When I parsed ids from Json and values are greater then 2,147,483,647 I got invalid results as '-2,147,483,500'. I could use Jackson configuration to handle this(DeserializationFeature.USE_BIG_INTEGER_FOR_INTS property in Jackson). But there is no way to put this property to the Jackson configuration.
Also I couldn't configure any Json parser in Gatling. 

I tried: 
check(jsonPath("$..IssueId").findAll.optional.saveAs("IssueIds"))
check(jsonPath("$..IssueId").ofType[Long].findAll.optional.saveAs("IssueIds"))
And got after parsing:
IssueIds -> Vector(-2137837295, -2137577295, -2137397295, -2137237295, -2137097295, -2136867295, -2136837295) instead of positive results as in response. 
It didn't help.

As a temporary method I used manual configuration:

**def objectMapper: ObjectMapper = {
    val mapper = new ObjectMapper
    mapper.enable(DeserializationFeature.USE_BIG_INTEGER_FOR_INTS)
    mapper.enable(DeserializationFeature.USE_LONG_FOR_INTS)
    mapper
  }**

.check(jsonPath("$..IssueId")(extractorFactory = new JsonPathExtractorFactory,
          jsonParsers = new JsonParsers(new Jackson(objectMapper, configuration.core.charset), new Boon, **preferJackson=true**)).findAll.optional.saveAs("IssueIds")) 

But it will be great to post this configs from config file.

Thanks!

**Comment by slandelle** [comment]
You're running an old version that's no longer maintained.
I've pushed a commit (see above) with some tests demonstrating Gatling 3 has no issues with long values.
Please upgrade.
