### ISSUE TITLE
gatling-commons declares a transitive dependency on logback

### ISSUE THREAD

**Issue by tomnis** [gatling/gatling#3593]
We are using gatling-core and have seen some slf4j warnings about multiple bindings present on the classpath. We fixed with some dependency exclusion rules, but thought I'd bring this up anyway. 

Here is a truncated output from `gradle -q dependencies`
```
|    +--- io.gatling:gatling-commons:2.3.1
<omitted for brevity>
|    |    +--- com.typesafe.scala-logging:scala-logging_2.12:3.7.2
|    |    |    +--- org.scala-lang:scala-library:2.12.2 -> 2.12.6
|    |    |    +--- org.scala-lang:scala-reflect:2.12.2 -> 2.12.6 (*)
|    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    \--- ch.qos.logback:logback-classic:1.2.3
|    |         +--- ch.qos.logback:logback-core:1.2.3
|    |         \--- org.slf4j:slf4j-api:1.7.25
```
Note that unlike gatling-commons, scala-logging only depends on slf4j-api and not any specific binding. I double-checked and this dependency is still present in gatling-commons 3.0.0.

From the slf4j manual:
```
Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose. When you come across an embedded component declaring a compile-time dependency on any SLF4J binding, please take the time to contact the authors of said component/library and kindly ask them to mend their ways.
```
https://www.slf4j.org/codes.html#multiple_bindings
:)

Please change the scope of logback dependency so it does not show up in published poms and end users classpaths. It looks like this would be a simple 1 line change in `project/Dependencies.scala`, is that right?

**Comment by slandelle** [comment]
From what you explain, I suspect you're building your own software on top of ours. I fail to see a different reason for depending on `gatling-core` but not on `gatling-app` (which requires logback with compile scope).
If that's the case, I'm sorry, but what you're doing is unsupported. Gatling is a software, not a library, and is supposed to be used as a whole.
