### ISSUE TITLE
HTTP: Wrong HttpStatus entry in HttpHelper after update to 3.0.0

### ISSUE THREAD

**Issue by TTBoesch** [gatling/gatling#3601]
After updating gatling from version 2.3.1 to 3.0.0, we faced the following problem:

When using inferHtmlResources, some resources were returned with StatusCode 304, resulting in errors like

> [gatling-http-1-3][WARN ][StatsProcessor.scala:114] i.g.h.e.r.DefaultStatsProcessor - Request 'favicon.ico' failed for user 1: status.find.in(200,201,202,203,204,205,206,207,208,209,303), found 304

which distorted the test results.

We found the following change in the HttpHelper between version 2.3 and 3.0:

Version 2.3:

`val OkCodes = Vector(200, 304, 201, 202, 203, 204, 205, 206, 207, 208, 209)`

Version 3.0:

`val OkCodes: BitSet = BitSet.empty + OK.code + SEE_OTHER.code + CREATED.code + ACCEPTED.code + NON_AUTHORITATIVE_INFORMATION.code + NO_CONTENT.code + RESET_CONTENT.code + PARTIAL_CONTENT.code + MULTI_STATUS.code + 208 + 209
`

We assume that instead of `SEE_OTHER.code` (303), it should read `NOT_MODIFIED.code` (304).

**Comment by slandelle** [comment]
Thanks for reporting
