### ISSUE TITLE
HTTP: Premature close handling doesn't cancel request timeouts and cause forked events

### ISSUE THREAD

**Issue by vas78** [gatling/gatling#3607]
This issue seems to be very similar to #3546, although it can be reproduced with Gatling 3.0.0. final.
In case the system under test throws request timeouts from time to time, the simulation ends up with a negative amount of active users and never finishes. It keeps logging to stdout, but never finishes and goes over 100% progress bar.
Here is simple simulation that reproduces the issue with Gatling-3.0.0:

```
import io.gatling.core.scenario.Simulation
import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._

class ReproducerSimulation extends Simulation {

  val scn = scenario("TimeoutIssueReproducer")
    .exec(
      http("dummy_req")
        .get("http://localhost:8083")
    )

  val baseProtocol = http
    .disableWarmUp
    .userAgentHeader("Gatling")
    .connectionHeader("Close")
    .acceptEncodingHeader("gzip,deflate")

  setUp(
    scn.inject(
      constantUsersPerSec(10) during (6 minutes)
    ).protocols(baseProtocol)
  )
}
```

Steps to reproduce:
1. Start the simlation and let it run for some time.
2. Kill the service under test and start netcat that listens to the same port in order to simulate server-side timeouts.
3. Kill netcat and restart the service under test.

Attached is the simulation run log.

**Comment by vas78** [comment]
[Gatling_Log.txt](https://github.com/gatling/gatling/files/2585938/Gatling_Log.txt)

**Comment by slandelle** [comment]
@vas78 Thanks, the logs helped a lot!
The root problem was how we handled retry on premature close. We weren't cancelling the request timeout, which caused an avalanche of fork events.

**Comment by thinkerou** [comment]
@slandelle gatling3.1.2 still have the question.
[consoleText.txt](https://github.com/gatling/gatling/files/3284965/consoleText.txt)

**Comment by slandelle** [comment]
@thinkerou It looks to me that your problem is completely unrelated. Your server crashed and/or is saturated.

**Comment by slandelle** [comment]
@thinkerou It looks to me that your problem is completely unrelated. Your server crashed and/or is saturated. Basically, it can't handle the load you're throwing at it.

**Comment by thinkerou** [comment]
@slandelle thanks your reply, I will test it!

**Comment by adityakap** [comment]
@slandelle is it possible this is still happening in [gatling3.2.1](https://github.com/denvazh/gatling/blob/master/3.2.1/Dockerfile)

We are seeing negative active users after a certain point of hitting premature close + 500 + timeout errors.

here is a sample right before it starts tripping over..

`================================================================================
2019-10-17 04:46:23                                         540s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=534    KO=1517  )
> get sherlock node URL                                    (OK=1      KO=0     )
> get authentication token                                 (OK=1      KO=0     )
> POST request /v2/execengine/isworkable                   (OK=532    KO=1517  )
---- Errors --------------------------------------------------------------------
> i.g.h.c.i.RequestTimeoutException: Request timeout to ip-172-3   1163 (76.66%)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX afte...
> status.find.in(200,400), but actually found 500                   221 (14.57%)
> j.i.IOException: Premature close                                  133 ( 8.77%)

---- MainTest ------------------------------------------------------------------
[########################################################-----             ] 75%
          waiting: 505    / active: 146    / done: 2049  
---- RecordedSimulationSetup ---------------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done: 1     
================================================================================`

`================================================================================
2019-10-17 04:46:28                                         545s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=534    KO=1738  )
> get sherlock node URL                                    (OK=1      KO=0     )
> get authentication token                                 (OK=1      KO=0     )
> POST request /v2/execengine/isworkable                   (OK=532    KO=1738  )
---- Errors --------------------------------------------------------------------
> i.g.h.c.i.RequestTimeoutException: Request timeout to ip-172-3   1288 (74.11%)
1-170-206.us-west-2.compute.internal/172.31.170.206:24136 afte...
> j.i.IOException: Premature close                                  227 (13.06%)
> status.find.in(200,400), but actually found 500                   223 (12.83%)

---- MainTest ------------------------------------------------------------------
[##############################################################             ] 84%
          waiting: 469    / active: -39    / done: 2270  
---- RecordedSimulationSetup ---------------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done: 1     
================================================================================`

**Comment by slandelle** [comment]
The best solution would be to provide us with a means to reproduce on our side.

**Comment by oleksiipetr** [comment]
Hi , in my case it was Nginx configuration, worker limit was 2048.
`2019-11-21 12:39:11                                          15s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=4368   KO=0     )
> getNewsList                                              (OK=2975   KO=0     )
> getNewsList Redirect 1                                   (OK=1393   KO=0     )

---- GetTournament -------------------------------------------------------------
[#################--------------------                                     ] 23%
          waiting: 3007   / active: 1600   / done: 1393
================================================================================


================================================================================
2019-11-21 12:39:16                                          20s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=5892   KO=44    )
> getNewsList                                              (OK=3982   KO=0     )
> getNewsList Redirect 1                                   (OK=1910   KO=44    )
---- Errors --------------------------------------------------------------------
> j.i.IOException: Premature close                                   25 (56.82%)
> status.find.is(200), but actually found 502                        19 (43.18%)

---- GetTournament -------------------------------------------------------------
[########################--------------------------                        ] 32%
          waiting: 2003   / active: 2043   / done: 1954
================================================================================
`
As you see , when i reached over 2000 active connections 'Premature close' issue starts to appear.

**Comment by slandelle** [comment]
"Premature close" is completely expected with a non graceful server. The only issue is the "negative active users" problem like @adityakap reported above. Do you experience it too?

**Comment by oleksiipetr** [comment]
Nope, never saw 'negative active users'

**Comment by slandelle** [comment]
@oleksiipetr thanks for your feedback

**Comment by thinkerou** [comment]
![0b7c9f8b62d45a8bf3505084b588576e](https://user-images.githubusercontent.com/4488261/69728654-c69d8a00-115f-11ea-9fb0-825e7f54fcb0.png)
my form data param string size > 12K, it will reproduce.
I use 4K string to test, it's OK.

**Comment by slandelle** [comment]
I'm going to freeze this ticket so people stop highjacking it with unrelated problems.

If someone still really suffers from duplicated virtual users and ends with a negative number of remaining users **after upgrading a modern Gatling version (at least 3.3.1)**, please open a new issue and provide a way for us to reproduce your problem.

If someone experiences "Premature close" errors, it's more likely the behavior of your server that closes the connection abruptly (poor connection handling, request body that exceeds a limit).
