### ISSUE TITLE
Gatling hangs with negative active users and progress exceeding 100%

### ISSUE THREAD

**Issue by nmutsanas** [gatling/gatling#3608]
Since migrating to gatling 3.0.0 yesterday we get invalid numbers in the progress console log: negative active users and overall progress that exceeds 100%. The loadtest seems to hang and needs to be aborted.

See log excerpt:
`---- Foo -----------------------------------------------------------------------`
`[###################################################################################]112%`
`          waiting: 0      / active: -150   / done: 1350  `
`================================================================================`

A rerun of the loadtest exhibits the same problem with different numbers
`---- Foo -----------------------------------------------------------------------`
`[##########################################################################]101%`
`          waiting: 0      / active: -13    / done: 1213  `
`================================================================================`

1200 users is what would be expected from the test setup

There is a second scenario that completed successfully in both runs

In both runs there are several warnings of the following form:
`07:33:00.955 [WARN ] i.g.h.e.GatlingHttpListener - Request 'bar' failed for user 3291`
`07:33:00.955 [WARN ] i.g.h.e.r.DefaultStatsProcessor - Request 'bar' failed for user 3291: i.g.h.c.i.RequestTimeoutException: Request timeout to xxxxx:1111 after 60000 ms
`
The same nightly loadtest has been running without this issue on gatling 2.3 for a few weeks.
The same loadtests with fewer users have been ran successfully on gatling 3.0.0.

The next nightly is scheduled to run only the 'problematic' scenario. I will update this bug report if it behaves differently.
Any hints on how to further narrow the problem down are appreciated.

**Comment by vas78** [comment]
I guess this is just the same as #3607

**Comment by slandelle** [comment]
@nmutsanas Closing as duplicate, but could you please confirm you have some "Premature close" exceptions in your logs?

**Comment by nmutsanas** [comment]
Thanks for your feedback!

I can confirm that one of the two runs has such exceptions in the logs:
```
io.gatling.http.client.impl.HttpAppHandler$1: Premature close
07:26:40.230 [WARN ] i.g.h.e.r.DefaultStatsProcessor - Request 'foo' failed for user 1050: j.i.IOException: Premature close
```
The other run has 16 exceptions of the following form
```
io.gatling.http.client.impl.RequestTimeoutException: Request timeout to xxxx:1111 after 60000 ms
15:34:51.572 [WARN ] i.g.h.e.r.DefaultStatsProcessor - Request 'foo' failed for user 5793: i.g.h.c.i.RequestTimeoutException: Request timeout to xxxx:1111 after 60000 ms
```
but no mention of premature close.

**Comment by slandelle** [comment]
Could you please share the full logs?

**Comment by nmutsanas** [comment]
I'm not allowed to publish them here, but I've emailed them to you.

**Comment by slandelle** [comment]
@nmutsanas Yes, I'm pretty sure that's the same issue. Thanks!
