### ISSUE TITLE
HTTP: Logback doesn't show response body for requests without check

### ISSUE THREAD

**Issue by TrickyDoodle** [gatling/gatling#3610]
Hi!

In gatling v.3.0.0 I have the following settings in logback.xml 

```
    <logger name="io.gatling.ahc.engine.response" level="TRACE" />
    <logger name="io.gatling.http.engine.response" level="TRACE" />
```

The problem is that I can view response body in a log only If I have .check method in a request, otherwise I can see just response headers. 

In gatling v 2.3.1 check method existence doesn't impact for logging.

**Comment by slandelle** [comment]
Thanks for reporting!
