### ISSUE TITLE
Core: Implement ArrayBasedMap `+`, `-` and `updated` methods

### ISSUE THREAD

**Issue by vu-illumio** [gatling/gatling#3625]
Gatling 3.0.1

Use Case:
We read all feeder records (using https://gatling.io/docs/current/session/feeder/#grabbing-records) at the beginning of the simulation and make following modifications before virtual users start using them:
- Adding required fields if we find them missing
- Updating existing fields if we find them incorrect

Example:
```
val simDataTokens: Vector[Map[String, Any]] = {
  csv(dataFile).readRecords.as[Vector[Map[String, String]]]
    .zipWithIndex
    .map(r => {
      val id = r._2
      val tokens = r._1
      tokens + ("id" -> id) // or tokens.updated("id", id)
    })
}
```

Feature Request:
ArrayBasedMap methods for `+`, `-` and `updated` need to be implemented. Currently, they return java.lang.UnsupportedOperationException when called.

**Comment by slandelle** [comment]
@vu-illumio PR?

**Comment by vu-illumio** [comment]
@slandelle If this PR is not urgent, I'd like to give it a shot. Please give me a week.

**Comment by slandelle** [comment]
@vu-illumio Sure. Thanks

**Comment by slandelle** [comment]
@vu-illumio Gentle ping
