### ISSUE TITLE
Gatling SBT plugin not honouring simulationClass

### ISSUE THREAD

**Issue by marcguilera** [gatling/gatling#3628]
**Versions:**

- SBT plugin: 3.0.0
- Gatling: 3.0.1.1

**Example 1:**

- gatling.conf: ```gatling.core.simulationClass = "MySimulation"```

- Run: ```sbt gatling:test```

**Example 2:**

- Run: ```sbt gatling:testOnly MySimulation```

**Results:**

Gatling runs all simulations and not only the class I am trying to run.

**Comment by slandelle** [comment]
**Example 1:**

The gatling-sbt-plugin is a test plugin in the sbt sense and just don't work this way and can't support the option in `gatling.conf`.

**Example 2:**

This is the proper way, and I've just checked with our [demo](https://github.com/gatling/gatling-sbt-plugin-demo) that it works as expected and `gatling:testOnly computerdatabase.BasicSimulation` only runs this simulation.

**Comment by slandelle** [comment]
No pro. No familiar with the gradle plugin. The only official component that uses this conf option is the zip bundle.
