### ISSUE TITLE
Let Gatling run multiple simulations sequentially

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#363]

**Comment by michaelmcmillan** [comment]
Is this functionality gone?

**Comment by slandelle** [comment]
Not available from the bundle. You're already running a script, you should be able to easily wrap it and launch a sequence.

Available from the maven plugin though, as it spawns new JVM for each simulation to run.

**Comment by pankajsir** [comment]
So what is the syntax to run all the simulations
