### ISSUE TITLE
HTTP: sending bytes with websocket

### ISSUE THREAD

**Issue by gstraymond** [gatling/gatling#3630]
When sending bytes with websocket connection, I got this error:  
`i.g.h.a.w.f.WsActor - unhandled event SendBinaryFrame(...) in state Idle`

The bytes are not sent to the server, and the simulation hangs forever to complete.

I tried with Gatling `3.0.1.1`, here is a simple Simulation to reproduce it :

```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._

class EchoSimulation extends Simulation {

  private val httpProtocol = http.wsBaseUrl("ws://demos.kaazing.com/echo")

  private val scn = scenario("EchoSimulation")
    .exec(ws("Connect WS").connect("/"))
    .pause(100.millis)
    .exec(ws("Say Hello WS").sendBytes("Hello".getBytes("utf-8")))
    .pause(100.millis)
    .exec(ws("Close WS").close)

  setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
```

I read the docs multiple times, did I miss something ?

**Comment by gstraymond** [comment]
BTW, it's working with `sendText`, you can test by changing line 16 :

```
.exec(ws("Say Hello WS").sendText("Hello"))
```

**Comment by slandelle** [comment]
Thanks for reporting!
