### ISSUE TITLE
HTTP: Websocket doen't handle correctly server closing connection

### ISSUE THREAD

**Issue by gstraymond** [gatling/gatling#3633]
The context :
- a client establish a websocket connection to a server
- the client sends bytes (multiple times) and waits for server response data
- the server returns response data and close the websocket connection right after

When the connection is closed, I get this error:
```
i.g.h.a.w.f.WsActor - unhandled event WebSocketCrashed(io.gatling.http.client.impl.HttpAppHandler$1: Premature close,...) in state Crashed
```

If the server returns only data, and the client close the websocket connection, its working fine.

I tried with Gatling `3.0.2-SNAPSHOT` (which contains this fix https://github.com/gatling/gatling/issues/3630)

Sample scenario:
```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._

class ServerCloseSimulation extends Simulation {

  private val bytes: Array[Byte] = ???

  private val httpProtocol = http.wsBaseUrl("ws://localhost:9000")

  private val scn = scenario("ServerCloseSimulation")
    .exec(ws("Connect").connect("/"))
    .foreach(bytes.grouped(2048).toSeq, "packet") {
      exec(ws("Send bytes").sendBytes("${packet}")).pause(60.millis)
    }
    .pause(10.seconds) // fails here
    .exec(ws("Close").close)

  setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
```

**Comment by slandelle** [comment]
Would you be able to provide a reproducer app, please? We're pretty swamped and won't have time atm to investigate without one.

**Comment by gstraymond** [comment]
Will do !

**Comment by gstraymond** [comment]
Here we go ! https://github.com/gstraymond/hello-websocket-play-server

**Comment by slandelle** [comment]
Cool, thanks! Travelling this week so I might only be able to have a look next week.

**Comment by slandelle** [comment]
Here's the simulation I ran against your sample:

```scala
class ServerCloseSimulation extends Simulation {

  private val httpProtocol = http.wsBaseUrl("ws://localhost:9000").disableWarmUp

  private val scn = scenario("ServerCloseSimulation")
    .exec(ws("Connect").connect("/?close=true"))
    .repeat(5) {
      exec(ws("Send text").sendText("Hello!"))
        .pause(60 millis)
    }
    .pause(5) // fails here
    .exec(ws("Close").close)

  setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
```

Then, I wonder if your problem is that you're not increasing `wsMaxReconnects`.
