### ISSUE TITLE
More than 100% completed requests

### ISSUE THREAD

**Issue by Onebitl0st** [gatling/gatling#3637]
Hello. I've downloaded latest gatling and trying to test our NetCore 2.1 based app.

Scenario is very simple:

```
class GetContacts extends Simulation {

  val httpProtocol = http
    .baseUrl("APP_URI")

  val headers = Map("Token" -> "Any_token")

  val scn = scenario("Contacts")
    .exec(http("contacts")
    .get("/contacts/_me")
    .headers(headers))

  setUp(scn.inject(constantUsersPerSec(25) during(600 seconds)).protocols(httpProtocol))
}
```

But, cause our app is kinda unstable, with k8s, im getting some 503, 504, and timeout responces. But with latest version - im getting this results:
![image](https://user-images.githubusercontent.com/7286958/50160856-49308f00-02eb-11e9-9208-2268d54a1e8c.png)

So, and i can terminate job only by Ctrl+C. That's first time than i got this, with any versions, so, can't even help with some investigation. Unfortunately, our app is not opened too, so, there is no options to test it from "other world".

Running gatling via PowerShell console on Win10

Looking forward to solve, and will provide any help.
Best regards, Dmitry.

P.S.: If there is any possibility - to return naming of report folder = name of desription im adding - that would be great

**Comment by slandelle** [comment]
* Please make sure you can reproduce with 3.0.1.1
* If you can still reproduce, I'm afraid we won't be able to investigate without being able to test against your server.

**Comment by Onebitl0st** [comment]
@slandelle Hello, thanks for fast reply.
1. I've downladed newest version today morning.
2. I'll try to do something. Maybe we can try to open our dev klaster for speciall ip or something. 
So, there is nothing to try without touching our app? I thought that may be on common level.

**Comment by slandelle** [comment]
> So, there is nothing to try without touching our app? I thought that may be on common level.

The other way is that you build a sample app and Gatling simulation that exhibit the same issue.

**Comment by Onebitl0st** [comment]
> The other way is that you build a sample app and Gatling simulation that exhibit the same issue.

Well, i have 1 thought about, may it be instigated by my hosts file.

To touch our k8s klaster, avoiding ARR, i've added 2 lines to hosts file, like:
1.1.1.1 app.dev.net
1.1.1.2 app.dev.net

May it be problem with this?

> The other way is that you build a sample app and Gatling simulation that exhibit the same issue.

About this, im just tester, ill talk with our developers, and maybe we will provide something via Azure in few days

**Comment by slandelle** [comment]
Were you able to figure out what happened?

**Comment by Onebitl0st** [comment]
@slandelle Sorry, but no ideas( Sometimes it happened with a lot of failed requests by different reasons. Looked like Gatling counted requests with timeouts twice, but im not sure. We've discussed - and can't create same app for you in close times, so, i've just close - and if ill find some ways - ill open new issue
