### ISSUE TITLE
HTTP: SSE close hangs if executed after http post request

### ISSUE THREAD

**Issue by zhudaxi** [gatling/gatling#3638]
In Gatling 3.0.1.1, we are trying to test our server's SSE connection.
The test is like below:

```
import scala.concurrent.duration._
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class sse_test extends Simulation {

  val httpProtocol = http
    .baseUrl("http://server-ip:9000")

  val scn = scenario("sse_test")
    .exec(http("Execute a post request").post("/god/help/me"))
    .exec(sse("Get SSE").connect("/workspaces/eventsource/123456"))
    .exec(sse("Close sse").close())

  setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
```

The problem is: the close sse action just won't finish, the test will running forever.

From the log we can see:
_Content-Type: text/event-stream'
15:12:02.531 [DEBUG] i.g.h.a.s.SseListener - Status 200 received for SSE
15:12:02.532 [DEBUG] i.g.h.a.s.f.SseActor - Connected, no checks, performing next action
15:12:02.536 [INFO ] i.g.h.a.s.f.SseActor - Client requested SSE stream close_

So the SSE close is triggered, but it just can't finish.

If we remove the http post request in the script, the SSE close can be executed successfully.

**Comment by slandelle** [comment]
Thanks for reporting!
