### ISSUE TITLE
Windows parameters works unexpectedly

### ISSUE THREAD

**Issue by Onebitl0st** [gatling/gatling#3642]
Hello, downloaded latests version today, and tryed to pass we parameters like:
```
PS D:\Gatling\bin> .\gatling.bat -ro 30minutes -rd 30minutesTest
GATLING_HOME is set to "D:\Gatling"
JAVA = ""C:\Program Files\Java\jre1.8.0_191\bin\java.exe""
Parsing log file(s)...
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: simulation directory 'D:\Gatling\results\30minutes' doesn't exist
```

Then i've added folder got this:
```
PS D:\Gatling\bin> .\gatling.bat -ro 30minutes -rd 30minutesTest
GATLING_HOME is set to "D:\Gatling"
JAVA = ""C:\Program Files\Java\jre1.8.0_191\bin\java.exe""
Parsing log file(s)...
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: simulation directory doesn't contain any log file.
```

System: Windows 10
Running via ConEmu Powershell with admin.

Best regards,
Dmitry.

P.S.: may i somehow setup log folder name? I don't want to get /health-20181224131255974, i need to passs some parameter for this. On my hand - then report folder name were equals to description, that i've passed - that was great

**Comment by slandelle** [comment]
ro parameter is the name of the directory, located in the results one.

**Comment by Onebitl0st** [comment]
soz, my mistake)
