### ISSUE TITLE
I want to insert feed's value to myself‘s custom functions,but failed

### ISSUE THREAD

**Issue by luowqn** [gatling/gatling#3643]
My code part:
`
public static String Code(String token,String url,String test)
    {
        String authcode =toHex(encryptionHMACMD5(token.getBytes(),url));
        return authcode;
    }

def randomCode(token: String,url: String,name: String): Iterator[Map[String,String]] = {
        Iterator.continually(Map(name -> Code(token,url)))
    }
object plateNumber{
        val feeder = csv("plateNumber.csv").circular
        val Exec = feed(feeder)
            .feed(randomUuid(30,"id"))
            .exec(_.set("token",token))
            .exec(_.set("apiKey",api_key))
            .exec(_.set("kksmall_url",plateNumberUrl))
            .feed(time("yyyy-MM-dd HH:mm:ss","imageTime"))
            .feed(randomCode("${token}",plateNumberUrl,"newkey"))
            .exec(http("test")
            .post("/signalway/image/structurization.htm")
            .body(ElFileBody("plateNumber.json")).asJSON
            .check(status.is(200),
            jsonPath("$.code").is("0")
            )   
        )  
    }`

randomCode("${token}",plateNumberUrl,"newkey")   

I print token value in Code ,the value is "${token}" ,but i want to token actually value

**Comment by slandelle** [comment]
For such question, Please use the community mailing list and not the bug tracker. You’ll find the address on our website.
