### ISSUE TITLE
Recorder: Don't generate ( .check(status.is(0)) ) for a request

### ISSUE THREAD

**Issue by 7belrhalmia** [gatling/gatling#3654]
Hello,

I recorded a scenario using GetLing recorder, however for somme requests it generates : .check(status.is(0))
and I dont know why ? , here is the code : 

`http("request_8").get("/api/datasources/real/uc_kpi1_performance?region=1%2C2%2C3%2C4%2C5%2C6&fields=commande%2Cachievement_mtd%2Cregion&date=2018-12-01%7C2018-12-31").headers(headers_7).check(status.is(0)),`

This generate an error of test in testing part : 

![image](https://user-images.githubusercontent.com/13202562/51692828-048cc780-1ffe-11e9-81cf-f043d7d3ed58.png)

**Comment by slandelle** [comment]
Please provide a way for us to reproduce on our side.

**Comment by 7belrhalmia** [comment]
Hi @slandelle ,
I figure out why the problem happens, actually in the API I check out one check box out of three in order that the section relative to this check boxe disappear from the page, and the two other section relatif to the two other check box still, so the .check(status.is(0)) is generated for them.

**Comment by slandelle** [comment]
Do you use the proxy or the HAR mode?

**Comment by 7belrhalmia** [comment]
HAR mode

**Comment by 7belrhalmia** [comment]
here is a part of the code : [(https://drive.google.com/open?id=1piJjhKgqvLTjfk75U4XTnR1epmOiSfeN)]

**Comment by slandelle** [comment]
No, I need the HAR (input), not the Scala code (output).
