### ISSUE TITLE
Use github releases for additional release notifications

### ISSUE THREAD

**Issue by Elufimov** [gatling/gatling#3659]
It would be very great if you consider to use github releases. Not so long ago github introduced an ability to subscribe only for new releases. This is a native way for get in touch. https://help.github.com/articles/watching-and-unwatching-releases-for-a-repository/ There is no need to put a real release note there, one can find it by himself.

**Comment by slandelle** [comment]
Sorry, but that's something we don't consider.
We deploy on maven central and advertise new releases on Twitter. You can also get automatically get notified with tools such as https://www.artifact-listener.org/.
