### ISSUE TITLE
Parameters from feeders discard double quotes

### ISSUE THREAD

**Issue by TrickyDoodle** [gatling/gatling#3662]
I'm using gatling v. 3.0.3. 
I have the following semicolon feeder: 

`val fooFeeder = ssv("foo.ssv").circular`

The contens of a file is:

```
FEEDER_VALUE
"2345","3456","4567"
"3456","4567","8901"
"8901","1234","5678"
```

The question is - when I launch my script and use feed(fooFeeder), the session parameter FEEDER_VALUE is like that: `FEEDER_VALUE-> 2345,3456,4567` - without double quotes. 

Is it a proper behaviour? I expected that FEEDER_VALUE will be the same as in a file.  On the other way, if a string partly or fully consists of single quotes, everything is ok, e.g: 
```
FEEDER_VALUE-> '2345','3456','4567'
FEEDER_VALUE-> '2345',"3456","4567"
```

Best regards.

**Comment by slandelle** [comment]
Please use the community mailing list for questions, not the bug tracker.
