### ISSUE TITLE
Feature Request: Add Prometheus DataWriter for realtime monitoring.

### ISSUE THREAD

**Issue by bmaguireibm** [gatling/gatling#3675]
This is a request to add a [Prometheus](https://prometheus.io) DataWriter that would expose Gatling results as a Prometheus metrics endpoint to provide Real time information.

This Feature is already implemented [here](https://github.com/bmaguireibm/gatling) and I'd be happy to create a PR if there's interest in adding it.
 
### Prometheus

Prometheus is a Time Series database and monitoring system optimised for collecting numerical data from large numbers of servers at a time.
It uses a pull model, where in it pulls data from registered endpoints via http requests.

Prometheus is heavily used in the Kubernetes ecosystem for collecting metrics on pod and node resource usage.

### The Use case

I've been using Gatling to run continuous health checks against services deployed on a Kubernetes cluster.
The Prometheus Data Writer allows for the results of these healthchecks to be collected by Prometheus and integrated into the existing monitoring and alerting framework for the Kubernetes cluster in real time.
If Gatling is run from within a pod itself, Prometheus can be configured to automatically pick up the metrics endpoint and start scraping data.
This data could additionally be made available to Horizontal Auto-Scaling controllers to provide for scaling based on Gatling results etc.

Overall, a Prometheus DataWriter should ease Gatling integration into Kubernetes clusters.

Existing Implementation can be found [here](https://github.com/gatling/gatling/compare/master...bmaguireibm:master).

Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [x] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [ ] Check that you can reproduce your issue with latest Gatling version
  * [ ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [ ] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x] Explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment]
Hi,

Thank you for posting your feature request.

As you may know, we now develop at the same time the open-source solution, Gatling, and its Enterprise version, Gatling FrontLine.

The way we see our R&D efforts is as follows:
* everything related to the core of Gatling (eg. new protocol support) is in the scope of Gatling
* everything related to new metrics, new reporting's features and news integrations is in the scope of Gatling FrontLine

You feature request falls in the scope of Gatling FrontLine. If you'd like to discuss this with us, we would be more than happy to see how we can work on this. Please then reach out at contact@gatling.io.

Thanks and regards

**Comment by bmaguireibm** [comment]
Hi @slandelle ,

Thanks for your quick reply. 
I understand your priorities regarding R&D, however, I've already implemented this feature in this [fork](https://github.com/bmaguireibm/gatling) and have been using it as part of my health checks on Kubernetes based services.
I feel it would make a useful addition to Gatling, especially in integrating it into Kubernetes environments.

Will I create a PR with my implementation code to continue the discussion there ?

**Comment by slandelle** [comment]
Hi,

Thank you for your answer.

I think there was a misunderstanding, I apologize. Including such feature in our open-source project would infringe our policy regarding our R&D efforts.

We unfortunately can’t accept this contribution. We sincerely hope you understand this situation. The same way we don’t want to jeopardize our open source model, we don’t want to jeopoardize our commercial product. Our entire company, and both our solutions, relies on this balance.

If however, you’d like to include this feature and benefit from our Enterprise version, I am sure we can find an agreement on that.

Let me know when you would be available, we would love to discuss this with you.

Thanks again and regards,
