### ISSUE TITLE
HTTP: Debug should show transformed response body instead of original body

### ISSUE THREAD

**Issue by jgaalen** [gatling/gatling#3678]
I'm using transformResponse to decode a binary response. Although when there is a check error and running in debug mode the original binary body is printed instead of the better readable transformed response body. This makes debugging hard. It makes more sense to print the transformed response body

(version 3.0.3)

**Comment by slandelle** [comment]
Thanks for reporting!

**Comment by asaarilahti** [comment]
The fix for this seem to allow transforming response time again:
```scala
.transformResponse {
  (session, response) =>
    response.copy(endTimestamp = newEndTimestamp)
  }
}
```
That worked with 2.3.x, but got ignored in 3.0.x. Fortunately it seems to work after this fix.
