### ISSUE TITLE
Angular chained requests returns 401 always though token is provided

### ISSUE THREAD

**Issue by D0421** [gatling/gatling#3679]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [x ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [x ] Check that you can reproduce your issue with latest Gatling version
  * [ x] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [x ] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x ] Explain your use case, not the implementation you have in mind.

one of the angular request:
http("request_38")
                        .post("/angular.do")
                        .headers(headers_28)
                        .formParam("sysparm_type", "Processor")
                        .formParam("method", "getContent")
                        .formParam("selectedItems", """[{"sysId":"8cd0eac6b7032300fa2d8605ee11a957","uuid":"40a91c86-fb66-4100-9a61-de1c421284e8"}]""")
                        .formParam("additionalSysParm", """{"sysparm_filters":[]}""")
                        .resources(http("request_39")
                        .get("/ConditionalFocus.jsdbx?v=Wed_Feb_20_08_35_14_CET_2019&c=5_59&_=1550665355606")
                        .headers(headers_32),

Headers as below:
val headers_28 = Map(
                "Accept" -> "*/*",
                "Accept-Encoding" -> "gzip, deflate, br",
                "Accept-Language" -> "en-US,en;q=0.9,nl;q=0.8",
                "Content-Type" -> "application/json; charset=UTF-8",
                "Origin" -> "http://localhost:8080",
                "User-Agent" -> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
                "X-Requested-With" -> "XMLHttpRequest",
                "Cookie" -> """****_user_route=****.259b8638e5d7a7738acc1ca7648a2854; JSESSIONID=955B113CC2FB49BB5DC109FF2B344CE9; ****_user_activity="U0N2MzpPV2F5YUdtTU1pQ3VvS01PTWNncXg2ZVpEQTd5S1Y0czpoeTdBdWVhc0RGbTcxRnBvZU9VcEUySTgrTUp1TFpZaXhSTTBiZFRMTnVRPTo2ODE2Zjc5Y2MwYTgwMTY0MDFjNWEzM2JlMDRiZTQ0MQ=="; ****_session_store=3AEE3FA073732300FA2D0B0FFAF6A7A1; __CJ_g_startTime=%221550665355050%22 """,
                "X-UserToken" -> "7aee3fa073732300fa2d0b0ffaf6a7a158885135e419a36209fb98fff97e03402afdac83")

Another angular get request:

http("request_21")
                        .get("/angular.do?sysparm_type=get_partial&name=some.xml&noCache=1550665356415")
                        .headers(headers_21),

val headers_21 = Map(
                "Accept" -> "application/json, text/plain, */*",
                "Accept-Encoding" -> "gzip, deflate, br",
                "Accept-Language" -> "en-US,en;q=0.9,nl;q=0.8",
                "User-Agent" -> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
                "Cookie" -> """****_user_route=*****.259b8638e5d7a7738acc1ca7648a2854; JSESSIONID=955B113CC2FB49BB5DC109FF2B344CE9; ****_user_activity="U0N2MzpPV2F5YUdtTU1pQ3VvS01PTWNncXg2ZVpEQTd5S1Y0czpoeTdBdWVhc0RGbTcxRnBvZU9VcEUySTgrTUp1TFpZaXhSTTBiZFRMTnVRPTo2ODE2Zjc5Y2MwYTgwMTY0MDFjNWEzM2JlMDRiZTQ0MQ=="; *****_session_store=3AEE3FA073732300FA2D0B0FFAF6A7A1; __CJ_g_startTime=%221550665355050%22 """,
                "X-UserToken" -> "7aee3fa073732300fa2d0b0ffaf6a7a158885135e419a36209fb98fff97e03402afdac83")

Could you help me out this issue please.

**Comment by slandelle** [comment]
This is a bug tracker.
Please use our community mailing list for questions.
