### ISSUE TITLE
 error while loading package, class file ... has location not matching its contents 

### ISSUE THREAD

**Issue by kolotyluk** [gatling/gatling#3680]
So, my project compiles, runs, and passes all its unit test fine, but when I try to run my Gatling tests from Maven I get
```
> mvn gatling:test
. . .
[ERROR] [2019-02-20 10:22:38,442] [main] [io.gatling.compiler.ZincCompiler$] error while loading package, class file '/Volumes/Repos/leaderboard/target/classes/net/kolotyluk/leaderboard/akka/package.class' has location not matching its contents: contains package object Akka
[ERROR] [2019-02-20 10:22:38,447] [main] [io.gatling.compiler.ZincCompiler$] error while loading package, class file '/Volumes/Repos/leaderboard/target/classes/net/kolotyluk/leaderboard/akka/endpoint/package.class' has location not matching its contents: contains package object endpoint
[ERROR] [2019-02-20 10:22:38,454] [main] [io.gatling.compiler.ZincCompiler$] error while loading package, class file '/Volumes/Repos/leaderboard/target/classes/net/kolotyluk/leaderboard/akka/endpoint/leaderboard/package.class' has location not matching its contents: contains package object leaderboard
[ERROR] [2019-02-20 10:22:38,487] [main] [io.gatling.compiler.ZincCompiler$] three errors found
```
These errors looks surprisingly similar to some errors I got trying to build my project with SBT, which is why I switched to Maven. If Gatling utilizes SBT to run, then it is more likely to fail.

I have used Maven a lot longer, and a lot more than SBT, and never found a crippling defect. However, I have found at least 3 crippling defects in SBT in that same time.

It would be nice to be able to invoke Gatling from Maven without any interference from SBT.

Feel free to play with the project at https://github.com/kolotyluk/leaderboard
```
<groupId>io.gatling</groupId>
<artifactId>gatling-maven-plugin</artifactId>
<version>3.0.2</version>
```

**Comment by slandelle** [comment]
That’s most likely your package named Akka with capital A that breaks Zinc.
You should fix it and use lower case for packages.

**Comment by kolotyluk** [comment]
I cannot rename my package Akka to akka, because then it conflicts with other things. If Zinc cannot handle that, then Zinc is broken, because nothing else has a problem with it. Also, what about the errors on packages endpoint and leaderboard?

**Comment by slandelle** [comment]
> I cannot rename my package Akka to akka, because then it conflicts with other things.

No, it's not that you can't, it's that you don't want to. If you don't know how to handle those conflicts in Scala, just don't name it "Akka/akka" but something else.

> If Zinc cannot handle that, then Zinc is broken

The Java Language Specification has always been recommending (not requiring) that package names use lower case. This rules has always been adopted by everyone that I can understand bugs can happen went you don't follow this rule.

> If Zinc cannot handle that, then Zinc is broken

Strictly speaking, I agree. You can open an issue [there](https://github.com/sbt/zinc/issues). But I suspect the best way to get this fixed is to contribute a fix yourself. I kind of expect that this won't be a priority for them as basically nobody names packages the way you do.

> nothing else has a problem with it

scala-maven-plugin uses a very old  pre-1.0 version of Zinc. I guess there was a regression.

> what about the errors on packages endpoint and leaderboard

Those are sub-packages and suffer from the same problem: capital `A` in full package name.

All in all, there's nothing we can do here.

**Comment by kolotyluk** [comment]
Okay. renaming the package from Akka to akka_specific solved the problem. Thanks

I could not rename the package to 'akka' because that conflicts with all the akka... packages, and I could not find a work-around for that. It's not that I didn't want to change the name, it was more that I wanted to exhaust other solutions before trying that one.

I generally don't use Uppercase in package names, and I understand the package naming recommendations, but they are not specifications, and Zinc should conform to specifications over recommendations. Also, the Zinc diagnostics could be better.

Thanks for the link to Zinc, I will take a look at that.

I wonder if SBT uses Zinc, and why it falls prey to that or similar problems???

Thanks again for your help.

**Comment by slandelle** [comment]
Zinc is sbt’s incremental compiler, ie sbt is built on top of it. And so is scala-maven-plugin and Gatling.
