### ISSUE TITLE
HTTP: Set content type for StringBodyPart fails

### ISSUE THREAD

**Issue by jukkasi** [gatling/gatling#3682]
I'm trying to post multipart and I am unable to set content type for body part:

```
http("myRequest")
.put("/request")
.bodyPart(StringBodyPart("foo", "${fooVal}")
   .contentType(HttpHeaderValues.ApplicationJson)
)
.check(status.is(200))
```

but debug log shows that content type is always null for this StringBodyPart no matter whatever I set and my API doest no accept this request.

However, this works just fine:

```
http("myRequest")
.put("/request")
.bodyPart(StringBodyPart("foo", "${fooVal}")
   .header(HttpHeaderNames.ContentType, HttpHeaderValues.ApplicationJson)
)
.check(status.is(200))
```

I have just started using Gatling so it might be something I don't understand. Using Gatling version 3.0.3.

**Comment by slandelle** [comment]
You’re most likely confusing Body and BodyPart, which is for multipart. If so, please check the documentation.

**Comment by jukkasi** [comment]
If you mean that I should use body instead of bodyPart that is not what I am after.

My API accepts formdata/multipart request which can have two parts, other is "foo" parameter which needs to be application/json. Other part is file, which is not required in the request. 

My API fails if "foo" part content type is not set to application/json so it needs to be set correctly, and only latter code works.

**Comment by slandelle** [comment]
Ah OK. It wasn't clear as your sample only had one part.

Indeed, contentType wasn't honored on StringPart, because it doesn't make sense in form. But I agree it does make sense for multipart.

Fixing.

Thanks for reporting!
