### ISSUE TITLE
Add Comments section in documentation pages

### ISSUE THREAD

**Issue by krlinus** [gatling/gatling#3685]
For example, in this page:
https://gatling.io/docs/2.3/extensions/sbt_plugin/

There are many questions that arise for newcomers, like (referring to the above) "how do you specify a dependency", what is the role of the "projects" folder and where is it expected to reside and/or where/how/when do we specify the path to it, or what on earth is a .scala build

There is presently no place for users questions and they are left to fend for themselves. The documentation/tutorials never address learning as a ground up and functional activity, but let me plug my rant right about here

Comments section would go a good way for users crowdsource into making documentation actually more useful. Thanks

**Comment by slandelle** [comment]
First, please don't referrer to Gatling 2.3 documentation as Gatling 2 has reached end of life some time ago and is no longer maintained. Generally speaking, use current documentation, eg 
https://gatling.io/docs/current/extensions/sbt_plugin/, that referrer to current stable release (currently Gatling 3.0). If you check the updated version of this page, you'll realize we have a sample you can download and a giter8 based scaffolder.

Then, documentation is not the right place to ask questions. The community mailing list is. And documentation can indeed be contributed to. You can provide a PR to modify https://github.com/gatling/gatling/blob/master/src/sphinx/extensions/sbt_plugin.rst. On each page, there's a link named `CONTRIBUTE`.

Finally, why are you fixed about using sbt? sbt is a build tool for Scala developers and is most likely the hardest to grasp for newcomers. If you're not familiar with any JVM build tool, you should first stick to the bundle distribution. Have you checked the [installation guide](https://gatling.io/docs/current/installation) and gone through the [beginner](https://gatling.io/docs/current/quickstart/) and [advanced](https://gatling.io/docs/current/advanced_tutorial/) tutorials?
