### ISSUE TITLE
Core: uniformRandomSwitch with 6 possibilities sometimes executes nothing

### ISSUE THREAD

**Issue by aartajew** [gatling/gatling#3692]
Hi guys,

I think there is a bug in uniformRandomSwitch implementation - when you have i.e. 6 cases defined, sometimes no case is executed at all.

Steps to reproduce:
1. Get fresh gatling-sbt-plugin-demo project (Gatling v3.0.3)
2. Use below simulation:

```
class ComputerWorld extends Simulation {

  val computerDbScn = scenario("Uniform Random Switch Scenario")
    .forever() {
      exec(_.reset)

        .uniformRandomSwitch(
          exec(_.set("foo", 1)),
          exec(_.set("foo", 2)),
          exec(_.set("foo", 3)),
          exec(_.set("foo", 4)),
          exec(_.set("foo", 5)),
          exec(_.set("foo", 6))
        )

        .doIf("${foo.isUndefined()}") {
          exec(session => {
            println("++++++++++ FOO IS UNDEFINED ++++++++++")
            session
          })
        }
    }

  setUp(
    computerDbScn.inject(atOnceUsers(1))
      .protocols(http.baseUrl("http://computer-database.gatling.io"))
  )
}
```

3. Execute simulation, i.e. `sbt "gatling:testOnly *ComputerWorld"`

Actual:
There are many executions where variable `foo` is not defined after executing uniformRandomSwitch.

Expected:
uniformRandomSwitch should make sure to always execute one of defined cases.

Cheers,
Adam

**Comment by slandelle** [comment]
Thanks for reporting.
Would you be interested in contributing a fix?

**Comment by Jijka** [comment]
> Thanks for reporting.
> Would you be interested in contributing a fix?

Hi Stephane,
Can you explain how I can contribute fixes?
How to debug gatling and do any features? Maybe do you have some instructions?

**Comment by slandelle** [comment]
> Can you explain how I can contribute fixes?

For this issue, the best way is to implement a spec such as this one that reproduces the issue, and then validate the fix: https://github.com/gatling/gatling/blob/master/gatling-core/src/test/scala/io/gatling/core/action/IfSpec.scala

> How to debug gatling and do any features?

Regarding features, one critical thing is to discuss with us before implementing something so we can make sure that we would be interested in merging it, and that the implementation is correct.
Then, we'd require you to sign our CLA.
We definitively have to write this process down.

**Comment by slandelle** [comment]
FYI, I've just pushed a refactoring of `IfSpec` so this could be a good start for implementing `RandomSwitchSpec`.

**Comment by slandelle** [comment]
I know what the issue is: it's a Double to Int truncation issue.
I'm afraid fixing this is going to require some internal refactoring.

**Comment by aartajew** [comment]
I think there is a simpler solution, please see the comment below:

```  
def uniformRandomSwitch(possibilities: ChainBuilder*): B = {
    require(possibilities.size >= 2, "uniformRandomSwitch() requires at least 2 possibilities")

    val possibility1 :: tailPossibilities = possibilities.toList
    val basePercentage = 100d / (tailPossibilities.size + 1) 
    // now round basePercentage to 2 decimals only, the rest is fine
    val firstPercentage = 100d - basePercentage * tailPossibilities.size

    val possibilitiesWithPercentage = (firstPercentage, possibility1) :: tailPossibilities.map((basePercentage, _))

    randomSwitch(possibilitiesWithPercentage, None)
  }
```

**Comment by slandelle** [comment]
@aartajew As I said, I wasn't satisfied with the existing implementation. New ones looks way better (and has unit tests...).
