### ISSUE TITLE
Reports: show request info

### ISSUE THREAD

**Issue by Kricket** [gatling/gatling#3694]
In the report generated after a test, we see the names of the requests as given in the scenario.

However, no more detailed information is given as to the request itself (URL, headers, parameters...).

Is this an option? Would it be hard to add?

**Comment by slandelle** [comment]
Please use the community mailing list for questions, this is a bug tracker.

> Is this an option? 

No

> Would it be hard to add?

Impossible, the OSS reports are not meant for that.
You can lower logging level in logback.xml if you want to debug.
