### ISSUE TITLE
HTTP: lift header max size security

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3695]

**Comment by slandelle** [comment]
@diceytroop sbt publishLocal on [gatling](https://github.com/gatling/gatling) and then [gatling-highcharts](https://github.com/gatling/gatling-highcharts).

**Comment by diceytroop** [comment]
thanks so much! i'm running into this error mid-compilation -- i realize this really isn't what these issue threads are for, though, so if there's another place where you'd suggest i post newb questions like this please let me know.

```
[info]  published ivy to C:\Users\tfitzgerald\.ivy2\local\io.gatling\gatling-core\3.1.0-SNAPSHOT\ivys\ivy.xml
[error] java.lang.IllegalStateException: Ivy file not found in cache for io.gatling#gatling-bundle;3.1.0-SNAPSHOT!
```

**Comment by slandelle** [comment]
Please ask on our [community mailing list](https://gatling.io/community-mailing-list/).

**Comment by davidwestonuk2000** [comment]
Hi, please can I understand when this version will be released? Thanks

**Comment by slandelle** [comment]
Beginning of next week. Next time, please use the community mailing list for questions.
