### ISSUE TITLE
Pace (Gatling 3.0.X)

### ISSUE THREAD

**Issue by HenkLengkeek** [gatling/gatling#3701]
Hi all

Currently we can use the **pace** method when combined with a loop or a during statement.

Examples:

repeat (10) {
   pace (60)
   .exec (<....>)
}

or

during (120 seconds) {
    pace (60)
    .exec (<....>)
}

We would expect that pace could be used on it's own in a scenario like:

  val scn = scenario("BasicSimulation")
    .pace(60 seconds)
    .exec(http("Open page")
        .get("/")) // 9

Not sure to report this as a bug or a wish.

**Comment by slandelle** [comment]
Pace must be used with a loop. It means "a given virtual user mustn't go through this step again sooner than given duration".

**Comment by HenkLengkeek** [comment]
> Pace must be used with a loop. It means "a given virtual user mustn't go through this step again sooner than given duration".

I am aware of the definition of pace but thanks for confirming that :)

I agree that pace should be part of a loop (during being a time-based loop), however in the case we run a scenario with constantConcurrentUsers(10) during (3600 seconds) there is already a loop and that poses the question why the loop should be defined twice.

**Comment by slandelle** [comment]
There’s no loop involved in closed workload model. When a user terminates, a new one starts with its own fresh state, connections, cookies, cache, etc.
