### ISSUE TITLE
Core: JsonPath doesn't properly scan objects in objects

### ISSUE THREAD

**Issue by asaarilahti** [gatling/gatling#3703]
Jsonpath expressions with wildcards do not produce matches. For example: `jsonPath(" $.abc.*.def").findAll`

Can be reproduced (latest master, macOS Mojave, both Java 8 and Java 11) by:
- applying this: https://github.com/asaarilahti/gatling/commit/c259e3bc9cf825589f52e6cd4a7741502fc7e739
- sbt gatling-http/test

**Comment by slandelle** [comment]
Thanks for reporting!
I could track this down to https://github.com/oblac/jodd/pull/696
