### ISSUE TITLE
Core: Measurement in microseconds

### ISSUE THREAD

**Issue by sdoeringNew** [gatling/gatling#3704]
A fast application can handle requests within a few milliseconds or even less. Further optimization can be done but not be measured with Gatling.

e.g.:
The average response time for an application is now 3.4ms. After the optimization it is 3.1ms. A major performance improvement of ~10%. But Gatling can't measure it because it only returns times in milliseconds. Before the optimization the average time is 3ms, after the optimization it is still 3ms.

Please add a possibility to output the result in microseconds.

**Comment by slandelle** [comment]
Honestly, this would require a lot of work to support across our whole stack.
If your company is interested in sponsoring this feature, please reach out at contact at gatling dot io so we can discuss this.
Otherwise, I don't think we'll support this any time soon.

**Comment by slandelle** [comment]
Unlikely to be implemented any time soon. Closing for now.
