### ISSUE TITLE
Recorder: resource files are always dumped to root possibly overwriting files from a different class

### ISSUE THREAD

**Issue by pmalic** [gatling/gatling#3706]
Resource files (*request.txt/*response.txt) are always dumped to root of resources folder even when you supply a package name in Recorder. The resource files only contain the class name in their names so you can't have two classes with the same name in different packages because the resource files would be overwritten.

Wouldn't it make more sense to dump them into a subfolder named after the package name, just as is the case with .scala file?

I can of course manually create a subfolder under resources folder, move the resource files into it and change the paths in the .scala file, but this happening automatically would be great and would prevent someone mistakenly overwriting their resource files.

**Comment by slandelle** [comment]
Looks like a good idea.
Willing to contribute?

**Comment by pmalic** [comment]
This is in gatling-recorder/src/main/scala/io/gatling/recorder/scenario/ScenarioExporter.scala, right?

Basically, transform requestBodyFileName and responseBodyFileName to be like simulationFilePath?

I haven't coded anything in Scala so far, but this seems fairly simple, I'd like to try :)

**Comment by pmalic** [comment]
Fixed by 7652b6ad8e661e8aef102f405b32c11a58d88b2c
