### ISSUE TITLE
HTTP: reverse proxy that requires client certificates

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3712]
Investigate https://groups.google.com/forum/#!topic/gatling/2d5rkY98my8

**Comment by slandelle** [comment]
@Neoware can you have a look please?

**Comment by hxtpoe** [comment]
@Neoware @slandelle It was working in Gatling 2.x . I was able to use client certificate with Gatling. 
Here is my answer to Matthias problem https://stackoverflow.com/a/58858267/2594499

**Comment by slandelle** [comment]
Thanks. Closing.
