### ISSUE TITLE
HTTP: WebSocketHandler doesn't flush Pong messages

### ISSUE THREAD

**Issue by jstermask** [gatling/gatling#3715]
Websocket server side use to sends "ping" to websocket clients and expect a pong as a reply to check that connection is still alive.
However, current WebSocketListener abstract class and its scala implementation only offers onPong.
 We should implement both onPing and onPong on listener and implement onPing to send a Pong.

**Comment by slandelle** [comment]
Why? Gatling automatically replies to ping frames with pong ones: https://github.com/gatling/gatling/blob/master/gatling-http-client/src/main/java/io/gatling/http/client/impl/WebSocketHandler.java#L139

Looks like the expected behavior to me.

**Comment by slandelle** [comment]
Ah, there’s probably an issue. It probably should be a writeAndFlush and not just a write there.

**Comment by jstermask** [comment]
Hello,

Here is an example : let's consider a websocket endpoint offered by a
microservice in the cloud (let's say a chat). Each connected client opens a
websocket session that usually take some resources on server side. Some
real life experiences showed us that these clients sometimes disconnect
while server side state still "thinks" that its client is connected and
therefore it doesn't free some resources.

To circumvent this issue, we use to implement a ping long initiated from
the server side. Microservice sends a ping from time to time and expects
its Client to listen to "onPing" and reply a Pong to server.

This is in place and now I'm using Gatling to simulate some clients.
However these client do never answer to server pings. Server side then
disconnect them all. While checking into the source code I think that it's
because Gatling web socket listener only listens to onPong messages as of
today.
By listening to onPing and replying Pong, it'll solve the issue.

I may try to do a pull request on that. However I'm not used to sbt(yet).

Do you think it's something relevant to fix or add to Gatling. For us it
would really be great

**Comment by slandelle** [comment]
Please properly read my previous answers.

**Comment by jstermask** [comment]
Oups you're right on that. Pong should just be flushed.

I'll have to rewrite the issue title to be more meaningful

**Comment by jstermask** [comment]
Hello,

Just to let you know that i fixed gatling code in my local workstation and tested the change (replace write by writeAndFlush). Now, my gatling simulation works perfectly and my clients don't get disconnected. So I confirm that you spotted the root cause and that we need to writeAndFlush pong so that it is taken into account.
