### ISSUE TITLE
scenarios execute in a group doesn't show statistics

### ISSUE THREAD

**Issue by houchj** [gatling/gatling#3725]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [ x ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [ x ] Check that you can reproduce your issue with latest Gatling version
  * [ x ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version).   There was a similar one: https://github.com/gatling/gatling/issues/886, it was closed without solution. But I think this is easy and valuable.
  * [ x ] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
The sample code is like this:
  val query2 = scenario("query2").
    exec(
      group("query-002") {
        exec(karateFeature("classpath:workers-query2.feature"))
      }
    )
* Regarding feature requests:
  * [ x ] Explain your use case, not the implementation you have in mind.
           Without this fix, in the report you only group the requests by the end point, for example xxx/Workers, but we have different query cases, some need to test expand by a special child entity, and some need to add special filter, and we need to statistics by the group, not all calculated in one group which is by api end point(xxxx/Workers)

![2019-05-07](https://user-images.githubusercontent.com/9351624/57268283-c94a6c00-70b5-11e9-80a8-e560d51f447c.png)

**Comment by slandelle** [comment]
What you’re using is Karate, which has nothing to do with genuine Gatling.
Please open an issue against it, not here.
