### ISSUE TITLE
Allow feeder value in cookie domain

### ISSUE THREAD

**Issue by grib0** [gatling/gatling#3727]
It seems that feeder values are not accepted in the withDomains cookie.

Step to reproduce:

Feeder:
cookies.csv
```
cookie_value,cookie_domain
foo,bar
```

Simulation:
```
val scn = group("Connexion") {

        feed(csv("cookies.csv").circular)
        .exec(addCookie(Cookie("MY_COOKIE", "${cookie_value}").withDomain("${cookie_domain}")))
        .exec(http("Login")
            .post("http://myserveradresse.test/myapp")
[...]
````

In the log I have :

```
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Login
=========================
Session:
Session(1557238869132,Map(cookie_value -> foo,  cookie_domain -> bar,  gatling.http.cookies -> CookieJar(Map(CookieKey(jsessionid,myserveradresse.test,/myapp) -> StoredCookie(JSESSIONID=z9-Sq4J-kvb1ahayiZB4jwbDLxK3T2OPSb4nDh28DQ5_j0o_LMYq!927322653, path=myapp, HTTPOnly,true,false,1557238874746), 
CookieKey(MY_COOKIE,${cookie_domain},/) -> StoredCookie(MY_COOKIE=foo, domain=${cookie_domain},false,false,1557238874357), 
=========================
HTTP request:
POST http://myserveradresse.test/myapp
headers=
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Pragma: no-cache
cookie: JSESSIONID=z9-Sq4J-kvb1ahayiZB4jwbDLxK3T2OPSb4nDh28DQ5_j0o_LMYq!927322653
host: myserveradresse.test
content-type: application/x-www-form-urlencoded
content-length: 289
cookies=
JSESSIONID=z9-Sq4J-kvb1ahayiZB4jwbDLxK3T2OPSb4nDh28DQ5_j0o_LMYq!927322653, path=myapp, HTTPOnly
[...]
```
thus the cookie is not added in the request as the domain is not correctly set.

**Comment by slandelle** [comment]
What's your use case exactly? Could you please elaborate on why you need dynamic cookie domains?

**Comment by grib0** [comment]
I'm trying to simulate the real behavior of an app that I need to stress test.
This app set a cookie from server. The servers are many so we defined them in a feeder for round robin.

I would like to have a workaround like `withDomain(session("cookie_domain").asString)` but it does not work neither.

**Comment by slandelle** [comment]
> The servers are many so we defined them in a feeder for round robin.

Sorry, but I still don't get it.
If you have a cluster of servers, typically behind a load balancer or with DNS roundrobin, they still serve the same domain.
Are you saying those servers serve different domains?

**Comment by grib0** [comment]
Yes you are right, there should be a load-balancer or a dns configured doing the round robin, but, because of a load balancer issue in our perf environnement we defined the servers with differents domains in a server feeder.
The servers are
instance-a.myservername.test
instance-b.myservername.test
[...]
OK, I just realized that setting myservername.test as domain worked !
Thank you very much for the input, I'm closing the ticket

**Comment by slandelle** [comment]
Great!

**Comment by grib0** [comment]
Sorry, I think I closed the ticket too early, even if I don't need the instance-a prefix, the simulations I'm launching have differents domains depending on parameter, so I still need to insert myserver.test in withDomain from feeder, or session value or parameter.
Or maybe I should try to set baseUrl ?

**Comment by slandelle** [comment]
> Or maybe I should try to set baseUrl ?

Yes. Don't use a feeder, use `baseUrls` to let Gatling do the roundrobin between your cluster nodes and don't specify cookie's domain so Gatling with use the picked baseUrl.

**Comment by grib0** [comment]
Should work in 3.3.0 thanks to #3792
