### ISSUE TITLE
value get is not a member of io.gatling.core.session.Session with latest gatling 3.1.1 (Sacala 2.12) and open jdk 11

### ISSUE THREAD

**Issue by PriaReddy** [gatling/gatling#3730]
Hi, 
I have upgraded gatling to latest version and when compiled, these errors pop up
- [main] ERROR io.gatling.compiler.ZincCompiler$ - C:\git\somepath\gatling\user-files\simulations\tests\Test1.scala:43:41: value get is not a member of io.gatling.core.session.Session

**Comment by notdryft** [comment]
Hi, please use the community mailing list for this kind of problem, unless you are sure it is a bug.

Also, while you do that, provide some code that can help us find a solution to your issue.

**Comment by slandelle** [comment]
See [doc update](https://github.com/gatling/gatling/commit/d589d9fc9c74b99492a8a8b1a721d76b2d25b6a4) (to be published) and related issue #3189.

**Comment by slandelle** [comment]
This syntax has never been correct in the first place, see https://github.com/gatling/gatling/issues/3402#issuecomment-492161051
