### ISSUE TITLE
Gatling seems not to search file in src/resrouces/bodies with maven plugin activation. 

### ISSUE THREAD

**Issue by aygalinc** [gatling/gatling#3734]
Hi,

I use maven with 

` <dependencies>
    <dependency>
      <groupId>io.gatling.highcharts</groupId>
      <artifactId>gatling-charts-highcharts</artifactId>
      <version>3.1.2</version>
    </dependency>
    <dependency>
      <groupId>io.gatling</groupId>
      <artifactId>gatling-app</artifactId>
      <version>3.1.2</version>
    </dependency>
    <dependency>
      <groupId>io.gatling</groupId>
      <artifactId>gatling-recorder</artifactId>
      <version>3.1.2</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-maven-plugin</artifactId>
        <version>3.0.2</version>
      </plugin>
    </plugins>
  </build> `
and the project structure is like the one generated with maven archetype: 

`
/modulename
pom.xml
/src/test/resources/bodies/update.raucb
src/test/scala/Engine
src/test/scala/Recorder
src/test/scala/IDEPathHelpers
src/test/scala/com.se.gxl.integration.firmware/BasicSimulation
`
My simulation is : 
`
package com.se.gxl.integration.firmware

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class BasicSimulation extends Simulation {

  val httpProtocol = http
    .baseUrl("http://localhost:8080") // Here is the root for all relative URLs
    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8") // Here are the common headers
    .acceptEncodingHeader("gzip, deflate")
    .acceptLanguageHeader("en-US,en;q=0.5")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")

  val scn2 =
    scenario("Firmware Update Request") // A scenario is a chain of requests and pauses
      .exec(
      http("Create contentV2")
        .post("/firmware")
        .bodyPart(
          RawFileBodyPart("update.raucb")
            .contentType("image/jpeg"))
        .asMultipartForm
        .check(status is 200))

  setUp(scn2.inject(atOnceUsers(1)).protocols(httpProtocol))
}
`

With this I got : 
`
imulation com.se.gxl.integration.firmware.BasicSimulation started...
18:32:36.068 [ERROR] i.g.h.a.HttpRequestAction - 'httpRequest-1' failed to execute: Resource update.raucb not found

================================================================================
2019-05-16 18:32:36                                           1s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=0     )

---- Errors --------------------------------------------------------------------
> Create contentV2: Failed to build request: Resource update.rau      1 (100,0%)
cb not found 
`

If i put the absolute path of the update.raucb, simulation is well launch with mvn gatling:test

As stated by the doc it not seems that gatling try to find RawBodyFile in bodies directory no ?

**Comment by slandelle** [comment]
`bodies` directory was dropped as of Gatling 3.0, see https://gatling.io/docs/current/migration_guides/2.3-to-3.0/.

There's a chance you're referring to obsolete documentation.
