### ISSUE TITLE
Gatling-Jms publisher is throwing exception

### ISSUE THREAD

**Issue by pallapothurameshbabu** [gatling/gatling#3747]
Hi, I am trying to publish messages to tibco topic using below code, which is throwing exception.
Could you please help me on this ?

import java.util.{Hashtable => JHashtable}
import io.gatling.core.Predef._
import io.gatling.jms.Predef._
import javax.jms._

import scala.concurrent.duration._
import javax.jms.ConnectionFactory
import javax.naming._

import scala.collection.mutable._
import com.fedex._
import javax.jms.Connection
import javax.jms.JMSException
import javax.naming.Context
import javax.naming.InitialContext
import javax.naming.NamingException
import java.util.Hashtable

import io.gatling.core.config.GatlingConfiguration

import scala.collection.mutable
//import io.gatling.core.config.Credentials
class TestJmsScala extends Simulation {

val requestTopic = topic("XXXXXXXXXXXXXXXXXXXXXX")

val jmsConfig = jms
.connectionFactory(
jmsJndiConnectionFactory
.connectionFactoryName("CF")
.url("url")
.contextFactory("ctxf")
).credentials("user", "pwd")

val scn = scenario("JMS DSL test").repeat(1) {
exec(jms("req reply testing").requestReply
.destination(requestTopic)
.textMessage("hello from gatling jms dsl")
)
}
setUp(scn.inject(rampUsersPerSec(1) to 10 during (1 minutes)))
.protocols(jmsConfig)
def checkBodyTextCorrect(m: Message) = {
m match {
case tm: TextMessage => tm.getText == "HELLO FROM GATLING JMS DSL"
case _ => false
}
}
}

Exception :

javax.jms.InvalidDestinationException: Not allowed to create destination
at com.tibco.tibjms.Tibjmsx.buildException(Tibjmsx.java:577)
at com.tibco.tibjms.TibjmsxSessionImp._createProducer(TibjmsxSessionImp.java:1075)
at com.tibco.tibjms.TibjmsxSessionImp.createProducer(TibjmsxSessionImp.java:5068)

**Comment by slandelle** [comment]
> javax.jms.InvalidDestinationException: Not allowed to create destination

Looks like your connection user doesn't have permissions to create temporary queues. Either grant the user correct permissions, or use a permanent queue for the `replyQueue`.

Next time, please don't use our bugtracker for questions, use our community mailing list.
