### ISSUE TITLE
GRPC: grpcResponse.find.exists preparation crashed: UNAVAILABLE: HTT P/2 error code: NO_ERROR Received Goaway

### ISSUE THREAD

**Issue by ducquyen2509** [gatling/gatling#3748]
When I load the test with 1000req / s within 60 seconds, there is always an error.
However, when I reduce the number of requests, everything is fine. I do not know why. Please help me.
Client:
val grpcConf = grpc(ManagedChannelBuilder.forAddress(grpcSV, port)).shareChannel
  val scn = scenario(this.getClass.getName)
    .feed(myFeeder)
    .exec(
      grpc(this.getClass.getName)
        .rpc(ZPBaseGrpc.METHOD_SEND_REQUEST)
        .payload(GrpcBaseRequest.newBuilder().setMethodName("core/cashin").putAllParams(mapAsJavaMap(myFeeder.next)).build())
        .check(extract { c: GrpcBaseResponse => c.getResponse.some } saveAs "response")
        .check(statusCode is Status.Code.OK)
    ).exitHereIfFailed
    .exec(session => {
        myLogger.info("response data: %s\n".format(session("response").as[String]))
      session
    })
  setUp(
    scn.inject(
      constantUsersPerSec(configs.getInt("common.injectUserPerSec"))
        during (configs.getInt("common.injectDuring") seconds),
    )
  )

**Comment by slandelle** [comment]
We don’t have gRPC support, you’re using a third party plugin, please ask there.

**Comment by phiSgr** [comment]
Sorry for digging up an old post. Author of the third party plugin here. I was looking for another discussion and saw this.

@ducquyen2509, I am going to be really blunt with you here.

I originally allowed questions in my issue board. Then I received questions like yours, in which I had to 
1. fish for information, and
2. assume you didn't even looked at your code

to close the issue.

Our software is free, but our time is not. This time you ask another stranger to debug your problem with nothing but your test code. That’s not how open source works. That’s not how any of this works.

**Comment by expe-elenigen** [comment]
@phiSgr Hi, sorry in advance for highjacking this thread, but I noticed you have deprecated your project and after migrating to the new gatling grpc client integration, I found out that we need to be using the enterprise version otherwise we are cap at 5 users for 5min max. Would you reconsider your decision about deprecating this project? Couldn't someone take instead the lead?
Thank you!
