### ISSUE TITLE
Link to Frontline is not active

### ISSUE THREAD

**Issue by Jijka** [gatling/gatling#3751]
On web page https://gatling.io/docs/current/  element 

`<img alt="FrontLine" src="/docs/3.1/_images/frontline-logo.svg" width="40%" class="lazyloading" data-was-processed="true"> `

refer to https://gatling.io/docs/current/_images/frontline-logo.svg 404 page

`<a class="reference internal image-reference" href="https://gatling.io/docs/current/_images/frontline-logo.svg"><div align="center" class="align-center"><img alt="FrontLine" src="/docs/3.1/_images/frontline-logo.svg" width="40%" class="lazyloading" data-was-processed="true"></div> </a>`

**Comment by slandelle** [comment]
Thanks!

**Comment by slandelle** [comment]
Fixed, thanks!
