### ISSUE TITLE
On new site version impossible change version of docs 

### ISSUE THREAD

**Issue by Jijka** [gatling/gatling#3752]
https://gatling.io/docs/current/ header is lower than breadcrumb

![image](https://user-images.githubusercontent.com/11795372/59750227-2295e580-9287-11e9-9608-6a69b03ad8e3.png)

**Comment by slandelle** [comment]
Thanks for reporting (NB: issue only happens with FireFox).

**Comment by Jijka** [comment]
Chrome Version 74.0.3729.169 too

**Comment by slandelle** [comment]
> Chrome Version 74.0.3729.169 and 75.0.3770.100

Works for me with those versions o_O

**Comment by slandelle** [comment]
Fixed, thanks!

**Comment by Jijka** [comment]
good
