### ISSUE TITLE
ElFileBody in bytesMessage for the JMS

### ISSUE THREAD

**Issue by pallapothurameshbabu** [gatling/gatling#3755]
Hi,

If I use, textMessage and ElFileBody, i am able to feed specific values into my xml from csv but if I do the same using bytesMessage and RawFileBody, it is taking the xml as is and not feeding the csv values. Am I missing something??

This works but it returns a textMessage 

feed(csv("data/id_data.csv").circular).exec(jms("req reply testing").send.destination(requestTopic).textMessage(ElFileBody("bodies/request.ssp"))

**but I want bytesMessage and this gives me the xml as is and does not replace values inside it from csv.**

feed(csv("data/mydata.csv").circular).exec(jms("req reply testing").send.destination(requestTopic).bytesMessage(RawFileBody("bodies/request.ssp"))

**Is this defect ? If not could you please help me to post dynamic bytesMessage to JMS.**

Here is my code

**val requestName = "contactNotify.ssp"
  val contactId = csv("contactId.csv").circular
  val scn = scenario("JMS DSL test").repeat(1) {
    feed(contactId)
      .exec(jms("req reply testing")
        .send
        .destination(requestTopic)
        .bytesMessage(ElFileBody(requestName)) // compilation error
        .property("operation", "delete")
        .jmsType("test_jms_type"))
    // .check(simpleCheck(checkBodyTextCorrect)))
  }**

Thanks,
Ramesh

**Comment by slandelle** [comment]
Gatling Expression Language is **text** based. Why would you want to use a text message as a binary payload in the first place?!

**Comment by pallapothurameshbabu** [comment]
Hi Stephen,

Than you for responding, in our org we are not allowed to publish textMessage to JMS, it is always expected to publish bytesMessage. i am able to publish static bytesMessage using RawFileBody but i want to send dynamic bytesMessage . could you please help me on this ? 

Thanks,
Ramesh.

**Comment by slandelle** [comment]
My name is Stéphane, not Stephen.

`ElFileBody` extends `Session => Validation[String]` so you can convert the result from String to bytes:

```scala
.bytesMessage(ElFileBody("file").andThen(_.map(_.getBytes(StandardCharsets.UTF_8))))
```

Now, again (as you've already done that in the past), don't use the bug tracker for asking for help.
If answers don't come fast enough for you on the community mailing list, please consider contracting with our for consulting.
