### ISSUE TITLE
Gatling Jenkins Pipeline - Users executes 1 iteration of request during whole test duration

### ISSUE THREAD

**Issue by myanees284** [gatling/gatling#3772]
We are running a Gatling test using maven in Jenkins pipeline for the test duration of 5 minutes with 5 users with 1 request and pacing of 1 second.

The issue which we are facing is, each user fires single request and does not do anything. i.e Totally we could see only 5 requests were fired. Ideally it should execute as many times within the test duration of 5 minutes.

This happens only if we run this in the Jenkins pipeline with Jenkins agent container (with nodejs 10).
If the test is executed locally outside of Jenkins, the execution happens as expected.
Below is the maven command we use:
**mvn clean gatling:execute -Dtestduration=5 -Dtestpack=Contentservicev1.json**

**Gatling version: 2.0.0-RC1
Scala version: 2.10.4**

**Comment by slandelle** [comment]
This gatling version wasn't even a stable release (RC = Release Candidate) and generally speaking, Gatling 2 has reached end of life last year. Please upgrade to latest Gatling 3 (3.2.0 is about to be released).
