### ISSUE TITLE
Gatling 3.1.3 Hangs the Taurus console in Mac

### ISSUE THREAD

**Issue by narendra15** [gatling/gatling#3778]
I upgraded gatling-taurus to 3.1.3 and the Taurus console hangs and the tests never complete in Mac. Where in the same scripts with the same version of gatling 3.1.3 works fine in windows.

Please help me understand if there is any fix for Mac required or any work around for Mac for the scripts to work.

**Comment by slandelle** [comment]
Taurus is not an official component and is not supported.
As you said, things work fine with genuine Gatling.

**Comment by narendra15** [comment]
I didn't get you. So you mean Gatling latest version 3.1.3 doesn't support Taurus?. If so please let me know how it works in Windows and not in Mac.

**Comment by slandelle** [comment]
Taurus is not a component from Gatling, use at your own risks.
You won't find any support for it here.
