### ISSUE TITLE
No logs after running the first simulation from list

### ISSUE THREAD

**Issue by Tikani** [gatling/gatling#3780]
Gatling version: 3.2.0
Hi! I have a case when I need to filter simulation by custom attributes (custom annotation with specific value, a list of names of simulation to launch in args, etc.), so I wrote a code which scans classpath, making a subset of simulations with predicate. And after that I wrote another piece of code, which launches simulations one by one:

`def runMultipleSimulations(): Unit = {
      simulations.filter(simulation => {
          val doesCurrentSimulationInArgs = args.contains(simulation.getCanonicalName)
          logger.debug(s"Simulation ${simulation.getCanonicalName} is in args $doesCurrentSimulationInArgs")
          doesCurrentSimulationInArgs}).foreach(launchSimulation)
 }`

    def launchSimulation(simulation: Class[Simulation]): Unit = {
      val props = new GatlingPropertiesBuilder
      props.simulationClass(simulation.getCanonicalName)
      println(s"##teamcity[testStarted name='${simulation.getSimpleName}']")
      Gatling.fromMap(props.build) match {
        case 0 => println(s"##teamcity[message text='Simulation is successful' status='NORMAL']")
        case 1 => println(s"##teamcity[testIgnored name='${simulation.getSimpleName}' message='Simulation has been ignored because of invalid parameters']")
        case 2 => println(s"##teamcity[testFailed name='${simulation.getSimpleName}' message='Simulation has been failed by assertion']")
      }
      println(s"##teamcity[testFinished name='${simulation.getSimpleName}']")
    }
All seems OK - simulations run sequentially, reports are generated, but with an issue - all subsequent simulations but first brings to STDOUT only output from **io.gatling.core.stats.writer.ConsoleSummary**  object, logs from **StrictLogging** trait's logger  are not passed to STDOUT at all.
I've investigated it a bit and found something suspicious in **io.gatling.app.Gatling** in private method `private[app] def start(overrides: ConfigOverrides, selectedSimulationClass: SelectedSimulationClass)` with very confusing piece of code:
`} finally {
      val factory = LoggerFactory.getILoggerFactory
      try {
        factory.getClass.getMethod("stop").invoke(factory)
      } catch {
        case _: NoSuchMethodException => //Fail silently if a logging provider other than LogBack is used.
        case NonFatal(ex)             => logger.warn("Logback failed to shutdown.", ex)
      }
    }`

What is the sense to do away with the Logback logging engine after running a single simulation? **io.gatling.app.Gatling** methods **fromArgs**/**fromMap** are designed as one-shot actions?

**Comment by slandelle** [comment]
Gatling’s architecture expects 1 fresh JVM per simulation so we make sure to free resources and always start with fresh ones.
