### ISSUE TITLE
Gatling EL being able to cast when retrieving session attributes OR jsonPath to save the response as certain type

### ISSUE THREAD

**Issue by sqilz** [gatling/gatling#3789]
I have ran into this problem recently where I gather values from a response **payload** in my case, using `jsonPath.findAll.saveAs("sampleIds")`

`{"itemsResponses":[{"status":"SUCCESS","payload":"32cf3d50-4aa2-41e7-955e-33793297d83c"},{"status":"SUCCESS","payload":"30f0f5a9-eba8-4f26-921e-445065387ce2"}] }`

however when I try to pass "Ids" to my case class
`case class sampleRequest[T] (
    samplesIds: Seq[T]
)`

with 
`
http(s"$requestName")
            .put(SAMPLE_FILTER_ENDPOINT)
            .headers(headers)
            .body(StringBody(Json.toString(QuerySampleRequest[String]("${sampleIds.jsonStringify()}"))))
            .asJson
            .check(
                status.is(OK.code())
            )`

the generated body looks like `"samplesIds" : "["id","id2", ...]"` and when I do it without jsonStringify I get  `"samplesIds" : "Vector(id, id2, ...)"`

and I'm attempting to get a `"samplesIds" : ["id", "id2", ...]`

I was thinking that it would be a good feature to gatling EL where a type could be specified/cast, e.g. `"${samplesIds.asList()}"` to return a list, or something similar to just return a string of Vector contents so it would be then possible to wrap that into a list or use it raw.

I have been struggling with this since friday and doing research without finding a solution.
Using gatling 3.2.0

**Comment by slandelle** [comment]
Please check the documentation: https://gatling.io/docs/current/session/expression_el/

```
Warning

This Expression Language only works on String values being passed to Gatling DSL methods. Such Strings are parsed only once, when the Gatling simulation is being instanciated.

For example queryParam("latitude", session => "${latitude}") wouldn’t work because the parameter is not a String, but a function that returns a String.

Also, queryParam("latitude", "${latitude}".toInt) wouldn’t because the toInt would happen before passing the parameter to the queryParam method.
```

This is exactly what you're trying to do. Only Gatling DSL methods can resolve String parameters with EL expression. How could `QuerySampleRequest`'s constructor possibly resolve it?

You have to pass a function, give up on Gatling EL and manually fetch data from Session.

Next time, please use the community mailing list for questions, not the bug tracker.
