### ISSUE TITLE
HTTP: getCookieValue withDomain does not accept an EL expression 

### ISSUE THREAD

**Issue by peterox** [gatling/gatling#3792]
My use case is the ability to test multiple URL's that actually resolve to the same multi-tenant application. I created a feeder that supplies a username and password as well as a baseUrl. 

The problem is that I want to extract a Cookie value to post in subsequent requests (XSRF protection) but I can't pass the value from the feed to the withDomain method.

```scala
    var login = exec(
        http("Authenticated")
          .get("${url}/api/v1/users/authenticated").asJson
          .check(status.is(403))
      )
      .exec(
        getCookieValue(
          CookieKey("XSRF-TOKEN")
            .withSecure(true)
            .saveAs("XSRF")
            .withDomain("${url}") <-- DOESN'T WORK
        )
      )

```

The error message I see is 

``` No Cookie matching parameters domain=${url}, path=/, name=XSRF-TOKEN, secure=true```

Is this something that can be fixed please

**Comment by slandelle** [comment]
Can't you rely on Gatling to automatically send stored cookies based on domain and path?

**Comment by peterox** [comment]
The XSRF mechanism relies on reading the value of a cookie and sending it in a header. So the missing bit is:

```scala
.exec(
        http("Login")

          .post("${url}/api/v1/users/signin")
          .header("X-XSRF-TOKEN", "${XSRF}")
          .body(StringBody("""{ "Name": "${username}" , "UnsecurePassword": "${password}"}""")).asJson
      )
```

I therefore need to be able to read the cookie using the URL supplied by the CSV feeder.

**Comment by slandelle** [comment]
Makes sense then.
Interested in contributing? https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/action/cookie/GetCookieValueBuilder.scala
