### ISSUE TITLE
maxDuration doesn't seem to work

### ISSUE THREAD

**Issue by ianynchen** [gatling/gatling#3794]
I used the following code to try to ramp up a bunch of users, let users reach maximum and maintain that request per second level for a while:

>     setUp(scn.inject(rampUsersPerSec(10) to(200) during(1 minute))).protocols(httpProtocol).maxDuration(5 minutes)

and it doesn't seem to work. So how does maxDuration work and when it takes effect? Instead of the test running for the expected 5 minutes, it completes in 1 minute.

then I tried to following as shown in your example:

>     setUp(scn.inject(rampUsers(200) during(1 minute))).protocols(httpProtocol).maxDuration(5 minutes)

again, the simulation finished in 1 minute instead of the expected 5 minutes.

**Comment by slandelle** [comment]
From [maxDuration's documentation](https://gatling.io/docs/current/general/simulation_setup/?highlight=maxduration#maximum-duration):

> It is useful if you need to bound the duration of your simulation when you can’t predict it.

`maxDuration` abruptly forces a run to terminate on a time limit, even though virtual users are still running.
It doesn't make your run last longer.
Virtual users lifespan is determined by their scenario.
