### ISSUE TITLE
How to handle non request-response websocket communication

### ISSUE THREAD

**Issue by nosalan** [gatling/gatling#3795]
This is a question.
In my scenario, the client sends messages to a websocket server at a constant rate. The server consumes the messages, however, it does not reply after each client message. Instead, the server replies when it decides to do so, independently of client messages, until it closes the session.

So sending is easy, but how do I listen to server messages in a way that does not block the sending? E.g. I would like to store the server replies without any checks in a list or file with the reception timestamp. 

Is it possible?

**Comment by slandelle** [comment]
> how do I listen to server messages in a way that does not block the sending

That's not supported atm.

This would require a lot of work so there's no plan to support this atm. The best way to have such feature happen would be to sponsor it.

Closing for now. Will reopen if it moves forward.

**Comment by nosalan** [comment]
Thanks for info. It would be nice to have someday since all speech-to-text engines work over websocket that way.
