### ISSUE TITLE
Question: Why number of active users high when begin to run test? 

### ISSUE THREAD

**Issue by thinkerou** [gatling/gatling#3802]
Sorry!
Because I always fail when I add one post to https://groups.google.com/forum/#!forum/gatling, I add the issue here.

![image](https://user-images.githubusercontent.com/4488261/65593773-cb10bf80-dfc3-11e9-819f-412a603b160f.png)

my code:

```
class shop extends Simulation {

  val userCount = 50000
  val duringTime = 180
  val url = http.baseUrl("https://www.xyz.com")

  val headerInfo = Map(
    "Accept" -> "application/json",
    "Cookie" -> "token=${token}",
    "Content-Type" -> "application/json"
  )

  def getPurchaseLimitCountFromDetail = scenario("getPurchaseLimitCountFromDetail")
    .feed(user)
    .exec(
      http("getPurchaseLimitCountFromDetail")
        .get("/rest/app/detail?item=123")
        .headers(headerInfo)
        .check(status.is(200))
    )

  var setUpList = List[PopulationBuilder]()

  setUpList :::= List(getPurchaseLimitCountFromDetail.inject(constantUsersPerSec(userCount) during (duringTime)).protocols(url))

  setUp(setUpList)

}
```

and result picture:

![企业微信截图_a54d2dcd-ae5f-440b-a910-33917ed2ef2e](https://user-images.githubusercontent.com/4488261/65593276-b5e76100-dfc2-11e9-9f40-27f6557cbc9a.png)

Why number of active users high when begin to run test?  thanks!

**Comment by slandelle** [comment]
It looks like Google Groups is having issues lately and issues error message while your message is actually posted, see https://groups.google.com/forum/#!topic/gatling/vOkl8u7xrbE.

The Google Group is indeed the right place for such question.

**Comment by thinkerou** [comment]
@slandelle thanks!
