### ISSUE TITLE
gatling-sbt: Unable to find recorder.conf on SBT 1.3.x

### ISSUE THREAD

**Issue by alextsc** [gatling/gatling#3803]
**Observed behavior**

The gatling-sbt plugin fails to load an existing recorder.conf file when using the startRecorder task on newer sbt versions. I encountered this issue with sbt 1.3.0 and 1.3.2 specifically, presumably any 1.3.x version is affected.

**Steps to reproduce**

1. Clone https://github.com/gatling/gatling-sbt-plugin-demo/ at 49091beb8b36e7daaa10cda6a98f51418ecdc9e5 (current head of master). This comes with sbt 1.2.8 preconfigured.
2. Edit project/build.properties and change the sbt version to 1.3.0 or 1.3.2
3. Edit src/test/resources/recorder.conf and change a config key to a non-default value
4. Run "sbt gatling:startRecorder" in the project root

You'll see the following output:

```
> sbt gatling:startRecorder
[info] Loading settings for project global-plugins from metals.sbt,idea.sbt ...
[info] Loading global plugins from /home/alextsc/.sbt/1.0/plugins
[info] Loading settings for project gatling-sbt-plugin-demo-build from plugins.sbt ...
[info] Loading project definition from /tmp/gatling-sbt-plugin-demo/project
[info] Loading settings for project gatling-sbt-plugin-demo from build.sbt ...
[info] Set current project to gatling-sbt-plugin-demo (in build file:/tmp/gatling-sbt-plugin-demo/)
Warning: Unknown option -of
Warning: Unknown argument '/tmp/gatling-sbt-plugin-demo/src/test/scala'
Warning: Unknown option -bdf
Warning: Unknown argument '/tmp/gatling-sbt-plugin-demo/src/test/resources/bodies'
01:19:22.713 [main] INFO io.gatling.core.config.GatlingConfiguration$ - Gatling will try to use 'gatling.conf' as custom config file.
recorder.conf file couldn't be located or is outdated
Recorder preferences won't be saved.
If running from sbt, please run "copyConfigFiles" and check the plugin documentation.
```
The last three lines indicate that the config could not be loaded. The recorder starts regardless, but with the default configuration values (i.e. the change made in step 3 is not applied).

**Environment**
Observed on Linux (Ubuntu 18.04)

**Comment by slandelle** [comment]
Hi @alextsc 
Indeed, it looks like sbt 1.3 broke something wrt classpaths.
Thanks for reporting.
