### ISSUE TITLE
Core:  Move checkIf one level up and let it take multiple checks

### ISSUE THREAD

**Issue by anasmi** [gatling/gatling#3806]
It would be nice to pass multiple actions to a `checkIf` method , the same way as a `check` allows through the comma.

So, for example, instead of writing this:
```
.check(
   checkIf("${first.exists()}")(do_first),
   checkIf("$first.exists()}")(do_second), 
   checkIf("${first.exists()}")do_third)
```
it would be nice to have API as follows:

```
check(checkIf("${first.exists()}")(do_first,do_second, do_third))
```

**Comment by slandelle** [comment]
Sounds like a good idea and would make a nice contribution :)

**Comment by Wosin** [comment]
Can I jump on that ?

**Comment by slandelle** [comment]
@Wosin Sure, go ahead!

**Comment by e-hat** [comment]
I know this is pretty old, but could I try to tackle this one? Unless it's been fixed since.
