### ISSUE TITLE
Feature request: support silencing for websockets

### ISSUE THREAD

**Issue by pschiffe** [gatling/gatling#3817]
Silencing - https://gatling.io/docs/current/http/http_request/#silencing - is currently supported only for HTTP requests. It would be great to have it also for websockets.

In the following example, `ws-check-poll-update` timeouts multiple times, which is correct (b/c we need to send client pings), however it's reported as an error, plus it adds the wait time to the response time, so it breaks lot of time statistics as well:

```scala
val wsWaitForPollUpdate =
  asLongAs(_("capturedFeedbackId").validate[Int].isInstanceOf[Failure]) {
    exec(ws("ws-ping").sendText("2")
      .await(20 seconds)(
        ws.checkTextMessage("ws-check-poll-update")
          .matching(substring("poll.update"))
          .check(substring(""""event_uuid":"${uuid}""""))
          .check(regex(""""feedback_id":([0-9]+),""").saveAs("capturedFeedbackId"))
      )
    )
  }
```

It's true that this is basically a workround to the missing feature described here https://github.com/gatling/gatling/issues/3783 but I think this feature could be useful even in other use cases.

Relevant mailing list threads:
https://groups.google.com/d/msg/gatling/CODxgKUoVVI/MLKwj4bKDAAJ
https://groups.google.com/d/msg/gatling/QHFu91DrCbM/zAQoroJWCgAJ

**Comment by pschiffe** [comment]
This is a friendly reminder for this issue (well, or #3783 ). We are trying to bring in more automation with Frontline's API and assertions, but this issue is making it so much harder. I understand that the websockets are second class citizen here, but in the modern web they are more and more popular and important.

Is there a way how could I help? I'm not able to create a PR just by myself, but maybe if having some pointers or some help I could try. Or someone else who also needs it and is more Scala efficient.

**Comment by slandelle** [comment]
@pschiffe sorry for the long wait. #3783 is a completely different story.

**Comment by pschiffe** [comment]
Awesome! Thank you @slandelle
