### ISSUE TITLE
Core: In the number of users who used the incrementuserspersec method before 3.3.0 has a gradual increased, but it has gradual decreased in 3.3.0.

### ISSUE THREAD

**Issue by zengruitester** [gatling/gatling#3818]
Gatling 3.2.1:
![image](https://user-images.githubusercontent.com/33141728/68095153-04511f00-fee2-11e9-89bd-30bb8ef08d49.png)
Gatling 3.3.0:
![image](https://user-images.githubusercontent.com/33141728/68095157-0c10c380-fee2-11e9-8c2b-467345a383a7.png)

steUp:
`setUp(
    scn.inject(
      incrementUsersPerSec(5) // Double
        .times(5)
        .eachLevelLasting(10 seconds)
        .startingFrom(10) // Double
    ))`

**Comment by slandelle** [comment]
Thanks for reporting!
