### ISSUE TITLE
typo in SBT usage example

### ISSUE THREAD

**Issue by hxtpoe** [gatling/gatling#3827]
There is a trivial typo in documentation. This can be confusing for copy&paste lovers or for those who are not familiar with Scala / sbt. 
I'm not able to find a source code of the gatling.io webpage. That's why I'm creating this one. 

![Zrzut ekranu 2019-11-18 o 14 15 15](https://user-images.githubusercontent.com/528685/69056334-0b168080-0a10-11ea-8ad1-0cafc2686205.png)

**Comment by slandelle** [comment]
Fixed, thanks (fixes will only be visible in a few minutes once cache expires).
