### ISSUE TITLE
HTTP: Memory leak when using DigestAuth. 

### ISSUE THREAD

**Issue by jacekmg** [gatling/gatling#3832]
Gatling version **3.2.1**

I've stumbled upon memory leak using digest authentication. Every few minutes, during run of load test following error in netty occurs:

`[ERROR] i.n.u.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)`

For endpoints that are not authenticated by digest this error does not occur.
After investigation I've found a problem in DigestAuthHandler class in io.gatling.http.client.impl package:
```java
 @Override
  public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {

    if (digestHeader == null) {
      // initial state
      if (msg instanceof HttpResponse) {
        HttpResponse response = (HttpResponse) msg;
        if (response.status() == HttpResponseStatus.UNAUTHORIZED) {
          String authenticateHeader = getHeaderWithPrefix(response.headers().getAll(WWW_AUTHENTICATE), "Digest");
          if (authenticateHeader != null) {
            digestHeader = realm.computeAuthorizationHeader(tx.request.getMethod(), tx.request.getUri(), authenticateHeader);
            return;
          }
        }
      }

      // nothing this handler can do about it
      // either we don't need authentication, or auth scheme is not Digest
      ctx.fireChannelRead(msg);

    } else if (msg instanceof LastHttpContent) {
        // send new request
        // FIXME make sure connection can be reused, otherwise use a new one
        // FIXME check what happens if buildRequest throws
        WritableRequest request = WritableRequestBuilder.buildRequest(tx.request, ctx.alloc(), config, false);
        request.getRequest().headers().add(AUTHORIZATION, digestHeader);

        // FIXME write can throw Exception!!!
        request.write(ctx);
        ctx.pipeline().remove(this);
    }
    // initial response chunks are just ignored
  }
```
According to netty documentation https://netty.io/wiki/reference-counted-objects.html#inbound-messages - content have to be released in channelRead() of handlers. 
Seems like msg.release() call is missing in else if() part of the method.
Please investigate.

**Comment by slandelle** [comment]
Indeed, thanks a lot for reporting!
