### ISSUE TITLE
Core: Turn requestPerSec assertion Double instead Int

### ISSUE THREAD

**Issue by MaksSieve** [gatling/gatling#3844]
It is really strange that mean requests per second should be Int.
![image](https://user-images.githubusercontent.com/9395027/71083813-f4954d80-21a4-11ea-8398-1cee195ede86.png)
for example it's not alowed to do something like this, to check that we were in target profile:
`global.requestsPerSec.between((intensity - intensity*0.05), (intensity + intensity*0.05),  inclusive = true)`

**Comment by slandelle** [comment]
Indeed, thanks for reporting
