### ISSUE TITLE
How to create an API service for gatling to call？

### ISSUE THREAD

**Issue by SevenLM361** [gatling/gatling#3846]
I need to use the restful api or other remote dispatch method to let gatling execute the corresponding simulation.

I can’t resolve this question after I read the document a few times.

And I need save my simulation params to database, but i don't understand How to transfer the params to gatling?

**Comment by slandelle** [comment]
This is a bug tracker, hence for bugs.
Please stick to the community mailing list for questions.
Moreover, we have what you’re looking for covered in FrontLine, our Enterprise product.
