### ISSUE TITLE
Dynamic Conditions on Assertions

### ISSUE THREAD

**Issue by kierannichol** [gatling/gatling#3853]
I would like to be able to have dynamic conditions for the "forAll" path. My use-case would be to assert that "all endpoints should have a mean response time less than N, except for endpoint X which should have a response time less than M". In my case I have many, many endpoints that all have the same performance requirements, with a small number of pre-approved exceptions; also, some conditional endpoints that might not even be called.

Example:
```
forAll.responseTime.mean.lte(path => path match {
    case "Long Running Endpoint" => 2000
    _ => 200
})
```

**Comment by slandelle** [comment]
That’s not possible. We need a serializable AST for the assertions and that’s not possible with user provided functions.

**Comment by freshfineapple** [comment]
Sorry, but I don't understand how it's impossible. Gatling's `doIfOrElse` essentially provides this conditional/dynamic behavior already for ChainBuilders. Why would it be any different for assertions?

**Comment by slandelle** [comment]
As I said, Gatling needs to be able to serialize assertions, eg for the "reports-only" feature of the HTML reports engine.

**Comment by walkerbohannan** [comment]
We have a similar use case to OP, is there another way that this could be solved?
