### ISSUE TITLE
High misleading response time results

### ISSUE THREAD

**Issue by dcalap** [gatling/gatling#3854]
Hi have this project to reproduce the issue:
https://github.com/dcalap/micronaut-gatling-issue

Basically it has an API REST controller with a GET `/hello`endpoint that does nothing.

If I run ./gradlew gatlingRun I get this results:

![image](https://user-images.githubusercontent.com/6464175/72342265-61c8cf80-36cc-11ea-8584-9265e2616cfc.png)

Where **98%** of the requests takes more than **57ms** in all executions and most of them even more than **70ms**

But If I use Apache Benchmark and execute the test in the same way as follows:
`ab -T 'application/json' -v -w -n 100 -c 100 http://localhost:8080/hello`

I get this results always less than **20ms** all the requests:
```
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /hello
Document Length:        11 bytes

Concurrency Level:      100
Time taken for tests:   0.016 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      13200 bytes
HTML transferred:       1100 bytes
Requests per second:    6335.93 [#/sec] (mean)
Time per request:       15.783 [ms] (mean)
Time per request:       0.158 [ms] (mean, across all concurrent requests)
Transfer rate:          816.74 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        3    5   1.0      5       7
Processing:     2    5   1.7      5       8
Waiting:        2    5   1.8      4       8
Total:          5    9   2.2      9      15

Percentage of the requests served within a certain time (ms)
  50%      9
  66%     10
  75%     11
  80%     11
  90%     13
  95%     13
  98%     15
  99%     15
 100%     15 (longest request)
```

Why is that?

It's a problem because in a production API the difference between Apache Benchmark and Gatling pointing to the same endpoint are always close to +**1000ms** which is A LOT of difference.

Any clue?

Thanks in advance.

Steps to reproduce:
- git clone the project and run it (`./gradlew run`)
- run gatling against the running app (`./gradlew clean gatlingRun`)
- Get results
- Download ab (Apache Benchmark in Ubuntu console)
- run `ab -T 'application/json' -v -w -n 100 -c 100 http://localhost:8080/hello`
- Get results
- Compare

**Comment by slandelle** [comment]
ab shines on this kind of dumb and unrealistic use case and Gatling can't just compete:

- very short burst: ab is a native app and while Gatling uses a runtime (the JVM) that needs to warm up (JIT)
- ab can only generate static requests, so it only computes the payload once, while Gatling is intended for dynamic requests and has to compute them over and over again.

Run a longer test and after a while, you'll see the same kind of numbers (which is what I observed on my local machine with the reproducer your provided).

**Comment by dcalap** [comment]
> ab shines on this kind of dumb and unrealistic use case and Gatling can't just compete:
> 
> * very short burst: ab is a native app and while Gatling uses a runtime (the JVM) that needs to warm up (JIT)
> * ab can only generate static requests, so it only computes the payload once, while Gatling is intended for dynamic requests and has to compute them over and over again.
> 
> Run a longer test and after a while, you'll see the same kind of numbers (which is what I observed on my local machine with the reproducer your provided).

Thanks for the clarification @slandelle . Could you provide me the data you used in what you called "longer test"? Thanks.

**Comment by slandelle** [comment]
* replaced your during loop with a repeat(100)
* added a Connection: close request header to match ab behavior without -k option

Note that you if you try to run longer tests this way (no keepalive) with tuning the machine, you'll quickly run into ephemeral ports starvation (no sure how micronaut behaves in such use case too).
