### ISSUE TITLE
HTTP: Cannot apply Gatling EL to Cookie Name 

### ISSUE THREAD

**Issue by kvma** [gatling/gatling#3857]
I am using Gatling to load test one of our endpoints as we analyze throughput characteristics.  We are using a feeder to model user data and user IDs.  The system under test accepts cookie names and some of them are suffixed with a userID.

For example, when we try:

```
userId,token,
12345,MYSPECIALTOKEN
```
```
addCookie(Cookie("x-md-${userId}", "${token}"))
```

It appears that while I can use expressions for the Cookie Value, the Cookie Name cannot.  We see that the cookie `x-md-${userId}: MYSPECIALTOKEN` where we actually expected:
`x-md-12345: MYSPECIALTOKEN`

**ref**: https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/action/cookie/AddCookieDsl.scala#L22

**Comment by slandelle** [comment]
Contributions welcome (should be very easy)!
