### ISSUE TITLE
TcpSender - Failed to write to Graphite server

### ISSUE THREAD

**Issue by MrVictorBro** [gatling/gatling#3858]
Hi.

I have problems sending live test data to influxdb. Sending data stops being sent to influxdb during the test.
I see an error in the Gatling logs:
`11:51:34.549 [DEBUG] i.g.g.s.TcpSender - Failed to write to Graphite server located at: influxdb-test.cloud/192.168.1.10:2004, retrying...`

This problem is not permanent and is repeated on different servers and workstations.
The error may occur after 1 hour from the start of the test, or after one week.

file gatling.conf
```
graphite {
  host = "influxdb-test.cloud"
  port = 2004
  protocol = "tcp"
  rootPathPrefix = "test"
  writePeriod = 1
}
```

file influxdb.conf
```
[[graphite]]
  enabled = true
  database = "testdb"
  bind-address = ":2004"
  protocol = "tcp"
  templates = [
   "*.*.*.*.* measurement.simulation.request.status.field",
   "*.*.*.*.*.* measurement.simulation.group.request.status.field"
  ]
```

**Comment by slandelle** [comment]
That's a network issue on your side.

**Comment by MrVictorBro** [comment]
Yes, I agree, I also first thought about problems with the network.
I switched the Protocol to udp, but Gatling can't send a large amount of data through the Protocol.


This scenario works:
```
setUp(
      Test1().inject(rampUsers(30) during (15 minutes)),
      Test2().inject(rampUsers(30) during (15 minutes))
).protocols(httpProtocol)
  .maxDuration( 60 minutes)
```

In this scenario, Gatling stops sending data:
```
setUp(
      Test1().inject(rampUsers(30) during (15 minutes)),
      Test2().inject(rampUsers(30) during (15 minutes)),
      Test3().inject(rampUsers(30) during (15 minutes))
).protocols(httpProtocol)
  .maxDuration( 60 minutes)
```
or
```
setUp(
      Test1().inject(rampUsers(5) during (15 minutes)),
      Test2().inject(rampUsers(5) during (15 minutes)),
      Test3().inject(rampUsers(5) during (15 minutes))
).protocols(httpProtocol)
  .maxDuration( 60 minutes)
```
Gatling does not log sending data over UDP, I saw that data is no longer sent by in wireshark. There are no network errors in wireshark.

**Comment by slandelle** [comment]
Feel free to investigate and contribute.
From our point of view, this module is kind of deprecated since we provide FrontLine that is way better and doesn't break distributions (doesn't compute percentiles averages).
