### ISSUE TITLE
AnnotatedSocketException thrown when running simulation script

### ISSUE THREAD

**Issue by holphi** [gatling/gatling#3861]
I am looking for load testing solutions for my team, and I am currently investigating Gatling. 

I wrote below simple load test code:

package mysimulations

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class InitialSimulation extends Simulation {
    
  val httpProtocol = http
    .baseUrl("https://jsonplaceholder.typicode.com")
    .acceptHeader(" application/json")
  
  val scn = scenario("Initial Scenario")
    .exec(http("Get all posts")
    .get("/posts"))
  
  setUp(scn.inject(atOnceUsers(1)).protocols(httpProtocol))
}

however, everytime when I execute above script, I'm continuously receiving a runtime error as below:

>---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=1     )
> Get all posts                                            (OK=0      KO=1     )
---- Errors --------------------------------------------------------------------
> i.n.c.AbstractChannel$AnnotatedSocketException: Invalid argume      1 (100.0%)
nt: jsonplaceholder.typicode.com/0.0.10.127:443

Did anyone meet the similar error before? The version of Gatling installed on my MacBook is 3.3.1, the OS version is 10.15.2(Catalina)

**Comment by holphi** [comment]
I tried executing the BasicSimulation which is saved in /user-files/simulations/computerdatabase in Gatling bundle, I receive the same error:

**Comment by slandelle** [comment]
There's something utterly broken with DNS resolution on your side.

How come both jsonplaceholder.typicode.com (real IP: 104.18.60.242) and computer-database.gatling.io (real IP: 35.205.124.134) are both resolved as 0.0.11.113?

**Comment by holphi** [comment]
It's a network issue, I just reboot my MacBook and don't see this issue anymore, both my script and the sample script can be successfully executed.

Thanks @slandelle !
