### ISSUE TITLE
HTTP: Secure websocket does not work though Proxy

### ISSUE THREAD

**Issue by jano7** [gatling/gatling#3863]
Using **wss** protocol for websocket does not work.

The application under test does not receive messages over websocket. The application is accessed via proxy so it may be a combination of wss and a proxy which which is causing the issue.

I'm also using a different library for end-to-end websocket testing which works without any problems with the same configuration.

**Comment by slandelle** [comment]
Gatling version? Tried latest?

**Comment by slandelle** [comment]
#3733 was fixed in 3.1.3. Could you please confirm you're using an older version?

**Comment by jano7** [comment]
I am using version 3.1.3.

**Comment by jano7** [comment]
I do not get UnresolvedAddressException. There is no error, just the application does not receive a request sent over a websocket. And the gatling test fails due to a timeout as it expect a response from the app.

**Comment by slandelle** [comment]
Please upgrade to latest version.
If it still fails, please provide a SSCCE: http://sscce.org/

**Comment by jano7** [comment]
I apologize, I'm actually using the latest version 3.3.1. It terms of the example: it is basically identical to #3733 including the proxy settings. The difference is that I did not get any exception, instead I got a timeout error. I managed to simulate the example from #3773 - this is the last report before terminating:

```
================================================================================
2020-02-10 09:33:24                                          70s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=300    KO=200   )
> UI Request                                               (OK=100    KO=0     )
> Connect to WS                                            (OK=100    KO=0     )
> Send Request                                             (OK=100    KO=0     )
> Check Order Download                                     (OK=0      KO=100   )
> Close WS                                                 (OK=0      KO=100   )
---- Errors --------------------------------------------------------------------
> Check Check Order Download timeout                                100 (50.00%)
> data frame using reserved opcode 5                                100 (50.00%)

 ---- Order Download ------------------------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done: 100   
================================================================================
```
Also I saw many errors like this:
`io.gatling.http.action.ws.fsm.WsActor    : WebSocket crashed while waiting for close ack`

**Comment by jano7** [comment]
I had a closer look at it. It seems to be related to netty issues:
https://github.com/netty/netty/issues/5201 and https://github.com/eclipse-vertx/vert.x/issues/2671

**Comment by slandelle** [comment]
Indeed, this issue is netty/netty#5201.
Sadly, the proposed fixed https://github.com/netty/netty/pull/9564 doesn't work for us. I have a local fork that works for us, but I'd rather have it fixed upstream.

**Comment by jano7** [comment]
Thank you very much for fixing this issue. I can confirm my load test using proxy and secure websocket does work.
