### ISSUE TITLE
Exception in logs: io.gatling.http.client.impl.HttpAppHandler$1: Premature close

### ISSUE THREAD

**Issue by ghilainm** [gatling/gatling#3866]
I am using latest Gatling version 3.3.1 I have the following error in the logs:
io.gatling.http.client.impl.HttpAppHandler$1: Premature close

I can't figure out where it comes from. I have activated TRACE logs but I don't see the full stacktrace. Anything I should do to get more insight?

My simulation is rather basic. I am posting the same request all the time against a spring-webflux application. No error on server side and this weird error from Gatling side.

**Comment by slandelle** [comment]
Premature close is not a client side bug.
It means client tried to write on the socket while server was closing it, and network is simply not instantaneous.
Now why the server was dropping the socket is for you to figure out.

**Comment by ghilainm** [comment]
@slandelle  Thx for answering, any idea how I could debug that? Seems quite weird for me because I have no clue on server side of any issue...

**Comment by slandelle** [comment]
Wireshark is your friend.

**Comment by ghilainm** [comment]
@slandelle Is there something I could activate on Gatling side to get more insight?

**Comment by ghilainm** [comment]
I could pin point that this only occurs when running my application inside a docker container. Weird...

**Comment by slandelle** [comment]
Meaning your ingress is likely at fault.

**Comment by ghilainm** [comment]
I have no special Ingress just standard docker port exposed. Did you already experienced such kind of issues ?

**Comment by slandelle** [comment]
Nope
