### ISSUE TITLE
Scala logging is not working after Gatling.fromMap(properties.build) statement 

### ISSUE THREAD

**Issue by pavannarrasdet** [gatling/gatling#3868]
Hi,
I am using Gatling 3.3.1 with Scala 2.12.0 version.
I have a scenario where i am calling a method to verify some component functionality post "Gatling.fromMap(properties.build)" statement .

I could see that the logic inside that method is executing as expected but no logger statements are saving in logfile / console .

**Comment by slandelle** [comment]
The problem is on your side: missing config file, multiple slf4j backends in the classpath, etc.

**Comment by pavannarrasdet** [comment]
> config

Hi,
i think you didnt get me .. i am able to successfully log the messages till fromMap step.. once fromMap statements gets executed then it runs simulation after that whatever logs are there its not logging the messages..

if its not there in classpath.. the logs shouldnt work at all ? if i am not wrong..

please advise

**Comment by pavannarrasdet** [comment]
object Engine extends StrictLogging with App  {

  logger.info(Message.HELLO + " from Scala Engine.") -- working
  val rootPath = Paths.get(".", "target/classes/").toAbsolutePath.toString()

  val properties = new GatlingPropertiesBuilder()
    .binariesDirectory(rootPath)
    .resultsDirectory(rootPath + "/results")
  Gatling.fromMap(properties.build)
  logger.info(Message.HELLO + " from Scala Engine... END") -- not working

**Comment by slandelle** [comment]
Unsupported usage. Gatling is a software, not a library to be embedded into your own code.
