### ISSUE TITLE
Simulation log files should be disable

### ISSUE THREAD

**Issue by jfdoube** [gatling/gatling#3872]
Hi,

I have disable simulation log file in gatling.conf, however it was still trying to write the file.

I found out that the `runResult.hasAssertions` from the snippet below bypass the configuration flag
```
private def initLogFileReader(runResult: RunResult): Option[LogFileReader] =
    if (reportsGenerationEnabled || runResult.hasAssertions)
      Some(new LogFileReader(runResult.runId))
    else
      None
```

would it be possible to force disable them if specified in config, even with assertion  ?

thanks

**Comment by slandelle** [comment]
> I have disable simulation log file in gatling.conf, however it was still trying to write the file.

No, it tries to **read** it.

Could you please elaborate on what you're doing? With Gatling OSS, the only way to have assertions is to read the log file.

**Comment by jfdoube** [comment]
Ok got it.

I was under the assumption that removing FILE from gatling.config would prevent writing any sort of simulation logs on the disk.

essentially I'm just trying to use graphite, no file logging

**Comment by slandelle** [comment]
> I was under the assumption that removing FILE from gatling.config would prevent writing any sort of simulation logs on the disk.

Yes it does. Again that's the `LogFileReader` not the writer. The code you mentioned should only try to read the file, won't find it and won't read anything.

> essentially I'm just trying to use graphite, no file logging

What's the point of having assertions then? Assertions only work with log file and FrontLine.

**Comment by jfdoube** [comment]
That's ok. It was failing to read the file b/c the file did not exists.

I removed the assertions for now.
