### ISSUE TITLE
Maven plugin: verify should fail on execution error (eg compile error)

### ISSUE THREAD

**Issue by davesnyckers** [gatling/gatling#3888]
Using gatling with maven (gatling-maven-plugin)

#### Context
We currently use the plugin on our continuous integration server to test our performance.
Tests are run against docker images. And to be able to always shutdown/clean up all docker containers in a correct way, we use the failOnError property with value false to not have our build fail immediately and not being able to cleanup our environment in a decent way.

During the verify phase, the lastRun.txt is checked and if tests failed, build will also fail.
So far so good.

#### Problem case
But when there is for example a problem in our scala code that is used to perform the tests, errors will be shown, but due to the failOnError=false, this will not fail the build and next phases will be executed.

During the  verify phase, our lastRun.txt is empty in this case. And this will not fail the build.
So in the end it will look as if all was good, but in fact, no tests were executed at all.

#### Feature request
Is it possible to adapt the verify mojo to:
- fail the build in case the lastRun.txt does not contain any entries, OR
- introduce a configuration property to let the build fail if no entries are found in the lastRun.txt

**Comment by slandelle** [comment]
I agree with the need but I disagree with the suggested solutions. IMHO, `lastRun.txt` should also store build failures and rethrow in verify.

Contributions welcome :)
