### ISSUE TITLE
how to give concurrent users run for 1 hr in gatling without using throttling

### ISSUE THREAD

**Issue by mrsRadhika** [gatling/gatling#3898]
i have used the below code for scenario but want to use it without using throttling

setUp(scn.inject(constantUsersPerSec(10) during (1 minutes))).throttle(
	reachRps(5) in (10 seconds),
	holdFor(5 minute),
	).protocols(httpProtocol)

but want to use without throttling.

simple use:
1. ramp up 10 users, 
2. run in duration phase of 1 hr
3. ramp down

please help

**Comment by slandelle** [comment]
This is a bug tracker. Please use to the[ community mailing list](https://groups.google.com/forum/#!forum/gatling) for questions.
