### ISSUE TITLE
JSONPath comparison and standardisation

### ISSUE THREAD

**Issue by glyn** [gatling/gatling#3908]
@cburgmer's JSONPath comparison project is currently discussing some [issues](https://github.com/cburgmer/json-path-comparison/issues?q=is%3Aissue+is%3Aopen+label%3A%22Proposal+A%22) relating to a proposed implementation of JSONPath known as "Proposal A". May I encourage you to get involved if you are interested in influencing the direction or, indeed, if you want to make your own proposals.

Similarly, please join us in slack ([invitation](https://join.slack.com/t/jsonpath-standard/shared_invite/zt-es623y9z-~JOiqJTylBXSttT5n_xaPQ)) for informal discussions on the comparison project and potential JSONPath standardisation.

**Comment by slandelle** [comment]
@glyn One quick thought: have you reached out for the owner of the `jsonpath.com` domain and the one of the [json-path](https://github.com/json-path) Github org? IMHO, you guys would really need those if you want your effort to be visible as the official JsonPath.

**Comment by glyn** [comment]
Good idea @slandelle!

@ashphy owns `jsonpath.com`, but I'm not sure about the json-path github org unless its @kallestenflo. Both of you, please see https://github.com/gatling/gatling/issues/3908#issue-636108588.

**Comment by slandelle** [comment]
> I'm not sure about the json-path github org unless its @kallestenflo

Yes, @kallestenflo is the owner.
