### ISSUE TITLE
Graphite Data Writer:: Push the request and response timestamps as well 

### ISSUE THREAD

**Issue by Charishma-Madupu** [gatling/gatling#3914]
Hello 

 I'm implementing a real-time monitoring dashboard for my project. After enabling the Graphite data writer, noticed that only below metrics been pushed to the server:

```
time                count max mean min percentiles50 percentiles75 percentiles95 percentiles99 request                  simulation    status stdDev
----                ----- --- ---- --- ------------- ------------- ------------- ------------- -------                  ----------    ------ ------
1485784307000000000 3     23  21   21  21            21            23            23            addNewComputer           computerworld all    0
1485784307000000000 3     26  23   22  22            22            26            26            postComputers_Redirect_1 computerworld ok     1

```
I want to monitor the response times and response time distribution as well, which can be plotted if the request and response time stamps being pushed like-wise in **simulation.log** file

And one more is that, can we get error messages as well along with KO status.

Please lemme know, is there any flag kind of thing present to send all the metrics. Or would be great if that feature is present 

Thanks in advance.

**Comment by slandelle** [comment]
No, that's not possible. And that won't be implemented either, logging that much data would kill permformance.

**Comment by slandelle** [comment]
Just making things clear: new reporting features go in FrontLine, not in Gatling OSS.
