### ISSUE TITLE
Gatling requests are failed and how the requests are generated when we record a flow 

### ISSUE THREAD

**Issue by Naveen-mp** [gatling/gatling#3919]
HI , I have recorded a login feature and executed it , After the execution i was going through the report and found that all the requests are failed . how are these requests generated and why they have failed . 

![Gatling issue](https://user-images.githubusercontent.com/68151142/87223603-071ee080-c39c-11ea-9e60-429873664663.PNG)

**Comment by slandelle** [comment]
First, this is a bug tracker: issues and feature requests only. For such questions, please use the [community mailing list](https://groups.google.com/g/gatling).

Then, there's no way to help you as you don't provide any details on your errors (check the errors block below this one). Please provide those informations when posting on the mailing list.
