### ISSUE TITLE
JMS - How we can add WMQ_CLIENT_NONJMS_MQ value in gatling so that addition tags in header are not part of request message like <Msd> ,<jms> <mgext> etc

### ISSUE THREAD

**Issue by 10ravikumar** [gatling/gatling#3920]
I am using JNDI file binding to connect IBM MQ  using gatling 3, able to connect and send the message to queue but somehow it added extra tags like <jms> <Dst> <Mcd> ect in start of  "sample.xml" message content.

(textMessage(ElFileBody("sample.xml")) 
 
Is there a way just send the text message only to queue without addition tags like REF,jms,Dst,Tms,Dlv> etc.

**Comment by slandelle** [comment]
First, please don't post here for questions, this is a bug tracker. Use the [community mailing list](https://groups.google.com/g/gatling) instead.

Then, I have no idea what you exactly do, nor what you should be doing with IBM MQ, but it looks like you should be setting [properties](https://gatling.io/docs/current/jms/#properties).
