### ISSUE TITLE
Gatling Slow execution!

### ISSUE THREAD

**Issue by HadiAbbasi** [gatling/gatling#3921]
I'm running gatling on latest debian server and I have installed java 12.0.1 and also java 14.0.1 but when I wanna run gatling.sh, I have to wait 5 mins until showing simulation selection menu!
also when I start to send just 10 requests to my another server api, this is the result:
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                           10 (100%)
> failed                                                 0 (  0%)
------------------------------------------------------------------------------------------
but when I send request using cURL, it receives response immediately under 0.5 seconds!

this is my test result for just 1 request:
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            1 (100%)
> failed                                                 0 (  0%)

and this is my scala:

```
package computerdatabase.attacksimulation

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class AttackSimulator extends Simulation {

  val httpProtocol = http
    .baseUrl("http://ip.ip.ip.ip") // Here is the root for all relative URLs
    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8") // Here are the common headers
    .doNotTrackHeader("1")
    .acceptLanguageHeader("en-US,en;q=0.5")
    .acceptEncodingHeader("gzip, deflate")
	.virtualHost("myhost.com")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")
	//.noProxyFor("myhost.com","www.myhost.com")

	val scn = scenario("AttackSimulator")
	.exec(http("AttackSimulator")
	  .get("/test.js"))
	  .pause(4)

	setUp(scn.inject(atOnceUsers(1)).protocols(httpProtocol))
}
```
this test is running immediately and normally on another server (ubuntu-gatling 3.1.1-java version "12.0.1")!
but I don't know why I can't run it on my new debian server(tested for java 12.0.1 and java 14.x.x-gatling 3.3.1)!!!
setting IP and virtual host are required as I wanna try to send this request contrary to the dns settings!
thanks a lot...
Best,

**Comment by slandelle** [comment]
How could one possibly figure out what your problem is if you don't provide any information?

**Comment by HadiAbbasi** [comment]
I'm running gatling on latest debian server and I have installed java 12.0.1 and also java 14.0.1 but when I wanna run gatling.sh, I have to wait 5 mins until showing simulation selection menu!
also when I start to send just 10 requests to my another server api, this is the result:
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                           10 (100%)
> failed                                                 0 (  0%)
------------------------------------------------------------------------------------------
but when I send request using cURL, it receives response immediately under 0.5 seconds!

this is my test result for just 1 request:
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            1 (100%)
> failed                                                 0 (  0%)

and this is my scala:

```
package computerdatabase.attacksimulation

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class AttackSimulator extends Simulation {

  val httpProtocol = http
    .baseUrl("http://ip.ip.ip.ip") // Here is the root for all relative URLs
    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8") // Here are the common headers
    .doNotTrackHeader("1")
    .acceptLanguageHeader("en-US,en;q=0.5")
    .acceptEncodingHeader("gzip, deflate")
	.virtualHost("myhost.com")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")
	//.noProxyFor("myhost.com","www.myhost.com")

	val scn = scenario("AttackSimulator")
	.exec(http("AttackSimulator")
	  .get("/test.js"))
	  .pause(4)

	setUp(scn.inject(atOnceUsers(1)).protocols(httpProtocol))
}
```
this test is running immediately and normally on another server (ubuntu-gatling 3.1.1-java version "12.0.1")!
but I don't know why I can't run it on my new debian server!!!
setting IP and virtual host are required as I wanna try to send this request contrary to the dns settings!
thanks a lot...
Best,

**Comment by slandelle** [comment]
Could you please check that your `/etc/hosts` file on your debian server is not broken, in particular that you're not missing the `127.0.0.1       localhost` entry?

**Comment by HadiAbbasi** [comment]
this is my /etc/hosts on debian server:

```
127.0.0.1	localhost
127.0.1.1	srv90367

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

ip.ip.ip.ip  test.myhost.com
ip.ip.ip.ip  myhost.com
```

**Comment by slandelle** [comment]
Maybe that's your network messing up with warmUp but I'd be very surprised because it's supposed to have a 2s timeout. Try [disabling](https://gatling.io/docs/current/http/http_protocol#automatic-warm-up) it.

Then, if, as you said, your Gatling test works fine on your other machine, the issue is not with Gatling itself but with your debian machine set up.
Sorry, but we can't do anything about it. Only you can figure out the differences between your 2 systems.

**Comment by HadiAbbasi** [comment]
sorry But I wanna know if my java version is compatible with gatling 3.3.1?
$  java -version
java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

$ javac -version
javac 12.0.2

**Comment by slandelle** [comment]
We only officially support LTS version (8 and 11 atm) but 12 should work as well (we test from time to time with 14).

**Comment by HadiAbbasi** [comment]
thanks a lot...
