### ISSUE TITLE
Feature suggestion: add bytes sent/received metric to generated reports

### ISSUE THREAD

**Issue by knittl** [gatling/gatling#3930]
Gatling generates HTML reports with different graphs and plots to analyze response time of all requests. A metric that can also be very helpful to gauge a web application's performance is the size of response and request (in bytes).

Other load testing tools such as k6 keep track of this metric out of the box, cf. <https://k6.io/docs/using-k6/metrics>

It is certainly not required to have this in core, but if there are simple recipes available as part of the official docs, that would be tremendously helpful.

**Comment by slandelle** [comment]
We do have inbound and outbound bandwidth usage metrics in [FrontLine](https://gatling.io/gatling-frontline/) (our Enterprise version), global and broken down by target hostname.

<img width="695" alt="frontline-bandwidth" src="https://user-images.githubusercontent.com/849197/89532676-7698bc00-d7f2-11ea-9173-9c59a197d652.png">

We don't have any plans for now for bringing it to the free version.
