### ISSUE TITLE
Gradle plugin: Update references after first publication

### ISSUE THREAD

**Issue by Isammoc** [gatling/gatling#3940]
All technical references to the previous plugin should be replaced by `io.gatling.gradle`.

Specifically (but not limited to):
 * README.adoc
 * sample project

Note: do not forget to mention previous work and contributors.

**Comment by eshepelyuk** [comment]
What should be done

1. change plugin id to `io.gatling.gradle`.
1. change source directory layout of sample project to use `src/gatling/scala` convention.
