### ISSUE TITLE
Gatling enhancement suggestion for websocket checks

### ISSUE THREAD

**Issue by bgalamb** [gatling/gatling#3942]
We would like to achieve more flexibility with the websocket checks machanisms .  Our worklfow is 

- sending a websocket request with body eg.: {numberOfAnswers: N} 
- expect N websocket responses. 

(We use feeders so we know the expected number of answers, so the information us there even during compile time.)

Suggestion to be enhanced In Gatling 

- allow use EL / session parameters in `await()` timeout e.g `await(${timeout})`
- allow gatling loop possibility for `await(N)(check)` only, and not the whole exec block e.g `repeat(${numberOfAnswers}) { await(${timeout})`}

Balazs

**Comment by slandelle** [comment]
> allow use EL / session parameters in await() timeout e.g await(${timeout})

Already happening in upcoming 3.4, see #3897

Then, regarding the rest or your feature requests, and generally speaking regarding any WebSocket support improvements, implementing such features would require quite an effort.
I'll be blunt: consider either contributing them or having your organization sponsor their development if you want those to happen any time soon.
