### ISSUE TITLE
Gradle plugin: generate logback.xml even with missing gatling resources directory

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3946]
Currenly, `logback.xml` is generated together with `processGatlingResources` task.

When resources directory (`src/gatling/resources`) is missing or users changes default location - the plugin may skip generation of `logback.xml` at all.

This may lead to improper logging configuration.

### Improve generation of logback configuration 

This is **refactoring**

* Detect if gatling resources contains either `logback.xml`, `logback.groovy` etc. Currently the file location is hardcoded, this should be changed to analyze source directories and only limit sources to gatling resources.
* If gatling resources has logback configuration - do nothing.
* If gatling resources doesn't include any logback config files - then
  * generate logback.xml somewhere in `build` directory. A separate directory should be used, the file must not be put into `build/resources` as now. The generated file is better to place into `build/generated` to prevent interference with real resources processed by Gradle.
  * As now generated logback.xml should use `gatling.logLevel` parameter to configure root logger level
* Generated logback.xml should be passed to every forked JVM that executes Gatling via additional `-Dlogback.configurationFile` system property as [logback docs](http://logback.qos.ch/manual/configuration.html#configFileProperty) explains.
* Make sure current tests work.
* Add test cases for other files, like `logback.groovy` etc.

### Add possibility to configure HTTP requests via gatling configuration closure 

This is **new feature**

* Add a new parameter to `gatling` configuration closure
  * named `logHttp`
  * values: enum of [NONE, ALL, FAILURES]
* during logback.xml generation `logHttp` should enable logger of HTTP request (io.gatling.xxx), according to passed value
* create tests

### Prevent logging misconfigurations and improve plugin UX

This is a **new feature**

* If a user puts `logback.xml` or similar to resources folder, but the same times uses `logLevel` or `logHttp` parameters of `gatling` closure - plugin should throw an exception 
  * as an option - WARN log should be logged, without an exception.
* create tests for this feature

**Comment by slandelle** [comment]
How do a user know how to enable HTTP traffic logging?

**Comment by eshepelyuk** [comment]
> How does a user know how to enable HTTP traffic logging?

1. **right now** - it's possible to add a section to plugin's docs explaining how to do this with custom `logback.xml`
1. **then** - new issue should be created, to add more logging related options to `gatling` configuration closure.

**Comment by slandelle** [comment]
> right now - it's possible to add a section to plugin's docs explaining how to do this with custom logback.xml

Sadly, that wouldn't suffice. We copied those files everywhere for a reason.
Please understand we're not only aiming at professional developers who do read documentation.
**Lots** of our users don't read doc. Check on our community mailing list or Gatling questions on StackOverFlow.

**Comment by eshepelyuk** [comment]
> > right now - it's possible to add a section to plugin's docs explaining how to do this with custom logback.xml
> 
> Sadly, that wouldn't suffice. We copied those files everywhere for a reason.
> Please understand we're not only aiming at professional developers who do read documentation.
> **Lots** of our users don't read doc. Check on our community mailing list or Gatling questions on StackOverFlow.

So - let's include this feature into this issue.

Please explain detailly what parameters should be added.

**Comment by slandelle** [comment]
Let's focus on what most users want:
* use the default non verbose mode
* have options for debugging either failing HTTP traffic, or all HTTP traffic. Those options should be easy to discover (**how? suggestions?**).

What we could do would be to generate a logback.xml file on the fly (somewhere in `target`) when the user doesn't provide one (see http://logback.qos.ch/manual/configuration.html#auto_configuration), meaning typically detecting none of the possible files exists in the classpath (or at least in the target dir). The easiest solution then would be to set this file thanks to the `logback.configurationFile` System property.

WDYT?

**Comment by eshepelyuk** [comment]
Currently

1. logback.xml is _already generated_ on the fly, using `gatling` configuration closure.
1. generated logback.xml is _already included_ into classpath if there's no provided file

But there's some bugs with this and using `logback.configurationFile` may be a one option to solve this

Also, currently plugin doesn't support HTTP traffic loggin.
For this I planned to introduce new parameters to `gatling` configuration

```build.gradle
gatling {
   logLevel = "WARN" // already exists
   logHttp = // new parameter, one of ALL, FAILED, NONE
}
```

This will allow to almost exclude a need to deal with custom `logback.xml` in souce code and only rely on plugin configuration.

**Comment by slandelle** [comment]
> Also, currently plugin doesn't support HTTP traffic loggin.
> For this I planned to introduce new parameters to gatling configuration
> 
> gatling {
>    logLevel = "WARN" // already exists
>    logHttp = // new parameter, enum, one of ALL, FAILED, NONE
> }

Fine with me as long as those options are displayed but commented in the sample. Are we good?

**Comment by eshepelyuk** [comment]
> Fine with me as long as those options are displayed but commented in the sample. Are we good?

Isn't it _too early_  to discuss this, the feature is not yet started.

**Comment by Isammoc** [comment]
> > Fine with me as long as those options are displayed but commented in the sample. Are we good?
>
> Isn't it too early to discuss this, the feature is not yet started.

Until this feature is implemented, we should let the example files in place.

**Comment by slandelle** [comment]
> Isn't it too early to discuss this, the feature is not yet started.

Sorry, I should have explained that we have an agenda :)

We're currently finishing QA for the upcoming release of Gatling 3.4.0 and FrontLine 1.12.0. We want to release the new gradle plugin at the same time (including doc and sample). We wanted to release by the end of the week but we'll probably be a bit late.

So the point is:

* if we can have this feature by end of this week => we can drop the logback.xml in the sample
* if not => we have to keep the file in the sample for the release, and remove it in a next release when we'll have the feature

**Comment by slandelle** [comment]
Making things clear: I'm not pressing you to work on this if you don't have the cycles in order to meet our own deadlines. That's something we can work on ourselves.

**Comment by eshepelyuk** [comment]
Ok I got the idea. 

Definately won't be able to finish ot EoW :(
Let's keep logback.xml for now, and I'll be working on this issue meanwhile.

**Comment by slandelle** [comment]
I've had a look at the [current implementation](https://github.com/gatling/gatling-gradle-plugin/blob/master/src/main/groovy/io/gatling/gradle/LogbackConfigTaskAction.groovy#L22-L30) and I have some questions/remarks:

* It only looks for `logback.xml`. We should look for [other possible files](http://logback.qos.ch/manual/configuration.html#auto_configuration), in particular `logback.groovy` and `logback-test.xml`.
* Why do you search in the resources directory? Why not search in the binary output directory? The file should have been copied there as the plugin triggers after compilation.
* Same remark for the generated file. It shouldn't be generated in the resources directory which is monitored by the VCS. It should be generated in the binary output directory.

WDYT?

**Comment by eshepelyuk** [comment]
All those options are reasons for creating this issue .

The current imeplementation causes inconsistencies, and this issue was created to address all of them, improving logback config generation.

**Comment by slandelle** [comment]
I was asking for your insights if you already had some, in case we go with implementing the fix to cope with our deadline.

> It's generated in build directory, not in sources. FYI

Yes, I stand corrected.

**Comment by eshepelyuk** [comment]
This is task description

### Improve generation of logback configuration (**refactoring**)

* Detect if gatling resources contains either `logback.xml`, `logback.groovy` etc Currently the file location is hardcoded, this should be changed to analyze source directories and only limit sources to gatling resources.
* If gatling resources has logback configuraiton - do nothing.
* If gatling resources doesn't include any logback config files - then
  * generate logback.xml somewhere in `build` directory. Separate directory should be used, file must not be put into `build/resources` as now. The generated file is better to place into `build/generated` to prevent interferention with real resources processed by Gradle.
  * As now generated logback.xml should use `gatling.logLevel` parameter to configure root logger level
* Generated logback.xml should be passed to every forked JVM that executes Gatling via additional `-Dlogback.configurationFile` system property as [logback docs](http://logback.qos.ch/manual/configuration.html#configFileProperty) explains.
* Make sure current tests work.
* Add test cases for other files, like `logback.groovy` etc.

### Add posibility to configure HTTP requests via gatling configuration closure (**new feature**)

* Add a new parameter to `gatling` configuration closure
  * named `logHttp`
  * values: enum of [NONE, ALL, FAILURES]
* during logback.xml generation `logHttp` should enabled logger of HTTP request, according to values
* create tests

### Improve UX for logging

* If a user puts `logback.xml` or similar to resoures folder, but the same times uses `logLevel` or `logHttp` parameters of `gatling` closure - plugin should throw an exception 
  * as an options - WARN log should be logged, wihout an exception.
* create tests for this feature

**Comment by eshepelyuk** [comment]
@slandelle put an whole task description above.

**Comment by slandelle** [comment]
@eshepelyuk @Isammoc PTAL https://github.com/gatling/gatling-gradle-plugin/pull/8

**Comment by eshepelyuk** [comment]
This issue became a mess, closing it

Created #3948 #3949 #3950

**Comment by jonatan-ivanov** [comment]
Just for the record, the cause which started this issue seems to be the same problem as described in:
- https://github.com/lkishalmi/gradle-gatling-plugin/issues/110
- https://github.com/lkishalmi/gradle-gatling-plugin/issues/111
- https://github.com/lkishalmi/gradle-gatling-plugin/issues/115
