### ISSUE TITLE
Gradle plugin: add maven repository for dependency resolution

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3947]
Currently, plugin adds dependencies but doensn't add maven repositories, so users are forced to include them into `build.gradle` manually.

Plugin should add a repository itself.  One of following could be used:

* `jcenter()`
* `mavenCentral()`

**Comment by slandelle** [comment]
What about environments that don't have access to the internet and rely on a maven proxy (Nexus or Artifactory)?

**Comment by eshepelyuk** [comment]
> What about environments that don't have access to the internet and rely on a maven proxy (Nexus or Artifactory)?

Introduce a new parameter into `gatling` configuration closure. one of following 

1. boolean parameter to enable \ disable this feature ( `false` by default )
1. Groovy `Closure` parameter that can be overriden to proviede custom repository configuration, by default `{ mavenCentral() }`

**Comment by slandelle** [comment]
Is there any way to only add a repository automatically if none is configured explicitly?

> Plugin should add a repository itself. One of following could be used:
>
> * jcenter()
> * mavenCentral()

I would vote for mavenCentral. We've had some issue with jcenter in the past.

**Comment by eshepelyuk** [comment]
> Is there any way to only add a repository automatically if none is configured explicitly?

Well, I suppose a following trick could be done
  * during plugin application it will try to resolve **only Gatling** deps, 
  * if resolution KO - then plugin adds a mavenCentral() and proceed application
  * if resolution OK - plugins does nothing and proceed application

> I would vote for mavenCentral. We've had some issue with jcenter in the past.

👍

**Comment by slandelle** [comment]
Are you sure there's no way to discover user-defined repositories in the project? I'm not familiar with gradle but this information is easily available in maven.

**Comment by slandelle** [comment]
What would `Project#getRepositories` return?

**Comment by eshepelyuk** [comment]
Just inspecting user defined repositories from `build.gradle` is just not a siutable from resolving this issue.

Imagine he scenario, when a user wants to use some libraries hosted on some internal maven repo (not a proxy to a world).
So, that user declares it's own repository in `repositories {}` block, expecting that it will be used only for getting those libraries. 
(even worse, users may declare [repository filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering))

So, if the plugin will behave as you suggested - the plugin will detect some declared repositories and **will not apply** the actual repositories that are needed for resolving Gatling dependencies.

As a result, Gatling deps won't be resolved and user will be forced to add repo manually.

**Comment by Isammoc** [comment]
> Well, I suppose a following trick could be done
> 
>  * during plugin application it will try to resolve only Gatling deps,
>  * if resolution KO - then plugin adds a mavenCentral() and proceed application
>  * if resolution OK - plugins does nothing and proceed application

Is it possible in case resolution is KO to only add mavenCentral() for plugin's dependencies, not for user's build dependencies?

I don't want the user to think they don't need repository if they apply our plugin.

**Comment by slandelle** [comment]
OK, thanks for the explanations.

Shouldn't we re-qualify this as a feature instead of a bug? This is how the plugin currently works, right?

IMHO, this is not something critical we must have for the upcoming release and that could wait for the next one. This way, we'll also have some time to ponder the different options:

* add by default and have an option for disabling
* try to recover from an artifact resolution with the original configuration (this sounds like a serious hack).

**Comment by eshepelyuk** [comment]
> OK, thanks for the explanations.
> Shouldn't we re-qualify this as a feature instead of a bug? This is how the plugin currently works, right?

This is a completley new feature. Plugin doesn't do anythign of this. Label should be changed to Feature.

> IMHO, this is not something critical we must have for the upcoming release and that could wait for the next one. This way, we'll also have some time to ponder the different options:
> 
> * add by default and have an option for disabling
> * try to recover from an artifact resolution with the original configuration (this sounds like a serious hack).

This is smth I didn't understand completely. Obviously this feature is not a blocker for the release, but the rest of sentence is unclear to me.

**Comment by eshepelyuk** [comment]
As for an implementation - I'd stay away from new configuration options as much as possible.

The proposal about resolution of dependencies is smth that I already did, at least for this project https://github.com/akka/akka-grpc/tree/master/gradle-plugin

**Comment by slandelle** [comment]
Labelled as "Feature".

> As for an implementation - I'd stay away from new configuration options as much as possible.

OK then.
