### ISSUE TITLE
Gradle plugin: possibility to configure HTTP requests logging via gatling closure 

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3949]
### Current issue

* Currently, the single way of enabling logging Gatling http request is to provide custom logback config in resource directory.

### Scope of changes

* Add a new parameter to `gatling` configuration closure
  * named `logHttp`
  * values: enum of [NONE, ALL, FAILURES]
* during logback.xml generation `logHttp` should enable logger of HTTP request (io.gatling.xxx), according to passed value
* create tests

**Comment by slandelle** [comment]
This feature should be pretty easy to implement. I'm in favor of giving it a try and ship it in upcoming 3.4.0 so we don't have to provide a logback.xml file in the sample.

Otherwise, as it's a feature, we'll have to wait for the 3.5.0 release that will only happen in a several months.

**Comment by slandelle** [comment]
PR submitted, PTAL https://github.com/gatling/gatling-gradle-plugin/pull/9
