### ISSUE TITLE
Gradle plugin: prevent logging misconfiguration and improve plugin UX

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3950]
### Possible issues

* Users may configure logging via `gatling` configuration closure and yet have their own logback config file. This may lead to confusion.

### Scope of changes

* If a user puts `logback.xml` or similar to resources folder, but the same times uses `logLevel` or `logHttp` parameters of `gatling` closure - plugin should 

  * log WARN message, explaining that logback.xml \ logback.groovy wii override `gatling` configuraiton closure
  * create tests for this feature

Blocked by #3952

**Comment by Isammoc** [comment]
I'm in favor of a warning that the plugin `logHttp` configuration will be overridden by the `logback.xml`.

The final user may want to add their own task on top of those provided by the plugin. Some will add the `logback.xml`, some not.
So, in the same project, the default configuration will be that of the `logHttp` plugin, and some will override this by its own `logback.xml`

More, it may be difficult to detect if the custom `logback.xml` is not for logging something else (an additional library to load data, etc.)

**Comment by eshepelyuk** [comment]
Makes sense. Will adjust the descriprion.

**Comment by Isammoc** [comment]
> FYI this is icorrect statement, a single gatling source folder can not have multiple logback.xml \ logback.groovy

I mentioned a single project, not a single folder.
Single project, single plugin, but different tasks (that can be linked to other folders as well)

**Comment by eshepelyuk** [comment]
What a you talking about ? 
The one project has **single resource folder** where logback.xml \ logback.groovy could be located.

All gatling tasks are sharing **the same code base** - i.e. there is a single logback.xml \ logback.groovy for all taskk in a one proejct !
