### ISSUE TITLE
Gradle plugin: generate logback config even if there's no gatling resource directory

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3951]
### Current issue

* Logback generation happens at `doLast` closure of `processGatlingResources` task. When there's no gatling resource, i.e. default folder `src/gatling/resource` missing - the logback.xml doesn't get generated.

### Scope of changes

* `LogbackConfigTaskAction` should be called as `doLast` closure of another task.
* proposal is to call it after successful compilation of Gatling simulation
* task name is `gatlingClasses`

**Comment by eshepelyuk** [comment]
Closing in favor of #3952

**Comment by jonatan-ivanov** [comment]
Just for the record, this seems to be the same issue as:
- https://github.com/lkishalmi/gradle-gatling-plugin/issues/110
- https://github.com/lkishalmi/gradle-gatling-plugin/issues/111
- https://github.com/lkishalmi/gradle-gatling-plugin/issues/115

**Comment by eshepelyuk** [comment]
@slandelle is smth wrong with the implementation ? Or just updating the issue parameters ?

**Comment by slandelle** [comment]
The latter, everything's fine.

**Comment by eshepelyuk** [comment]
Ok, sorry for bothering.

**Comment by slandelle** [comment]
No pro
