### ISSUE TITLE
Gradle plugin: move documentation to main Gatling docs repository

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3953]
@slandelle @Isammoc 

Creating a task for you to properly manage plugin's docs and move them from git repo to your docs repo.

**Comment by eshepelyuk** [comment]
May I ask to keep logo and badges in https://github.com/gatling/gatling-gradle-plugin 

:)

**Comment by slandelle** [comment]
FYI, we also acknowledge the original contributors in the main doc, eg:

* https://gatling.io/docs/current/jms/
* https://gatling.io/docs/current/http/websocket/

**Comment by slandelle** [comment]
Closed by 3752c208c3084781aaa40a5c8dcb07562a158794

**Comment by eshepelyuk** [comment]
@slandelle @Isammoc is 3.4 M1 docs availble online ?

**Comment by slandelle** [comment]
@eshepelyuk No. Generally speaking, we don't document milestones because they are very unstable/early stage and usually not intended for public usage. 3.4.0-M1 was exactly that: a private release for one of our customers using a custom protocol.
