### ISSUE TITLE
Gradle plugin: proposal for github page improvements

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3954]
## disable packages, since this repo is not going to use GitHub packages ATM
![image](https://user-images.githubusercontent.com/1279477/92148404-32b2ca00-ee25-11ea-88e3-22a0cfbdfbed.png)

## Add repository description and labels for better searching \ indexing 
![image](https://user-images.githubusercontent.com/1279477/92148495-59710080-ee25-11ea-823c-997b509a45de.png)

**Comment by eshepelyuk** [comment]
@slandelle @Isammoc WDYT ?

**Comment by slandelle** [comment]
Done. Thanks!
