### ISSUE TITLE
HTTP: Support optional checks in WebSocket protocol

### ISSUE THREAD

**Issue by aartajew** [gatling/gatling#3959]
This is a feature request :)

[Sorry for repeating this thread here, but nobody reacted on Gatling Google Group]

My WebSocket scenario is to connect and authorize, which works fine. Then I just need to listen for and save incoming messages from WebSocket - no need to send any messages to the server.

I managed to send dummy "ping" messages just to be able to add "await" with "checkTextMessage" and check/save incoming message. This way I can simulate listening for incoming messages. 

The only problem is a failure when the check times out (for me it's not a real failure, it just means no message was sent from the server in given time, which is fine). I can't extend the timeout to infinity, because it will block the scenario execution.

A solution would be to support optional check, which would not fail even after time out. Unfortunately "optional" flag on check does not help.

Thanks in advance,
Adam

**Comment by slandelle** [comment]
See comment [here](https://github.com/gatling/gatling/issues/3942#issuecomment-683799953).

**Comment by aartajew** [comment]
Thanks Stephane!

However, according to this WebSocket documentation sentence: 

"You can use almost all the same check criteria as for HTTP requests." 

- optional checks would be the natural order of things ;)

**Comment by aartigao** [comment]
I have some spare time and want to take a look a it but I'm missing some context.

@slandelle Adding a default parameter boolean flag to `await` to not break execution is suffice? Or did you thought another approach?

**Comment by slandelle** [comment]
@aartigao From what I understand from @aartajew 's description, the actual need is to be able to await without having to send a message first.

**Comment by aartigao** [comment]
Let @aartajew clarify then.

I understood that he bypassed the send message thingy with a dummy payload but then talked about `await` ruining the checks on timeout.

From my point of view there are two feature requests:

1. Receive WebSocket messages without prior payload sent.
2. Configure `await` to not fail checks on timeout.

**Comment by aartajew** [comment]
Hi @aartigao - sorry, I just saw your question :)

Yes, the two feature requests you have listed are correct, but for me the latter (optional checks on `await`) is more general and I think simpler to implement - and frankly would cover my scenario :)

Thanks in advance!

**Comment by pschiffe** [comment]
Hey @aartigao , any luck with feature request nb. 2?

BTW feature request nb. 1 is discussed here - #3773 - but it's probably not that easy to implement, at least without parallel execution - #3783

**Comment by aartigao** [comment]
Wow! I didn't even remember this. Sorry, I abandoned the development here because it was too difficult for me to implement something on top of Gatling model. It has to be thought carefully because it'll involve non-trivial changes and I'm not expert enough in Gatling to do that.

**Comment by slandelle** [comment]
Closing:
* actual need is covered in #4100
* conditional checks similar to what exists in HTTP is covered in #3999
