### ISSUE TITLE
Gradle plugin: add INFO logs about automatic generation/configuration and decisions

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3960]
The plugin comes with more and more automatic decisions and configuration.

IMHO, it would really help support to have the plugin log its decisions.

Some users refuse to share a bug reproducer under the pretence that their actual project contains some private code they can't share... In such a situation, asking for logs is the best possible fallback.

**Comment by slandelle** [comment]
cc @eshepelyuk WDYT?

**Comment by eshepelyuk** [comment]
Definately the plugin must log as much as possible. Currently it's quite poor, I do realize. 
So I 100% support this intention. Let's maybe elaborate some standard way of logging and try to add logs piece by piece ?

**Comment by slandelle** [comment]
No need for this. The next version of the plugin is removing lots of automagic behavior in favor of implicit configuration by the user, eg:
* the scala plugin will have to be applied if the user wants to use Scala
* the logback conf will no longer be automatically generated
