### ISSUE TITLE
Schedule a http call

### ISSUE THREAD

**Issue by UserNoOne** [gatling/gatling#3963]
Are there any planes in future releases to support scheduling a http call in gatling like, 

```
val scn = scenario("My Simulation")
    .exec(getServerStatus) // schedule this call for every 1 min of simulation
    .during(60 mins) {
     feed("feed users file")
       .exec("http call 1")
       .exec("http call 2")
       .pause(5 seconds, 10 seconds)
    }

setUp(scn.inject(1).during(1)).protocols(http)

```
**getServerStatus** http call will be triggered for every 1 min. By any chance is this feature already exists or any planes in implementing same ??

**Comment by slandelle** [comment]
Please use the community mailing list for questions, not the bug tracker.
