### ISSUE TITLE
Gradle plugin: documentation fixes

### ISSUE THREAD

**Issue by eshepelyuk** [gatling/gatling#3965]
This page misses info about Gradle https://gatling.io/open-source/

![Screenshot_2020-09-24-19-45-19-743](https://user-images.githubusercontent.com/1279477/94175111-e3e5d680-fe9e-11ea-8ef2-5fbdc5dce190.jpeg)

@slandelle @Isammoc

**Comment by slandelle** [comment]
Yes, we'll take care of it tomorrow morning (different tools, different people and we finished late).

**Comment by eshepelyuk** [comment]
Thank you.

**Comment by slandelle** [comment]
Not perfect, blocks are not aligned. Will improve tomorrow.

**Comment by eshepelyuk** [comment]
Jaja, Gradle is superiour, comparing number of lines :))

**Comment by eshepelyuk** [comment]
@slandelle @notdryft Also this page misses info about Gradle

https://gatling.io/docs/current/extensions/

**Comment by eshepelyuk** [comment]
@slandelle @Isammoc @notdryft kindly reminding 

> this page misses info about Gradle
> https://gatling.io/docs/current/extensions/

**Comment by slandelle** [comment]
@eshepelyuk done, sorry for the delay

**Comment by eshepelyuk** [comment]
Great, thank you !
