### ISSUE TITLE
HTTP: Make header Methods Accept CharSequences as Values

### ISSUE THREAD

**Issue by jGleitz** [gatling/gatling#3970]
Gatling 3.4 deprecates `io.gatling.http.HeaderValues` in favour of `io.netty.handler.codec.http.HttpHeaderValues`. Hence, all header value constants are now `AsciiString`s, not `String`s. However, the various methods for setting headers still demand `String`s as values. They should be changed to accept `CharSequence`s (or `Expression[CharSequence]`s) as values instead.

In a nutshell, I want to be able to write:

```scala
http("example")
    .get("/my/url")
    .header(ACCEPT, TEXT_HTML)
    .headers(Map(    
        CACHE_CONTROL → NO_CACHE,
        PRAGMA → NO_CACHE
    ))
```

currently, I am forced to write:

 ```scala
http("example")
    .get("/my/url")
    .header(ACCEPT, s"$TEXT_HTML")
    .headers(Map(    
        CACHE_CONTROL → s"$NO_CACHE",
        PRAGMA → s"$NO_CACHE"
    ))
```

**Comment by slandelle** [comment]
Thanks for reporting.

We'll have to weight going this way or revert the deprecation.
If we could the former, I'm afraid this is not something we'll be able to do before Gatling 3.5.0 because it would break binary compatibility.

**Comment by jGleitz** [comment]
@slandelle thank you for the explanation.

Would it be an option to add the `header` methods that accept `CharSequences` as overloads and mark the existing methods `@Deprecated`? That would keep binary compatibility and solve the issue, I think.

**Comment by slandelle** [comment]
Closed as of #3973. We'll be reverting the deprecation in 3.4.1 and users will keep on using the usual constants where the values are Strings.

> Would it be an option to add the header methods that accept CharSequences as overloads and mark the existing methods @Deprecated? That would keep binary compatibility and solve the issue, I think.

No. All those methods actually take generic types where String or CharSequence are only type parameters. We can't have such overloads because of Java's type erasure.

**Comment by slandelle** [comment]
Closing as rejected in favor of #3971 

But thanks a lot for reporting!

**Comment by jGleitz** [comment]
#3973 is also a good solution for us. Thank you for addressing the issue!
