### ISSUE TITLE
RenamedAwareConfig Should Support All Operations

### ISSUE THREAD

**Issue by jGleitz** [gatling/gatling#3972]
Since Gatling 3.4, `GatlingConfiguration.config` no longer is a proper `Config`, but rather a `RenamedAwareConfig`. `RenamedAwareConfig` throws an `UnsupportedOperationException` for almost all operations. This is a breaking API change.

We have an internal Gatling plugin for an internal network protocol. We read its configuration values from the `GatlingConfiguration` so that it can be configured in the same way the HTTP plugin is configured. We used this code to read our configuration:

```scala
configuration.config.withFallback(CONFIG_DEFAULTS).getConfig(CONFIG_KEY)
```

`RenamedAwareConfig` does not support `withFallback` (nor `getConfig`), so our approach suddenly breaks with Gatling 3.4.

From my point of view, throwing `UnsupportedOperationException`s from a type that is exposed through a public API is bad design, to begin with. In our case, it leads to exceptions at runtime for code that looks valid and compiles. Furthermore, in this particular case, I see no good reason for why `RenamedAwareConfig` needs to throw this exception at all. As far as I understood the code, legacy values could be copied to their new paths (if no value exists there) while reading in the config. This way, Gatling could use a normal `Config` and still support renamed properties.

Please fix `GatlingConfiguration.config` so that it returns a fully functioning `Config`. I, personally, do not care whether `RenamedAwareConfig` is extended to support all operations or whether values are duplicated in a normal `Config`. The latter sounds easier and more reasonable to me, though.

If necessary, I’d submit a PR implementing the second approach.

**Comment by slandelle** [comment]
>  from a type that is exposed through a public API

Your error is that you're considering that Gatling is a framework/library where most code is a public API, a la Spring.

It's not. Gatling is a **software with mostly internals**, where only the external DSL provides some stability.
Proof: you couldn't find any official material documenting how to develop this internal plugin you've mentioned.

For now, we want to have the liberty of changing our own code for whatever reason, being improving design, bringing new features, fixing bugs, without having to worry about breaking code outside of our control, and possibly we're not even aware of.

Some people do write their own plugins after digging into our (undocumented) internals, but they do so at their own risk. In particular, we advice authors of popular open-source third parties to consider contributing upstream so we can help maintaining.

We're open to discussion with friendly (where unfriendly means competitors or people wanting to implement in-house features provided in FrontLine) users, typically open source third party plugins maintainers, about potential internals changes or absence of changes.

Regarding your specific issue, I've checked the code of most of the [OSS third party plugins listed in our documentation](https://gatling.io/docs/current/extensions/) and none of them use `GatlingConfiguration#config`.
Actually, I realize we no longer use it either and should probably remove it from `GatlingConfiguration`.

Could you please elaborate on why you insist on riding on our private internal instead of loading your own `Config` instance?

**Comment by slandelle** [comment]
The more I think about it, the more I think you shouldn't be using our own Config. You don't need our `gatling-defaults.conf` fallback and you don't need our renamed or removed props detection.

You just need to read from `gatling.conf` if you really insist on configuring your custom plugin from our own file (but well, you could/should use your own file), fallback to your own defaults file if you want to have one, and maybe read from System props just like us. All in all, it's plain Typesafe Config usage and just one line of code.

**Comment by jGleitz** [comment]
Hi @slandelle, thank you for your explanation. I want to present my side of things. Once again: not to argue, but to give you an understanding of what your customers are doing.

I was _not_ mistaken into thinking that most of Gatling has a stable public API. Gatling’s documentation as well as the lack thereof makes this pretty clear. However, from my point of view, I did not have a choice but to roll with whatever Gatling offers me. We thankfully switched to Gatling & Gatling Frontline from JMeter at our project. This was a big improvement for us. However, we still have an internal RPC protocol that we need to support for load testing. Nobody likes it, but that does not make it go away.

So for us, it was either implementing the protocol for Gatling, or going back to JMeter. We went with the former. But that means that we have to rely on whatever Gatling offers us and swallow whatever changes Gatling makes. So for me, all the types needed to implement a protocol (like `io.gatling.core.protocol.{Protocol, ProtocolComponents, ProtocolKey}`) are de-facto API. I know that you do not give guarantees for them, but I am still affected if you break them. The wording of my ticket may not have been ideal. But trust me, I am aware that my request is about API you don’t want to support.

---

Back to the issue:

> Could you please elaborate on why you insist on riding on our private internal instead of loading your own Config instance?

We configure our protocol in `ProtocolKey.defaultProtocolValue(configuration: GatlingConfiguration)`. Since this method receives a `GatlingConfiguration`, it was straightforward to use just that. We don’t necessarily “insist” on anything. As you say, we don’t need the `gatling-defaults.conf` and we don’t need the renamed or removed props detection.

I think it is sensible to read our protocol configuration from `gatling.conf`. Because then, users can configure our protocol the same way they configure the http protocol:

```
gatling {
    http {
     ...
    }
    internalProtocol {
   ... 
   }
}
```

True, that is not _necessary_, but it is the most consistent solution, from my point of view. Having said that, I think it makes sense to read from `GatlingConfiguration.config`. Because it already contains the parsed values I am looking for.

If you tell me that reading values form `gatling.conf` is not intended by Gatling, then I guess I’ll have to swallow that. But as I said, I think it creates a worse user experience than having all protocol configuration in one file.

---

Regardless of where we read our values from, I still think that it is bad that the de-facto exposed object `GatlingConfiguration.config` (it is exposed to everyone writing protocols) throws `UnsuportedOperationException`s. This could be mitigated, as you say, by removing `GatlingConfiguration.config`. Or by applying my suggestion, which is making `GatlingConfiguration.config` fully functional. The latter would be a binary compatible change.

**Comment by slandelle** [comment]
> Because it already contains the parsed values I am looking for.
> de-facto exposed
> binary compatible change

Again, that's unexpected, we shouldn't have exposed it in the first place.
That was never a feature/API.
There's no such thing as binary compatible guarantees when it comes to internals.

> If you tell me that reading values form gatling.conf

Not what I'm saying. I'm saying you shouldn't use our `Config` instance (that we shouldn't expose in the first place) but use your own.

I still think it would be best for you to build your own Config instance:

```
object CustomConfig {
  val Instance = {
    val cl = getClass.getClassLoader
    ConfigFactory.systemProperties
      .withFallback(ConfigFactory.parseResources(cl, "gatling.conf"))
      .withFallback(ConfigFactory.parseResources(cl, "custom-defaults.conf"))
  }
}
```

or even if you don't want default values:
```
object CustomConfig {
  val Instance = ConfigFactory.systemProperties
      .withFallback(ConfigFactory.parseResources(getClass.getClassLoader, "gatling.conf"))
}
```

Just those few lines of code look like a very small price to pay to stop relying on an internal that's likely to go away.

**Comment by jGleitz** [comment]
I see, thanks for explaining. We will go forward with parsing `gatling.conf` ourselves.

I think it would be good to remove `GatlingConfiguration.config` in 3.5.0 if you don’t plan to expose & and maintain it

**Comment by slandelle** [comment]
Cool, thanks for your understanding!
