### ISSUE TITLE
HTTP: Revert HeaderNames and HeaderValues deprecation

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3973]
We would have more control over our own constants, at the cost of keeping on maintaining our own list.

**Comment by jGleitz** [comment]
Can you give an estimation of when you plan to publish this change? 

I don’t need a definite date, it is just to plan whether we will migrate to 3.4.0 or wait for 3.4.1 to be released first. Is it a matter of days, weeks, months?

**Comment by slandelle** [comment]
It depends on how many bugs we find and their gravity. If there's a blocking bug, we could release very fast. Otherwise, probably one month.

But then, I don't understand what this is a blocker for you: those are just deprecation **warnings**. You can still stick with `HttpHeaderNames` and `HttpHeaderValues`, live with the warnings and your code will still compile.

**Comment by jGleitz** [comment]
Thank you for the info!

You are right, those are only warnings. But we just don’t like to have warnings :)
