### ISSUE TITLE
Got j.i.IOException: Premature close error for Gatling 3.3.1 version

### ISSUE THREAD

**Issue by sriharshaganti** [gatling/gatling#3986]
My Issue:
Gatling version: 3.3.1
Http library config: 
`val httpConf = http
    .baseUrl(baseURL)
    .acceptHeader("application/json")
    .basicAuth(<user>, <password>)
    .header("Content-Type", "application/json")
    .shareConnections`

My load setup
 performAuth.inject(
     nothingFor(10 seconds),
      atOnceUsers(50),
      nothingFor(10 seconds),
      rampUsers(20) during (10 minutes),
      nothingFor(10 seconds),
      constantUsersPerSec(usersCount) during(rampTime minutes))
  ).protocols(httpConf)

usersCount = 70 and rampTime = 60

Got the error : > j.i.IOException: Premature close                               1165916 (55.14%)

**Comment by slandelle** [comment]
"Premature close" means the server closed the socket before sending the full response. This is a network/server side issue. Make sure your server and your network can withstand your load and you don't have some network security blocking you (anti-DoS, anti-virus).
