### ISSUE TITLE
i.n.c.ChannelException: Failed to open a socket

### ISSUE THREAD

**Issue by lamquangthanh178** [gatling/gatling#3990]
* Regarding issues:
  *  Gatling version: 3.3.1
  *  I'm facing with issues Failed to open socket, but it's just happened when we execute endurance testing (after 6 hours running)
![image](https://user-images.githubusercontent.com/31389259/96208393-93423480-0f97-11eb-97ed-0bb33e628dca.png)

The concurrent users is 7000. Don't have this issues with previous release. In this release, I have some test case related to upload file from csv (ramp ups 350 cc per 10s for upload test case)

Already config $ ulimit -n 65536

**Comment by slandelle** [comment]
The latest version is 3.4.1. Could you please upgrade?
If the issue still exists, please provide your feeder configuration (circular?).

**Comment by lamquangthanh178** [comment]
Hello @slandelle 
Because my test plan is version 3.3.1, so I can't upgrade the version of Gatling. Below is the code related.

I didn't using any feeder method in gatling. I selected the random file base on the variable in request

In the request, I get the ${coderandom} variable

```
def GetListClass(baseUrl: String)
= http("Get /api/classrun/byCourseId?courseId - Get classrun")
.get(baseUrl + "/api/classrun/byCourseId")
.headers(headers_authorized)
.queryParamSeq(Seq( ("skipCount","0"), ("maxResultCount","10")))
.check(jsonPath("$.items..classRunCode").findRandom.optional.saveAs("classrunCoderdm"))
```

And using it pick random a file to upload
```
val Import =
exec(session => {
val fileName = "file_pp/File_" + session("coderandom").as[String] + "_.csv"
val fileResourcePath = Paths.get(baseCsvPath, fileName).toString;
session.set("fileResourcePath", fileResourcePath)
})
```

```
def ImportCsvFile(baseUrl: String)
= http("Import csv file")
.post(baseUrl + "/api/registration/${courseId}/importParticipant")
.headers(headers_authorized)
.header("Content-Type","multipart/form-data")
.formUpload("file", "${fileResourcePath}")
```

**Comment by slandelle** [comment]
> Because my test plan is version 3.3.1, so I can't upgrade the version of Gatling.

Why is that???

> And using it pick random a file to upload

Do you have any failure on the "Import csv file" request?

**Comment by slandelle** [comment]
Also, is it http or https?

**Comment by lamquangthanh178** [comment]
> Why is that???
> >That is a contract with client :)

>  And using it pick random a file to upload
>Do you have any failure on the "Import csv file" request?
>>It works fine without any problems.

> Also, is it http or https?
>>And I use https

**Comment by slandelle** [comment]
If there's no way to investigate this, typically reproduce on our side, I'm afraid we'll have to close.
