### ISSUE TITLE
HTTP: Duplicated values in sec-websocket-extensions header

### ISSUE THREAD

**Issue by kurilov** [gatling/gatling#3991]
I want to set the value of **sec-websocket-extensions** header different from the default, but after adding **ignoreProtocolHeaders** parameter and setting my headers, I see that headers are appended, but not replaced.
Also, this heder is not on this list
[https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/Headers.scala](https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/Headers.scala)

```

val connect: ChainBuilder = exec(ws("Connect to WS")
    .connect("/ws")
    .ignoreProtocolHeaders
    .headers(Map[String, String](
      "Sec-WebSocket-Extensions" -> "permessage-deflate; client_max_window_bits"
    )).subprotocol("json"))
```

Request from wireshark

```
    Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6,tr;q=0.5,de;q=0.4,it;q=0.3\r\n
    accept: */*\r\n
    accept-encoding: gzip, deflate\r\n
    host: XXX\r\n
    upgrade: websocket\r\n
    connection: upgrade\r\n
    sec-websocket-key: /J6kf1eO22iuIZ+cVPQDbQ==\r\n
    origin: XXX\r\n
    sec-websocket-protocol: json\r\n
    sec-websocket-version: 13\r\n
    sec-websocket-extensions: permessage-deflate; client_max_window_bits,permessage-deflate;client_no_context_takeover;client_max_window_bits,deflate-frame,x-webkit-deflate-frame\r\n

```

**Gatling version: 3.4.0**

**Comment by slandelle** [comment]
Would you be interested in contributing?

**Comment by kurilov** [comment]
It looks more interesting than implementing your own protocol or forking. I can try :)

**Comment by slandelle** [comment]
So, there are 2 things:
* some extensions are always enabled in Gatling: `permessage-deflate`, `client_no_context_takeover`, `client_max_window_bits`, `deflate-frame` and `x-webkit-deflate-frame` => we don't plan to change that, that would be a lot of work and in the end, those are just advertising the server that some features are supported
* there's a bug in Netty where it doesn't check if those extensions are already present in the header before adding the ones related to the enabled features.

**Comment by slandelle** [comment]
@kurilov PR against netty under review: #10951

**Comment by kurilov** [comment]
@slandelle. https://github.com/netty/netty/pull/10951 already merged.

**Comment by slandelle** [comment]
@kurilov We'll upgrade to netty 4.1.60 in the next release. In the meantime, you can enforce dependency upgrade with your build tool.
