### ISSUE TITLE
Add lambda form of "andThen"

### ISSUE THREAD

**Issue by theathlete3141** [gatling/gatling#4003]
My test case is:
- Create n cats
- AND THEN get each of the n cats

The create step returns an id which is required for use in the get step. This requires a way of saving the ids returned from the create steps for subsequent use in the get steps.

An attempted implementation:
```
class CatsGatlingSimulation extends Simulation {

  MockUtils.startServer()

  val nameFeeder = Array(
    Map("name" -> "Felix"),
    Map("name" -> "Simba"),
    Map("name" -> "Shadow"),
    Map("name" -> "Bob")
  )

  val numUsers = nameFeeder.readRecords.length

  val fileName = "ids.csv"
  val file = new File("src/test/resources/" + fileName)
  val writer = new PrintWriter(new FileOutputStream(file, false))
  writer.println("id")
  writer.close()

  val create = scenario("create")
    .feed(nameFeeder)
    .exec(
      http("POST /cats")
      .post("/")
      .body(StringBody("""{ "name": "${name}" }"""))
      .check(status.is(200))
      .check(jsonPath("$.name").is("${name}"))
      .check(jsonPath("$.id").saveAs("id"))
    )
    .exec { session =>
      val writer = new PrintWriter(new FileOutputStream(file, true))
      val id = session("id").as[String]
      writer.println(id)
      writer.close()
      println("wrote id " + id)
      session
    }

  def idFeeder() = {
    val feeder = csv(fileName)
    println("read " + feeder.readRecords.length + " records")
    feeder
  }

  def get() = scenario("get")
    .feed(idFeeder())
    .exec(
      http("GET /cats/{id}")
        .get("/${id}")
        .check(status.is(200))
        .check(jsonPath("$.id").is("${id}"))
        .check(jsonPath("$.name").exists)
    )

  val httpConf = http.baseUrl(System.getProperty("mock.cats.url"))

  setUp(
    create.inject(atOnceUsers(numUsers)).protocols(httpConf).andThen(
      get().inject(atOnceUsers(numUsers)).protocols(httpConf)
    )
  )
}
```
This will write the ids from the create steps to a file. However the file is read for the get steps before being written to in the create steps. Therefore it fails to execute the get requests because the id feeder is empty.

This test case could be implemented if `andThen` accepted a lambda so that the read from file is executed after the write to file.

Please see the attached example project which uses Gatling 3.4.1. The use of the karate test framework is only so that a mock server can be run. The example can be ran by executing
```
mvn clean test -D gatling.simulationClass=mock.CatsGatlingSimulation
```
[gatling.zip](https://github.com/gatling/gatling/files/5510004/gatling.zip)

An additional example has been added which shows a related but different test case: create and get a cat n times. This is not an issue here and works as expected
```
mvn clean test -D gatling.simulationClass=mock.CatsGatlingSimulation2
```

**Comment by slandelle** [comment]
Your actual issue is your using Gatling CSV feeders wrong.

Those builtin feeders are meant for using file based data prepared upstream. This way, we can verify the file exist before starting, and possibly load the data in memory and parsing doesn't happen at runtime. Maybe it will change someday, but not in the near future.

That's not what you have as the data doesn't exist before running the test. And except if the amount of data you're using is humongous and doesn't fit in memory, you don't even need a file for this.

You should have you own feeder implementation, possibly have the first scenario push data in a concurrent structure such as a ConcurrentHashMap or a ConcurrentLinkedDeque depending on your use case, and have the second scenario pull data out of it.

**Comment by theathlete3141** [comment]
Thanks for the pointer about using ConcurrentHashMap/ConcurrentLinkedDeque. Using that, I was able to find this https://groups.google.com/g/gatling/c/PrXLbKoIQI8
which led me to a working solution
```
class CatsGatlingSimulation extends Simulation {

  MockUtils.startServer()

  val nameFeeder = Array(
    Map("name" -> "Felix"),
    Map("name" -> "Simba"),
    Map("name" -> "Shadow"),
    Map("name" -> "Bob")
  )

  val numUsers = nameFeeder.readRecords.length

  val idQueue = new ConcurrentLinkedDeque[String]

  val create = scenario("create")
    .feed(nameFeeder)
    .exec(
      http("POST /cats")
      .post("/")
      .body(StringBody("""{ "name": "${name}" }"""))
      .check(status.is(200))
      .check(jsonPath("$.name").is("${name}"))
      .check(jsonPath("$.id").saveAs("id"))
    )
    .exec { session =>
      val id = session("id").as[String]
      idQueue.add(id)
      session
    }

  val get = scenario("get")
    .exec { session =>
      val id = idQueue.poll()
      session.set("id", id)
    }
    .exec(
      http("GET /cats/{id}")
        .get("/${id}")
        .check(status.is(200))
        .check(jsonPath("$.id").is("${id}"))
        .check(jsonPath("$.name").exists)
    )

  val httpConf = http.baseUrl(System.getProperty("mock.cats.url"))

  setUp(
    create.inject(atOnceUsers(numUsers)).protocols(httpConf).andThen(
      get.inject(atOnceUsers(numUsers)).protocols(httpConf)
    )
  )
}
```
[gatling.zip](https://github.com/gatling/gatling/files/5510347/gatling.zip)
