### ISSUE TITLE
Core: ChainableAction does not catch exceptions in dispatched execution

### ISSUE THREAD

**Issue by phiSgr** [gatling/gatling#4008]
Consider this pathological example:

```scala
.exec(new ActionBuilder {
  override def build(ctx: ScenarioContext, next: Action): Action = new Action {
    override def name: String = "wrongDispatcher"
    override protected def execute(session: Session): Unit = {
      scala.concurrent.ExecutionContext.global.execute(() => next ! session)
    }
  }
})
.exec { _ =>
  throw new IllegalStateException()
}
```

The first action runs `next ! session` in a different thread, so the `SessionHook` have to submit the execution to the event loop. When the exception is thrown, it is not inside the `try` of `ChainableAction.!`. The scenario will then never end.

---

I did not hit this problem myself, because most, if not all `Action`s do resume inside the event loop. It is very reasonable to not handle this edge case as long as this is commented in code.

BTW is the misspelling `evenLoop` intentional?

**Comment by slandelle** [comment]
Fix, thanks for reporting.

Then, honestly, there's a chance we enforce at some point execution from the EventLoop.

**Comment by phiSgr** [comment]
As normal users don't create their own `ActionBuilders`, I don't mind the "run `!` in event loop" requirement to not involve any runtime check at all.

Maybe a transition patch/minor version that adds the assertion to notify third-party extension authors.

**Comment by slandelle** [comment]
Such change would only happen in Gatling 4.
