### ISSUE TITLE
Provide integration with Keptn

### ISSUE THREAD

**Issue by jetzlstorfer** [gatling/gatling#4009]
I would like to see an integration to trigger Gatling tests via the [Keptn](https://keptn.sh) control-plane.

The integration should start Gatling tests once it is triggered by Keptn and upon the test completion, it should send back a cloud-event to inform Keptn about the result. Keptn will then move on with the evaluation of the test results for the testing period.

For full transparency, an issue has also been created in the Keptn github repository: https://github.com/keptn/keptn/issues/2674

**Comment by slandelle** [comment]
Sorry, but Gatling automation is something that falls in the scope of [FrontLine](https://gatling.io/gatling-frontline/), our Enterprise version.

FrontLine has a REST API and plugins for Jenkins, Bamboo and TeamCity, so having an integration with Keptn would be pretty feasible I guess.
