### ISSUE TITLE
Missed UserId in simulation.log

### ISSUE THREAD

**Issue by m4nfreb** [gatling/gatling#4010]
Gatling Version: 3.4.1

Missed: UserId column in simulation.log file

Verification code:
```
import io.gatling.core.Predef._
import io.gatling.http.Predef._

class test extends Simulation {

    val protocol = http.baseUrl("https://httpbin.org")

    val request = http("request")
      .post("/get")

    val scn = scenario("scenario")
      .exec(request)

    setUp(
      scn.inject(atOnceUsers(10)).protocols(protocol)
    )
}
```

simulation.log attached
[simulation.log](https://github.com/gatling/gatling/files/5533425/simulation.log)

**Comment by slandelle** [comment]
I've explained many times on the community mailing list that the simulation.log was an internal file only meant to be parsed by our HTML report engine and that it was undocumented and subject to change without any further warning.

This is exactly the situation that happened in 3.4.0 where we removed fields that our reports weren't using to make the file smaller and hence faster to write and read, in particular during long runs and/or with heavy throughput.
