### ISSUE TITLE
Starting Gatling a second time programatically does not work

### ISSUE THREAD

**Issue by royteeuwen** [gatling/gatling#4013]
I am trying to start the exact same gatling process a second time after the first time worked. But it does not seem to work, it only keeps logging that it has done 0%.

How I start up my tests (from Java):

```
        log.info("Starting process");
        Class<?> scenario = Class.forName(simulationClassName);
        scala.collection.mutable.Map<String, Object> options = new HashMap<>();
        options.put("gatling.core.runDescription", scenario.getSimpleName());
        options.put("gatling.core.directory.results", "reports/v1");
        Option<Class<Simulation>> optionalSimulation = Option.apply((Class<Simulation>) scenario);
        var result = Gatling$.MODULE$.start(options, optionalSimulation);
        if (result == 0) {
            log.debug("Successfully started gatling tests");
        } else {
            log.warn("Could not start gatling tests: {}", result);
        }
        gatlingResult = Optional.empty();
```

The first time it gives me the result, the second time it indefinitely keeps on logging the following: (notice the 0% at the end)

```
================================================================================
2020-11-18 15:13:34                                          10s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=30     KO=0     )
> Open search page                                         (OK=30     KO=0     )

---- Search Scenario -----------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 30     / done: 0     
================================================================================
```

Is there something I should do to terminate the first process correctly? I already tried by using the debugger and doing actorSystem.terminate() when the first time has finished but that doesn't seem to do the trick

**Comment by slandelle** [comment]
Nope, not supported and out of scope, please don't do that.
The only supported launchers are the official ones we provide: bundle, maven/sbt/gradle plugins and the little helper for launching from the IDE.

**Comment by royteeuwen** [comment]
@slandelle  can you give a bit more context to why this is not supported?

**Comment by slandelle** [comment]
Gatling is a software, not a library. The public API is the DSL for the tests, here you're hacking internals.
