### ISSUE TITLE
Recorder: Package configuration differs from actual property

### ISSUE THREAD

**Issue by notdryft** [gatling/gatling#4014]
Default configuration uses `package`: https://github.com/gatling/gatling/blob/master/gatling-recorder/src/main/resources/recorder-defaults.conf#L6

Configuration property is actually `pkg`: https://github.com/gatling/gatling/blob/master/gatling-recorder/src/main/scala/io/gatling/recorder/config/RecorderConfiguration.scala#L130

**Definition of done**
1. `packageName` everywhere (`package` is a reserved keyword and `pkg` is not useful enough)
2. ~~`packageName` will have a sensible default (`com.example.simulations`?)~~
3. The generated Simulation should be in the declared `packageName`
4. Each step is well tested (configuration parsing with or without declaring the option, a generation with pre-filled data will generate in the package in the wanted directory)

**Comment by notdryft** [comment]
Actually, both `pkg` and `package` are ignored.

**Comment by michiboo** [comment]
@notdryft  Hi I would like to try out this issue, but if both are ignored what needed to change?

**Comment by notdryft** [comment]
There could be some misusage in the ConfigurationFrame itself: https://github.com/gatling/gatling/blob/master/gatling-recorder/src/main/scala/io/gatling/recorder/ui/swing/frame/ConfigurationFrame.scala#L524

**Comment by Isammoc** [comment]
Note: edited the description to include the DoD

**Comment by slandelle** [comment]
Wrong analysis. The actual issue (not described in here) has nothing to do with config props and case class attributes not being aligned.
