### ISSUE TITLE
New Feature: Jenkins Plugin - Add 99th Percentile and Max Graphs

### ISSUE THREAD

**Issue by anthonyemerson** [gatling/gatling#4016]
The Jenkins Plugin currently only displays graphs for KO, 95th Percentile, and Mean request times. Personally I find 95th percentile and Mean to be next to useless in a production environment. I want to be able to know at a glance what the worst parts of my app are doing.

I am proposing adding graphs for 99th Percentile and Max request times. Ideally these graphs would be configurable, so any user can set which graphs they'd like in their Jenkins instance, but I recognize making it configurable would be a much more involved task. So I'm just asking for the graphs to be added that tell me the information I think is most useful for all users.

**Comment by slandelle** [comment]
Reporting improvements fall in the scope of FrontLine where we already have what you're looking for.

![trends](https://user-images.githubusercontent.com/849197/100435878-dc110100-309e-11eb-9237-9a00e77a55dc.png)
