### ISSUE TITLE
Local configuration file

### ISSUE THREAD

**Issue by tomers** [gatling/gatling#4017]
I would like to override two charting-related values in my Gatling 3.4.2 run. 
I use a pre-built docker with Gatling, where the configuration file is already included, so it would be hard for me override the default configuration file (I don't want to build a new image for each configuration override).
I reviewed https://gatling.io/docs/current/general/configuration/ and couldn't find an alternative way to achieve this functionality.

My question is whether there is a way to provide an override configuration file, so that Gatling will initially use the global, unchanged, `gatling.conf` file and on top of it use `gatling.local.conf` to override some of the values? If not, I think such feature would be useful for some users ;-)

```
###############################
# Local Gatling Configuration #
###############################

# This file contains override values on top of the global Gatling configuration file

gatling {
  charting {
    indicators {
      lowerBound = 100      # Lower bound for the requests' response time to track in the reports and the console summary
      higherBound = 300    # Higher bound for the requests' response time to track in the reports and the console summary
    }
  }
}
```

**Comment by slandelle** [comment]
> I use a pre-built docker with Gatling

Not an official component, no idea what's in there.

We have:
* `gatling-default.conf` that's contains the default value and that is baked in our jars
* `gatling.conf` (file name can be overridden with the `gatling.conf.file` System property) that contains user provided overrides
* System properties that have precedence over the above sources

I don't think we should add any extra level of overrides, what we already have looks plenty enough to me.

In your case, you should pass `-Dgatling.charting.indicators.lowerBound=100`. Or remove this `gatling.conf` file from your Docker image.
