### ISSUE TITLE
Get data of Response Time Distribution

### ISSUE THREAD

**Issue by tomers** [gatling/gatling#4033]
Not sure whether this issue is a question or feature request...
I would like to perform some statistics on Gatling's run data using Python. I need to fetch (among other things) the data of Response Time Distribution graph. It seems this data is embedded in the HTML file, and is not available as a standalone JSON file. Is there a possibility to have Gatling dump such data in a readable format? 

Thanks for your help!

**Comment by slandelle** [comment]
Sorry, but extra stats/reporting features fall in the scope of FrontLine. And indeed, FrontLine already provides an API for this.
