### ISSUE TITLE
Gradle-plugin: tune scala compiler flags by default

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4040]
On contrary to the maven plugin or the [zip bundle compiler](https://github.com/gatling/gatling/blob/master/gatling-compiler/src/main/scala/io/gatling/compiler/ZincCompiler.scala#L232-L241), the gradle plugin doesn't tune the Scala compiler flags.

This is particularly an issue when trying to compile code that uses the postfix notation (eg `1 second`) with Scala 2.13.

**Comment by Isammoc** [comment]
Documentation:
 * [ScalaCompileOptions](https://docs.gradle.org/current/javadoc/org/gradle/language/scala/tasks/BaseScalaCompileOptions.html)
 * ```groovy
     tasks.withType(ScalaCompile) {
       scalaCompileOptions.apply {
         memoryMaximumSize = '1g'
         jvmArgs = ['-XX:MaxPermSize=512m']
        additionalParameters = ['-language:postfixOps']
       }
    }
    ```
