### ISSUE TITLE
Allow configure maxBufferSize in CsvParser 

### ISSUE THREAD

**Issue by shalastra** [gatling/gatling#4045]
I have a csv feeder, where the file has a single column with http request body. In some scenarios Gatling throws an error about reaching the maxBufferSize for CsvParser and with suggestion to increase it. Unfortunately, there is no easy way to pass such an argument. 
Is it possible to add a configurable field to `stream` method in `SeparatedValuesParser`?

**Comment by slandelle** [comment]
Could you please provide the actual stacktrace you experienced?

**Comment by slandelle** [comment]
Default `maxBufferSize` is 8M chars. I'm very surprised ou have CVS cells larger than that?!

**Comment by slandelle** [comment]
@shalastra Gentle ping.

**Comment by shalastra** [comment]
@slandelle Today we agreed in my project on different parameters, so the issue no longer occurs. :) You can close the issue. Tnanks for a quick reaction.

**Comment by slandelle** [comment]
OK, thanks for the update.
