### ISSUE TITLE
 i.g.h.c.i.RequestTimeoutException: Request timeout to <host> after 60000 ms

### ISSUE THREAD

**Issue by Ankit-Laddha** [gatling/gatling#4048]
### Description
I'm not able to send a POST request to my application using Gatling. It always results in Request-Timeout. While GET request to the same application doesn't timeout.

Below is some information:
* Gatling version: 3.5.1
* gatling-maven-plugin: 3.1.1
* Tried to increase the timeout, but still it times-out.
* Running/Triggering script locally
* No Vpn/proxy/firewall configured. The application can be accessed directly over the internet.
* Running it for only one user. 
* Same request is possible via Postman, No errors with these tools.
* Attaching console logs. If you can find anything

LOGS:
[gatling-error-logs.txt](https://github.com/gatling/gatling/files/5972739/gatling-error-logs.txt)

**Comment by slandelle** [comment]
> Tried to increase the timeout, but still it times-out.

I guess you didn't remove the `#` to uncomment. Anyway, that won't fix your issue.

Impossible to tell without being able to reproduce.
The only thing I can think of is that Gatling and your server negociated TLSv1.3 but your server doesn't actually properly support it.
Please provide a way to reproduce your issue.

**Comment by slandelle** [comment]
Also, what are those super weird HTTP values for your url and host header???

```
POST /<LOGIN-PATH-FORMAT: /login> HTTP/1.1
client-language: en-pl
api-version: 102
client-version: 3.6
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
user-agent: gatling
accept-encoding: gzip, deflate
host: <HOST-format: www.xyz.com>
content-type: application/json
content-length: 117
```

**Comment by Ankit-Laddha** [comment]
Thanks for looking into it.

Those HOST and URL values I have changed for now. Just have added a format of how those values look like. I might not be able to share actual URLs and values.

Other headers (API-version, client-version) you can ignore. It will still work without them.

Regarding timeout, no I uncomment it and increased it. But it still failed. Then I reverted it back.

**Comment by Ankit-Laddha** [comment]
@slandelle should I push my code in a private repo and share it with you?

**Comment by slandelle** [comment]
Please do.

**Comment by Ankit-Laddha** [comment]
Just did. Please check. You must have received the invite.

**Comment by slandelle** [comment]
Thanks, will have a look.

**Comment by slandelle** [comment]
2 things:

1. your application requires CORS headers, so you must add a `.header("origin", "https://<DOMAIN>")` when performing a POST or an Ajax request.
2. your application is buggy. When the `origin` header is missing, it should do something: send a response with an error status, close connection, etc, but not leave the connection hanging forever like this. This would make a nice DDoS vector!

**Comment by Ankit-Laddha** [comment]
no @slandelle . Even after adding the origin header, I'm getting the same request error timeout. Did you run my test at your end by changing the header? Did it pass for you?
I've also added a comment in the README.

**Comment by slandelle** [comment]
OK, your issue is even more funny than I thought.
Your application doesn't properly parse JSON.

**Doesn't work:**

```
"""
          {
              "username": "test1@xyz.com",
              "password": "test1"
          }
        """
```

```
"""{"username": "test1@xyz.com", "password": "test1"}"""
```

**Works (removed all the spaces):**

```
"""{"username":"test1@xyz.com","password":"test1"}"""
```

**Comment by Ankit-Laddha** [comment]
oh! I can confirm this worked. ✅ Thanks a lot @slandelle 👍 
May I ask how did you discover the root cause? was there something in logged that helped you find it? It will be useful to learn this and apply in the future saving time to raise issues.

**Comment by slandelle** [comment]
As I could reproduce with curl, the issue was not with Gatling. The issue was for sure with the app choking on either the headers or the body.
I checked the browser's request and pasted elements in Gatling and it worked.
