### ISSUE TITLE
Obtain response time during execution of my simulation

### ISSUE THREAD

**Issue by politrons** [gatling/gatling#4052]
Hi all, this is not an issue but a question.

I'm using Gatling as an agent that is hitting a service that I have, as a side-car.
What I would like is make some actions if at some point the response time mean is higher than X. 

But I would like to do it during the execution of the **simulation**, and not at the end, since like I said, I'm using the simulation as an agent running all the time together with my Service.

There's any function that I can use, like **check** where I can obtain the mean of requests to do some actions?

Regards

**Comment by slandelle** [comment]
Hi,

Sorry, but as you've pointed out yourself, here is a bug tracker, hence not the right place for such question. Please use our [community mailing list](https://gatling.io/community-mailing-list/).
