### ISSUE TITLE
Recorder: Unable to record website (http2 / alpn)

### ISSUE THREAD

**Issue by amb1ent** [gatling/gatling#4055]
I was unable to record my https website, https://noodles.street-food.space/

I was able to record my http website, http://noodles.street-food.space/

I'm hosting this in an application on top of the vertx app server; https://vertx.io/

Willing to contribute but I will need some on-boarding help as a developer scala is alien to me at this point.

gatling-charts-highcharts-bundle v 3.5.1

**Comment by amb1ent** [comment]
After I added my server's ssl certificate via keystore.jks I was able to record the https website.

**Comment by slandelle** [comment]
Please check the documentation for recording over HTTPS: https://gatling.io/docs/current/http/recorder/#https-mode

**Comment by amb1ent** [comment]
Yes, there was a protocol violation [I accepted the self-signed certificate] when I used self-signed.  When I added the correct certificate to the recorder via my keystore.jks the protocol error didn't happen.
