### ISSUE TITLE
Unable to get recorder.sh working for Centos 7

### ISSUE THREAD

**Issue by vijar50** [gatling/gatling#4059]
Hello,

I am installing the latest version of Gatling on Centos 7. I am running:
Java 8
Scala 2.12

I've extracted the zip file and am able to run the gatling.sh script and simulations successfully generate reports.
However when I launch the recorder app via recorder.sh the app opens with a 'blank' screen. I.e. no buttons/fields/text etc.

I was wondering if anyone has encountered this before? Thanks

**Comment by slandelle** [comment]
> I was wondering if anyone has encountered this before?

Not I'm aware of.

Do you have an X server up?

**Comment by vijar50** [comment]
I'm not sure where the logs are located. (Nothing in the CLI)

**Comment by slandelle** [comment]
Are you sure you have a full JDK installed, including the graphical libraries for Swing and awt?

**Comment by 1t5j0y** [comment]
@vijar50 I faced this today as well on Pop OS with Java 8 on a machine with NVIDIA graphics. If you have a similar setup, what worked for me was setting the Nvidia Graphics to 'Prefer Maximum Performance'. The recorder still does not reliably always show up after this but it did show up finally a couple of times. [Stackoverflow link](https://stackoverflow.com/questions/22737535/swing-rendering-appears-broken-in-jdk-1-8-correct-in-jdk-1-7) that led me to this solution.

You could add a `-verbose` to the JAVA_OPTS in the recorder.sh file to see if there is any other issue.

**Comment by slandelle** [comment]
@1t5j0y Which version of Java 8 do you have? If you're running an old version, have you tried upgrading? Maybe you're hitting an old bug that's been fixed since then?

**Comment by slandelle** [comment]
Actually, that this is a Java bug or an NVIDIA one is pretty debatable, see https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/9971/bug-java-gui-refresh-in-8426-java-screens-wont-r/

@vijar50 Do you also have a NVIDIA GPU?

**Comment by slandelle** [comment]
Closing for lack of answer from the user.
Feel free to chime in.
