### ISSUE TITLE
Gradle plugin: Running tests with gradle may not start test on second time

### ISSUE THREAD

**Issue by Vants** [gatling/gatling#4063]
**The environment**
Gatling 3.5.1. Win10.  Running from gradle plugin. I have tried from Windows CMD and Git Bash.

**The steps**
1. Clone example gradle plugin demo https://github.com/gatling/gatling-gradle-plugin-demo.
2. Run it first time with commands that are show in readme.
3. When finished run second time.

**The problem**
When running second time I only get and tests don't start.
```
BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 up-to-date
```

When I run gatlingRun command with clean, like this `gradlew clean gatlingRun`, then it starts tests again. But this also deletes results from build folder.

**Comment by toelt** [comment]
https://stackoverflow.com/questions/29427020/how-to-run-gradle-test-when-all-tests-are-up-to-date

**Comment by slandelle** [comment]
@toelt Thanks for the tips!

@Isammoc @eshepelyuk What do you think? Should we set `gatling.outputs.upToDateWhen {false}`?

**Comment by Vants** [comment]
For my case this feature would be nice. Because I use Gatling tests with different configurations (Gatling or environment). But at the moment tip from @toelt helps. Thanks!

I did some new tests with latest Gatling but I have some with older version 3.0.2 and I didn't had such problem there. So it would be nice to have same command for running Gatling tests. At the moment it seems that we need to use that flag rerun-tasks.

**Comment by eshepelyuk** [comment]
If you refer to 3.0.2 as a plugin version, then there were no such feature at all. It was introduced later.
So, maybe a solution will be just to document `--rerun-tasks` ?

**Comment by Vants** [comment]
Gatling and plugin version both are 3.0.2

**Comment by slandelle** [comment]
@Isammoc Could you please update the documentation then?

**Comment by slandelle** [comment]
> jfyi, I am open to pick up the task of implementing a new flag in plugin settings.

It would be great, thanks a lot! Let's document for the upcoming release and then ship a new flag once you have a PR.

**Comment by eshepelyuk** [comment]
> > jfyi, I am open to pick up the task of implementing a new flag in plugin settings.
> 
> It would be great, thanks a lot! Let's document for the upcoming release and then ship a new flag once you have a PR.

Sorry @slandelle , that was almost 2 months ago. I'd advice to not rely on my spare time in nearest time :(

**Comment by slandelle** [comment]
Sorry, this went under my radar.

**Comment by mcanalesmayo** [comment]
Same issue here, we run the same load test with different parameters (fetched from environment variables). Therefore we need to use `--rerun-tasks` for now.

In case you are planning to implement a new flag in the plugin, do you have any ETA for that to be released?

**Comment by slandelle** [comment]
IMHO, having such flag only has value if we can rerun by default without impacting the whole project (typically not impacting unit tests) and this flag is used to optionally disable rerun.
Otherwise, just replacing a one line option in one place with another one line option somewhere else is really not worth it.

**Comment by mcanalesmayo** [comment]
> IMHO, having such flag only has value if we can rerun by default without impacting the whole project (typically not impacting unit tests) and this flag is used to optionally disable rerun.
> Otherwise, just replacing a one line option in one place with another one line option somewhere else is really not worth it.

I agree with that

**Comment by eshepelyuk** [comment]
@slandelle in case described by @mcanalesmayo I see it as a bug from plugin side.
Since env vars may change the behaviour of the gradle task and simulations,
so env carchange mustbe considered as code change and sumulations should be re run.
I suggest to open another issue regarding this case, maybe we could improve the code.

Wdyt ?

**Comment by Isammoc** [comment]
@eshepelyuk 
The plugin cannot know the list of effective environment variables to watch.
In such a context, that is the sole responsibility of our dear users to add the requirements to the task in their `build.gradle` as it is in their own configuration only that such environment variables exist.

In another hand, we should provide a pointer how to configure that.

Samples:
https://stackoverflow.com/questions/27612075/gradle-how-can-i-make-a-task-depend-on-an-environment-variable

WDYT?

**Comment by eshepelyuk** [comment]
I was thinking about adding a configuration parameter to a `gatling` closure, where _dear users_ :) 
could configure literally anything, that could affect simulations re-run. 
In simple example to illustrate - code below tells that task is always out of date and must be re-run

```
gatling {
   extraUpToDateCheck = { false }
}
```

Although, I understand that this is an additional work, that can't be addressed right now, so it's only my proposal for a future.

Adding a documentation is obviously a excellent idea, although I'm not yet ready to volunteer :)

**Comment by Isammoc** [comment]
What is the difference between implementing and managing this `extraUpToDateCheck` configuration parameter and the standard way:
```groovy
tasks.gatlingRun.outputs.upToDateWhen { false }
```

I really do not see any profit. Please help me out in my ignorance here.

> Adding a documentation is obviously a excellent idea, although I'm not yet ready to volunteer :)

We just did that in a [note block](https://gatling.io/docs/current/extensions/gradle_plugin/#default-tasks)

**Comment by eshepelyuk** [comment]
Ohhh, you are right @Isammoc !
I forgot about that API

**Comment by Isammoc** [comment]
Seems like we can close this issue.
@eshepelyuk WDYT?

**Comment by eshepelyuk** [comment]
> Seems like we can close this issue.
> @eshepelyuk WDYT?

Absolutely @Isammoc, Merci beaucoup !

**Comment by Isammoc** [comment]
Closed as this can be achieved following [the documentation](https://gatling.io/docs/current/extensions/gradle_plugin/#default-tasks)

excerpt:
```groovy
tasks.gatlingRun.outputs.upToDateWhen { false }
```
