### ISSUE TITLE
Callback function for "exitHereIfFailed"

### ISSUE THREAD

**Issue by Vants** [gatling/gatling#4066]
"exitHereIfFailed" and maybe "exitHereIf" needs callback function that is called when exit function is called. Then gatling tests can clean up safely (for example logout).

**Comment by notdryft** [comment]
You can do that with `exitBlockOnFailure`:

```
val scn =
  ...
  .exec(login)
  .exitBlockOnFailure {
    exec(...)
      .exec(...)
  }
  .exit(logout)
```
