### ISSUE TITLE
Transform with loop doesn't respect boolean condition

### ISSUE THREAD

**Issue by PkAIR** [gatling/gatling#4067]
Two implementation pretty similar.

1. Without cycle. It simply check value found via XPath have something in common (valid for one found item)
`exec(http("Request without cycle")
      .get("url")
      .check(status.is(200))
      .check(xpath("ValidXpathHere")
        .transformWithSession((data: String, session: Session) =>
          data.indexOf(session("someId").as[String])).gt(-1)))`

It throws error with value mismatch

2. With cycle. Similar to the first point but checks whole list of finding to contain some string
`exec(http("Request with cycle")
      .get("url")
      .check(status.is(200))
      .check(xpath("ValidXpathHere").findAll
        .transformWithSession((data: Seq[String], session: Session) =>
          data.foreach(it => it.indexOf(session("someId").as[String]).gt(-1)))))`

It won't throw any error in case of value mismatch

**Comment by slandelle** [comment]
The second one has completely broken because:

1. it abuses the implicit conversion from `Int` to `Duration`. This implicit conversion is for example used when calling `pause(1)`  instead of the actual `pause(1.second)`. Here, `gt` is a method on `Duration`, not the Gatling check DSL method.
2. it doesn't have any check comparison step, so the default `exists` applies.

formatted:

```scala
(data: Seq[String], session: Session) =>
        data.foreach(it =>
          it.indexOf(session("someId").as[String]).gt(-1)
        )
```

with explicit conversions:

```scala
(data: Seq[String], session: Session) =>
        data.foreach(it =>
         // this results either true or false, but you don't do anything from that
          it.indexOf(session("someId").as[String]).seconds
           .gt(-1.seconds)
        )
```

This would work:

```scala
. transformWithSession((data: Seq[String], session: Session) =>
        data.foreach(it.contains(session("someId").as[String]))
        )
).is(true)
```

**Comment by slandelle** [comment]
Next time, please use the [community mailing](https://groups.google.com/forum/#!pendingmsg/gatling) list for such questions.

**Comment by PkAIR** [comment]
@slandelle I'm using version 3.5.1 and firstly you solution won't work for two reasons:

1. foreach doesn't know requested 'it' - simply shows 'can't resolve it'. So you should use something like

`data.foreach(it => it.contains...)`

2. When you correct first issue you will face with 'is check'. It's hard to tell where you placed that due to brackets count mismatch.

I guess you meant to place it on 'transform' level, right? That's kinda strange because I want to check every sequence item to contain some text or it should do a final check afterwards and in case of any `false` value will fail the check?

```scala
.transformWithSession((data: Seq[String], session: Session) =>
      data.foreach(it => it.contains(session("someId").as[String]))
    ).is(true)
```
If you do so you'll get type mismatch in my example (from the original description for the issue) - `found Boolean but expected session.Expression[Unit]`

```scala
exec(http("Request with cycle") 
  .get("url") 
  .check(status.is(200)) 
  .check(xpath("ValidXpathHere").findAll 
    .transformWithSession((data: Seq[String], session: Session) =>
          data.foreach(it => it.contains(session("someId").as[String]))
        ).is(true)))
```

**Comment by slandelle** [comment]
forall, not foreach.

```scala
  exec(http("Request with cycle")
    .get("url")
    .check(status.is(200))
    .check(xpath("ValidXpathHere")
      .findAll
      . transformWithSession((data: Seq[String], session: Session) =>
        data.forall(it => it.contains(session("someId").as[String]))
      )
    .is(true))
  )
```
