### ISSUE TITLE
Error during DNS switch

### ISSUE THREAD

**Issue by b10s** [gatling/gatling#4071]
We do run some load test with Gatling by requesting some URL through proxy.

The URL's domain name at the time of test is changing from A to CNAME which finally leads to IP change.

During such change we receives the following error:

```
gatling.http.cache.dns -> io.gatling.http.cache.DnsCacheSupport$$anon$1@187a450a, 53767e8e-f3f6-41a1-a6d3-0570d26a1dc2 -> 503
```

What it might be and how to solve it?

Interestingly, when we change DNS record from CNAME to A back, there is no such issue.

**Comment by slandelle** [comment]
Could you please provide the full stacktrace?

**Comment by b10s** [comment]
@slandelle :

```
Session(PointPartsAnalytics,2,1618463946828,Map(gatling.http.cache.baseUrl -> http://my-domain.com, gatling.http.cache.dns -> io.gatling.http.cache.DnsCacheSupport$$anon$1@187a450a, 53767e8e-f3f6-41a1-a6d3-0570d26a1dc2 -> 503, timestamp.53767e8e-f3f6-41a1-a6d3-0570d26a1dc2 -> 1618463946828, gatling.http.ssl.sslContexts -> SslContexts(io.netty.handler.ssl.OpenSslClientContext@4a18f61c,None), gatling.http.referer -> http://my-domain.com/pp/analytics, gatling.http.cookies -> CookieJar(Map())),181,OK,List(GroupBlock(List(/pp/analytics),1618464446927,14,OK), ExitAsapLoopBlock(53767e8e-f3f6-41a1-a6d3-0570d26a1dc2,io.gatling.core.session.package$RichExpression$$$Lambda$486/1545327692@72451150,io.gatling.core.action.Exit@12e4ec48)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$568/1625939772@587ca90b)
```

**Comment by slandelle** [comment]
This is not the error, this is a printed Session, I guess the one of the virtual user that encountered the issue you're mentionning.
Please provide the whole logs.

**Comment by b10s** [comment]
Hm, I have no other logs other than that. It was running in Jenkins and we have such output in it.

Is it seems to be Jenkins/Gatling or proxy error? Any suggestions with reproduction, investigation will be apretiated.

I'm going to run it locally to reproduce meanwhile.

**Comment by slandelle** [comment]
No idea why you don't have more logs. Could be your Jenkins set up.
I can't provide an hint on how to investigate this without having at least the actual error, sorry.
Also, make sure you're using the latest version of Gatling, 3.5.1 atm.

**Comment by b10s** [comment]
Tested more and turned out it was our internal misconfiguration.
Let me close the ticket

**Comment by slandelle** [comment]
Honestly: huge relief :)
Thanks for the update!
