### ISSUE TITLE
HTTP: Support passing multiple BodyParts at once

### ISSUE THREAD

**Issue by asmburning** [gatling/gatling#4076]
Use Case:
   I need upload thousands of files via http, currently HttpRequestBuilder only support single BodyPart parameter, doesn't support Array or List of BodyPart.
   HttpRequestBuilder is not a real builder, because you can only build it once, you can't modify the builder after you build it,
which means you can't loop your BodyParts to the HttpRequestBuilder

**Comment by slandelle** [comment]
> I need upload thousands of files via http, currently HttpRequestBuilder only support single BodyPart parameter, doesn't support Array or List of BodyPart.

Contributions welcome. Should be super easy to add.

> HttpRequestBuilder is not a real builder, because you can only build it once, you can't modify the builder after you build it, which means you can't loop your BodyParts to the HttpRequestBuilder

A builder can perfectly be immutable, eg [that's how Cassandra Java Driver's QueryBuilder API works too](https://docs.datastax.com/en/developer/java-driver/4.9/manual/query_builder/). You have to either update the accumulator reference, or use something such as `foldLeft`.

**Comment by asmburning** [comment]
Just used Gatling and Scala for a week, not sure if the following code works
`def bodyParts(bodyParts: Array[BodyPart]): HttpRequestBuilder = {
    for (bodyPart <- bodyParts) {
      this.modify(_.httpAttributes.bodyParts).using(_ ::: List(bodyPart))
    }
    this
  }`

**Comment by slandelle** [comment]
I went this way:

```scala
def bodyParts(bodyParts: List[BodyPart]): HttpRequestBuilder = {
this.modifyAll(_.httpAttributes.bodyParts).using(_ ::: bodyParts)
}
```
