### ISSUE TITLE
Add ability to send monitoring data to VictoriaMetrics

### ISSUE THREAD

**Issue by valyala** [gatling/gatling#4078]
Gatling supports sending monitoring data to InfluxDB. It would be great adding the ability to send monitoring data to VictoriaMetrics, since it usually requires lower compute resources (RAM, CPU, disk space, disk IO) compared to InfluxDB - see [these benchmarks](https://docs.victoriametrics.com/Articles.html#benchmarks) and [these case studies](https://docs.victoriametrics.com/CaseStudies.html) for details. VictoriaMetrics supports data ingestion via multiple popular protocols:
* Influx line protocol
* Graphite plaintext protocol
* OpenTSDB protocol
* Prometheus text exposition protocol
* CSV
* JSON
See [these docs](https://docs.victoriametrics.com/#how-to-import-time-series-data) for details.

It would be great if gatling could send monitoring data to VictoriaMetrics via one of these protocols. The ingested data then can be queried via Prometheus-compatible query language - [MetricsQL](https://victoriametrics.github.io/MetricsQL.html). VictoriaMetrics supports Prometheus querying API (see [these docs](https://docs.victoriametrics.com/#prometheus-querying-api-usage)) and Graphite querying API (see [these docs](https://docs.victoriametrics.com/#graphite-api-usage)).

**Comment by slandelle** [comment]
We already support [Graphite plaintext protocol](https://gatling.io/docs/current/realtime_monitoring/#graphite).
Any additional metrics and reporting features fall into the scope of our Enterprise version.
