### ISSUE TITLE
Ability to enrich feeder's records with extra fields

### ISSUE THREAD

**Issue by madhead** [gatling/gatling#4096]
Imagine there is a CSV file with member IDs:

```csv
member
1
2
...
```

Now, image there is a third-party service providing auth tokens for this members, allowing to call the system under the test on their behalf.

What is needed in the test is a pair `member` + `token`, but the CSV feeder builder doesn't allow to enrich the records with extra fields, only convert them:

```scala
val members = csv("data/members.csv").random.convert{ case("member", member) => ... }
```

What would be great is to have an enrich method like:

```scala
val membersWithTokens = csv("data/members.csv").random.enrich{ record => record("token", TokenService.getForMember(record("member"))) }
```

**Comment by slandelle** [comment]
I don't think we'll implement this, unless there's more demand for it, in particular as it's very easy to implement on your side:

```scala
val members = csv("data/members.csv").random.apply().map{  aMapRecord => someOtherMapRecord }
```

**Comment by madhead** [comment]
@slandelle, will this construct be lazy or will it read all the data into memory?

**Comment by slandelle** [comment]
It won't change the behavior. `apply` returns an `Iterator`.

**Comment by madhead** [comment]
Ok, thanks for the quick reply with explanations!
