### ISSUE TITLE
HTTP: add a disableAutoOrigin option

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4099]
https://groups.google.com/g/gatling/c/NBW8EdronWU

We want an option similar to [disableAutoReferer](https://github.com/gatling/gatling/blob/main/gatling-http/src/main/scala/io/gatling/http/protocol/HttpProtocolBuilder.scala#L101).

The option must be propagated to [here](https://github.com/gatling/gatling/blob/main/gatling-http-client/src/main/java/io/gatling/http/client/RequestBuilder.java#L197) to not add an `Origin` value.

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue, But being a beginner, can you guide me how to contribute and what EXACTLY needs t o be done here .
thanks🙂

**Comment by slandelle** [comment]
Hi,

I've updated the issue description. Good luck! :)

**Comment by himanshu007-creator** [comment]
I still cant figure out what should i do, I dont know scala language. Please help

**Comment by slandelle** [comment]
The point of contributing is to help and alleviate the burden on core maintainers.
Plead read some tutorial on Scala, install a Scala dev environment and check the code.
