### ISSUE TITLE
[Gatling Maven plugin] The only one simulation gets executed while runMultipleSimulations=true

### ISSUE THREAD

**Issue by alexpopil** [gatling/gatling#4104]
According to the https://gatling.io/docs/gatling/reference/current/extensions/maven_plugin/, there is an option to run multiple simulations sequentially. However, when using `<runMultipleSimulations>true</runMultipleSimulations>`, even along with simulations listed explicitly within `<inlcudes>...</inlcudes>` Gatling executes only one simulation.

**Comment by Isammoc** [comment]
I just tested and it works as intended:

**Reproduction steps**
 * Clone [gatling-maven-plugin-demo](https://github.com/gatling/gatling-maven-plugin-demo)
 * Duplicate `BasicSimulation` to `BasicOtherSimulation` (to have multiple simulations)
 * Add `configuration` element and `runMultipleSimulations` element with `true` value (in `plugin` element along with `id`/`group` for the gatling plugin).
 * Launch `mvn gatling:test`

**Result**
Both simulations ran successfully one after the other.

*Note*:
For more information, please use the mailing list (and provide more information with your particular issue)

**Comment by alexpopil** [comment]
@Isammoc, thank you for such a quick response. If works indeed in the sample project you provided. But, as I found out later on, all simulations get executed as long as none of them fails due to assertion error, otherwise all simulations, following the one that failed, get skipped. Is that expected behavior? If so, is there any corresponding config parameter to prevent that?

**Comment by Isammoc** [comment]
Reopened as #4107
