### ISSUE TITLE
Gradle plugin: fail if Gatling test doesn't exist

### ISSUE THREAD

**Issue by mcanalesmayo** [gatling/gatling#4105]
When running Gatling tests like the following:
```
./gradlew gatlingRun-my.unexisting.gatling.test.GatlingTest
```
then currently the Gradle task is finishing successfully if the test doesn't exist.
My expectation is that it should at least fail and log this error to let the user know that the test doesn't exist.

**Comment by mcanalesmayo** [comment]
I'm not very familiar with groovy but I'll give it a try

**Comment by slandelle** [comment]
So actually, we won't do this, neither on the gradle plugin nor the sbt one.

This behavior is idiomatic gradle behavior. See https://stackoverflow.com/questions/22505533/how-to-run-only-one-unit-test-class-using-gradle, the `--tests` parameter takes a pattern and execute all matching classes and doesn't fail when no tests are executed.
