### ISSUE TITLE
HTTP: The default header value cannot be overridden.

### ISSUE THREAD

**Issue by kudoueiji** [gatling/gatling#4106]
I defined the following scenario.					
						
		val httpProtocol = http				
			.baseUrl("http://XXX.XXX.XXX.XXX")			
			.acceptHeader("AAA")			
			.acceptLanguageHeader("BBB1")			
						
		val headers_1 = Map(				
			"Accept-Language" -> "BBB2"			
			)			
									
		val scn = scenario("S1")    				
		      .exec(				
		        http("Request1")				
		          .get("/YYY")				
		          .headers(headers_1)				
		      )				
						
When the above scenario is executed using Gatling 3.6.0, the following three headers are set in Request1.					
	Accept: AAA				
	accept-language: BBB1				
	Accept-Language: BBB2				
						
When the above scenario is executed using Gatling 3.3.1 or an older version, Request1 is set with the following two headers.	
The value of the Accept-Language header will be overridden by the value of header_1.				
	Accept: AAA				
	Accept-Language: BBB2		

I think it works correctly with Gatling 3.3.1 and older versions.
For other headers(Accept, Accept-Language, User-Agent, Connection, Accept-Encoding, etc.) , it was confirmed that the value defined in header_1 is added instead of overwriting.

GatlingRecorder will generate a Simulation file that behaves similarly to the above.

**Comment by kudoueiji** [comment]
In acceptLanguageHeader, the header name is set as AsciiString type, 			
but in the headers method, the header name is set as String type.			
			
I used the headers method as described in the documentation.			
			
https://gatling.io/docs/gatling/reference/current/http/protocol/			
https://gatling.io/docs/gatling/reference/current/http/request/			
					
It was confirmed that the header value can be overwritten as before by defining headers_1 as follows.			
			
	val headers_1 = Map(		
		HttpHeaderNames.AcceptLanguage -> "BBB2"	
		)
	
I think there is a bug in Document and Gatling Recorder.

**Comment by slandelle** [comment]
Thanks for reporting. See #4108 for the Gatling side fix.
I'm investigating the Recorder now.

**Comment by slandelle** [comment]
Close as of #4108

I'll let the recorder as is for now.
