### ISSUE TITLE
Maven Plugin: After failed assertion in the simulation all the following ones get skipped

### ISSUE THREAD

**Issue by alexpopil** [gatling/gatling#4107]
As soon as the simulation fails due to assertion error, all the following simulations are ignored.

**Comment by Isammoc** [comment]
Note: I'm not sure if this is a feature request or a missing documentation. (I saw your message in the other issue, but I had no time to work on it yet)

**Comment by slandelle** [comment]
Contributions are welcome.
Honestly, I'm not fond of this multi run feature anyway. IMHO, running multiple tests is the responsibility of an orchestrator such as a CI tool a la Jenkins.

**Comment by slandelle** [comment]
Closing for now. We don't plan to work on this and it's been around for almost 3 years without seeing any contribution.
