### ISSUE TITLE
HTTP: Merging HTTP header maps should ignore case

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4108]
HTTP headers defined in protocol and request are not detected as having the same name when they have different cases.

**Comment by Isammoc** [comment]
Duplicate #4106 ?

**Comment by slandelle** [comment]
@Isammoc No. #4106 actually reports 2 different issues: one with Gatling and one with the recorder.

**Comment by Isammoc** [comment]
I don't see the bug in the recorder.
The recorder records headers from the browser which are not same case as netty's headers.
Now you fix the insensitive case headers merging, the recorder won't be a problem anymore, will it?

**Comment by slandelle** [comment]
That was more of a possible improvement to enforce standard HTTP/2 case, but I gave up on that.

**Comment by slandelle** [comment]
Close as of #4106
