### ISSUE TITLE
Compiling gatling and gatling-highcharts master branch

### ISSUE THREAD

**Issue by 3XC1T3D** [gatling/gatling#4109]
Hi,

i would like to complie the master branch of gatling and gatling-highcharts due to websocket based gatling tests.

Unfortunately the last release is missing some fixes for websocket testing, so i want to complile the maste branch by myself.

Could you please handle me a tutorial, how i can compile it and get the specific jar's?

Best regards

**Comment by 3XC1T3D** [comment]
Hi,

i managed to build it this way and copied the jar/zip from the local ivy cache. Is this correct?

```
cd /opt/gatling-main
sbt -Dproject.version="master" publishLocal
cd ../gatling-highcharts-main
sbt -Dproject.version="master" publishLocal
```
Best Regards

**Comment by slandelle** [comment]
Hi,

Glad you could sort this out yourself. Sorry for the delay: based in France and yesterday was a national day off.

Which WebSocket fixes are you referring to? Bug fixes should have all been ported to the 3.6 branch. Only new features can only be introduced in the next minor version.

Also, next time, could you please use the [community mailing list](https://gatling.io/community-mailinglist/) for such question and not the bug tracker?

**Comment by 3XC1T3D** [comment]
Hi,

i am referring to following pull request https://github.com/gatling/gatling/pull/4100 or following issue https://github.com/gatling/gatling/issues/3929

This is missing in the latest 3.6.1 Release. Yeah next time i will use the community mailing list. Thank you.

Best regards

**Comment by slandelle** [comment]
Exactly, so those are features, not bug fixes.

Thanks!
