### ISSUE TITLE
Want to get the response time of each requests that are being sent during the simulation

### ISSUE THREAD

**Issue by NikitaSoni1205** [gatling/gatling#4112]
**Please don't post questions here but use our [community mailing list](https://gatling.io/community-mailing-list/) instead.**

For feature requests:
 For different simulation scenarios, while using feeders to pass variable inputs to the simulation, can we have the response time for each requests that are being sent, so that we can analyse which kind of input takes more time and for which types of inputs takes less time, depending on the use case.

**Comment by slandelle** [comment]
No. Use some APM for this.
