### ISSUE TITLE
Core: Introduce a `withDefault` check step

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4114]
Built on top of `transformOption`, see https://groups.google.com/g/gatling/c/EmBcnnApZd0/m/J80BHr3iBQAJ

**Comment by jingcj** [comment]
hi, I'd like to give it try.

**Comment by slandelle** [comment]
@jingcj Great, thanks a lot!

**Comment by jingcj** [comment]
@slandelle 
Here is the PR, https://github.com/gatling/gatling/pull/4122
API docs is not updated yet, I think I need some advice

**Comment by slandelle** [comment]
Reviewed, thanks!

What kind of advice do you need about the doc?
