### ISSUE TITLE
Unable to install Grafana Datasource via cli

### ISSUE THREAD

**Issue by FischlerA** [gatling/gatling#4115]
I am unable to install the frontline datasource into my grafana deployment via the grafana cli.
The following error occures:

```
bash-5.1$ grafana-cli --pluginUrl http://downloads.gatling.io/releases/frontline-grafana-bundle/1.14.2/frontline-grafana-bundle-1.14.2-bundle.zip plugins install frontline
Error: ✗ failed to download plugin archive: Failed to send request: 403 Forbidden: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.20.0</center>
</body>
</html>
```

It appears to be an issue on the side of the gatling server as i am able to install other plugins without any issues.

I was able to install the datasource before in the version 1.13.4 but then it suddenly stopped working about a month ago.

**Comment by slandelle** [comment]
@FischlerA FYI, you should use the proper support channel (Jira Service Desk) and not this bug tracker that's only for Gatling OSS.

Can you download `http://downloads.gatling.io/releases/frontline-grafana-bundle/1.14.2/frontline-grafana-bundle-1.14.2-bundle.zip` from your web browser? Or is it only failing with `grafana-cli`?

**Comment by FischlerA** [comment]
I'm able to download the zip with curl:

```
$ curl https://downloads.gatling.io/releases/frontline-grafana-bundle/1.14.2/frontline-grafana-bundle-1.14.2-bundle.zip -o /tmp/test.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23732    0 23732    0     0  37133      0 --:--:-- --:--:-- --:--:-- 37081
```

And i'm running Grafana CLI version 8.0.4

**Comment by FischlerA** [comment]
The same error occurs on a windows machine in a completly different network

```
.\grafana-cli.exe --pluginUrl http://downloads.gatling.io/releases/frontline-grafana-bundle/1.14.2/frontline-grafana-bundle-1.14.2-bundle.zip plugins install frontline
[31mError[0m: [31m✗[0m failed to download plugin archive: Failed to send request: 403 Forbidden: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.20.0</center>
</body>
</html>
```

**Comment by FischlerA** [comment]
> @FischlerA FYI, you should use the proper support channel (Jira Service Desk) and not this bug tracker that's only for Gatling OSS.
> 
> Can you download `http://downloads.gatling.io/releases/frontline-grafana-bundle/1.14.2/frontline-grafana-bundle-1.14.2-bundle.zip` from your web browser? Or is it only failing with `grafana-cli`?

And thank you for the information about the right support channel, you can close this issue and i will make contact there :)
