### ISSUE TITLE
Is there a documentation on creating custom protocol in gatling ? 

### ISSUE THREAD

**Issue by pshingavi** [gatling/gatling#4121]
**NOTE:** This link did not work to post the question to the mailing list: https://gatling.io/community-mailing-list/

I am looking to perf test AWS lambda, kinesis etc. Wanted to see if there is any plugin recommended or if I have to create my own custom protocol and what are the steps I need to follow to do so.

**Comment by Isammoc** [comment]
Hi!
Where did you get this link?
You are right, the link is wrong, it should be [`https://gatling.io/community/`](https://gatling.io/community/)
Please let us know where is the wrong link as we can fix it.
(about your question, you should definitely ask it on the [mailing list](https://groups.google.com/g/gatling))
Cheers!

**Comment by slandelle** [comment]
> Where did you get this link?

In the original CONTRIBUTING.md. It was an issue on our side, I've fixed it.

**Comment by slandelle** [comment]
No, there's currently no tutorials for implementing custom protocol supports. Our internals are not stable so we don't want to turn them into a public API at this time.
