### ISSUE TITLE
Doc: current online version is main while it should be 3.6

### ISSUE THREAD

**Issue by ArseniyStar** [gatling/gatling#4125]
I need to use the latest HttpProtocol parameters for Websocket, which I see in the [documentation](https://gatling.io/docs/gatling/reference/current/http/websocket/#configuration).
<img width="959" alt="docs" src="https://user-images.githubusercontent.com/89085653/129740008-46fda915-5ecf-4008-b33d-a98e6144cbf2.PNG">

I see it in the latest version of Gatling in the [GitHub repo](https://github.com/gatling/gatling/blob/main/gatling-http/src/main/scala/io/gatling/http/protocol/HttpProtocolBuilder.scala).
<img width="906" alt="GitHub repo" src="https://user-images.githubusercontent.com/89085653/129740018-7c0f2c3e-7efa-4da2-8418-6c2f1603741d.PNG">

But I don't see it in the latest version in the Gradle plugin, and can't use these parameters.
<img width="934" alt="gradle" src="https://user-images.githubusercontent.com/89085653/129740058-5421dd2a-2545-4521-850c-67802fa2842a.PNG">

**Comment by slandelle** [comment]
That's a publication issue. Those features haven't been released yet and will be shipped in next Gatling 3.7.

**Comment by slandelle** [comment]
Documentation was republished and properly points to the latest **released** version.

Thanks for reporting!
