### ISSUE TITLE
App: Simplify ScanHelper?

### ISSUE THREAD

**Issue by nsoft** [gatling/gatling#4131]
Happened to wind up reading your code debugging something and noticed an oddity...

https://github.com/gatling/gatling/blob/main/gatling-commons-shared-unstable/src/main/scala/io/gatling/commons/shared/unstable/util/ScanHelper.scala#L88

creates a new JarFile object after parsing a URL that it finds on the connection an converts to a URI etc... but the jar file object is already available as

```
connection.getJarFile
```

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/JarURLConnection.html#getJarFile() 

Way simpler... did you find a case where that didn't work?

**Comment by slandelle** [comment]
Thanks for the suggestion! Honestly, I wasn't aware of this method :) IIRC, this code was inspired from Spring's, so I suspect it wasn't using `getJarFile` either.

Will give it a try, thanks a lot!
