### ISSUE TITLE
New Release 3.7.0

### ISSUE THREAD

**Issue by politrons** [gatling/gatling#4146]
Hi all,

There's any estimation of when version 3.7.0 will be released?.

Regards

**Comment by slandelle** [comment]
Well, [my answer won't change](https://stackoverflow.com/questions/69434029/gatling-dsl-in-java/69440019#69440019) if you ask here too: in a few weeks.

Also, next time, please use the [community group](https://gatling.io/community/) for questions, not the bug tracker.

**Comment by politrons** [comment]
@slandelle thanks a lot and sorry for ask here
