### ISSUE TITLE
RFC for upcoming Java support in Gatling

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4147]
Gatling 3.7 will introduce a new DSL in Java.

The goal is to make usage easier for non-Scala users: no new language basics to learn, no additional setup for Java (or Kotlin users). 

This DSL is designed as a wrapper on top of the Scala one. A critical goal is to have usage as similar as possible between Scala, Java and Kotlin.

As of now, this DSL is neither stable nor documented.

Examples of usage can be found in:
* https://github.com/gatling/gatling/tree/main/gatling-bundle/src/main/java/computerdatabase
* https://github.com/gatling/gatling/blob/main/gatling-core-java/src/test/java/io/gatling/javaapi/core/CoreJavaCompileTest.java
* https://github.com/gatling/gatling/blob/main/gatling-http/src/test/scala/io/gatling/http/compile/HttpCompileTest.scala

The goal of this ticket is to gather feedback from our community before we release a stable version where things will be way harder to change.

**Comment by tonyairwallex** [comment]
That would be great if we can support Kotlin!
