### ISSUE TITLE
RFC for upcoming Kotlin support in Gatling

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4148]
This ticket is a sibling of #4147

Gatling 3.7 will introduce a new DSL in Java.

We want this DSL is be also usable in Kotlin.

The goal of this ticket is to gather feedback from our community before we release a stable version where things will be way harder to change.

**Comment by slandelle** [comment]
Hi,

Thanks for your feedback.

1. I would love it if I could just add a library and add a test using JUnit 

This doesn't work. You have to understand that a load test has a strong requirement: it mustn't have to compete for resources  with other processes on the machine.
With such runner, what will happen for sure is:
* people running unrelated tests sequentially from the same machine, with ephemeral ports still in use (see TCP ports recycling) and ruining the next test
* worse, people running tests concurrently

2. Receiver functions

Thanks, we 'll investigate, in particular if it removes the need to have an explicit constructor (just like we do in Scala).

However:
* we still need to provide the imports because pieces of code might be extracted outside of Simulation classes, typically into constants and helper functions. Please check our tutorials.
* we still need setUp to define which populations (scenario + injection profile) we actually want to trigger. For example, you might want to define several of those, but trigger only some depending on some configuration.

**Comment by checketts** [comment]
Thanks for the quick response! Now that I've had a chance to start playing with the DSL. I'm excited to go through the tutorials, exercising the DSL, and getting a better understanding of Gatling.

I'm not sure I understood the points against JUnit. I intend to setup Gatling tests on our ci servers, running the Gatling gradle task. If I were to use a gradle test task, it would be on the same server, with potentially the same resource contention.  Perhaps you are recommending against mixing other tests with the load tests? I agree with that perspective. (I'm not pushing back, more just trying to understand if my gatling usage overall is flawed.)


>we still need setUp to define which populations (scenario + injection profile) we actually want to trigger. For example, you might want to define several of those, but trigger only some depending on some configuration.

I'll start looking into this config to better understand what you mean. It sounds like you are saying the simulation would have conditional logic calling differing `setup` calls based on the config.

**Comment by slandelle** [comment]
> I'm not sure I understood the points against JUnit.

JUnit is meant for unit tests. Unit tests are meant to be cheap, fast and run in isolation. Exactly the opposite of load tests.
As a result, unit tests framework let you run lots of tests at once, possibly in parallel to make use of all the cores so the whole test suite completes very fast and provide quick feedback.
If we were to provide a JUnit or whatever unit test framework runner, we'd end up with lots of users running broken tests because that's how they've always been using JUnit.

> Perhaps you are recommending against mixing other tests with the load tests?

I'm recommending against running load tests from a machine that runs other expensive processes at the same time: the application under test itself, other load tests, unit tests, functional UI tests eg Selenium, etc.

**Comment by checketts** [comment]
Those are great explanations. Thanks for taking the time to spell them out. I'll be sure to look into the config example you provided and try it in the DSL.

I've been digging into the Gatling DSL and am impressed with just how rich it is.

In #4147 you mentioned wanting to keep the DSL between Scala, Kotlin, and Java as similar as possible. I've been able to read the Scala examples and use them pretty easily in Kotlin. So in that regard I think the DSL is successful. 

When I learned about checks and assertions, I tried to use them in the DSL but wasn't able to find them without opening up the documentation and locating examples. So that is good that the examples were applicable between the two languages, but I was a little frustrated that the DSL wasn't discoverable for me.

However with such a powerful DSL, I'm itching to leverage Kotlin strengths using it. That could cause a little bit of drift between them. If that isn't welcome, I don't want to waste your time in that regard. However, if you are at least curious in that regard, I would be happy to flesh out my Kotlin examples completely.

Initial Kotlin DSL (still need quite a bit of work):
```kotlin
class BasicSimulation : HttpSimulation({
    http {
        baseUrl("http://localhost:8080") // Here are the common headers
                .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
                .doNotTrackHeader("1")
                .acceptLanguageHeader("en-US,en;q=0.5")
                .acceptEncodingHeader("gzip, deflate")
                .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")
    }

    scenario("scenario name") {
        get("/") // Request name is left off, because default autogenerated name
        pause(1)
        get("/sleep", requestName="sleep")
        pause(1)
        get("/flow", requestName="flow")

        post("/computers") { //Using receiver block for exposing more details for that exec call
            formParam("name", "Beautiful Computer")
            .formParam("introduced", "2012-05-30")
            .formParam("discontinued", "")
            .formParam("company", "37")
        }

    }
})
```

Current Java DSL usage in Kotlin:
```kotlin
class BasicSimulation2 : Simulation() {
    init {
        val httpProtocol = http().baseUrl("http://localhost:8080") // Here are the common headers
                .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
                .doNotTrackHeader("1")
                .acceptLanguageHeader("en-US,en;q=0.5")
                .acceptEncodingHeader("gzip, deflate")
                .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")

        val scn = scenario("scenario name")
                .exec(http("root").get("/"))
                .pause(1)
                .exec(http("sleep").get("/sleep"))
                .pause(1)
                .exec(http("flow").get("/flow"))

                .exec(http("computer").post("/computers")
                        .formParam("name", "Beautiful Computer")
                        .formParam("introduced", "2012-05-30")
                        .formParam("discontinued", "")
                        .formParam("company", "37"))

        setUp(scn.injectOpen(atOnceUsers(1)).protocols(httpProtocol))
    }
}
```

The second one just needs an 'init{}' block to behave like the Scala construction.

Potential pain points: `http()` (protocol builder) and `http("requestName")` are very different and might be cause user error if the name is left off: `exec(http().get("/"))` gives an un-helpful eror message. (`receiver type mismatch MatchGroupCollection`)

I noticed the the `SetUp` builder is mutable, but the `ScenarioBuilder` and most others aren't. I'm guessing that matches the current Scala DSL, but it would be nice to be consistent. (I would favor mutable and perhaps add a `copy` on the builder if the user needs a separate copy for their needs)

**Comment by slandelle** [comment]
> When I learned about checks and assertions, I tried to use them in the DSL but wasn't able to find them without opening up the documentation and locating examples. So that is good that the examples were applicable between the two languages, but I was a little frustrated that the DSL wasn't discoverable for me.

I see 2 possibilities:
1. have a single bootstrap object that lets you discover possible checks:

```java
http("foo")
  .get("/")
  .check(
    check.status().is(200),
    check.jmesPath("foo")
  )
```

2. directly call the check method on the parent

```java
http("foo")
  .get("/")
  .status().is(200)
 .jmesPath("foo")
```

I find the former pretty verbose.
I'm afraid the latter would be incredibly hard to implement (the check DSL has lots of optional steps) and would lose the ability to define sets of checks and pass them at once.

**Comment by phiSgr** [comment]
I have published `gatling-kt-ext`, which includes mutable builder syntax.

https://github.com/phiSgr/gatling-ext/blob/master/gatling-kt-ext/src/gatling/kotlin/computerdatabase/ComputerDatabaseSimulation.kt#L38

**Comment by slandelle** [comment]
FYI, with the upcoming changes in the Gatling syntax, you'll be able to write:

```
class BasicSimulation2 : Simulation() {
    init {
        val httpProtocol = http().baseUrl("http://localhost:8080") // Here are the common headers
                .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
                .doNotTrackHeader("1")
                .acceptLanguageHeader("en-US,en;q=0.5")
                .acceptEncodingHeader("gzip, deflate")
                .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")

        val scn = scenario("scenario name").exec(
                http("root").get("/")),
                pause(1),
                http("sleep").get("/sleep"),
                pause(1)
                http("flow").get("/flow"),
                http("computer").post("/computers")
                        .formParam("name", "Beautiful Computer")
                        .formParam("introduced", "2012-05-30")
                        .formParam("discontinued", "")
                        .formParam("company", "37")
          )

        setUp(scn.injectOpen(atOnceUsers(1)).protocols(httpProtocol))
    }
}
```

Way less verbose and flows are better formatted.
