### ISSUE TITLE
Command "sbt gatling:generateReport"  does not use src\test\resources\gatling.conf

### ISSUE THREAD

**Issue by kudoueiji** [gatling/gatling#4152]
In version 3.1.0 and earlier versions of the gatling-sbt plugin, the "sbt gatling:generateReport" command used the settings in src \ test \ resources \ gatling.conf.
However, in version 3.2.0 and later versions of the gatling-sbt plugin, the "sbt gatling:generateReport" command does not used the settings in src \ test \ resources \ gatling.conf.

I think it's a classpath related bug, but I didn't know how to fix it correctly.			
Also, I was not allowed to register ISSUE in the gatling-sbt repository, so I will register ISSUE here.

The procedure for confirming the operation is as follows.
1. Clone the master branch of the gatling-sbt-pluguin-demo repository.			
2. Change the gatling-sbt version of project\plugins.sbt to 4.0.0-M1.			
3. Execute "sbt gatling:copyConfigFiles" command to generate src\test\resources\gatling.conf.			
4. Change percentile2 in the gatling.conf file to 90(default is 75).			
5. Running the simulation with the "sbt gatling:testOnly" command produces an HTML report (percentile2 is 90).			
6. When I execute the "sbt gatling:generateReport" command, an HTML report (percentile is default 75) is generated.	
7. At this time, it was confirmed that target\scala-2.13\test-classes was not created.		
8. Move the gatling.conf file to src\main\resources.
9. When I execute the "sbt gatling:generateReport" command, an HTML report (percentile is 90) is generated.		
					
The environment that has been confirmed to work is as follows.			
・Windows 10 Pro 		
・AdoptOpenJDK 11		
・sbt 1.5.5		
・gatling 3.6.1		
・scala 2.13.6

**Comment by slandelle** [comment]
Thanks for the detailed reports.
I can confirm I can reproduce and things indeed work as expected in 3.1.0.
