### ISSUE TITLE
Core: Deprecate ${} Gatling EL syntax in favor of #{}

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4157]
Motivation:

* `${}` is a hassle in Scala with IntelliJ that prepends an `s`
* `${}` is a hassle in Kotlin that uses it for String interpolation so it has to be escaped into `\${}`
* how long for Java to implement String interpolation and use this pattern too?

Let's deprecate `${}` and introduce `#{}` so new Java and Kotlin users will directly go with the new syntax.

**Comment by phiSgr** [comment]
With the new logic, I don't think it is possible to escape the escape. I.e. having the literal `\#{` in result string.
Not that it's likely to happen, but for the sake of theoretical completeness I guess it's worth having.

To do that we need to check the parity of `extraSlashCount`.

BTW:
the section [Escaping `${`](https://gatling.io/docs/gatling/reference/current/session/expression_el/#escaping-) needs to be updated;
there is a `println` in `ElCompiler`, which I guess is a debug log.
