### ISSUE TITLE
Redis: Requesting RPOPLPUSH

### ISSUE THREAD

**Issue by shoaib42** [gatling/gatling#4163]
I've had in my past used `RPOPLPUSH` with the redis feeder. This redis operation comes in handy when you want to send a REST request on some "ID", and then reuse it in another capacity. Say for example of a bookstore (over simplified).

Queue 1 : books to be added to catalog, gatling consumes and makes a rest call (post) to add the book to the inventory
Queue 2 : Holds books that have been added from the above operation. gatling consumes and makes a rest call to get info, search etc.

`RPOPLPUSH queue1 queue2` returns the right item from queue1 and inserts it to the left in queue2

I tried adding this to the `RedisFeederBuilder` but it seems to be very strict w.r.t. to having only one key. (I don't want to dictate the implementation :) ).

PS - `RPOPLPUSH` is deprecated since 6.2.0 while the scala redis client being used for gatling hasn't caught up to the newer replacement of `RPOPLPUSH` aka `LMOVE`

**Comment by slandelle** [comment]
Hello,

Sure, such a contribution would be welcomed.

> while the scala redis client being used for gatling hasn't caught up to the newer replacement of RPOPLPUSH aka LMOVE

My feeling is that we should ditch this client:
* I'm not sure the original author still wants to actively maintain it
* Now that we're introducing Java support, this client is very cumbersome to config for Java users, see https://github.com/gatling/gatling/blob/main/src/docs/content/reference/current/core/session/feeder/code/FeederSampleJava.java#L143-L154

Regards

**Comment by slandelle** [comment]
Gentle ping

**Comment by shoaib42** [comment]
Will make time this weekend.

**Comment by shoaib42** [comment]
How are you testing the java side of this? I see `// new RedisClientPool("localhost", 6379);` in the test class. I guess I'll need setup redis :).  I'm trying to wrap this up and would like to package and test it out with a real scenario. Is there some doc detailing how to build package the binaries?

**Comment by shoaib42** [comment]
Nevermind the above comment, there is always a way to swap jars in the bundle ;)

**Comment by slandelle** [comment]
Thanks a lot!
I’m in PTO for one week, I’ll only be able to review when I’ll be back.
