### ISSUE TITLE
HTTP: Java: PATCH request actually performs a POST

### ISSUE THREAD

**Issue by C3li4** [gatling/gatling#4176]
Hi, I was trying to convert my scala tests in java ones. When I arrived to a PATCH request, it continues failing without any reasons at first sight and my logs gave me a 405 error saying POST method is not supported like following:
`WARN  o.z.p.spring.common.AdviceTraits - Method Not Allowed: Request method 'POST' not supported`
With help I finally looked it up in the Http.class from io.gatling.javaapi.http package  and it appears that for a simple patch request that is a post that is called (cf. line 54) instead of a patch.
```
@Nonnull
    public HttpRequestActionBuilder patch(@Nonnull String var1) {
        return new HttpRequestActionBuilder((new io.gatling.http.request.builder.Http(this.name)).post(Expressions.toStringExpression(var1)));
    }
```

Minor bug but confusing for beginners like me :) 

Thanks for all what you've done anyway!!

**Comment by slandelle** [comment]
Doh! Do you want to contribute a fix?

**Comment by C3li4** [comment]
Sure what should i do?

**Comment by slandelle** [comment]
Please fork the repository, send a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) and sign our [CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw/edit).
