### ISSUE TITLE
Bug: Inconsistent scenario name trim

### ISSUE THREAD

**Issue by vJoeyz** [gatling/gatling#4178]
Due to the `.trim`-ming of the scenario name in the `PopulationBuilder `https://github.com/gatling/gatling/blob/97c016dca388902ae513c6269485b319011eaf8b/gatling-core/src/main/scala/io/gatling/core/structure/PopulationBuilder.scala#L105 and the updated `scenarioBuilder` not being reassigned, there is an inconsistency between the returned `ScenarioBuilder` in `.build()` and the value of `scenarioBuilder`. 

This inconsistent value is then accessed from `ShortScenarioDescription`. Thus, scenario names ending with a space lead to crashing DataWriters with errors such as:
`12:27:09.049 [ERROR] i.g.c.s.w.ConsoleDataWriter - Internal error, scenario 'Test Scenario' has not been correctly initialized`

Solutions would be to either eliminate the trim from the PopulationBuilder, reassign the trimmed ScenarioBuilder or explicity re-trim the name in the ShortScenarioDescription.

I'd gladly implement one of the proposed solutions.

**Comment by slandelle** [comment]
Thanks for reporting!
