### ISSUE TITLE
Bug: EL debug logs

### ISSUE THREAD

**Issue by vJoeyz** [gatling/gatling#4182]
When a scenario definition contains special characters (`/` in this case) in it's EL, some kind of debug logs are outputted to the console, making logs hard to read when there are many users. These can't be turned off since they aren't logback logs.

Example scenario:
`ws("Open WS").connect("/#{chargePointSerialNumber}")`

Console output:
```
n=1 offset=0 test=true char=/
n=1 offset=1 test=false char=/
Simulation cpls.sim.core.SimulationRunner started...
```

**Comment by slandelle** [comment]
dup of #4174
