### ISSUE TITLE
Java API methods not directly compatible with Scala API objects

### ISSUE THREAD

**Issue by rafalszulejko** [gatling/gatling#4183]
The addition of Scala API to Gatling is great, but in its current form it doesn't seem like it's possible to bring Java into an existing project written using Gatling's Scala API. While I tested and confirmed possibility of compilation of Gatling project including both Java and Scala code (including enforcement of compiling Scala code first), the Java API methods only consume Java API 'wrapper' classes. This means that to bring Java into the project I would have to rewrite entire shared configuration.

Let's say I have a Scala object with shared configuration details, like `io.gatling.core.controller.inject.open.OpenInjectionStep` simulation load configuration used in multiple Scala simulations. Then I want to use it in my new Java simulation, but the API will only allow `setUp(scn.injectOpen(io.gatling.javaapi.core.OpenInjectionStep ... steps))`.

Now, I've been going through the source files of Java API and I see that most of these classes are simple wrappers including Scala object as a private member! They just hide it behind a private (in many cases) constructor and static methods. I assume that's in order to enforce Scala DSL-like usage. For some reason though, these wrapper classes have `toScala` method to export underlying Scala object. This means that I could use Java code in Scala, but not the other way around.

Because of the Java's type erasure, I cannot make a generic method to access these hidden constructors without a bloated case-by-case code that effectively makes me rewrite my original configuration.

Now, the most transparent solution allowing for most seamless use would be to overload all these methods to allow usage of the original Scala objects since unwrapping of these Scala objects happens in Java API anyway (`io.gatling.javaapi.core.ScenarioBuilder.injectOpen`). An alternative solution would be to make constructors in all Java wrapper classes public, but this would obviously lead to more redundant code.

**Comment by slandelle** [comment]
I'm afraid Java and Scala DSL interoperability is not something we'll ever do.

> Now, I've been going through the source files of Java API and I see that most of these classes are simple wrappers including Scala object as a private member!
> Now, the most transparent solution allowing for most seamless use would be to overload all these methods to allow usage of the original Scala objects since unwrapping of these Scala objects happens in Java API anyway (io.gatling.javaapi.core.ScenarioBuilder.injectOpen). An alternative solution would be to make constructors in all Java wrapper classes public, but this would obviously lead to more redundant code.

Those are implementation details that we could change. What if in a future version we decide to do the other way around and implement the Scala DSL on top of the Java one as it becomes the most popular one?

> This means that to bring Java into the project I would have to rewrite entire shared configuration.

No. This is only something you have to do if you want to have shared components. Not everyone's use case.

And then, that's something you can achieve in a matter of minutes-hours at worst. If you really don't want to do it yourself, that's something we can do for you with a contract. All in all, it would be way more efficient to migrate everything than having us trying to implement Java and Scala DSL interop.

**Comment by rafalszulejko** [comment]
AFAIK, the interoperability is there, and will be as long as one DSL builds on top of another, regardless of implementation details - there is just a decision to allow the users to have it or not (or something in between as it is now). Allowing interoperability means allowing Java devs into an existing project and less time spent on learning new language alongside new framework, so I guess not just my use case. Anyway there are dozens of factors I do not know about and the decision is not mine so thanks for the response and your point of view.
