### ISSUE TITLE
Add ability to skip incoming WebSocket text frame

### ISSUE THREAD

**Issue by HardNorth** [gatling/gatling#4185]
Hello Gatling creators!
I'm developing an experimental bot API which supports different protocols and want to measure its performance. The problem which I met is that my bot responses are not instant. It is calling some underline search engines and calculations APIs and the response may take up to minute. For this minute I have to send back "bot typing" messages to show user that the bot actually processing the request. 

I don't want to test these "bot typing" messages, moreover I don't know how many of them I will receive. It's also depends on load. Server just send them every 10 seconds while waiting. And this creates a huge problem for me as I have to process them in Gatling to be able to check actual response. If I don't do that I get those `.find.exists, found nothing` errors.

For some protocol implementations I found a workaround (i.e. socket.io), I just setup `wsAutoReplyTextFrame` with message `6` (noop). That allows me to ignore all these frames and server just ignores my answers, but other implementations are still untested. I.E. Azure Direct Line API 3.0 which does not have "noop" messages.

So I believe it will be nice to have an ability to skip some web socket frames.

The implementation is quite easy almost as `wsAutoReplyTextFrame`. I already did that in my fork: https://github.com/HardNorth/gatling/tree/ws-message-skip
But contribution guide requires unit tests. This can take time, since the code is not covered by tests already and I have no examples.

**Comment by slandelle** [comment]
This is exactly what `matching` is for, so you can filter messages of interest.
