### ISSUE TITLE
Recorder - Java format - Creating incorrect headers Map.

### ISSUE THREAD

**Issue by BharathM** [gatling/gatling#4186]
Gatling - 3.7.3, jdk - 17.0.1 , Recording format - Java 17, Intellij - 2021.03

I have recorded the script for the site https://worldpostalcode.com/ , just launching the URL. The recorded Java code contains the headers map for which "Map.ofEntries" and "Map.entry" not getting resolved. Following are the Intellij snapshot and Map code snippet. 
![Map of headers](https://user-images.githubusercontent.com/534618/147408275-d2b33943-e2da-4291-b368-01c05affd64a.jpg)
  _private Map<CharSequence, String> headers_0 = Map.ofEntries(
    Map.entry("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"),
    Map.entry("Cache-Control", "max-age=0"),
    Map.entry("If-Modified-Since", "Sat, 25 Dec 2021 19:10:34 GMT"),
    Map.entry("Sec-Fetch-Dest", "document"),
    Map.entry("Sec-Fetch-Mode", "navigate"),
    Map.entry("Sec-Fetch-Site", "none"),
    Map.entry("Sec-Fetch-User", "?1"),
    Map.entry("Upgrade-Insecure-Requests", "1")
  );_

I have added the following imports, but still, those methods are not getting resolved.
_import static java.util.Map.entry;
import java.util.Map;_

I have gone through the documentation https://gatling.io/docs/gatling/reference/current/http/request/#headers . The following code snippet given under Java is also not working, "params" can't be resolved.

_// Extracting a map of headers allows you to reuse these in several requests
Map<String, String> sentHeaders = new HashMap<>();
    params.put("content-type", "application/javascript");
    params.put("accept", "text/html");_

It looks recorder is not able to create the correct definition for the Map and the documentation is also not correct.

**Comment by slandelle** [comment]
The issue is on your side: you haven’t configured Java 17 on your IntelliJ project but an older version instead.

**Comment by BharathM** [comment]
Thank you @slandelle.
After updating the pom.xml to the desired JVM, I have not updated the repository.
