### ISSUE TITLE
Core: exitASAP loops don't exit properly

### ISSUE THREAD

**Issue by Blackbaud-ChrisBlythe** [gatling/gatling#4188]
While running a previously existing test on Gatling 3.7.3, I encountered the following error.

2022-01-06 22:24:16  [gatling-24-2] ERROR io.gatling.core.action.InnerTryMax - exitTryMax called but stack List() head isn't a TryMaxBlock, please report.

The code snippet associated with this was:

```
.asLongAsDuring(session => session.attributes.getOrElse("check_amount", "null") != "10", 30.seconds) {
      exec(http("doSomething")
        .post("https://REMOVED")
        .headers(lists_headers)
        .body(StringBody("""REMOVED"""))
        .check(jmesPath("status").is("Completed"))
        .check(jmesPath("payload.amount").transformOption(extract => extract.orElse(Some("null"))).saveAs("check_amount")))
        .pause(5.seconds)
    }
```

Basically, I'm using this to periodically poll until the expected value is returned, or the time limit is reached. The test did complete, but my automation picks up the "ERROR" text and marks it as a failure. If you have a suggestion for a workaround to avoid this ERROR until this is addressed, it would be greatly appreciated.

**Comment by slandelle** [comment]
Please provide a reproducer we can run on our side, there's nothing we can do otherwise.
In particular, your error message mentions `tryMax` and there's isn't one in your piece of code.

**Comment by Blackbaud-ChrisBlythe** [comment]
My apologies @slandelle, I did some additional digging and think it's related to the combination of the asLongAsDuring wrapped by an exitBlockOnFail. Here is a concrete example that reproduces the error.

```
package tcs

import scala.concurrent.duration._
import io.gatling.core.Predef._
import io.gatling.http.Predef._

class TryMaxError extends Simulation {
  val httpConf = http
    .baseUrl("https://prf-tusa01.app.blackbaud.net/jvtst")
 
  val scn = scenario("TryMaxError")
    .exitBlockOnFail {
        asLongAsDuring(session => session.attributes.getOrElse("check_value", "null") != "2022.1.5.2", 30.seconds) {
            exec(http("version")
                .get("https://prf-tusa01.app.blackbaud.net/jvtst/version")
                .check(bodyString.saveAs("check_value")))
            .pause(1.seconds)    
        }
        .exec{ session =>
            println("Check Value: " + session("check_value").as[String])
            session
        }
    }

  setUp(
    scn.inject(atOnceUsers(1)).protocols(httpConf)
  )
}
```

```
Simulation tcs.TryMaxError started...
AFTER
Check Value: 2022.1.5.2
09:44:55.776 [ERROR] i.g.c.a.InnerTryMax - exitTryMax called but stack List() head isn't a TryMaxBlock, please report.
```

**Comment by slandelle** [comment]
Thanks a lot, I can reproduce now! Investigating!

**Comment by slandelle** [comment]
Regression introduced in #4179
