### ISSUE TITLE
Gradle-plugin: Upgrade transitive log4j dependency to 2.17.1

### ISSUE THREAD

**Issue by domi-nika60** [gatling/gatling#4189]
Hi,
with using the newest version of gatling (3.7.3) I'm getting error:

```
Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.apache.logging.log4j:log4j-core:2.11.0.
     Searched in the following locations:
       - file: <...>/.m2/repository/org/apache/logging/log4j/log4j-core/2.11.0/log4j-core-2.11.0.pom
     Required by:
         project : > io.gatling.gradle:io.gatling.gradle.gradle.plugin:3.7.3 > gradle.plugin.io.gatling.gradle:gatling-gradle-plugin:3.7.3 > com.github.jengelman.gradle.plugins:shadow:5.2.0
```

I was checking it also for version 3.7.1.
I suppose there is some dependencies of jengelman which were not updated. 

Our artifactory is blocking vulnerable version of log4j.
When this will be updated? Or how to do it by myself manually in gradle?

**Comment by slandelle** [comment]
We'll have a new release tomorrow.

**Comment by slandelle** [comment]
Gradle plugin 3.7.3.1 is out.
