### ISSUE TITLE
shadow dependency group name update

### ISSUE THREAD

**Issue by josephnatale** [gatling/gatling#4191]
Hi there, can the  be updated to reflect the new group name?  

The current [dependency for shadow](https://github.com/gatling/gatling-gradle-plugin/blob/72ff2ad7586f51c3f47911dd001be6a6f64348f2/build.gradle#L17) is referencing the group 'com.github.jengelman.gradle.plugins', the latest version available in this group is 6.1.0 (which is currently quarantined for me).  The group 'gradle.plugin.com.github.johnrengelman' is where the latest releases are all going.  While we're at it can we update the dependency to the latest version of shadow, 7.1.2?

**Comment by slandelle** [comment]
Hi,

I'm not sure we should go this way:
* we only use a very small subset of the classes in the plugin, basically `ShadowJar` and friends
* this plugin directly uses slf4j + log4j for logging, instead of using gradle's loggers. I guess this is the reason of the quarantine comes from. It wouldn't have happened if it was using gradle's loggers as expected.

Maybe we should just fork and remove the features we don't care about, eg relocation.

That being said, contributions welcome!

**Comment by slandelle** [comment]
Please also note that the latest release of gatling-gradle-plugin upgrades log4j to 2.17.1. Not sure why old versions of the shadow plugin are being quarantine in your organization, instead of just vulnerable versions of log4j.

**Comment by josephnatale** [comment]
> That being said, contributions welcome!

I'm happy to make the change myself, but I wanted raise some awareness and get some feedback.  It sounds like there's a bit of hesitation to simply upgrading to the latest version.

> Not sure why old versions of the shadow plugin are being quarantine in your organization, instead of just vulnerable versions of log4j.

you and me both 😃

**Comment by slandelle** [comment]
We can upgrade first, it's probably easier.
Please note we want to make sure our plugin still works with Gradle [5, 7].

> I'm happy to make the change myself

Awesome!

**Comment by josephnatale** [comment]
Between struggling a bit to get my environment working (behind corporate proxy/nexus/firewall/etc) and some failing tests (hard to tell whether its environmental or due to the dependency update) I'm closing this issue and opting to substitute the dependency in my build.gradle rather than risk a breaking change.  Closing this issue.

**Comment by slandelle** [comment]
It seems modern versions of shadow don't support a wide range of gradle versions (even more restrictive than what the README states).

**Comment by josephnatale** [comment]
thanks for the update @slandelle!
