### ISSUE TITLE
HTTP: WebSocket close timeout

### ISSUE THREAD

**Issue by vJoeyz** [gatling/gatling#4194]
When running under heavy load, the situation might occur that a WebSocket close doesn't get ack'd (as is currently the case in my project). However, there is no timeout on WebSocket close requests, and thus the user stays active indefinitely. Is this a bug/missing feature or is there another way to make it time out instead?

**Comment by slandelle** [comment]
From the issue template, could you please:

> provide a Short, Self Contained, Correct (Compilable), Example (see http://sscce.org/)

**Comment by vJoeyz** [comment]
> From the issue template, could you please:
> 
> > provide a Short, Self Contained, Correct (Compilable), Example (see http://sscce.org/)

I omitted the example because there's a line in the source code pointing to this missing feature already:
https://github.com/gatling/gatling/blob/9e98ce0147e52beb1bd5426b1e89cc9fb98fcfc7/gatling-http/src/main/scala/io/gatling/http/action/ws/fsm/WsIdleState.scala#L138

**Comment by slandelle** [comment]
Well, the best way to make something happen is to provide a contribution.
The second best way is to provide an actionable reproducer that reduces the effort on our side.

**Comment by slandelle** [comment]
Also, don't you handle such timeout on the server side? Doesn't the server close the socket or is it assuming the clients will nicely close them and free resources?

**Comment by vJoeyz** [comment]
> Also, don't you handle such timeout on the server side? Doesn't the server close the socket or is it assuming the clients will nicely close them and free resources?

The latter, it expects clients to close them. I'm not sure on how to create an actionable reproducer since it's so dependent on the load I'm generating and the conditions of the server I'm testing.

I'm willing to try to contribute the timeout, could you perhaps point me to a place where a similar timeout is already implemented in the Gatling source?

**Comment by vJoeyz** [comment]
> Well, the best way to make something happen is to provide a contribution. The second best way is to provide an actionable reproducer that reduces the effort on our side.

I've created a naive prototype on my fork, which currently appears to fix my issue (although I couldn't figure out the right place for some things). Perhaps you could improve on it :).
https://github.com/vJoeyz/gatling/commit/fdad9ddcf9d95e567937b3ef495ab62f563b6c57

**Comment by slandelle** [comment]
Cherry-picked, thanks!

**Comment by vJoeyz** [comment]
> Cherry-picked, thanks!

Thank you! Will this be included in the next minor release? :)

**Comment by slandelle** [comment]
Yes
