### ISSUE TITLE
Core: New implicits in core.Predef breaks logic with Expression[Any]

### ISSUE THREAD

**Issue by jigarkhwar** [gatling/gatling#4195]
Hello!
When I migrated to gatling, I noticed a problem with the new implicits in `import io.gatling.core.Predef._`

 ```
 implicit def integerToFiniteDurationExpression(i: Integer): Expression[FiniteDuration] = intToFiniteDuration(i.toInt).expressionSuccess
  implicit def intToFiniteDurationExpression(i: Int): Expression[FiniteDuration] = i.seconds.expressionSuccess
  implicit def jlongToFiniteDurationExpression(i: java.lang.Long): Expression[FiniteDuration] = i.toLong.seconds.expressionSuccess
```

Use Case: 
our jdbc plugin https://github.com/Tinkoff/gatling-jdbc-plugin/blob/5edf8a2c6441d0af80b2f16e52e276591e195a4b/src/test/scala/ru/tinkoff/load/jdbc/test/cases/Actions.scala#L36

My script:
`InsertInto("TEST_TABLE", Columns("ID", "NAME")).values("ID" -> 20, "NAME" -> "Test 12"),`
`def values(values: (String, Expression[Any])*)`

An unexpected implicit conversion occurs
![image](https://user-images.githubusercontent.com/11795372/150557232-fe701ddb-c8ea-4203-9e48-bfd712eba09d.png)

and I Get errors because it converts Int -> FiniteDuration
`Data conversion error converting "'20 seconds'  SQL statement: (TEST_TABLE: ""ID"" INTEGER NOT NULL)"`

Also I noticed a problem with gatling-core dsl 

```
.doIfEquals(_("myInt").as[Int], 1){
          exec()
        }

.doIfEquals(1, 1){
          exec()
        }
``` 
![image](https://user-images.githubusercontent.com/11795372/150557955-38142092-7272-4c53-bb6b-7e53a369ab24.png)
![image](https://user-images.githubusercontent.com/11795372/150557998-305eb84f-6329-49fe-9a4d-6587a5d291ec.png)
![image](https://user-images.githubusercontent.com/11795372/150563396-7017ff73-bebe-447e-9eef-7ce29146b815.png)

and other cases with http queryParam, http formParam, jms etc.
https://github.com/gatling/gatling/search?q=Expression%5BAny%5D

Could you revert that implicits? We need `implicit def value2Expression`

**Comment by jigarkhwar** [comment]
Thanks! 
how soon it will be possible?

**Comment by slandelle** [comment]
Unless it becomes a blocking issue for customers, only when we'll have new features to publish. Probably 2-3 months then.
