### ISSUE TITLE
[Gatling-Java-Core] ClosedInjectionStep instance contains a wrong level duration value

### ISSUE THREAD

**Issue by kuznecc** [gatling/gatling#4197]
**The problem**
It's impossible to configure the ClosedInjectionStep instance correctly by using (a.e.) CoreDsl.incrementConcurrentUsers(userRampIncrementSize) builder. 
Each time you call methods `startingFrom` and `separatedByRampsLasting` it multiplies the initially configured level duration and eventually, you will have an injection instance with level duration like `initialLevelDuration * levelsQty * levelsQty`.

**Affected methods :**
- io.gatling.javaapi.core.ClosedInjectionStep.Composite#startingFrom
- io.gatling.javaapi.core.ClosedInjectionStep.Composite#separatedByRampsLasting(java.time.Duration)

**How to fix**
Both these methods are instantiates the new intance of a `io.gatling.core.controller.inject.closed.StairsConcurrentUsersCompositeStep` and passes to the constructor arg wrong value. 
The constructor arg expects to get a `levelDuration` but obtains `durations` instead. 

It's need just to replace `step.duration()` with `step.levelDuration()` in both mentioned method bodies.
 ``` 
public Composite startingFrom(int startingUsers) {
      io.gatling.core.controller.inject.closed.StairsConcurrentUsersCompositeStep step =
          (io.gatling.core.controller.inject.closed.StairsConcurrentUsersCompositeStep) asScala();

      return new Composite(
          new io.gatling.core.controller.inject.closed.StairsConcurrentUsersCompositeStep(
              step.usersIncrement(),
              step.levels(),
              step.duration(),   //   <----   This is a culprit !
              startingUsers,
              step.rampDuration()));
    }
```

**Comment by slandelle** [comment]
Thanks a bunch for reporting!
