### ISSUE TITLE
HTTP: Unable to send multipart request with HTTP2 enabled

### ISSUE THREAD

**Issue by kudoueiji** [gatling/gatling#4199]
Unable to send multipart request with HTTP2 enabled.

The following request was defined in the scenario and the simulation was executed.

http("request-1")
  .get("/AAA")
  .bodyPart(
     StringBodyPart("param1", "value1")
       .dispositionType("form-data")
       .charset("utf-8")
     )
  .asMultipartForm

Requests can be sent normally with HTTP / 1.1, but the following error occurs when HTTP / 2 is enabled(DSL .enableHttp2).
	
i.g.h.c.i.RequestTimeoutException: Request timeout to XXX.XXX.XXX.XXX/XXX.XXX.XXX.XXX:443 after 60000 ms

I captured the packet with WireShark and checked the contents.
Gatling was sending the payload of the DATA frame after the payload of the HEADERS frame of the request (not sending the 9 bytes of the header of the DATA frame).
It is correct to send the payload of the DATA frame after 9 bytes of the header of the DATA frame.
Probably this is a bug.

I confirmed in the following environment.
Gatling 3.7.4
AdoptOpenJDK11
* When capturing with WireShark, useOpenSsl = false in gatling.conf is temporarily set.

**Comment by slandelle** [comment]
Could you please provide a Short, Self Contained, Correct (Compilable), Example (see http://sscce.org/)?

**Comment by kudoueiji** [comment]
I'm sorry.
Attach the file to reproduce.
Change only the argument of baseUrl.

[upload.zip](https://github.com/gatling/gatling/files/7969160/upload.zip)

**Comment by slandelle** [comment]
Sorry but that's not a complete reproducer. You're missing the "Self Contained" part. I can't run this on my side, I would need a target app.

**Comment by kudoueiji** [comment]
understand.
Consider whether you can have an accessible target app.

**Comment by slandelle** [comment]
Nevermind. It was able to reproduce against httpbin (that now supports HTTP/2). It's indeed a bug.

**Comment by slandelle** [comment]
Fixed. Thanks for reporting!
