### ISSUE TITLE
HTTP: HTTP/2 connection pool doesn't work when url's host is an IP address

### ISSUE THREAD

**Issue by kudoueiji** [gatling/gatling#4200]
When HTTP / 2 is enabled, a virtual user may have multiple connections to a domain and port at the same time.

Each time you use resources in a scenario, the virtual user establishes a new connection.
Even if the virtual user already has a connection, a new connection will be added, so multiple connections will be held for the same IP address and port.

When using HTTP / 2, I think it's correct that a virtual user has 0 or 1 connection to the same IP address and port.

I confirmed in the following environment.
Gatling 3.7.4
AdoptOpenJDK11
When capturing with WireShark, useOpenSsl = false in gatling.conf is temporarily set.

**Comment by slandelle** [comment]
Could you please provide a Short, Self Contained, Correct (Compilable), Example (see http://sscce.org/)?

**Comment by slandelle** [comment]
> When using HTTP / 2, I think it's correct that a virtual user has 0 or 1 connection to the same IP address and port.

Not necessarily. In particular when the user-agent doesn't have any prior knowledge of the remote peer supporting HTTP/2. What happens if you configure prior knowledge, https://gatling.io/docs/gatling/reference/current/http/protocol/#enablehttp2

**Comment by kudoueiji** [comment]
[Sample.zip](https://github.com/gatling/gatling/files/7977364/Sample.zip)


This event seems to occur only when the IP address is set in baseUrl.
The behavior did not change with or without .http2PriorKnowledge.

In the case of the following definition,
1-request to 6-request were sent on the same connection.
Attachment TestS.scala (Simulation ID is issue.TestS)

```
  val httpProtocol = http
    .baseUrl("https://gatling.io")
    ...
    .enableHttp2


  val scn = scenario("GatlingDoc")
    .exec(
      http("1-request")...
        .resources(
          http("2-request")...,
          http("3-request")...
        )
    )
    .exec(
      http("4-request")...
        .resources(
          http("5-request"),
          http("6-request")
        )
    )
```

If you change gatling.io to an IP address, it will be sent over 3 connections.
* 1-request, 4-request ⇒Connection A
* 2-request, 3-request(1st resources) ⇒Connection B
* 5-request, 6-request(2nd resources) ⇒Connection C
Attachment TestM.scala (Simulation ID is issue.TestM)

After receiving the 1-request response,
2-request, 3-request, 5-request, 6-request are sent, but is it necessary to establish connections B and C?

**Comment by slandelle** [comment]
Fixed. Thanks for reporting!
