### ISSUE TITLE
Core: Inconsistent amount of pace iterations

### ISSUE THREAD

**Issue by vJoeyz** [gatling/gatling#4203]
The amount of paces in a during is somewhat hard to predict:
```
during(15.seconds, UUID.randomUUID.toString, false) {
      pace(5)
        .exec(xxx)
}
```
When placing a `pace` inside a `during`, the first iteration is run directly, whilst each subsequent run will wait for the pace duration to have expired because the counter was already initialized. https://github.com/gatling/gatling/blob/de546043c7a1176ac386a9da3120da51731ee410/gatling-core/src/main/scala/io/gatling/core/action/Pace.scala#L45
So the above example runs 4 times the first run, but only 3 times each following run. It can be temporarily bypassed ("fixed") by instancing a new UUID every run:
`pace(5, (() => UUID.randomUUID.toString)())`

Is this by design?

**Comment by slandelle** [comment]
The semantics of `pace` are: the virtual user shouldn't pass through here faster than once every "period".

Generally, speaking, with the during loop's default exitASAP of true, the number of iteration is expected to vary.
In your example where the loop content is one single (I guess fast) request and a pace whose duration is a divider of the loop duration, it's pretty likely this happens.

**Comment by slandelle** [comment]
Assuming response times of 5.1 seconds, you'd roughly get:
* t=0: request 1
* t=5.1: new loop iteration
* t=5.1: pace doesn't do anything
* t=5.1: request 2
* t=10.2: new loop iteration
* t=10.2: pace doesn't do anything
* t=10.2: request 3
* t=15.3: during loop with exitASAP false exits

=> 3 requests

Assuming response times of 4.9 seconds, you'd roughly get:
* t=0: request 1
* t=4.9: new loop iteration
* t=4.9: pace waits 0.1s
* t=5: request 2
* t=9.9: new loop iteration
* t=9.9: pace waits 0.1s
* t=10: request 3
* t=14.9: new loop iteration
* t=14.9: pace waits 0.1s
* t=15: request 4
* t=19.9: during loop with exitASAP false  exits 

=> 4 requests

The behavior you're experiencing is the expected one.

Indeed, `pace` is antinomic with being able to predict the number of requests.
