### ISSUE TITLE
Enhancing usability of Expressions

### ISSUE THREAD

**Issue by shoaib42** [gatling/gatling#4216]
**Clean scripts**

I've been using an implicit class for String and would help when I decide moving above 3.6. Would bringing something like this be considered.

```
object Expressionify {
  implicit class StringExp(str: String) {
     // perhaps use asExp instead of toExp
    def toExp: String = "${"+str+"}"
    def toExp(func : String): String = "${" + str + "." + func + "()}"
  }
 }
```

The pros of having this is that we end up not using string literals and its easier to maintain and reuse objects when constructing execution chains. Not to mention autocomplete and hints from IDE. As an example

```
import foo.bar.Expressionify._

object Auth {
  val myAuth : String = "auth"
  
  val getAuthToken = exec(http("some")
    .post("/give/me/token")
    .param("apiKey", "hereyougo")
    .check(jsonPath("$.authToken").saveAs(myAuth)))
}
object Stuff {
  val doStuff = exec(http("other")
    .get("/whatever")
    .headers("Authorization", Auth.myAuth.toExp))
}
```

Would be happy to help if such a contribution would be welcomed. I see the complexity of this with accessing nested dataType (maybe a varargs)
PS - would need some pointers as to where to tackle this from.

**Comment by Isammoc** [comment]
Hi @shoaib42!
Disclaimer: I'm not the one to decide ^^

IMHO, two distinct things here to discuss here:

First, your example is about `headers` one of the few method that cannot take an Expression as argument yet (I'm positive contribution are welcome here ^^)

Second, I'm not fan of the concept of this `toExp`.

We already can use constant if wanted. eg, consider:

```scala
object Product {
  val myProductId: String = "productId"

  val getAuthToken = exec(
    http("some")
      .get("/give/me/random/product")
      .check(jsonPath("$.id").saveAs(myProductId))
  )
}
object Stuff {
  val doStuff = exec(
    http("other")
      .get("/buy/product")
      .queryParam("id", _(Product.myProductId).as[String])
  )
}
```

when an expression is acceptable, it is really a function `Session => String` (or whatever correct type for the return value)
and we already have an implicit that lift a String to this. [See `ValidationImplicits` loaded through `Predef._`](https://github.com/gatling/gatling/blob/main/gatling-core/src/main/scala/io/gatling/core/ValidationImplicits.scala#L81)

So, really, I'm not sure of the plus value of this feature.

Perhaps I miss a great opportunity, please feel free to fight for your idea :wink:

**Comment by shoaib42** [comment]
> First, your example is about headers one of the few method that cannot take an Expression as argument yet

I meant to say expression string.

I'm aware of using a `_(Foo.bar).as[String]` instead of writing `${value}`. What I'm trying to address is to reduce the verbosity and remove the errors from using string literals. I'm happy with the implicits I use, I know its not the clean way when looking from the perspective of gatling DSL itself, but at least the scripts are clearer to read and speeds up coding :)

So to tackle it from a middle ground, wouldn't it be better to reduce the `_(Product.myProductId).as[String]` to something simpler? Something where the enduser doesn't have to worry about properly quoting `#${` etc.

PS -  I looked at ValidationImplicits, tried to use it in my scripts, but I can't seem to figure out what needs to be imported.

**Comment by Isammoc** [comment]
Mmmh... What's wrong with Scala's string interpolation then?

```scala
object Stuff {
  val doStuff = exec(
    http("other")
      .get("/buy/product")
      .queryParam("id", s"#{${Product.myProductId}}")
  )
}
```

Less verbose, still correct.

My point is: it is hard to tell when to use your `toExp` or not. and easy to miss if forgot or not.

About your PS:

```scala
object MyPredef extends ValidationImplicits {
  implicit class GELString(value: String) {
    def toGel[T: TypeCaster]: Expression[T] = ElCompiler.compile(s"#{$value}")
  }
}

object Product {
  val myProductId: String = "productId"

  val getAuthToken = exec(
    http("some")
      .get("/give/me/random/product")
      .check(jsonPath("$.id").saveAs(myProductId))
  )
}
object Stuff {
  import MyPredef._
  val doStuff = exec(
    http("other")
      .get("/buy/product")
      .queryParam("id", Product.myProductId.toGel)
  )
}
```

**Comment by shoaib42** [comment]
I submit my case :) . I see there is no one way of enforcing a cleaner way to write out the gatling scripts. I like your suggestion of implementing the validation implicit. Thanks a bunch :)

**Comment by slandelle** [comment]
Closing for now.
