### ISSUE TITLE
Gatling - How to retrieve Gatling raw report in CSV format from simulation log file

### ISSUE THREAD

**Issue by chittuvtu** [gatling/gatling#4218]
**Please don't post questions here but use our [community mailing list](https://gatling.io/community/) instead.**

For bugs, please: 
  1. upgrade to the latest Gatling release
  2. search this bugtracker and check if your issue hasn't been already reported
  3. provide a Short, Self Contained, Correct (Compilable), Example (see http://sscce.org/)

For feature requests, please:
  * explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment]
Please follow this bugtracker’s instructions.

**Comment by chittuvtu** [comment]
> Please follow this bugtracker’s instructions.

thanks. Can you please provide the steps n how to use the code from github to my gatling bundle and re-use it in order to generate csv file as am new to gatling tool, am finding it difficult. Thanks in advance.
