### ISSUE TITLE
Recorder: Generates corrupted simulation when scenario is too long and gets split

### ISSUE THREAD

**Issue by mcopjan** [gatling/gatling#4219]
Gatling 3.7.5

When I record a short simulation then I can compile and replay it Gatling with no problems, for longer recording it looks like recorder splits scenario into  multiple scenarios/chains. when I am trying to run it I get the following error

`
[ERROR] C:/Projects/gatling-maven-plugin-demo-scala/gatling-maven-plugin-demo-scala/src/test/scala/io/gatling/demo/RecordedSimulation2.scala:35: illegal start of simple expression
[ERROR] C:/Projects/gatling-maven-plugin-demo-scala/gatling-maven-plugin-demo-scala/src/test/scala/io/gatling/demo/RecordedSimulation2.scala:822: ')' expected but '}' found.
[ERROR] two errors found
`
[RecordedSimulation2.zip](https://github.com/gatling/gatling/files/8141850/RecordedSimulation2.zip)

**Comment by slandelle** [comment]
Thanks for reporting!
Are you interested in contributing a fix?

**Comment by mcopjan** [comment]
Hi @slandelle, unfortunately I am new to Gatling and I am not very familiar with Scala either.

**Comment by slandelle** [comment]
Thanks anyway :)
