### ISSUE TITLE
To generate the CSV raw report from Gatling Simulation Log File

### ISSUE THREAD

**Issue by chittuvtu** [gatling/gatling#4222]
Hi Team,

Can you please help me in generating the csv raw report file from gatling simulatin file. I tried some ways by copying the 'gatling-report-6.0-capsule-fat.jar' file to target folder of gatling bundle, but on executing i got capsule exception error. 
Please help me on this issue as this task is quite critical.
![GatlingReportError](https://user-images.githubusercontent.com/95242824/155852700-f69acd61-ce70-471d-b1c0-af5da59f9f00.PNG)
Your help is much appreciated.

Regards,
chittuvtu

**Comment by slandelle** [comment]
Hi,

Sorry, but what you seem to be using is definitely not an official component, hence not supported here.
