### ISSUE TITLE
[gatling-maven-plugin] failOnError flag not working

### ISSUE THREAD

**Issue by michalakadam** [gatling/gatling#4231]
Filing an issue here as it is not possible to do it in [gatling-maven-plugin repo](https://github.com/gatling/gatling-maven-plugin).

To reproduce this issue gatling-maven-plugin-demo-scala is used as an example Gatling project but the issue is reproducible on other project using same Gatling plugin and dependency version. Reproduction steps:

1. Clone [gatling-maven-plugin-demo-scala repo](https://github.com/gatling/gatling-maven-plugin-demo-scala)

Gatling plugin and dependency version at the time of reporting this issue:
```
<gatling.version>3.7.6</gatling.version>
<gatling-maven-plugin.version>4.1.3</gatling-maven-plugin.version>
```

2. Modify url of one or many get requests in [BasicSimulation](https://github.com/gatling/gatling-maven-plugin-demo-scala/blob/main/src/test/scala/computerdatabase/BasicSimulation.scala) to some dummy value eg. `.get("/url-that-does-not-exist")`

3. Run load tests with `mvn clean gatling:test`. Notice that build ends with success even though there are failed test cases and `failOnError` flag of gatling-maven-plugin is set to true by default.

4. Set `failOnError` explicitly to true in gatling-maven-plugin configuration:
 ```
<configuration>
    <failOnError>true</failOnError>
</configuration>
```
Notice that build ends with success even though according to [the gatling-maven-plugin code base](https://github.com/gatling/gatling-maven-plugin/blob/main/src/main/java/io/gatling/mojo/GatlingMojo.java#L96), it should fail.

**Comment by slandelle** [comment]
Simply having a request fails doesn't make the whole test fail. That's something for you to configure with [assertions](https://gatling.io/docs/gatling/reference/current/core/assertions/), eg have 0 failed requests.
