### ISSUE TITLE
Set environment variable in Gatling plugin

### ISSUE THREAD

**Issue by politrons** [gatling/gatling#4233]
Hi all, 

I'm using Gatling plugin 

```
<groupId>io.gatling</groupId>
<artifactId>gatling-maven-plugin</artifactId>
<version>4.1.3</version>
```

Where in my Simulation I'm trying to get some environment variables using

`System.getenv(key)`

For now I tried several things without success like add in the plugin

```
<simulationSystemProperties>
						<DELAY_SERVICE_NAME>bla</DELAY_SERVICE_NAME>
					</simulationSystemProperties>
					<propagateSystemProperties>true</propagateSystemProperties>
```

Any idea how to accomplish this?

Regards.

**Comment by Isammoc** [comment]
As stated in the issue template you deleted:
> **Please don't post questions here but use our [community mailing list](https://gatling.io/community/) instead.**

**Comment by politrons** [comment]
Sure, thanks!
