### ISSUE TITLE
CLI should format the report file with a file:// URI to make it clickable in modern terminals and editors

### ISSUE THREAD

**Issue by andrejpk** [gatling/gatling#4234]
```
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                           779 (100%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            1 (  0%)
> failed                                                 0 (  0%)
================================================================================

Reports generated in 0s.
Please open the following file: /Users/xxxx/repos/xxxxxxxxxxbuild/reports/gatling/performancetestsimulation-20220405153252036/index.html
```

It would be very helpful if this was a clickable URL. I think it's just changing [this line](https://github.com/gatling/gatling/blob/3e1e67c57032fe4a258904dc78f9f39e09c6c101/gatling-app/src/main/scala/io/gatling/app/RunResultProcessor.scala#L67) to:

```scala
println(s"Please open the following file: file://${indexFile.toFile}")
```

This is a small but useful step-saver. I can't think of any downsides unless there are people scraping the CLI output.

**Comment by slandelle** [comment]
I'm not sure how such change would behave across platforms: different Linux builds, Windows and WSL, etc. There are so many terminals out there.
I'm not sure this is a good idea or a Pandora box.

Note: iTerm2 already properly interpret the path as a clickable file url.

**Comment by slandelle** [comment]
> it doesn't create a link in the integrated terminal or run output window as it is, but adding file:// does make it a link

At least on Mac, you can directly copy-paste a path in Chrome and FireFox's navbar and they will figure out the `file://`.

**Comment by slandelle** [comment]
Writing file url instead of path experiment results:

Mac:
* IntelliJ ✅ 
* iTerm2 ✅ 
* default terminal ❌

**Comment by slandelle** [comment]
@andrejpk Do you have any update on your side?

**Comment by slandelle** [comment]
Done

**Comment by andrejpk** [comment]
Hi @slandelle , sorry for the delay, was out today. It seems like this is moving forward but I'll add a couple more test cases on Windows for the record.

**Comment by andrejpk** [comment]
| Environment | Base file | file URL |
|---|--|--|
| Windows Terminal v 1.12.109893.0 | ❌ | ✅ | 
| Putty 0.62  | ❌ | ❌ |
