### ISSUE TITLE
HTTP: WebSocket request/response time

### ISSUE THREAD

**Issue by nvollmar** [gatling/gatling#4239]
We're mostly interested in reporting of the time between sending a message over the socket and receiving a specific message back as the calculation on the server is what we really want to test under load.

Has there been anything in this regard since #1824?

**Comment by slandelle** [comment]
@nvollmar Have you checked the [documentation](https://gatling.io/docs/gatling/reference/current/http/websocket/) to see if we have what you need? I think we do.

Also, please use our [community forum](https://community.gatling.io/) for questions, not the bug tracker.

**Comment by nvollmar** [comment]
The documentation has no mention in that regard. I'll check the forum and restate the question there if necessary.

**Comment by slandelle** [comment]
@nvollmar PTAL at the check section: https://gatling.io/docs/gatling/reference/current/http/websocket/#checks

**Comment by nvollmar** [comment]
@slandelle I've checked this part, but there is no mention what kind of durations are reported/how they could be customized.

```
    ws("calculation")
        .sendText(s"""{ /* some json */}""")
        .await(5.seconds)(ws
            .checkTextMessage("calculation")
            .matching(jsonPath("$.reqId").is("#{reqId}"))
            .check(
              jsonPath("$.action").is("calculation"),
            )
        )
```

I'm interested to have the duration between sending the json and receiving the response in the report.

**Comment by slandelle** [comment]
That's what is measured. Have you given it a try?

**Comment by nvollmar** [comment]
Thanks for the confirmation, I've must misinterpreted the result then.

**Comment by slandelle** [comment]
In the above example, the check would measure the time between sending the outbound message and receiving the first matching inbound one.
