### ISSUE TITLE
Influxdb : Send minimal data in InfluxDB line protocol

### ISSUE THREAD

**Issue by shoaib42** [gatling/gatling#4255]
I'm trying to tackle the issue of pre-aggregated data being sent to influxDB. What if only the minimal data is sent to influxDB in line protocol format. And the stats shenanigans are left for influxDB (better yet the influxDB continuous queries).

As an example we send

`gatling,group=groupName,request=requestName,status=OK responseTime=42 1654790084123000042`
`gatling,request=requestName,status=OK responseTime=42 1654790084123000042`
`gatling,scenario=scenarioName,userStatus=active userCount=42 1654790084123000042`

Where status is `OK` or `KO`, and userStatus is `waiting`, `active` or `done`. The state of `All` will be implied if the influxDB query does not have the status/userStatus tag.

**Timestamp in nanosecond** Where we have the millisecond + user Id (from 0 to 999999). In the example above we have 1654790084123000042 where 1654790084123 is the timestamp in milliseconds and 000042 is user# 42. This will be necessary to avoid updating the field values. As for user#, we really don't need to have the actual userId / user#, this can be tackled while building the batch to send simply append 6 digit number from 0 to 999999.

***Can this be buggy?*** If you have a case where in one millisecond you were able to send 1M (or more) requests of the same name.

I can look into the code side of things if this feature would be considered.

**Comment by slandelle** [comment]
Sorry, but I don't think we'll ever want that.

> If you have a case where in one millisecond you were able to send 1M (or more) requests of the same name.

I suspect the perf impact will be visible before 1M events/sec, even not of the same name. I really think we'd be opening a Pandora box.

Then, stats improvements fall into the Enterprise scope.
