### ISSUE TITLE
Core: Session.getDouble throws NumberFormatException on real double value

### ISSUE THREAD

**Issue by svyaz** [gatling/gatling#4256]
I try to get double value from feeder provided value for some calculations and got this issue.
Example:
```
var myScenario = scenario("Scenario-1")
    .feed(myFeeder)
    .exec(
        session -> {
            var prd = session.getDouble("PRD");
            return session.set("NEW_PRD", prd * 5.0);
        }
    )
```
Result:
`
00:36:48.178 [ERROR] i.g.c.a.b.SessionHookBuilder$$anon$1 - 'hook-9' failed to execute: j.l.NumberFormatException: For input string: "34.20"
`
However method `getDoubleWrapper` works well.

**Comment by slandelle** [comment]
Thanks for reporting!
