### ISSUE TITLE
HTTP: Digest Authentication is not working

### ISSUE THREAD

**Issue by abdessaamad** [gatling/gatling#4257]
I am trying to execute a simple HTTP PUT request using digest authentication within a Gatling scenario, but i always get the first 401 response, it seems to not send the second request with the WWW-Authenticate header.

```  
val xml, url, username, password = ??? 
val myRequest: HttpRequestBuilder = http("http request")
   .put(url)
   .digestAuth(username, password)
   .body(StringBody(xml.toString))

val scn: ScenarioBuilder = scenario("myScenario")
    .exec(myRequest)

**Comment by slandelle** [comment]
As instructed in the[ issue template](https://github.com/gatling/gatling/blob/main/ISSUE_TEMPLATE.md), please:

> provide a Short, Self Contained, Correct (Compilable), Example (see http://sscce.org/)

Without one, we can't investigate your issue, in particular on such an exotic use case as Digest auth.

**Comment by abdessaamad** [comment]
```
package test

import io.gatling.core.Predef._
import io.gatling.http.Predef._

class Frontend extends Simulation {
  val baseUrl = "https://..."
  val username = "username"
  val password = "password"

  val httpProtocol = http
    .baseUrl(baseUrl)
    .digestAuth(username, password)

  val scn = scenario("Scenario").exec(http("/random").put("/random").body(StringBody("Hello")))

  setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
```
The request is successful with curl but not with Gatling
