### ISSUE TITLE
Feature: Add support for json to EL

### ISSUE THREAD

**Issue by oddfrost** [gatling/gatling#4261]
Hello, 
  Currently Gatling EL "supports arrays, Java List, Scala Seq and Product"
  It would be helpful to support jackson JsonNode (or some other classes) to iterate over sequences or access json properties.
  
  My use case:
  There is a web page which have template stored in json. For example
  {result: {customers: [{id: 0, name: "user1", phone: 12345...} ... ], products: [....] }}
  It renders as a form.
  User is updating all customers or other objects and for each update there is a request with updated object (whole object not a single part).
  I would like to iterate over json array and access other json properties using EL.
Like: #{savedJson.customers} or  #{customer.id}
  
  Currently on version 3.7.6 (java api) it is unsupported.
  
  For now i'm saving json object using check: jsonPath(...).transform(stringToJsonNode function).saveAs(...) for updating it and i'm saving other parts of the json to iterate over them.
  
  It is not the first time when i deal with situation like this. Some times it is jms requests. 
  Maybe other gatling users have some similar cases.

**Comment by slandelle** [comment]
I have you feeling you're not aware of existing features. It looks to me you can already achieve all of this.

1. you can save your full response body as a Map (a JSON object), see see https://gatling.io/docs/gatling/reference/current/core/check/#jsonpath

`check(jsonPath("$").ofMap().saveAs("savedJson"))`

2. Gatling EL supports key access, see https://gatling.io/docs/gatling/reference/current/core/session/el/#syntax

```java
.foreach("#{savedJson. customers}", "customer")
          .on(exec(http("get").get("/customer/#{customer.id}")))
```

**Comment by oddfrost** [comment]
Yes, i've missed ofMap() option.
Thank you!
