### ISSUE TITLE
App: Invite users to upgrade Gatling version

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4263]
Some users tend to not upgrade their Gatling version, possibly because they're not aware of the latest release and the new features and bug fixes.
Let's advertise the new releases in the console and add a deprecation warning in the HTML reports when the version is more than 1 year old.

**Comment by clfsoft** [comment]
any options to turn this feature off ?
no one ever wanna a new version to replace working ones.

**Comment by henricook** [comment]
@slandelle I'm thinking about raising a PR to disable this feature with a Java Opt (`-D`) - would you mind letting me know if this has already been discussed or you have any reason to think that the PR wouldn't be accepted?

Background: I have automatic dependency management and an allow-listed outbound environment and don't want to allow the communication required to check the release on every startup, or go through the seconds of wait time while it times out.

**Comment by slandelle** [comment]
Sorry but this has already been discussed and we wouldn't accept this PR. We do want users to upgrade.

> go through the seconds of wait time while it times out.

The connect timeout and the read timeout are both 1s, so I expect the request to last at most 2s.

**Comment by henricook** [comment]
@slandelle Darn sorry to hear that. It's a simple change with a default behaviour of `On` so it seems especially stern. It's hard to believe there are people out there without automatic dependency management taking care of this for them.

**Comment by henricook** [comment]
On the topic of timeouts I should add that it failing due to timeouts on my local machine (UK based, 1Gbit up+down, generally low latency for a residential line) was what drew my eye to it in the first place.

**Comment by slandelle** [comment]
> It's hard to believe (but I'm sure very real) that there are people out there without automatic dependency management taking care of this for them.

That's the vast majority.

> On the topic of timeouts I should add that it failing due to timeouts on my local machine

Weird. Do you have direct connection to the internet?

**Comment by henricook** [comment]
I do indeed! Maybe it was a Maven burp as it's not deterministic and seems to mostly be working now 🤷🏻
