### ISSUE TITLE
Gatling 3.8.1 gatling.bat don't show typed "simulation number" and "run description" until pressed Enter

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4270]
Version: 3.8.1 (Bundle)
OS: Windows 10 Pro
Browser: Chrome 103.0.5060.114

`gatling.bat` don't show typed "simulation number" and "run description" until pressed Enter, which may lead to confusion when running the simulation.
Example of bug for "simulation number" below.

After typed option `555` but before pressed Enter
![image](https://user-images.githubusercontent.com/30750006/178032855-8106ba46-7d7f-4946-8b65-8e8ef51ca664.png)

After pressed Enter
![image](https://user-images.githubusercontent.com/30750006/178032997-8126ae72-b1bf-4133-bfc7-e881714aafd8.png)

**Comment by slandelle** [comment]
Sorry, I don't follow. Are you saying `555` isn't displayed in your terminal until you press "Enter"?

**Comment by gemiusz** [comment]
Yes, exactly.
The typing of option (1) is visible, but after in other `selections` isn't:
![image](https://user-images.githubusercontent.com/30750006/178048935-b5c0b6f3-b904-48f7-9933-66f0f292daf1.png)

**Comment by slandelle** [comment]
Seems to be fixed by https://github.com/gatling/gatling/commit/84ee94d168df06bd224329493d16f08f5d9bfe54 🤷
