### ISSUE TITLE
App: Gatling 3.8.1 gatling.bat don't show correct error message for Simulations range

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4271]
Version: 3.8.1 (Bundle)
OS: Windows 10 Pro
Browser: Chrome 103.0.5060.114

`gatling.bat` don't show correct error message for Simulations range. 
Should be `Invalid selection, must be in Range 0 until 5` but is `Invalid selection, must be in Range 0 until 6` for 6 Simulations.

Screen below.
![image](https://user-images.githubusercontent.com/30750006/178033561-11605b4f-34d9-4094-9f60-83ddf56dade5.png)

**Comment by slandelle** [comment]
We haven't changed the message here. It has alway uses the [Scala Ranges](https://alvinalexander.com/scala/how-to-use-range-class-in-scala-cookbook/) syntax where `to` is right inclusive while `until` is right exclusive.
Then, I'm going to improve the message to use the standard mathematical notation.

**Comment by slandelle** [comment]
Thanks for the notice.
