### ISSUE TITLE
Gatling 3.8.1 gatling.bat showing StackTrace when Simulations are missing

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4272]
Version: 3.8.1 (Bundle)
OS: Windows 10 Pro

`gatling.bat` showing StackTrace when Simulations are missing. 
I think that should show only `Error message` without StackTrace.

Screen below:
![image](https://user-images.githubusercontent.com/30750006/178034662-30da94a2-3743-41ba-bf6a-4ea4c743e302.png)

**Comment by slandelle** [comment]
Thanks for reporting!
