### ISSUE TITLE
Reports: Gatling 3.8.1 Issues with sorting tables with values

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4274]
Version: 3.8.1 (Bundle)
OS: Windows 10 Pro
Browser: Chrome 103.0.5060.114

Tested on `AdvancedSimulationStep05` Simulation.

When try sort on column `Cnt/s` there aren't any changes - I think the reasons for this are values below zero, but I haven't checked how it behaves when they above zero.

![image](https://user-images.githubusercontent.com/30750006/178038001-8dc4bee8-f504-415b-9bf9-c2e9b4be4c80.png)
![image](https://user-images.githubusercontent.com/30750006/178038076-9a32eeb7-0ae6-49da-99bf-ccfe98abbff6.png)

I don't understand what is pattern for sorting `Requests` - this can be confiusing is someone want to sort by it.

![image](https://user-images.githubusercontent.com/30750006/178038246-ab7786f9-701b-44bd-8b53-b543d57c73cd.png)

**Comment by slandelle** [comment]
@franciscotco Can you please take a look?
