### ISSUE TITLE
Reports: Gatling 3.8.1 Red line of KO at "Number of requests per second" introduces confusion

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4275]
Version: 3.8.1 (Bundle)
OS: Windows 10 Pro
Browser: Chrome 103.0.5060.114

When looking at report a Red line of KO at "Number of requests per second" introduces confusion because there aren't any KO but line is appear - should be like in 3.7.6.

![image](https://user-images.githubusercontent.com/30750006/178041091-6b70472d-1991-4ba2-a933-b96588677f44.png)

**Comment by slandelle** [comment]
I'm afraid we can't do anything about this.
Between 3.7 and 3.8, we've performed a minor upgrade of the JS charts library we use to benefit from a bug fix.
Between those versions, the library authors have made the line representing an empty area (errors have always been stacked on top of successes, this hasn't changed) slightly more visible.

The only thing we could do would be to not have a series when it's empty, but that might introduce a different kind of confusing with an inconsistent behavior where a series might or might not be there.

**Comment by gemiusz** [comment]
It is possible that this line will be on the floor not on top ? So Green be above Red, but I'm not sure if this kind of showing KO is good. Will be nice to see it. But decision is for you :)

**Comment by slandelle** [comment]
It's not a line, it's an area without a width.
If we were to reverse the order, we would reverse it always, meaning that when you would have failures, their area would be display below and the successes on top.
This doesn't feel nice to me, in particular as most people would/should have more successes than failures.

**Comment by slandelle** [comment]
And then, we enforced a consistent design to always have failures stacked on top of successes in all the charts.
IMHO, consistency overcomes this more visible line.

**Comment by slandelle** [comment]
Thanks for the feedback anyway :)
