### ISSUE TITLE
Bundle: Gatling 3.8.1 in Docker reports incorrect Gatling home

### ISSUE THREAD

**Issue by laxsrbija** [gatling/gatling#4279]
I'm trying to run Gatling 3.8.1 inside a Docker container based on Ubuntu 22.04 LTS.

However, even after manually defining the `GATLING_HOME` environment variable, I get the following error:
``Gatling Home is not set correctly,
Please set the 'GATLING_HOME' environment variable to the root of the Gatling bundle.``

I was able to bypass the error by downgrading to Gatling 3.7.6 while keeping the value of `GATLING_HOME` unchanged.

**Comment by slandelle** [comment]
Sorry, but your Docker image is not something we can investigate.
It would be great if you could investigate the differences between `gatling.sh` in [3.7.6](https://github.com/gatling/gatling/blob/v3.7.6/gatling-bundle/src/universal/bin/gatling.sh) and [3.8.1](https://github.com/gatling/gatling/blob/v3.8.1/gatling-bundle/src/universal/bin/gatling.sh) and contribute a fix.

**Comment by slandelle** [comment]
There's a chance you're missing one of the bundle's directory.
I've improved the error reporting, see https://github.com/gatling/gatling/commit/2f5baac1f079f1363053832299c04c5a17af9c70
