### ISSUE TITLE
Documentation site makes "flashes" when using dark mode when changing subpages.

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4280]
OS: Windows 10 Pro
Browser: Chrome 103.0.5060.114

When changing subpages on [Documentation](https://gatling.io/docs/gatling/) when using dark mode you will noticed "flashes".
If you have fast eye you can noticed that when page is changed at first moment is loaded light version of page (Visible Moon icon) and after that is changed to dark (Visible Sun icon).

**Comment by slandelle** [comment]
@notdryft Could you please take a look?

**Comment by notdryft** [comment]
I've just published a fix for the flashing. It is good on your end? The fonts might still blink a bit though.

**Comment by gemiusz** [comment]
In my opinion, it works perfectly.

**Comment by slandelle** [comment]
Great!
Nice job @notdryft !
And thanks for the help @gemiusz !
