### ISSUE TITLE
Reports: Dark Theme

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4281]
It would be nice to have Dark Theme in reports.

**Comment by slandelle** [comment]
@franciscotco @gpoulet Is this even feasible? I mean, these reports are static files. Can they store some cookie so that a Theme preference can be saved accros pages?

**Comment by luish** [comment]
@slandelle it could use [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), though that is not a good idea when opening the reports locally (i.e. file:// url) as each browser might behave differently.

Maybe just a simple toggle that would add a query parameter to the page URL, something like `index.html?theme=dark`  would suffice? The js code could get this value with

```js
const queryParams = new URLSearchParams(window.location.search);
const currentTheme = queryParams.has('theme') ? queryParams.get('theme') : 'default';
```

And toggle-switch the markup with
```js
document.documentElement.setAttribute('data-theme', currentTheme);
```

Then the CSS would set variables for the colors
```css
[data-theme="dark"] {
    --primary-color: #fff;
    --bg-color: #000
}
```

If users are linking to that report published somewhere then they could just append the theme value to the link to default it to the dark theme.

**Comment by gemiusz** [comment]
Can be this a parameter in gatling.conf  or/and additionall parameter when running -ro ?

**Comment by slandelle** [comment]
Yes, I suspect that having an option to render light or dark mode at generation time is the only way.

**Comment by slandelle** [comment]
I flagged this feature request as "contribution welcome" :)

**Comment by micheljung** [comment]
> Yes, I suspect that having an option to render light or dark mode at generation time is the only way.

Nah, with a bit JavaScript and CSS this is rather easy :) https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web

**Comment by micheljung** [comment]
@slandelle see my MR - what do you think? :)

**Comment by micheljung** [comment]
@slandelle the last release was quite a long time ago, any chance to release 3.10.0 soon?

**Comment by slandelle** [comment]
@micheljung Gatling 3.10.3 is already out 😁
