### ISSUE TITLE
The number of active users constantly increases when using constantUsersPerSec in Gatling 3.8.1

### ISSUE THREAD

**Issue by ghost** [gatling/gatling#4282]
When running a test with constantUsersPerSec using Gatling 3.8.1, the number of active users reported into console/graphite constantly increases. The resulting html report also contains an increasing trend.
Here is a simple reproducer:
```
import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration.DurationInt

class TestSimulation extends Simulation {

  setUp(
    scenario("TestScenario")
      .exec(http("Test").get("https://gatling.io/"))
      .inject(constantUsersPerSec(1) during 10.seconds)
  )
    .protocols(http)
}
```

Gatling 3.7.6:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/17594673/178246267-dfcbb741-1b78-4d82-84fe-7fb00a933416.png">

Gatling 3.8.1:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/17594673/178246338-a68d0180-2911-4cb6-a684-93d8e4742b02.png">

**Comment by vas78** [comment]
Great, thanks @slandelle!
