### ISSUE TITLE
JavaApi. Can not execute scenario as action

### ISSUE THREAD

**Issue by oddfrost** [gatling/gatling#4290]
Gatling 3.8.2 Java Api
Example in kotlin: 
```
val first_scenario = scenario("scenario one")
                      .feed(someFeeder)
                      .exec(someAction)

val second_scenario = scenario("scenario two")
                      .exec(first_scenario) //will be shown as error in IDE
```

As i can see in scala it is still available to execute one scenario from another and in gatling 3.7 this feature was available in java api. Looks like it was missed somehow.

**Comment by slandelle** [comment]
Accepting to let users in the Scala DSL do was a design error. It wasn’t documented and I decided to not reproduce this design error in the Java DSL.

The correct way to reuse is:

`ˋ`kotlin
val chain = feed(someFeeder)
                      .exec(someAction)

first_scenario = scenario("scenario one")
                      .exec(chain)

val second_scenario = scenario("scenario two")
                      .exec(chain)
