### ISSUE TITLE
Documentation: Can't scroll with Up/Down Arrow Keys

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4291]
On all pages in Internet (Main page of Gatling too ;)) it's posibble to scroll up and down by Arrow Keys.
In [Gatling Documentation]( https://gatling.io/docs/gatling/) this isn't working and this can be frustrating :/
Can you fix this please :)

**Comment by notdryft** [comment]
Fixed and deployed, thanks for reporting!
