### ISSUE TITLE
Confusing console prompt when overriding directory param in conf file

### ISSUE THREAD

**Issue by Narryel** [gatling/gatling#4294]
Version 3.8.2. 
Local bundle. 

Prerequisites: 
- i have written my scenarios with Kotlin and placed them to dir src/test/.../gatling 
- change conf/gatling.conf file gatling.directory.simultaions parameter to absolute path to my src/test/.../gatling dir
- ./gatling.sh -rm local
- confusing console message that i have no simulations (that's true i think, since gatling only supports .java files), but points me to default simulations dir instead of overrode one.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/35465534/182250972-6634cf07-59c0-4a2e-804a-3e2506171f26.png">

thanks in advance!

**Comment by slandelle** [comment]
As mentioned in the [documentation](https://gatling.io/docs/gatling/tutorials/installation/#using-the-bundle):

> This package only support Java and Scala, not Kotlin. For using Kotlin, you’ll need a [maven](https://gatling.io/docs/gatling/tutorials/installation/#maven) or [gradle](https://gatling.io/docs/gatling/tutorials/installation/#gradle) project.

**Comment by Narryel** [comment]
@slandelle sorry, but why did you decline that? root problem is not that i used kotling, but the confusing console ouptut

**Comment by slandelle** [comment]
@Narryel Sorry, misunderstood your report as it was mentioning kotlin with the bundle.
Fixed.
Thanks for reporting.
