### ISSUE TITLE
ValidationImplicits /  implicit def stringToExpression has a resolve problem

### ISSUE THREAD

**Issue by jigarkhwar** [gatling/gatling#4295]
I have kafka plugin
Method with Expression arguments
https://github.com/Tinkoff/gatling-kafka-plugin/blob/c248bbe48a6350692e7deba6035657f45b2be983/src/main/scala/ru/tinkoff/gatling/kafka/request/builder/Sender.scala#L34

When I up-to-date gatling version to 3.8.2 
i get error https://github.com/Tinkoff/gatling-kafka-plugin/runs/7410371792?check_suite_focus=true#step:4:38 

```
[error] /home/runner/work/gatling-kafka-plugin/gatling-kafka-plugin/src/test/scala/ru/tinkoff/gatling/kafka/examples/Avro4sSimulation.scala:63:35: type mismatch;
[error]  found   : String("Key")
[error]  required: io.gatling.core.session.Session => ?
[error]         .send[String, Ingredient]("Key", Ingredient("Cheese", 0d, 70d)),
```

Gatling 3.7.6 is have no this problem

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/11795372/182400468-086e8300-fd93-4c23-9fdd-84336faa7ce6.png">

**Comment by jigarkhwar** [comment]
Workaround 

`send[String, Ingredient]("Key".expressionSuccess, Ingredient("Cheese", 0d, 70d))`

**Comment by slandelle** [comment]
Sorry, but we can't help with your third-party plugin.

Please provide a [simple reproducer](https://stackoverflow.com/help/minimal-reproducible-example) that only relies on Gatling code.
For example, the following example compiles just fine with Gatling 3.8:

```scala
def foo[K, V](key: Expression[K], value: Expression[V]): Unit = ???
foo[String, Int]("#{bar}", 1)
foo[String, Int](_ => "bar", session => 1)
```

**Comment by slandelle** [comment]
@jigarkhwar Any news on this?

**Comment by slandelle** [comment]
@jigarkhwar Does this mean you've found a solution? Will you be able to upgrade to Gatling 3.8?

**Comment by jigarkhwar** [comment]
https://github.com/Tinkoff/gatling-kafka-plugin/pull/89/files

the problem was with headers, which caused a type mismatch with send[k,v] (k, v, h) and send[k,v] (k, v) 
but there is one strange thing that worked on version 3.7
