### ISSUE TITLE
Gatling 3.8.3 > Gradle 7.5 > Cannot Configure Gradle plugin > Class GatlingPluginExtension is final

### ISSUE THREAD

**Issue by ghilainm** [gatling/gatling#4300]
Bug introduce with Gatling 3.8.3 was working with 3.8.2.

I use Groovy Gradle DLS because the Kotlin one was not working anyway.

Here is the error I encounter

´´´
An exception occurred applying plugin request [id: 'io.gatling.gradle', version: '3.8.3']
> Failed to apply plugin 'io.gatling.gradle'.
   > Could not create an instance of type io.gatling.gradle.GatlingPluginExtension.
      > Class GatlingPluginExtension is final.
```

Here is my Gatling configuration

```
gatling {
    simulations {
        include("**/XXXSimulation.java")
    }
}
´´´

**Comment by slandelle** [comment]
Please upgrade your plugin to 3.8.3.1.
