### ISSUE TITLE
Gatling 3.8.X Console Sumarise Report - Response Time Distribution descriptions not shown correctly.

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4302]
Gatling: 3.8.X (gatling-charts-highcharts-bundle-3.8.X)
OS: Windows 10 Pro
JDK: jdk-17.0.4

After end of Simulation is shown Summarize Report but in section about Response Time Distribution descriptions are not shown correctly.
![image](https://user-images.githubusercontent.com/30750006/182952391-7f6c9fc3-bc7c-4087-ae42-20fce2fd0301.png)

**Comment by slandelle** [comment]
Thanks!
