### ISSUE TITLE
HTTP: asyncNameResolution  causes a WARN log on MacOS

### ISSUE THREAD

**Issue by y0j0** [gatling/gatling#4304]
I'm trying to run Gatling tests on my new Mac with M1 chip and I started to getting this error

`i.n.r.d.DnsServerAddressStreamProviders - Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.`

Then my tests are failing because of that. 

I found some [Github issue](https://github.com/netty/netty/issues/11020) on netty where they recommend to use `osx-aarch_64` 

My environment:
java -version
`
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment Homebrew (build 18.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.2+0, mixed mode, sharing)
`

mvn -version
`Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec
Java version: 18.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/18.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_SK, platform encoding: UTF-8
OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"`

gattling version
`3.8.3`

Any idea how to fix that please?

**Comment by slandelle** [comment]
Can you please confirm that you're enabling `asyncNameResolution`?

> Then my tests are failing because of that.

I'm not sure about that. This log is a WARN (an excessive one IMO), not an ERROR.

**Comment by y0j0** [comment]
Yes, this is warning but I see it as a reason why I'm getting such errors afterwards

`Request 'get-results' failed for user 247: i.n.r.d.DnsNameResolverTimeoutException: [/122.38.133.13:53] query via UDP timed out after 5000 milliseconds (no stack trace available)`

or

`get-api-version: KO i.n.r.d.DnsNameResolverTimeoutException: [/188.168.1.1:54] query via UDP timed out after 5000 milliseconds (no stack trace available)`

I'm getting such errors for all the requests.

The `asyncNameResolution` is enabled.

**Comment by slandelle** [comment]
Could you please add the missing dependency:

```xml
<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-resolver-dns-native-macos</artifactId>
  <version>4.1.79.Final</version>
  <classifier>osx-aarch_64</classifier>
</dependency>
```

It should fix the WARN log. Does it fix your DNS resolution issue too?

**Comment by slandelle** [comment]
@y0j0 The missing dependencies will be added in the next release. This fixes the WARN log.
Then, I can't say if it's related to your actual issue of not being able to resolve your hostname.

If you still face an issue, please open a different ticket and include a way to reproduce.
