### ISSUE TITLE
Core: add random generators to Gatling EL

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4305]
We could consider adding some random generator functions to Gatling Expression Language, such as:
* random numbers (int, long), possibly with a range
* random UUUI
* random alphanum Strings with a length

Note: as this is a feature, it has to go in a minor version, which we release ~3 months.
Implementation would be similar to what we do with `currentTimeMillis`.
Performance is a must, so I recommend using `ThreadLocalRandom`.

**Comment by shoaib42** [comment]
Mind if I pick this?

**Comment by slandelle** [comment]
@shoaib42 Sure! I recommend you go one by one so we can review and advice quickly. `randomUUID()` is probably the easiest one as it's parameterless.

**Comment by shoaib42** [comment]
@slandelle I'm thinking of two version of randomUUID, The java OOTB uses a secure random = slow. Would be nice to have a faster one where I build it up using two long randoms. I tried this and shows over 6x difference in generating these, which I think can be improved further :) . For some very strict cases users will need a UUID generated using secure random.

Here are my other thoughts.

1. While at it, why not add something like `#{myList.randomSubList(5)}` that returns a max of 5 random elements from the list. Use case: randomly pick 5 items from the catalog (which was returned as a json) and do what the boss told you to do, in a foreach loop
2. An isEmpty/notEmpty on a collection, gatling only has exists.

**Comment by slandelle** [comment]
> The java OOTB uses a secure random = slow.

Agree, that's why I [suggested](https://github.com/gatling/gatling/issues/4305#issue-1331433567) using `ThreadLocalRandom`. 

1. This is kind of covered by [findRandom](https://gatling.io/docs/gatling/reference/current/core/check/#findrandom)
2. OK. Could work also with Strings

Then, this is becoming an epic. IMO, we should go with baby steps.

**Comment by shoaib42** [comment]
@Amerousful Ah well, all cool! Maybe you can add this (or an improved version of what I've). It generates a pseudo UUID in scala using ThreadLocalRandom (just two calls). Using secure random may lead to a "hung" JVM when entropy "runs out", this will be very frustrating to the end user.

We can get a little bit faster by removing the second call to `nextLong` and replacing it with a fudged data like this

```
val msbees = ThreadLocalRandom.current.nextLong()
val lsbees = msbees + 0xFFFFFFFFL
```

[Faster UUID](https://gist.github.com/shoaib42/fd7b9bee1cd65d5cdecf9f07bd3ea4b0)

**Comment by slandelle** [comment]
Agree with @shoaib42 to have a faster less secure UUID implementation.

Then, @shoaib42 , there's only one way to have correct microbenchmarks on the JVM: [JMH](https://github.com/openjdk/jmh).

**Comment by Amerousful** [comment]
@shoaib42 Nice point, thank you) I'm gonna check performance for both methods
@slandelle ok, I will provide results here

**Comment by shoaib42** [comment]
@Amerousful scrap the idea I proposed `val lsbees = msbees + 0xFFFFFFFFL` , since the LSBs are dependent on MSBs and there is a likelihood of a collision. It would be nice if you can share what you see from your end (performance of fastUUID)

**Comment by Amerousful** [comment]
@shoaib42  I thought about collisions, but decided to check performance at first) Ok, got it

**Comment by Amerousful** [comment]
@shoaib42 @slandelle Hey there! I created a repository with benchmark: [link](https://github.com/Amerousful/gatling-el-random-benchmark), so you can check results. Seems like the native UUID method has better performance. 
I need to say it was my first experience with JMH and I hope did everything correct. I'm talking about load setup like: iterations, blackhole, etc...

**Comment by shoaib42** [comment]
@Amerousful thanks, I briefly looked at that, I'll test this myself over the weekend.

The array to map nibbles to char, we have a mix of int and char. That would trigger a toChar conversion.

Anyways let's keep the faster one. (Just let me try it ☺️).

Thanks a bunch!

**Comment by slandelle** [comment]
@Amerousful Could you please try the following implementation?

```scala
object UnsecureUUID {

  private val Version4Mask = 2L << 62
  private val VariantMask = 2L << 62

  def version4UUID(): UUID = {
    val rnd = ThreadLocalRandom.current()
    var mostSigBits = rnd.nextLong()
    var leastSigBits = rnd.nextLong()
    // first, ensure type is ok
    mostSigBits &= ~0xF000L // remove high nibble of 6th byte
    mostSigBits |= Version4Mask
    // second, ensure variant is properly set too (8th byte; most-sig byte of second long)
    leastSigBits = (leastSigBits << 2) >>> 2 // remove 2 MSB
    leastSigBits |= VariantMask // set 2 MSB to '10'
    new UUID(mostSigBits, leastSigBits)
  }
}
```

Also, I think it would be way better to go with the generators one by one so we can discuss the syntax, the design and the implementation for each?

IMHO, for UUID, we should have `uuid()` and `securedUuid()` with the latter using standard `UUID#randomUUID()`. Both of them should generate `UUID` and not Strings.

@shoaib42 `UUID#toString` was intrisic'ed in modern Java versions, so if you run benchmarks involving String representation, make sure to use Java 17.

**Comment by slandelle** [comment]
@Amerousful I've updated your benchmark with my generator:

```
[info] Benchmark                                      Mode      Cnt        Score   Error  Units
[info] BenchmarkUUID.nativeUUID                     sample  7490346      400.736 ± 4.121  ns/op
[info] BenchmarkUUID.newUUID                        sample  7644042       51.768 ± 3.231  ns/op
```

Clear win

**Comment by Amerousful** [comment]
@slandelle Yep, the same)
```
[info] Benchmark                                      Mode       Cnt        Score   Error  Units
[info] BenchmarkUUID.nativeUUID                     sample  44308312      422.396 ± 0.714  ns/op
[info] BenchmarkUUID.uuidv4                         sample  38334773       23.829 ± 0.373  ns/op
```

**Comment by Amerousful** [comment]
I have to admit I would not be able to write generator as yours

**Comment by Amerousful** [comment]
Is the next topic about random number? Need to agree a parameters format. In PR I did this:
```
"#{randomNumber(10)}"
"#{randomNumber(5,10)}"
"#{randomNumber(5, max)}"
"#{randomNumber(5, maxL)}"
```

**Comment by slandelle** [comment]
> I have to admit I would not be able to write generator as yours

You can check the RFC: https://www.rfc-editor.org/rfc/rfc4122.html

But honestly, I was in a hurry and adapted https://github.com/cowtowncoder/java-uuid-generator/blob/master/src/main/java/com/fasterxml/uuid/impl/UUIDUtil.java#L154-L160. All credits go to @cowtowncoder.

**Comment by slandelle** [comment]
> Is the next topic about random number?

Can we please go with topics one by one? First have a PR for UUID and merge it.

**Comment by Amerousful** [comment]
Got it. @slandelle here you are https://github.com/gatling/gatling/pull/4313

**Comment by slandelle** [comment]
I'm closing this ticket (an epic) in favor of individual tickets.
Let's take the discussion about random numbers generators in #4316.
