### ISSUE TITLE
In IDEPathHelper method invocation toURI() may produce NPE

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4308]
JDK: 17
Repository: [gatling-maven-plugin-demo-java](https://github.com/gatling/gatling-maven-plugin-demo-java)
Class: [IDEPathHelper](https://github.com/gatling/gatling-maven-plugin-demo-java/blob/main/src/test/java/IDEPathHelper.java)

![image](https://user-images.githubusercontent.com/30750006/183509660-7c6dcae9-e244-4b07-917a-ab4714869cf1.png)

Example of NPE:

![image](https://user-images.githubusercontent.com/30750006/183510131-38e42dce-81ee-44c7-a30d-eadc7592613c.png)

**Comment by slandelle** [comment]
Well, this class is just a convenient helper that's based on the hypothesis that the `gatling.conf` file is present as expected in all the demo projects. We really want to keep things simple here. I'm not sure adding more error handling here is really worth it.

**Comment by gemiusz** [comment]
The IDE (IntelliJ IDEA) recommends to use Objects.requireNonNull in this place and that can be best and simpler solution it this should be simple as possible.

**Comment by slandelle** [comment]
Have you given it a try?
If I'm correct, `Objects.requireNonNull`  will also throw a NPE, except that you won't benefit from the NPE improvements in Java 17 with the helpful error message.

**Comment by gemiusz** [comment]
Yes you are right but IDE and Qodana don't show information about potential NPE so "potentialy this can fixed it" ;)

**Comment by slandelle** [comment]
Done.
Thanks for the suggestion.
