### ISSUE TITLE
Reports: increase width of reports

### ISSUE THREAD

**Issue by biski** [gatling/gatling#4323]
Hello, 

please increase the width of the table with stats. There is a lot of free space that could be used and names of requests could be displayed without cutting. Full names of requests allow user to use ctrl+f and easly find specific request.

Charts also could be wider. It will help a lot to analyze some cases.

Before:
![image](https://user-images.githubusercontent.com/350362/188427648-4f0d3b35-9285-4da4-90c7-8a286f0b3d20.png)
After:
![image](https://user-images.githubusercontent.com/350362/188427684-f36374d8-64e5-41b2-94c9-542e54798f6a.png)

**Comment by slandelle** [comment]
What is your screen width and what have you changed between the 2?

**Comment by biski** [comment]
Now I'm using full hd display but WQHD/4k screens are becoming popular.
I've disabled this in firefox to make this example screenshot:
![image](https://user-images.githubusercontent.com/350362/188429452-d0c73838-ac90-4123-acb2-83da4a8bd13f.png)
Could you include it in next release?
And of course it doesn't help  with short request names.

**Comment by slandelle** [comment]
@franciscotco WDYT?

**Comment by gemiusz** [comment]
Not everyone has a 4k monitor and some people working using only notebook screen so width should be... dynamically :)

Screen:
![image](https://user-images.githubusercontent.com/30750006/188474118-2b60aa25-63e4-4827-8932-396f089dcdac.png)

**Comment by franciscotco** [comment]
I will have a look to improve the responsive design of the page for widescreen. Regarding the research by ctrl-f, I can crop the text in CSS instead of JS. So, the full name will appear in the DOM, and the search will be able to find occurrences.

**Comment by biski** [comment]
I've upgraded Gatling to v3.8.4 and I see differences. Requests names are longer and tables are wider.
Thanks for changes.
But there are still big white places on the sides which could be used for a wider table.
![Selection_999(1184)](https://user-images.githubusercontent.com/350362/191944700-50dff4a9-038e-4d10-a0f2-ad33381e860d.png)

Please consider removing width attribute as I showed you in my first comment to make tables width even more dynamically

**Comment by MatthewKr** [comment]
Our tests last about 100h. Analyzing charts will be more effective seeing them wider on the screen. Charts should dynamically adjust to the resolution of browser window.
