### ISSUE TITLE
Core: stopInjector don't wait for save results of previously exec

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4326]
Gatling: 3.8.3
OS: Windows 10 Pro
JDK: jdk-17.0.4

stopInjector should wait for save results of previously exec.

Scenario:
```
public class StopInjectorStatusCodeSimulation extends Simulation {

    HttpProtocolBuilder httpProtocol =
            http
                    .baseUrl("https://postman-echo.com");

    ScenarioBuilder scn =
            scenario("GeMi_ExitHereStatusCodeSimulation")
                    .exec(
                                            http("GeMi_ExitHereStatusCodeSimulation_get")
                                                    .get("/status/414")
                                    )
                    .stopInjector("EndOfThis");
    

    {
        setUp(scn.injectOpen(atOnceUsers(1)).protocols(httpProtocol));
    }
}
```
Simulation.log is empty.

Console:

![image](https://user-images.githubusercontent.com/30750006/188467272-fb0ce45b-2485-4c2e-b97c-89f295888769.png)

**Comment by slandelle** [comment]
That's indeed a bug: we were performing a hard stop instead of a graceful one, so in your case the log file wasn't forcefully flushed (and it never was naturally because the buffer is never full with just one single request performed).

Thanks for reporting!
