### ISSUE TITLE
Report: second header line for detailed view of request

### ISSUE THREAD

**Issue by ppzarebski** [gatling/gatling#4329]
**Feature request**:
Please consider adding second header line in 'details' tab of report containing request name.

**Case**:
I am adding some id at the end of name of every request that helps me find such request in application logs, for example the slowest one etc.
In details tab of report there is list of requests with my custom names that I am adding while scenario is running, however these names are uncopiable without opening source file. I think that request name could be added as second header line.

Alternatively add some feature that will allow adding description to the request, please.

**Comment by slandelle** [comment]
Hi,

That's maybe something we'll consider for a future iteration on the reports.

Then:
* in 3.8.4, long truncated names will be searchable in full
* the full name is displayed on hover on the truncated one
* I'm not sure your use case makes a lot of sense for the reports. On the contrary, making each request execution generate a unique request name defeats the goal of our reports: no aggregation (1 request per request name) so no distributions/percentiles, probably a humongous number of request names. An performance or visual display issue would be considered out of scope.
