### ISSUE TITLE
Gatling.conf has typo for Java TLS debugging

### ISSUE THREAD

**Issue by ahus1** [gatling/gatling#4334]
The gatling.conf contains the text: 

> useOpenSsl = true                    # if OpenSSL should be used instead of JSSE (only the latter can be debugged with -Djava.net.debug=ssl)

Unfortunately this Java property is missing an "x", and therefore doesn't work as described. The correct property is `javax.net.debug`, see https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html

As this took me a while to figure it out after I want to safe myself and other that time by fixing the typo. 

I'll prepare a PR for this.

**Comment by slandelle** [comment]
Thanks for your contribution!
