### ISSUE TITLE
Reports: Not shown full name of selected request

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4336]
Gatling: 3.8.4
OS: Windows 10 Pro
JDK: jdk-17.0.4
Browser:  Chrome (105.0.5195.127)

Details on below screens.

If selected:
![image](https://user-images.githubusercontent.com/30750006/191095088-8dc4c1ae-7a8b-4bda-9240-46dd76aef16e.png)

If not selected:
![image](https://user-images.githubusercontent.com/30750006/191095218-acdfe3a2-3343-4722-839d-4d465651ab20.png)

**Comment by slandelle** [comment]
Thanks for reporting @gemiusz !
We're going to investigate.
