### ISSUE TITLE
Gradle plugin 3.8.4 - can't configure gatling section when using build.gradle.kts 

### ISSUE THREAD

**Issue by kkocel** [gatling/gatling#4337]
I try to set `logLevel` and `logHttp` using Kotlin Gradle file:

```kotlin
gatling {
    logLevel = "TRACE"
    logHttp = ALL
}
```

When I do that I get:

>Cannot access 'io.gatling.gradle.JvmConfigurable.Trait.FieldHelper' which is a supertype of 'io.gatling.gradle.GatlingPluginExtension'. Check your module classpath for missing or conflicting dependencies

<img width="1003" alt="Screenshot 2022-09-23 at 13 47 00" src="https://user-images.githubusercontent.com/454412/191957194-ac4d0993-72b2-419b-adfc-b25804e14c9e.png">

**Comment by slandelle** [comment]
Reading [this](https://youtrack.jetbrains.com/issue/KT-18592), it seems it's some incompatibility between groovy and kotlin.

**Comment by slandelle** [comment]
Fixed as of gatling-gradle plugin 3.9.0.1

**Comment by kkocel** [comment]
@slandelle after new Gradle release it will change - https://twitter.com/sdeleuze/status/1641697648792018945
Worth to re-test after that.

**Comment by slandelle** [comment]
@kkocel The issue was that kotlin was struggling with Groovy traits, which we got rid of.
