### ISSUE TITLE
HTTP WebSocket: Impossible to read all messages after connection

### ISSUE THREAD

**Issue by AnastasiiaKulimova** [gatling/gatling#4338]
**Use Case:**
1) Connect to the Websocket.
2) Read and check all messages from the server after the connection.

**Problem**
In the latest version of Gatling it's impossible to read and check all message after connection.
So, in the Gatling Instruction:
```
//#check-from-connect
  exec(ws("Connect").connect("/foo").await(30 seconds)(myCheck))
```

I could not implement `loop `( `repeat, forever`, etc.)  with checking messages inside this `exec()` .
I tried to create other `exec()` with loop on reading messages - but also got a trouble.

The single way to do this case, repeat a lot of `await()` methods inside `exec(ws("Connect"))`, something like that:
```
exec(ws("Connect").connect("/foo")
.await(30 seconds)(myCheck)
.await(30 seconds)(myCheck)
.await(30 seconds)(myCheck)
...
)
```

But it's a bad decision cause I need to open a lot of connections and get a lot of messages.

Is it possible to allow gatling loop possibility for `await(N)(check)`  on reading messages  after the connection  to websocket?

Thanks in advance,
Anastasiia
`

**Comment by sergeylysov** [comment]
I got the same problem 
I faced the same problem
Please heeelpppp

**Comment by Amerousful** [comment]
@AnastasiiaKulimova  You can send simple ping request instead of connection. Something like that:
```
ws("WS ping with wait...")
    .sendText("{}")
    .await(10 seconds)(myCheck)
```

**Comment by slandelle** [comment]
> Read and check all messages from the server after the connection.

"all" doesn't have any generic meaning in a multiplexed protocol like WebSocket. 

> But it's a bad decision cause I need to open a lot of connections and get a lot of messages.

Absolutely not. This will only open 1 connection. You're only calling `connect` once.

> The single way to do this case, repeat a lot of await() methods inside exec(ws("Connect")), something like that:
>
> exec(ws("Connect").connect("/foo")
> .await(30 seconds)(myCheck)
> .await(30 seconds)(myCheck)
> .await(30 seconds)(myCheck)
> ...
> )

Wrong, you can do:


```scala
exec(ws("Connect").connect("/foo")
 .await(30 seconds)(myCheck, myCheck, myCheck)
)

or
exec(ws("Connect").connect("/foo")
  .await(1.second)(Iterator.continually[WsFrameCheck](myCheck).take(3).toList: _*)
```
