### ISSUE TITLE
Use "by name" parameters in Assertion DSL to support dynamic variables

### ISSUE THREAD

**Issue by kpritam** [gatling/gatling#4339]
Currently all the `AssertionBuilder` API's take parameters eagerly hence use cases where one has to assert against mutable variables does not work.

In below example, `totalRequests.get()` always returns `0` in assertion even though that is getting incremented on every request.
```scala
private val totalRequests = new AtomicInteger(0)
scn
  .inject(atOnceUsers(10))
  .assertions(global.successfulRequests.count is totalRequests.get())
```

**Actual**
------------
```scala
def is(value: T): Assertion
```

**Expected**
--------------
```scala
def is(value: => T): Assertion
```

**Comment by slandelle** [comment]
Sorry, but that’s something we won’t do. Assertions must be serializable, which a function isn’t.
