### ISSUE TITLE
core-java: doWhileDuring evaluates condition before execution

### ISSUE THREAD

**Issue by jakubskalak** [gatling/gatling#4345]
While working on some tests in Java I found that **doWhileDuring** is making evaluation of condition before execution.

Found piece of code which may cause this problem:
https://github.com/gatling/gatling/blob/112b2de2a12ae81a05b9695e20daf67dea7e4951/gatling-core-java/src/main/scala/io/gatling/javaapi/core/internal/loop/ScalaDoWhileDuring.scala#L86

It looks same as:
https://github.com/gatling/gatling/blob/112b2de2a12ae81a05b9695e20daf67dea7e4951/gatling-core-java/src/main/scala/io/gatling/javaapi/core/internal/loop/ScalaAsLongAsDuring.scala#L86

So I understand this as probably wrong call _asLongAsDuring_ instead of **doWhileDuring**  in **ScalaDoWhileDuring**

Gatling version: 3.8.4

**Comment by slandelle** [comment]
Oops. Thanks for reporting!
