### ISSUE TITLE
HTML Report: Improve 'Print to PDF' layout/view

### ISSUE THREAD

**Issue by meck93** [gatling/gatling#4353]
#### Current Situation

It is almost impossible to export the HTML report to a multi-page PDF with the current CSS configuration. The PDF always contains a single page with the scrollbars visible. See attached screenshot.

![no-media-query](https://user-images.githubusercontent.com/22457755/203335643-e1543bef-fb00-4e8f-8d6a-444a1183db71.png)

#### Solution Proposal

Modern browsers support a media query called: `@media print` with which the CSS can be customized when a HTML page printed (e.g., when a user clicks 'Print to PDF' in the browser). 

I have experimented a little bit and with the main CSS file: [https://github.com/gatling/gatling/tree/main/gatling-charts/src/main/resources/io/gatling/charts/assets/style/style.css](https://github.com/gatling/gatling/tree/main/gatling-charts/src/main/resources/io/gatling/charts/assets/style/style.css) and have added the following print media query. 

##### Additional CSS

```css
@media print {
	.nav {
		display: none;
	}

	.cadre {
		overflow-y: unset;
	}

	.content-in {
		overflow-x: unset;
	}
}
```

It hides the sidebar navigation and removes the horizontal and vertical scrollbars, allowing the content to flow over multiple pages. 

![with-media-query](https://user-images.githubusercontent.com/22457755/203335845-1ea49be7-4a61-4302-a878-cb1866e51374.png)

I'd be happy to contribute this as a PR, if others think this might be a valuable addition.

**Comment by slandelle** [comment]
Looks like a good idea. So indeed, could you please provide a PR?

**Comment by meck93** [comment]
> Looks like a good idea. So indeed, could you please provide a PR?

Yes, sure. Here you go: https://github.com/gatling/gatling/pull/4354
