### ISSUE TITLE
Gradle plugin: Rewrite in kotlin

### ISSUE THREAD

**Issue by Isammoc** [gatling/gatling#4357]
As kotlin is now the standard for plugin for gradle, we should rewrite our plugin.

Pros:
 * will naturally solve issue with kotlin gradle configuration #4337 
 * will use a typed language (more close to scala we know how to use)

Cons:
 * we don't know kotlin either
 * will have to dig in gradle documentation
 * time consuming

Requirements:
 * Current user groovy gradle configuration should still work (except for the plugin version itself, obviously)

**Comment by Isammoc** [comment]
I personally am in favor of a complete rewrite to follow the best practice of kotlin plugin for gradle. (ie, I don't advise to translate from our current groovy implementation)

**Comment by slandelle** [comment]
If we decide to go this way, it's paramount that the existing groovy configuration keeps on working, or at least that the change is minimal.

**Comment by Isammoc** [comment]
> If we decide to go this way, it's paramount that the existing groovy configuration keeps on working, or at least that the change is minimal.

Agree! Perhaps avoid to hard set the gatling version but let the user decide? (as in maven plugin?)

**Comment by slandelle** [comment]
> Perhaps avoid to hard set the gatling version

It's not hard set, it's a default value.
