### ISSUE TITLE
Maven Plugin: Since version `4.2.8` the `jvmArgs` are ignored

### ISSUE THREAD

**Issue by ahopgood** [gatling/gatling#4363]
Since version `4.2.8` of the `gatling-maven-plugin` ignores any values in the `jvmArgs` block:
```
<plugin>
    <groupId>io.gatling</groupId>
    <artifactId>gatling-maven-plugin</artifactId>
   <version>4.2.8</version>
    <configuration>
        <failOnError>true</failOnError>
        <includes>
            <include>ExampleSim</include>
        </includes>
        <jvmArgs>
            <args>-Dmy-arg=test</args>
        </jvmArgs>
    </configuration>
</plugin>
```
Simulation class that reads this arg:
```
public class ExampleSim extends Simulation {
    private String arg  = System.getProperty("my-arg","failed to find arg");

    {
        System.out.println(arg);
    }
}
```

When using version `4.2.7` the correct argument is printed out but with version `4.2.8` the argument doesn't seem to be passed through.

I believe the bump in `gatling-enterprise-plugin-commons` in this commit [https://github.com/gatling/gatling-maven-plugin/commit/159c4b60317efad115dcc880b6e6e66a3a482fa5](https://github.com/gatling/gatling-maven-plugin/commit/159c4b60317efad115dcc880b6e6e66a3a482fa5) resulting in replacing `MainWithArgsInFile` with `ForkMain` may be the culprit.

**Comment by slandelle** [comment]
gatling-maven-plugin:4.2.9 is being published.

**Comment by slandelle** [comment]
Thanks for reporting!
