### ISSUE TITLE
Session.java - > public List<String> groups() - Not correct Javadoc

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4367]
Hi,
I'm looking into Gatling and found a not proper Javadoc - should refer to returned groups list:
https://github.com/gatling/gatling/blob/07d8beb96c7293573039347e598b9fefc5908cba/gatling-core-java/src/main/java/io/gatling/javaapi/core/Session.java#L409-L416

**Comment by slandelle** [comment]
Fixed, thanks!

**Comment by gemiusz** [comment]
I'm not sure if fix is correct :)
Please check my comment: https://github.com/gatling/gatling/commit/6a0e9fb64d06cf54d6a406948b9a0b072af23ba6#r93529766

**Comment by gemiusz** [comment]
@slandelle ?? :)

**Comment by slandelle** [comment]
@gemiusz Fixed. But please understand that I'm on vacation :)

**Comment by gemiusz** [comment]
@slandelle ohh sorry...
Have a great vacations :)
Beware of Sharks or Bears ;)
