### ISSUE TITLE
Documentation: Realtime Monitoring - Link to not actual version of InfluxDB Telegraph’s Graphite input

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4371]
Acctual version of InfluxDB Telegraph is 1.24 but Documentation refer to 1.20:

https://github.com/gatling/gatling/blob/b4e431758e775a3887bf54d41b2758e9116b49d6/src/docs/content/guides/realtime_monitoring/index.md?plain=1#L59

I wondering if it will be better to set version to `latest`:
https://docs.influxdata.com/telegraf/latest/data_formats/input/graphite/

**Comment by slandelle** [comment]
> I wondering if it will be better to set version to latest

Agree. Do you want to send a PR?

**Comment by gemiusz** [comment]
I will try to prepare PR :)

**Comment by gemiusz** [comment]
PR: https://github.com/gatling/gatling/pull/4372
