### ISSUE TITLE
Documentation: Tutorials - Quickstart - not properly showing Windows paths

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4373]
Browser: Chrome 108.0.5359.125

Strange violet color in Windows paths for `recorder.bat` and `gatling.bat`. 

![image](https://user-images.githubusercontent.com/30750006/210115491-15470fbf-d913-406e-96d6-404a88551065.png)
![image](https://user-images.githubusercontent.com/30750006/210115725-dc024cc6-82b9-40ef-872b-4448639ec399.png)

**Comment by slandelle** [comment]
@notdryft is working on a fix. Thanks for reporting!
