### ISSUE TITLE
Core: DataWriter as custom plugin

### ISSUE THREAD

**Issue by kubehe** [gatling/gatling#4375]
Feature request:

Allow to register custom DataWriters as plugins.

In old versions it was possible to create custom plugins for DataWriters. This was broken due to [this commit](https://github.com/gatling/gatling/commit/62330b9ebb2fc0abf64b447be1ad996f211681d2)

**Comment by slandelle** [comment]
As already explained in your previous message, this won't happen.
All additional data related features for in the scope of Gatling Enterprise and are declined from the open-source/free version.

**Comment by kubehe** [comment]
It's a bit disappointing that adding custom DataWriters was removed this way.

After all if someone doesn't want to pay then they could just replace data writer engine class with their own and make it work anyway, just uglier.

Other tools have this feature for free and it's not a dealbreaker to purchase enterprise.
