### ISSUE TITLE
Feature Request: Allow for dynamically setting the runDescription in the Simulation

### ISSUE THREAD

**Issue by mikesnare** [gatling/gatling#4384]
I pass many command line options to my simulation class in order to alter each run with things like environment, number of users, ramp time, etc, but there's no way to take those command line options and use them to add text to the report that makes it clear what was run to generate the report.

It would be nice if we could set the `runDescription` inside the scala/java code in the simulation class.  I could then take all the command line options (or the defaults if they weren't given) and generate a string that represents the current run.  That would then make it to the report, which be a huge help as you build up lots of reports over time.

The `-rd` option isn't really an option for me since A) I'm not using `gatling.sh` and B) it would mean encoding the same information twice (once for the params itself, and once for the description which I'd like to derive from the params).

**Comment by slandelle** [comment]
Hi,

Sorry, but that's not something we will do (nor can).
The `runDescription` is resolved outside and logged in the `simulation.log` **before** the Simulation gets executed.

You'll indeed have to compute it upfront.

Note: Gatling Enterprise automatically logs the Simulation parameters for each run.
