### ISSUE TITLE
Core: logback-classic dependency update

### ISSUE THREAD

**Issue by ViliusS** [gatling/gatling#4386]
It is common to use gatling in a testing suite which also uses Selenium and https://github.com/bonigarcia/webdrivermanager . Since these projects now have migrated to slf4j 2.0, running gatling tests will produce the warnings below because of dependency conflict:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/vs/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

In order to avoid this logback-classic dependency in gatling project needs to be updated to 1.4 series which is compatible with slf4 2.0 by default.

**Comment by slandelle** [comment]
> It is common to use gatling in a testing suite which also uses Selenium and https://github.com/bonigarcia/webdrivermanager .

I'd argue that's a bad practice to mix them altogether in the same classpath. You're bound to have dependency versions clashes.

The only safe solution is to isolate Selenium and Gatling tests in different modules so they don't share dependencies.

Then, the workaround is to properly handle your transitive dependencies versions with [dependencyManagement](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html).

> In order to avoid this logback-classic dependency in gatling project needs to be updated to 1.4 series which is compatible with slf4 2.0 by default.

This would solve it for you, but break things for all other users who are still on slf4j 1. Netty is still using slf4j 1, so is hibernate 6.

As a consequence, that's not a move we'll be doing as long as slf4j 2 is not the dominant version.

**Comment by ViliusS** [comment]
Isn't logback-classic 1.4 backward compatible with slf4j-api v1? I think it should be https://www.slf4j.org/faq.html#compatibility

**Comment by slandelle** [comment]
That was not my understanding when I first read it:

> Please note that the table below applies by analogy not just to slf4j-simple but also to other providers such as (...), logback-classic (...)

slf4j-api version | slf4j-simple version | Result | Explanation
-- | -- | -- | --
1.7.x | 2.0.x | no bindings can be found warning message | 2.0.x providers do not act as 1.7.x/1.6.x compatible bindings

So my understanding was that logback-classic 1.4 that depends in slf4j 2 would not work with slf4j 1.7.

But indeed, I haven't given it a try.

Have you?

**Comment by slandelle** [comment]
I gave a it try and confirm that logback 1.4 does NOT work with slf4j 1.7:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
```

IMO, logback 1.3 should have been logback 2 because of this change.

So, back to my original response: this upgrade would probably break things for lots of users, so t's not something we can easily do until slf4j 2 domnates over slf4j 1.

**Comment by ViliusS** [comment]
> So, back to my original response: this upgrade would probably break things for lots of users, so t's not something we can easily do until slf4j 2 domnates over slf4j 1.

I guess this is a chicken and egg problem then. Nobody is migrating to slf4j 2 because everyone is waiting for slf4j 2 to dominate.

**Comment by slandelle** [comment]
Agree. Like dropping Java 8 support and enforcing Java 11 or better Java 17.
But it’s the responsibility of major frameworks (Spring, Hibernate, Quarkus) to lead the way.
And regarding slf4j/logback, my opinion is that their breaking change is super aggressive and they could have provided compatibility.


Anyway, we’ll keep this ticket open so other people can jump in and weight in(being frank: customers have lots if weight here).
And as I said, you should probably isolate Gatling, Selenium and maybe your application ‘s classpaths.
