### ISSUE TITLE
Core: checksum Check is not threadsafe

### ISSUE THREAD

**Issue by jhalliday** [gatling/gatling#4388]
When using a csv feeder with columns "url,sha1sum" to fetch static content with known checksum values,
then applying
```
.check(sha1().is(session->session.getString("sha1sum"))
```
the check will pass so long as there is only one user, but fail incorrectly in the face of concurrency.
The equivalent check
```
bodyBytes().transform((bytes) -> {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        return String.format("%040x", new BigInteger(1, md.digest(bytes)));
    } catch (Exception e) {
        return null;
    }
}).is(session -> session.getString("sha1sum"))
```
will, by contrast, behave correctly in concurrent cases. i.e. the response content is correct, the built-in checksum calculation apparently isn't.

gatling version 3.9.0 on Java 19.

**Comment by slandelle** [comment]
You're absolutely right! 🤦 
I don't know when  broke this, probably some time ago.

Thanks a lot for reporting!

**Comment by slandelle** [comment]
@jhalliday  Gatling 3.9.1 is out.
