### ISSUE TITLE
Unable to override Java memory allocation flags in Gatling Bundle 3.8 and 3.9 with OpenJDK

### ISSUE THREAD

**Issue by avbenavides** [gatling/gatling#4389]
Unable to override Java heap flags in Gatling Bundle 3.8 and 3.9 with OpenJDK.

When setting JAVA_OPTS with -Xms and -Xmx flags, they are not honored when running OpenJDK. This impacts tests that use more than 128M allocated memory (when simulating thousands of users).

OpenJDK honors the rightmost flag if duplicated:

```bash
/opt/gatling $ $JAVA_HOME/bin/java -version; $JAVA_HOME/bin/java -Xmx1G -XX:+PrintFlagsFinal -Xmx2G 2>/dev/null | grep MaxHeapSize
openjdk version "13-ea" 2019-09-17
OpenJDK Runtime Environment (build 13-ea+32)
OpenJDK 64-Bit Server VM (build 13-ea+32, mixed mode, sharing)
   size_t MaxHeapSize                              = 2147483648                                {product} {command line}
   size_t SoftMaxHeapSize                          = 2147483648                             {manageable} {ergonomic}
```

Since version 3.8 https://github.com/gatling/gatling/blob/main/gatling-bundle/src/universal/bin/gatling.sh has changed L30 in commit https://github.com/gatling/gatling/commit/01f11ed7cf38fc53b69b5062688e4e507a057d40 to look like this:

```bash
JAVA_OPTS="${JAVA_OPTS} -Xms32M -Xmx128M"
```

Instead this simple change will make it possible to override the limits for OpenJDK.

```bash
JAVA_OPTS="-Xms32M -Xmx128M ${JAVA_OPTS}"
```

Similar change is required for `gatling.bat`

For other JDKs the mileage may vary, I don't think there's specified behavior for duplicated flags.

**Comment by slandelle** [comment]
The change you're suggesting is wrong. It would only change the JVM option for the Java CLI process, not for the actual Gatling load test one.

Check the [configuration documentation](https://gatling.io/docs/gatling/reference/current/core/configuration/) or run `/gatling.sh -h` and look for the proper option.

**Comment by avbenavides** [comment]
So the right way would be with this
```bash
-erjo, --extra-run-jvm-options "-Option1 -Option2"
                           Defines additional JVM options used when running your code locally (e.g. setting the heap size with "-Xms2G -Xmx4G"). See https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html for available options.
```

Like `gatling.sh -erjo "-Xms2G -Xmx4" ...`?

**Comment by slandelle** [comment]
Exactly :)
