### ISSUE TITLE
Reports: Gatling html report does not show run description nicely

### ISSUE THREAD

**Issue by Kieun** [gatling/gatling#4391]
Hi Gatling team,
First of all, thanks for the great product.

While we adding some simulation related information in the run description to properly indicate what type of simulation parameters are used, the current html report has small room to add such information to the description parts.

It would be great to have more space or room for presenting such description in the run information.
If possible, it would be good to have a way to set a list of information by using key, value pair and the html report draw such information with table or something.

**Comment by slandelle** [comment]
The current reports already lets you pass a long run description.

<img width="240" alt="Screenshot 2023-08-14 at 14 16 29" src="https://github.com/gatling/gatling/assets/849197/b49c8ccd-5d14-468c-a1cb-9f86bca8bc7c">

Then, indeed, it won't let you pass rich formatted text, such as bullet list, new lines, etc.

But that's only something we want to address in Gatling Enterprise.
