### ISSUE TITLE
Gradle Plugin: 3.9.1 and above don't work gradle [7.0, 7.4], work with 7.6

### ISSUE THREAD

**Issue by mirkobeine** [gatling/gatling#4394]
Running gatlingRun with the latest releases > 3.9.0.4 results in:
```
A problem was found with the configuration of task ':load-testing:gatlingLogback' (type 'LogbackConfigTask').
- In plugin 'io.gatling.gradle' type 'io.gatling.gradle.LogbackConfigTask' property 'logger' is missing an input or output annotation.
```
I suppose that this is due to change to **LogbackConfigTask.groovy** introduced with [this commit](https://github.com/gatling/gatling-gradle-plugin/commit/b7ce993e4e954ef4df5031e925c078ba820c250e).

It looks like this is related to a similar problem: #4068 

I have only tested this with gradle 7.4 but suppose that all versions 7.x are affected.

**Comment by slandelle** [comment]
@guilgaly Could you please take a look?

@mirkobeine Thanks for reporting

**Comment by guilgaly** [comment]
@slandelle I can reproduce the issue with the Java demo project using a Gradle version between 7.0 and 7.4 specifically. It seems to work fine with Gradle 7.5+ (or with the latest 6.x version).

**Comment by slandelle** [comment]
Gradle ascendant compatibility is a joke.

**Comment by mirkobeine** [comment]
Thanks for responding so quickly. Great tool, btw!

**Comment by slandelle** [comment]
@mirkobeine Gatling Gradle plugin 3.9.2.1 is out and fixes the compatibility issue with these Gradle versions.

Thanks again for reporting, and thanks for your kind words.
