### ISSUE TITLE
Gatling crashes with SIGBUS on Solaris 11.4 SPARC and JDK 11

### ISSUE THREAD

**Issue by n4al** [gatling/gatling#4402]
Gatling 3.9.0 as well as older versions (tried with: 3.8.4, 3.7.6, 3.6.1, and 3.5.0) crash on Solaris 11.4 SPARC with Oracle JDK 11. The problem seems to be platform specific rather than JDK-specific given that the same problem is observed on Zulu JDK 11, OpenJDK 11, 12, 13, and 14. The exact error message observed is:

```console
$ ./gatling.sh  -rm local
GATLING_HOME is set to .../gatling-charts-highcharts-bundle-3.9.0

 A fatal error has been detected by the Java Runtime Environment:

  SIGBUS (0xa) at pc=0xffffffff64e1f468, pid=1250, tid=203

 JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.17+10) (build 11.0.17+10-LTS-269)
 Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.17+10-LTS-269, mixed mode, tiered, compressed oops, g1 gc, solaris-sparc)
 Problematic frame:
 J 2104 c1 net.openhft.hashing.UnsafeAccess.getLong(Ljava/lang/Object;J)J (9 bytes) @ 0xffffffff64e1f468 [0xffffffff64e1f340+0x0000000000000128]

 Core dump will be written. Default location: .../gatling-charts-highcharts-bundle-3.9.0/core or core.1250

 An error report file with more information is saved as:
 .../gatling-charts-highcharts-bundle-3.9.0/hs_err_pid1250.log

--SNIP--

Compiled method (c1)    4489 2105       3       net.openhft.hashing.CityAndFarmHash_1_1$BigEndian::fetch64 (11 bytes)
 total in heap  [0xffffffff64e20010,0xffffffff64e206d8] = 1736
 relocation     [0xffffffff64e20168,0xffffffff64e201d0] = 104
 main code      [0xffffffff64e201e0,0xffffffff64e204c0] = 736
 stub code      [0xffffffff64e204c0,0xffffffff64e205b0] = 240
 oops           [0xffffffff64e205b0,0xffffffff64e205b8] = 8
 metadata       [0xffffffff64e205b8,0xffffffff64e205f0] = 56
 scopes data    [0xffffffff64e205f0,0xffffffff64e20638] = 72
[hs_err.zip](https://github.com/gatling/gatling/files/11108980/hs_err.zip)

 scopes pcs     [0xffffffff64e20638,0xffffffff64e206b8] = 128
 dependencies   [0xffffffff64e206b8,0xffffffff64e206c0] = 8
 nul chk table  [0xffffffff64e206c0,0xffffffff64e206d8] = 24
Could not load hsdis-sparcv9.so; library not loadable; PrintAssembly is disabled
```

To reproduce:
1. Download JDK11 and unzip JDK11
2. Set JAVA_HOME to JDK11 location
3. Download and unzip Gatling
4. execute ./bin/gatling.sh -rm local
5. observe the error

The error report:
[hs_err.zip](https://github.com/gatling/gatling/files/11108985/hs_err.zip)

In case you would be able and willing to fix this issue but do not have a platform to test it, I can test it for you or provide access to one of my SPARC machines.

**Comment by slandelle** [comment]
As you can see, the crash happens in the `net.openhft.hashing.CityAndFarmHash` class.
This class belongs to [one of the OpenHFT libraries](https://github.com/OpenHFT/Zero-Allocation-Hashing).
Gatling doesn't depend nor ships this library. You've introduced this library yourself.

Unrelated to Gatling, nothing we can do about it.

**Comment by n4al** [comment]
Correction, I did not introduce this library. 

This package is referenced by Zinc compiler: 

https://github.com/sbt/zinc/blob/develop/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/HashUtil.scala

The code referencing it is in zinc-compile-core_2.13-1.8.0.jar and the actual library is in zero-allocation-hashing-0.10.1.jar that is shipped with Gatling 3.9.0

**Comment by slandelle** [comment]
Sorry for the confusion.

Then, sorry but I don’t think we’ll be able to investigate ourselves:
• we don’t support Solaris/SPARC
• this is a dependency of a dependency, not anything in Gatling’s own code.

Here’s what I suggest:
• upgrade the zero-allocation-hashing library to 0.16 which is the latest version 
• if you still experience a crash, open a ticket to this other project directly with the details you provided here: https://github.com/OpenHFT/Zero-Allocation-Hashing

Generally speaking, it’s complicated for open source project to support commercial platforms.

Regards

**Comment by n4al** [comment]
Fair enough. Thank you.
