### ISSUE TITLE
Doc: Core Concepts reference doco - typo "dandling"

### ISSUE THREAD

**Issue by ardc-shorn** [gatling/gatling#4404]
https://github.com/gatling/gatling/blob/92521a7a7152281759e3998a89f439013abdf052/src/docs/content/reference/current/core/concepts/index.md?plain=1#L21

Is "dandling" a typo?

**Comment by Isammoc** [comment]
Contributions welcome (I do think that is a typo too... for "dangling"?)

**Comment by slandelle** [comment]
Indeed, I meant dangling.

**Comment by slandelle** [comment]
Thanks for reporting!
