### ISSUE TITLE
Gradle `logLevel` config not propagating to simulation

### ISSUE THREAD

**Issue by ardc-shorn** [gatling/gatling#4405]
Following doco here: 
https://gatling.io/docs/gatling/reference/current/extensions/gradle_plugin/#logging-management

Setting the `logLevel` in the Gradle config doesn't seem to work, example:
https://github.com/au-research/raido/blob/fb8ec015b6dd834cae483995922a45b56f0bf2be/api-svc/load-test/build.gradle#L84

I have to hardcode the log level in the config, as per:
https://github.com/au-research/raido/blob/fb8ec015b6dd834cae483995922a45b56f0bf2be/api-svc/load-test/src/gatling/java/logback.xml#L12

Expected functionality: User should be able to set define the `logLevel` on a per `GatlingRunTask` basis.

Using Gatling Gradle plugin: `3.9.3`

Logs:
```
05:34:19,717 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.6
05:34:19,740 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
05:34:19,744 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/ardc/raido-v2/api-svc/load-test/build/resources/gatling/logback.xml]
05:34:19,745 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@7c469c48 - Resource [logback.xml] occurs multiple times on the classpath.
05:34:19,745 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@7c469c48 - Resource [logback.xml] occurs at [jar:file:/C:/ardc/raido-v2/api-svc/spring/build/libs/spring-raido-v-1.1-130-g67e570e-dirty.jar!/logback.xml]
05:34:19,745 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@7c469c48 - Resource [logback.xml] occurs at [file:/C:/ardc/raido-v2/api-svc/load-test/build/resources/gatling/logback.xml]
05:34:19,844 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
05:34:19,844 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
05:34:19,851 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
05:34:19,878 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to DEBUG
05:34:19,878 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
05:34:19,879 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@12e61fe6 - End of configuration.
05:34:19,880 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7ee955a8 - Registering current configuration as safe fallback point
```

Note that despited the warning about multiple log config files, the load-test config is what is being used (as confirmed by changing the log pattern and that hardoding the root appender `level` works).

When I look for usages of the `GatlingPluginExtension.logLevel` in IDEA, it thinks the value is only ever read from tests? 
That could just be that IDEA can't follow the groovy code though.

**Comment by Isammoc** [comment]
Ok, I dug a little bit in the code and here are my findings:

 * `logLevel` (and `logHttp`) are used during the `gatlingLogback` task. (in `generateLogbackConfig` method that is annotated with `@TaskAction`)
 * In `GatlingUnitSpec` we do [test if the `gatlingRun` task depends on this `gatlingLogback` task](https://github.com/gatling/gatling-gradle-plugin/blob/main/src/test/groovy/unit/GatlingPluginTest.groovy#L97)
 * we [do register the dependency](https://github.com/gatling/gatling-gradle-plugin/blob/main/src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy#L96)

But!

The `gatlingLogback` is designed not to override any `logback.xml` existing file.
We do check if there is any `logback.xml` configuration file in the scope
And if any, we don't write another `logback.xml` with value provided in gatling scope.

The solution is either:
 * delete your `logback.xml` in any resource set in gatling scope
 * change the level in your `logback.xml`

**Comment by slandelle** [comment]
@Isammoc Let's update the documentation to make the behavior clear. Agree?

**Comment by Isammoc** [comment]
@slandelle Already documented

> The default Gatling console log level if no logback.xml present in the configuration folder

Source: [Gradle Plugin - Plugin configuration](https://gatling.io/docs/gatling/reference/current/extensions/gradle_plugin/#plugin-configuration) (on `logLevel` line)

And we do have a warning:
```console
$ ./gradlew gatlingRun

> Task :gatlingLogback
Existing logback.xml will override logLevel and logHttp from gatling configuration in build.gradle.
```
