### ISSUE TITLE
Include service time response (from http header) in gatling reports.

### ISSUE THREAD

**Issue by lurbanski-equinix** [gatling/gatling#4406]
Hi gatling guys!
There is [x-envoy-upstream-service-time header](https://webtechsurvey.com/response-header/x-envoy-upstream-service-time). It shows real service response time without network latency.
I would like to have the server time included in gatling reports. The header name can differ depending on tool and should configurable.
1. Is it feasible to add the functionality?
2. If not. Is there a way to write a workaround to add this to gatling reports?

Regards

**Comment by slandelle** [comment]
Hi,

I'm afraid that's not possible at the moment.

Actually, we're considering introducing an API for reporting custom metrics (counts and durations) but this will be an Enterprise only feature.

I can't think of a workaround.

Regards

PS: questions are best asked on our community forum: https://community.gatling.io/

**Comment by lurbanski-equinix** [comment]
Thank you for your response. I will use forum next time.
Happy Easter!
