### ISSUE TITLE
Recorder: Export to HAR file unsuccessfull: Error while processing HAR file: c.f.j.d.JsonMappingException: String length exceeds maximum length

### ISSUE THREAD

**Issue by ashu38** [gatling/gatling#4407]
Step to reproduce :

1- launch the recorder ./recorder.sh
2- select HAR
3- upload HAR file
4- select Java8 (or Java17, Java11, Scala, Kotlin)
5- Click on Start and Observe

Error displayed
<img width="1432" alt="Screenshot 2023-04-12 at 11 04 38 AM" src="https://user-images.githubusercontent.com/31126454/231687627-0f0786b4-4b3b-458e-a3dc-c6c2cc01d22f.png">

Testing on gatling sample 3.9.3

HAR File : 
[CL_NoFilter_KnxMS.har.txt](https://github.com/gatling/gatling/files/11219462/CL_NoFilter_KnxMS.har.txt)

**Comment by slandelle** [comment]
caused by https://github.com/FasterXML/jackson-core/issues/863

It seems the only way to lift this limit is to pass a tuned `JsonFactory` to the `ObjectMapper` constructor.

**Comment by slandelle** [comment]
@ashu38 Thanks for reporting. This one is a pretty low hanging fruit. Are you interested in contributing?

**Comment by ashu38** [comment]
No worries. This is my first time reporting an issue. Can you let me know how can I contribute?

**Comment by slandelle** [comment]
> Can you let me know how can I contribute?

I've indicated above the class that needs to be modified and how.
You have to fork this repository, code the change, make sure it compiles (you need to install sbt and run sbt compile), push in your fork and then send a Pull Request.

Cheers

**Comment by pksax** [comment]
I am trying to use gatling for the first time. Encountered the issue mentioned in this thread. When can we expect this to be resolved or is there an older version of Gatling that can be used and where we will not see this issue. Inputs greatly appreciated

**Comment by slandelle** [comment]
Possibilities:
* contribute as explained above
* revert to Gatling 3.9.2
* downgrade Jackson to 1.14 (note: this change is a vulnerability fix)
* exclude humongous (> 5MB once uncompressed) responses from your HAR recording. In @ashu38 , the issue is with a Javascript library.

> When can we expect this to be resolved

Possibilities:
* when the release backlog for 3.9.4 or 3.10.0 is large enough
* when this issue becomes a major blocker for a large number of free users
* when this issue become a pain for paying customers

**Comment by UO283216** [comment]
I am also starting to use Gatling for the first time to test a React application [(Lomap)](https://github.com/Arquisoft/lomap_en2a). The problem i am encountering is that the google maps api and the solid pod providers accesses of our application are blocked by the proxy as it can be seen on the image of this [issue](https://github.com/Arquisoft/faq/issues/46). My approach was then to use the HAR file but encontered the same problem being discussed here. 
May you give me some clues on how to solve it or point to a reference to download the mentioned Gatling 3.9.2 version that fixes this bug.
