### ISSUE TITLE
Reports: milliseconds to Graphs & Simulation Duration

### ISSUE THREAD

**Issue by JJRdec** [gatling/gatling#4416]
For feature requests, please:
  * Please could you add milliseconds to Graphs (right now we can only see times to the second)
  * Could you also do this for duration of simulation?

![image](https://user-images.githubusercontent.com/94698858/236416104-0563ffca-8ba0-4296-a9cd-42672431e309.png)

![image](https://user-images.githubusercontent.com/94698858/236416659-1a9c52de-2561-4a98-aefa-788570d295d7.png)

**Comment by slandelle** [comment]
I don't think such a short burst makes much sense in the context of Gatling as the JVM's Just-In-Time (JIT) compiler hasn't kicked in yet (and a similar warm up is also probably necessary on your application's side too).

**Comment by JJRdec** [comment]
@slandelle fair point, I'm closing this then!
