### ISSUE TITLE
Core: Adapt console output length based on terminal width

### ISSUE THREAD

**Issue by clbuttic** [gatling/gatling#4418]
The [ConsoleSummary's OutputLength](https://github.com/gatling/gatling/blob/main/gatling-core/src/main/scala/io/gatling/core/stats/writer/ConsoleSummary.scala#L34) is hard coded to a width of 80. That leave a max length for the action (and errors) to be truncated to 56 characters making naming of what constitutes an action in the summary somewhat difficult. 

Plus, with wider monitors and running gatling scenarios from the command line, that's a lot of wasted real estate.

Please make this a configurable option.

**Comment by slandelle** [comment]
Maybe something based on [jline](https://github.com/jline/jline3)?

Are you interested in contributing?

**Comment by clbuttic** [comment]
@slandelle Autodetecting the terminal is most definitely a better way to handle terminal widths than a simple config option.. Sure, I'm happy to contribute a PR. I'll familiarize myself with your contributor guidelines and see what I can come up with.

**Comment by slandelle** [comment]
@clbuttic gentle ping :)

**Comment by slandelle** [comment]
Closing for now due to lack of activity and interest.
