### ISSUE TITLE
contentType not working for RawFileBodyPart inside bodyPart

### ISSUE THREAD

**Issue by rawl05** [gatling/gatling#4430]
I'm trying to send a .dcm file to an API which accepts `multipart/related` and `multipart/form-data` using bodyPart(RawFileBodyPart) with contentType as `application/dicom` , snippet attached below. But when I check this in my API which is receiving the request it shows MediaType for the RawFileBodyPart as `application/octet-stream`
```
dicomScenario = scenario("Upload DICOM")
            .exec(
                http("/dicomweb/studies")
                    .post("/dicomweb/studies")
                    .header(HttpHeaderNames.CONTENT_TYPE, "multipart/related")
                    .header(HttpHeaderNames.ACCEPT, "*/*")
                    .header(HttpHeaderNames.CONNECTION, HttpHeaderValues.KEEP_ALIVE.toString())
                    .header(HttpHeaderNames.ACCEPT_ENCODING, "gzip,deflate,br")
                    .header(HttpHeaderNames.AUTHORIZATION, "Bearer <token>")
//                        .bodyParts(getFiles())
                    .bodyPart(RawFileBodyPart("dicom/example.dcm")
                        .contentType("application/dicom")
//                        .transferEncoding("binary")
//                        .charset("utf-8")
                    )
                    .check(status().is(200))
//                    .asMultipartForm()
            );
    }
```
Its **NOT** working for multipart/related as well as multipart/form-data.

API Function: 
![image](https://github.com/gatling/gatling/assets/37844947/522ea5cc-2a8a-45bc-ae27-0ebb622389f2)

MediaType logged in API:
![image](https://github.com/gatling/gatling/assets/37844947/c4f8c3fb-eec0-4ee7-a81e-3c9193757b75)

Its working through PostMan though:
![image](https://github.com/gatling/gatling/assets/37844947/d718e8d4-e431-47d7-aecd-775a78ca311d)

I'm using gatling version 3.9.5
gatling maven plugin: 4.3.5
maven compiler plugin: 3.10.1

**Comment by slandelle** [comment]
@rawl05 Not an issue?
