### ISSUE TITLE
Custom gatling.conf ignored with gatling-maven-plugin 4.3.5

### ISSUE THREAD

**Issue by RJKeane2000** [gatling/gatling#4431]
I have a custom gatling.conf file with core outputDirectoryBaseName set to "performance" and charting indicators set.  Upgrading my pom file from gatling-maven-plugin version 4.3.4 to 4.3.5 with no other changes, results in the report folder name changing from "performance" + timestamp to the scala class + timestamp.  The charting indicators  values are not reflected in the report either.

It appears that the gatling.conf file is not picked up after upgrading to 4.3.5.

**Comment by slandelle** [comment]
Can't reproduce sorry.

What I did:
* run on MacOS
* clone https://github.com/gatling/gatling-maven-plugin-demo-java and https://github.com/gatling/gatling-maven-plugin-demo-scala
* change `outputDirectoryBaseName = "performance"` and `higherBound = 1000` in `gatling.conf` (uncommented, removed the `#`)
* run `mvn gatling:test`
* observe that `gatling.conf` is properly copied in `target/test-classes`, reports are generated in `target/performance-xxx` and indicators are changed as expected.

<img width="292" alt="Screenshot 2023-06-04 at 06 18 57" src="https://github.com/gatling/gatling/assets/849197/839cc784-a045-4139-8a74-6cc20292831d">

<img width="505" alt="Screenshot 2023-06-04 at 06 20 57" src="https://github.com/gatling/gatling/assets/849197/acab74d5-779c-4b22-8de4-1d43204067ad">

Please provide a reproducer.

**Comment by RJKeane2000** [comment]
@slandelle Thank you for such a quick response and the sample project. It took me a bit to recreate the situation using https://github.com/gatling/gatling-maven-plugin-demo-scala but I was finally able to do it.

In gatling.conf, uncomment outputDirectoryBaseName and set it to "test".

In the pom.xml in the build section, replace `<testSourceDirectory>src/test/scala</testSourceDirectory>` with 
```xml
<testResources>
  <testResource>
    <directory>src/test/scala</directory>
  </testResource>
</testResources>
```

You should see that the test runs successfully with version 4.3.4 of the gatling-maven-plugin and the output folder is named "test" with a timestamp.

If you change the version to 4.3.5 and re-run the test, again the test will run successfully but the output folder is named "computerdatabasesimulation" with a timestamp. 

I found this [document](https://www.codetab.org/tutorial/apache-maven/plugins/manage-maven-directories/) talking about "testSourceDirectory" and "testResources". 

We use "testResources" so we can point to where the scala files are but it also allows us to exclude java files in the same directory. Our "testResources" looks like this:

```xml
<testResources>
  <testResource>
    <directory>src/test/java</directory>
    <excludes>
      <exclude>**/*.java</exclude>
    </excludes>
  </testResource>
</testResources>
```

I think I can reorg the files to isolate the scala files and point the testSourceDirectory to the directory with the scala file. 

Do you have any idea why 4.3.5 is behaving different when using "testResources"?

**Comment by slandelle** [comment]
Your setup is wrong. `testResources` is for remapping `src/test/resources`, not `src/test/java`. If you're not declaring scala as sources, you're breaking scala compilation.

> Do you have any idea why 4.3.5 is behaving different when using "testResources"? 

You could check the git history yourself: https://github.com/gatling/gatling-maven-plugin/commits/main
The [change](https://github.com/gatling/gatling-maven-plugin/commit/29a4fe3f04d890c12b9b03ab73ecef450bf73f7e) is here and is correct.
