### ISSUE TITLE
Gatling report skips points on the graphic

### ISSUE THREAD

**Issue by jigarkhwar** [gatling/gatling#4444]
Gatling 3.9.5 skips some points on test start and it might be interpreted incorrectly

I don't see 330ms point but there is value in the aggregation table
<img width="1010" alt="image" src="https://github.com/gatling/gatling/assets/11795372/2d4f7ad8-b196-434f-89c3-6fe7d1a4745c">

<img width="469" alt="image" src="https://github.com/gatling/gatling/assets/11795372/8f4d2d30-6dea-4661-bc5a-28530300155a">

[reports.zip](https://github.com/gatling/gatling/files/12162549/reports.zip)

**Comment by slandelle** [comment]
Hi,

Sorry but we can't fix this as this is how the HighchartsJS library behaves and we don't have any plan to replace it any time soon as it would be very expensive.

Closing as "won't fix".

Note: Gatling Enterprise directly uses D3.js and I'm pretty sure there's no issue there.
