### ISSUE TITLE
Recorder: Unchecking the "Enable Filters" checkbox has no effect

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4448]
Gatling: 3.9.5 (gatling-charts-highcharts-bundle-3.9.5)
OS: Windows 10 Pro
JDK: jdk-17.0.4

When try to use `HAR Converter` and have configured it as below (Added to section AllowList any value e.g. AllowList):
![image](https://github.com/gatling/gatling/assets/30750006/397273e3-2ce4-4c63-b72a-7ae47c994e8e)

and "unticked" Enable Filters recorder does not disable filters and show error after `Start !`:
![image](https://github.com/gatling/gatling/assets/30750006/b14175d6-8a8a-4c05-84ee-56f685e4192b)

**Comment by slandelle** [comment]
Thanks for reporting @gemiusz
