### ISSUE TITLE
HTTP: contentType and contentId are swapped in RawFileBodyPart

### ISSUE THREAD

**Issue by gebhardt** [gatling/gatling#4450]
I'm using Gatling version 3.9.5

If I create a multi-part message for an SOAP MTOM-Request like this:

```
    http("SOAP MTOM Request")
        .post("endpoint")
        .header(HttpHeaderNames.CONTENT_TYPE, "multipart/related; type=\"application/xop+xml\"")
        .bodyParts(
            ElFileBodyPart("SOAP-Template.xml") 
                .contentType("application/xop+xml; type=\"text/xml\"")  // here everything works as expected
                .contentId("SOAP-Msg"), 
            RawFileBodyPart("attachment.txt") 
                 .contentType("application/octet-stream")  // --> this becomes the contentId in the sent http messge part
                 .contentId("attachment"))     // --> this becomes the contentType
            .check(status().is(200)));
```
the headers of the `RawFileBodyPart` uses the `contentId(..)` as `contentType` and vice versa. However, the `ElFileBodyPart` works correctly, i.e. the `contentType(...)` sets really the `contentType` header.

Unfortunately, I wasn't able to track down, where the `contentType` and `contentId` get switched when creating the actual http message.

**Comment by slandelle** [comment]
Thanks for reporting!

**Comment by gebhardt** [comment]
Thanks for fixing!
