### ISSUE TITLE
Core: ChainableAction does not catch exceptions in dispatched execution

### ISSUE THREAD

**Issue by phiSgr** [gatling/gatling#4453]
I believe 4f2be2cb9c6759820a66af8c7292039986e50b98 reverted the fix for #4008.

Let me know if you want me to add a test for it.

A clear "will not fix" is also fine.

**Comment by slandelle** [comment]
Hi @phiSgr ,

For now, I'm inclined for "won't fix". The example you provide in #4008 is actually incorrect: your `Action` has a `next` to propagate in case of an error, so it should be a `ChainableAction` and implement `execute` instead of `!`.

Do you have another example that would apply?

**Comment by phiSgr** [comment]
The custom `wrongDispatcher` action does not fail. It does propagate to the `next` action.

What dropped the user is `SessionHook`.

**Comment by phiSgr** [comment]
Edited the original issue to and used `ChainableAction`. It fails with the same behaviour.

**Comment by slandelle** [comment]
You're right. Reverting.

**Comment by slandelle** [comment]
Thanks!
