### ISSUE TITLE
Bundle: Don't recognise Kotlin (.kt) simulations

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4458]
Gatling: 3.9.5 (gatling-charts-highcharts-bundle-3.9.5)
OS: Windows 10 Pro
JDK: jdk-17.0.4

Bundle version don't recognise Kotlin (.kt) simulations:
![image](https://github.com/gatling/gatling/assets/30750006/3ad86f22-7b09-4d3e-bbdb-19f8e490b618)

**Comment by gemiusz** [comment]
I found information about that in documentation :-/

**Comment by slandelle** [comment]
Indeed, and it most likely never will. The bundle only supports Java and Scala.

From what we've observed, almost all the Kotlin users use gradle.

**Comment by gemiusz** [comment]
Ok, sorry for the confusion.
