### ISSUE TITLE
Using LogFileReader from Gatling in 3rd party code

### ISSUE THREAD

**Issue by perlun** [gatling/gatling#4459]
Hi,

Thanks for a nice tool. We have previously been using version 3.3.1 which has worked well for us. Because of updates related to the Gatling plugin (the old community effort didn't play well with more recent JDK versions) we recently upgraded to 3.4.0. Yes, I agree we are a bit slow. :slightly_smiling_face: 

Either way, this caused compilation issues:

```
$ gw runLogParser --args "/path/to/ios_2021_04/20.0/ name_of_scenario-20230906150600818"

> Task :compileJava FAILED
/path/to/src/main/java/my/app/logparser/LogParserApplication.java:159: error: resultsHolder() has private access in io.gatling.charts.stats.LogFileReader
                        numberOfRequestInResponseTimeRange( logFileReader.resultsHolder(), requestName, total.count() )
                                                                         ^
1 error

FAILURE: Build failed with an exception.
```

I suspect this is because of the https://github.com/gatling/gatling/commit/e2b80deac583f190e9e507981c3b16857097f19c change in the Gatling code base.

I perfectly understand why Gatling doesn't want 3rd party code to be dependent on its internals, so let me explain what we are doing a bit more in depth.

### Our use case

We have built a fairly advanced architecture on top of Gatling which takes care of:

1. Running a few Gatling simulations with predefined "number of users/s" from a `.json` config file.
2. Parsing the result, checking if "things did go well" or if we have passed the threshold of "reasonable performance" (as defined by our tool) for the particular simulation.
3. Re-running the Gatling simulation with increasing number of users/s, until performance starts to degrade to the point of "threshold passed".
4. Once all simulations are complete, generate JSON files + an HTML page with the overall results for all simulations, and publish a link to this on one of our Slack channels.

All of this works well, but it's perhaps the "check if things did go well" part that is a bit intricate. The way we do it by an approach that looks roughly like this (slightly modified from our production code - `SimulationResultForRequest`, `GatlingSimulationResult` and `NumberOfRequestsInResponseTimeRanges` are plain DTO classes in our Java-based project):

```java
    private LogParserApplication parseSimulationLog() {
        LogFileReader logFileReader = new LogFileReader( simulationId, gatlingConfiguration );

        SimulationResultForRequest globalSimulationResult = getGlobalSimulationResult( logFileReader );
        long simulationStarted = logFileReader.runStart();
        long simulationEnded = logFileReader.runEnd();
        GatlingSimulationResult simulationResult = new GatlingSimulationResult( globalSimulationResult, simulationStarted, simulationEnded );

        // ...
    }

    private SimulationResultForRequest getGlobalSimulationResult( LogFileReader logFileReader ) {
        return getSimulationResult( logFileReader, none() );
    }

    private SimulationResultForRequest getSimulationResult( LogFileReader logFileReader, Option<String> requestName ) {
        //
        // This method is strongly inspired by computeRequestStats in StatsReportGenerator.scala, in
        // the Gatling source code.
        //

        GeneralStats total = logFileReader.requestGeneralStats( requestName, none(), none() );
        GeneralStats ok = logFileReader.requestGeneralStats( requestName, none(), Some.apply( Status.apply( "OK" ) ) );
        GeneralStats errors = logFileReader.requestGeneralStats( requestName, none(), Some.apply( Status.apply( "KO" ) ) );

        ResponseTimePercentileStats percentile1Stats = getResponseTimePercentileStats( gatlingConfiguration.charting().indicators().percentile1(), total, ok, errors );
        ResponseTimePercentileStats percentile2Stats = getResponseTimePercentileStats( gatlingConfiguration.charting().indicators().percentile2(), total, ok, errors );
        ResponseTimePercentileStats percentile3Stats = getResponseTimePercentileStats( gatlingConfiguration.charting().indicators().percentile3(), total, ok, errors );
        ResponseTimePercentileStats percentile4Stats = getResponseTimePercentileStats( gatlingConfiguration.charting().indicators().percentile4(), total, ok, errors );

        SimulationResultBuilder simulationResultBuilder = new SimulationResultBuilder()
                .requestName( requestName.getOrElse( () -> null ) )
                .requestCounts( total.count(), ok.count(), errors.count() )
                .minResponseTimes( total.min(), ok.min(), errors.min() )
                .maxResponseTimes( total.max(), ok.max(), errors.max() )
                .meanResponseTimes( total.mean(), ok.mean(), errors.mean() )
                .standardDeviations( total.stdDev(), ok.stdDev(), errors.stdDev() )
                .meanNumberOfRequestPerSeconds( total.meanRequestsPerSec(), ok.meanRequestsPerSec(), errors.meanRequestsPerSec() )
                .responseTimePercentiles(
                        percentile1Stats,
                        percentile2Stats,
                        percentile3Stats,
                        percentile4Stats
                )
                .numberOfRequestsInResponseTimeRanges(
                        numberOfRequestInResponseTimeRange( logFileReader.resultsHolder(), requestName, total.count() )
                );

        return simulationResultBuilder.build();
    }

    // Note: this is perhaps the method that is most dependent on ResultsHolder, since it calls
    // into this class for getting the response time range buffers
    private NumberOfRequestsInResponseTimeRanges numberOfRequestInResponseTimeRange( ResultsHolder resultsHolder, Option<String> requestName, long totalCount ) {
        ResponseTimeRangeBuffer counts = resultsHolder.getResponseTimeRangeBuffers( requestName, none(), gatlingConfiguration );
        int lowerBound = gatlingConfiguration.charting().indicators().lowerBound();
        int higherBound = gatlingConfiguration.charting().indicators().higherBound();

        return new NumberOfRequestsInResponseTimeRanges(
                null, lowerBound, counts.low(),
                lowerBound, higherBound, counts.middle(),
                higherBound, null, counts.high(),
                counts.ko(), totalCount
        );
    }
```

### Conclusions

Why we've done things the way we've done is fairly rational: reimplementing the parsing of `simulation.log` files generated by Gatling makes little sense, when Gatling already has this code in place. Hence, we tried to reuse as much as possible of this logic and just handle the "write result data to our custom JSON format" in our application.

### Potential suggestions

1. Let Gatling provide a public, well-defined API for this (perhaps it already exists? feel free to point me in the right direction)
2. Include our code in the Gatling code base, essentially writing the `simulation.json` files that we currently create as a post-processing step directly from Gatling instead.

I think option 2 is doable (but I'd have to check this internally first) if we want to go this route. Our current implementation is Java-based though and I don't really have much Scala experience... so perhaps adding the Java code as-is would be problematic for the Gatling maintainers. :thinking:

Please let me know your thoughts, and once again thanks for a nice tool that's been rather helpful in continuously measuring the performance of our application. :+1:

**Comment by slandelle** [comment]
Hello,
Thank you for your suggestions.
What you are asking for are advanced features for our Enterprise customers, eg our REST API for querying the test stats.
Please get in touch with our sales teams to know more about it.
We’d be happy to do a demo for you.
Best regards
