### ISSUE TITLE
Dump response body in a log file when check fails

### ISSUE THREAD

**Issue by fabienbancharel** [gatling/gatling#447]
Hi,
I am testing 1.1.0, and I love it !
In a scenario, I start to add checks, to verify that responses are what is expected.
On the disconnect request on our application, I added this check :
.check(regex("Error").notExists, regex("Your user session is terminated").exists)
but it gives me 60% of failed request, and I can hardly diagnose them.
What I can found in simulation.log is just : KO Check 'exists' failed, found None.

As I can not see what is wrong for these 60% failures, is there a way to have response bodies dump when check fails ? (Changing a log level for exemple).

Else it would be a feature request :
Have a checkFailed.log with response bodies for failed checks. Maybe with an option to log only the first failure for a given request, else it could lead to a huge log file, and impact performance of gatling.

Thanks for your help.
Fabien.

**Comment by dkaplan-pivotal** [comment]
This is now done with this statement:

```
<logger name="io.gatling.http.ahc" level="DEBUG" />
```

**Comment by gaalandr** [comment]
Hi,

is it possible to log request and response only on errors?

This enables log for all requests.
`<logger name="io.gatling.http.ahc" level="DEBUG" />`


Thanks

**Comment by ndtreviv** [comment]
This is broken. It will log 200 response codes as well.

**Comment by slandelle** [comment]
@ndtreviv can you reproduce with 2.2.4-SNAPSHOT?

**Comment by hdev59** [comment]
I reproduced this issue with final 2.2.4 :

<<<<<<<<<<<<<<<<<<<<<<<<<
11:49:11.533 [DEBUG] i.g.h.a.ResponseProcessor -
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Login Redirect 1: OK
=========================


=========================
HTTP response:
status=
200 OK
headers=
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff

**Comment by sistum-ELS** [comment]
Add this line to your logback file. It prints the response details only for the failed requests :
<logger name="io.gatling.http.engine.response" level="DEBUG" />
Example:

...
=========================
HTTP response:
status=
404  Not found
headers= 
Content-Type: application/json; charset=UTF-8
Content-Length: 181


<<<<<<<<<<<<<<<<<<<<<<<<<
14:06:11.954 [DEBUG] i.g.h.a.ResponseProcessor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Index Status: not found
=========================
...
