### ISSUE TITLE
HTTP: WebSocket cancelTimout clears message buffer before to log

### ISSUE THREAD

**Issue by Amerousful** [gatling/gatling#4470]
Hi!
I found a problem: `WsFsm.cancelTimeout()` calls before `fsm.wsLogger.logCheck` and there will be empty received messages in a log.

Is it a good idea to store buffer messages into a variable before `cancelTimeout()`? Something like that:
```scala
    val messagesFromBuffer = fsm.fetchBuffer()
    cancelTimeout()
    fsm.wsLogger.logCheck(..., ..., ..., messagesFromBuffer, ...)
```
Or it would be better to extract the 'clear' functionality into a separate method and call it in the appropriate place.

***

<img width="1512" alt="image 142" src="https://github.com/gatling/gatling/assets/22199881/7b6c631e-f9bd-4bd0-a2df-d1e8f4cf2fbb">
<img width="1512" alt="image 141" src="https://github.com/gatling/gatling/assets/22199881/d099349a-316c-482b-bce8-8e9a9b182b70">

**Comment by slandelle** [comment]
Nice catch, thanks!

**Comment by Amerousful** [comment]
Thank you too! I noticed that you made other refactoring. Seems cool, it's elaborated changes!
