### ISSUE TITLE
HTTP: Make WsLogger use the same slf4j logger as HTTP (io.gatling.http.engine.response)

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4471]
Way too cumbersome to have to enable and sync 2 different loggers.

**Comment by slandelle** [comment]
@Amerousful FYI

**Comment by Amerousful** [comment]
Roger that

**Comment by Amerousful** [comment]
@slandelle Hi. You know, now I don't think this change was a good idea. In my opinion, it's better to have the option to filter your loggers, meaning you can enable or disable them as needed. 

I comprehend that WebSocket operates on the HTTP protocol, yet it is a distinct protocol.
Also, I found as an example - SSE (Server Sent Event) which has a separated logger.
```xml
<logger name="io.gatling.http.action.sse.fsm" level="DEBUG" />
```
https://gatling.io/docs/gatling/reference/current/http/sse/#debugging

Could I ask you to reconsider this change?

**Comment by Amerousful** [comment]
@slandelle Hi again! Would you be able to review the message above?
