### ISSUE TITLE
Core: String length (5042668) exceeds the maximum length (5000000) gatling test

### ISSUE THREAD

**Issue by drrc1709** [gatling/gatling#4472]
Hello everyone, I have the following situation:

Within my Gatling workflow, a .zip file is encrypted in base64, which generates a very long string of characters that is generating the following exception  Hello everyone, I have the following situation:

Within my Gatling workflow, a .zip file is encrypted in base64, which generates a very long string of characters that is generating the following exception
```
Jackson failed to parse into a valid AST: c.f.j.c.e.StreamConstraintsException: String length (5042668) exceeds the maximum length (5000000)
```
![image](https://github.com/gatling/gatling/assets/50565417/603ebad6-1702-4a6a-a209-b7bf0f2e257a)

 In my project I only have the gatling highcharts dependency, I would like to know if you have any way to solve it, I look forward to your help, thank you

**Comment by slandelle** [comment]
@drrc1709 You're hitting the new security limits in Jackson. We should lift them. Then, please note that the memory usage of your payload is far from ideal.

**Comment by drrc1709** [comment]
Hi @slandelle, I see that you already made the change, but while it merges and is deployed, is there a way to increase this limit in my local project, either with scala or java

**Comment by slandelle** [comment]
The only workaround is to downgrade the Jackson version.
