### ISSUE TITLE
HTTP: Method that record log on a specific API call only

### ISSUE THREAD

**Issue by nptri** [gatling/gatling#4476]
Request feature:
A method that only log on a specific API call
I have a use case as below:
I got a workflow contains 30 APIs call, I have ensured that 28 of them are working fine, but the other 2 are the one that I need to view the call body and response body. If I set things in logback.xml to be TRACE LEVEL, it will show all other 28 APIs which is a lot of information to scroll to find the exact API I need, or setting log DEBUG for fail requests is not relevant since the API can still call successfully.

**Comment by nptri** [comment]
hi @slandelle , could you share me some insights on this feature ?

**Comment by Isammoc** [comment]
Hi @nptri,
Did you tried to change the log level programmatically during the execution?
I didn't try it myself, but if you set the level to TRACE/DEBUG right before (in an exec call, I guess). You should workaround your issue. But I'm afraid that this is not something that will be done in gatling itself.

**Comment by nptri** [comment]
hi @Isammoc , currently I am following the println method on Gatling's doc as a workaround, but I believe it would be more convenience if we can set in logback.xml (or any method there), and I'm unsure if the appender is applicable in my situation though.

**Comment by slandelle** [comment]
The next release will truncate printed bodies to 500,000 bytes, see https://github.com/gatling/gatling/commit/0d68559afeed5ceedfb4bca390d009c202134a7f

I think that should be enough. I don't think we should add a DSL method related to trace logging.
