### ISSUE TITLE
Invalid format of SSE Json body

### ISSUE THREAD

**Issue by johkin** [gatling/gatling#4484]
I'm trying to verify the behavior of our SSE implementation, and since the ServerSentEvent's are converted to a Json document, I thought it would be easiest to verify message content with a Json-path expression.
This does unfortunately fail, and the Json document seems to have an invalid format?

From the logs:
jsonPath($.data.length()).find.is(0) preparation crashed: Jackson failed to parse into a valid AST: c.f.j.c.JsonParseException: Unrecognized token 'Some': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"{"id":"2023-12-04T22:20:49.1000325Z","data":"[]","retry":Some(15000)}"; line: 1, column: 62]

The retry field should be a integer with the value 15000, but for some reason the "Some" wrapper is included event though the code reads:

this.retry().foreach((value) -> {
            return $anonfun$asJsonString$4(this, sb, BoxesRunTime.unboxToInt(value));
        });

I'm a Scala newbie, but I would expect the wrapper to be unboxed if the method "asJsonString" is actually used?

**Comment by slandelle** [comment]
@johkin Gentle ping.

**Comment by slandelle** [comment]
Idle for 2 weeks and lack of details.
Closing for now, will reopen if someone can provide more details.
