### ISSUE TITLE
Add support for customising StatsProcessor

### ISSUE THREAD

**Issue by jonathannaguin** [gatling/gatling#4485]
In case of a HTTP failure, the StatsProcessor will include the Session and the HTTP request in the logs (from https://github.com/gatling/gatling/blob/394d7ef88de8369fb5564294385d862aefe1e4b0/gatling-http/src/main/scala/io/gatling/http/engine/response/StatsProcessor.scala#L58-L75)

```
 loggingStringBuilderPool
        .get()
        .append(Eol)
        .appendWithEol(">>>>>>>>>>>>>>>>>>>>>>>>>>")
        .appendWithEol("Request:")
        .appendWithEol(s"$fullRequestName: $status ${errorMessage.getOrElse("")}")
        .appendWithEol("=========================")
        .appendWithEol("Session:")
        .append(session)
        .append(Eol)
        .appendWithEol("=========================")
        .appendWithEol("HTTP request:")
        .appendRequest(result.request)
        .appendWithEol("=========================")
        .appendWithEol("HTTP response:")
        .appendResponse(result)
        .append("<<<<<<<<<<<<<<<<<<<<<<<<<")
        .toString
```

If the request body is large, this will flood the logs of the machine that runs the load test.
At the moment, we can only turn off logging to avoid large log files.
Ideally, we would want some control over which information is logged (for example, only the response).

**Comment by slandelle** [comment]
> At the moment, we can only turn off logging to avoid large log files.

Already solved as of 0d68559afeed5ceedfb4bca390d009c202134a7f. Not released yet.

> Ideally, we would want some control over which information is logged (for example, only the response).

I don't think that will happen. We're trying to keep things generic.
