### ISSUE TITLE
Core: null check for Session attributes

### ISSUE THREAD

**Issue by TomH-FR** [gatling/gatling#4487]
Gatling version: **3.9.5**

Use-case is using scrollId to get all pages of search results from the server. Server returns `null` in scrollId attribute (in JSON) once the last page is reached.

Example:
```scala
class TestNull extends Simulation {

  val scn: ScenarioBuilder = scenario("myScenario")
    .exec { session =>
      val newSession = session.set("scrollId", null)
      System.out.println("scrollId value is null! " + newSession("scrollId").validate[String])  // only .validate produces somewhat reasonable output
      newSession
    }
    .doIf(session => session.contains("scrollId")
      && session("scrollId") != null // does not work - the returned value of session("scrollId") is a complete Session (that seems as bug to me as well) and so it is not null
      && session("scrollId").asOption[String].isDefined  // error (tested also separately)
      && session("scrollId").asOption[String].getOrElse(None) != None  // error (tested also separately)
    ) {
      exec { session =>
        System.out.println("scrollId value is not null!")
        session
      }
    }

  setUp(scn.inject(atOnceUsers(1)))
}
```
* "error" mentioned above: `Condition evaluation crashed with message '[ERROR] i.g.c.action.If - 'if-2' failed to execute: j.l.ClassCastException: Attribute scrollId's value is null`. Casting to String, needed before any comparison operation, fails on null value.
* 
In session there is:
```
... scrollId -> null, ...
```
I was also thinking of using `transformResponse` to avoid having `null` from response in Session variable, but I wasn't lucky enough on handling `null` there.

I have also tried something like `jsonPath("$.scrollId").notNull.optional.saveAs("scrollId"))`, but that is not possible as well.

**Comment by slandelle** [comment]
Hello,

Sorry but this is a bug tracker, not a place for question or asking for assistance.
Please use our [community forum](https://community.gatling.io/).

**Comment by TomH-FR** [comment]
Ok, so apparently only possible way, that feels bit hacky is
```
.
.
   .doIf(session => session.attributes.getOrElse("pageCookie", null) != null)
.
.
```
I hope it helps someone.
source: https://performance-related.blogspot.com/2019/01/gatling-load-test-tricks-and-debug.html
