### ISSUE TITLE
HTTP: SignatureCalculator, a request log doesn't have added entities

### ISSUE THREAD

**Issue by Amerousful** [gatling/gatling#4498]
**Version**: 3.10.2

**Code**:
```scala
  val protocol: Protocol = http
    .baseUrl("https://httpbin.org")
    .sign { (request, session) =>
      request.getHeaders.add("qwerty", "3.10.2")
      request
    }

  val request = http("get request")
    .get("/get")
```
***

There isn't the added header in the block `header:`
**Log**:
```
19:00:29.855 [TRACE] i.g.h.e.r.DefaultStatsProcessor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
get request: OK 
=========================
Session:
Session(Example scenario,1,HashMap(gatling.http.cache.baseUrl -> https://httpbin.org, gatling.http.cache.dns -> io.gatling.http.resolver.ShufflingNameResolver@21310af4, baseUrl -> https://httpbin.org, simulation -> example, gatling.http.ssl.sslContexts -> io.gatling.http.util.SslContexts@6a3bab69),OK,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$668/0x000000080074a040@15d7aa61,io.netty.channel.nio.NioEventLoop@3d98d138)
=========================
HTTP request:
GET https://httpbin.org/get
headers:
	accept: */*
	host: httpbin.org                  <-------- absent the header
=========================
HTTP response:
version:
	HTTP/1.1
status:
	200 OK
headers:
	Date: Tue, 19 Dec 2023 17:00:29 GMT
	Content-Type: application/json
	Content-Length: 245
	Connection: keep-alive
	Server: gunicorn/19.9.0
	Access-Control-Allow-Origin: *
	Access-Control-Allow-Credentials: true

body:
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "Qwerty": "3.10.2",                             
    "X-Amzn-Trace-Id": "Root=1-6581cc2d-408585e220f4f46067a650f9"
  }, 
  "origin": "...", 
  "url": "https://httpbin.org/get"
}
```

**Comment by Amerousful** [comment]
Hi, I'm back with the new details.
`io.gatling.http.client.Request#copyWithCopiedHeaders` creates a new header object using `copy`, whereas `StatsProcessor` uses the old/previous header object. 

[commit](https://github.com/gatling/gatling/commit/ee259bee9d598e9e36422960185d12de00c80ac3#diff-3a11f35b3ee47a462d2ad6caa84230358abcdb6151655f41d487c2482ee86a4eR96)

<img width="1512" alt="image 1360" src="https://github.com/gatling/gatling/assets/22199881/6b870c15-7db6-450e-9a38-940da2ae099f">
<img width="1085" alt="image 1361" src="https://github.com/gatling/gatling/assets/22199881/862790db-3990-4514-8969-4cab8c0f689f">
<img width="1512" alt="image 1363" src="https://github.com/gatling/gatling/assets/22199881/4ba4770b-0031-43e3-b826-b01c963f475e">

**Comment by slandelle** [comment]
I don't think this can be fixed for now. We will probably need to revisit the way our HTTP client is integrated.

**Comment by Amerousful** [comment]
Sure. It definitely is. I suffered a little bit while debugging, trying to figure out what was going on.
