### ISSUE TITLE
Missing `assertions.json` file after update into to version: >=3.10.0 

### ISSUE THREAD

**Issue by patrykks** [gatling/gatling#4500]
After updating Gatling (Gradle Gatling Plugin - 'io.gatling.gradle') to version: 3.10.0 in gatling report (gatling artifacts file) there is missing `assertions.json` file. Before update report was containing following files:

* build/reports/gatling/app/js/assertions.json
* build/reports/gatling/app/js/assertions.xml

But after change there is only single file assertions.xml (assertions.json) is missing

* build/reports/gatling/app/js/assertions.xml

I tried to find information about this change in release notes but I didn't manage to find anything about it. Is is expected change? If so does exists any way to restore generating `assertions.json` file (for example by modyfying Gatling simulation source code)? If this is not expected is it possible to restore old format of gatling report?

**Comment by slandelle** [comment]
This change is intended.
This file was never a publicly documented feature nor used internally in any Gatling official components.

**Comment by AnskCat** [comment]
Previously I was heavily using `assertions.xml` to reflect test/assertion statuses on Test report in AzureDevOps pipelines (as ADO can parse it as Junit results).  I guess same happening in other CI solutions. Without having access to `assertions.xml` it can be limit results visualisation. 
If there will be enough official plugins, issue can be eliminated.

**Comment by slandelle** [comment]
There's a wide range of official CI solutions plugins and integrations for Gatling Enterprise, including [AzureDevOps pipelines](https://gatling.io/docs/enterprise/cloud/reference/plugins/azure_devops/).
There won't be any new free ones.

**Comment by jonhattan** [comment]
> This file was never a publicly documented feature nor used internally in any Gatling official components.

@slandelle indeed it was documented at https://gatling.io/docs/gatling/reference/current/core/assertions/#reports

It is a mess to lose features we rely on overnight.

**Comment by slandelle** [comment]
You're right, this was indeed documented.

Unfortunately, it was generating extra maintenance burden for us, while not serving any purpose in any official Gatling component, neither open-source nor Enterprise.

I've updated the documentation accordingly.

Regards
