### ISSUE TITLE
Reports: Missing Gatling logo

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4501]
Gatling: 3.10.2
OS: Windows 10 Pro
JDK: 21+35-LTS-2513

Screen:
![image](https://github.com/gatling/gatling/assets/30750006/6647ffdc-64e6-4436-a73e-5d9f8cc28e5e)

**Comment by slandelle** [comment]
Hello @gemiusz
This is already fixed in 3.10.3, see https://github.com/gatling/gatling/issues/4499
