### ISSUE TITLE
Reports: White background in "Dark reports"

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4502]
Gatling: 3.10.2
OS: Windows 10 Pro
JDK: 21+35-LTS-2513

Background should be "dark" too.

Additionally when hover on element background should be in color so hovered text should be visible.

Screen:
![image](https://github.com/gatling/gatling/assets/30750006/8f69200d-586b-4b21-8871-7ff0a65e0ee6)

**Comment by slandelle** [comment]
Hello @gemiusz 
This is already fixed in 3.10.3, see #4499
