### ISSUE TITLE
Core: Console output not respect utcDateTime = true - always show System time.

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4504]
Gatling: 3.10.3 Bundle
OS: Windows 10 Pro
JDK: 21+35-LTS-2513

Screen:
![image](https://github.com/gatling/gatling/assets/30750006/3dae82e6-c2cb-43ae-b4d6-62bf6b70a8b0)

![image](https://github.com/gatling/gatling/assets/30750006/41f64c5b-8e58-40d4-864e-ca744d893ee5)

**Comment by slandelle** [comment]
I was originally not in favor of this change, but you're right, for consistency reasons we should do it.
Thanks for your feedback!
