### ISSUE TITLE
Core: writePeriod config should inject values <= 0

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4505]
Gatling: 3.10.3 Bundle
OS: Windows 10 Pro
JDK: 21+35-LTS-2513

Screen:
![image](https://github.com/gatling/gatling/assets/30750006/d80b6134-9e63-40e6-a8e4-8ffb690f5a2b)
![image](https://github.com/gatling/gatling/assets/30750006/622f58ed-e4f9-4683-a780-fd1f38bce681)

**Comment by slandelle** [comment]
Thanks for the suggestion
