### ISSUE TITLE
Where is the 3.10.3 version of gatling-commons-shared?

### ISSUE THREAD

**Issue by mcanlas** [gatling/gatling#4511]
Was going through an automated upgrade of dependencies and I noticed that 3.10.3 was released but not for this specific artifact. What is the reason why?

**Comment by slandelle** [comment]
Hi,

The only library you should explicitly depend on is `io.gatling.highcharts:gatling-charts-highcharts`.
The other ones should be pulled transitively and are an implementation detail.
The way we organize our internal modules and how we refactor things shouldn't be a concern for you as an end user.

**Comment by slandelle** [comment]
Note: for questions, please use our [community forum](https://community.gatling.io/), not our bugtracker.
