### ISSUE TITLE
How to run Karate feature file via Java DSL ?

### ISSUE THREAD

**Issue by fingerdancer** [gatling/gatling#4541]
It seems that we can run karate feature file according to this link https://karatelabs.github.io/karate/karate-gatling/
The below is an Scala example. How to use Java DSL to call karate feature file ? 

import com.intuit.karate.gatling.PreDef._
import io.gatling.core.Predef._
import scala.concurrent.duration._

class CatsSimulation extends Simulation {

  val protocol = karateProtocol(
    "/cats/{id}" -> Nil,
    "/cats" -> pauseFor("get" -> 15, "post" -> 25)
  )

  protocol.nameResolver = (req, ctx) => req.getHeader("karate-name")
  protocol.runner.karateEnv("perf")

  val create = scenario("create").exec(karateFeature("classpath:mock/cats-create.feature"))
  val delete = scenario("delete").exec(karateFeature("classpath:mock/cats-delete.feature@name=delete"))

  setUp(
    create.inject(rampUsers(10) during (5 seconds)).protocols(protocol),
    delete.inject(rampUsers(5) during (5 seconds)).protocols(protocol)
  )

}

**Comment by slandelle** [comment]
karate-gatling is not a Gatling component but a Karate one, so it’s not supported here.
Moreover, we recommend against using it as it doesn’t make the load generated by Gatling’s genuine HTTP component but by Karate itself so performance is not great.

**Comment by fingerdancer** [comment]
Hi @slandelle , thanks for you reply. So we had better write test scenarios scripts using gating directly,  rather than karate, right ?

**Comment by slandelle** [comment]
Exactly
