### ISSUE TITLE
Too long time of report building

### ISSUE THREAD

**Issue by plokhotnyuk** [gatling/gatling#4543]
These days servers are able to serve hundreds of thousands of requests per second, so that for 1 minute of simulation Gatling spends 10+ minutes for the report building.

I've profiled it with async-profiler and got the following flame-graph for CPU cycles:
![image](https://github.com/gatling/gatling/assets/890289/e079136b-88a3-4f26-b4ef-4f9f23f43f29)

So it seems that it uses 1 CPU thread and most cycles are burned in adding nodes to AVL tree.

**Comment by slandelle** [comment]
Hi,

Sorry but we optimize stats collection and reporting for huge traffic such as yours in Gatling Enterprise, thanks to a completely different stats engine.
We have no plans for optimizing it in the free version.

Regards

**Comment by plokhotnyuk** [comment]
@slandelle Will you accept a contribution for improved reporting speed in the free version?

**Comment by slandelle** [comment]
I'm open to it, but it depends on the scope of the changes.
