### ISSUE TITLE
Bundle: Missing 3.10.5 in Maven Repo 

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4546]
Missing:
[https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.10.5/gatling-charts-highcharts-bundle-3.10.5-bundle.zip](https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.10.5/gatling-charts-highcharts-bundle-3.10.5-bundle.zip)

When:

![image](https://github.com/gatling/gatling/assets/30750006/afea2f09-5eee-4b30-8688-31d912488a87)

Then:

![image](https://github.com/gatling/gatling/assets/30750006/a59b26c7-32e2-421b-a2ef-c507a3147f9e)

**Comment by slandelle** [comment]
Fixed, thanks!
