### ISSUE TITLE
Reports: increasing resolution of rounded up KO percentages

### ISSUE THREAD

**Issue by fingerdancer** [gatling/gatling#4548]
I use gatling Java DSL to do some simulation. it works well but I found that some of my API KO percentage is not correct in the report.  some other API KO percentage is correct, could you please give me some hints ? **The KO number is not zero but the KO percentage is 0%**
The global report as follow
<img width="971" alt="image" src="https://github.com/gatling/gatling/assets/7591115/dbea33e7-bb11-4075-b511-ec07e659063c">

one of the detail report as follow (The KO number is 21)
<img width="1078" alt="image" src="https://github.com/gatling/gatling/assets/7591115/74ed71f6-8409-4837-bc10-bb1d2edfb90a">

**Comment by Isammoc** [comment]
Hi @fingerdancer 

> The KO number is not zero but the KO percentage is 0%

How do you expect that gatling compute the percentage?

By definition, the percentage is `count / total * 100 %`.
For instance, for your "Payment Page(OPF)" line: 
 * `total` is 5000
 * `count` (of KO) is 24

The computation is:
* `count / total * 100 %`
* `24 / 5000 * 100 %`
* `0.0042 * 100 %`
* `0.42 %`

As usual with percentage, gatling rounds them to the nearest integer.
As the value is less than `0.5` the nearest is... `0`
What is effectively displayed in the reports.

So, what is the error exactly?

For any question, I suggest to ask them on our [community forum](https://community.gatling.io/), as the GitHub tracker is only for Bugs and validated Feature Requests.

Cheers!

**Comment by fingerdancer** [comment]
@Isammoc  got it. thanks for you reply, that is to say, if value less than 0.5%, it will be 0%. is it gatling default behavior ? can I let it to show 0.42% througn some configuration ?

**Comment by slandelle** [comment]
Re-opening. I'm investigating displaying doubles with 2 digits.

**Comment by slandelle** [comment]
> I need wait for the future new version which have fixed this issue, right ?

Yes. The next release will be 3.11.0.
