### ISSUE TITLE
Gatling Gradle plugin 3.11.1 with Gradle 8.7 fails with "You must configure the plugin for your language of choice"

### ISSUE THREAD

**Issue by askucins** [gatling/gatling#4557]
Hello,
When I'm trying to use the recent gatling gradle plugin I'm getting this error:

```
An exception occurred applying plugin request [id: 'io.gatling.gradle', version: '3.11.1']
> Failed to apply plugin 'io.gatling.gradle'.
   > You must configure the plugin for your language of choice: java, scala or kotlin.

```
Here is my setup:
* linux
* java 11
* gradle 8.7
* gatling gradle plugin 3.11.1

I don't have problem with my setup when I use the previous version of the gatling plugin - either the 3.10.5 or 3.10.5.1

**Comment by slandelle** [comment]
Have you checked the [upgrade guide](https://docs.gatling.io/release-notes/oss/upgrading/3.10-to-3.11/#upgrading-the-gatling-gradle-plugin-to-3110) before upgrading?

**Comment by askucins** [comment]
Oh, yeah I'm sorry, I must have missed that - I was looking for the error message instead with no luck  - now I see what I'm missing there. Sorry for the false alarm. It's works much better with explicitly passed `id java`
Thanks!

**Comment by slandelle** [comment]
Glad you could make it work!
