### ISSUE TITLE
Graphite reporter initial onFlush inconsistently receives empty data leading to a lower reported request count than the actual test run performed 

### ISSUE THREAD

**Issue by jgoldring** [gatling/gatling#4563]
This has been tested using 3.9.5 and 3.11.2

When configuring Gatling to use the built-in Graphite reporter there appears to be an inconsistency between the reported request count and what is passed through the Graphite reporter. I setup a local Telegraf/Influx image to receive the data, and configured Gatling as follows:

```
    graphite {
      light = false              # only send the all* stats
      host = "localhost"         # The host where the Carbon server is located
      port = 8094               # The port to which the Carbon server listens to (2003 is default for plaintext, 2004 is default for pickle)
      protocol = "tcp"           # The protocol used to send data to Carbon (currently supported : "tcp", "udp")
      rootPathPrefix = ${?GATLING_ROOT_PATH_PREFIX} # The common prefix of all metrics sent to Graphite
      bufferSize = 8192          # Internal data buffer size, in bytes
      writePeriod = 1            # Write period, in seconds
    }
```

While querying Influx I noticed that the request count occasionally differed from the reported request count in the terminal post-test run, and when it differed it was always either 2 or 4 fewer requests counted in Influx.

I did a simple log check in the `onFlush` method in `GraphiteDataWriter.scala` and whenever the request count is off, the initial onFlush has empty requestMetrics data.

For example, test run report via the console:
![Screenshot 2024-05-14 at 1 09 10 PM](https://github.com/gatling/gatling/assets/3430378/6934f4d9-a7ca-4b0c-a017-79d96241be86)

Influx request data:
![Screenshot 2024-05-14 at 1 09 42 PM](https://github.com/gatling/gatling/assets/3430378/65f84842-1398-4433-b5da-43b9435219b5)

The initial data being empty I believe leads to the missing 2 - 4 requests, as every subsequent onFlush has data, and I can't see what causes this apparent race condition.

**Comment by slandelle** [comment]
This component was a contribution that has been buggy for years, with no community member interested in contributing a fix.
Moreover, nowadays, the official solution to have real time reporting is Gatling Enterprise.

As a result, it was deprecated for removal in the next release (3.12) and is already no longer documented.

**Comment by jgoldring** [comment]
Ah I didn't realize it was slated for deprecation, thanks for the heads up!

**Comment by asisgrover** [comment]
We would be happy to provide you with the demo of Gatling Enterprise to show you the real time reporting feature and how it can help you.

Would you be open for that ?
