### ISSUE TITLE
RequestReply not working in latest version 3.11.2

### ISSUE THREAD

**Issue by SomeshK4** [gatling/gatling#4564]
It hangs while using request reply . Seems like somehow not able to receive message and always in the waiting mode.

`public class PaymentRequestJmsSimulation extends Simulation {

    Logger log = LoggerFactory.getLogger(PaymentRequestJmsSimulation.class);

    ConnectionFactory connectionFactory =
            new org.apache.activemq.ActiveMQConnectionFactory("tcp://localhost:61616");

    String correlationId = UUID.randomUUID().toString();
    JmsProtocolBuilder jmsProtocol =
            jms.connectionFactory(connectionFactory)
                    .credentials("admin", "secret")
                    .replyTimeout(30000)
                    .usePersistentDeliveryMode();

    ScenarioBuilder scn =
            scenario("JMS DSL test")
                    .repeat(1)
                    .on(
                            exec(
                                    jms("Pain013 Message")
                                            .requestReply()
                                            .queue("rtp.pain013.in")
                                            .replyQueue("rtp.pain013.acks")
                                            .textMessage(Pain013MessageFixture.PAIN_013_MESSAGE)
                                            .property("jms_correlationId", correlationId)
                                            .check(simpleCheck(this::checkBodyTextCorrect))));

    // with pain013
    // xml message

    {
        setUp(scn.injectOpen(rampUsers(1).during(5))).protocols(jmsProtocol);
    }

    public boolean checkBodyTextCorrect(Message m) {
        // this assumes that the service just does an "uppercase" transform on the text
        if (m instanceof TextMessage) {
            try {
                return m.getJMSCorrelationID().equals(correlationId);
            } catch (JMSException e) {
                throw new RuntimeException(e);
            }
        } else {
            return false;
        }
    }
}`

**Comment by slandelle** [comment]
The [JMS CorrelationID](https://docs.oracle.com/cd/E13171_01/alsb/docs25/interopjms/MsgIDPatternforJMS.html) is not a property named `jms_correlationId`. You should let your application set it.
Also, here, you're correlationId is a constant.

Please use the community forum when asking for help on test crafting, not the bug tracker.
