### ISSUE TITLE
Private `class JsonParsers` broke checks in third parties plugins

### ISSUE THREAD

**Issue by jigarkhwar** [gatling/gatling#4569]
Hi, in the last [commit](https://github.com/gatling/gatling/commit/421885ba8a31d8c66b1adf373bcf53713a4cde19#diff-3bb9ff3d5af3d94e94488ab42e73af026285f2e700d361522ff6955f5c4b9c64R30) you made the `class JsonParsers` private and this change breaks our opportunity to support json checks in plugins in the gatling way. 

May we revert this changes?

affected repos:
https://github.com/galax-io/gatling-kafka-plugin/blob/132be41fb75652c9111452f4aaca4fec967cca8c/src/main/scala/org/galaxio/gatling/kafka/checks/KafkaCheckSupport.scala#L66
https://github.com/galax-io/gatling-amqp-plugin/blob/1accec7652e804f3fec8397b80ea3c0e01c9e43c/src/main/scala/org/galaxio/gatling/amqp/checks/AmqpCheckMaterializer.scala#L37
https://github.com/Amerousful/gatling-kafka/blob/4b79dcf7d14ff0b69d4940f4824c5c59aa06a9bc/src/main/scala/io/github/amerousful/kafka/check/KafkaCheckMaterializer.scala#L40

**Comment by slandelle** [comment]
Hi,

My bad
