### ISSUE TITLE
JMS: Support checks on JMS properties

### ISSUE THREAD

**Issue by VitalyShalaev** [gatling/gatling#4574]
My scenario involves a chain of calls to receive messages and it is necessary to check and reuse headers from previous responses.

**Comment by slandelle** [comment]
Are you interested in contributing this feature?

**Comment by VitalyShalaev** [comment]
I'm not sure I can do it yet

**Comment by slandelle** [comment]
Either that or your company can sponsor the development.

**Comment by sami355-24** [comment]
Hi, I've had a similar experience in the past when I used gatling

My scenario was also tested by putting the response value to the first request as a header to the second request.
However, when I sent a request above a certain level, there was a problem that some requests did not set the value correctly in the header.

So, if you don't mind, I'd like to contribute on the issue.

**Comment by slandelle** [comment]
@sami355-24 Sure, feel free to give it a try! Thanks!
