### ISSUE TITLE
HTTP: Gatling should send secure cookies to "localhost" as well

### ISSUE THREAD

**Issue by ahus1** [gatling/gatling#4578]
The spec: The W3C specs describe that secure context are those of https URLs, but also localhost and some others. 
https://w3c.github.io/webappsec-secure-contexts/#algorithms. Cookies marked as secure are sent to a secure context.

The expected behavior: When I run a Gatling test against `http://localhost:8000`, I expect Gatling to send secure cookies to the server.

Actual behavior: The current code only considers URLs starting with "https://" as a secure. 

https://github.com/gatling/gatling/blob/ad01135d2849a508d3a388a2dee9d405e4ac1ded/gatling-http-client/src/main/java/io/gatling/http/client/uri/Uri.java#L79

https://github.com/gatling/gatling/blob/610f0b6bcc7b226d98a1162dcc37b2f0d8ab1f44/gatling-http/src/main/scala/io/gatling/http/cookie/CookieJar.scala#L121-L127

In comarison, this is the logic Keycloak implemented recently around this to identify a secure context: https://github.com/keycloak/keycloak/blob/310824cc2b17eed2a48e93d7275efb4163cc9f6e/services/src/main/java/org/keycloak/cookie/SecureContextResolver.java

### With a browser like a Chrome 127 (both expected and observed behavior): 

* Prepare a server that sends Secure cookies: The included example sends a secure cookie to the browser in every request. Run with JDK 21 and a command `java CookieServer.java`.
* Open the URL in the browser. The first request does not send a in the  a cookie yet to it prints "Cookie Missing"
* Hit "refresh" to send another request to the sever. This second request contains the cookie, so it prints "Cookie Received".

### With Gatling: 

Expected behavior: First response is 400 / Cookie Missing, the second 200 / Cookie Received as it received the cookie

Actual behavior: The first and the second response are 400 / Cookie Missing (tested with Gatling 3.11.5 and the gatling-maven-plugin-demo-java-main project):

Prepare a server that sends Secure cookies: The included example sends a secure cookie to the browser in every request.
Run with JDK 21 and a command `java CookieServer.java`.

```
// CookieServer.java
public class CookieServer {

    public static void main(String[] args) throws Exception {
        HttpServer server = HttpServer.create(new InetSocketAddress(8000), 0);
        server.createContext("/", new Cookie());
        server.setExecutor(null);
        server.start();
        System.out.println("Server listening on port 8000");
    }

    static class Cookie implements HttpHandler {
        @Override
        public void handle(HttpExchange t) throws IOException {
            String response;
            int result;
            List<String> cookies = t.getRequestHeaders().get("Cookie");
            if (cookies != null && cookies.stream().anyMatch(s -> s.contains("mycookie=value"))) {
                response = "Cookie Received";
                result = 200;
            } else {
                response = "Cookie Missing";
                result = 400;
            }
            t.getResponseHeaders().put("Set-Cookie", List.of("mycookie=value; SameSite=None; Secure"));
            t.sendResponseHeaders(result, response.length());
            OutputStream os = t.getResponseBody();
            os.write(response.getBytes());
            os.close();
        }
    }
}

```

The scenario:

```
package computerdatabase;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;

/**
 * This sample is based on our official tutorials:
 * <ul>
 *   <li><a href="https://gatling.io/docs/gatling/tutorials/quickstart">Gatling quickstart tutorial</a>
 *   <li><a href="https://gatling.io/docs/gatling/tutorials/advanced">Gatling advanced tutorial</a>
 * </ul>
 */
public class CookieSimulation extends Simulation {

    ChainBuilder noCookieYet = exec(
        http("FirstRequestNoCookie").get("/")
                .check(status().is(400))
    );

    ChainBuilder withCookieSet = exec(
            http("SecondRequestWithCookie").get("/")
                    .check(status().is(200))
    );

    HttpProtocolBuilder httpProtocol =
        http.baseUrl("http://localhost:8000");

    ScenarioBuilder users = scenario("Users").exec(noCookieYet, withCookieSet);

    {
        setUp(
            users.injectOpen(rampUsers(1).during(10))
        ).protocols(httpProtocol);
    }
}

```

The output: 

```
> Global                                                   (OK=1      KO=1     )
> FirstRequestNoCookie                                     (OK=1      KO=0     )
> SecondRequestWithCookie                                  (OK=0      KO=1     )
```

**Comment by slandelle** [comment]
> The expected behavior: When I run a Gatling test against https://localhost:8000, I expect Gatling to send secure cookies to the server.

I guess you have a typo here and you actually mean `http://localhost:8000`, right?

**Comment by ahus1** [comment]
> I guess you have a typo here and you actually mean `http://localhost:8000`, right?

Correct - stupid mistake on my side. I fixed it in the description above. Sorry for the confusion.

**Comment by ahus1** [comment]
Thank you for merging the fix. I see this is now scheduled for 3.12.0 - is the an ETA for that release? I didn't see a date attached to the milestone in GitHub. We have a workaround, but it is a bit annoying (connecting to 0.0.0.0 instead of 127.0.01). 
Thanks again!

**Comment by slandelle** [comment]
We're waiting for the next Netty release that will ship a feature we're contributed.
