### ISSUE TITLE
Graphite support being dropped?

### ISSUE THREAD

**Issue by ma-ts** [gatling/gatling#4583]
Hi Gatling team,

From recent commits I can see Graphite support being dropped in 3.12? Can someone elaborate what the rationale is behind that? For us, it is the only way to have metrics written for long-term storage. 

https://github.com/gatling/gatling/commit/d4375d832b00950322c29c11a68b268c3b1a0c37 is the commit that refers to a 'Deprecated Graphite configuration'

**Comment by slandelle** [comment]
Hi,

Please use the [community forum ](https://community.gatling.io/) for questions, not the bug tracker.
