### ISSUE TITLE
Logback and Akka issue with latest gatling-maven-plugin 

### ISSUE THREAD

**Issue by politrons** [gatling/gatling#4584]
Hi all,

Since we upgrade the plugin version from `4.0.0` to `4.9.6`, and libraries to `3.11.0`, now when we run a simulation we have a weird error related with logback and Akka actors.

I'm trying to figure the issue but I cannot find a similar issue opened. 

It would be great if you provide some support.

Unfortunately I cannot provide stack trace errors since this is happening in my company and I cannot open the issue there, or share any code into my local computer.

Some of the logs that I see is

`Logger log1-slf4Logger did not respond with LoggerInitialized, sent instead. [TIMEOUT]
`

`java.lang.NoSuchMethodError: akka.actor.ExtendedActorSystem.uid()J
`

**Comment by slandelle** [comment]
I suspect you have multiple akka modules in your classpath with different and incompatible versions.

**Comment by politrons** [comment]
Yes, you were right, thanks a lot!, closing ticket!
