### ISSUE TITLE
.from(int) and .to(int) in csv feeder (and tsv, ssv) ?

### ISSUE THREAD

**Issue by nptri** [gatling/gatling#4589]
Hi, I have a use case where I have a csv record of around 5k data in a single file and needed to push a certain part of data to each separate scenario, is it possible to have a ```.from(int rowNumber)``` and ```.to(int rowNumber)``` to quickly push the data ?
My pseudo-code, I think: 
```
val csvFill = csv("my/dir/to/file.csv)
                    .circular //can be looped in range defined
                    .from(rowNumber = 1)
                    .to(rowNumber = 1000)
```
Currently workaround is to separate csv into smaller files and feed to each scenario, but it's not really good in time aspect.

**Comment by slandelle** [comment]
What you’ve explained is not a use case, it’s a solution you can think of. Why do you need this exactly?

If your actual goal is just to make sure the virtual users of the different scenarios don’t use the same data, you can simply share a single feeder instance.

I’m not fond of the feature as I have a feeling it won’t play nicely with Gatling Enterprise’s shard.

**Comment by nptri** [comment]
Hi @slandelle 
The reason of needing this is to reduce the time to prepare test data, so instead of separating into smaller files for each scenario, user can decide right on one single csv file at which part of data can be passed.
-
Take my case as an example with sample csvFile content:
```
column1, column2, conditionData
data1, data_1, condition1
data2, data_2, condition2
...
data5000, data_5000, condition
```
I have 5 scenarios, one single csv file with 5000 data rows, each scenario I have to pass 1000 data directly into it based on the **conditionData** column.
So to fulfill my need to pass 1000 data into each scenario, I have to take that 5000 data file, manually split it into 5 csv files, each has 1000 data with satisfy condition, it would be taking some time to do it.

> If your actual goal is just to make sure the virtual users of the different scenarios don’t use the same data, you can simply share a single feeder instance.
It was not actually about unique data, but rather affected by a condition that will put V.U into different scenario.

I hope this explanation is cleared enough

**Comment by slandelle** [comment]
The easiest way, as long as your data is not humongous and can fit in memory, is to load all the records and filter them based on your conditionData.
See https://docs.gatling.io/reference/script/core/session/feeders/#read-records
