### ISSUE TITLE
Core: Info log in Workload doesn't properly print the scenario name

### ISSUE THREAD

**Issue by cleliofs** [gatling/gatling#4590]
**Please don't post questions here but use our [community forum](https://community.gatling.io/) instead.**

For bugs, please: 
  1. upgrade to the latest Gatling release
  2. search this bugtracker and check if your issue hasn't been already reported
  3. provide a Short, Self Contained, Correct (Compilable), Example (see http://sscce.org/)

For feature requests, please:
  * explain your use case, not the implementation you have in mind.

**Comment by cleliofs** [comment]
One example of the object reference is in: `io.gatling.core.controller.inject.Workload`
```
 logger.info(s"Scenario $scenario has finished injecting")
 ```

**Comment by slandelle** [comment]
Thanks for reporting. The log you mentioned is the only place I could find where we're trying to print the Scenario instance instead of its name. I've fixed it.
