### ISSUE TITLE
Gatling 3.12.0 problems with multiple logs and reportsOnly option

### ISSUE THREAD

**Issue by besessener** [gatling/gatling#4591]
Until Gatling Version 3.11.5 I was able to run `mvn gatling:test -Dgatling.reportsOnly=mysimulation` where `mysimulation` contained multiple log files. From my perspective all log files have been consodered for creating a report.

Now with `3.12` it fails with an error, as did does not find a file named `simulation.log`. Naming one of the files will succeed the command, but as expected only parse one file, not all.

I have a minimum example, it comes without code, only 2 log files. It is configured for Gatling 3.12, by changing the version it will start working again.
[example.zip](https://github.com/user-attachments/files/17258962/example.zip)

**Comment by slandelle** [comment]
Hi,

Sorry but that's something we don't intend to support. Distributed tests are featured in Gatling Enterprise.

**Comment by besessener** [comment]
@slandelle so it was a bug it was working before then? Could you please mention this in the release notes then? Or did I miss it? I am pretty sure this has impact to some users other than me.

**Comment by besessener** [comment]
https://github.com/gatling/gatling/blob/3.9/src/docs/content/guides/scaling_out/index.md#scaling-out-with-gatling-open-source 
Seems like it used to be supported also in the open source edition....now the on recent branches/releases also the docs are gone. I am a bit disappointed :(

**Comment by saviour123** [comment]
The best solution now is to downgrade. 3.11.5 if you are on opensource, this would this allow you to run distributed report.
