### ISSUE TITLE
Feature request : InfluxDB 3.0 integration

### ISSUE THREAD

**Issue by suyashcjoshi** [gatling/gatling#4594]
Please consider adding integration with InfluxDB 3.0 (cloud) for storing metrics as it's a popular use case. Thanks!

**Comment by slandelle** [comment]
Hi,

We do have some plan to develop integrations with external datastores.
However, these integrations will only be developed for Gatling Enterprise, not the free version.

If you wish, you can fill a feature request for InfluxDB there so it helps us building our roadmap: https://portal.productboard.com/gatling/1-gatling-roadmap/tabs/1-ideas/submit-idea

Cheers
