### ISSUE TITLE
Check is alert(s) present

### ISSUE THREAD

**Issue by 4FunAndProfit** [gatling/gatling#4597]
Hello!

I love your tool it is amazing for load test 

Yet on my load charge, I have to verify and check that an alert (or maybe multiple) is present and executed on browser side

I know it is possible in selenium but I do love Gatling and I want to stay in gatling haha 

Is it possible to add a check like in selenium to check if alert is present?

Or if possible now is it possible to check with dsl that an alert is present (regex is not enough because we don't know if it is really or not executed in browser)

**Comment by slandelle** [comment]
Gatling doesn't execute web browsers. Think of it as a rich HTTP client (when it comes to HTTP load testing).
So you can't test the presence of the alert, you must test the condition that triggers the alert, probably coming from some information in some HTTP response payload.

Important note: for question, please use our community forum: https://community.gatling.io/
