### ISSUE TITLE
Silent by scenario

### ISSUE THREAD

**Issue by nptri** [gatling/gatling#4601]
**Please don't post questions here but use our [community forum](https://community.gatling.io/) instead.**
For feature requests, please:
  * explain your use case, not the implementation you have in mind.

Hi, I have a use case where I need to run a sample set up first, let's say I have a full scenario defined as below
```
setUp(
     sampleSetup
          .andThen(myMainScenario)
)
```
Both ```sampleSetup``` and ```myMainScenario``` share 2 same APIs script, and I don't think I should separate it (for management), but I don't need the first sampleSetup run to be reported since it's run with low request rate, is there any possibilities that we can have a silent for Scenario ?

**Comment by slandelle** [comment]
Please use our [community forum](https://community.gatling.io/) for asking usage questions, not the bugtracker.

**Comment by nptri** [comment]
@slandelle 
I think my question is about request for a new feature, because we have silent for single request, not silent for scenario.
