### ISSUE TITLE
SSE: Last Event Not Consumed

### ISSUE THREAD

**Issue by Asinrus** [gatling/gatling#4602]
I am experiencing an issue with Gatling during Server-Sent Events (SSE) testing when using a proxy based on Spring Cloud Gateway. The issue is that Gatling retrieves all SSE events except the last one, according to the log records and tests. This behavior can be observed in the provided example which demonstrates the interaction between the proxy and Gatling.

Tests:  
- [Test](https://github.com/Asinrus/gatling-sse-issue/blob/master/src/gatling/java/sse/simulation/SimulationWithoutProblem.java) with consuming last event. Wiremock produces [file](https://github.com/Asinrus/gatling-sse-issue/blob/master/compose/wiremock/__files/sse_events_body.txt)
- [Test](https://github.com/Asinrus/gatling-sse-issue/blob/master/src/gatling/java/sse/simulation/SimulationWithProblem.java) without consuming the last event. Wiremock produces [file](https://github.com/Asinrus/gatling-sse-issue/blob/master/compose/wiremock/__files/sse_events_body_without_final_event.txt)

I see that the proxy consumes the full data and puts it on the network. (according the log)

Expected Result:

- Confirmation that Gatling reads everything from the network socket and the issue lies within my example.
- Alternatively, clarification if this is unexpected behavior from Gatling's side and whether it requires a specific event to stop processing.

Link to Example app: https://github.com/Asinrus/gatling-sse-issue
There you can find the [instruction](https://github.com/Asinrus/gatling-sse-issue) on how to reproduce this behaviour and run the environment.

Additional info:
Laptop: Macbook Pro M1 
OS: 15.1 (24B83)

**Comment by slandelle** [comment]
It looks to me that your stream is malformed.

As per the [SSE specification](https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream):

> event         = *( comment / field ) end-of-line

Your last event is missing the end-of-line.

**Comment by AOsheev-Collibra** [comment]
@slandelle , thank you for your help 
It is a really problem with `end-of-line`
