### ISSUE TITLE
Ability to generate csv file with aggregated results

### ISSUE THREAD

**Issue by fdrouet** [gatling/gatling#593]
Today, Gatling generate only an html report with some computed numbers and mostly with Charts.
I need to gather most of the computed numbers of several runs to put it in another tool (a spreadsheet for exemple) for historization but mostly to be able to compare different runs results.

Today, doing such things is very painful (copy/past from orange box statistics)  or impossible (all computed numbers in graphics)

Could you provide some configuration parameters to generate raw computed numbers in a format like csv ?

Your current html report is cool but clearly insufficient for more advanced usage.

Thanks in advance

**Comment by swapnil-kotwal-sp** [comment]
Somebody please have a look at our questions here ?

I'm not able to find way to export Gatling results.log file to CSV

thttp://stackoverflow.com/questions/29115408/how-to-export-to-csv-a-gatling-log-file

**Comment by slandelle** [comment]
This was dropped. There's a JSON file instead.

**Comment by chittuvtu** [comment]
> @fdrouet I've finished implemented this feature. Here's what the CSV looks like: https://gist.github.com/3057077. Feedback welcomed.

Can you please tell me the steps on how to retrieve the CSV raw data from Gatling report. Above link is not working.
