### ISSUE TITLE
Misc: MongoDB support

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#921]
http://reactivemongo.org or low level JSON?

**Comment by slandelle** [comment]
No community demand

**Comment by zafarella** [comment]
there is a demand actually, would be really handy.. thanks

**Comment by slandelle** [comment]
@zafarella Sorry, but your single demand is not sufficient to make this a priority for us.

We would either need:
* tons of demands from our users
* contributions
* a sponsorship contract
